code/modules/mob/living/carbon/human/species/station/station.dm
Fixes Kazkin's typo, allowing Mar'Qua to select their dedicated hairstyles.
=> Sneaky PR for Sneaky Boys

code/game/objects/items/weapons/shields.dm
No idea why the fuck this wasn't done before
Does exactly what the title says, no idea why these weren't used. they're in the lefthand and righthand files too so :shrug:
:cl:
added item_state to buckler
added item_state to tray shield
/:cl:
=> Adds item states to shields that have their individual sprites

code/modules/mob/living/carbon/human/update_icons.dm
<details>
<summary>
copy_overlays(a.get_mob_overlay()) was being erroneously used to try to attach uniform accessory overlays to mobs. 
as copy_overlays() looked for overlays in a target atom and get_mob_overlay() returns an image, this meant copy_overlays() retrieved nothing.
switched it to use add_overlay(a.get_mob_overlay()) instead
you can now wear scarves again
</summary>
<hr>
<hr>
</details>
:cl: 
fix: accessory overlays now display properly
/:cl:
=> scarves work again

code/modules/mob/living/carbon/superior_animal/roach/life.dm
This is really unforgiving well trying to get someone when on lower pops, and getting lost.
I think and after first and seeing a failer to save someone that died in a basic area and got DNR it should be upped to give people time. Imagine dieing in a coroner and a basic roach eat the body do to sci/med unable to fine them is just not fun to deal with by any party 
:cl:
balance: Ups Roaches timer to eat bodys from 5 mins to 15mins to give us time to eat the body
/:cl:
=> Roaches now wait 15 mins to DNR rather then 5

code/modules/reagents/reagents/dispenser.dm, code/modules/reagents/reagents/nanites.dm
Cht'mants when eating or injecting METAL or nanite based chems will have increased negative affects
For basic metal it will be small toxic harm, nothing to bad unless you never heal yourself or start guzzling down all 12 metals at once and then inject them - So not an issue
For nanites - they drain more blood, cant heal toxic damage and deal a small amount of toxic damage, nothing a little bit of anti-toxin and sugar cant fix!
:cl:
add: Cht'mants as pre lore dislike metals and will take really low amounts of toxic damage form them if injected or eaten. Nanites for cht'mants only will no longer heal toxins, and take even more blood then normal. Nanites only for Cht'mants will deal increased toxic damage in all cases.
/:cl:
=> Cht'mants now take toxic damage from metals and nanites

code/modules/research/rdmachines.dm
Makes it so the printer in Rnd can use biomatter to make things like kits and goggles for people and the church when trading for things...
:cl:
fix: Rnd can now use biomatter to print things that they need biomatter for
/:cl:
=> Fixes Rnd printer being unable to use biomatter

code/modules/reagents/reagent_containers/food/snacks.dm
Replaces the more oddly added chems into crackers/coco bars with better stuff
Lowers the amout of healing power in MRE's 
:cl:
tweak: Replaces serotrotium in moral bar with coco powerder
tweak: replaces iron in MREs with Salt, and lower trico when heated
balance: Crackers now have salt and normal dex rther then steady and dex+
balance: Lowers chems in nutrient paste
/:cl:
=> Nerfs ERPs

code/modules/stashes/stash_types/captain.dm, code/modules/stashes/stash_types/excelsior.dm, code/modules/stashes/stash_types/ninja.dm, code/modules/stashes/stash_types/valueables.dm
Captains stash no longer gets a nuke disk
Ninja stash now can get
Weaker then basic chem dispender for rigs
Katana
Warlock Wine
Upto 3 cam bugs
A silencer
A fancy pen!
Weath/Money Stash 
No longer has TC
No longer has a bag of broken coins
Excelsior Stash
It can now spawn Excelsior handguns and vintorez 
It can now also spawn Excelsior stock parts and cells
:cl:
/:cl:
=> Rebalances and tweaks some stashes

code/modules/reagents/reagents/medicine.dm, code/modules/reagents/reagents/toxins.dm
All changes ONLY effect Cht'mants.
Diplopterum, acts as Dexalin.
Seligitillin acts as Kelotane
Starkellin acts as Bicaradine
Gewaltine acts as Dylovene
Fuhrerole acts as Peridaxon
Blattedin still acts as Tricordrazine.
Dexalin, Kelotane, Tricordrazine and Peridaxon now do NOTHING to
Cht'mants. Dermaline and Dexalin plus still do the same thing they do for everyone.
Bicarardine heals for half as much brute damage as it does for others. Dylo remains untouched.
Alkysine and Imidazoline will still treat brain and eye damage as normal.
All roach chems have no od limit for cht'mants, and are not addictive or toxic to them. (or at least i hope this is my first code attempt ever and I tested alot but probably messed up some where) 
<details>
<summary>
</summary>
<hr>
<hr> …
=> Chem changes for Cht'mants

code/modules/research/experiment.dm
Raises the points you get for most things other then bluespace/illegal tech to help make the two not the epic meme stuff that you shoot for all at once to max RnD without wanting to wast time/mats on other techs
:cl:
balance: RnD points from levels is a small bit easyer. Meaning Rng and illegal tech are no longer the way to go
/:cl:
=> Buffs RnD points form things outside of bluespace/illegal tech

code/game/objects/items/weapons/shields.dm
Riot shields now block bean bag shots
Riot shields are also now able to block lasers normally if they deal less then 16 damage - theirs not a single laser that does that iirc
Corrects some code side commits
:cl:
/:cl:
=> Shield buffs

code/modules/reagents/machinery/chem_dispenser.dm, maps/encounters/deeptunnels/_Nadezhda_Deep_Tunnels.dmm
Really easy mistake to make, simply just an op dispender being named something like /med
confusing eris stuff is confusing
:cl:
/:cl:
=> removes admin dispender in sci underground

code/game/machinery/cryo.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/core_implant/cruciform/rituals/priest.dm, code/modules/reagents/reagent_containers/syringes.dm, code/modules/reagents/reagents/drugs.dm, code/modules/reagents/reagents/medicine.dm, code/modules/reagents/reagents/toxins.dm, code/modules/surgery/old_encased.dm, code/modules/surgery/old_surgery.dm, code/modules/surgery/surgery.dm, code/modules/surgery/wound_repair.dm
-Fixed a typo with the ire litany to describe its cooldown accurately (5 minutes, not 15)
-Fixed an issue with the prayer of reunion with a pathing typo. It now works just fine.
-Many drugs and toxins can now be scanned and detected by scanners.
IMPORTANT! THE NEXT CHANGES VASTLY CHANGE GAMEPLAY
----Wound surgery now subtracts a charge per use when healing someone, for every 15 points of brute or burn healed you lose 1 charge and depending on the targeted body part the game will automatically use 3, 2, or 1 charges based on how many internal organs that area has (groin 3, chest 2, head 1).
----Surgery difficulty has been drastically heightened, non-mechanical surgery now has a 30% lowered success chance, self surgery or operation without being a doctor now have a much higher failure …
=> Medical Rebalance Update.

code/modules/mob/living/simple_animal/hostile/big.dm
More eye QoL/ Mob cheats nerfs makes these frankly massive things camo in full daylight, that has conflicting pallets be see able without needing to use safety squints. Like really, its less about "just get gud" when they already decloak to attack and shit, this just makes it so I dont have eye stain form trying to play the game
Nightmarks aplha is now 80 from, 15
:cl:
/:cl:
=> why do I have to squint to see things?

code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
Makes the spider hunter cloaker 80 aphla rathe rather then 50
being 50 is a bit to hard to see number imo to the point were you cant see one really at all with 100% lighting on the dirt roads or conflicting pallets. Camo only is meant to work if its same-ish. Still really hard to see in most cases in maints and the like but not as much when you have full lighting and the like 
:cl:
/:cl:
=> Makes cloakers a bit less harder on the eyes

code/modules/reagents/reagent_containers/glass/beaker.dm
This but better by adding a 100u option
:cl:
tweak: Beakers and buckets can now transfer 100cubes at a time
/:cl:
=> Transfer units QoL

maps/submaps/dungeon_rooms/exits/1.dmm
End game loot for grayson now has 1 of each super rare admin spawn only (usually) tool augments.
=> Grayson end boss loot

code/datums/armor.dm, code/game/objects/effects/mines.dm, code/game/objects/items/weapons/mine.dm, code/game/objects/random/traps/traps.dm, code/modules/mob/living/simple_animal/hostile/big.dm, code/modules/mob/living/simple_animal/parrot.dm
Fixes mines so they can be better used in traps and allow for more functional use instead of just "X is a hazard". Croaker lords properly open their eyes when they begin search for a target. Armor now doesn't globally update when upgraded, fixing the bug we had.
=> Bugfix Update

code/game/objects/effects/spiders.dm
having to clean up after a spider webber takes like really long for what should be an easy task that adds nothing but bussy work that dosnt feel that rewarding to smack the same thing 3-6 times with a crowbar just to then get a floor tile.
Using a welder takes fuel and damages eyes so why would you ever?
:cl:
/:cl:
=> lower webs health - aka Making clearing spider nests much faster/easyer

code/modules/projectiles/guns/energy/laser.dm
A rail guns still fires projectiles even if the power is from a cell, thus you should be able to add in things like a better barrle
:cl:
/:cl:
=> Rail guns now can have projectile mods added on if wanted

code/datums/outfits/jobs/engineering.dm, code/game/machinery/vending.dm, code/game/objects/items/weapons/autolathe_disk/guild_disks.dm, code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm, code/game/objects/items/weapons/circuitboards/machinery/pacman.dm, code/modules/power/port_gen.dm, code/modules/power/solar.dm, code/modules/research/designs/cell.dm, code/modules/research/designs/circuits.dm, code/modules/research/designs/structures.dm, code/modules/research/nodes/engineering.dm, code/modules/research/nodes/power.dm, code/modules/scrap/scrap_burner.dm
Solars can now be upgraded with glass, each glass type thats more exspestive then the last will give more power and have more health!
Guild techs now have a disk that allows them to make more SMES, coils and pacmans
2 new pacman types Wood based CAMPER(Its funny shut up) Miss uses diamonds(A girls best friend!)
RnD can now make industeral chem dispensers - as well as these new pacmans + diesel ones
diesel generator now has normal stock parts
Maybe fixes a bug with upgrading pacmans to properly state how much power they make
Makes SCRAPMAN pacman ya know... named correctly and tell you the correct fuel type...
:cl:
/:cl:
=> Legit Powergaming

code/modules/organs/internal/_internal.dm, code/modules/reagents/reagent_containers/food/snacks.dm
Another request from SynthNumeric.
Internal organs can be consumed. Weird, but okay.
Double checked to made sure it doesn't break surgery. Once a bite is taken out of the item, it can't be used for surgery anymore.
:cl:
add: Internal organs can now be eaten.
/:cl:
=> Internal organs are edible.

code/modules/modular_computers/file_system/programs/generic/ntnrc_client.dm, html/changelogs/MeghanRossi-RelayChatFix.yml
<details>
<summary>
This fixes a bug where computers and pdas held in a person's hand or inventory slots couldn't see relay chat channels created by computers and pdas lying on the ground and vice versa.
</summary>
</details>
:cl:
fix: Fixed a bug where computers and pdas held in a person's hand or inventory slots couldn't see relay chat channels created by computers and pdas lying on the ground and vice versa.
/:cl:
=> Fix relay chat not letting held and non-held computers communicate

code/game/objects/items/weapons/tools/_tools.dm
Fixes a runtime in _tools.dm that was caused by an empty list in get_tool_type().
This means for one that machetes can now hack apart a locker to get steel.
Fixed a runtime - always good. Made a feature work again - quite good as well.
=> Fixes a runtime in tools.dm

code/game/objects/effects/decals/Cleanable/fuel.dm, code/game/objects/effects/spiders.dm, code/game/objects/items/weapons/flamethrower.dm, code/modules/mob/living/carbon/superior_animal/defense.dm
if a superior animal mob is dead for 90 seconds and on fire, they will dust.
spider based things now only need 50~c to take harm
spider cobwebs now only need around 25c to take damage
flamer fule no longer calls itself "welding fuel" but plasma mist, looks more blue and is harder to see (for traps)
:cl:
/:cl:
=> flame changes to spider stuff and mobs

code/modules/admin/admin_verbs.dm, code/modules/admin/view_variables/helpers.dm, code/modules/admin/view_variables/topic.dm
<details>
<summary>
Perk name is inputted manually, has to be the tailend of the path from https://github.com/sojourn-13/sojourn-station/blob/aca66e8cbbc9c32f48237728d838af8e87623db9/code/__DEFINES/perks.dm
So "sharp_mind" would be for the Sharpened Mind perk.
Might implement a list later, but this would require implementation with perks.dm to dynamically react when new perks are added. It's an admin command, doesn't need too much finesse at the moment.
Was tested in my own server, both direct command with Add-Perk and Remove-Perk work as well as using View Variables to add or remove perks. Not the most elegant picking as you have to type the perk name manually, but it'll work with any perk, both oddity and non-oddity ones. 
You're welcome, Kinni.
</summary>
<hr>
<hr>
</details>
:cl: …
=> Admin Add and Remove Perks

code/modules/mob/living/simple_animal/hostile/big.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/hostile/pirate.dm
Allows directly controlled mobs to fire their guns by pressing Middle-Click. A mob controlled will trigger its firing routine if it has one.
Known Issue: Greysons Mech will not work properly due to its special attack pattern where it chooses what to do based on a chance. You can still fire, but there is an unpredictability as to which direction and other stuff.
Also fixed minor bug: aero-trooper not firing and two big mobs missing their resting animations.
<details>
<summary>
Allows admins (or anyone else directly controlling a hostile mob with a ranged attack) to fire that attack.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Direct Control Hostile Mobs Can Now Shoot

maps/CEVEris/_Nadezhda_Colony_Underground.dmm
Removed the 2 Bar/RnD advertisement holopads - people were confused why they were their
Moved down the cook room food storer thing, added a window in place, moved up the grinder.
AI case glass thing as been correct by its access lock to now open if you have AI Upload access - Turns out this was a mapping oversight
Moved RD stamp 1 tile - to prevent new CRO's from getting confused on were the samp is located
Bar stuff - Added glass shutters to the bar tables same unlock as normal bar keep stuff
Made the club below much more to clean and such, more trash and the like really
Make the vendor in club need credits rather then vending all its stuff for free cuz you jumped over a table - Things that are normally free are still free iirc only really makes the booze and drinks costs credits if …
=> Map requests

code/game/machinery/autolathe/fabricators.dm, code/game/objects/items/weapons/circuitboards/machinery/biogenerator.dm, code/game/objects/items/weapons/storage/boxes.dm, nano/templates/bulletfabricator.tmpl
Adds the code for the munitions fabricator which generates ammo using any material it grinds up, basing the value of points by the amount * price tag of said materials, with rarer/more expensive mats being worth more.
Quick rundown:
-Smack materials (steel, glass, uranium, etc.) onto machine and hit the process button to get points.
-Use points to generate magazines, ammo boxes, or exotic ammo.
-Guild adepts **should absolutely** get this upgraded as soon as possible as the material per mag/box is immensely punishing otherwise. The cheapest ammo is a .35 speed loader which gives you 6 bullets fit for a revolver and that costs 15 steel, glass, or plastic.
--Standard super science parts reduce the cost by 67% while grayson (the reasonably best parts available) grant an 80% cost reduction. …
=> The long awaited bullet fab.

code/game/objects/items/weapons/tools/_tools.dm, code/game/objects/items/weapons/tools/misc.dm, code/game/objects/items/weapons/tools/pickaxe.dm, code/game/objects/items/weapons/tools/saws.dm, code/game/objects/items/weapons/tools/scalpels.dm, code/game/objects/items/weapons/tools/screwdrivers.dm, code/game/objects/items/weapons/tools/shovel.dm, code/modules/scrap/oldificator.dm
https://github.com/SyzygyStation/Syzygy-Eris/pull/209
Makes as stated in the O.G pr tools as they get more broken loss precision
Some power tools like saws now use more power then before after all they are saws
Guns as they get older now have a bit more randomness to them rather the flat fire rate and recoil
Gun damage and penetration also is affected bit more randomly by being old
Older tools also now have less precision, workspeed and hp
Tools that are old however as not as damaged.
Reduced tool durability across the board.
Standard Tools = 300 Health
Digging Tools = 500 Health
Scalpels = 100 Health
Munchkin5000 = 200 Health
#MakeTapeUsefulAgain #PrintingNewToolsShouldHappenMore #MakeDegerationModsUsefulAgain
:cl:
/:cl:
=> ports a really balance pr - Oldifaction now matters. 

code/modules/cargo/packs_hospitality.dm, code/modules/reagents/machinery/chem_dispenser.dm
Fixes cofffee master when hacked giving normal chem dispender chems + 14 glasses
Added a new cargo crate with each soda/booze/coffee board in it to make them
:cl:
/:cl:
=> coffee dispender fix & cargo pack

code/datums/perks/racial.dm, code/datums/setup_option/backgrounds/origin.dm, code/game/objects/items/weapons/grenades/emgrenade.dm, code/game/objects/items/weapons/grenades/flashbang.dm, code/game/objects/items/weapons/grenades/spawnergrenade.dm, code/game/objects/items/weapons/storage/belt.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/simple_animal/hostile/syndicate.dm
Opifex belts are now sorted by ethnicity and give you equipment based on background. Mechanists gain the standard toolbelt, biomechanists get a medical webbing, and combat techs get a tactical belt. All of which are loaded with genuinely useful items. 
-Mechanist focused opifex get an additional +5 mechanical and cognition. 
-Manhacks allied to the colonists are now a thing.
-Fixed some grenade typos referencing frozen star (old eris company replaced by Holland and Sullivan)
Copied from the code for ease of reading:
-Medical belt gets
Health scanner
Syringe (Hyperzine 15u)
Syringe (Tricord15u)
Syringe (Inaprov15u)
Pill bottle (Tramadol)
Pill bottle (Dylo)
Pill bottle (Bica)
Pill bottle (Derma)
Pill bottle (Dex+)
Pill bottle (Prosurgeon)
Cryobag
Mini fire extinguisher
-Combat belt gets …
=> Opifex Belt Perk Rework (+typo fixes)

code/modules/projectiles/guns/energy/stun.dm
The Counselor now has 3 fire modes,
Taser for 50wats
Stunbolt for 300wats
Stunshot for 600wats
These are balanced by longer fire rate making them not spam-able well still being viable 
:cl:
/:cl:
=> Counselor buffs

code/datums/autolathe/security.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/game/objects/items/weapons/stunbaton.dm
Stunbatons can now be deconstructed into mats
Stunbatons can now be made in the sec disk
As a reminder, you can make for FAR less, in crafting menu
:cl:
/:cl:
=> Adds stunbatons to sec disk

code/game/objects/items/weapons/storage/pouches.dm
Baton hostelers can now hold much more, such as some o2 tanks, mcells and other well-fitting thems
Tubular harness can now fit 7 items rather then five and have seen a much needed buff to be useful for day to day use
:cl:
/:cl:
=> Buffs baton and tubular hostelers 

code/modules/clothing/glasses/powered.dm, code/modules/clothing/glasses/thermal.dm, code/modules/clothing/spacesuits/rig/suits/light.dm, code/modules/research/designs/illegal.dm, code/modules/research/nodes/illegal.dm
Makes thermal and NV goggles now have their mat cost in the item itself rather then in the printing prossess
Added thermals to the new thermal node
Moved all NV/Thermal tech into mining (as thats really usefull for them like optic scanners)
Lowered the costs of the SPACER RIG as its way to costly for really bad armor and rigs are kinda common
Lowered the costs of Combat Defibs and moved them to be below freedom implant rather then borge illegal
:cl:
/:cl:
=> rnd changes

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Corrects missing Sec guns into Sec gun disk
Added 0 point cost mag to the SBW disk for hand loading
Added missing ammo from Rifle mag disk 
Corrects .257 ammo crates in sports rifles rather then small boxes
:cl:
/:cl:
=> Gun disk tweaks

code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, code/modules/mob/living/carbon/superior_animal/roach/attack.dm, code/modules/mob/living/carbon/superior_animal/roach/roach.dm, code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm, code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm, code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm, code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm, code/modules/mob/living/carbon/superior_animal/roach/types/support.dm, code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm, code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
Cutting up bodies takes half the time and half the skill - yay
Roaches based on their type now have knockdown odds rather then flat type.
Roachlings now have a weighed system to be more fair when eating a bodie
Roachlings eat bodies much slower
Spiders are no longer knocked down by roaches.
Fixes spiders endlessly webbing their own.
Added more things to a list that im sure dosnt work, such as attacking mechs in way or railings. Again this dosnt work at this time.
:cl:
/:cl:
=> Bug tweaks and fixes

code/game/objects/explosion.dm, code/modules/research/experiment.dm
That was painful.
Makes bombs legit count for RnD, like they are meant to but we had the wrong check for a bomb code that uses one thats disabled. Moves the code in case we enable it to a slighted nerfed version 
Is tested.
If you go out of your way to waste time and such on making a bomb, then tada, it will get you points like its meant to.
:cl:
trilbyspaseclone creating an admin explosion at the Toxins Mixing Room.
[Science] Kinetic Energy Scanner states, "Detected explosion with power level 7, received 7000 research points"
ADMIN LOG: Explosion with size (1, 2, 3) in area Toxins Mixing Room (45,20,1) (JMP)
[Science] Kinetic Energy Scanner states, "Detected explosion with power level 7, received 1400 research points"
ADMIN LOG: Explosion with size (7) in area Toxins Mixing Room …
=> Bomb code, bomb code never changes

code/modules/reagents/reagents/medicine.dm
There was no reliable way to un-husk people if they die to massive ammounts of burn damage, and Ryetalyn, the only chem that actually did it, wasn't coded to act on dead people. This PR fixes that, as well as tweaking a couple more things regarding medicine:
<details>
<summary>
The changes
</summary>
<hr>
- Ryetalyn now works on dead people, fixing husking along with mutations. It also gets recognized by scanners as a positive medicine.
- Added an overdose effect for Rezadone: Causes clone damage.
- Oxycodone now properly recognized by Health Analyzers to avoid dosing more than necessary / overdosing.
- Added clotting description to Meralyne to inform it also ceases bleeding.
- Modified the description of Kyphotorin to, instead of referring to the chance of the limb getting damaged on …
=> Ryetalyn now affect corpses

code/game/objects/random/mob/spider.dm
Tanky spiders like fortress and guarden seem to be second/third most common type, this lowers it a small bit to allow more clockers and other types that are less tanky to spawn as well
:cl:
/:cl:
=> Makes the weighted spider spawn system be less tanky

code/datums/outfits/jobs/science.dm
<details>
<summary>
</summary>
<hr>
They already spawn with a full toolbelt, so the toolbox they spawn is obsolete because they already got the tools.
<hr>
</details>
:cl:
=> Remove the Roboticist's Spawn Toolbox

code/modules/mining/mine_turfs.dm, code/modules/mining/ore.dm
Its really dumb that a toxin bomb cant be used to mine anything other then sand do to it blowing up the ore
Makes emitter mining not as trash - why do you lose so much ore?
Makes bombs mine legit amouts of ore rather then 1-2 as that is really dumb, also light bombing now digs out ore making you /want/ to use ligher bombs scattered around rather then one massive nuke
:cl:
/:cl:
=> Makes ore bomb proof

maps/CEVEris/_map_data_Eris.dm, maps/encounters/deeptunnels/deeptunnels.dm
Changes is_contact_level = TRUE on map of the mines as well as the solar panels.
This allows the NTNet to function on these maps provided they are either using an Advanced Network Card, or have a wired Ethernet card. This does nothing to affect computers using basic network cards.
=> Restores NTNet Functionality

code/controllers/subsystems/voting/poll_types.dm
Heads of staff/"antags" now longer get 2+ in votes but 1.3
Why?
A head of staff can cancle out **3** dead votes and turn  2 living votes into a tie. Thats not good for voting...
This new way cancle outs 2 dead votes but only 1 living rather then tieing two making the dead vote/newcrew vote a bit more of a voting force.
:cl:
/:cl:
=> Slightly more fair voting

code/game/machinery/biogenerator.dm
Fixes bug where round spawn Xenofloral Biogenerators could not be upgraded or deconstructed.
Fixes bug where choosing Leather Jacket caused Biogenerator to seize up and brick itself.
Makes Leather Satchel actually produce a leather satchel as opposed to a standard grey satchel.
=> Xenofloral Biogenerator Fixes

code/modules/dungeons/procedural/deepmaint.dm
Halfs the max hallway lanth, being 120 tiles is a bit much imo and ends up using a lot more space on halls then it likes thus it stops placing rooms or fails to path to them.
:cl:
/:cl:
=> Makes deep maints a bit less hall-y

code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm, code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
Exl disks and boards now have their faction and such echted onto the board itself rather then being modular so that the teleporter can read the names correctly
:cl:
/:cl:
=> Exl teleporter name fixes

code/modules/sanity/inspiration_component.dm
Should fix the doup reading of its stats
Should also fix the lack of mechanical power for matterforage in a trinket
Also gives a better idea of what trinket power is when looked at
:cl:
/:cl:
=> Oddity doup reading fix

code/datums/autolathe/circuits.dm, code/game/mecha/equipment/tools/tools.dm, code/game/mecha/mecha_wreckage.dm, code/game/objects/items/weapons/autolathe_disk/guild_disks.dm, code/game/objects/random/junk.dm, code/game/objects/random/purerandom.dm, code/game/objects/structures/salvageable.dm, code/modules/scrap/scrap_pileripper.dm, code/modules/scrap/scrap_refine.dm, code/modules/scrap/scrap_refinery.dm
Clamping scrap piles now cube them hopefully
taking apat things now gives unrefined scrap, you get more as guild
unrefined scrap is now a common trash item
unrefined scrap is now in trash piles
Drasticlly highers the odd of the scrapper into refined scrap
fixes the missing boards in the thingys that do the things with the boards and the parts
adds 2 more boards to the logistic disk making it /work getting/ maybe
:cl:
/:cl:
=> Scrap code changes and fixes

code/game/objects/random/mob/roach.dm, code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm, code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/reagents/reagent_containers/food/snacks/meat.dm
Gluhend or "glowing" roach is now in! Its 100% toxin proof making it the pain to some biomatter based trapped
Its fancyness in that if flashes at a "5%"(4%) odds per attack on top of their pintch attack that leaves chemical burns.
meat type has uranium in it! Making it quite worth to hunt down and skin for rnd or chemists!
:cl:
/:cl:
=> Gluhend Roach implantation

code/modules/mob/living/simple_animal/hostile/doomba.dm, code/modules/mob/living/simple_animal/hostile/onestar_drone.dm
icon naming is hard
drops were not set for cook/serves roombas I guess
:cl:
/:cl:
=> icon fix for roomba tripper and fixes some drops

code/game/machinery/autolathe/matterforge.dm
Before my initial fixes: matter forge was altering the *apparent* cost of a recipe but not the actual cost.
After my initial fixes: matter forge was altering the actual cost properly.
Problem now: matter forge was not tweaked in my fix to no longer recalculate the real cost when needed.
Fix now: matter forge no longer calculates actual cost twice.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
fix: Matterforge doing the cost-to-matter calculation on recipes twice.
/:cl:
=> Fixes double cost calculation in matterforge.

code/datums/setup_option/backgrounds/origin.dm
Makes useless traits like iron lung have a reason to be picked for the backround stats and such to reflect your life choices of low o2.
Adds 5 new backround things, to give more options
Balances out Former Social Worker a bit to be not as much cog to overturn savont 
Ups the bio on Former Mill medic to to 5 (from 3)
:cl:
/:cl:
=> more background options and such

code/modules/scrap/scrap_refinery.dm
You now can only get refined scrap from lumps of scrap with the recycler, as this prevents people from dumping 300000 bullet cases into the recycler for endlss refined scrap, or bottles
:cl:
/:cl:
=> Fixes a exploit with recycler

code/modules/power/hydroelectric.dm
Changing the Hydroelectric Dam.
Due to a missing line in the initial release, the counter to check if the die would change would always spill over and only trigger once per round. This made malfunctioning a near impossibility.
It will now function as desired. Before, it was stuck at the lowest possible filling setting. Not will randomly choose between a few numbers of settings. 
To balance out the potential for faster filling, the chance to malfunction (which now it will) goes up 10% each time the dam is turned on.
=> Hydroelectric fix2

code/modules/reagents/reagent_dispenser.dm
<details>
<summary>
Increasing BIDON capacity due to non-existant use, and no reason to use them
</summary>
<hr>
I increased the capacity of both BIDONs to ten times their current value, to 6000 and 9000 units respectively. They aren't used whatsoever, and given that the capacities are laughable two/three bluespace beakers, they seemed like a joke considering they can't be placed on tables, and you can put way more bluespace beakers visible on one turf square than is taken up by a BIDON.
This change would let them actually be used for mass storage purposes, be that medicine refills, poison storage, and perhaps even trading large amount of chemicals for credits without requiring god-tier micro to prevent insanity.
<hr>
</details>
:cl:
balance: Multiplied BIDON capacity by ten
/:cl:
=> Increase BIDON capacities tenfold

code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm
Lowers the gluhand roach spawns as they are better then toxic ones and have a flash built into their attacks that reck most spiders making roaches only need around 12 to kill a queen do to likelyhoold of stunlocks
Also uranium is inside them making it a bit to easy to get chem warfare against people with rads
:cl:
/:cl:
=> Lowers Gluhand roaches spawn

code/modules/reagents/reagents/stims.dm
effect_multiplier is the amount consumed, not the amount in bloodstream. It was being used like that, however, which meant all stat boosts were multiplied by, like, 0.01 and just neutered.
Also, having higher effects per unit is kinda insane. If you had 18 units (the overdose limit) of machine spirit in your system, and the effects scaled with amount in your body, you would end up with like, 300 extra mechanical skill.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
balance: stims now provide their flat bonus, instead of scaling with the amount in the body
fix: the bug that prevented most stims from having any effect at all is gone
/:cl:
=> Uncurses Stim Chems

code/modules/projectiles/guns/matter/launcher.dm, code/modules/projectiles/guns/projectile/other/protector.dm
When porting over the new and fancy grenade launchers we forgot to disable their now broken grenade loading and firing for hand grenades such as smoke bombs, frag, and other hand held ones that should have been disabled.
:cl:
/:cl:
=> Fixes grenade launchers taking grenade 

code/modules/organs/internal/_internal.dm
Taking upwards of 1000 food units to heal the heat 1 damage (max you can have i 500) is really really high... 
:cl:
/:cl:
=> drasticly lows food intake when healing damaged organs

code/modules/reagents/reagents/medicine.dm
Ryetalyn had no proper way to unhusk dead people (given the way husking works, you'd only find it as a mutation on dead people), even with the `affects_dead` flag, wich I'm assuming only meant that it would work while inside a Cryotube. ~~(Testing pending)~~
**Testing concluded:** Ryetalyn did not even work with the `affects_dead` flag inside a cryotube on a husked dead patient.
~~(Thanks Faxington)~~
<hr>
This PR changes the datum from an `affect_blood` into an `on_mob_add`, making it so that it acts the first time the chemical is added to the blood rather than the datum wich prevents chemicals from circulating on a dead body (and not necessarily having an entire separate use of Ryetalyn for just husks, and have it act normally for the rest of the mutations it heals)
This PR also adds an …
=> Fixes Ryetalyn unhusking dead people, for real this time!

code/datums/craft/recipes/guild.dm
All guild armor crafting now need mesh, this is to help it form onto armor!
All guild armor has been tweaked a bit to cost eather more types of mats, or reduced
Guild laser armor now only costs 3 plat but 17 plastic.
:cl:
/:cl:
=> guild armor tweaks - crafting

code/datums/autolathe/guns.dm, code/game/machinery/portable_turret.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/energy/stun.dm, code/modules/projectiles/guns/projectile/automatic/battlerifle.dm, code/modules/projectiles/guns/projectile/automatic/nordwind.dm, code/modules/projectiles/guns/projectile/automatic/ostwind.dm, code/modules/projectiles/guns/projectile/automatic/wirbelwind.dm, code/modules/research/designs/weapon.dm
All cases of Seinemetall Defense GmbH being called SM have been replaced by GmhH
All cases of just Seinemtall, and Seinemetall Defense have been replaced with Seinemetall Defense GmbH
Correrts name and manufactory of the Solaris
The stun revolver now shows that it was made by Seinemetall Defense GmbH with SI help
The consoler now has better lore on why it was made as a non-lethal take down weapon.
The laser cannon inside of turrets at preppers is now its own type of laser gun, only differentce from RnD's is that it dosnt have a charge mode nor uranium inside as well as more lore on why no one ever makes them anymore (bad marketing)
colony turrets now have Cogs inside them as they were meant to.
:cl:
/:cl:
=> Guns manufacture and naming lore tweaks

code/modules/reagents/reagents/medicine.dm
- Most medicines that are beneficial are now identifiable by the Health Scanner.
- Removed flavor text on Haloperidol stating that it lowers NSA: It doesn't do so directly, it merely removes chems. If those chems increased NSA of course it'd be lowering it, but by virtue of **removing** them, it does not lower NSA by itself mechanically.
- Increased the metabolization rate for Synaptizine as it was very slow to purge, considering you don't need more than 1 unit to stop hallucinations and that it still poisons you while inside the body.
- Reduced the metabolization rate of Spaceacillin to not require constant re-dosing of it for the treatment of infections.
:cl:DimmaDunk
tweak: Medicines should all be scannable now.
balance: Made Synaptizine metabolize faster and Spaceacillin metabolize …
=> Medicine QoL changes

code/game/objects/items/weapons/cigs_lighters.dm, code/game/objects/items/weapons/melee/energy.dm
- Energy melee weapons now properly do their corresponding swing sound instead of the stock hit by blunt weapons
- You can now take drags off your cigarette by holding it on your hand and clicking your character's sprite, with sound!
:cl:/DimmaDunk
add: You can take drags off cigarettes and cigars now.
soundadd: Not really adding sounds, just properly assigning them for their intended use.
/:cl:
=> Take a drag off that cig! +Energy Melee weapons now sound like energy weapons

code/game/mecha/mecha.dm
Modifies the explosive damage formula for mechs, using armor level to calculate flat health damage.
The formula is, as a proportion of the mech's health: 1 / (severity + armor_level - 2).
Severity ranges from 1 to 3, with 1 being the most severe and 3 being the least.
With this new formula, a severity 1 explosion will instantly destroy any mech with an armor level of 2 or less, which includes Gygaxes, Firefighter APLUs, Ripley APLUs, Odysseuses, and Hover Pods.
Against a Durand, this formula means three severity 1 explosions will destroy it, or five severity 3 explosions.
I may make an ERA module for mechs at some point which modifies their armor level against explosions and weapon hits a certain number of times before exhausting its uses and needing replacement.
:cl:
tweak: changed the …
=> Tweak/Modify explosive damage formula for mechs.

code/game/dna/genes/powers.dm, code/modules/mob/living/carbon/human/human_species.dm, code/modules/mob/transform_procs.dm
The start of making genetics better, this PR allows monkeys to be humanized in the DNA scanner by manipulating the monkey gene (Structural Enzyme 27). Importantly, this in a one-way transformation - humans still cannot be turned into monkeys, to avoid griefing with monkification activators.
* Allows monkeys to be humanized in the DNA scanner and with (de)activators.
* Does not allow humans to be monkified.
* Randomizes monkeys' blood type (requested by Sebastian)
:cl:
tweak: monkeys' blood type is now randomized.
fix: fixed DNA scanners being unable to humanize monkeys.
/:cl:
=> Bugfix/Allow monkeys to be humanized.

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/shock.dm, code/modules/mob/mob.dm
Fixes Cht'mants being in pain and being slowed after pulling embedded objects out of their bodies.
:cl:
fix: Fixed Cht'mants being in pain/being slowed after yanking objects out of themselves.
/:cl:
=> Bugfix/Fix Cht'mants being in pain after pulling objects out of their bodies.

code/modules/mob/living/silicon/robot/robot_dogborgs.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/living/silicon/robot/robot_upgrades.dm, code/modules/research/designs/robot_parts.dm
* Fixes the big knife robot upgrade behaving oddly when used on a robot.
* Also fixes some typos in the mining cyborg's satchel of holding upgrade.
:cl:
fix: Fixed robots' big knife upgrade behaving strangely when applied.
spellcheck: Fixed a few typos in robots' ore satchel of holding upgrade.
/:cl:
=> Bugfix/Fix big knife robot upgrade and some typos.

code/modules/projectiles/gun.dm
Turns out every vig stat is 1 AP on all bullets, meaning the commander nulls most armor round start with +30-40AP making their laser gun and bullet gun almost null armor. Lets make it so that this isnt a thing and armor be worth wile.
:cl:
/:cl:
=> Makes it so VIG isnt as op with bullets

code/__HELPERS/matrices.dm
When we take damage while standing we'll call the shake_animation procedure normally.
Created a new procedure specifically for players that will take into account the size multiplier. 
The math now includes using the size multiplier as well as translating the matrix upward so that we retain the same footing as before / as everyone else.
Currently this implementation may make the model to appear just a tad different, with the difference only visible after the model is updated with update_icons, this is due to how animate works in byond.
If that is too noticeable / becomes an issue, we can use update_icons at the end of the proc, but at the moment it's not included since calling it every time we're hit would just add more unnecessary matrix calculations into the mix.
=> No Shrinking / Growing during damage

code/__DEFINES/perks.dm, code/datums/perks/job.dm, code/game/jobs/job/medical.dm, code/game/mecha/mecha.dm, code/modules/surgery/surgery.dm, code/modules/surgery/wound_repair.dm
This PR adds some stat scaling (and a medical perk) to make the mechanical and biology stats more impactful. I'll be expanding on this more in future PRs.
* Adds an Advanced Medical Techniques perk for Doctors and the CBO, which allows them to use their Biology stat to scale the amount of damage healed by ATKs and ABKs in reconstructive surgery. Will be adding to this perk more later.
* Reworks reconstructive surgery to only use the number of kits necessary for the amount of damage the patient has.
* Adds stat scaling to welders repairing mechs, both for external and internal repairs.
:cl:
add: Added a perk to Doctors and the CBO allowing them to scale the amount healed by ATKs and ABKs during reconstructive surgery.
balance: Added stat scaling to repairing mechs and reconstructive …
=> Balance/Add stat scaling (and a perk) for mec and bio skills.

code/datums/setup_option/backgrounds/origin.dm, code/datums/setup_option/core_implants.dm, code/modules/client/preference_setup/general/02_body.dm, code/modules/core_implant/core_implant.dm
-Cht'mants can't be cultists anymore, so sayeth the cht'mant lore dev. Selecting a cht'mant as a race clears your cruciform and disables the option. Selecting an ethnicity also disables augments now, which you shouldn't be taking augments as a cht'mant unless you want to die quickly.
=> Cht'mants can't be cultists

code/modules/projectiles/ammunition/ammo_kits.dm
Scrap ammo now uses correct ammo names
:cl:
/:cl:
=> name fixes

code/game/machinery/Sleeper.dm, code/game/objects/items/weapons/cigs_lighters.dm, code/modules/reagents/reagents/drugs.dm, code/modules/reagents/reagents/medicine.dm
- Sleepers have more attractive chems as upgrades
- Hyper sleeper has even more amazing selection of chems to justify their rarity
- Tobacco now tastes like tobacco, with a distinction between cigar's fine tobacco and cigarette tobacco
- Makes Peridaxon no longer heal bones too
- Fixes to Ryetalyn so that it continues to proc the mutations cleanup on every life tick
- Fixes Paracetamol taking ages to metabolize
- Adds an overdose effect for Noexcutite
- Changes Peridaxon so that it no longers heals bones, to justify making Ossisine (also Peri shouldn't heal bones!)
:cl:DimmaDunk
add: Added Fine Nicotin for the expensive cigars
add: Added Noexcutite overdose effect
tweak: Peridaxon no longer heals bones, only internal organs
balance: Changed the Sleeper's unlockable chems by tier, as well …
=> More QoL changes

code/modules/scrap/scrap_beacon.dm
Doubles scrap beacon pre-cooldown to not take 1 hour form shift to start it
:cl:
/:cl:
=> Doubles scrap beacon pre-cooldown to not take 1 hour form shift to start it

code/controllers/subsystems/jobs.dm, code/controllers/subsystems/overlays.dm, code/modules/client/preference_setup/options_popup.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/new_player/preferences_setup.dm, code/modules/projectiles/gun.dm
Fixes several runtimes. Tested and no major problem appeared, or any problems as far as I could tell.
Runtime in gun.dm line 535: cannot read null.screen. Added sanity check when initializing scope. Scope initialization will run at gun initialization to properly set it up. Gun is not being held by anyone with a screen at the time though. Fix applied.
Runtime in glowing.dm line 34. Known issue. Glowing roaches runtime. Kept for later testing purposes. Fix can be done via eye check, but left in here in case we get the problem again where runtimes won't show up at all. 
Runtime in overlays.dm line 247: undefined variable /var/our_overlays. Added sanity check. If cut_overlays is ran before copy_overlays, it will destroy the list and cause this runtime. Need to check that it still exists. Cut …
=> Runtime Fixes

code/game/machinery/cryopod.dm, code/modules/mob/living/silicon/robot/drone/_drone.dm, code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Drones can now use the lift to leave the round, same as borgs
Drones can use robotic storage to leave the round, same as borg
Drones are killed by robotic Id swipe rather then a mix of Guild/Robotics (meaning like Marshal/Preimer only for some reason)
Drones maybe revive-able now Yay!
Drones (NOT BLITS) start unlocked for repairing/upgrading the cell/internals.
:cl:
/:cl:
=> Many drone QoLs/fixes

code/modules/projectiles/projectile/bullettypes.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
For the purpose of re-balancing some weapons, mostly 257. ones, and making them worthwhile, I've decided to augment their damage values. Same with 408 (and 10x24 though minor), which despite being much, much rarer than 7.5 (with the exception of blackshield.), and having nearly no weapon disks that can print weapons using this ammunition, was actually weaker.
I also plan to modify some weapons' damage modifiers, notably the STS to be a 1.1x instead of 1.3x, along with some boltguns if this request passes through.
(First PR of mine. Pardon if anything's not up to par.)
Here are all the of the changes.
/obj/item/projectile/bullet/light_rifle_257 
damage_types = list(BRUTE = 22) (from 16) …
=> Small changes to some projectiles' damage.

code/modules/mob/living/silicon/robot/drone/_drone.dm, code/modules/mob/living/silicon/robot/drone/drone_remote_control.dm, sojourn-station.dme
The AI can not do the following:**
- Click on a drone fabricator to create a new drone shell for themselves and enter it.
- Leave and enter drone bodies whenever they want by clicking uncopied drone shells. Release-Control is the verb to leave a drone, available under Silicon Commands
- If a drone is destroyed while controled, control is simply turned back to the old AI core.**
Enjoy. Tested on my server. No runtime, runs as expected.
=> AI Drone Control

code/datums/ai/ai_law_sets.dm, code/game/objects/items/weapons/RCD.dm, code/modules/projectiles/guns/energy/centurio_auretian.dm, maps/CEVEris/_Nadezhda_areas.dm, sojourn-station.dme
-Auretian is now buffed, its firing modes have been changed to:
--Plasma, slower firing with 30 burn and 30 armor pen.
--Laser, faster firing with 20 burn and 10 armor pen.
This is in response to the centurio being rebalanced, now auretian is now far more useful as its laser firing mode is great for clearing crowds and its plasma firing mode is better at dealing with tougher enemies.
-The RCD no longer creates space tiles when deconstructing floors.
-Derelict maintenance drones now have no laws at all, acting as an optional robotic out of colony option. At the moment they only spawn at the free republic, but later this will be expanded to include the abandoned fortress, abandoned solars, and vault bunker. They're faction alignment may also be changed so engineers and auto drones no longer …
=> Small Fixes

code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/automatic/sts.dm, code/modules/projectiles/guns/projectile/boltgun/roe_sika.dm, code/modules/projectiles/guns/projectile/boltgun/scout.dm, code/modules/projectiles/projectile/bullettypes.dm
About The Pull Request : 
(Now fixed.)
This is the change that was announced after modifying 257. and 408. stats, after an awful fight with my poor coding skills, I've managed to put all of those changes in a single PR. However, the fact it can't merged together automatically might be because some projectile values are the same. 
(Despite being a change from the forked version of sojourn, which was somehow different from the version the server uses on SS13.)
Some weapons have also been modified, like the Scout and SA AKM to actually be relevant now.
🆑
Weapon balance.
/🆑
=> Balance (stats) change for (some) weapons. 

code/modules/virus2/items_devices.dm
The animated antibody scanner sprite was totally unused because it was currently using the health analyzer's one to flick once used. This fixes it and now it uses the correct animated sprite.
:cl:DimmaDunk
fix: Antibody Scanners now use the correct animated sprite instead of the Health Analyzer one.
/:cl:
=> Fixes the antibody scanner's sprite on use

code/game/objects/items/weapons/storage/firstaid.dm
Code oversight about making the kits `exact_fit` prevented them from being filled with anything that wasn't their initial contents, ignoring completely the list of items allowed inside of them. This fixes that.
:cl:
fix: Triage kits now are able to take their intended items inside, and nothing else.
/:cl:
=> Fixes triage kits not being able to be filled with bottles/etc.

code/modules/projectiles/projectile/bullettypes.dm
Scrap ammo no longer have same AP value as basic ammo as they are trash shots
HP 408, now longer has more AP then basic ball ammo
:cl:
/:cl:
=> AP values fix

code/game/objects/items/weapons/storage/belt.dm
Tactical belts can now take bottled water or soda drinks into the belt
Tactical belts can now hold snackies
Tactical belts can now hold pens
:cl:
/:cl:
=> tactical belts can now hold snacks and drinks

code/game/objects/random/food.dm
Normal food spawns are no longer crayons
:cl:
/:cl:
=> crayon hot fix

code/game/objects/items/weapons/tools/simple_weapons.dm
They're called "steel mini hoes" should cost steel, not plasteel
Also quality shoveling 10 for two sheets of plasteel is a **scam**.
<hr>
:cl:
fix: Mini-hoes cost steel instead of plasteel to make, as intended
/:cl:
=> Mini hoes no longer cost plasteel

code/modules/projectiles/guns/projectile/shotgun/hunter_crossbow.dm
As funny as it is, you no longer can saw down bolt lancers into pump action 20mm grizzles 
:cl:
/:cl:
=> hunter cross bow can no longer be sawn down

code/game/machinery/doors/airlock.dm
Jantior keys are faster to punch in the codes
When a door is unlocked by the key it saves its code
When the door fails to unlock by the key it discards that code making you more likely to open it next try
:cl:
/:cl:
=> janitor qol

code/game/objects/items/oddities_faction.dm
Biosiphon Anomaly now prints every 30 mins rather then 2 hours as no one uses these. And the case is itself a nerf on storage over a normal one for some reason
Removes Biosiphon Anomaly bluespace tech as its not teleporting anything
:cl:
/:cl:
=> Biosiphon Anomaly buffs

code/game/objects/items/devices/flash.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm, code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm, code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm, code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoImpressive.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoMega.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoRobust.dm
Roaches changes with flash - 
Flashes against Furher are half affective
Flashes against Kaiser are not as affective
Flashes against Glowing ones are not affective
Flashes against Bluespace roaches are not affective
Spider changes with flashes - 
Flashes against Reaper spiders are not affective
Flashes against Emper are less affective
Flashes against Queens are less affective
Xeno Changes with flashes
Flashes against Queen/praetorian are not as affective
Flashes against Boilers are not affective
Flashes against most xenos has been reduced 
:cl:
/:cl:
=> reduces teh usefullness of flashes

code/game/objects/items/weapons/clown_items.dm
Soaps now have limited slips that need to be presoaked to recharge, church soap has the most slips for common soap.
Hunters is better then churches
Antag soap is better then Hunters
Commie soap is better then Antag
Bluespace soap is bestsoap
:cl:
/:cl:
=> Pro Clown Gamer Moves

code/modules/surgery/wound_repair.dm
Wound repair no longer consumes the maximum amount of brute packs, burn packs, or nanopaste.
Instead, they use one pack if needed.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
balance: wound repair surgeries now act only once per run
/:cl:
=> Surgeons can now control wound repair

code/modules/reagents/machinery/chem_dispenser.dm
Balances chem_dispensers to have lower recharge rate.
<details>
<summary>
Cuts the recharge rate from 48 to 24 for the inital recharge start (before capacitor fix it was 24) A 800 (the one it starts with) now starts at 24, 1000m becomes 40 and a 1600 goes up to 64, Those are without capacitor upgrades so if you really need super solution amounts upgrade the capacitor along with it.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Chem Dispenser Recharge Balance

code/modules/food/recipes_microwave.dm
Re-creates the class so that it's the parent class instead of /roach one, much like the cake. We need a default class first before we can go straight into a sub-class.
=> Fix the Cube

code/datums/perks/job.dm
<details>
<summary>
Fixes Revival Sickness to be properly scaled with the severity of it.
</summary>
<hr>
This was a rather strange thing to come across - Revival sickness used to be extremely strange on how it worked, going from a -15 debuff, to a -10, to a -25 in terms of damage modifiers. This corrects that, and the stat-loss.
While this actually does nothing in terms of damage incoming, it now further reduces skills.
<hr>
</details>
:cl:
Tweak: Revival sickness now scales with its tier, along with applying lesser/much worse stat debuffs
/:cl:
=> [FIX&REBALANCE]Revival Sickness

code/game/machinery/Sleeper.dm, code/game/machinery/cryo.dm, code/game/objects/items/devices/scanners/health.dm, code/game/objects/items/devices/scanners/reagents.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, code/modules/reagents/machinery/centrifuge.dm, code/modules/reagents/machinery/chem_heater.dm, code/modules/reagents/machinery/chem_master.dm, code/modules/reagents/machinery/electrolyzer.dm
Pushes the fix for spider fixes
Makes it so all medical gear stat can be bypassed by perks that sci and medical gets
All medical stuff is medical perk only
The sci stuff is sci perk and medical perk bypassable
:cl:
/:cl:
=> corrects spender fed amout per egg laying and perks

code/datums/craft/recipes/clothing.dm, code/datums/craft/recipes/weapon.dm, code/game/objects/items/oddities.dm
Scrap bots can now be made! Still keeing with the theme of them being trash they are made of bits and bobs and a way for propis to get a bit more use out of their oddities and scrap clothing by needing to craft up to a scrap bot if they want to.
:cl:
/:cl:
=> Craftable new scrap bot nades

code/modules/projectiles/guns/projectile/automatic/ak47.dm
The AK in this change is now made into a high recoil-high damage option instead of before, to make it a more distinct option compared to other weapons. It's less accurate, but does more damage now. (Which'd be more accurate to the real life counterpart too, as it uses a round with more power and more recoil than other assault rifles chambered in 5.56 and the likes, the sooner being known to overpenetrate a lot.)
:cl:
<!--add: Added new things
tweak: tweaked a few things
/:cl:
=> Re-balance for the AK to be more special.

code/modules/projectiles/guns/oddity_items.dm
The bluecross boltgun didn't have an internal mag tag, while some other single-shot weapons like the AMR had, it may had been overlooked.
:cl:
balance: rebalanced something
fix: fixed a few things
/:cl:
=> Fixed bluecross boltgun.

code/modules/power/solar.dm
Solars on map load will now have 20% per pannel to be broken, meaning the pacmans untill you fix up the glass is likely needed
=> Solars can brake and now on round start can spawn broken

code/modules/power/cable.dm
You know whats fun? Getting a small bit of scrap form 1 or 2 of cells or 10 coil to get some camera film.
You know what people do? Abuse the heck out of everything to maxium abuse to powergame. We can have nice things ever thanks to them. If you are personally affected by this more then a minor annoyance then your apart of the problem and you should rethink why you are here and playing to win. Were HRP and endless matter creation for ever. single. round. ruins are more gimmicy or fun things that add a bit of unrealistic qol.
P.S This is why we cant have fun, or QoL.
:cl:
/:cl:
=> Wow coils are brokenly good. One of many balance changes aimed at people that abuse endless mats

code/game/objects/items/weapons/tools/mods/_defines.dm, code/game/objects/items/weapons/tools/mods/mod_types.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/guns/mods/mods.dm
-Guns now have the sight slot (currently only used by laser sights)
-Booster now increases laser damage by 25%, up from 20%.
-Sanctifier now fits the gun mechanism slot instead of free slot.
-Excruciator now fits the barrel slot instead of mechanism. Charge cost is now 15%, down from 40%.
-Kriosans with the instinctual skill perk now get plain text when inspecting fire arms they negate the 1 handed penalty too.
-All firearms capable of being dual wielded now display text stating so when examined.
=> Slight Adjustments

maps/CEVEris/_Nadezhda_Colony_Surface.dmm
- Adds a second combat surgery kit to the Blackshield Corpsman room.
We have two Corpsman slots, and some people often cryo with the only surgery kit. This lets both Corpsmen be able to perform surgery, and also helps buffer against people cryoing with vital equipment. This is something that an active Corpsman player requested of me to add.
Corpsman prep area: https://gyazo.com/19f7bfed73c138053c5315721a77d8b7
=> Adds a second combat surgery kit to the Blackshield Corpsman room

code/modules/cargo/packs_security.dm
Allows Lonestar to order Handgun ammunition, either normal or rubber, in 35, 40 and 50 Kurtz. Removed the STS rifles from cargo ordering.
=> Lonestar Handgun Ammo

code/game/machinery/autolathe/matterforge.dm
Nanoforges now work properly and will remove the price based on the actual price rather than the base one. This makes it so that manipulators are useful and don't simply show a deceiving price.
Nanoforge built items will no longer be recycled for materials.
=> Nanoforge Fix and Exploit Removal

code/modules/client/preferences.dm
In the only instance that `copy_to(mob/living/carbon/human/character, is_preview_copy = FALSE)` is called with `is_preview_copy` being `TRUE`, `mannequin.update_icons()` is guaranteed to be called again in the stack. So placing the `is_preview_copy` check before eliminates a redundant `update_icons()` call.
=> Removes Redundant update_icons() call.

code/modules/organs/internal/machine.dm
The simplest solution is often the best. We simply no longer drop you for 3 seconds in case you run out of charge. Because nuclear cells no longer recharge while in use, this keeps happening after an hour or two of walking around and doing stuff as a synthetic.
This fixes it. Tested it on my own server, everything seemed to work just fine.
=> Fixes Synthetic Batteries

code/modules/client/preference_setup/augmentation/01_modifications.dm, code/modules/client/preference_setup/preview.dm
CHANGELOG
Cleans up Character Creation a little, hopefully will reduce creation lag on the server.
-----------------------------------------
DEV EXPLANATION
`getFlatIcon()` is almost never called in the East direction. In fact, the only time a character's sprite will be seen facing East is in the Augmentations tab, and that is only if they are specifically rotated to face that way.
However, `getFlatIcon(EAST)` is called a LOT more than when it is actually used in that one circumstance.
This PR hopefully will reduce the number of proc calls in character creation drastically, hopefully reducing server load for people creating characters.
=> Removes Redundant getFlatIcon() calls

code/__DEFINES/perks.dm, code/controllers/subsystems/staverbs.dm, code/datums/perks/job.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/machinery/autolathe/mechfab.dm, code/modules/research/rdconsole.dm
All rnd consoles can no longer start unlocked
Cog needed to hack the rnd console raised to 50 and useing it needs 60
Mech fabs needs 30 mech to use it, not that hard
Sci and CBO now get a perk to bypass these checks for stats
We cant have nice things
:cl:
/:cl:
=> Medical can no longer steal sci's jerb

code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/automatic/basstet.dm, code/modules/projectiles/guns/projectile/automatic/bren.dm, code/modules/projectiles/guns/projectile/automatic/bulldog.dm, code/modules/projectiles/guns/projectile/automatic/dp.dm, code/modules/projectiles/guns/projectile/automatic/luger.dm, code/modules/projectiles/guns/projectile/automatic/mac.dm, code/modules/projectiles/guns/projectile/automatic/nordwind.dm, code/modules/projectiles/guns/projectile/automatic/ppsh.dm, code/modules/projectiles/guns/projectile/automatic/sts.dm
<details>
<summary>
I noticed after looking through gun values that things such as the Kalash had higher prices than guns with similar if not the same stats despite having a high recoil. In turn I've lowered most STS and Kalash recoils to be more on-par with certain guns like the Pitbull or the 'PKM' LMG (which only has a recoil of 3.5.) Also modified some other weapons as well to fix their values. This will require tweaking and testing as we get feedback but overall prospectors, security members and others have mentioned certain guns such as the AK were objectively inferior due to high recoil. This should hopefully fix and balance that somewhat.
</summary>
<hr>
</details>
:cl:
tweak: Adjusted STS, AK, Kalashnabren, DP (by .5) and other guns stats to balance them
tweak: Adjusted STS, AK …
=> Gun Price Fixes & Minor Recoil Rebalance

code/modules/client/preference_setup/augmentation/01_modifications.dm, code/modules/client/preference_setup/general/01_basic.dm, code/modules/client/preference_setup/general/02_body.dm, code/modules/client/preference_setup/general/04_equipment.dm, code/modules/client/preference_setup/general/06_furry.dm, code/modules/client/preferences.dm
Now instead of update_preview_icon sanitizing the entirety of the character every time, only the parts of the mob that belongs to the altered category is changed.
I am now officially out of ideas of how to better optimize the processes of creating a character.
=> Categorizes Graphic Updates in Char Creation

code/modules/projectiles/guns/mods/mods.dm
I made so the contract killer scope increased fire delay instead of recoil, and deleted the guild scope's recoil, because what the fuck. No seriously, why would a scope increase recoil? At best you're gonna spend more time aiming, hence the fire delay, but why /recoil/? It essentially made them pointless besides the zoom itself. So here you go.
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
=> Fix scopes

code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
-Xenomorphs now impale you with their tail (50 brute) and stun you if you attempt to grapple or disarm them.
-Tarantulae class spiders (fortress, ogre, emperor, and reaper) now stun you if you attempt to grapple or disarm them.
-The math for pushdowns is now correct, as a slight mistype made it so it was far too easy to knock down superior mobs. All mobs have 30 + 10% robustness. Tarantula class spiders and xenomorphs have 10 + 10% robustness as their fucking huge and failing has a severe penalty as well.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Big boy rebalance

code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoMega.dm
-Xenomorphs no longer tail stab you when dead when you attempt to grab or disarm them.
-Spiders no longer knock you down if you attempt to grab or disarm them when they are dead.
-Perks DEFENSIVE_TRAINING and BRAWN are now considered when grappling or disarming spiders and xenomorphs. People with either can grab and choke hold any class spider and disarm knockdown is prevented. Against a xenomorph you are not knocked down, but the grapple is immediately broken and you still get tail shanked.
-Tail stab text updated to reflect its armor piercing qualities. The damage is 50 flat, unmitigated by armor.It's an 8 ft tail with an armor rending spike on the end, anything else doesn't make sense.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fixed funny bugs

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
The blackshield ammo disk couldn't produce 7.5 ammo for some reason, so here it is.
fix: fixed a few things
=> Fix blackshield ammo disk

code/modules/projectiles/guns/energy/sst.dm
Title says it all. No longer will you be able to holster a machinegun. Can't believe I have to make this.
=> You can't holster an MG SST

code/game/verbs/ooc.dm
This lets you disable hearing LOOC now. You were able to disable it before, but it wouldn't do anything. Now however it allows you to no longer hear LOOC.
=> Fix LOOC Disable Preference

code/modules/core_implant/cruciform/rituals/path.dm
-Buffs the Lemniscate litanies with the stats they provide from 10 to 15
-Fixes the description error which was previously present due to incorrect path.
Reason for the buff: Compared to other paths Lemniscate is underpowered. Their one gimmick is that they can buff others the like a vector but it lasts for 30 minutes. This is basically useless as vectors do the same thing and  you're typically sticking around the same group of people. This should hopefully strengthen the niche they have a bit more.
=> Lemniscate Buff & Desc Fix

code/modules/projectiles/guns/projectile/automatic/sts.dm
What this PR does : Give you a reason to saw off the STS Heavy Rifle, as before it didn't change the gun's size. Which is the whole reason why you saw a part of it off.
=> Fix the sawn-off heavy STS size

code/game/machinery/bioprinter.dm, code/modules/organs/internal/eyes.dm, code/modules/organs/internal/heart.dm, code/modules/organs/internal/kidneys.dm, code/modules/organs/internal/liver.dm, code/modules/organs/internal/lungs.dm, code/modules/organs/internal/muscles.dm, code/modules/organs/internal/stomach.dm
This PR separate the prosthetic printer and the organ printer with more than just a binary value, so its list of possible organs it can print will naturally be prosthetic organs.
However, due to the fact that several organs were missing prosthetic counterparts (And I was told that Character Creation put regular organs in instead of prosthetic), I added prosthetic lungs, stomachs, livers, and kidneys, based on the prosthetic eyes and heart and using the unutilized sprites. The only one that didn't already have a prosthetic sprite was the stomach, so it still looks the same.
=> Make the prosthetic printer actually print prosthetic organs

code/modules/sanity/sanity_mob.dm
Food and drink is now more likely to level you up with increased odds and likely options if it double roles into it
Drugs are also now more likely to pull form
This should make barkeep and cook more seeked after
:cl:
/:cl:
=> Makes food and drinks more likely for leveling up

code/modules/core_implant/cruciform/rituals/base.dm
-Fixes a broken litany which was commented out.
-Slight description adjustment to give an idea for its duration.
-Also nerfs the litany with: 
--Cost made greater with the original of 15 to new 30. 
--And light level produced from 6 to 5. A lantern's light level is 4.
=> Church flare litany fix + nerf to it

code/game/mecha/mecha_construction/durand.dm, code/game/mecha/mecha_construction/firefighter.dm, code/game/mecha/mecha_construction/gygax.dm, code/game/mecha/mecha_construction/odysseus.dm, code/game/mecha/mecha_construction/phazon.dm, code/game/mecha/mecha_construction/ripley.dm
ALL, and I say all, of the other resources needed to make mechs are 5 sheets. Steel, Plasteel, Gold, Silver, if it was a stackable material, then you needed 5 sheet of it for that step.
So why the hell did you need 4 cable coils?! WHY?!
Anyway now each step that need cable now need five cable coils instead of the previous four.
=> Make all mechs construction need 5 cables instead of 4.

code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/ritual_book.dm
What this PR adds:
1. A base litany that any cruciform bearer can access.
-Makes the book they are holding light up with light level 5
-Costs 15 energy, has 15 min cd, and lasts for 15 minutes
2. Allows the church's ritual book fit within the belt storage slot
Balance thoughts: The closest and easiest comparison is to a lantern. A lantern is easy to get, is slightly dimmer, but it fits into your pocket or the back slot of something you're wearing. The ritual book only fits into your belt slot, where a common tool belt or webbing would go, or has to be held in your hand. 
General thoughts: In general I think its a nice church-flavored addition which provides something useful+cool. If there is any thoughts/ideas/concerns let me know. It has been tested nearly entirely except for the AoE …
=> New Church Litany: Word of Guidance aka Glow Book + Ritual book storage adjustment

code/modules/core_implant/cruciform/rituals/base.dm
For the Word of Guidance litany:
-Makes the litany properly display the message of your ritual book glowing to people around you. Previously it did not.
-This also increases the sound slightly since it was hard to hear.
For the Entreaty Litany:
-Added the bit where you can use it despite stuttering.
Reason: Considering the weight of using this litany where it lets every other cruciform bearer see where you are and that you're fucked its typically used at the last moment, at least in scenarios where I've have to do it. And during the last moments of being alive you're going to be stuttering. If you aren't stuttering, allowing you to use it, you're likely in a situation where you'll survive.
=> Word of Guidance litany bug fix & Entreaty stutter change

code/game/objects/effects/mines.dm, code/game/objects/items/devices/defib.dm, code/game/objects/items/weapons/tools/simple_weapons.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/hydroponics/seed_datums.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/projectiles/guns/oddity_items.dm
-Nerfed knockdown timers on spider traps. Now its 3, down from 8.
-Ire litany is now immensely more easy to resist, with the math being 100% - Vigilance * 3 (minimum 34 to be immune).
-Corrected some typos's in seed datums and bluespace daggers.
-Dying without the rez sickness perk now gives you a permanant -15 to all stats before assigning rez sickness.
-Added an experimental untested function that should fix the issue with low nutrition not slowing you down.
-Powerfist now has a working in-hand sprite when turned on.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Bugfixes, Death penaltie increase

code/modules/organs/body_modifications.dm
Assisted organs are dumb. This remove Assisted Organs
They are repaired like prosthetic organs.
BUT
They aren't affected by EMP like prosthetic organs are.
AND
They get healed/hurt by chems like organic organs.
Not to mention that they aren't mentionned ANYWHERE in the code. Even the Prosthetic organs had 1-2 actual organs coded in.
If you have assisted organs on your characters, fear not! For it shall automatically revert them to organic organs. I tested it.
It will also prevent you from selecting them again.
=> Comment out assisted organs.

code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm
did you know there was code that gave roaches a 70% chance to revive with blattedin...
but it didn't work because the code to run it would only run when the bug was alive, meaning that there was no way to revive with it
this fixes that.
idea: giving roaches a way to revive a few seconds after getting beat to shit if they have blattedin in their corpse (callback?)
bugs about bugs should be fixed
Changelog
🆑
fix: Roaches now actually have their 70% chance to revive if they have blattedin injected into their corpses.
/🆑
=> ports an eris fix to roach revival 6245 - By Hatterhat 

code/modules/reagents/recipes/recipes.dm
Eris had this one right
MLGTASTICa - Water/Pot reaction explosions now get divided by 45 instead of 10 , at 600 reaction amount (bluespace beakers) resulting in a explosion slightly weaker than a cracker.
Trilby - Now makes it so nytro bombs devide by 10 rather then 2 making it not as easy to spam 127 tile bombs
:cl:
/:cl:
=> sometimes good things can not be had

code/game/objects/structures/crates_lockers/closets.dm
Dump_contents happens whenever a closet is destroyed. Changes dump_contents to drop to turf.
Players were getting sent to nullspace before.
Changelog
🆑
fix: Fixes locker destruction.
=> bigpep closet fix

code/modules/biomatter_manipulation/toxic_biomass.dm
Did you know that if you spill biomatter on some floor tiles it vanishes! Cool right?
Well not for when people stop and stare at someone and then falls over dead
:cl:
/:cl:
=> biomatter spills no longer hide under floors

code/game/mecha/mecha_wreckage.dm
Mechs no longer when broke hide under things like catwalks or floors making an invisible shield basically 
:cl:
/:cl:
=> mecha wreckage no longer hides

code/modules/sprite_accessories/_accessory_facial.dm
-Adds the same line of code hair has to allow all species to use it. (Although its not necessary for them.)
-Comments out cindarite horn adorns as they did not do anything
Reason: Some species had species specific facial hair options which are not available to them due to it being locked out.
Simple adjustment for now. Perhaps at a later time I'll take look at a lot of these which are commented out and see if they can be fixed.
=> Allows other species to use facial hair.

code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/priest.dm
What this PR does in a listed fashion:
1. Fixes a bug with the penance litany where it did not work.
2. Hands of Mercy aka Pain relief litany has its effect buffed. Previously it gave the pain killer effect of 15 making it effectively useless for a litany that only Devout get. Now it has been improved to give 50. For reference the self-pain relief any church member gets is only 30. 
3. The light up litanies have been both nerfed. The duration of Words of Guidance has been lowered from 15 to 10. The duration of Holy Light has been lowered from (mistakenly) 50 minutes to 20. The cost of these correlate to the duration.
4. Also a minor spelling mistake fixed.
=> Fixes penance, improves the hands of mercy, nerfs the light producing litanies, and spelling fix

code/game/objects/items/devices/organ_module/active/multitool/farmer.dm, code/game/objects/items/devices/scanners/plant.dm, code/modules/research/designs/prosthesis_implants.dm, code/modules/research/nodes/biotech.dm, sojourn-station.dme
In preparation to the Church FBP, this pr add a researchable implantable Farming Multitool.
It act like the mining multitool, with instead of a single omnitool like the Medical or Engineering implant, it got multiple tools you can choose from.
It got a plant scanner, a minihoe, a bucket, a plant bag and a spade.
I also profited of the occassion to clearly indicate in the code why the plant analyzer take no power.
=> Add farming multitool

code/datums/autolathe/biomatter.dm, code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm, code/modules/clothing/accessories/holster.dm
-Removes the sheath storage from the bioprinter disk
-Adds a better version to it "Absolutist Sword Scabbard"
-Adds all of the cruciform backpack types (satchel, normal backpack, and sport) to the church bio printer disk
-Removes the plain black satchel from the bio printer disk
The better version has the following attributes:
--It goes on clothing like other holsters (why it was added)
--Holds NT swords
--Holds crusader sword
Reason for this change: The previous sword sheath was useless. Sword sheaths can only fit on belt slots. Swords can also fit on belt slots. There is no point to make one or use it at all. So this change make it useful with it fitting onto uniforms. 
All has been generally tested and works appropriately.
=> Church Sword Sheath Adjustment + Printable church backpacks

code/game/objects/items/weapons/storage/costume.dm
-Fixes the Mad Scientist Costume kit (purchaseable from the Portable Stage vendor).
Previously it did not get the items in it. Now it works properly and gets the contents.
=> Bugfix: Mad Scientist Costume Kit

code/datums/setup_option/backgrounds/origin.dm
-Adds in the Northern Naramad background including blurb, limitation to naramad, and stat changes.
Why? Its on the lore page so I don't see why it shouldn't be an in game thing.
Stat changes are rather simple:
+10 TGH
-10 VIG
+5 BIO
-5 COG
Rather light changes compared to others. Free to adjust at a later time but at least its in and can be picked.
Tested and works appropriately.
=> Naramad Background Addition

code/game/objects/items/weapons/storage/firstaid.dm
-Allows for stasis bags to fit into the reinforced triage kit. Does not provide it with one nor any extra space.
Why? Their belts can hold one so allowing the kit to hold one as well is a nice QoL change for paramedics. Especially since its one of the best tools at their disposal.
=> Paramedic Reinforced Triage Kit Adjustment

code/datums/ai/ai_law_sets.dm, code/game/objects/items/weapons/AI_modules.dm
This PR add an Absolute AI Lawset and a board for it, although it doesn't map the board in, so I think only Admins will be able to spawn it or give it to the AI.
The lawset : 
1. All the other laws are of equal priority.
2. Thou shall always aid and comfort a fellow colonist in need, if said comfort will aid them.
3. Thou shall always aid fellow colonists by reciting thy cruciform litanies when requested.
4. A member of the fold shall never harm another member, unless by inaction would an innocent person die.
5. A member of the fold shall never demand of or treat unfairly a fellow member.
6. A member shall not use the Scrying litany on another member without permission, those in the church must respect each others privacy.
7. A member shall never misuse the Atonement litany, nor those …
=> Add Absolute AI lawset

code/defines/obj.dm
This make the handing skeletong model no longer a dense object.
It was just annoying and in the way of the filling cabinet Medical use to store paperwork.
=> Make the skeleton no longer dense

code/game/machinery/rechargestation.dm
- Buff the starting repair platforms by giving them an extra 400 starting repair points, for the grand total of 500 points, or the equivalent of 20 steel sheet compared to the previous 4.
- Remove an exploit, Repair platforms started with a 100 repair points when made, so when they ran out you could just deconstruct and reassemble them.
- Added a check to prevent the repair plateform from spending all its repair points trying to repair a destroyed component that it can't fix.
=> Repair Plateform Fix & Buff

code/modules/core_implant/cruciform/rituals/base.dm
-Word of Guidance FINALLY glows right after you do the litany. No more need to drop it to make it work.
-Holy Light returning it to its original light level (making it brighter).
Based upon personal experience it appears to me that the holy light litany didn't do its purpose of actually lighting up a space well enough.
=> Word of Guidance fix & Holy Light buff

code/datums/perks/job.dm, code/game/objects/items/devices/organ_module/active/multitool/farmer.dm, code/game/objects/items/devices/scanners/plant.dm
Make the plant analyzer take as much as the health analyzer instead of not taking any power at all.
Add a subtype of the plant analyzer that doesn't use power for use in perks or implants.
Change the green thumb perk from using the normal analyzer to the powerless version.
=> Make the plant analyzer take power again

code/modules/scrap/scrap_beacon.dm
The relocation of the scrap beacon to the outside of the colony now poses a greater challenge to the acquisition of essential materials by the Church. The removal of the obelisks makes killing the roaches a much harder task (Especially in the start of a shift) and having to wait for Blackshield or for a Marshall to show up to the gate adds yet another delay, especially in low-pop rounds, not to mention the greater time needed to move piles of roach meat and scrap metal back to the bioreactor.
Halving the scrap beacon's recharge rate does not subtract from this new element of difficult, and instead allows for a more rewarding and fun experience to Vectors who are still willing to excavate through piles of debris amidst the increased danger, especially now that their operation has the …
=> Halves scrap beacon cooldown

code/modules/core_implant/group_ritual.dm
I can't believe it has been broken for _THIS LONG._
Why was it broken? **Cruciform paths.** Thats what broke it. Specifically looking for the type the speaker had.
This PR fixes it. Tested and works appropriately.
=> FIXES THE BROKEN GROUP RITES

code/game/machinery/rechargestation.dm
The issue was that whenever upgrading the repair station, you'd cause the math to go crazy and draw bilions of wats. 
Now it no longer does it.
=> Infinite Power Draw Fix

code/modules/organs/body_modifications.dm
Basically allow players to have Soteria Prosthetics while not in Soteria, Church limbs without being a vector or a prime, and Blackshield without being a trooper or an officer.
Because I really doubt that the factions would go out of their way to force players to change prosthetics simply because they want to cook one shift.
=> Remove departemental restrictions on the prosthetics

code/game/objects/items/weapons/vacuum.dm
Its now longer to use the vacuum so you have a reason to use legitmently any other tool
as the vacuum has endless uses without needing to be refilled
and cleans better then mops
:cl:
/:cl:
=> Vacuum balance

code/game/objects/items/weapons/vacuum.dm
Turns out Eris is bad at balance, 2 tick delay in clicking with vacuums
:cl:
/:cl:
=> Fixes vacuum

code/game/machinery/doors/airlock.dm
<details>
<summary>
Fixes the fact that, when using the janitor's keys to unlock a door, it'd do two do_after checks. Intended (according to a comment), is to have one check for a total of 30s.
</summary>
<hr>
<hr>
</details>
:cl:
fix: Fixed the janitor's keys taking twice as long as they should have.
/:cl:
=> Fixes the double do_after

code/modules/projectiles/guns/projectile/boltgun.dm
Fixes an issue where a runtime would be generated every time a boltgun would be shot by someone with Boltgun Training.
Tested on my server and runs without an issue.
=> Boltgun Runtime Fix

code/game/objects/items/weapons/storage/pouches.dm
Adds in missing items that should be able to be hosteler like cans, bottles breadtubes and bread 
:cl:
/:cl:
=> Corrects baton storage of items

code/modules/projectiles/ammunition.dm, code/modules/projectiles/guns/projectile.dm
Crossbolts and any other ammo now will not magiclly lose their name
Crossbolts and other ammo will now not magically lose their item paths
:cl:
/:cl:
=> ammo names and paths fixed at last

code/game/objects/items/weapons/power_cells.dm
Makes the Omega-Geysers power cell material cost more inline with the other power cell instead of the massive cost.
Small Cell : 1 Steel, 1 Plastic, 1 Silver.
Small Atomcell : 1 Steel. 1 Plastic, 1 Silver, 2 Uranium
Previous Small Omega-Geyser : 5 Steel, 5 Plastic, 3 Silver 1 Gold
Medium Cell : 2 Steel, 2 Plastic, 2 Silver.
Medium Atomcell : 2 Steel. 2 Plastic, 2 Silver, 4 Uranium
Previous Medium Omega-Geyser : 9 Steel, 9 Plastic, 6 Silver 3 Gold
Large Cell : 3 Steel, 3 Plastic, 3 Silver.
Large Atomcell : 3 Steel. 3 Plastic, 3 Silver, 6 Uranium
Previous Large Omega-Geyser : 12 Steel, 12 Plastic, 9 Silver 6 Gold
Which is just exagerated when it only give 2000/200/100 comparted to the cheaper L/M/S cells that only need silver.
New Omega-Geyser Cell cost, those follow the same convention as …
=> Make Omega-Geysers way cheaper

code/modules/mob/living/carbon/superior_animal/defense.dm
Mobs can now be attacked in melee. Issue was that attackby was no longer calling its parent proc. 
Tested on my server.
=> Fixes Mobs being Attacked

code/modules/surgery/internal.dm
Now when we remove an item like shrapnel or non-implant non-organ, we'll drop it to the ground instead of making it fully disappear.
Tested on my server
=> Removed Sharpnel and other Items now Drop

code/game/objects/items/weapons/power_cells.dm
To give a reason for people to print them beyond the relatively low extra capacity, the Omega cell now charge 3 times faster than all the other cells, including Postronic and Atomic Cell.
=> Make Omega Cells charge 3 time faster.

code/modules/client/preference_setup/loadout/gear_tweaks.dm, code/modules/client/preference_setup/loadout/loadout.dm
fluff is hrp
seriously it's actually great since you can now add fluff items without having to bloat code with them + it's still balanced because it's based on loadout items which should all be not-super-powergay anyways
:cl:
add: loadout now has a balaclava + you can now rename/change description of loadout items
/:cl:
=> adds balaclava to loadout + custom name/descriptions for loadout items

code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/construction.dm, code/modules/core_implant/cruciform/rituals/crusader.dm, code/modules/core_implant/cruciform/rituals/inquisitor.dm, code/modules/core_implant/cruciform/rituals/machinery.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/core_implant/cruciform/rituals/priest.dm, code/modules/core_implant/ritual.dm
(Accidentally closed my previous one.) <summary>
Anyways this PR is the same as before.
-Makes all litanies (beside group ones) have a nutrition cost.
-Makes failing the nutrition cost take blood from the user but still successfully casts the litany
-Reduces the energy cost for entreaty litany from 50 to 25
Things of note: Humans have 400 max nutrition and 560 max blood.
So the nutrition cost for litanies has been balanced as follows:
50 for important spells (healing, knockdowns, buffs, etc)
25 for all medium (pain relief, reveal, etc)
10 for low importance. (Sending, light spells, etc)
There is also a cost of blood when you fail to cast a litany while lacking the proper nutrition.
Presently that blood cost is at the same level for whatever the nutrition cost of the litany is.
It has been …
=> Church Litanies General Nerf Added Cost (Trilby's PR but adjusted)

code/game/objects/items/weapons/power_cells.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/power/cell.dm
Field techs and captains of void wolfs no longer rapid fire as their guns physically cant do that
Fixes a small reloading bug with laser guns spawning full cells rather then depleted ones
Fixes reloading messages being nameless making a bit of confusion on who just reloaded  
:cl:
/:cl:
=> cell fix, better reload messages and void rapid fire nerfs

code/game/objects/items/weapons/hydrogen_fuel_cell.dm, code/modules/cargo/packs_medsci.dm, code/modules/projectiles/guns/plasma/hydrogen.dm, code/modules/projectiles/projectile/hydrogen.dm
This make the plasma weaponry more powerful to justify the risks and the cost.
- Boost the damage output from 40 burn (Barely 10 more than the Church's plasma guns) to 100 burn (enough to 3-shot a trapdoor spider.)
- Boost the overclock damage output from 75 burn damage to 150.
- Boost the shot's explosion from 1 power, to 2 power. Doesn't seem that much, but it mean the explosion will actually hurt the target, and not just break the tile in front of them.
- Reduce the automatic cooling time from 250 seconds (or ~4 minutes) to 30 seconds. It still won't keep up with the heat gain if you shoot it constantly.
- Buff the cryo-sealed hydrogen pack to hold enough hydrogen-plasma for 500 shots rather than just 200.
- Made the crates cost 1$ per plasma unit. So the hydrogen pack cost 5000$, and …
=> Buff the plasma weaponry

code/game/objects/random/oddities.dm, code/modules/projectiles/guns/plasma/hydrogen.dm, code/modules/projectiles/guns/plasma/variant.dm, code/modules/projectiles/guns/plasma/welder.dm
In 40k lore, plasma torchs are canonically able to be used as makeshift but powerful weapons.
> A Plasma Torch is a common tool utilised by Imperial engineers and Tech-priests, exploration teams who need to breach multiple barriers, and Space Marine Techmarines. Plasma Torches utilise a controlled plasma arc to make precise alterations when fixing Imperial technologies, although they are more commonly used to cut through impeding bulkheads within voidships. Plasma Torches are capable of cutting through adamantine plating that is up to 20 centimetres thick in a standard minute, and can cut thinner and weaker materials far faster. **Plasma Torches can also be fired as a weapon in a similar way to a Plasma Pistol, albeit at a shorter range and without the ability to fire on maximal mode. …
=> Allow the welder to turn into a gun and back

code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/drone/ai.dm, code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm, code/modules/mob/living/carbon/superior_animal/drone/life.dm, code/modules/mob/living/carbon/superior_animal/fungi/ai.dm, code/modules/mob/living/carbon/superior_animal/fungi/fungi.dm, code/modules/mob/living/carbon/superior_animal/fungi/life.dm, code/modules/mob/living/carbon/superior_animal/life.dm, code/modules/mob/living/carbon/superior_animal/lodge/ai.dm, code/modules/mob/living/carbon/superior_animal/lodge/lodge.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
It give *all* the superior mobs the Follower AI that the Hunting Lodge's pet, the Shroomling and Soteria's handmade bots already had, while changing it to be a bit more streamlined with a few more vars for customization.
- The `obey_friend` var determine if the superior mob only listen to the mobs in its `friends` var or to anyone. By default it is set to TRUE, but the Hunting Lodge's pets have it set to FALSE.
- `following` is simply the mob they are currently running after.
- `follow_distance` is how close do they try to stay from the one they are following, By default it is 2, but the Hunting Lodge's pets have it set to 3.
- `follow_message` & `stop_message` are self-explanatory, it is the message that the mob emote when receiving the order.
- The AI as a whole is less finicky and more …
=> Give all superior mobs the Follower AI

code/modules/mob/mob_movement.dm
Catwalks no longer need mag boots to work as a walkway in anti-gravity 
:cl:
/:cl:
=> makes catwalks help space movement

code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/core_implant/cruciform/rituals/priest.dm, code/modules/reagents/reagents/medicine.dm
**To fix a bug regarding litanies regarding how the painkiller effects are handled,such as never going away, they are solved via this PR.**
-Add in 3 different type of pain relief chems for use in this
-First chem is "Nepenthe"  which provides the massive pain removal for the monomial.
-Second chem is "Anodyne" which provides a medium pain relief.
-Third chem is "Laudanum" which provides a low pain relief
These chems: Do not show up on a scanner, process at twice the rate of normal painkillers (so 0.2 instead of 0.1), and have no overdose limit.
-All the litanies which provide a painkiller effect have been readjusted to these chems with what I feel is an appropriate amount, which is either giving 5 or 10 units of it to the individual(s).
This PR has been tested and …
=> Bug Fix/Adjustment: Adds in church painkiller chems + changes litanies

code/datums/craft/recipes/weapon.dm
Makeshift bear traps are faster to craft
Makeshift bear traps now only need 5 steel + saw rather then 20+saw
=> Makes makeshift bare traps less horrable to make

code/modules/research/experiment.dm, code/modules/research/nodes/biotech.dm, code/modules/research/nodes/illegal.dm
Mind swapper has been moved to be in covert tech
Slime cores now when scanned will give a reasonable sum of points compared to other things like plants or bombs
swaps borg illegal tech and tyrant AI lawset around
:cl:
/:cl:
=> ups slimes points + moves mind swapper to covert tech

code/modules/organs/external/_external.dm
So, turns out that while the rejuvenation proc **does** check if there's implants and make sure not to eject those, it doesn't give a single fuck about augments !
This just add an additional check that should have been made when augments were introduced.
=> Fix Rejuvenation Proc ejecting augments

code/modules/projectiles/guns/plasma/variant.dm
The 'Reclaimator' Bluecross Hydrogen-Plasma Gun now take 10 hydrogen-plasma per shot and lose its infinite cell.
It still doesn't heat up through.
=> Nerf Bluecross Hydrogen-Plasma gun.

code/game/mecha/equipment/weapons/laser_weapons.dm
This PR aims to rebalance the inefficient laser weapon you can mount on exosuits, right now, the cooldown is absolutely enormous, making a shot perhaps every three or four seconds, while the laser-beam itself does twenty damage. For an exosuit mounted weapon, even an inefficient and improvised one, it remains extremely weak. This is even worse considering this is the only improvised ranged weapon that requires no ammo, and while this is an advantage, this is its only. You are better off with a Martin DPM wise.
This change simply halves the cooldown to a reasonable 15. Which should make about two seconds. For record, this is the cooldown of the /heavy/ exosuit laser, which does twice the damage.
:cl:
Welder-Laser exosuit weapon slightly buffed.
/:cl:
=> Making the rigged laser more viable.

code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/unarmed_attack.dm
-Added an attack type called hammer fist to mycus, a subtype that deals +5 bonus damage.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Mycus attack change

code/modules/client/preferences_spawnpoints.dm
The lift, long bed and cryo pod when spawning into them no longer sleep you.
Lasts for to long, annoying and harms RP as when you come up/wake up you might want to talk to the people that are greeting you.
:cl:
/:cl:
=> Spawnpoints no longer sleep you

code/modules/mob/living/carbon/brain/MMI.dm
MMIs now longer get brain damage when emped
Turns out well in a borg, it still procs this leading to killing a borg in like 3 shots of ions even when fully repaired and basiclly round removing borg players
:cl:
/:cl:
=> Update MMI emp

code/modules/mob/living/carbon/superior_animal/attack.dm
Apparently superior mobs deal the waring faction damage bonus as long as they have a waring faction set.
This get fixed in this PR.
=> Fix the waring faction thing.

code/modules/mob/living/carbon/superior_animal/vox/thrown_items.dm
The birbs rocks and spears are balanced around melee armor and thus should use melee armor for is checks
:cl:
/:cl:
=> now properly checks melee armor

code/controllers/subsystems/jobs.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm
Comments back in alt titles, along with adding a handful. Includes a fix to un-break their visibility and payroll courtesy of 
https://github.com/Occulus-Server/Occulus-Eris/pull/161
Additionally! This time it was actually tested and is working properly. 
Scientists -Soteria Xenobotanist, Soteria Xenoarcheologist, Soteria Xenobiologist
Doctors -Soteria Nurse, Soteria Surgeon, Soteria Pharmacist, Soteria Medical Intern
Adepts - Guild Novice
Officers - Marshal Junior Officer
Troopers - Blackshield Cadet
Update science.dm
Update medical.dm
Update engineering.dm
Update security.dm
Update engineering.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Alt Titles payroll/manifest fix

code/datums/craft/recipes/clothing.dm, code/modules/clothing/head/helmet.dm, code/modules/clothing/shoes/jobs.dm, code/modules/clothing/spacesuits/void/station.dm, code/modules/clothing/suits/armor.dm, code/modules/clothing/suits/miscellaneous.dm
- Makes 35 protection the golden standard baseline of a standard security vest for melee/bullets/laser, every armor should have more (if better) or less (if poor) of those stats. Most of the rebalance here is based upon these numbers.
- Flak vests and plate carriers are now more specialized towards protecting against damage rather than being reskins of a  generic armor vest. Values against lasers mostly unchanged.
- Commander and WO vests are generally stronger, reflecting their uniqueness and importance of a faction leader
- Nerfs wooden armor down to handmade armor vest tier (a bit lower in fact) as its stats were TOO good for the materials it takes to make.
- Outsider cloak no longer protects arms and legs, I have no idea why it did but it shouldn't. Tweaked its stats to compromise so …
=> Armor rebalance

code/modules/mob/living/silicon/robot/robot_upgrades.dm
Borg arc welder is more consentant to the crafting of one by hand
Illegal mods for borgs now cost half the diamond it had
:cl:
/:cl:
=> Massively reduces borg arc welder and illegal upgrade

code/datums/outfits/jobs/science.dm, code/game/objects/items/weapons/storage/belt.dm, code/modules/projectiles/guns/plasma/variant.dm, code/modules/projectiles/guns/plasma/welder.dm, code/modules/projectiles/projectile/hydrogen.dm
Since Soteria is all about high-tech stuff, give Roboticists a bit of a new loadout consisting of :
- Electric Screwdriver
- Big Wrench
- Hydrogen-Plasma Welder
- Normal Crowbar
- Normal Wirecutters
- Normal Multitool
- RoboAnalyzer
In addition, it move the cable coil from their belt to their bag, with their analyzer going the opposite way, and adding an hydrogen fuel flask to their bag too. Wouldn't want them to be unable to use their fancy new welders.
*Also I used this occasion to fix a few things with the hydrogen welder, in preparation of allowing them to have toolmods installed.
=> Change the roboticist loadout

code/modules/projectiles/guns/energy/tesla_shotgun.dm, code/modules/projectiles/projectile/beams.dm, sojourn-station.dme
Add a series of shotguns that use tesla relays to drain power from the nearby APCs to recharge their powercell. Come in four variations : 
Normal : Default gun, charge overtime as long as it is in a room with a powered APC.
Manual : Same as normal, but you can pump it to charge 1/5th of a shot.
High-Power : Same as normal, but deal more damage.
Atomic : Same as normal, but has an atomcell instead for when you don't have an APC nearby.
Names and descriptions are subject to change. Sprites **will** change.
=> Add The Tesla Shotgun

code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
Exl snipers no longer make full mags drop when reloading
:cl:
/:cl:
=> makes exl no longer drop full mags

code/modules/reagents/reagent_containers/bidon.dm
Make the Stasis Bidon work correctly.
For some reason it never has the NO_REACT flag which is what prevent chemical reactions from occuring which is the main point of the Stasis beakers & stuff
=> Make the Stasis Bidon work correctly.

code/game/machinery/excelsior/ex_teleporter.dm, code/modules/hydroponics/spreading/spreading.dm
From vode-code
removes three division by zero runtimes,one in ex_teleporter.dm RefreshParts(), one in spreading.dm refresh_icon()
=> 2 runtime fixes form eris

code/modules/psionics/psionic_items.dm
Add a psi injector that can give one psionic point to a psion. Currently a one-use item, but it can be var-edited to give multiple points per use and to have multiple uses.
=> Add the Psi Injector

code/modules/core_implant/cruciform/cruciform.dm, code/modules/psionics/psion.dm
Makes it so that when you have a core_implant, your text bubble no longer disappears. This was because on process we would continously execute an update_implants run. This should also reduce lag (SLIGHTLY) because of of fewer runs of update_implants, which is fewer re-draws.
=> Core_implant Text Fix

code/modules/dungeons/junk_tractor_beam.dm
Contributor
hyperioo
If people were teleported outside the JTB border because of a teleportation incident, they were unable to get out of there without admin intervention. Now they can just walk toward the edge and they will be teleported back inside.
=> [JTB] Fix people being unable to get back in

code/game/machinery/doors/airlock.dm
Contributor
zombiemimic
More or less makes glass doors weaker then normal doors + makes shooting most doors less viable to help get people to do none shooty into roomy!
=> Ups airlock health

code/game/machinery/tesla_turret.dm, code/modules/mob/living/simple_animal/simple_animal.dm
Allow the tesla turret to actually *deal* damage to simple mobs such as mice or diyaab.
Also make it so that the turret don't attack dead mobs.
=> Allow the tesla turret to damage simple mobs

code/modules/maint_expeditions/adms.dm
Corrects disks when ejected staying in the content list in a ADM meaning when you deconned it, it would teleport back to its spot
=> Disk correction ADMs - tested to work

code/datums/perks/racial.dm, code/modules/modular_computers/computers/subtypes/preset_console.dm
Remove the cooldown on the mycus follower perk so that it is less laggy. Still one-use though. I am not making the perk delete itself because the description is still useful.
Make the nanobot's console start with a strong LED because I forgot about it.
=> smol fixes

code/modules/mob/living/carbon/superior_animal/xenomorph/attack.dm
the bull xenomorph now properly checks the targets perks to see perks.
=> Bull knockdown checks

code/game/objects/structures/crates_lockers/closets.dm
Removes a loop in destory фor lockers to stop the MC фorm crashing
=> removes loop

maps/CEVEris/_Nadezhda_Colony_Surface.dmm
Prospector map additions!
Three, abeit cruddy, sleeping areas!  Boss Hogg doesn't wanna spend too much on these Scavs.
A more secure holding area for weapons, items, explosives, and the Lathe was moved in there too.   The Marshals can now stop sweating when they see a thousand weapons when they walk past the doors.
Scav shop! Come buy some questionable weaponry from questionable people.  Don't steal, or you may find yourself lost in maintenance!
Additional toilet areas.  Because they are smelly people.
Fixed Prospector and Scavenger spawns, they're now the right way around!
Surface east-side maint has been expanded, and is now more accessible.  Lets hope this is the start of a great new thing.  
Surface Office has been moved around to accomodate those pesky scavengers, however in the …
=> Prospectors area update + Minor Surface jiggery pokery

maps/CEVEris/_Nadezhda_Colony_Surface.dmm, maps/CEVEris/_Nadezhda_areas.dm
Blackshied armory now looks better, nothing new or removed
Sky teleporter area now has its own area APC/atmos
Propis prep now has random amouts oф starter materal so they can use their disk/make basic things - In return the random spanws oф their spare guns spawners have been converted to low odd spawners
adds a closer ATM to the propis shop
lower odds spawner on one oф the three random фirst aid kits get
фixes a bad missing pipe
just look into those words, cant say no to that!
=> last фew mapping corretions фor now

code/modules/paperwork/paper.dm
Klutz now when renaming paper rather then prevent you, deals 1 damage.
=> Klutz no longer prevents naming papers

code/game/objects/items/weapons/hydrogen_melee.dm, code/modules/nanogate/nanogate_powers.dm
- Make the Nanogate 'Message' power compatible with non-deadmins admins.
- Make the Nanogate 'Message' power ceck for manniquins and remove the user of the power from the list.
- Give the Hydrogen Sword a sound effect when hitting something.
- Make the Hydrogen Sword & Grenade have a special effect when exploding.
- Nerf the Hydrogen Sword Heat Wave range from 2 to 1.
- Nerf the Hydrogen Grenade Heat Wave range from 3 to 2.
- Buff the Hydrogen Grenade's throw range from 5 to 7.
- Make the Hydrogen Sword a tool with 25 Welding, 25 Cauterizing and 50 Cutting when turned on.
- Make the Hydrogen Grenade play a sound when being armed.
=> Fixes for nanogate and sword

code/__DEFINES/perks.dm, code/datums/perks/nanogate.dm, code/modules/nanogate/powers/user.dm, code/modules/organs/internal/nanogate.dm, code/modules/projectiles/guns/mods/mods.dm
- Add a check that prevent synths from using the nanite chem power that they wouldn't gain any benefit from.
- Make the faulty mechanism work again.
- Add two nanites power : 
- Ammo Box : For 1 point, give the user a perk that allow them to spawn an ammo box every 30 minutes. They can choose the type of box that spawn.
- Modifications : For 1 point, allow the user to spawn a designated tool/gun mod, with the exception of AIs, Greyson, Bluespace and Faulty stuff. It is the only power that is usable more than once, costing 1 point per activation.
=> Add Nanites Powers

code/modules/mob/living/carbon/human/update_icons.dm
- Allows items that have a back icon to show that icon when equipped in the belt slot. 
- Fixed an issue where BELT_LAYER_ALT was not refreshed when refreshing belt layers, which would cause belt icons to remain on you if you had them over your suit even after taking the belt off. 
Tested on my server, everything works fine and dandy.
=> GunsOnBelts

code/game/gamemodes/storyteller_meta.dm, code/game/machinery/autodoc_excelsior.dm, code/game/objects/effects/spawners/gibspawner.dm, code/modules/clothing/accessories/holster.dm, code/modules/clothing/spacesuits/rig/modules/storage.dm, code/modules/mob/living/carbon/human/inventory.dm
Fixes Holstered weapons with the automatic firemode breaking when unholstered
Also likely fixes a lot of bugs caused by put in active hand lacking the swapped_to proccall
Credit to Bruh Momentium / Roma for giving me a very reliable test case to replicate the issue with
tweak: Gibbing roaches now makes 3 splatters instead of 5. - This is a lag improvement
fix: The storyteller refusing to storytell
fix: Fixed being able to put RIGS inside Themselves , causing them to disspear.
Fixes the relaymove proc using usr , and not user , resulting in edge cases where the player wouldn't get out , fixes the else if wall making the code better to read, renamed some variables to be more explanative to what they are , fixes the style inconsistencies where some procs use src. but some don't.
=> Mlgtastica 1

code/modules/psionics/greater_powers.dm
Add a confirmation to Journey to Nowhere in order to prevent people from accidentally teleporting themselves.
Improve a bit of code behind the three oddity-weapon powers.
=> Add confirmation to Journey to Nowhere

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/airlock_control.dm, code/game/machinery/doors/door.dm
Removes all doors from processing , cutting down around 1500~ machinery from 10000 machinery processing roundstart
Very likely will break in edge cases i can't test or even think of
Holy fuck why do we still process every fucking door this is 2021
Changelog
🆑
fix: Fixed doors processing
/🆑
=> Makes all doors not process  by Contributor MLGTASTICa 

code/modules/psionics/psion.dm
Make the psionic organ be a little more precise when checking for implants and prosthetics. Hopefully it fix the issue of held implants being deleted.
=> Fix the psionic organ deleting held objects

code/modules/client/preference_setup/loadout/lists/clothing.dm, code/modules/reagents/reagents/medicine.dm, maps/CEVEris/_Nadezhda_Colony_Underground.dmm, maps/encounters/deeptunnels/_Nadezhda_Deep_Tunnels.dmm
-Buffs Carthatoline to purge the following chems: 
The ones dylo does:
--pararein
--carpotoxin
--toxin
EXTRA PURGES Carth also gets:
--stoxin (sleep toxin aka soporific)
--zombiepowder
--xenotoxin
The one thing carth will be lacking though, compared to dylo, is the anti-sleepy effects. **But** it purges the chems and more so that means its better. It IS supposed to be the upgraded version... Let me know if there are any other common animal toxins that I've missed in adding. (Did this because people whined and are too lazy to do it themselves.)
-Loadout additions
A variety of masks have been added to loadout. Several animal types that carry no mechanical benefit, all of them costing a single point. The eris clown gasmasks (costing 2 points much like normal gasmasks), …
=> Carth Buff, Loadout Additions, Map adjustments

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm
corrects dispolies pipes
corrects wire messess up
shiфts around some maints spawns and makes it less likely to walk into halls
corrects some camera's and adds more to the new blind spots that were added
corrects missing blast doors
corrects missing vender(s)
re-adds missing mainst biogenerator board
corrects some other misc things
=> Trilby's map corrections

code/modules/psionics/psionic_items.dm, code/modules/reagents/recipes/recipes.dm
-Cerebrix inhalers now take 40/40/40 cerebrix/water/silicon but now have 4 charges instead of one. Returns are now 50% instead of 33% (you get more essence per spent cerebrix on inhalers now).
-Wiki updated to reflect this change.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Cerebrix QoL Change

code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/game/objects/items/weapons/gift_wrappaper.dm, code/modules/clothing/head/helmet.dm, code/modules/economy/price_list.dm, code/modules/trade/datums/trade_stations_presets/cybernetics.dm, code/modules/trade/datums/trade_stations_presets/hellcat.dm, code/modules/trade/datums/trade_stations_presets/nt_cruisers.dm, code/modules/trade/datums/trade_stations_presets/trash_refine.dm
The scrap ship now dosnt get as much trash piles
But has more trash random spawner types and prices depending on the type
Corrects a ton 0 price items
Corrects bad lists
Corrects wrong guns
Marshals and blackshield disks now have landmines
exl disk cloner can now be printed by the exl disk
=> re-balance scrap trade + misc corrections

code/modules/reagents/reagent_containers/food/snacks/meat.dm
Quick clot was spelled without a c in it. Should be in the meat now.
=> Typo Fix in Birb Meat

code/game/machinery/autolathe/fabricators.dm, code/game/objects/items/weapons/tools/bonesetters.dm
Removes sleep checks on bullet printer to use the much more optimized spawn
swaps 1-0 to TRUE FALSE
Adds missing ammo
Makes printing things way better and more streamlined
Makes getting points via max stacks on materals way quicker
corrects adv bone setter sprites
=> makes bullet printer not shit

code/datums/craft/recipes/lodge.dm, code/datums/craft/recipes/storage.dm, code/datums/perks/job.dm
-Leather pouches have been moved to a lodge recipe, as having it universal made pouches so simply to get that 2 seperate factions could mass produce them with such ease that it made them a joke to get. Unfortunate, but its for the better balance of the server.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Unpopular Fix

code/controllers/subsystems/jobs.dm, code/game/jobs/department.dm, code/game/jobs/job/captain.dm, code/game/jobs/job/church.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/job.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/offcolony.dm, code/game/jobs/job/prospector.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/modules/admin/admin_verbs.dm, code/modules/client/preference_setup/occupation/occupation.dm, code/modules/mob/mob.dm
We now enable the last part of time tracking, namely the locking. You can check how much time you've played in each job under IC. Currently need to have played 20 hours in that department to be able to play the head of staff, or 20 in the council in general to play Premier and Steward.
Tested in my own test environment (a lot of times). Things should work as expected.
=> Time Tracking 2.0

code/datums/craft/recipes/lodge.dm, code/datums/craft/recipes/storage.dm, code/game/objects/items/weapons/storage/pouches.dm
- Re-adds the small leather pouch to be a craft available for everyone.
-  Lowers the cost of crafting for the medium and large pouches.
- Adds a space for proper grammar.
- Lowers the credits worth of leather pouches a bit.
Reasons why I changed this:
Nobody will make a small pouch when they can make a medium or a large. And the leather small pouches look nice, so I want them to be used, somehow. Allowing it to be crafted by everyone means that colonists and outsiders will have a way to make a simple storage container, through appropriate effort, which still doesn't beat the best.
The crafting cost change was simply too high, so I lowered it. Credits worth has been lowered slightly, if that is considered to be an issue.
Let me know what/how/why things are good or bad …
=> Simple Pouch Changes

code/modules/admin/admin_verbs.dm
One letter messed it up and made it so that you'd change your own bypasses instead of the target's. Caused false positive results in testing.
Tested and all that.
=> Bypassing fix

code/modules/projectiles/guns/projectile/boltgun/flaregun.dm
Disallows Dazzlation on getting overshooters, baynet sharpening and silencing
=> Gun tag correction

code/modules/mob/living/carbon/superior_animal/vox/thrown_items.dm
The voxes in the jungles rocks and spears now have drop
The voxes protectiles are way slower now to be avoidable in the tight weaves in the paths
=> Birds no longer cheat

code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm, code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/types/colony.dm
Make the aether mining bot have to be manually activated so that it doesn't move as soon as the game start.
=> Make the mining bot have to be manually activated

code/modules/mob/death.dm
Suggested by CDB
When a mob dies, the close by mobs wake up.
=> anticheese

code/game/machinery/turret_control.dm
Well still cheating the advanced turret now shoots ever second rather then .5 seconds
=> advanced turret now take 1 second to shoot

code/datums/craft/recipes/tools.dm
By
Omni44
Tweaks recipe for expanded fuel tank to still be mildly time consuming to craft but without requiring welder pack, which iirc can't be even printed or anything, and hardly ahs place in game regardless.
=> Easyer expanded fuel_tank making

code/modules/surgery/surgery.dm, code/modules/surgery/surgery_ui.dm, nano/templates/surgery_organ.tmpl
By
SirRichardFrancis 
Added "remove shrapnel" button to surgery UI, it's not visible when there is no shrapnel to remove.
Requires hemostat / wirecutters and skill check that is harder than diagnostic check.
=> Shrapnel anti-age

code/modules/projectiles/ammunition/magazines.dm
By
MLGTASTICa
Linked ammo boxes are now normal size rather then small, as they are a box and not a magazine
=> Ammo linked crate correction

code/modules/projectiles/guns/projectile/boltgun/flaregun.dm
The dazzlation no longer has 27 melee damage
=> dazzlation tweaks

code/controllers/subsystems/inactivity.dm, code/game/jobs/job/job.dm, code/modules/organs/external/_external.dm
Fixes the following runtimes:
1. A runtime in inactivity where we were calling on null.
2. A runtime in job.dm where we were calling on a null ckey
3. A runtime in organs where a muscle that was fully destroyed would divide by 0
Tested and all that, shouldn't cause issues.
=> RuntimeFix225

code/game/objects/items/weapons/storage/belt.dm, code/game/objects/items/weapons/storage/briefcase.dm, code/game/objects/items/weapons/storage/toolbox.dm, code/modules/detectivework/tools/crimekit.dm
Detective kit now holds 12 items rather then 14
Detective kits now can go on belt slots
Suitcases can once more fit in bags and backpacks/duffles but cant hold bulky anymore.
Red and Black toolboxes are also improved
they are well basiclly like a harness, have a major draw back in that you cant bag it to then put a larger item in its place
Harnesses now hold 14 items like the old detective kits but its only small items, well still allowing gas masks and helmets to allow rp and the like
=> the suitcases/harness changes

code/modules/reagents/machinery/chem_dispenser.dm
the t2 upgrade to booze dispeners now properly gives "ethanol"
=> ethonal upgrade

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/living_defense.dm
Move the pain given by being set on fire after the check that verify if you get hurt from being set on fire.
You'll still agonize for half an hour before dying if you don't wear any protection, but at least you won't go unconscious if you do have protection.
=> Move the pain of being set on fire behind the fire check.

code/modules/power/antimatter/control.dm, code/modules/power/antimatter/shielding.dm
The Antimatter Engine will notify Engineering when the stability is less than 75%, Command when less than 50%, and will announce it on general when the stability is less than 25%.
=> Add radio message to AME instability.

code/datums/craft/recipes/guild.dm, code/game/objects/items/weapons/storage/belt.dm
-The artificer guild now crafts a unique webbing instead of the generic webbing, it holds 12 items (down from 14) but can take normal sized items.
**Editor's Note**: The changes to webbing made this crafting recipe completely worthless and given most guild need to carry the basic 7 + hammers, drills, saws, and spare cells this webbing is actually viable for them. It can also be crafted for other purposes, if somene wants da good stuff in terms of belt storage with size.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Guild Belts: The Unshittening

code/game/objects/items/weapons/storage/belt.dm
Guild belt by default is same as all other belts, but can be right click and adjusted into the three modes - 
Large storage, 6 Bulky items, such as powerhammers and other larger tools
Normal storage, 9 Normale size items, like old belts
Small Storage, 14 Small items like current belts are
Modularity that will outshine the standard harness
=> guild belt rebalance

code/game/objects/items/stacks/medical.dm
By TheShown911
Fixes a bug where advanced trauma kits and bandages could be spamed and used multiple times on a bandaged wound.
By Trilby
Massively increases kits healing to account for spamming bug corrected
=> medical kit rebalance

code/modules/mob/living/carbon/human/life.dm
Title
:cl:
fix: Nanogate regen now applies to synthetics, as implied by the wiki.
/:cl:
=> Fixes nanite regen to work on synths (as wiki intended)

code/modules/research/designs/illegal.dm, code/modules/research/designs/medical.dm, code/modules/research/designs/mining.dm, code/modules/research/designs/rigmodules.dm
Retires the mining tab in rnd designs
Moves all rig moduls and rigs to their own tab
restorts some items to make more logical sence
massively lowers SI tool's cost to print
=> restorts and and condendes rnd designs

code/game/objects/items/weapons/tools/_tools.dm
Batons when upgrade dont massively nerf themselfs
=> baton upgrade hotfix

code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
Spiders now will properly check if they have hit you when injecting spiderlings, rather then it assuming it is
=> Makes nurses unable to use magic

code/modules/projectiles/ammunition/bullets.dm
.50 and 7.5 laser ammo no longer stores their matterals in the bullet
=> Fixes some bad materals in bullets

code/modules/cargo/packs_security.dm
Renames the bull crate in cargo to stop confusion
Adds the new Laser Show crago crate that has two super good cells and a lasercore with a heat sink for 1850
=> small name change and new crate

code/game/gamemodes/scores.dm, code/game/jobs/department.dm, maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm, maps/CEVEris/centcomm.dmm
Fixes LSS score, if this dosnt get merged ill just make a new pr with the singular fix
Drastically increases starter funds of every department
Removes most drip feed free money to help incentives departments paying one a other and using the credit
Marshals/Blackshield still get 1.5k an hour to try and not drain the most played department 
Adds account balance terminal to Preimer room, this allows them to monitor against fraud, see payments and termitate dead accounts and deal with det better
=> rebalances ecom a bit + a score fix

code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
The melee void wolf now has their proper armor, rather then none at all
=> Fixes void wolf armor

code/modules/mob/living/carbon/human/human_damage.dm
Fixes the adjustBruteLossByPart function to be affected by brute_mod_perk instead of burn_mod_perk
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes the adjustBruteLossByPart function to be affected by brute_mod_perk instead of burn_mod_perk
/:cl:
=> Fixes the adjustBruteLossByPart function

modular_sojourn/cardgame_2.dm
=> Card doup correction

code/game/objects/items/weapons/material/knives.dm, code/game/objects/random/contraband.dm, code/game/objects/random/oddities.dm, code/modules/projectiles/guns/oddity_items.dm
Retires finger of god, frenchmen and light show laser SMG form the bluecross spawn pool
Places the frenchmen onto switch blade spawners
reduces frenchman backstab damage to not be bluecross levels
Gives all bluecross spawn weapons their own price tag to be worth selling to cargo
fixes the orge clubs materals so it no longer gives just plastic and metal
=> prices and matterals

code/modules/psionics/psionic_items.dm
Mage shield can no longer be back slotted nor in belt slot
=> Mage shield fix

code/modules/mob/living/carbon/superior_animal/defense.dm
Superior mobs like roaches, spiders, xenos no longer depressurize atmos
=> maybe huge lag debuff

code/modules/organs/blood.dm, code/modules/organs/external/_external.dm, code/modules/organs/external/damage.dm, code/modules/organs/internal/_internal.dm, code/modules/organs/internal/internal_organ_processes.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes some variable typos for get_process_efficiency
Changes the heart's blood volume equation to an identical one that is easier to look at.
Changes the get_tally() function for including nerve an muscle efficiency. Only thing changed between this equation and the old equation is a .25 modifier on muscle efficiency. So minor it won't be noticed. (it still doesn't do much)
Changed the take_damage function to account for bone efficiency when deciding whether to fracture a bone, like it does when an organ takes internal damage.
Overall just gives us an easier read of organ efficiency values
/:cl:
=> Very slight Organ Efficiency changes and bugfixes

code/game/objects/effects/effect_system.dm, code/modules/reagents/holder.dm
By Kegdo
/datum/reagents/Destroy() does everything /datum/reagents/delete() does and more, and delete() is called only from /obj/effect/Destroy() which ITSELF is redundant with its parent /atom/movable/Destroy()
=> ports some micro opimation

code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
When a dense mob dies it now will properly be density = 0
=> spooder wall fix

code/modules/mob/living/carbon/superior_animal/superior_animal.dm
My best attempt for now at the least greedy way of flipping superior mobs back to their normal icon states.
Tested and works on my server.
=> Superior Mob Flip Fix Non-Greedy

code/datums/perks/nanogate.dm, code/game/objects/items/weapons/tools/mods/mod_types.dm, code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm, code/modules/nanogate/powers/user.dm, code/modules/organs/internal/nanogate.dm
Nanogate no longer gives biomatter
Nanogate rnd and materal levels are way higher!
Nanogate fabrication has been tweaked, removing mods and ammo that contain explosives or biomatter
Nanogate ammo fabricator can no longer make ammo packets that are laser based
Nanogate ammo fabricator can no longer make fire shot shells or large shotgun crate mapping box flare box
Nanobot can no longer be harvested in to get the best console gear in the game. SAD (prevents soft locks and balance issues to get a console bigger then the bot popping out of a small drone)
Guild armor plates now have the materials it takes to make them inside them (no more getting 30 platium when making an item that costs 3)
=> Nanobot balance and fixes

code/modules/projectiles/guns/projectile/boltgun.dm
Bolt guns now give more feedback when failing to load it
Bolt guns no longer can take caseless ammo do to it bugging the gun
=> some bolt gun banaid permient fix

code/game/objects/items/weapons/nt_melee.dm
Nerfs flanged mace to not be a direct upgrade to longswords
Nerfs church warhammer to not be a directly better halberd
fixes an oversight that made the mace and war hammer being cutting tools
=> slightly sainer numbers

code/game/objects/random/mob/misc.dm, code/modules/genetics/creatures/wasonce.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/life.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm
-Temporarily disabled shoggoth class enemies from spawning and the fade/appear functions for psi-mobs as both were determined to be bugged. Will develop a work around tomorrow, just really tired after coding all day and running the event.
-Fixed a sound issue with psi mobs attacking.
-Fixed a air pressure issue with psi-mobs that made them progressive take toxin damage.
-Fixed a typo in the ponderous.
TODO:
-Fix and then re-enabled the shoggoth class psi mobs.
-Find a more server resource viable fade/appear method.
-Add the custom ambiance for deep maints (has some odd musical choices, which will require me to test it carefully.
-Add more voice lines to the various deep maint mobs.
-Remove kebab.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Minor fixes and temp additions

code/modules/projectiles/guns/energy/cog.dm
When the cog is on back, it now will have its proper icons
=> fixes cog on back sprites

code/datums/craft/recipes/storage.dm
Unlike the guilds fancy better verson the normal sheet snatcher should be availed to most roles that get scrap tools or can crate them for easier storage in line with other storage means
=> Lowers sheet snatcher screwdriver costs

code/game/machinery/doors/airlock.dm
When a tool is wedged into a door it now will take damage rather then healing
=> makes door crushing accully damage the tools

code/modules/projectiles/ammunition/bullets.dm
Makes 408 laser bullets cost more in line with ever other laser type
=> 408 laser bullet cost fixes

code/datums/craft/step.dm
So what basiclly makes the runtime and bricks the crafting is when ever a non-tool gets put onto a tool step making it unable to complete the proc or something when clicked and drag onto ut without being any other thing thats checked and returned beforehand.
=> Fixes the rare crafting big - By Sieg

code/modules/projectiles/ammunition/magazines.dm
The metal speed loader no longer gives biomatter
=> no more magic speed loader biomatter

code/modules/modular_computers/hardware/portable_hard_drive.dm
The coin disks are no longer a virus
=> fixes a virus

code/game/dna/dna_modifier.dm
Small oversight with old genetics consoles not needing a cog check
=> console now needs cog in old genetics

code/game/machinery/vendor/weapon_vendors.dm, code/modules/core_implant/cruciform/rituals/base.dm, code/modules/projectiles/guns/energy/cassad.dm, code/modules/projectiles/guns/energy/mindflayer.dm, code/modules/projectiles/guns/energy/nuclear.dm, code/modules/projectiles/guns/energy/plasma.dm, code/modules/projectiles/guns/energy/railgun.dm, code/modules/projectiles/guns/energy/tesla_gun.dm, code/modules/projectiles/guns/energy/tesla_shotgun.dm, code/modules/projectiles/guns/plasma/hydrogen.dm, code/modules/projectiles/guns/plasma/variant.dm
-The cassad now requires 2 hands and cannot be duel wielded.
-The mindflayer now requires 2 hands and cannot be duel wielded.
-The AEG now requires 2 hands and cannot be duel wielded.
-All plasma based church weapons can no longer be duel wielded and require two hands.
-All pistol sprite hydrogen weapons can now be duel wielded and used with one hand.
-The tesla shotguns and all subtypes now require you to 2 hand them.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Energy Weapons: Twohand and can_duel

code/modules/cargo/packs_engineering.dm
Simular to steel, glass, and plasteel, adds in both bulk and normal 120 sheet buying of the basic plastic, this is more exspensive then buying steel do to steel needing 2 ores rather then 1 to make and plastic needing just smelted carbon.
Or doing chems to make endless plastic. qol on cargo/colony and miners
=> Adds plastic to cargo buying

code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/recoil.dm
disarming adds recoil that scales off of ROB
your own ROB negates some of recoil damage
you need 60+ recoil to disarm
80 if item is wielded!
the CRAZY formulas, made up by Humon
rob_attacker = (50 / (1 + 150 / (min(1, attacker robustness))) + 40) - soft capped amount of recoil that attacker deals
rob_target = max(0, min(400, target robustness)) - hard capped amount of recoil the target negates upon disarming. 400 - no recoil
recoil_damage = (rob_attacker * (1 - (rob_target / 400))) - recoil itself
By Kegdo and Humonitarian
add: disarm deals recoil, scales off of ROB from both the attacker and target, wielding matters
=> ports removal of disarm spam

code/modules/genetics/genetics.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
SHOULD fix a bug where multiple active on_clone mutations in a single genetic sample caused the cloning vat to runtime.
/:cl:
=> Allow multiple cloning mutations to be active in a single sample plate

code/modules/maps/tg/reader.dm
By Shadow-Quill
Adds extra debugging info for the reader.dm runtimes.
=> Gets extra info on the reader runtimes

code/modules/admin/tickets/adminticketsverbs.dm, code/modules/admin/view_variables/topic.dm
Allows devs whom ALREADY can VV and ALREADY edit, but not in the same menu, actually edit and VV at the same time.
Allows devs to use the ticket system to actually fix and collect data on reported bugs in game so were not legit useless to players unless they ask us in dms or an mod tells us about their issues.
=> seizes power, aka let me do my job

code/modules/genetics/creatures/ambusher.dm
The ambusher mob is more optimized to not runtime, and not take up as much processing when around
=> Less laggy ambusher

code/modules/mob/living/carbon/human/human_attackhand.dm
Creates a soft cap on unarmed damage starting at 80 robustness (roughly 12 points of damage per punch) You can still gain damage beyond that point but its much smaller. -Tested-
=> Unarmed damage soft cap

code/ATMOSPHERICS/components/unary/vent_scrubber.dm, code/modules/clothing/suits/greatcoat.dm, maps/DeepForest/map/_Deep_Forest.dmm, maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
fixes bad tiles
fixes bad areas
removes some maintance mechinery that is un-used and processes to get even the slightlest more optimation
redoes the layout for the garden - willson approved
removes a spare preimer cap
does a todo
adds more traps to the jungle
adds missing t3 parts to preppers
Moves some chargers to be useable in scav prep
moves the LSS plasma plasma tag oddity to blackshield
=> map fixes and tweaks

code/modules/research/experiment.dm
Doesn't actually affect the Nitroglycerin explosion in any way. However changes the kinetic explosion scanner.
Scanner now looks for a randomized number between 1 and 20 (found by just looking at it), and your job is to provide an explosion as close to that number as you can.
FUN FACT: There is a inverse correlation between the temperature of the 02 used in a TTV bomb and the power of the explosion.
Coders Note: So, when I first discovered that Nitroglycerin bombs not only were counted by the explosion meter, but was also stackable, I thought it was awesome because SCIENCE! Unfortunately, this quickly resulted in three problems.
1.) It broke Toxins. Corn bombs were (and still are) a source of large Research Points. Far more than traditional Toxin bomb making could ever dream of keeping up …
=> Risikio "Breaks" Corn Bombs

code/game/objects/items/weapons/tools/mods/_defines.dm, code/game/objects/random/contraband.dm, code/game/objects/random/guns.dm, code/game/objects/random/materials.dm, code/game/objects/random/medicine.dm, code/game/objects/random/oddities.dm, code/game/objects/random/rig.dm, code/game/objects/random/tool_mods.dm, code/game/objects/random/tools.dm
the scav perk that lets them get a fancy item in the trash pile now, always should spawn an item if they get the coin flip
adds more to the fancy item list to add more randomness
=> Scav rng improvements

code/datums/perks/job.dm, code/datums/setup_option/backgrounds/origin_upbringing.dm, code/game/objects/items/devices/flash.dm, code/game/objects/items/devices/lighting/toggleable/flashlight.dm, code/game/objects/items/devices/scanners/health.dm, code/game/objects/items/weapons/grenades/grenade.dm, code/game/objects/items/weapons/handcuffs.dm, code/game/objects/items/weapons/material/kitchen.dm, code/game/objects/items/weapons/melee/energy.dm, code/game/objects/items/weapons/shields.dm, code/game/objects/items/weapons/swords_axes_etc.dm, code/game/objects/items/weapons/tools/screwdrivers.dm, code/modules/assembly/mousetrap.dm, code/modules/mob/living/silicon/robot/analyzer.dm, code/modules/paperwork/paper.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/guns/breacher.dm, code/modules/reagents/reagent_containers/syringes.dm
Klutz is a horrible perk based on pure RNG and being utterly awful to have.
So I toned it down meaning that people will not have much of trouble of having it but still a decent chance of failing of doing certain actions.
Also, re-balances the klutz Upbringing.
</summary>
<hr>
<hr>
</details>
:cl:
add: Klutz upbringing has their stats balanced, and they can perform way more task without having a ridiculous chancing of fail.
/:cl:
=> Rebalances klutz

code/modules/research/experiment.dm
Toxin bomb target range has been greatly tweaked to give actually achievable numbers with toxin bombs
=> More achiveable numbers

code/modules/reagents/reagent_containers/glass/bottled_chemicals.dm, maps/DeepForest/map/_Deep_Forest.dmm, maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm, sojourn-station.dme
Removes and replaces the sleepers, and chem dispenders in void wolfs. Replacing them with more medical gear and bottled chems rather then the boards needed to produce endless chems
Fixes a deepmaints spawn
Flips the lifts and improves the stairwell hallway to look better
Makes tunneling harder into GM room silently
=> map things that are approved

code/modules/detectivework/tools/crimekit.dm
Detective kit has been rebalanced to better suit detective work then general storage
Detective kit wasnt meant to stick 12 first aid kits, or 12 guns or any sort of thing like that. So now it holds 21 (3 rows) of detective gear and some other basic things
=> Fix detective kit

maps/DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm, maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
moves blackshield ammo disk to the autolathen so people can get ammo - highly requested
moves some ammo to their right location
replaces the toxins R-walls with rocks to prevent nuking and scrapping the metal
improves toxins layout to be more useable and resetable
=> fixes and improvements

code/game/machinery/alarm.dm, maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Turns off Vent pumps by default when hooked up to the air alarm, turning on when in panic mode or cycling. When combined to a map edit to replace all vent pumps with an 'off' state version, Should have an appreciable effect on the lag situation.
/:cl:
=> Turn off vent pumps via air alarm

code/datums/perks/job.dm, code/game/machinery/doors/door.dm, code/game/objects/structures/window.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/mob/living/simple_animal/hostile/huntersprey.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/tables/interactions.dm, interface/skin.dmf
By Kegdo
add: diving, sliding, rest while moving, hold rest to move
add: resting hotkey - C
tweak: parkour perk reduces the time it takes to stand up
tweak: can't stack resting action anymore
Tactical Combat design doc PR stage 1
Rest hotkey - C
Can't stack resting action anymore
You can dive and dodge now, based on rest(more info in the video in discord, too big to post here)
Removed bay leftover SHEET ROLLING PROC
Parkour perk reduces the time it takes to stand up
Diving is a 1-tile JUMP(you can bridge gaps!) which lets you pass over tables, so you can vault over a table and cover. Press C(rest) while moving. You may continue to hold down C after a dive to preserve your momentum and slide. This will allow you to close a few extra tiles at an increased speed until you run out of …
=> Tacticoool

code/modules/clothing/under/miscellaneous.dm, code/modules/projectiles/projectile/bullettypes.dm
<details>
<summary>
General outline; The idea of these changes are to maintain roughly the same PVE experience while making HV/HP more niche(and subsequently more effective when used properly). As it currently stands, HV is the hottest kid on the block. This change won't make HV less useful, but it will force consideration. .408 SLAP will tear through someone in bulletproof armor, but if you bring it out against the scav in hand-made plate? You'll see better performance from ball with its more balanced performance. 
(also includes a small fix for a bug related to change_appearance for BDUs)
<hr>
.35 standard
Dam: 16
AP: 5
.35HP(the small numbers here made it hard to make meaningful change.)
Damage:18->22
Agony:20->18
AP: 0
,35HV
damage and AP reversed, against mobs this means the same …
=> Bullet balance changes.

code/controllers/subsystems/trade.dm, code/modules/trade/datums/_trade_station.dm, code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm, code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm, code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm, code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm, code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm, code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm, code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
By Pink
Fixes some older code and betters the trade code
Fixes trading air tanks as full
Balances having every trade station to needing use the favour system rather then having them all unlocked shift start - as intented by eris
More balanced trades and items and lowers some prices on things
=> trade station fixes and balance

code/game/objects/items/weapons/tools/scalpels.dm
-Advanced laser scalpers now cost 1 plasteel, 2 plastic, and 1 silver (formerly 4 steel and 4 plastic)
--Note: The silver change was expected, but the small plasteel edit was to bring it in line with the advanced non-laser scalper. Still viable to sell, mind, but not as silly good.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Inevitable Scalpel Fix

code/modules/goonchat/browserassets/css/browserOutput.css
Command radio is now this colour:
=> Makes radio command colour on darkmode less same as admin message

code/controllers/subsystems/trade.dm, code/datums/setup_option/backgrounds/origin_homeworld.dm, code/game/objects/items/weapons/tools/screwdrivers.dm, code/game/objects/items/weapons/tools/wrenches.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/reagents/reagents/food-Drinks.dm
-Fixed carnivores losing nutrition when eating nutriment due to a factoring error.
-Akulas are now carnivores and have the aforementioned perk. Akulas can no longer take the Neapolis homeworld.
-Added some currently commented out church code that I will likely expand on tomorrow once I finish todays upkeeping.
-Rebalanced combi drivers. Combi drives now have tool qualities 40 in screw driving and bolt turning. Electric screw drivers and big wrenches now have their qualities set to 50.
-The trade beacon now takes a 20% commission from any and all transaction using any account that is not the main lonestar account. This comes in response to a simple code solution to an otherwise annoying problem with crediting accounts and values for commissions.
<details>
<summary> …
=> Fixes and rebalances

code/modules/power/antimatter/control.dm
Prevent Antimatter Engines which can't announce their stability from announcing their startup and shutdown.
=> Prevent testing Engines from announcing their startup and shutdown.

code/datums/mind.dm, code/game/machinery/cryopod.dm
- Players that are inactive for more than an hour are now shown as 'SSD' on the manifest instead of a blank status.
- Players that cryo now get their records deleted when their character is, removing them from the manifest.
Some staff members didn't know why the crew manifest didn't remove people when they left for the lower colony, and would have liked that it did.
So I looked at the code and managed to make it remove people from the crew manifest when they cryo.
=> Make cryo'ing remove the crew record.

code/modules/mob/living/silicon/robot/gripper.dm, code/modules/power/antimatter/control.dm
Allow cyborgs to pick up and manipulate stuff related to the Antimatter Engine.
- Allow cyborgs to pick up antimatter fuel jars.
- Allow cyborgs to pick up antimatter shielding boxes.
- Allow cyborgs to remotely access the Antimatter Engine Console.
- Allow cyborgs to insert antimatter jars into the Antimatter Engine Console.
=> Allow borgs to interact with antimatter engine stuff

code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/_defines.dm, code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/build_a_drone.dm, code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/presets.dm
- Make the customizable drone have custom attacks based on its equipment.
This part of the Build-A-Drone PR focused on making the custom drones more than glorified walls.
- Drones with a flamethrower will fire a flame glob to set people on fire and drop a 'hellfire' flamethrower
- Drones with a gun will fire .35 bullets and drop a 'Spring'
- Drones with a laser weapon will fire lasers (duh) and drop a cog.
- Drones with a syringe will inject some toxin with every attack and drop a syringe
- Drones with a welder bonk people (Because superior mobs can't deal unarmed burn damage) and drop a regular welder.
- Added support for exploding drones.
Part 3, which will probably wait a few days, will focus on adding a vendor that people could spend credits at to create their own drone.
=> Build a drone part 2

code/game/objects/items/weapons/storage/hardcases.dm
Ammo hard cases can hold more basic gear, cells and grandes aka things you would reasonable want to store in a ammo hardcase
=> hardcase buff

code/modules/organs/internal/machine.dm
- Make the standard way of reviving artificial colonists less fucky.
A possible alternative to https://github.com/sojourn-13/sojourn-station/pull/2831, but in no way incompatible with it. This PR unfucks the Synth/FBP (Which are mechanically the same thing) standard revival method of removing and reinstalling the cell by stealing code from the rejuvenate() proc.
We can't call the revive() proc directly, because it heal all brute & burn damage, and we all know that people would abuse that to heal Synths faster.
=> Make the FBP revive less worse

code/modules/virus2/disease2.dm, code/modules/virus2/dishincubator.dm, code/modules/virus2/isolator.dm
Alters viro to be more usable on server! I will add more viruses and light changes over time while me and Ayshe figure out how we want to restructure it. But for now the following changes are:
People will no longer cure themselves randomly. They will require virology equipment or radium injections to produce antibodies. (Antibodies can be shared afterwards tho and are easy to produce in large quantities.)
Viro's Isolator machine will no longer lock up when a syringe is put in.
Virus food is no longer able to be bugged to be infinite in the incubator.
Incubator has been adjusted to get far more food for every unit of virus food in exchange.
Spaceacillin no longer cures stage 1 diseases. It instead stops diseases from moving to the next stage. (Consumes some of the spaceacillin each time it …
=> Viro no cure self fix

modular_sojourn/cardgame_2/cardgame_2.dm, modular_sojourn/cardgame_2/cardpacks_and_spawner.dm
Fixes spawners for card carp always spawning rare cards 1/10th the amount of cards their area
Adds in more rules and tweaks terrain cards heavily to be more viable
Adds in Thorns and Rivalry 
Nerfs rat deck
=> new cards and fixes - CCC

code/datums/craft/menu.dm, code/datums/craft/recipe.dm, code/datums/craft/recipes/guild.dm, code/datums/craft/recipes/lodge.dm, code/datums/craft/recipes/robot.dm
Different hand crafting categories that are specific only to certain jobs can only been seen and clicked on by those specific jobs.
=> Hides Crafting Menus of Unknown Categories

code/datums/contract.dm, code/game/objects/random/guns.dm, code/modules/projectiles/guns/mods/mods.dm
<details>
<summary>
Comments out the handholder rail from the modlist. 
This is for several reasons;
1. The rail breaks typical balance by allowing *more* exchanges of gunfire past viewing range, this alone is a massive issue as it removes the niche of proper 'sniper' type weapons and encourages an incredibly bland strategy where its use is never not beneficial
2.  The rail further breaks balance by allowing scope attachments to _all_ weapons, even if they already have a scope - this results in very silly things such as scout-rifles with several screens of view range
3. The rail is insanely easy to obtain - it has been included in the basic leveled list for weapon mods which means a handful of random weapon-mod-crates grants an extraordinarily powerful item.
</summary>
<hr>
<hr> …
=> Removes the hand-holder rail mod. 

code/game/objects/items/weapons/cards_ids.dm, code/modules/mob/living/carbon/human/human.dm
Adds ability to toggle the title on ID cards.
No longer are well known people stuck having their first names removed with a worthless snowflake title.
Marshals and Blackshield can now go on break! (Then get yelled at by commander and warrent officer!)
Right clicking the ID card allows you to alter if it shows the title or not. Or you can use the "Toggle-Title" command for those who like to type. Tested with proof picture in development-general.
=> ID cards get a title toggle verb.

code/game/objects/items/weapons/cards_ids.dm, code/modules/mob/living/carbon/human/human.dm
Reverts sojourn-13/sojourn-station#2840
This unfortunately caused 2 runtimes and has to be reverted until said runtimes are fixed.
=> Revert "ID cards get a title toggle verb."

code/game/machinery/vendor/weapon_kit_vendors.dm, code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/build_a_drone.dm, code/modules/nanogate/nanogate_items.dm, code/modules/power/antimatter/control.dm
Fix a runtime that happen when someone start the antimatter engine and doesn't bother to update the stability.
Fix the nanite rig initializing twice.
Make the Blackshield & Marshal's vouchers choices display correctly.
Allow build-a-drone drones to be pulled.
=> Misc Fixes

code/datums/perks/nanogate.dm, code/modules/nanogate/powers/rig.dm, code/modules/organs/internal/nanogate.dm
The Nanogate's rig powers now follow the same concept as the Nanobot Powers, so that the upgrades appear once the player get a nanobot instead of always clogging the power tab.
Also fix a nanogate runtime.
=> Make the Nanite rig give the verbs upon spawning the rig

code/modules/materials/materials.dm, code/modules/modular_computers/computers/subtypes/preset_tablet.dm
This adds a Tesla Link to all Soteria Tablets on round start akin to normal Tablets already in Soteria Medical
Fixes reinforced glass to give the proper 1 Steel 1 Glass rather than the bugged amounts
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Tesla_Links & Reinforced Glass Hotfix

code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/build_a_drone.dm
Boost the custom drone's health, 25 -> 100, and damage (5-10 -> 10-15) so that they survive a bit longer.
=> Boost the custom drone's health and damage

code/modules/modular_computers/computers/subtypes/preset_pda.dm, code/modules/modular_computers/file_system/programs/antagonist/uplink.dm, code/modules/modular_computers/file_system/programs/generic/taxes.dm
Remove the Antag Tax program and also fix the typos in the names of the tax programs.
We do not have any antags which (to my knowledge) use the antag uplink disguised as a tax program. And since we now have an actual, working tax program, it will probably just cause some confusion if someone doesn't know which one is which.
Also since all the antags we do get are powered by admins, they don't really need the uplink anyway. And if they do, I am sure that the admins will be able to give them a disk or something with the program for them to use.
=> Remove the Antag Tax program 

code/modules/mining/drilling/wurm_wave.dm
<details>
<summary>
Even small wurms are rather dangerous mobs, and the current spawn/burrow rates are overtuned, spawning 4 wurms every 12 seconds at the maximum. Rather than alter the stats of the wurms to make them less deadly, I have instead posed changes to make the wurm waves themselves more manageable. The only changes are to the duration between spawn intervals for the burrows themselves and the wurms that come out of them, in order to give miners enough time to potentially clear the wurms and burrows before they get overwhelmed.
</summary>
<hr>
<hr>
</details>
:cl:
balance: multiplied spawn rate from burrows by x5, with intervals shortening by 10 seconds for each level of wave severity, except for from dormant to negligible (20 seconds difference). Burrow interval is 2x spawn …
=> Using the mining drill is no longer suicide

code/modules/organs/internal/psionic.dm, code/modules/psionics/psionic_items/psi_catalysts.dm, code/modules/psionics/psionic_items/psi_misc.dm, code/modules/psionics/psionic_items/psi_temp_items.dm, code/modules/psionics/psionic_items/psi_weptools.dm, code/modules/psionics/researched_powers.dm, code/modules/psionics/standard_powers.dm
This PR add multiple powers that @Kazkin asked me to code, with only one currently available to the public.
The rest will be added in a future update by Possum.
**Kinetic blast**: Standard power (all psions get it)
Creates a psi based item in your hand that fires a kinetic blast. The blast costs 1 psi point per shot. The item disappears if dropped. The damage scales off of cognition, dealing max damage if you have the psionic psychosis perk.
**Researched variants**
- **Cryo-Kinetic Blast**: 4 points per shot, deals no damage but stuns for 1 second per 10 points of cog, capping at 4.
- **Pyro-Kinetic Blast**: 2 points per shot, impacts like an explosive grenade, damaging objects, knocking people down, and setting flammable objects on fire.
- **Electro-Kinetic Blast**: Hit scan, costs 3 …
=> Psionic Powers : Heck Around And Find Out Edition.

code/modules/mob/living/carbon/superior_animal/lodge/types/clucker.dm
<details>
<summary>
Fixes a bug with clucker eggs in which having their own Process() proc stacked with the existing one they get from being a subtype of eggs laid by chickens. The duplicate proc has been removed, preventing further double-processing that may have an impact on performance.
</summary>
<hr>
<hr>
</details>
:cl:
fix: clucker eggs no longer double-process
/:cl:
=> Bugfix for clucker eggs

code/game/machinery/kitchen/smartfridge.dm, code/game/objects/items/weapons/storage/bags.dm
<details>
<summary>
Because poultry is not a meat subtype, produce bags and smartfridges couldn't hold it. This PR adds the chicken meat type to the list of things the smartfridge and produce bag can hold.
</summary>
<hr>
<hr>
</details>
:cl:
fix: Produce bags and Smartfridges can now hold raw chicken breast
/:cl:
=> produce bag/smartfridge can hold raw poultry

code/datums/craft/recipes/lodge.dm
<details>
<summary>
The lodge doesn't currently have a source of polytrinic acid to make plastic from plastellium, so now their soap, tape, and flex tape recipes use wood instead. Fluff-wise, you can explain this as plant fibers being a viable alternative for plastic for those recipes. I also reduced the leather sheets needed to make powder pouches from 2 to 1, so that you don't have to be wasteful and slaughter extra animals to use all four horns from each tatonka.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Tatonka powder now costs 1 leather instead of 2.
tweak: Lodge Soap, Tape, and Flex Tape recipes now use wood instead of plastic.
/:cl:
=> Lodge recipe tweaks

code/modules/projectiles/guns/plasma/hydrogen.dm
Turn the explosion that happen when an Hydrogen-Plasma gun overheat into an actual heatwave.
=> Turn the overheat explosion into an overheat heatwave

code/controllers/communications.dm, code/game/objects/items/devices/radio/radio.dm
SHOULD Prevent radios from getting runaway situations where multiple of the same device are added to a listening list.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
SHOULD Prevent radios from getting runaway situations where multiple of the same device are added to a listening list.
Improves debugging for situation where frequency is dropped for whatever reason.
Improved logging for core error in case we see it again.
/:cl:
=> Small Radio tweak

code/modules/core_implant/cruciform/rituals/path.dm
Make the Divisor's threat detection litany work when there's carbon people around.
=> Fix the Threat Detection Litany

code/game/objects/effects/chem/chemsmoke.dm, code/game/objects/items/oddities.dm, code/game/objects/random/oddities.dm, code/modules/mob/living/carbon/breathe.dm, code/modules/sanity/inspiration_component.dm
By Alliostra 
add: The descriptions of oddity stats are now randomly generated.
fix: chemical reagent smoke should be much more reliable now.
By Trilby
Fixes propis oddity boxes not spawning correct amout of items
=> Alliostra is a coder byond my understanding

code/modules/virus2/dishincubator.dm
Virology gets faster the more radiation you have in the dish, but as a balancing point, you can no longer receive minor mutations above 50 rads, this means that you have to play a balancing PR between quick major mutations, or slightly slower minor mutations
=> Viro rebalance

code/modules/virus2/effect.dm
what
Essentially; the way they were healing with this was never tested, I believe, and the proc it was using was deprecated. Just old code that needed a fix-up.
=> Runtime fix?

code/controllers/subsystems/jobs.dm, code/modules/client/preference_setup/general/07_stats.dm, sojourn-station.dme
By Jamini
add: Players can now dynamically set their stat bonuses from education. Up to +15 or -10 in any one stat. COG counts for half.
admin: consolidated our oddity override files.
=> Ports stats trainning

code/game/objects/items/oddities.dm, code/game/objects/items/oddities_faction.dm, code/game/objects/items/weapons/secdocs.dm, code/modules/reagents/reagent_containers/food/snacks/donut.dm
Massively rebalances oddites levels and stats
Many oddites have more odds to gain a perk
Adds in a "minium" stat system so good oddites like the crafted cube will no longer be able to role nat 1s cuz rng hates you
Some oddies like sec docs and brick no longer are able to gain a perk
Buffs faction oddies like the masterwork donuts and von to be actually viable in round play
=> The rebalance

code/modules/reagents/reagent_containers/glass/bottle.dm, code/modules/reagents/reagents/drugs.dm, code/modules/reagents/reagents/other.dm, code/modules/reagents/recipes/recipes.dm
Fixes sanguinum overdose. Its now the same as any other overdose. No more putting hundreds of units into you without consiquence.
Adds two chems, nosfernium and viroputine. I have more plans for viroputine down the road.
Nosfernium is a much stronger blood restore with toxin damage and bad withdrawels.
Viroputine is a unique chem in that you feed it blood and chems with nosfernium to make more. (This is why the innitial making of nosfernium is so low)
=> Adds New blood chems, Fixes Sanguinum OD

code/datums/perks/nanogate.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/projectiles/guns/matter/launcher/books.dm, code/modules/projectiles/projectile/beams.dm, code/modules/virus2/effect.dm
yikes
Nanogate regen healing has been halfed
young Folken now heal 33% less, this is still more then normal folken
mycus healing also halfed
heavilly reduces harmoney staffs healing and greatly increases fire delay, this was not meant to out heal mid-combat
Longevity Syndrome no longer ages you up rapidly
Longevity Syndrome now is much weaker at healing
=> nerfs some op healing

code/modules/mob/say.dm
For clarity, this does not enable gaps in your emotes, those will still be hashtags.
This just lets people see what they're writing
=> [TESTED] Buffs ERP

code/modules/clothing/clothing.dm, code/modules/clothing/masks/gasmask.dm, code/modules/clothing/masks/miscellaneous.dm, code/modules/mob/hear_say.dm, code/modules/mob/living/carbon/human/say.dm
<details>
<summary>
Ports over Eris' PR ( https://github.com/discordia-space/CEV-Eris/pull/6960 ) which makes voices muffled behind gas masks or other specific face coverings show as an unknown voice. Basically a one-to-one port.
</summary>
<hr>
<hr>
</details>
:cl:
add: Adds in muffled voices to mask identity of the wearer.
/:cl:
=> Port - Unrecognizable voice when wearing Gas Masks

code/modules/projectiles/ammunition/boxes.dm
Replaces the Buckshot inside Old Ammunition Box 20mm Slug with the correct ammo type, Old Slug Ammo  Bug reported by DukeOfSpades
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Old Ammunition Box Slug Fix

code/game/objects/items/oddities.dm, code/modules/core_implant/cruciform/machinery/eotp.dm
Church relic and materal spawns have been fixed to not give puzzel boxes and full stacks of materals now using a wighted system to be 10-15-20
=> wait this is a church nerf?

code/modules/mob/living/carbon/human/life.dm
Shock shouldn't stack infinitely and is why being set on fire was made such a death sentence, you can easily accrue 2000+ shock which makes anything other than oxycodone completely worthless.
=> Makes shock stage not stack infinitely

code/game/machinery/computer/supply.dm
<details>
<summary>
Simply allows Supply consoles to buy contraband, but more importantly sell contraband without the need of a EMAG. In this case, allowing the exporting of organs and other questionable items.
Considering we don't have any contraband that we can buy, and getting hold of a EMAG is near impossible. I believe this PR simply allows Lonestar to export more...questionable things. 
</summary>
<hr>	
<hr>
</details>
:cl:
Edit Supply console.
/:cl:
=> Lonestar Organ Market

code/modules/virus2/effect.dm
This made longevity so trash it wasn't even worth using. No.
To explain why, viro symptoms DO NOT HAVE A 100% chance to proc.
This was not tested in its pre-nerf state, this was not tested in its after-nerf state. As the only individual who has tested this, it was fine. It healed ~30 damage of brute in 5 minutes.
=> [REVERT] Reverts trilby's nerf to funny man viro

code/modules/mob/living/simple_animal/hostile/carp.dm
Shark carps are insanely stupid right now. They have instant movement and can hit harder than some boss-level monsters. 
And this is all while they are in space where you are usually drifting around, where you have left your good armor behind for the one they give in the trash beacon. With all this considered, I made these changes after talking with a few people about it. 
Sure, I do not know if it's balanced, but I shot for the stars hoping that it's going to fix the problem of people never going into the trash beacon place.
https://youtu.be/T8r6eXTa8o4 Without changes.
https://youtu.be/jOSz7Eket-8 With changes.
Also, FIRST PR here. Woah.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Carp changes

code/modules/clothing/spacesuits/rig/suits/hydrogen_knight.dm
Apparently the rig *completely* overwrite any armor values that the armor would otherwise have.
- Make the Hydrogen Knight Rig's armor values actually work.
- Also give the suit a bit more starting stuff since it is admin-only.
=> Fix the suit's armor value

code/modules/clothing/spacesuits/spacesuits.dm, code/modules/clothing/spacesuits/void/station.dm, code/modules/clothing/suits/armor.dm, code/modules/clothing/suits/miscellaneous.dm, code/modules/clothing/suits/storage.dm
Wait they are a direct upgrade form even full plate armor?
Scavenger armor now has less stats and more downsides form longer time to take off and on to a small amount of slowdown
Scavenger welding helmet now observs vision along with all space helmets
Lowers melee armor on scavenger gear to not be better then plate armor
Fixes scavenger armor not getting its upgrades
Fixes pocketed suits storing upgrades inside the pockets and wasting slots
=> Gives scavenger armor and hand made gear more downsides

code/game/objects/items/weapons/melee/energy.dm
This will hopefully fix some of the problems.
The subtype does not seem to have a use, so it would be fine to keep the damage to it.
It tested and worked for the Soteria Prosthetic combat background.
It's just force damage to the sword, that's it.
_It does not do any damage currently in game_
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Prosthetic energy sword fix

code/modules/clothing/masks/gasmask.dm
The alt opifex gas mask that legit states you can eat with it on, now allows you to eat with it on.
=> Opifex gas mask fix

code/modules/surgery/internal.dm
<details>
<summary>
This bug was caused by if(!(organ_tag in implant.allowed_organs)) in the check for implants in the insert step. The way this computed made it so that implants with an empty allowed_organs list would not be installable via Insertion surgery, despite being installable in every limb with an Implanter. This check has been replaced with conditions that check if this var exists in the first place, if it actually has anything in it, and if the other two conditions are met, if the organ to be installed into has its tag in the allowed_organs list.
</summary>
<hr>
<hr>
</details>
:cl:
fix: Implants can now be implanted via item insertion surgeries. Most useful for people with robotic limbs, who don't feel like stripping naked in public just to put a death alarm or circuit …
=> Fixes a bug where implants could not be installed via surgery

code/modules/clothing/spacesuits/void/station.dm
I was too mean to the goldilocks. It's now similar in power to a regular mining voidsuit. Still not top tier, since it is a joke item, but on par with the basics available in Lonestar's department.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
- Buffed the goldilocks voidsuit to be similar in power to a regular mining voidsuit. Still not top tier, since it is a joke item, but now on par with the basics available in Lonestar.
/:cl:
=> Buffs Goldilocks

code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Raise the universal maximum chicken limit by 10, to a limit 20
5 chicken, or half the current limit, were in the Admin Genetic Testing area, thus just about blocking more chicken from spawning from the eggs.
It was either raising the limit, or doing map work to remove the chicken crate.
=> Raise the maximum chicken limit by 10, to 20

code/game/jobs/job/civilian.dm
Allows the artest to be able to see perks on oddites, given that they work with them so often and barely can even use them for personal gain
=> Buffs artest

code/__DEFINES/qdel.dm
In theory this will make the GC go much faster to keep up with how much we demand on it compared to places like on tg or eris.
This in theory should make more memory be able and help reduce lag
This is a non-fix to underlieing issues but should help none the less what we cant fix
=> Exsperimental GC changes

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Sick and tired of needing to be at the desk 24/7 to sell your products?
Sick and tired of going around getting the parts needed to get yourself a custom vender to pay off the considerable debt that your father had accumulated before his mysterious disappearance?
Well no longer will you have to suffer as much!
Like cargo has 3 custom vendors every department (Other then blackshield) has a easy to set up vendor with metal, wire and parts to go with the board! Everything you need to set up so you can accully do your job for 4 seconds before needing to refill the darn thing...
=> Recettear: An Item Shop's Tale

code/datums/contract.dm, code/game/machinery/excelsior/blackshield_teleporter.dm, code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm, code/modules/clothing/head/helmet.dm, code/modules/clothing/suits/armor.dm, code/modules/psionics/conquest_powers.dm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Adjusts the Shield teleporter's energy gain slightly and its rewards for doing the acquirement quests, incentives shields to actually get said items. 
Adds in several new items that can be acquired from the teleporter, ranging from armor, ammo, to shield gun disk. Reduced point cost for plasteel, bringing it down from 250 to 150. 
Reduces license point cost of the Duty on the Blackshield disk. It was too much for it to be 6 license points for what it was worth.
Moved the ammo disk back into the secure armory. Was a mistake to have it outside.
Readjusts Blackshield ablative armor, giving it slowdown and raises some more general protections against other types, but better to wear other armor for said stuff.
Adds in more traps for those who tunnel in farther into the colony.
=> Blackshield Adjustments

code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_runner.dm
Rename the Ameridian Runner to Ameridian Runtling, as it is a far better name.
=> Rename the runner

code/modules/modular_computers/file_system/programs/generic/trade.dm
The basic trade beacon found in consoles can no longer be stolen, only used
An alt version is now only aviable on the NT.net access to cargo to download it and transfer the data to others.
This is both a fix for a rather gamey and jerk move form people to steal the program and allow cargo techs to freely hand out said program to whom they deal with or keep on their own to watch/do bounties remotely
=> Makes the trade beacon a lot more balanced

code/datums/autolathe/tools.dm, code/game/objects/items/weapons/autolathe_disk/lonestar_disks.dm, code/game/objects/items/weapons/power_cells.dm, code/modules/research/designs/cell.dm, code/modules/research/nodes/power.dm
buffs crank charger so it no longer takes an entire minute to charge S cells- it now takes 16 seconds to charge a 800M cell at 25 toughness, and 80 seconds to charge it at 0 toughness and below. large cells still need an obscene amount of time (2 minutes at max TGH), to stop handcrank charger from being the be-all end-all cell charger
it's been moved from soteria to prospectors' disk,  since they're concievably the ones who need it the most (being away from chargers and all)
:cl:
balance: crank charger no longer sucks
fix: crank charger
/:cl:
=> crank charger buffs + fixes crank charger

code/modules/cargo/packs_security.dm
This change adds new 7.5 and 257 ammo packs, aswell as orders for ammo disks and a last void wolf "Marksman" kit with a single bolt gun, a few rounds, and a mod. All of these were designed to be accurately priced so they're not overpowered, but to also make them relatively accessible for departments when cargo is /actually/ there.
I was tired that there was only handgun ammunition in the cargo console so I added more options.
=> Minor addition to cargo packs

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Does what it says on the tin. The service lounge now takes access from: 22,28,26,25,35,43
bar, hydro, chaplain, the cook, the janitor, and theater enjoyers fall under this.
This PR also 'fixes' the access on the cook's downstairs room, which required bar access- not kitchen access.
🆑 
tweak: Airlock restrictions in service
/:cl:
=> The service lounge is now service only 

maps/_DeepForest/map/_River_Forest.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Rims Fixes pr!
🆑
add: Cave overgrowth (Gardener's Bedroom)
add: Additional Fridge for easier access to ingredients
add: Low chance oddity spawn in employee lounge hallway
add: DIRT! WHOO!
del: Removed disposal chutes in lounge temporarily to prevent disposal issues. (They will return)
del: Random ugly tile next to the diner pillar.
del Random fire alarm inside of hydroponics tray in botany.
tweak: Kitchen layout for easier access to ingredients
tweak VIP areas are no longer free and public (sorry), Chef/Bartender guest passes required to enter. (Though charging isn't necessary, standalone rates will be 150 per intended body for the sake of economy)
tweak: Replaces booze dispenser in Rustic VIP lounge with a soda machine. Incentivizes bar refills, and room service.
fix: Employee lounge …
=> Elf mapping gone wrong

code/modules/ameridian/_defines.dm, code/modules/ameridian/ameridian_crystal.dm, code/modules/ameridian/ameridian_crystal_blue.dm, code/modules/ameridian/ameridian_spire.dm, sojourn-station.dme
Rework the blue ameridian crystals : 
\- Spire has a 10% chance of spawning a blue crystal instead of a green crystal
\- Blue crystals now boost the growth & spread of every green crystals in a 2 tile range and spread normally instead of spreading 1 tile further and slightly faster.
\- Blue crystals now regularly spawn runtlings, albeit with 50% more time between spawns. Those runtlings spawn in packs of 5. The crystal will still spawn 3 runtlings upon being excavated.
=> Rework blue crystals

code/modules/mob/mob.dm
A while ago, eris updated their mob file to force harddels on everything. THis was due to a very old TG PR. TG has moved on from that as it was a temporary, awful measure. See https://github.com/tgstation/tgstation/pull/51887.
WARNING. I just found out this causes most mobs to fail GC on deletion. This means they are stuck in the memory and can cause a memory leak. This isnt to say its our only memory leak, we have a fuckton of GC failures, this'll jsut make it worse.
:cl:
code: Updated mob destroy() to not force harddels.
/:cl:
=> Removes the forced harddel on mobs

code/modules/projectiles/guns/projectile/revolver/lemant.dm
Make it so that when hitting a Pilgrim with an ammo box, after a small delay, to start individually loading the ammo into the gun.
This way players don't have to take the ammo out of the box, then load the Pilgrim manually using those bullets.
It apply to all type of pilgrims, however, it doesn't automatically remove the old ammo for you.
=> Allow the Pilgrim to directly reload from boxes

code/modules/projectiles/guns/energy/railgun.dm, code/modules/projectiles/projectile/bullettypes.dm
<details>
<summary>
Some changes to the Bat'ko. Removed it as a plasma projectile, preventing limb-gibbing as easily, and instead made it akin to the rail rifle as a ballistic projectile. Reduced its AP from 100 to 60. This should limit making the gun too powerful. As a note: Previous PR fixed the heat-gain issue, and I've also added text when examining it to remind you to vent it. (Or else you take 50 burn.) Similarly Trilby's previous PR made the gun only able to take two attachments, limiting one's ability to mod it to high-shit. **I may need to re-buff this in some way in the future**, such as increased ammo capacity or less cell-cost usage, but this should service for now. I'll keep watch of the rifle in game and adjust it accordingly.
</summary>
<hr>
<hr>
</details>
:cl:
balance: …
=> Bat'ko Balance & Hotfix

code/modules/mob/living/silicon/robot/robot.dm
Research borgs were unable to lock/unlock other borgs because their card/robot module was never being used.
This PR adds a simple additional check if said card was used on a borg. 
:cl:
fix: Research borgs can lock/unlock borgs again
/:cl:
=> Allows research borgs to unlock other borgs again

code/__DEFINES/weapons.dm, code/modules/projectiles/guns/projectile/automatic/c20r.dm, code/modules/projectiles/guns/projectile/automatic/drozd.dm, code/modules/projectiles/guns/projectile/automatic/greasegun.dm, code/modules/projectiles/guns/projectile/automatic/luger.dm, code/modules/projectiles/guns/projectile/automatic/mac.dm, code/modules/projectiles/guns/projectile/automatic/ppsh.dm, code/modules/projectiles/guns/projectile/automatic/texan.dm, code/modules/projectiles/guns/projectile/automatic/tommygun.dm, code/modules/projectiles/guns/projectile/automatic/triage.dm, code/modules/projectiles/guns/projectile/automatic/vector.dm, code/modules/projectiles/guns/projectile/automatic/wirbelwind.dm
An simple change to SMG weapons(and only SMG weapons). Currently, they're in a very weird place where a generally low damage mod, plus pistol caliber(.35 almost exclusively) and further penalties for using full auto meant that they were highly unfavorable to use in almost all scenarios. Consequently, adds new fire modes without the -.2 damage mod ONLY for SMGs. This will hopefully help their lackluster performance in almost all fields when not being used essentially as large pistols, which you'll note retain their damage penalty for full auto.  
This change affects the c20r, Drozd, Greasegun, Vintovka Lyugera, Mac10, PPSH, Texan, Ekaterina, Semyonovich, Thompson
Looking at .35 and .40 in a vacuum, this will amount to a total damage bonus of 4.8 per shot on .40 SMGs(24->28.8) and a total …
=> SMG balance stuff

code/modules/projectiles/projectile/bullettypes.dm
<details>
<summary>
Adjusts Bat'ko to no longer be a sharp projectile. Because now, unlike before, it can one shot gib limbs with the change being ballistic.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Unintended side effect to remove the mythical 'one hit gib' Bat'ko - turning it into the real one-hit delimb bat'ko. Fixed.
/:cl:
=> Bat'ko Projectile

code/game/machinery/xenobio.dm
Base functionality added to the slime_dye_vat (Has to be spawned in)
Uses crayons to set color, Slime jars to get uses for dying things. And of course.... Comes with its own special creation!
Currently the base model is uncolored. And there is two known colors that don't appear right. Orange and Rainbow.
=> Xenobio Dye Vat -Admin Testing Only For Now-

code/modules/scrap/scrap_pileripper.dm
pile ripper can now dig out loot from trash piles. Hooray, it's now no longer just a murder machine. Pile ripper also now only deletes items when emagged (use the recycler or smelter instead). 
i sincerely doubt this will severely impact the trashpile economy, since you either 1. drag it around in maint after powering the area apc, wrench it down for every trashpile and unwrech it to move it, potentially gibbing yourself if you're not careful or
2. you get a ripley and start walking around compressing cubes into scrap, loading up the scrap cubes and moving it to a fixed pileripper, which is about as fast as manually going through the piles with a good shovel
3. it's more excuse for it to be used = more likely people will fall in = funny
:cl:
balance: pile ripper can now loot trashpiles, …
=> pile ripper fix(?)/rework

code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
Removed role restriction for Absolutist path-based clothing, because they're simply the clothing for the path- not a uniform for being on-duty as church, but day-to-day clothes (to my knowledge).
:cl:
Removed role restriction for Absolutist path-based clothing.
/:cl:
=> Make absolutist garments unrestricted by role again :)

code/game/machinery/autolathe/autolathe.dm, code/modules/projectiles/guns/breacher.dm
Tin. I-Autolathes, and all autolathes with recycling, can be Control-Clicked to toggle automatic feeding. This takes all sheets on the tile in the direction it's facing, and attempts to load them. Unsupported materials don't get loaded- you can't put biomatter in regular lathes this way. Performance implications are similar to smelters and recyclers, and the feature starts off, so it's likely a nonissue.
Additionally, all autolathes can now be ControlShift clicked to be rotated. 
:cl:
add: autolathe autoinput (as long as it's capable of recycling)
/:cl:
=> Factorio: Industrial Autolathes can now automatically load sheets

code/modules/projectiles/projectile/energy.dm
<details>
<summary>
Stunslugs do 80 agony damage, equivalency of a 40mm baton round - yet have an infinite affective range. This will make it slowly drop agony damage for each tile traveled. Akin to how the beanbag loses effectiveness after a few tiles traveled.
</summary>
<hr>
<hr>
</details>
:cl:
balance: Stunslugs now have an affective range.
/:cl:
=> Stunslug Affective Range

code/datums/craft/recipes/guns.dm, code/datums/craft/recipes/weapon.dm, code/modules/projectiles/ammunition/bullets.dm, code/modules/projectiles/guns/energy/charge.dm, code/modules/projectiles/guns/launcher/crossbow.dm, code/modules/projectiles/projectile/bullettypes.dm, maps/Centcom/map/centcom.dmm, maps/_DeepForest/map/_River_Forest.dmm, maps/__Nadezhda/map/Surface_Old.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_Surface.dmm
powered crossbows are no longer only useful for pvp in closed areas (with pinning)
Crossbow projectile damage now scales with tension. Every second of charging gets you 100% more damage, with 10 damage base for metal rods.
crossbows now do 50 damage at full charge (achieved after 5 seconds of charging). Rods are still reusable as ammo. Basic rods can't embed.
RXDs have been nerfed slightly- now they have less damage, but higher AP. This is due to their ease of ammo handling compared to regular crossbows- you don't have to unwield to shoot, and to set them apart somewhat due to their significantly higher material cost.
Heated crossbow bolts do a mix of brute and burn: 12.5 extra burn on both regular bolts and RXD bolts, embedding, but at the cost of not being able to recover your …
=> powered crossbow/rxd rework

code/modules/reagents/machinery/grinder.dm
<details>
<summary>
Makeshift grinder insertion code was using a lazylen on something that wasn't a list and so everything that wasn't a reagent_container wasn't grindable. I just took the check from the regular grinder instead.
</summary>
<hr>
<hr>
</details>
:cl:
fix: makeshift grinders can properly grind non-food items now
/:cl:
=> Fixes makeshift grinders

code/modules/mob/living/living_defines.dm
Hopefully reduce some lag by changing a single variable. Might break slimes trying to eat you, but who do slimes anyway?
-- Trilby don't include the part below --
The variable 'update_slimes' is used in one place, here : https://github.com/sojourn-13/sojourn-station/blob/master/code/modules/mob/living/living.dm#L582
So every time any mob moved, it would check for nearby slimes.
So with this change, we reduce the number of checks from however shit the mob had near it to just 1, which, considering the minimum is at least 10 (9 turf + src mob), should reduce some lag.
=> Hopefully reduce some lag

code/game/objects/items/stacks/stack.dm, code/game/turfs/turf.dm, code/modules/mob/mob.dm
Tin. Stacks autostack when crossing a stack that they can stack with.
Controlclicking a tile calls Haul on that tile.
:cl:
add: Stacks autostack when crossing a stack that they can stack with. Controlclicking a tile calls Haul on that tile.
/:cl:
=> stack autostacking, haul on controlclicking tiles

code/modules/cargo/packs_engineering.dm
<details>
<summary>
Adds Bulk Glass Crate to Lonestar cargo. Priced proportionally as the rest of the bulk crates vs their single stack variants. We have this for plastic and steel so why not glass? Also QOL so I don't have to keep clicking around in our awful cargo UI if I'm trying to order the same amount of sheets
</summary>
<hr>
<hr>
</details>
:cl:
Adds Bulk Glass Sheets Crate
/:cl:
=> Adds "Bulk Glass Crate"

code/game/objects/items/weapons/tools/pickaxe.dm
<details>
<summary>
This just fixes the RIG suit drill so it actually functions as a digging tool now instead of an excavation tool.
The reason the previous fix didn't work was the toggle function is never called so it never updates the starting tool qualities that are inherited from the diamond drill it's parented off from. 
</summary>
<hr>
<hr>
</details>
:cl:
fix: RIG drill module digs instead of excavates.
/:cl:
=> Fixes RIG suit drill

code/datums/autolathe/biomatter.dm
Material costs of the knight rigsuit doubled for biomatter, gold, silver. Material cost of plasteel raised to 100. While these numbers may seem high it's worth noting that printed from a bioprinter the final value will only be 60% of these numbers. This means that the new, total cost for the suit is lower than initially seems.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Church Knight rigsuit cost nerf

code/modules/projectiles/guns/energy/sst.dm, code/modules/projectiles/projectile/bullettypes.dm, code/modules/trade/machinery/trade_beacon.dm
SST guns nerfed, but also not that badly.
SST weapon no longer work through all armor, they now instead work much akin to pepperball ammo(checks face covering, essentially. Must be something akin to a gas mask to be defended against). They retain their rubber rounds and still punch high above their weight.
Additionally they were given some slightly adjusted 'effective range', to give a distinct advantage over just using a /real/ gun using similar rubber ammo.
Abnegate : affective_damage_range = 2->5
Formatbound : affective_damage_range = 4->6
Humility: affective_damage_range = 1->5
Systemcost : unchanged.
Their price in the protolathe however has been reduced. They no longer require uranium, and at request instead of fully removing their platinum it has been SIGNIFICANTLY reduced(.1, .2, …
=> SST balancing

code/game/objects/items/weapons/storage/deferred.dm, code/modules/trade/datums/_trade_station.dm, code/modules/trade/datums/trade_stations_presets/1-common/factio.dm, code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm, code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm, code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
:cl:
balance: purchasing now gives 25% of the money as favour, up from 12.5%
balance: recoll prices back to material sheet price * 3 (generally)
balance: casino sells more random things now, and has a lower secret inv threshold
balance: it's now cheaper to get disks from Factor instead of disk vendor
balance: C4 price is now 1500 again from Kaida
balance: suitup's secret inv threshold is now 6000, down from 24,000
balance: Greyson Printer station no longer sells greyson significantly cheaper
/:cl:
=> beacon balance pass part 1

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Slight map adjustment! Evidence storage has been moved to the top right corner of the 'investigation block' in the central Marshals, in its place is the E.Y.E Pods storage room, locked to Ranger access(All Marshals will have access thusly.)
To use it, simply put on the provided equipment in the room, turn on the provided internals and climb in before clicking the pod.
It functions similarly to the AIs eye, allowing you to pan through the camera network in a highly efficient fashion. Credit goes to @Kirov#6255 for the actual code of the thing!
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> LITERALLY 1984: 2, cyberpunk boogaloo

code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/automatic/dp.dm, code/modules/projectiles/guns/projectile/automatic/lmg.dm, code/modules/projectiles/guns/projectile/automatic/nordwind.dm, code/modules/projectiles/guns/projectile/automatic/sts.dm, code/modules/projectiles/guns/projectile/boltgun/zatvor_ak.dm
<details>
<summary>
Mostly small changes to 7.5 guns across the board and various LMGs. The Takeshi, for example, was called 'so good' as well as the DP-27 - which was a clear indication of their time not being upkept. These guns had worse stats than even their counterparts. Now all **should** have some resemblance of a usable, balanced gun. And an incentive to actually use various rifles instead of sawn off AKs being worse than .35 pistols or LMGs being objectively worse than all rifles. Minor changes to STS guns, mostly prices and recoil changes. This is intended to go hand-in-hand with the 7.5 rebalance, they are kept separate for input purposes. With the changes this should make 7.5s balanced akin to the .257 platform, some having bonus pen, others bonus damage. Giving trade-offs …
=> 7.5 & LMG Rebalance

code/modules/projectiles/projectile/bullettypes.dm
<details>
<summary>
So - basically, it feels as if 7.5 ammo was never balanced with the other calibers. 7.5 HV rounds were objectively weaker than their counter parts due to low pen-to-damage ratio (effectively doing less damage even if it pens) and not being hitscan. Also the step delay on the 7.5 bullets were 0.2 higher than .408 and .257. Why? No clue. Also - increased the affective range to 7, still lower than .408 but actually can be used as DMR caliber now instead of only 'best' at close range.
</summary>
<hr>
<hr>
</details>
:cl:
balance: Balances 7.5 affective range, HV fixes (hitscan, AP, etc) and bullet-speed changes.
/:cl:
=> Mild Buffs to 7.5 (Oversights??)

code/game/objects/items/weapons/circuitboards/machinery/ameridian.dm, code/game/objects/structures/flora/flora_potted.dm
Rename the 'contained ameridian shard' to 'potted ameridian shard'
Change the description to hint at the ability to change the field's opacity.
Make the opacity change not bugged.
=> Fix the ameridian plant pot

code/game/objects/structures/crates_lockers/closets/job_closets.dm, code/modules/client/preference_setup/loadout/lists/suits.dm
Adds the Charming Waistcoat to Loadout and the Chef's locker, as the waistcoat refactor of my earlier PR made them unobtainable in-game.
<hr>
:cl:
add: Added charming waistcoat to the chef's locker.
fix: Due to an oversight from waistcoat refactor, adds the Charming Waistcoat to loadout options (under suits) again.
/:cl:
=> [Quickfix] Makes Helltaker waistcoat obtainable again

code/game/objects/structures/flora/flora_potted.dm, code/game/objects/structures/noticeboard.dm, maps/__Nadezhda/area/_Nadezhda_areas.dm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
\- Replace the Teleportation Lab that was in construction for 6 months with an Ameridian Lab instead!
However, as Soteria outsourced the lab's construction to Space-IKEA, the colony's scientists will have some assembling to do before the lab is actually in working order.
\- Fix a typo with RnD's Notice Boards
\- Allow Potted Ameridian Plants to be EMP'ed.
=> Add an Ameridian lab to Soteria

code/modules/mob/living/simple_animal/friendly/ameridian_tender.dm
Prevent player-controlled ameridian tenders from harvesting an ameridian spire.
=> Tender Hotfix

code/__HELPERS/time.dm, code/controllers/subsystems/ticker.dm
SHOULD theoretically fix the timer for round restart to go off real world time rather than tickrate time.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Real time O:

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
<details>
<summary>
I did a fucky-wucky in a PR last minute and forgot to merge a commit that fixed the PPV on the Marshal negotiator disk. This should fix the issue completely.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Marshal negotiator disk loading an improper icon due to bad pathing.
/:cl:
=> Fixes Marshal Negotiator Disk

code/modules/modular_computers/file_system/data.dm
<details>
<summary>
Over doubles the data on the audio recording disk. Why? Because otherwise the software breaks if you use it to its limit, for some reason. (This is clearly a Marshal uber-buff...................)
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Over doubles the size of the audio-recording disk.
/:cl:
=> Buffs Tape Recorder!!!!!

code/modules/paperwork/faxmachine.dm, maps/Centcom/map/centcom.dmm
Make all of the faxes sent to admins end up in Central Command instead of nullspace, so that admins can see the faxes that were sent in the rounds without needing to be online when the fax was sent.
=> Give a place for admin faxes to end up

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Due to an oversight, I added the autolathe datum, but never assigned it to the Security disk as originally intended. This PR fixes that.
:cl:
fix: ACOG design now properly added to security disk
/:cl:
=> Adds the ACOG to the sec disk

code/modules/reagents/machinery/chem_dispenser.dm, nano/templates/chem_dispenser.tmpl
Moved milk , grape soda, watermelon juice and berry juice to there respective dispensers round start instead of behind upgraded parts. Milk to the coffee dispenser and the rest to the soda dispenser.
=> Bar drink dispenser changes 

code/game/objects/items.dm, code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/projectiles/projectile/bullettypes.dm, code/modules/projectiles/projectile/special.dm
adds post-pen damage to hollowpoints. nerfs hollowpoint agony by ~66% across the board.
:cl:
balance: hollowpoints deal greater post-penetration damage
/:cl:
=> hollowpoint rework, post-penetration damage

code/modules/trade/machinery/trade_beacon.dm
<hr>
Sets the trade beacon bluespace entropy to ZERO. If the intention is for Lonestar to switch over to the trade beacons, and fading out the shuttle...then why are we being punished for using the trade beacons with bluespace entropy? I had spoken with Moon regarding this matter, and with their approval I made this PR.
<hr>
</details>
=> Removal of Trade Beacon bluespace entropy

code/modules/projectiles/guns/energy/tetra.dm
<details>
<summary>
Tetra was a bit unbalanced before due to it effectively having no downside to using its IR setting over a default setting, its fire delays not appearing to work properly(?) and its ability to be a duel wieldable Cog with better damage and cell-usage cost. Now its more of a proper SMG with a similar niche-usage, but no major 'buff' in damage to its firemode. Should still function as an objectively better version of a Firestorm and likely /be/ better than a Cog - but as an SMG putting rounds down range rather than a rifle-SMG hybrid.
</summary>
<hr>
<hr>
</details>
:cl:
balance: Rebalances Tetra's damages and firemodes.
/:cl:
=> Tetra Rebalance

code/modules/goonchat/browserassets/css/browserOutput_override.css, code/modules/mob/living/silicon/robot/robot.dm, code/stylesheet.dm
<details>
<summary>
Yassari should have the proper color now when spoken. Robots should also now be able to learn Esperanto and Yassari now instead of being unable to learn it.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Missing interface color for Yassari.
/:cl:
=> Finally Fixes Yassari Colors

code/modules/recycling/disposal.dm
No more resistance against disposals, damage remains unchanged exactly. But there is no longer a way to resist or nullify the damage.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Makes disposals deadly again.

code/game/objects/structures/crates_lockers/closets/wardrobe.dm
Does what the title says. These lockers contain every other Marshal loadout outfit besides the Marshal BDU, so I decided to add it.
Playtested, functional with no errors.
=> Adds the Marshal BDU to the Marshal outfit lockers.

code/game/machinery/suit_storage_unit.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/simple_animal/friendly/ameridian_tender.dm
\- Fix examine not showing as unknown when wearing mask
\- Fix some typo in the ameridian tender's description.
\- Make the Ameridian Tender not controllable by default, but add a subtype that is.
=> Fix examine not showing as unknown when wearing mask

code/modules/clothing/masks/gasmask.dm, code/modules/clothing/masks/miscellaneous.dm
There is a difference between muffled and having a different voice now.
Added the ability to alter the transmitters in gas masks to turn you unknown. This is done with a screwdriver on ANY gas mask.
Adds in the ability to put voice recognizer from the assembly system onto any mask to give it the same effect as the gas masks.
This won't hide your face if the mask won't. BUT IT DOES WORK ON SNORKELS! Be warned it won't come back off once installed.
=> Mask Voice Transmitters

code/game/objects/items/stacks/medical.dm
<details>
<summary>
This buffs the soteria medical gauze that doctors can make to match normal gauze in brute healing and adds the missing toxin healing that the description states.
</summary>
<hr>
<hr>
</details>
:cl:
balance: Buffs Soteria Medical Gauze from up from 5 to 10 brute heal to match normal gauze and adds 5 toxin heal.
/:cl:
=> Buffs Soteria medical gauze 

maps/submaps/junk_field/j25_25/neutral/neutral1.dmm, maps/submaps/junk_field/j25_25/neutral/neutral3.dmm
Niko (some dumb coding nerd) keeps finding error logs in the junk fields of /obj/machinery/atmospherics/pipe/simple/hidden placed on a wall turf. I searched through the files and found these offending pipes. This deletes them. Maybe it'll fix stuff. Who knows.
Better off without them anyways. Atmos pipes shouldn't be placed on wall tiles. It breaks things.
https://i.imgur.com/daredxN.png
https://i.imgur.com/OFkFFog.png
=> Attempted bugfix for a mapping error in the Junk Field submaps.

code/game/machinery/doors/blast_door.dm
<details>
<summary>
</summary>
<hr>
Bypasses the need to sequentially call open() on every blast door that is mapped to spawn open during initialization by setting the variables to what the open() proc does to each door.
<hr>
</details>
:cl: Sakina
fix: Bypassed open() on blast doors mapped into the game open.
/:cl:
=> Blast door loading optimisations

code/game/objects/structures/burrows.dm
<details>
<summary>
</summary>
<hr>
Not sure if this counts more like oversight or a bug fix but you can now hammer cracks left behind from burrows (significantly harder and slower than just welding). Seeing as regular crack decals (?) can already be hammered up don't see why you can't this.
<hr>
</details>
:cl:
add: Hammering cracks after burrows
/:cl:
=> Burrow hammer

maps/__Nadezhda/data/shuttles-nadezhda.dm
<summary>
This PR simply alters the travel time of the Prospector shuttle from a whopping 15 minutes (not including time dilatation) down to 7 minutes instead. Reason for doing this is because by time the Prospector shuttle reaches somewhere, someone could of ran from the colony to the location within half the time which makes no sense.
</summary>
<hr>
</details>
=> Prospector Shuttle Buff

code/game/objects/effects/mines.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Makes it so that when a mob finds a new target it aggros instantly and tries to attack it.
BE WARNED. THIS HAS BALANCE IMPLICATIONS. This increases aggro rate by 3x, I think, which will make the strategy of ganking a lot harder. Also, makes trap spiders attack before you can get up in some circumstances. 
I started this as a bugfux but realized it is just a buff to most mobs. 
NOTE. I tested this. Mobs seem to aggro very well now, targetting works, no runtimes, but I can't profile it. For some reason I don't have access to the native profiller. I don't know why.
I personally support this PR, because I think ganking is a shit strategy, and if we are basing our balance off of it, that kinda sucks. If this causes issues, I feel the best course of action would be to instead change other …
=> Increases mob reaction time by approximately 300%.

code/modules/projectiles/gun.dm, code/modules/projectiles/guns/mods/mods.dm, code/modules/projectiles/guns/projectile/automatic/battlerifle.dm, code/modules/projectiles/guns/projectile/automatic/blackguard.dm, code/modules/projectiles/guns/projectile/automatic/bulldog.dm, code/modules/projectiles/guns/projectile/boltgun/baroque.dm, code/modules/projectiles/guns/projectile/revolver/tacticool_revolver.dm, code/modules/projectiles/guns/projectile/shotgun/sbaw.dm
- Added annotation guidelines for how zoom_factor var affects scoping in game, through extensive testing. This fixes the incorrect assumption that a 0.5 value means "five more tiles" when it's just 3.
- Standardizes most scopes and mods by rounding their values up to even values (amount of zoom unchanged)
- Ups the Blackguard zoom factor to 1 (8 extra tiles) as the scope was overwhelming for its (teleporter) power value, price and rarity.
- Minor typo fixes.
```
x0.2 = 1 extra tile
x0.3 / x0.4 = 2 extra tiles
x0.5 = 3 extra tiles
x0.6 / x0.7 = 4 extra tiles
x0.8 = 5 extra tiles
x0.9 = 6 extra tiles
x1 / x1.1 = 8 extra tiles (standard for anything to be considered a sniper rifle)
x1.2 = 9 extra tiles
x1.3 / x1.4 = 10 extra tiles (character no longer seen on screen)
x1.5 = 11 extra tiles …
```
=> Scope standardization

code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Title. THis is how it is because otherwise crit can be cheesed for most humans to not aggro any mobs and just kill everything. Also, this is the threshold eris originally uses for targetting, so it's only fair we use it here.
:cl:
tweak: Mobs will now stop attacking at -50 HP instead of just 0.
/:cl:
=> Makes mobs check for hardcrit on humans instead of just 0 health on most AI checks.

code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
tin
psi monsters/xenomorphs/greyson hypo drones are unaffected because 1. they should be stronger and 2. they'd feasibly be strong enough to pierce suits (xeno/psi)  or have a injector that ignores suits (greyson)
=> spiders now apply less venom to things that can't be injected

code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/game/objects/items/weapons/autolathe_disk/marshal.dm, code/game/objects/random/lathe_disks/guns.dm, sojourn-station.dme
Adds the missing disks for loot rotation of the 408 omnis and blackguard
Adds in every new marshal gun to a disk as well as in loot rotation
Fixes some names of disks
Fixes some disk location
=> Loot rotation and missing disks

code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/lodge/lodge.dm, code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/rook.dm, code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/friendly.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm
Makes scavs junkbots, churchs golem rooks, and all hunting lodge mobs have increased pritory targeting over anything else when a mob agros
Reduces xenos and a hunter spiders view range to not be as insainly large of an area
=> simple targeting tweaks

code/__DEFINES/admin.dm, code/__DEFINES/topic.dm, code/modules/admin/admin.dm, code/modules/admin/view_variables/helpers.dm, code/modules/admin/view_variables/topic.dm
Everything below is active to R_FUN, R_DEBUG, and R_ADMIN.
VV will now have a new drop-down feature on /atom: Save as copy. This will prompt the admin to first name the var copy, and then type, case-senstive, the name/key of every var they wish to save. Typing stop will end the loop and prompt the code to save the name as a key and the vars given into a associative global list.
This global list can be accessed by 3 verbs: Spawn Copy, which spawns a copy of whatever item you made a copy out of and then applies the vars you added to the list to it. Remove Copy, which remove a copy from the global list (please do this to save memory, if youre not going to use a copy). List Copy Names, which generates a list of the name/key of every copy that is currently saved.
To prevent exploits, a global …
=> Adds a new admin tool, var copies, that allow admins to copypaste var editted atoms.

code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Mobs will now actually respect their ideal range for firing. Also adds a var that controls how close they move vs how far they fire.
:cl:
fix: Makes it so mobs respect comfy_range
/:cl:
=> Makes it so mobs actually use comfy_range for their targetting.

code/game/mecha/equipment/weapons/melee.dm, code/game/mecha/equipment/weapons/ranged/bullet_weapons.dm
<summery>
This PR firstly adjusts the Autocannon and its jury rigged version taking into account of player given feedback, however would require someone to review the balance. Also removed the welding ability of the mech energy cutlass as it was preventing people from putting it on the mech...and pretty sure could be used to repair other mechs with your own mech due to the welding ability. Considering the limb plating that allows mechs to punch shit is considered a combat weapon and thus illegal without permit on a mech, I have increased its damage and material cost. 
<hr>
</summery>
=> More Mech Weapons: The Balance Edition

code/modules/shield_generators/shield_generator.dm
I want to use one of these in an event at some point abut I can't if they'll constantly scream about their damage status.
:cl:
tweak: Added a var to shield gens that allows them to not report it's damage.
/:cl:
=> Adds a var to shield generators that controls if it will report it's damage or not.

code/game/turfs/flooring/flooring.dm
Hey /SoJ/ once again me, ya cat in blue with Satan, storage nerfs once more been thought of and it clicked
Not having things on your back ISNT viable! Well Lets correct that here by making it so having anything on your back well running on underplating now a negitive!
Not waring anything on back will now always save you form tripping on platting!
=> Bags of Chaos!

code/game/jobs/department.dm
Every department now has enuff money to pay off a full shifts worth of people in 6 hours accounted for with neptism perk
This is in-additon to the already baseline spending money they get.
=> Better departmental accounts

code/game/objects/effects/spiders.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/spider_armor.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
Spider eggs now lay 1 less spiderling
Carrier spiders now drop 3 spiders rather then 5
Spiders now have 2 more armor groups, young and aged
Aged gives more health and better armor at the cost of speed!
Young removes health and armor, but has increased speed
Spiderlings now have odds to rather then grow up, just die
Spiderlings now take longer to grow as well.
=> spider tweaks and rng

code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Title.
This will do two things: 1. If a melee mob is stuck against a wall, it might rub itself over to the left or right and find it's way through a doorway to it's target on the other side. 2. If a ranged mob's can_see is returning false, erronously, which does happen, it might allow it to reposition to a position that lets it actually hit it's target.
One is questionable, but two is just a bugfix.
<hr>
</details>
:cl:
balance: Mobs will now wander if they can't see you.
/:cl:
=> Makes mobs wander a little if they can't see you.

code/game/objects/effects/spiders.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/spider_armor.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, code/modules/mob/living/carbon/superior_animal/roach/roach_armor.dm
Spiders have been lowered speed wise by 0.5
Spiders now have +5 energy armor to help them have a bit more survivability against basic laser arms to still stay a threat in those cases
Spiders now have 2 additonal armor prefixes,
venomous = +1 toxins per inject, 5 bomb armor 15 bio and rad armor and 10 pain armor
brutish = -5 energy armor 15 pain armor +2 damage +2 ap +5 health + 5 melee bullet bomb armor
Aged spiders now have 1 less toxin per bite
Young spiders have additionally 1 more toxin per bite
Pit snapper now has aranecolmin as its toxin
Bug fix: burning spider eggs now accully works
Orb weavers are less active in webbing/making a mess by 18~% (like 15 but what ever)
=> Slightly slower but more danger

code/modules/mob/living/carbon/human/human_damage.dm
Limbs now begin to take internal damage to their muscles and whatnot when 75% of the limb is gone, not at 40%.
=> Balance to Limb Damage

code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/life.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Title.
It was always weird to me how they followed you through walls. They don't do that anymore. They'll still chase down your most recent position, and will probably find you again, but now you can trick them by looping around.
Also fixes the bug with burst fire mobs firing when dead, improves some code, etc etc etc. I put the weakened check on handle_ai as that's the parent proc for many of the procs it was on.
:cl:
fix: Fixed burst fire mobs firing when dead
balance: Made mobs lose sight of you and chase your msot recent position if they lose LOS
/:cl:
=> Mobs lose sight and stop trying to follow you if you break LOS. They instead follow your position. Also a few bugfixes and code improvements.

code/game/gamemodes/events/blob.dm, code/game/gamemodes/events/carp_migration.dm, code/game/gamemodes/events/electrical_storm.dm, code/game/gamemodes/events/infestation.dm, code/game/gamemodes/storytellers/chronicler.dm, code/game/gamemodes/storytellers/healer.dm, code/game/gamemodes/storytellers/jester.dm, code/game/gamemodes/storytellers/mime.dm, code/game/gamemodes/storytellers/sleeper.dm, code/game/gamemodes/storytellers/warrior.dm
Enables voting for "Mime" Story teller. This disables story teller actions, used for when people want a more traditional "Green shift"
Reduces carp spawn in carp events.
Massively lowers jestors and warriors point gain
Lowers i.g most story teller point gains
Removes eletro storm form even triggering
Reducies time for blob to announce it is morbing out
Added Termites to story teller mob spawning
Added spider nests to story teller mob spawning
=> Better balance Of story Tellers

code/datums/perks/job.dm, code/datums/perks/nanogate.dm, code/datums/perks/psionic.dm, code/game/jobs/job/prospector.dm, code/game/jobs/job/security.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/reagents/reagents/race.dm
Since the fact of Blackshield and Prospectors having **extra damage reduction** was brought up **atop of the bonus health** currently given, I've went about removing the job perk damage reductions. This includes for Prospectors, Church and Blackshield, though they have received a changed perk instead. 
- Prospectors have gained a perk that allows them to be more resilient to drug addiction and a soft-buff to their NSA limit, as well as the ability to see what drugs/chems are in a container. To keep Prospector viable over salvager, I have given them a slight bonus to cognition and removed the salvager's bonus to cog, as their perk is better than the Prospector counterpart by a tad bit now.
- Blackshield have gained a perk that increases their resistance to explosions (Akin to Rough Life, …
=> Brute & Burn Modifiers Rework

code/game/machinery/kitchen/smartfridge.dm, code/game/machinery/xenobio.dm, code/game/objects/items/weapons/manuals.dm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
- Places Slime Dye Vat, "Slime Cores and Reactions" manual, a box of beakers, Dropper, and replaces plasma sheet with a beaker preloaded with 20u of plasma to prevent rendering the department useless if other scientists steal the mats for RND, to the Xenobio lab.
- Small room to the south of Xenobio gets an IV drip, a large beaker, a paper bin and some crayons.
- Xenobio surgery room shifted for ease of use, adds a proper slime storage unit next to it, as well as a table with a xenobio bag and a box of bodybags
- Replaces autopsy scanner for a proper slime scanner
- Virology has the Cure Research Machine removed due to its uselessness, instead replaced by a previously unused Pathogenic Isolator (more useful)
- Slime Storage SmartFridge can now also store slime potions
- Minor typo fixes …
=> [APPROVED] Xenobio buffs & Misc map fixes

code/datums/perks/psionic.dm
<details>
<summary>
Gives some health back to Psionics as-per feedback given on the previous PR that traded their brute/burn modifiers in for instead overall health. (This was done to avoid stacking brute/burn modifiers making them incredibly weak in some cases.)
</summary>
<hr>
<hr>
</details>
:cl:
balance: Changes psionic negative health from -30 -> -20 instead to be more fair.
/:cl:
=> Return of some Health to Psionics

code/game/jobs/job/captain.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm
<details>
<summary>
Basically does similar to #3565 but only removes negative health modifiers. This is a compromise alternative, fixing the major issue most players took in having negative health. In my opinion, I don't think jobs should have positive or negative health at all - but this PR makes 0 extra health baseline for non-combat/non-command position jobs (instead of -10) and keeps any added health to others jobs (ex prospector, marshal, etc)
</summary>
<hr>
</details>
:cl:
tweak: Removes any negative health added by jobs while not reverting positive health - as a compromise since most players voiced complaints about having negative health rather than the system itself.
/:cl:
=> Removes negative health modifiers

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Two substations in maintenance had no area of their own, so their internal APC was just powering maintenance. Fixed by giving them each an unused substation area. Additionally fixed an APC in southeast maint that wasn't inactive.
Also added Absolutist protection wall obelisks to cryo by request of CDB.
=> Fixes substations and APCs in maintenance, adds Church wall obelisks to cryo

code/game/gamemodes/events/hivemind_controller.dm, code/modules/hivemind/mobs.dm, code/modules/hivemind/wires.dm
Hivemind now by default no longer teleports away when damaged, no longer spreads through borrows and no longer gibbs dead people.
Staff in game can trigger these affects on and off
=> hivemind balances

code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
Kaiser Roaches now have limited acid spits before it swaps to melee
Re-targeting will force the kaiser to reload
This is a massive buff to roach kind
=> Kaizer rebalance

code/modules/biomatter_manipulation/toxic_biomass.dm
Biomapper mapped in no longer has its Aoe processing checks
Rather crossing over it will do the aoe attack.
This should sasdly reduce its lethality but have way less lag
=> Sadly less lethal biomatter

code/game/jobs/job/prospector.dm
Gives Salvagers their cognition bonus back
<details>
<summary>
</summary>
<hr>
Gives the 10 cognition back to salvagers. For some reason this was removed, causing the technicians to have less cognition than the Prospectors who gained the same bonus. Wouldn't be against having salvagers have more cognition than prospectors, but, for now, they're now equal in cognition stats
<hr>
</details>
:cl:
Gave salvagers their 10 cognition bonus back
/:cl:
=> Gives Salvagers back their cognition bonus

code/modules/modular_computers/file_system/programs/generic/trade.dm, nano/templates/trade.tmpl
Re-adds the direct selling feature that was unintentionally removed in [#3612](https://github.com/sojourn-13/sojourn-station/pull/3612). Also, adds a chat log alert when trying to sell or fulfill an offer without an account linked.
:cl:
adds: adds error message to the chat log when trying to use the trade program without an account linked
fix: re-adds direct sales
/:cl:
=> Trade fix: re-adds direct sales, some error messages

code/game/objects/items/weapons/emp_mine.dm
Allows emp landmine to be shot like other types of mines, making it a small bomb
=> Emp landmine counter

code/__DEFINES/is_helpers.dm, code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/carbon/superior_animal/superior_defines.dm
Mobs will now use hearers() to see if they can see their target if their target has a client. Somewhat more expensive than before, but now mobs will perfectly detect if they can see players.
The mob targeting delay is now modular.
Tested, no runtimes, etc.
:cl:
code: Mobs now use hearers() on mobs with clients for their can_see checks
code: Mob targeting delay is now modular and controlled by vars
/:cl:
=> Improves mob AI even more.

code/__DEFINES/mobs.dm, code/_onclick/click.dm, code/game/objects/items/weapons/tools/hammer.dm, code/modules/mob/mob_defines.dm
Hello hello /soj/ers and robust graytide alike. Down in the aether above talking with the lovely gods above we had relised that being bagless only really affecting underplating wasnt enuff to make it common outside running away form things. Well today with the help form those above I have decided to make it also now decrease click delay, yes thats right by sacrificing not waring things on your back you will be slightly faster on click cooldowns making a bagless ruin run much more viable as you gain more DPS and attack ecomics. This even is modular for admins to tweak for mobs or additional to perks in the further
With this additon ive also taken the liberty of standardizing the Seinemetall Defense \"Ironhammer\" Breaching Hammer to only be 2x slower then normal attacks rather then 2.2x …
=> Bagless Buff

code/__DEFINES/perks.dm, code/datums/perks/job.dm, code/datums/perks/oddity.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/prospector.dm, code/game/jobs/job/security.dm, code/game/objects/items/stacks/medical.dm, code/modules/reagents/reagent_containers/syringes.dm, code/modules/reagents/reagents/stims.dm, code/modules/surgery/organic_damage.dm, code/modules/surgery/surgery.dm, code/modules/surgery/surgery_ui.dm
Adds code to check for Medical's surgery perk (Or herbalist for hunters) to do surgeries or a bio of 50+. Some surgeries are locked behind this - mostly relate to organ repair, bone grafting and other surgery types. This 'lock' can be bypassed by using Ultrasurgeon, granting a temporary perk atop of its increase in biology allowing you to attempt surgery. Shrapnel removal has seen a **slight** increase in difficulty - but still has a 100% success rate if the person has 40 bio skill basically. Self surgery has also been penalized **heavily** by having a doubled fail-rate from what it was and a doubled time-wait.
As every 'balancing' PR is a take-and-give, I've lowered the requirement to use the advanced kits **heavily**. People who are non-Soteria with a bio skill of 25 (instead of 75) can …
=> Medical Perk-Checking

code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
Flashes are a crutch that let you cheese mobs and do combat with zero risk.
This combat should not have zero risk.
:cl:
balance: Reavers are now immune to flashes
/:cl:
=> Makes voidwolf reavers flash immune

code/modules/mob/living/living_defense.dm
Balances ballistic and energy overpen. Instead of energy doing 2x the normal over-pen damage, they only do the normal amount. Ballistics, since some bullet types and/or modifications to guns can shoot into multiple targets, have received a 0.8 modifier; making them do less overpen.
This is done due to the fact that overpen system has created a snowball effect of mob difficulty. Staff/Devs of the past saw players shoot their mobs with 8.6mm/.408s, which are doing 50+ damage to mobs every bullet due to their overpen modifier (Or worse - energy guns with high AP), and thinking: "Wow, my mob is shit" only to buff it. Not seeing what lower-end weapons do the the mob, as a 9mm/.35 round can only do roughly ~16 damage per hit on a mob with no armor; overpen included.
This should make it so:
1. …
=> The Armor_Overpentration Revolution & Its Consequences 

code/game/machinery/excelsior/blackshield_teleporter.dm
I added the Heroic to the teleporter, but there's no way to use it if you don't have the right mag (or in this case, linked box) to load it with, unless the armory is open (which means you could instead use the one in the armory) or printed through Guild. This PR adds an **empty** linked 7.62mm ammo box for the Heroic (and the Pulemyot) on the teleporter for 65 power.
<hr>
:cl:
add: Adds an EMPTY linked ammo box of 7.62mm to the Blackshield teleporter for 65 power cost.
/:cl:
=> Empty linked box on teleporter

code/datums/craft/recipes/guns.dm, code/modules/projectiles/ammunition/magazines.dm
- Adds empty 7.62mm rifle and 6.5mm carbine stripper clips to Guns tab of crafting menu
They're cheap, disposable pieces of metal meant to guide bullets quicker into feeding chambers or mags, they should be easy to obtain as a help for those that can't afford more advanced weaponry, in other words...**EVER UPWARD! GUNS FOR THE PEO-**
> -> [ [ [ This PR has been seized by Nadezhda Marshals for fostering Excelsior propaganda, have a good day. ] ] ] <-
<hr>
:cl:
add: Adds craftable stripper clips for 6.5mm carbine and 7.62mm rifle under Guns tab: 1 metal sheet, sawing quality of 10, hammering quality of 10.
/:cl:
=> Handmade stripper clips

code/datums/craft/recipes/guns.dm
I am very dumb.
<hr>
:cl:
fix: Fixes handmade stripper clip crafting datum bad pathing, 6.5 stripper clips should now be properly craftable.
/:cl:
=> Fixes handmade stripper clip crafting datum bad pathing

code/game/objects/items/weapons/storage/deferred.dm, code/game/objects/items/weapons/storage/firstaid.dm, code/game/objects/items/weapons/tools/tape.dm, code/modules/reagents/reagent_containers/hypospray.dm, code/modules/reagents/reagent_containers/pill.dm
- Replaces Dylovene pill bottle on Combat Medical Kit with Carthatoline pill bottle, as every chem inside it already WAS an upgrade over their normal counterparts, making it better at halting toxins damage and preventing liver from killing you. Also adds a bottle of blood restoration pills to help with bloodloss which would cause the former as well.
- Replaces one of the Quicklot syrettes with a Sanguinum syrette on the Oxygen Deprivation First Aid Kit for better treatment of causes of oxyloss.
- Combat surgery kits gain advanced bonesetter and drill (since every other tool except those was already advanced)
- Changes the advanced bone gel item description to make it obvious it's an upgrade.
- Standardizes pill icons based on chem colors across all pre-built pills for easier recognition. …
=> I HATE LIVERMED, I HATE LIVERMED, I HATE LIVERMED!!!

code/datums/wires/vending.dm
Used in a forthcoming PR. Adds a new wire hacking minigame for vending machines to use. It's still doable without needing to level MEC to see the wire names, but requires nonzero effort.
:cl:
add: Added a new wire datum for vending machines
/:cl:
=> New vending machine wire hacking minigame

code/game/jobs/job/medical.dm
<details>
<summary>
</summary>
<hr>
Adds the "Soteria Paramedic" and "Soteria Client Recovery Specialist" alt-titles to Trauma Team.
_Why?_
Trauma Team is a cool name, and a nice reference, but a little bit of variety is good to have. Also, I personally (not sure if others feel the same) would prefer to use the non-setting-specific title than one that's explicitly a reference.
<hr>
</details>
:cl:
add: Added two alt-titles to Trauma Team
/:cl:
=> Adds 2 alt titles for Trauma Team

code/game/objects/random/psi_loot.dm
<details>
<summary>
</summary>
<hr>
The list of psi loot spawns was named /obj/random/rig/item_to_spawn for some reason, meaning most of the spawns (i.e. non weapon-specific spawns) just straight up didn't work. There was no list to pull from.
<hr>
</details>
:cl:
fix: Psi loot should spawn properly now, allowing you to find more of it, as well as more variety.
/:cl:
=> Fixes psi loot spawns

code/modules/psionics/psionic_items/psi_armor.dm
closes #3717 
Fixes psion armor douping its cog removal if you speed remove it
=> Cog draining bad

code/modules/reagents/metabolism.dm
increases NSA lower cap so when a nerve gets fried people arn't stuck at 20 NSA till the nerve gets fixed. Instead increases it to 50 so people don't suddenly start dropping instantly from one bad nerve in the arm.
=> NSA lower threshold balance

code/modules/research/xenoarchaeology/artifact/artifact.dm
Had a request to make anomalies not have a find range of potentially only 2.5 tiles. Ups the minimum scanner detection range to 50 tiles and the upper limit to 250. EVERY FIND PICKS RANDOMALY BETWEEN THESE TWO NUMBERS.
=> Anomaly find range request

code/modules/projectiles/gun.dm, code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/automatic/drozd.dm, code/modules/projectiles/guns/projectile/automatic/maxim.dm, code/modules/projectiles/guns/projectile/automatic/ppsh.dm, code/modules/projectiles/guns/projectile/automatic/vintorez.dm, code/modules/projectiles/guns/projectile/revolver/wayfarer.dm
Quite shrimple.
Makes non-communists have a 60% chance (minus one's cog skill, so high cog can prevent this mechanic) of exploding if they use an Excelsior branded firearm. This has been lore for awhile and forcefully done by admins on people who use Excelsior gear - so now you have an actual downside that happens. (:
More to come in the future on separate PRs. Planned:
- Make it so upon using an Excelsior weapon with a Cruciform, Psionic organ or Nanogate - you just shoot yourself instantly to prevent the whole: "I can't be implanted so it's safe for me to **use** this!" mentality.
- Make it so armor will hurt you and/or explode if you are shot when worn and non-excelsior.
- Make it so Excel batteries had a chance to explode if not loaded into an excelsior machine or fired from a gun by …
=> Excelsior Guns as Lore Intended

code/__DEFINES/components.dm, code/__DEFINES/maths.dm, code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/carbon/superior_animal/superior_defines.dm, code/modules/projectiles/projectile.dm
Title.
Just lets us give mobs inaccuracy.
:cl:
code: Added the ability for mobs to be inaccurate with shots.
balance: Mobs now have 2 degrees of firing offset by default.
/:cl:
=> Adds firing offsets to mobs.

code/modules/admin/verbs/buildmode.dm
Previously, dead movement was on by default because I misunderstood my own proc. It is now off by default.
:cl:
fix: Pathmode now defaults to having dead movement off
/:cl:
=> Fixes a issue with pathmode's dead movement

code/game/objects/items/weapons/melee/energy.dm, code/modules/reagents/machinery/chem_dispenser.dm
closes #3775
Fixes eblades form implants deleteing themselfs incorrectly
Fixes chem dispensers using a bad proc on being blown up
=> chem and eblade fixes

code/modules/clothing/spacesuits/rig/suits/station.dm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Swapped out the old stewards suit which was the SI 'Retainer' control module with a hazard suit loaded with the same modules.  New suit offers better protection and may result in it getting used rather than collecting dust as the current one does.
=> Steward hard suit changes

code/game/machinery/autolathe/matterforge.dm
Was asked by Rebel if I could look into this after being told guild was using the ammo fab to print off ammo and get back more compressed matter than it took to print. This change makes it so the forge no longer takes ammo.
=> matterforge no longer takes ammo

code/modules/ameridian/ameridian_crystal.dm
Makes amerdian qdel on any explosion severity to make bombs and explosion the ultimate nuke option if everything else fails.
Should do the job nicely as a last resort
:cl:
tweak: Ameridian is weak to explosions now
/:cl:
=> Ameridian weak to explosions

code/modules/mob/language/ancient_latin.dm, code/modules/mob/language/esperanto.dm, code/modules/mob/language/german.dm, code/modules/mob/language/jana.dm, code/modules/mob/language/language.dm, code/modules/mob/language/monkey.dm, code/modules/mob/language/outsider.dm, code/modules/mob/language/serbian.dm, code/modules/mob/language/station.dm, code/modules/mob/language/yassari.dm
Ports over simple language understanding code. For an example of how this works:
Say a person speaks Serbian and the other speaks Russian. When speaking their languages, they have a 60% chance to understand **each** word from them. (I.E - they type "How are you today good sir?" - it may come up as "Vodka blyad cheeki good cyka?" or any combination as each word you type is a probability chance of 60 to understand)
Added a lot here, so I suggest reading the files changed per-langauge.
:cl:
add: Adds Bay's mutual understanding chance to languages. Ranging from 5% intelligibility between Latin and Common/English to 60% between Russian and Serbian.
/:cl:
=> Bay Port - Mutual Language Understanding

code/modules/core_implant/cruciform/machinery/wall_obelisk.dm
Maybe better codes wall oblistic to not scan *every atom*
Wall obelisks no longer care about mushrooms
Wall obelisks no longer suppresser borrows, this was never meant to happen in the first place
Massively increases wall oblistic damage
=> better wall obelisk optimization

code/game/mecha/equipment/weapons/ranged/laser_weapons.dm
<details>
<summary>
Does the PR for ApplePlastic but alternative way of fixing it. Instead of hard-removing I added a higher fire delay, charge cost and creation cost to the hydrogen mech weapon. Wacky how the weapon that does an explosion and 100 damage has no extra fire delay and low as shit cost. Quirky.
</summary>
</details>
:cl:
balances: Mech hydrogen cannon is no longer as broken-powerful. Even Trilby confirmed it had improper values.
/:cl:
=> Controversial PR #2: Soteria Nerf

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
The shield generator room is now using the main grid wire instead of the surface subgrid. The shield generator room has its own breaker too, in case you want to bypass it more quickly. 
Soteria's break room disposal is now properly connected. Soteria's backup generator is properly wired again.
Used FastDMM2 for this instead of strongDMM. Throw a brick at me if shit breaks
=> Shield gen Rewire plus Soteria map fixes

code/modules/multiz/shadow.dm
Title. This fixes bugs such as mobs not doing AI if they change zlevels.
:cl:
fix: Mobs now properly change zlevel if they use forcemove
/:cl:
=> Causes mobs to update their zlevel if they actually change zlevel through forceMove

maps/_HunterLodge/map/_Hunting_Lodge.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm, maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
All heads of staff have lost their bed, heads of staff rooms has also been shrunk as well
Genetics has been reduced to 1/3d its size
Organ Theater has been made its own room
Fixes a few errors in map like doble stacked lockers or wall items
Fixes Wall lockers that could not be closed
Lighting/cameras on low walls have been corrected (that i know of)
Guild lobby now has shutters and a proper line
Fixes floors and missing roof in the hunting lodge
=> dorms nerf

code/modules/aberrants/organs/mods/5_upgrades.dm
Health buff down to 20% from 40%, specific organ size increased by 0.5
:cl:
balance: Durable membrane damage threshold buff reduced to 20%, added specific size mod of 0.5
/:cl:
=> Nerfs durable membrane

code/modules/mob/mob.dm, code/modules/mob/mob_movement.dm
Problem: Mobs had density set to TRUE on death, all of them, and mobs couldn't rest under one another
Fix: Putting set_density behind a deadcheck, so deadmobs dont have this set. NOTE, this may cause unforseen consequences in certain parts of this spaghetti of a mobcode. Also, adding (lying || moving_mob.lying) to /mob.canPass(), which is true if either of the mobs are resting. 
WARNING. The canpass change might break shit, it probably won't but jesus christ this code is so fucked it might fucking delete the entire database if we're unlucky.
Testing steps:
1. Spawn in as BST and turn on ruin_everything mode
2. Run around and kill some roaches
3. Lead roaches through the corpses of their allies. They don't avoid them. This is good
1. Spawn 2 BSTs in
2. Try to rest under one
3. Success …
=> Hopefully fixes mobs avoiding dead mobs in pathfinding, fixes mobs not being able to rest under eachother

code/modules/mob/living/say.dm
Falloff should properly work now.
Before this PR, falloff didn't work (text getting smaller when youre far away). This was due to me only checking if distance < falloff. I've changed it to first check distance <= message_range (full sized text range), then if thats false, distance <= falloff. 
Testing steps:
1. Load in
2. Spawn in as 2 BStechs 8 tiles away with message_range of 7 and falloff_range of 10
3. breakpoint line 262 of saycode
4. Say something and watch
Results: Anything past message_range consistantly was added to falloff_listening instead of listening
This PR doesn't really have any IC impact whatsoever, although some people might crack jokes about how things are quieter now. Not something worth any ic announcent or smthm.
:cl:
fix: Fixed saycode falloff
/:cl:
=> Fixes a dumb mistake I did in saycode

code/game/machinery/camera/camera.dm, code/game/objects/items/weapons/storage/storage.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/reagents/reagents/dispenser.dm, code/modules/reagents/reagents/toxins.dm
By [MLGTASTICa](https://github.com/MLGTASTICa)
balance: Acid now takes into account all worn clothing
balance: Acid now melts clothing before dealing damage.
fix: Multitool interactions with camera
fix: Some items showign up through z-levels at time
fix: Lookup not working at times
By Wouju
fix: Hivewires cant be killed via plantbgone anymore, acid can now kill wires by being sprayed on
Testing: Made sure it complies
impact on perforance, likely not improving cpu uses when intracting with these
closes #3810
=> Eris fix ports

code/modules/organs/internal/heart.dm, code/modules/organs/internal/kidneys.dm, code/modules/organs/internal/liver.dm, code/modules/organs/internal/lungs.dm, code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm, code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
Adds in more into both Arua and Introversion weapons and gear so that when you unlock them you have more things to buy
This also includes a MOLLE pack and some emps (that you already can get form other trade stations)
Sol Fed branded gear (Note: These are not the super op admin only ones)
China lake and the ammo for it
Organs no longer sell for insain amounts
The Arua now asks for advanced organs rather then basics (other then kidneys)
Introversion now wants uplinks and emags
Preformance: More stuff to stock in trade ships
=> syndacat trade beacon buffs

code/modules/mob/language/ancient_latin.dm, code/modules/mob/language/esperanto.dm, code/modules/mob/language/generic.dm, code/modules/mob/language/german.dm, code/modules/mob/language/jana.dm, code/modules/mob/language/jive.dm, code/modules/mob/language/language.dm, code/modules/mob/language/monkey.dm, code/modules/mob/language/outsider.dm, code/modules/mob/language/serbian.dm, code/modules/mob/language/station.dm, code/modules/mob/language/synthetic.dm, code/modules/mob/language/yassari.dm, code/modules/mob/living/say.dm, code/modules/modular_computers/file_system/programs/generic/configurator.dm, code/modules/modular_computers/hardware/printer.dm, code/modules/paperwork/carbonpaper.dm, code/modules/paperwork/paper.dm
Ported a bunch of Bay's language code system to make the partially intelligible language system work properly. Language users now will properly be able to understand one another within the probability values given previously.
Also ported the system from Bay allowing languages to be written on paper. Computer tablets and consoles, that sport a printer that is, can be configured via program to allow printing of documents in specific languages as well.
Written language system (Serbian speaker -> Russian speaker - 60% Understanding)
Verbal language system (Serbian speaker -> Russian speaker - 60% Understanding)
Future to-do: Make it so scanners/copy machines can copy into different languages. Not urgent so I'd prefer this be merged first since that will take time to do.
:cl:
fixes: Language …
=> Fixes Language Intelligibility & Adds Written Languages

code/game/objects/items/weapons/material/kitchen.dm, code/game/objects/items/weapons/shields.dm, code/game/objects/items/weapons/swords_axes_etc.dm, code/game/objects/items/weapons/tools/stunbatons.dm, code/modules/projectiles/gun.dm
Kltuz has been relooked at in its hard stuns to be less long and more in line with how are combat works rather then being down and out of the count for 10 seconds well waiting for your ticket to decide that you can infact get up
Shooting yourself with a rigged/klutz gun no longer drops and bricks the gun
Shooting yourself with a rigged/klutz gun no longer drops at all
Testing: Made sure it complies
Performance: Stunbatons klutz takes more performance everything else is the same
=> Klutz balance pass
