sojourn-13/sojourn-station

code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm

Mobs attacking the area around them has been corrected.
Hopefully

ruin has come

---

code/game/machinery/deployable.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/girders.dm
code/game/objects/structures/grille.dm
code/game/objects/structures/low_wall.dm
code/game/objects/structures/railing.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/tables/tables.dm

Tested to work once more
Dont mind the burning
Makes it so mobs correctly now can attack things like closes, grills, tables, ect

it all works and complies

---

code/game/machinery/autolathe/matterforge.dm
code/game/objects/items/devices/radio/radio.dm
code/modules/power/port_gen.dm
code/modules/shield_generators/hull.dm
code/modules/shield_generators/shield_generator.dm

Nanoфorge no longer lies about stored matterals
фixes pacman, intercoms and shield generator tool actions
фixes shield generators magiclly never unconnecting фorm their network when wrenched and unwrenched.
:cl:
/:cl:

many misc corrections

---

code/__HELPERS/logging.dm
code/modules/admin/admin.dm

Uncomment the admin logging code.

---

code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm

Makes mobs see once more that grills are their way
super mobs now deal same damage to lower walls and grurders

Mobs will attack grills again

---

code/modules/projectiles/ammunition/ammo_kits.dm

Ammo kit name фix, 40mm -> 30mm

Update ammo kits. 

---

code/datums/mob_stats.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/organs/internal/psionic.dm
code/modules/psionics/psion.dm
code/modules/psionics/standardpowers.dm

<details>
<summary>
</summary>
<hr>
Fixed starting Psi Points so they start the round with points equal to their maximum.
Fixed Psi Points causing issues when removed from the body.
<hr>
</details>
:cl:
Fixed starting Psi Points so they start the round with points equal to their maximum.
Fixed Psi Points causing issues when removed from the body.
/:cl:

Psi starting points fix

---

code/game/objects/items/devices/defib.dm
code/modules/mining/ore.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/mob/living/silicon/robot/inventory.dm
code/modules/mob/living/silicon/robot/robot_dogborgs.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

Thanks to Occulus, cyborgs can now have shockpads
Crossing over ore should now auto-pickup ores as a human or as a borg

ports things

---

code/game/objects/items/weapons/storage/pouches.dm

People keep eating the grow a guns

Adds a warrening lable

---

code/datums/outfits/jobs/science.dm
code/game/objects/items/weapons/storage/belt.dm

Make the roboticist's scanner spawn in the pocket instead of the belt and put the cable coil in the belt instead of in the backpack.

Smol loadout change

---

code/datums/datum_click_handlers.dm

фrom MLGTASTICa - makes automatic guns not sleep

Lag correct???

---

maps/CEVEris/_Hunting_Lodge.dmm
maps/CEVEris/_Nadezhda_Colony_Surface.dmm
maps/CEVEris/_Nadezhda_Colony_Transition.dmm
maps/CEVEris/_Nadezhda_Colony_Underground.dmm
maps/CEVEris/_Nadezhda_areas.dm
maps/encounters/deeptunnels/_Nadezhda_Deep_Tunnels.dmm

Adds missing decals to top side colony
Corrects railings placements
Corrects area names in blackshield being "sec"
Moves around some buttons and corrects perimer shutters
Corrects some tiles
Adds many more decals around the colony as a whole
Adds a фlamer thrower to blackshield armory
Adds фluфф around the shield generator
Corrects misc bad things that are oф no note

decals, corrects and changes

---

code/__DEFINES/craft.dm
code/datums/craft/item.dm
code/datums/craft/recipe.dm
code/datums/craft/recipes/guild.dm
code/datums/craft/recipes/guns.dm
code/datums/craft/recipes/lodge.dm
code/datums/craft/recipes/machinery.dm
code/datums/craft/recipes/medical.dm
code/datums/craft/recipes/misc.dm
code/datums/craft/recipes/tools.dm
code/datums/craft/step.dm

Ports a ton corrections to making items
Makes some items have less/condenced steps to have less clicking

making correctoins

---

code/__DEFINES/craft.dm
code/datums/craft/recipe.dm
code/datums/craft/recipes/guild.dm
code/datums/craft/step.dm
code/modules/power/port_gen.dm
code/modules/shield_generators/shield_generator.dm
maps/CEVEris/_Nadezhda_Colony_Surface.dmm

Pacman and sheild generator can now be deconned
фixes some bad craфting steps
фixes a bad pipe

craфting and shield/pacman фix

---

code/controllers/subsystems/voting/poll_types.dm

5 hour vote

---

code/__DEFINES/perks.dm
code/datums/perks/nanogate.dm
code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
code/modules/modular_computers/computers/subtypes/preset_console.dm
code/modules/nanogate/nanogate_items.dm
code/modules/nanogate/nanogate_powers.dm
code/modules/nanogate/powers/nanobot.dm
code/modules/nanogate/powers/rig.dm
code/modules/nanogate/powers/user.dm
code/modules/organs/internal/nanogate.dm
code/modules/psionics/psionic_items.dm
code/modules/sanity/sanity_mob.dm

-Removed some nanogate powers that were copy pastes of psion powers. Will have them replaced later.
-Updated the nanobot treatment chems to be alot better.
-Fixed an issue wih the consoles being below your nanobot when deployed.
-Updated alot of the text and descriptions to most of the content.
-Rebalanced some of the power costs.
-Added the debuff that nanogates give by halving inspiration and readded a missing addition to inspired to give mar'qua there +50% inspiration gain rate back.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Nano Gate Work

---

code/__DEFINES/misc.dm
code/controllers/configuration.dm
code/modules/client/client_procs.dm
code/modules/client/preference_setup/global/01_ui.dm

<details>
<summary>
Uhhhhhhhhhhhhhhhhhhhhhhhh I don't know why this was disabled
</summary>
<hr>
<hr>
</details>
:cl:
add: Re-adds client FPS?
/:cl:

[Apparently works] Client FPS re-enabling.

---

code/game/objects/items/devices/radio/radio.dm
code/game/objects/items/weapons/cigs_lighters.dm
code/game/objects/objs.dm
code/game/objects/structures.dm
code/game/objects/structures/girders.dm
code/game/objects/structures/low_wall.dm
code/game/objects/structures/railing.dm
code/game/objects/structures/window.dm
code/game/turfs/simulated/wall_attacks.dm
code/game/turfs/simulated/walls.dm
code/modules/detectivework/forensics.dm
code/modules/materials/materials.dm
code/modules/mob/living/carbon/human/human_defense.dm

фorm MLGTASTICa
add:Getting hit by an item now transfers your fibers to it
add:Dismantling windows,walls,griders and railings now leaves your fingerprints on the sheets they spawn
balance:Made windows always throw glass shards nearby
balance:Increased chance to leave suit fibers from 10 to 30
balance:Increased chance to leave uniform fibers from 15 to 45
balance:Increased change to leave glove fibers from 20 to 60
balance:Climing over low walls and rails leaves prints
code:Made the drop_matter proc accept user as a argument to leave fingerprints with
add:Ciggaretes now have a chance to grab your fingerprints everytime you put them in your mouth, or when you treat them.
fix: Radios now take your fingerprints when you use them

the detective update that we all wanted

---

code/game/machinery/excelsior/ex_turret.dm
code/game/machinery/portable_turret.dm

Contributor
SugarBone
Turrets no longer get hit when tooled/reloaded/celled/on help intent

corrects turrets

---

code/modules/reagents/reagent_containers/food/condiment.dm

Small surgar now has a 50% icon to spawn 
corn oil now has its proper sprite

Corrects olive oil

---

code/game/objects/items/weapons/mine.dm
code/game/objects/random/traps/traps.dm

AHHHHHHHHHHHHHHHHHHHHHHHHH
Landmines now will kaboom when shot
Landmines were re-hidden
Improvised Landmines now spawn armed once more

Landmines now when shot will explode

---

code/modules/clothing/accessories/holster.dm

hot correction - Sieg

---

code/ATMOSPHERICS/atmospherics.dm
code/ATMOSPHERICS/components/unary/vent_pump.dm
code/ATMOSPHERICS/components/unary/vent_scrubber.dm
code/__DEFINES/machinery.dm

Legit banaid correction to an issue I cant correct. This issue is so dumb

banaid correction to prevent vent/scrubber power generation 

---

code/modules/sanity/sanity_mob.dm

Make the Mar'qua Inspiration Perk and the Nanogate Perk actually affect inspiration gain.

Fix insight

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

a single wire

---

code/modules/sanity/sanity_mob.dm

Hopefully fix the insight gain.

Hopefully fix the insight gain.

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
The new residential district
https://cdn.discordapp.com/attachments/860194987392368700/888769132756107324/dormsV2.png
The previous dorms retrofit into free shops 
https://cdn.discordapp.com/attachments/860194987392368700/888776236271271996/simple.png
</summary>
<hr>
<hr>
</details>
:cl:
add: A new residential district with four F3 dorms, plus a new substation and a little bit of maintenance tunnels.
fix: A wire in the guild was not connected correctly.
add: Two public access claimable shops for all the colonists various commercial needs.
add: Moved the drones fabricators to the ladder shaft between the guild and robotic.
/:cl:

Residential distric & various map changes

---

code/game/objects/items/weapons/storage/judgement_sheath.dm

Corrects icon pathing and that it cant hold its own swords

Update judgement sheath to work

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
A few errors in the residential district.
</summary>
<hr>
<hr>
</details>
:cl:
add: Four church protection in the dorms to prevent mob spawn.
fix: There was a light missing in the ladder shaft.
fix: Forgot a cable under the powernet sensor.
/:cl:

Minor mapping fixes

---

code/game/objects/items/weapons/storage/judgement_sheath.dm

I rather not talk | type about it | action

Error correction

---

code/modules/projectiles/guns/projectile/pistol/olivaw.dm

Fix the Olivaw's burst fire to be a 2-round burst like its description say.

Fix the Olivaw's burst fire

---

code/game/machinery/vendor/misc_vendors.dm
code/game/objects/items/weapons/storage/blackshield_kits.dm
maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

Colt pack blackshield kit now has high caps
STS pack now has correct ammo
Blacksheild vender added to blackshield
Laser armor kit moved to vender

mapped in and tweaked

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

Makes the blackshield shocker kit have the correct cell with it

bad cell b-gone

---

code/game/objects/items/weapons/storage/blackshield_kits.dm

- Give the Cog Kit a pouch that can hold the cells.

Give the Cog Kit a pouch that can hold the cells.

---

code/game/objects/effects/spiders.dm
code/game/objects/random/mob/spider.dm

Spider lings that are spawned by carrers can no longer grow into carrers. As carrers spawning carrers is rather dumb and lame
spider egg, and normal spiderlings can make carrer spiders as thats reasonable

spiderling correction

---

code/__DEFINES/tick.dm
code/__HELPERS/game.dm
code/controllers/subsystems/processing/mobs.dm
code/game/machinery/doors/airlock.dm
code/game/machinery/doors/door.dm
code/game/objects/explosion.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/life.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
code/modules/mob/living/carbon/superior_animal/life.dm
code/modules/mob/living/carbon/superior_animal/roach/life.dm
code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/living_powers.dm
code/modules/mob/mob.dm
code/modules/sanity/sanity_mob.dm

Contributor
MLGTASTICa
Reworks how superior animals are handled to avoid a lot of unnecesarry checks , predominantly roaches and spiders
Cuts down a lot of lag , maptick CPU increase prevents "Screen-freezes"
If you fucks merge this instantly to main i will be very angry if everything breaks down.
Scratch the maptick , 20% is already generous
Upon additional testing and changes, MS usage now falls all the way down to 80 MS(roaches still used life as their ai)
Changelog
🆑
balance: roaches and spiders can no longer be put into cryotubes
code: reworked how roaches and spiders are handled to lag less
code: Increased maptick CPU to prevent screen freezes
code: reworked the AI activation for roaches and spiders to be less laggy
/🆑
Also corrects …

Superior animal handling rework , Maptick CPU no longer increased + door correction #6546

---

code/game/objects/items/weapons/storage/blackshield_kits.dm

Swaps out the generic bullet helmet with the blackshield type

ballistic militia

---

code/game/objects/items/weapons/storage/belt.dm

-Changed the hunting belt storage from 7 to 11 slots.

Hunting belt QoL

---

code/__HELPERS/filters_effects.dm
code/modules/core_implant/cruciform/rituals/priest.dm

This PR fix the holy glow so that it correctly make those affected glow instead of the one casting the ritual.
It is an alternative to https://github.com/sojourn-13/sojourn-station/pull/1981
Here is how it should actually glow :

Fix the holy glow.

---

code/modules/core_implant/cruciform/rituals/path.dm

I figured out a way to make those affected only glow once instead of once per prosthetic limb & organ.

Fix the Mass Repair Litany glow.

---

code/game/objects/structures/burrows.dm

Allows RnG borrows, to be at a glance be told is a deep maints ladder

Borrow tweak

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

corrects AI core wires
corrects AI core piping
Makes the AI core have shutters (they are meant to)
makes the guild lobby have more storage rather then lockers as they have their own dorms
removes guilds starter trash cube and pile ripper
adds more camera's to the training area so you can obser whats going on

way better wiring

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

Corrects the mult-z wire again
adds more anti-tampering messes to the maints area

single wire

---

code/modules/projectiles/gun.dm

Turns out @Kazkin overwrote a correction eris made to maths

corrects vig being op

---

code/modules/clothing/shoes/costume.dm
code/modules/clothing/shoes/miscellaneous.dm
code/modules/clothing/spacesuits/void/wizard.dm
code/modules/clothing/suits/armor.dm
code/modules/clothing/suits/costume.dm
code/modules/clothing/suits/greatcoat.dm
code/modules/clothing/suits/jobs.dm
code/modules/clothing/suits/miscellaneous.dm
code/modules/clothing/suits/storage.dm
code/modules/clothing/under/costume.dm
code/modules/clothing/under/jobs/civilian.dm
code/modules/clothing/under/jobs/engineering.dm
code/modules/clothing/under/jobs/militia.dm
code/modules/clothing/under/miscellaneous.dm
code/modules/clothing/under/pants.dm

Went through most clothes and adjusted some grammar errors, capitalized faction names and ranks.
Lowered the triad jacket's armor value (approved by possum) because whoever made it gave it stats better than most armor vests. Lowered other coat's values because they didn't make sense and people powergamed.
Lowered some hunting lodge armor values because someone kept power creeping them to be better than their counterparts.
Let me know if you find any more grammar errors so I can change them.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Clothing grammar fixes, mostly

---

code/datums/craft/recipes/guild.dm
code/datums/objective/individual_objective/church.dm
code/datums/objective/individual_objective/common.dm
code/datums/objective/individual_objective/guild.dm
code/datums/objective/individual_objective/individual_objective.dm
code/datums/objective/individual_objective/ironhammer.dm
code/datums/objective/individual_objective/moebius.dm
code/datums/objective/individual_objective/prospectors.dm
code/datums/objective/individual_objective/technomancers.dm
code/game/area/Space Station 13 areas.dm
code/game/jobs/job/job.dm
code/modules/clothing/under/costume.dm
code/modules/mob/mob.dm
maps/CEVEris/_Nadezhda_areas.dm

-Modifies the prospectors to have their own objectives.
-Adds some/modifies existing objectives.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Personal Objective Update

---

code/modules/mining/satchel_material_box.dm

At @Kazkin request, I reworked the Material Sheet Box so that it actually worked.
It display the total amount of mats inside as well as the total material cost.

Rework the material box

---

maps/encounters/deeptunnels/_Nadezhda_Deep_Tunnels.dmm

adds 4 materal boxes, removes random blue wire under doors

---

code/game/machinery/autolathe/fabricators.dm
code/game/machinery/doors/airlock.dm
code/game/machinery/doors/airlock_control.dm
code/game/machinery/doors/door.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/power/smes.dm

By 
MLGTASTICa
Corrects doors closing and locking
By Trilby
Makes mobs able to get common when controled by a player
Makes SMES require 25 or a perk to use
Makes the new miner bot way more easyer to use as a ghost
Makes the bullet printer require the same trainning or mechical check as matter nanoforge to keep it constant

misc and targeted corrections

---

code/game/machinery/autolathe_disk_cloner.dm
code/modules/scrap/oldificator.dm

The disk cloner is now exl branded as it is
Old disks now have less licenses

exl disk cloner + older disks

---

code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm

Make the mining drone able to be controlled by ghosts. Mostly @Trilbyspaceclone.
If you want you to play one you'll have to ask an admin.

Make the mining bot ghost-compatible

---

code/modules/mob/living/carbon/human/human.dm

By
Contributor
MLGTASTICa 
Explosions no longer forcefully paralyse people , we got the pain to handle it now

removes hardstuns

---

code/game/objects/items/weapons/storage/storage.dm

Fix the message that appear when inserting objects into backpacks.

Fix the storing message

---

code/datums/craft/recipes/robot.dm

Make the mining bot require a diamond-tipped drill to make.

Make the mining bot require a diamond-tipped drill to make.

---

code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/roomba.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
code/modules/mob/living/simple_animal/hostile/hivebot.dm
code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
code/modules/projectiles/projectile/beams.dm

Lowers the lethality on laser mobs do to normale lasers now having AP meaning that basic armor isnt able to protect against it.

Tones down mob laser lethality

---

code/modules/power/smes.dm
maps/CEVEris/_Hunting_Lodge.dmm

Hunters can now use a really simple smes

Cold correction

---

code/controllers/subsystems/supply.dm
code/game/gamemodes/scores.dm
code/game/jobs/department.dm

Scores now use proper department names
LSS no longer gets magic money ever hour
by
Fiftyllama 
LSS credit score is now caultated by end round bank account rather then pure selling goods on the cargo shuttle

slightly better scores

---

code/modules/mob/living/carbon/human/human.dm

Update the pull punch verb to be smaller while not changing the output.

Update the pull punch verb.

---

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm

proper guns

---

code/modules/admin/admin_verbs.dm

New fix for the bypass, it was still falling into a false positive where it only affects you.

TimelocksBypassFix20

---

code/modules/projectiles/guns/projectile/boltgun.dm

Makes it look at both contents AND loaded.

bolt gun hot correction

---

code/datums/craft/recipes/lodge.dm

Bolts now need rods to make rather then other bolts, saving a step and many wasted bolts

Bolt making cold correction

---

code/game/machinery/vendor/misc_vendors.dm

Laser armor now costs the correct cost

corrects costs

---

code/modules/clothing/suits/armor.dm

Makes the ablastive armor have plat as lore demands

corrects armor costs

---

code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm

<details>
<summary>
</summary>
<hr>
Allows glasses of stuff that have an alternate drink sprite to swap out the default glass for the old alternate drink sprites we know and love.
<hr>
</details>
:cl:
Allows glasses of stuff that have an alternate drink sprite to swap out the default glass for the old alternate drink sprites we know and love.
/:cl:

While I'm at it, I want my milkshake to look like a milkshake too, I'm greedy like that

---

code/game/objects/effects/decals/Cleanable/humans.dm
code/game/objects/effects/decals/Cleanable/misc.dm
code/game/objects/effects/decals/Cleanable/tracks.dm
code/modules/detectivework/tools/swabs.dm

MLGTASTICa commented 2 days ago
Lets detectives sample the blood reagent for its DNA
fixes some code style
By Trilby
Looking at blood piles now tell you what kind shoe walked in them

more detective qol

---

code/modules/projectiles/projectile/special.dm

corrects the live time on dazzlation rounds

makes dazzlation  not instantly die

---

maps/CEVEris/_map_data_Eris.dm
maps/CEVEris/shuttles-nadezhda.dm
maps/encounters/deepforest/_Deep_Forest.dmm

removes spacecastle

---

code/__DEFINES/mob_stats.dm
code/__HELPERS/mobs.dm
code/datums/perks/job.dm
code/datums/perks/perk.dm
code/datums/perks/racial.dm
code/datums/setup_option/backgrounds/origin_akula.dm
code/datums/setup_option/backgrounds/origin_career.dm
code/game/atoms.dm
code/game/jobs/job/civilian.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/security.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/reagents/reagents.dm
code/modules/reagents/reagents/core.dm
code/modules/reagents/reagents/dispenser.dm
code/modules/reagents/reagents/drugs.dm
code/modules/reagents/reagents/food-Drinks.dm
code/modules/reagents/reagents/nanites.dm
code/modules/reagents/reagents/other.dm
code/modules/reagents/reagents/toxins.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Certain Reagents have gained the traits "Common" and "Illegal", to denote how easily they can be identified by different characters.
Reagents with the "Common" trait are easily identifiable by everyone. If a common reagent is the most abundent reagent in a solution, the average layman will be able to tell that the solution is "Mostly" made of the common reagent.
Reagents with the "Illegal" trait are identifiable by Marshal/BS, who recieved training to ID them. Anyone wearing Security Shades, and certain other neerdowells can identify illegal chemicals too.
The "Bar Menu" Perk was added. Those with the perk are able to see the exact amount of common reagents present in a container. They are available for:
- …

I said I wanted to know that I'm drinking a milkshake and I meant it

---

code/game/machinery/doors/holy_door.dm
code/modules/core_implant/core_implant.dm
code/modules/core_implant/cruciform/cruciform.dm
code/modules/core_implant/cruciform/modules.dm
code/modules/core_implant/cruciform/rituals/machinery.dm
code/modules/core_implant/upgrade.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/friendly.dm
code/modules/trade/datums/trade_stations_presets/boozefood.dm

-Updated the names and descriptions of the church doors.
-Fixed the apostle pathway for the church.
-Buffed rook golems, as they cost a high amount of rare supplies for what was a robot as shitty as prospie junkbots. They now have higher damage and armor.
-Fixed main.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Church Buffs

---

code/modules/goonchat/browserassets/css/browserOutput.css

By CDB
Corrects the eye bleed blackshield darkmode eye bleed

Removes blackshield darkmode eye bleed

---

code/game/objects/effects/decals/Cleanable/humans.dm

Makes blood dry in 10 mins rather then in 50~

Blood drys quicker

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm
maps/encounters/deeptunnels/backup/_Nadezhda_Deep_Tunnels.dmm

<details>
<summary>
</summary>
<hr>
Z-1 LEVEL OF SOTERIA
Z-2 LEVEL OF SOTERIA
<hr>
</details>
:cl:
add: Soteria upper level, moved a lot of rooms up there.
tweak: Most of the Soteria lower level got reworked.
add: A new maintenance tunnel, south of Soteria.
add: The future genetics lab construction site.
add: A light to R&D. Because why not?
add: A floodlight to the xenoarc' storage.
/:cl:

Soteria Major Remap initial commit.

---

code/game/objects/items/weapons/nt_melee.dm
code/game/objects/items/weapons/shields.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/human_movement.dm
code/modules/mob/living/carbon/superior_animal/roach/attack.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/mob.dm
code/modules/psionics/psionic_items.dm

By DarkLevelSS13
Reworked shields to provide armor increase and lesser knockdown immunity.
By Trilby
Rebalances sheild armor levels a bit and their health to be more brake-able and need maintaining
Removes lies in the halburd desk
Cleans up insainly log code lines in church weapons
Corrects roach taming

shameless shield rebalance

---

code/game/objects/items/weapons/storage/belt.dm

Fixes harnesses but sadly has to remove mask/hat storage

harness hotfix

---

code/modules/psionics/psionic_items.dm

stops an issue

---

code/game/mecha/working/ivan.dm

Buff the ivan max equipment slot from 2 to 3

Buff the ivan max equipment slot

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

Move the Drone Fab room and the ladder next to it by 1 tile, alongside the stuff associated with it, to make room to place the Robotic's shutters button next to said shutters instead of 3 meters away.

Move Drone Fab and ladder 1 tile

---

code/modules/sprite_accessories/_accessory_marking.dm

removes evil spaces

---

code/game/objects/effects/decals/Cleanable/humans.dm

Blood now takes around 3 mins to dry so its not as instant

Blood drys slower

---

code/__DEFINES/weapons.dm

Firemodes no longer over-ride icon states

Makes over-righting icons in gun modes no longer a thing

---

code/modules/mob/living/carbon/superior_animal/superior_animal.dm

Further changes the code to (hopefully) allow superior mobs to follow players. I tested it this time, I swear
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Further changes the code to (hopefully) allow superior mobs to follow players. I tested it this time, I swear
/:cl:

Fixing superior mob following properly

---

code/modules/mob/living/carbon/superior_animal/roach/riding.dm
code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm

The rootin tootin roach'ie con noow bee road like thath wind

Western Cat sounds

---

code/game/objects/structures/crates_lockers/closets/secure/militia.dm
code/modules/mob/living/carbon/superior_animal/roach/roach_summon.dm
sojourn-station.dme

Add a one-use item that can be used to spawn an already-tamed roach.
Put one of these roach spawner inside the Blackshield Commander's locker.

Add Tamed Roach Spawner

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

the better AI core

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

removes doble lights
removes a bad tile in the guild with a bad door

hot correction

---

code/game/machinery/doors/airlock_control.dm

By MLGTASTICa 
Corrects airlock crashes

airlock crash

---

code/modules/projectiles/projectile.dm
maps/CEVEris/_Hunting_Lodge.dmm
maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm
maps/CEVEris/_Nadezhda_Solar_Area.dmm
maps/encounters/deepforest/_Beast_Cave.dmm
maps/encounters/deepforest/_Deep_Forest.dmm
maps/encounters/deepforest/_River_Forest.dmm
maps/encounters/deeptunnels/backup/_Nadezhda_Deep_Tunnels.dmm

Dead bodies now shouldnt be useable as endless shield blocks

Corrects body blocking maybe

---

code/datums/objective/individual_objective/command.dm
code/datums/objective/individual_objective/common.dm
code/datums/objective/individual_objective/moebius.dm
maps/CEVEris/_Nadezhda_areas.dm

Removes all personal objectives to kill faction items or collect them
Removes odd gift objective do to lag
Removes Protector do to it being dumb bad and horrable
Adds 2 new personal goals
Re-adds back transfer and better explains how to do it

better goals and lag removed

---

code/modules/mob/living/carbon/shock.dm

Broken bones now deal 10 less shock
O2 damage deals more pain 
Fire damage deals less pain
Halloss (mostly tasers and disarms) deals sightly less
Cloneloss deals less
Slurring like being drunk or on heavy drugs heal more shock

Pain rebalance

---

code/__DEFINES/mobs.dm
code/_onclick/item_attack.dm
code/game/objects/items/devices/radio/radio.dm
code/game/objects/items/oddities_faction.dm
code/game/objects/items/stacks/medical.dm
code/game/objects/items/stacks/nanopaste.dm
code/game/objects/items/weapons/autopsy.dm
code/modules/biomatter_manipulation/bioreactor/biotank.dm
code/modules/core_implant/cruciform/rituals/group.dm
code/modules/core_implant/cruciform/upgrades.dm
code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/mob/living/silicon/robot/robot_items.dm
code/modules/organs/surgery_helpers.dm
code/modules/research/experiment.dm
code/modules/research/rdconsole.dm
code/modules/research/research.dm
code/modules/surgery/organic.dm
code/modules/surgery/surgery.dm

By Evankhell561
Much better scores, makes points work from biomatter made, rnd's and destoying some times
By MadmanMartian
add: Adds emergency self surgery.
add: Stand still, and use a sharp item on the limb with shrapnel in it to remove shrapnel from yourself.
add: Stand still, and use a hot item to cauterize any open wounds on yourself. Useful if you're out of bandages.

Two upstream prs

---

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm

Tweaks the blackshield disks costs to be more in line with marshals disks
Adds the backshield PPSH to their disk

disk and balance

---

code/modules/power/antimatter/control.dm

Add a way for admins and devs to prevent the AME from announcing stuff.

Add a way to prevent the AME from announcing stuff.

---

code/modules/reagents/reagents/drugs.dm

Many drugs now have a more legitment use other then leveling up or forcing emotes
Space drugs - 
Now acts as a pinkiller but also reduces cog
serotrotium -
Reduces cog,
Increases TGH stat
acts as a mild painkiller
and heals small bit of toxins
cryptobiolin -
Reduces cog,
Increases TGH stat
acts as a painkiller
and heals small bit of toxins
impedrezene -
Heals heart damage
Reduces Cog
Great painkiller
Increases tgh
Has an addiction that increases TGH and ROB
Mindbreaker Toxin -
Heals minor brute and burn damage
great painkiller
reduces cog
reduces tgh
acts as a blood cloat
withdraw now
deals some toxins 
increases both tgh and cog
psilocybin - 
Amazing painkiller
hyperzine - 
Increases hunger
Heals muscle  damage
If you have 50 or more damage 
will slowly give burns and brute damage
s

drug rebalance

---

code/modules/clothing/spacesuits/rig/modules/combat.dm

Ports over corrected rig hardsuit shield code

better code

---

code/game/objects/items/weapons/traps.dm

Both makeshift and normal bear traps now are much more lethal

Massively increases lethality of beartraps

---

code/game/objects/items/weapons/material/kitchen.dm

By 
MLGTASTICa
Fixes spoons bypassing masks

spoon correction

---

code/game/objects/items/weapons/grenades/emgrenade.dm

By
MLGTASTICa 
fix: Fixed Low Yield Emp Grenades having the same effects as a normal one.

Fixes low yield EMP grenades being as effective as normal ones

---

code/controllers/subsystems/tickets/tickets.dm
code/modules/admin/admin_verbs.dm

By hyperioo
Add Skill Issue autoresponse

skillissue

---

code/modules/projectiles/ammunition/boxes.dm

Fixes a issue with 257 ammo boxes not having cardboard
cleans up some code to be better
corrects .223 ammo boxes to store its ammo

better coding cleaning

---

code/modules/mob/living/carbon/superior_animal/drone/ai.dm
code/modules/mob/living/carbon/superior_animal/nanobot/ai.dm

Prevent Handmade robots & Nanobot from adding themselves to the friend list while adding any user.

Prevent Robots from adding themselves to user list.

---

code/datums/setup_option/core_implants.dm

-The guild master should now correctly be able to select the AG nanogate in character set up.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Guild Master NG hotfix

---

code/modules/clothing/spacesuits/rig/modules/modules.dm

Fix repairing rig modules with cables.

Fix repairing rig modules with cables.

---

code/game/objects/items/weapons/tools/bonesetters.dm
code/game/objects/items/weapons/tools/cauterys.dm
code/game/objects/items/weapons/tools/crowbars.dm
code/game/objects/items/weapons/tools/hammer.dm
code/game/objects/items/weapons/tools/hemostats.dm
code/game/objects/items/weapons/tools/knifes_daggers.dm
code/game/objects/items/weapons/tools/misc.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm
code/game/objects/items/weapons/tools/multitool.dm
code/game/objects/items/weapons/tools/pickaxe.dm
code/game/objects/items/weapons/tools/retractors.dm
code/game/objects/items/weapons/tools/saws.dm
code/game/objects/items/weapons/tools/scalpels.dm
code/game/objects/items/weapons/tools/screwdrivers.dm
code/game/objects/items/weapons/tools/shovel.dm
code/game/objects/items/weapons/tools/simple_weapons.dm
code/game/objects/items/weapons/tools/surgicaldrills.dm
code/game/objects/items/weapons/tools/tape.dm
code/game/objects/items/weapons/tools/weldingtools.dm
code/game/objects/items/weapons/tools/wirecutters.dm
code/game/objects/items/weapons/tools/wrenches.dm

-Went through and added actual values to every tool in the hopes of making the market for them a little more viable, will be subject to future balances and changes but I did the best I could.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Tool prices

---

code/modules/nanogate/powers/nanobot.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Fix Nanobot Naming

---

code/modules/mob/living/carbon/human/life.dm

Reverts sojourn-13/sojourn-station#2243

Revert "Fixes nanite regen to work on synths (as wiki intended)"

---

code/datums/craft/recipes/guns.dm

You can now craft the Pilgrim Claw

really fixes Pilgrim Claw

---

code/modules/reagents/recipes/recipes_food_drinks.dm

Antifepressant drink can now be made without conflicting the reagents

makes antidepressant actually craftable

---

code/game/machinery/vendor/misc_vendors.dm
code/modules/clothing/suits/gorka.dm

Adds a dark gorka 
Adds all gorka's to the clothing vender

dark gorka

---

code/__DEFINES/misc.dm
code/datums/datum_hud.dm
code/game/machinery/surveillance_pod.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/under/miscellaneous.dm
code/modules/mob/living/silicon/ai/ai_UI.dm
code/modules/multiz/movement.dm
sojourn-station.dme

add: armored version of type-34 helmet
add: surveillance pods, stationary version of camera MIU

ports Surveillance pods #6708

---

code/game/objects/items/devices/radio/headset.dm

Buffs CRO to hear and talk better with robots

CRO headset buff

---

code/datums/craft/recipes/robot.dm

Make the Aether Mining bot take a diamond drill to fit with them dropping a diamond drill on death.

Make the Aether Mining bot take a diamond drill.

---

code/game/objects/effects/spawners/ghostroles.dm
code/game/objects/random/ammo.dm
code/modules/projectiles/ammunition/ammo_kits.dm
code/modules/projectiles/ammunition/boxes.dm
code/modules/projectiles/ammunition/bullets.dm
code/modules/projectiles/ammunition/magazines.dm
maps/encounters/deepforest/_Prepper_Bunker.dmm

Ammo box correction + bullet fix

---

code/modules/mob/living/carbon/superior_animal/roach/roach_armor.dm

Massively reduces roaches mutations allowing them to get less armor

rebalancin roaches mutation odds

---

code/game/objects/items/weapons/stock_parts.dm

Makes all the handcrafted parts say they are handcrafted to help more easily at a glace reading them to tell if its t5 or t4

handcrafted

---

code/modules/projectiles/projectile.dm

Kris stop being me as a shield, im DIEING  -- Tested to work

---

code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm

NO WOUNDER WHY SPIDERS ARE LOSING

Nurses when webbing things now get fed again

---

code/game/objects/items/weapons/tools/simple_weapons.dm

Preimers sabler is now called decorative saber to stop their being 40 different preimer sabers

renames premiers saber

---

code/modules/mob/living/carbon/superior_animal/nanobot/ai.dm

Slapping the bot no longer act as slapping the console.

Remove Nanobot Legacy Code

---

code/modules/mining/drilling/ore_sonar.dm

Ore Sonar Fix

---

code/modules/projectiles/guns/plasma/hydrogen.dm

Unfuck the Process() proc of the hydrogen plasma guns, that I did back when I didn't know how it worked.

Unfuck process()

---

code/modules/genetics/genetics.dm
code/modules/genetics/machinery/genetics_cloner.dm
code/modules/genetics/machinery/genetics_extractor.dm
code/modules/genetics/recipes/cloning_recipes.dm
code/modules/reagents/reagent_containers/bidon.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Removed verbs for interacting with the cloner through object interactions. Now you have to operate it via the console exclusively.
Fixed Icon updating for the bidon can, so the correct anchoring sprites show.
Fixed an issue causing a majority of the cloning recipes to not function correctly. Go make some cows with chocolate milk!
/:cl:

Genetics fixes

---

code/modules/economy/price_list.dm

Selling smokes is no longer more money then it takes to buy them.

smoking ecomy

---

code/game/objects/random/mob/misc.dm
maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

-Adds some atrocity spawns to maintenance shafts.
-Except for one (which is static), the rest all have a 20% spawn chance.
-They're usually found near roach spawns.
-god forgive me

Adds genetic atrocities to maintenance

---

code/game/objects/effects/roaches.dm
code/game/objects/effects/spiders.dm
code/modules/mob/living/carbon/superior_animal/roach/life.dm
code/modules/mob/living/carbon/superior_animal/roach/roach.dm
code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm

basiclly buffs SI
Roaches grow up, eat and lay eggs MUCH faster and more actively
Roaches on gibbing people will remove all their gear to prevent nulling items illegally
Roaches now will try and eat spiderlings if they can
Spider nests have been toned down again to allow them to not endlessly swarm areas and out spawn even admins spam clicking roach eggs

massive roach buff

---

code/game/objects/items/devices/radio/headset.dm

Fixes CRO headset

---

code/modules/mob/living/simple_animal/hostile/hivebot.dm

forgotton seekers are not longer frendly

forgotton seekers are not longer frendly

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
fix: The guild mixing chamber got her plasma windows back.
tweak: Moved a bin three tiles to the left in the genetics lab.
tweak: Changed the type of two walls in the robotics hallway.
/:cl:

Minor map fixes

---

code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm

Hopefully make the mining bot less laggy when picking up or dropping large quantity of items.

Hopefully make the mining bot less laggy

---

code/game/objects/items/weapons/autopsy.dm

The sci-fye magic scanner now when scanning a wound will give the correct weapon used a 100% of the time

autopsies are a 100% correct when scanning

---

code/__HELPERS/_lists.dm

By Kevinz
typecache filter list microoptimization

ports micro-optimation

---

code/game/machinery/doors/door.dm
code/game/mecha/mecha.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/mob/mob_defines.dm
code/modules/multiz/movement.dm
code/modules/multiz/ztravel/climb.dm
code/modules/multiz/ztravel/phase.dm
code/modules/multiz/ztravel/zmethod.dm

By MLGTASTICa 
makes unscrewd doors able to open when bumped into
By SirRichardFrancis 
Fix invisibility after z-travel
By Kegdo 
fix: Fixed not being able to harm borgs with certain tools
By Trilby
Adds basic cooldowns to mech and robots
Fixes speed-attacking mechs
Updates zmethod file to be upto date with eris

Robobalance

---

code/game/objects/items/weapons/storage/belt.dm
code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm

Nano bots when cut up will drop scrap rather then meat
many more belts can hold radios

few small fixes

---

code/modules/mob/living/silicon/robot/drone/drone_items.dm

Matter eaters can once more eat remains

matter eater fix

---

code/game/mecha/mecha.dm

Is a dumb and intented one to many times

Mech attachment fix

---

code/game/machinery/autolathe/fabricators.dm
code/modules/projectiles/ammunition/boxes.dm
code/modules/projectiles/guns/energy/nuclear.dm

Empty mags are now labeled Empty

bulletfab name fix

---

code/modules/surgery/surgery_ui.dm

<details>
<summary>
</summary>
<hr>
Fixes prosthetic organs so they can be extracted during surgery.
<hr>
</details>
:cl:
Fixes prosthetic organs so they can be extracted during surgery.
/:cl:

Allow prosthetic organ extraction

---

code/modules/projectiles/projectile/bullettypes.dm

Shotgun drop off is no longer as insain with slugs making them back to being semi-good down a range

fixes shotgun drop off

---

code/modules/projectiles/guns/projectile/shotgun/sbaw.dm

Gives the SBAW more upgrade slots
Gives SBAW more upgrade tap
Gives SBAW 1.5 ap mod
Gives SBAW 1.1 damage mod to be in line with the regulator
Reduces SBAW recoil so it can accully be used without the 7 mods

SBAW correct

---

code/modules/projectiles/guns/projectile/automatic/blackguard.dm

Blackguard now can take 4 gunslots
Blackguard has proper fire modes once more

Blackguard update

---

code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/simple_animal/simple_animal.dm

Makes AI and players controling a mob better able to controle a mob by turning on and off its ckey and other aspects

ai ckey check

---

code/game/machinery/smelter.dm
code/game/machinery/sorter.dm
code/modules/mining/machine_stacking.dm
code/modules/mining/machine_unloading.dm
code/modules/mining/satchel_material_box.dm

By R4D6
Optimiation on sorters, smelters and ore things

maybe makes stacker and unloaders less laggy

---

code/modules/genetics/mutations/cloaking.dm

Makes cloaking and greater cloaking a lot less invisable matching them to still be the most hideable but not unseeable

Cloaking balance

---

code/modules/mob/living/simple_animal/hostile/hivebot.dm

Seeker cant borrow

---

code/modules/genetics/creatures/wasonce.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Removes the blood fountain that is the wasonce dying (will be readded later in a way that doesn't break the server)
/:cl:

Bad stop breaking the server thank you

---

code/game/jobs/department.dm

The starter balances and wealth has been corrected

corrects some vars

---

code/modules/projectiles/guns/projectile/automatic/vector.dm

Vector 2 shot mode was coverted to auto

Vector balance

---

modular_sojourn/cardgame_2.dm

better card game code

---

code/modules/mining/satchel_material_box.dm

fixes materal boxes not dropping materals

hotfix - materal boxes now drop their contents

---

code/modules/mob/living/carbon/human/species/station/station.dm
code/modules/organs/organ_description.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes FBPs so markings can overlay on their hands and feet
/:cl:

Fix Robot Hands

---

code/game/objects/items/weapons/tools/hammer.dm

FIXES MASTER ONCE MORE

---

code/game/objects/random/mob/misc.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Makes seekers rarer

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm
maps/encounters/deepforest/_Deep_Forest.dmm

Massive improves preppers base to be more worth looting and such
Adds a single camera to the preimers room to cover the blind spot

preppers redone

---

code/game/mecha/equipment/tools/tools.dm
code/game/objects/items/weapons/shields.dm

Kill clamps will now harm people

makes kill clamps deal damage

---

code/modules/core_implant/cruciform/rituals/base.dm

makes installing upgrades doable

single dot

---

code/game/machinery/cryo.dm

Cryo pods no longer endlessly doup chemicals

cryo pod doup fix

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

Adds a camera to the main surface hall by the doors, to stop a blind spot
Adds a medical camera to the medical cooler room so its not a blind spot
Re-adds a grass and flower pattern that was stealth removed

Removes more blindspost

---

code/game/objects/items/devices/radio/radio.dm

fixes a issue with radio sounds

radio sound bug correction

---

code/game/objects/items/weapons/tools/mods/mod_types.dm
code/modules/projectiles/guns/mods/mods.dm

Reverts sojourn-13/sojourn-station#2359

Revert "Toolmod rebalance"

---

code/__DEFINES/damage_organs.dm
code/modules/biomatter_manipulation/bioreactor/platform.dm
code/modules/organs/body_modifications.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Makes it so Exalts are properly identified as organic.
/:cl:

Fix Exalt Surgery (And probably a hundred other things)

---

code/game/objects/items/weapons/implant/implantcase.dm

implant cases should be seeable now

implantcase fix

---

code/game/objects/items/weapons/tools/mods/mod_types.dm
code/modules/projectiles/guns/mods/mods.dm

with only 2 added bulk its still LESS then 2 pills, as seen here and still then a small item with 2
Rebalances prices for tools mods and gun mods
4 bulk
-2 bulk
Martin with -3 bulk
Martin with -30 bulk with a +30 vector

Rebalances tool mods - with added bulk, reducer bulk and more sain prices

---

modular_sojourn/cardgame_2.dm

Perhaps, maybe, possably finally fixes card holders

maybe last card fix

---

code/modules/projectiles/gun.dm
code/modules/projectiles/guns/projectile/automatic/vector.dm

Fixes folding stocks to be refoldable

Folding fix

---

maps/encounters/deepforest/_Deep_Forest.dmm

Corrects the stairs in preppers

prepper stairs fix

---

code/modules/organs/pain.dm
code/modules/reagents/reagents.dm

Ports Organ Efficiency mod functions from Eris for processing chems and sensing pain in the body.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Ports Organ Efficiency mod functions from Eris, 
Ties toxin and medicine processing to organ efficiency
Ties ability to sense pain to nerve efficiency
/:cl:

Less than Slight Organ Efficiency Ports

---

code/game/objects/random/mob/misc.dm

Seekers being a bit to common still so it should be reduced more to be more fair

reduces seekers more

---

code/game/objects/items/stacks/medical.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/head/misc_special.dm
maps/encounters/deepforest/_Deep_Forest.dmm

Fixes welding masks when sprite changed to stay changed
Fixes hopefully medical stacking items icon stats to be updating
Hopefully fixes preppers stairs... I hate stairs... they are bad

icon corrections

---

code/modules/organs/external/_external.dm
code/modules/reagents/reagents.dm

<details>
<summary>
</summary>
<hr>
Tones the improved speed from exalts way the hell down
Improves some chem equations so the consuming function runs faster
<hr>
</details>
:cl:
Tone improved speed from exalts way the heck down
Improves some chem functions so they run faster
/:cl:

Efficiency buffs

---

code/modules/projectiles/guns/projectile/pistol/clarissa.dm

Malpracts desc redone

---

code/modules/reagents/recipes.dm

All chemicals will no longer be mixable with in the microwave

Microwave blacklist

---

code/game/machinery/kitchen/microwave.dm

Fixes reagent flags being removed when moved or cleaned

microwave flag fix

---

maps/encounters/deepforest/_Deep_Forest.dmm

For real, the tots fix prepper stair fix staring CTL C CLT V form the IDENTICAL STAIRS on the river forest map

maybe fixes stairs

---

code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm

air fix for xenos

---

code/modules/mob/living/living_defense.dm

fixes mobs being on fire

---

code/modules/reagents/reagents.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixing Eris's problem for them- stims and other constant metabolism items should now drain from the body properly.
/:cl:

fixes chems

---

code/modules/hydroponics/trays/tray.dm
code/modules/mob/death.dm
code/modules/mob/living/silicon/robot/robot_upgrades.dm
code/modules/random_map/drop/drop_types.dm

Makes TK no longer work and teleport items in hydro trys
Makes Drop Pods more with buying
Maybe a borg fix
Mob tweaks

random things

---

code/modules/mob/living/carbon/superior_animal/nanobot/life.dm

Make nanobots heal toxin and oxygen damage as they apparently get those.

Make nanoboy heal tox and oxy damage

---

code/datums/mob_stats.dm
code/modules/mob/living/silicon/robot/component.dm
code/modules/mob/living/silicon/robot/robot_dogborgs.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/mob/living/silicon/robot/robot_upgrades.dm

Borgs have more mechicanl stats
Borgs now have perks, depending on their role
Borgs all have 30% more speed to make it less hard to run away form hoards of mobs

Borg rebalance

---

code/datums/outfits/jobs/medical.dm

Paramedics, Docs and CBO now properly spawn with their tablet

paramedic gear fix

---

code/datums/wires/wires.dm

Looking at wires will now tell you what they are rather then always failing

fixes wire checking

---

code/datums/craft/recipes/robot.dm

Robotic made right legs
now inline with left leg,
no longer needs a diamond drill

The robotic right leg no longer needs a diamond drill

---

code/modules/mob/living/carbon/superior_animal/vox/thrown_items.dm
code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
code/modules/mob/living/carbon/superior_animal/vox/vox.dm

the jungel birds can no longer have their spears embed
The jungel birds have less health to not be as tanky as spiders well having more then their damage range

Rebalances the birbs

---

code/game/objects/items/weapons/autolathe_disk/lonestar_disks.dm

The LSS CEO disk now has the dazzlation inside it!

Adds flare gun designs to the LSS master disk

---

maps/submaps/deepmaint_rooms/core/Lab.dmm
maps/submaps/deepmaint_rooms/core/Lab2.dmm
maps/submaps/deepmaint_rooms/core/archive.dmm
maps/submaps/deepmaint_rooms/core/core_rooms.dm
maps/submaps/deepmaint_rooms/core/diner.dmm
maps/submaps/deepmaint_rooms/core/lab5.dmm
maps/submaps/deepmaint_rooms/core/maint_asteroid.dmm
maps/submaps/deepmaint_rooms/core/medbay.dmm
maps/submaps/deepmaint_rooms/core/overrun.dmm
maps/submaps/deepmaint_rooms/core/podbay.dmm
maps/submaps/deepmaint_rooms/core/telecoms.dmm
maps/submaps/deepmaint_rooms/core/vault.dmm
maps/submaps/deepmaint_rooms/core/xenostudy.dmm

Adds liches deepmaints changes and runs the mapmerger tool so that the maps are cleaner

Simplereplacement

---

code/_onclick/item_attack.dm
code/datums/perks/job.dm
code/datums/perks/racial.dm
code/game/machinery/kitchen/gibber.dm
code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/organs/internal/nerves.dm
code/modules/reagents/metabolism.dm
code/modules/reagents/reagents/medicine.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes the detox chem so it doesn't reset the NSA of anyone with a perk modifying it.
Causes a player's NSA threshold to be improved/hurt by both nerve efficiency and damage done to those nerves, in line with what we previously thought it did. This also means that removing nerves from the body can TANK a player's NSA threshold.
Reworks the background math for NSA-modifying perks so the math is a little more convenient to track and modify.
Changed muscle efficiency in arms to affect weapon damage
Allows Punching to work properly for people with Special(tm) organs implanted, and removes a previously unknown, super niche exploit for everyone else.
Fixes Gibber and increases the amount of nutrition it has in its …

Yet more Organ efficiency changes

---

code/modules/research/nodes/biotech.dm
code/modules/research/nodes/bluespace.dm
code/modules/research/nodes/combat.dm
code/modules/research/nodes/engineering.dm
code/modules/research/nodes/greyson.dm
code/modules/research/nodes/illegal.dm
code/modules/research/nodes/power.dm
code/modules/research/nodes/robotics.dm

Almost rnd nodes are now 25% more

increases rnd costs

---

code/game/objects/items/weapons/melee/energy.dm

Makes eswords no longer act as shields with 0 slowdown flat 50% omnie proection and null attacks
Maybe makes e-dagger sprites fixed

Esword fixes

---

code/modules/reagents/reagents/race.dm

reverts rest and recover

---

code/__DEFINES/_planes+layers.dm
code/_onclick/click.dm
code/_onclick/hud/hud.dm
code/datums/datum_click_handlers.dm
code/modules/mob/login.dm

By Kegdo
Remove click catchers

ports click catcher removeal

---

code/modules/research/experiment.dm
code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm

Makes getting geo samples usefull to rnd as they now give rnd data points by scanning the paper with the sci tool

xenoarch usefulness

---

modular_sojourn/cardgame_2.dm

Clears up confusing wording in the card game
Better balances the card game
Clears up and better defines the card game rules

Better card game balance and rules

---

code/game/mecha/combat/durand.dm
code/game/mecha/combat/marauder.dm
code/modules/projectiles/guns/plasma/hydrogen.dm
code/modules/projectiles/guns/plasma/variant.dm
code/modules/projectiles/guns/plasma/welder.dm
code/modules/projectiles/projectile/hydrogen.dm
code/modules/research/designs/circuits.dm
code/modules/research/designs/mecha_equipment.dm
code/modules/research/nodes/power.dm
code/modules/research/nodes/robotics.dm

Makes hydrogen guns no longer costs osmium
Makes hydrogen guns not cost 4 arms and legs
Makes hydrogen guns deal more AP, but lowers its damage
Old Stomper now spawns with a mecha sword so it has a way to deal with basic spiders and roaches other then to taser them
Mecha swords can now be rnd'ed and printed
The tesla tower board can now be printed

misc rnd buffs and tweaks

---

code/datums/craft/recipes/guild.dm
code/modules/projectiles/guns/energy/abdicator.dm
code/modules/projectiles/guns/energy/cog.dm
sojourn-station.dme

abdicator is now easyer to craft being faster and cheaper
abdicator now has better cell charge making it last longer
abdicator now has a flare mode
abdicator is now its own gun rather then a cog

guild gun goes dazzlation

---

code/game/machinery/kitchen/slime_gibber.dm

The slime core should now spawn at the users tile rather then noware

slime gibber core fix

---

code/game/jobs/job/church.dm

Removes a eris holdover that told the prime they can clone the dead, as they cant really do that

Prime is no longer exspected to clone things

---

code/modules/projectiles/gun.dm

folding stocks now massively improves the gun making it more worth it to unfold the stock
unfolding the guns with stocks makes them even bigger

buffs folding stocks

---

modular_sojourn/cardgame_2.dm

More general cardcarp balance
Lowers wolf spawns in cards so you dont get 6 wolf cards in every pack ever

more card balancing

---

code/ATMOSPHERICS/components/unary/vent_scrubber.dm
code/ZAS/Zone.dm
code/__DEFINES/components.dm
code/controllers/subsystems/machines.dm
code/game/machinery/doors/firedoor.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
code/modules/mob/living/carbon/superior_animal/psi_monsters/life.dm
code/modules/mob/living/carbon/superior_animal/robots/robot.dm
code/modules/mob/living/carbon/superior_animal/xenomorph/life.dm
code/modules/mob/living/simple_animal/friendly/roomba.dm
code/modules/mob/living/simple_animal/friendly/spiderbot.dm
code/modules/mob/living/simple_animal/hostile/carp.dm
code/modules/mob/living/simple_animal/hostile/commanded/nanomachines.dm
code/modules/mob/living/simple_animal/hostile/excelsior.dm
code/modules/mob/living/simple_animal/hostile/hivebot.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
code/modules/mob/living/simple_animal/hostile/stranger.dm
code/modules/mob/living/simple_animal/hostile/syndicate.dm
code/modules/mob/living/simple_animal/simple_animal.dm

By MLGTASTICa
code: Optimized firedoors to no longer process
balance: Firedoors no longer give as much data about the other sides
code : Optimized scrubbers to not process
By Trilby
Massive mob opimation
Robotic, space proof humans, xenos, and other monsters that should need to breath no longer ever check for air in the first place
Fixes a controling issue with simple mobs
removes a broken mob conmand

Massive lag reduction

---

code/modules/mob/living/carbon/superior_animal/nanobot/ai.dm

Hopefully fix the Medbot Mode of the Nanobot not injecting Dermaline.

Hopefully fix the medbot injection mode.

---

code/__DEFINES/jobs.dm
code/controllers/subsystems/economy.dm
code/game/jobs/department.dm
code/game/jobs/job/captain.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/job.dm
code/game/machinery/cryopod.dm
code/modules/economy/Accounts.dm
code/modules/economy/economy_misc.dm
code/modules/modular_computers/computers/subtypes/preset_pda.dm
code/modules/modular_computers/file_system/programs/generic/taxes.dm
nano/templates/tax_app.tmpl
sojourn-station.dme

Massively redoes and improves accounts, and bugets to be more modular, more cleaner and more easyer to use in game
Adds in a tax program that works

dead and taxes

---

code/modules/mob/living/carbon/superior_animal/ai.dm

Apprently this will help against lag?

Experimental lag fix

---

code/modules/mob/living/carbon/superior_animal/ai.dm

Reverts sojourn-13/sojourn-station#2449

Revert "Experimental lag fix" - didnt work

---

code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm

removes a loop

---

code/modules/genetics/creatures/wasonce.dm

Now that oncewas will spit people out properly it, it will now properly die part too!

oncewas proper fix

---

code/game/machinery/doors/airlock.dm
code/game/machinery/flasher.dm
code/game/objects/structures/crates_lockers/closets.dm
code/modules/economy/cash_register.dm
code/modules/mob/living/silicon/ai/ai.dm

By MLGTASTICa
Fixes Engi tool interactions with
AI
Unscrewed Doors
Closets
Portal flashes, wall flashes,
Cash registers

omni tool additions

---

code/modules/genetics/creatures/wasonce.dm
code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiImpressive.dm

Makes the jelly blobs have less health and less ko'ing

Stopdoingthat #2455

---

code/modules/genetics/creatures/wasonce.dm

Slight error in removing a dquel

Oncewas now deletes

---

code/game/machinery/doors/firedoor.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes "DEBUG: Runtime in robot_modules.dm,1093: Cannot execute null.Charge(). "
Should fix "DEBUG: Runtime in firedoor.dm,384: cannot read from list"
/:cl:

fix Drone module null.Charge error

---

code/game/objects/items/weapons/storage/pouches.dm

<details>
<summary>
Reduces the cost of church/leather pouches. As of now they were REALLY fucking expensive for how easy they were to produce. they still are worth a good amount, but no more 1000 for 15 biomass.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Reduces pouch prices.

---

code/modules/food/recipes_microwave.dm
code/modules/reagents/reagent_containers/food/cubes.dm

Each roachcube has their own uniquic respice now making them all microwaveable
Roachcubes can hold more inside them to be able to inject the blood needed to grow them without removing reagents

Rochcubefixes

---

code/game/objects/items/slimeflashlight.dm
code/game/objects/items/weapons/power_cells.dm
code/game/objects/random/food.dm
code/modules/mob/living/carbon/slime/items.dm
code/modules/mob/living/carbon/slime/slime_cores.dm
code/modules/reagents/recipes/recipes_slime.dm
code/modules/research/designs/greyson.dm
code/modules/research/nodes/greyson.dm
sojourn-station.dme

Adds way more reactions to slime cores
Removes slime power cell
Fixes potato cells giving silver
Slime cores now sell for credits
Renames slime extract to slime plort
buffs slime light to be worthwile

Slime changes

---

code/controllers/subsystems/economy.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Should fix the economy wages for exalts and purge some runtimes that occur when outsiders/lodge jacks don't have records.
/:cl:

Fixing the economy

---

maps/submaps/deepmaint_rooms/core/core_rooms.dm

Makes the deepmaints fancy new deepmaints maps spawn

Makes liches maps spawn

---

code/modules/client/preference_setup/loadout/lists/headwear.dm

the numerical hat should now work in loadout

fixes numerical hat in loadouts

---

code/modules/materials/materials.dm

By Kurgis
tweak: Some materials will form regular-looking walls now.

Ports wall fix

---

code/game/objects/items/weapons/storage/wallets.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Allows wallet to hold purgers, sample plates, and injectors
/:cl:

wallet holds genetics things

---

code/modules/mob/living/carbon/slime/slime_cores.dm

Slime plorts are no longer icon broken

slime plorts no longer invisable

---

code/controllers/subsystems/economy.dm

Corrects the pay annoucement to say Nadezhda colony rather then CEV Eris

Nadezhda colony is are payers

---

code/modules/reagents/reagent_containers/food/cubes.dm

Roach cubes are now for real able to be injected with blood and shouldnt be full anymore at all times

roach cube for real fix

---

code/modules/genetics/recipes/cloning_recipes.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixed croaker lord clone recipe 
Fixed nightmare stalker cloning recipe
/:cl:

Fix croaker lord and nightmare stalker cloning recipes

---

code/modules/projectiles/guns/projectile/automatic/battlerifle.dm

Sol now will not be as bulky as the non-sawn verson

fixes sawn down sol being bulky

---

code/modules/mob/living/carbon/slime/slime.dm

Slimes now dont tank 900000 damage and then blort around

slimes now die

---

code/game/jobs/job/medical.dm

By CrystalNole
Adds in the ablity that Trama team can help access and mange the Medical departments account, to add money or use it to by spare equiment for the team, same idea that robotics have to Sci account. This helps mirror better the two departments more over as well.

TT now gets access to the department account

---

code/controllers/subsystems/economy.dm
code/game/objects/items/devices/organ_module/passive/armor.dm

Title.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Changed crew to colonist, removed dupe code.

---

code/modules/modular_computers/file_system/programs/generic/coin_miner.dm

The unused cardholder check no longer prevents being able to use the cryto miner

Coin miner no longer needs the Id holder

---

code/modules/cargo/packs_hydroponics.dm

Allows hydro trays to be buyed out of cargo

Makes hydro tray crate

---

code/modules/hydroponics/beekeeping/beehive.dm

getting 50% bees every tick was not intented shockingly

more sain bee culations

---

code/modules/modular_computers/file_system/programs/generic/coin_miner.dm

Then compressed file decompresser no longer needs the internet....

Decompressers dont need internet

---

code/game/jobs/job/church.dm

<details>
<summary>
</summary>
<hr>
Updated that prime no longer can clone people
<hr>
</details>
:cl:
tweak: Prime description no longer lies about them being able to clone people
/:cl:

Prime description updated

---

code/modules/reagents/reagents/drugs.dm

Corrects the broken paths for half the affects

fixes mage potion drinking and withdraw

---

code/modules/organs/body_modifications.dm

Makes the augmentation menu not spam the chat - By ValoTheValo
closes #1857

Makes the augmentation menu not spam the chat - By ValoTheValo

---

code/controllers/subsystems/economy.dm

The hourly pay now longer plays the command announcements things

Makes payroles not do command annouces

---

code/modules/genetics/machinery/genetics_analyzer.dm
code/modules/genetics/machinery/genetics_cloner.dm
code/modules/genetics/machinery/genetics_extractor.dm

Makes all the genetic things have their own cog/sci perk skill check to do to prevent people that built them in maints or having a medical intern press all the buttons wrong

all genetic things

---

code/game/objects/items/weapons/storage/marshal_kits.dm
code/modules/clothing/suits/armor.dm

-The firefly box now has the firefly.
-The colt box now has the colt.
-The sky pistol box now has the sky pistol.
-Updated the marshal riot suit and marshal ablative armor to actually state its status respectively.
-Riot suit box now contains the security riot hud helmet.
-Updated marshal specific armor descs and names.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Marshal Kit Fixes

---

code/game/objects/structures/crates_lockers/closets.dm
code/modules/mob/living/carbon/superior_animal/defense.dm

Locker tricks against huge mobs no longer work

fixes locker exploite

---

code/datums/craft/recipes/guild.dm

Making bulk guild crafted parts no longer magiclly takes more materals then one by one

Makes guild crafted boxes cheaper

---

code/datums/craft/step.dm

By Sieg
Fixes crafting for real

crafting fix

---

code/game/dna/genes/powers.dm
code/modules/mob/living/carbon/human/human_species.dm

-Remove the ability to turn monkies into humans. This was and always has been an exploit that was originally merged for an intended different use that people then began to misuse. People on are server cannot be cloned. Period. You get gibbed, your either a robot or gone for the round.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

No More Monkey Business

---

code/game/dna/genes/powers.dm
code/modules/mob/living/carbon/human/human_species.dm

Reverts sojourn-13/sojourn-station#2521 but also fixes it

Yes More Monkey Business

---

code/game/machinery/vendor/misc_vendors.dm

Game Stop turns out is a real store

Less memey name

---

maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

Makes the marshals holding cells a bit more spacey to play their card games and have better time talking to people inside
massively improves WO office to be compact and adorables
adds more decals and fire lockers to marshals
fixes a singular bad wall in the firing range
moves a sci poster to a more themadic place

improves sec a bit

---

code/modules/genetics/machinery/genetics_analyzer.dm
code/modules/genetics/machinery/genetics_cloner.dm
code/modules/genetics/machinery/genetics_extractor.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Xeno Genetics machines now sass people who try to use it with low Cog
/:cl:

Improve genetics sass

---

modular_sojourn/cardgame_2.dm

more cardcarp balance

---

code/game/objects/items/weapons/storage/marshal_kits.dm

I wanted the Ladon not the Porton

gives ladon pistol box the ladon

---

code/modules/projectiles/gun.dm

Perfect one handed aim no longer nulls normal recoil

fixes Krosin perk one hand shooting

---

code/modules/mob/living/recoil.dm

This is a good change.
By Humonitarian
balance: recoil now decreases progressively, instead of all at once

Recoil cooldown change By Humonitarian

---

code/modules/mob/living/silicon/silicon.dm

fix: robots being able to rest

Fixes robo resting by  - SirRichardFrancis

---

code/__DEFINES/economy.dm
code/controllers/subsystems/economy.dm
code/game/jobs/department.dm
code/game/machinery/cryopod.dm
code/modules/economy/Accounts.dm
code/modules/economy/economy_misc.dm
code/modules/modular_computers/file_system/program.dm
code/modules/modular_computers/file_system/programs/generic/taxes.dm

Fixes external department funding
Better ecomic code in general

Fix external department funding - by SirRichardFrancis

---

code/game/objects/items/weapons/storage/blackshield_kits.dm
code/modules/clothing/suits/storage.dm
code/modules/projectiles/gun.dm

-Added a missing parenthesis in storage.dm and gun.dm
-The pilgrim kit now contains the pilgrim instead of the mistral.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Fixes Main and BS Kit

---

code/modules/projectiles/projectile.dm

balance: projectiles pass trough stairs

Projectiles passing trough stairs -  by SirRichardFrancis

---

code/datums/perks/nanogate.dm

Adds basic anticheating to nanogate checks

basic anticheating

---

code/modules/genetics/creatures/wasonce.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Slows down the movement of the wasonce so it has trouble chasing people down.
/:cl:

Slow wasonce way down

---

code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiImpressive.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Changes children of the was once to go to sleep way earlier than their parent- because unlike their miniboss of a father, they don't need to be awake constantly.
/:cl:

Wasonce Children Go tf to sleep

---

code/modules/genetics/genetics.dm
code/modules/genetics/machinery/genetics_designs.dm
code/modules/genetics/machinery/genetics_items.dm
code/modules/research/nodes/biotech.dm
maps/CEVEris/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Adds the Small Mutagenic Scanner as items to the R&D console, Xenogenetics disks, and to the Xenogenetics lab.
/:cl:

Implement the Small Mutagenic Scanner

---

code/modules/reagents/reagent_containers/borghydro.dm

:cl:
fix: Wahhhhhh, fixes reagent container issue because list()
/:cl:

waaaaaaaahhh

---

code/game/objects/effects/decals/Cleanable/misc.dm

Hopefully a less over round lag

exspermental lag reduction

---

code/ATMOSPHERICS/components/unary/vent_scrubber.dm
code/game/machinery/alarm.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Makes it so scrubbers only start doing scrubbing when they need to, and not passively for no reason. Should reduce lag.
/:cl:

Lagfix: Scrubbers only turn on in emergencies

---

code/modules/power/hydrogen_generator.dm

hydrogen generator mat doup fix

---

code/modules/mob/living/silicon/robot/robot_dogborgs.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

Borgs shouldnt have things that are major contraband just on them at all.

no more illegal illegals

---

code/modules/trade/datums/trade_stations_presets/cybernetics.dm

Removes bugged trade ship

---

code/modules/surgery/surgery.dm

Self surgery is much harder now
Selfsurgery now takes longer as your doing it on yourself, hope those painkillers last...

self surgery nerfs

---

code/modules/projectiles/guns/projectile/shotgun/swat.dm

push commits darn it!!!

---

code/game/turfs/initialization/maintenance.dm

Makes mice and oil spawn less in large sections of the map to help aganst lag

slightly less laggy maints

---

code/modules/admin/tickets/adminticketsverbs.dm
code/modules/admin/view_variables/topic.dm
code/modules/admin/view_variables/view_variables.dm

Accully makes it so devs can view tickets
and do things

sieze power properly

---

code/controllers/subsystems/tickets/mentor_tickets.dm
code/controllers/subsystems/tickets/tickets.dm
code/modules/admin/admin.dm
code/modules/admin/topic.dm
code/modules/admin/verbs/adminpm.dm
code/modules/admin/verbs/modifyvariables.dm

for real lets devs edit and handle dev related ahelps/issues

Propper permission medaling

---

code/game/objects/items/weapons/tools/mods/mod_types.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/projectile/shotgun/swat.dm

Allows more aspects of tool mods to applie to guns
Fixes a small refresh bug on scopes
Fixes prefixes for guns (maybe)

stock fix and power creep

---

code/game/objects/random/mob/roach.dm
code/modules/mob/living/carbon/superior_animal/roach/life.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Removes the Obese Kampfer Roach from regular random mob spawns, to see if it has an appreciable effect on server speed
/:cl:

Lagfix: Remove roach chonkers

---

code/modules/projectiles/guns/projectile/shotgun/swat.dm

SWAT ammo loading fix
SWAT changing fire mods every alt fire fix

guns r dumb

---

code/controllers/subsystems/trade.dm
code/modules/materials/material_sheets.dm
code/modules/modular_computers/file_system/programs/generic/trade.dm
code/modules/reagents/reagent_containers/hypospray.dm
code/modules/trade/datums/_trade_station.dm
code/modules/trade/datums/trade_stations_presets/KriosanConfederacy.dm
code/modules/trade/datums/trade_stations_presets/McRonalds.dm
code/modules/trade/datums/trade_stations_presets/asterstradecapital.dm
code/modules/trade/datums/trade_stations_presets/bluespace_tech.dm
code/modules/trade/datums/trade_stations_presets/boozefood.dm
code/modules/trade/datums/trade_stations_presets/caduceus.dm
code/modules/trade/datums/trade_stations_presets/cybernetics.dm
code/modules/trade/datums/trade_stations_presets/fs_weapon_factory.dm
code/modules/trade/datums/trade_stations_presets/hellcat.dm
code/modules/trade/datums/trade_stations_presets/material_refine.dm
code/modules/trade/datums/trade_stations_presets/mecha.dm
code/modules/trade/datums/trade_stations_presets/nt_cruisers.dm
code/modules/trade/datums/trade_stations_presets/suit_up.dm
code/modules/trade/datums/trade_stations_presets/trash_refine.dm
code/modules/trade/datums/trade_stations_presets/zarya.dm
nano/templates/trade.tmpl

By Pink-Chink
code: added new functionality for trade stations, trade subsystem, and trade program to allow multiple offers per station, secret inventories, a reputation-like system for unlocking secret inventories, and stock replenishment
add: secret inventories and offers to the starting traders and Dionis
add: hypospray and full material sheet stack presets
tweak: adjusted some station inventories for balance and to minimize overlap
tweak: trade station grammar and style changes

ports and tweaks

---

code/modules/projectiles/guns/projectile/automatic/c20r.dm

Makes the trama team SMG mag be real

pathing issue fix

---

code/game/objects/random/guns.dm

Makes amazing guns spawns less chaingun heavy and have more amazing guns

Makes rare guns less same-y

---

code/modules/projectiles/guns/projectile/automatic/c20r.dm

adds the single line to make c20r have its ui

C20r preload fix

---

code/modules/core_implant/cruciform/rituals/construction.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
spellcheck: fixed Speed of the chosen Upgrade typo
/:cl:

Fixed typo in Speed of the chosen Upgrade

---

code/game/objects/items/weapons/shields.dm

Esheilds are good at blocking melee, and smaller caliber bullets are lasers, not heavy modded out 120 damage ones

Eshield rebalance

---

code/modules/organs/internal/nanogate.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
fix: Fixes so many bugs and quirks with nanogates in dead people/etc and makes them empable.
/:cl:

[BIG FIXERONI] Nanogates are now actual synthetic parts

---

code/modules/psionics/psionic_items/psi_armor.dm

Mage helmet no longer clips through mulitable items

Mage helmet no longer clips through mulitable items

---

code/game/objects/items/weapons/storage/storage.dm
code/modules/hydroponics/trays/tray.dm
code/modules/mining/mine_turfs.dm
code/modules/projectiles/guns/energy/egun.dm
code/modules/projectiles/guns/energy/sst.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes produce bags (and most other bulk item bags) from generating huge amounts of messages in chat when piles of items are picked up.
Improves the text for putting things in bags to be more grammatically correct.
Fixes runtime with preloaded martins & SST's.
/:cl:

Produce bag fix And Martin fix

---

code/game/objects/items/devices/defib.dm
code/modules/projectiles/ammunition/bullets.dm
code/modules/projectiles/ammunition/magazines.dm

fixes cbo gun to shoot
defibs now should spawn updated icons

fixes cbo gun and icon for defibs

---

code/modules/materials/material_sheets.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Changed material stacks with non-integer amounts to instead generate shrapnel containing the remainder upon creation. This should keep players from abusing the "Infinite decimal ingot" exploit.
/:cl:

Fractions of material stacks produce shrapnel

---

code/modules/mob/living/simple_animal/hostile/dino.dm
code/modules/projectiles/gun.dm
maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Repairs main to work
adds the propis pets to be the correct one

fixes master and babyrender

---

code/__DEFINES/mobs.dm

Nerfs bleeding

---

code/game/objects/items/weapons/storage/vendor_loot_boxes.dm

Rewords the boxes to not be fraud
Makes propis oddity boxes always has their oddites

fixes propis loot boxes

---

code/modules/mob/living/silicon/ai/latejoin.dm

Make the wipe core option for AIs much easyer to fine

Make the wipe core option for AIs much easyer to fine

---

code/modules/projectiles/guns/projectile/boltgun/flaregun.dm

Unrelated to Lonestar's actions, a flaregun that use less than 6 steel & plastic to make shouldn't be worth the same amount of money as a Kardashev-Mosin Boltgun.
- Reduce the Flaregun's price from 500 to 30.

Make the flaregun worth a lot cheaper.

---

code/game/objects/random/mob/misc.dm

New type of cluster xenomorph spawner without some types to add more constancty to your pain

Xenomorph saver spawners

---

code/game/machinery/autolathe/fabricators.dm

adds the pan mag and 40 magnum smg mags to the guilds ammo printer.

added missing ammo from ammo printer

---

code/game/jobs/job/medical.dm

Swaps docs to have access to the medical account rather then TT

Makes doctors have access to account then TT

---

code/game/objects/items/weapons/tools/hammer.dm

fixes deadblow hammers sprite

---

code/game/objects/items/weapons/storage/blackshield_kits.dm
code/game/objects/items/weapons/vouchers.dm

name and voucher fix

---

code/game/jobs/job/science.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
add: Added geneticist alt-title to scientist
/:cl:

Added geneticist alt title to scientist

---

code/game/objects/items/weapons/grenades/frag.dm
code/modules/projectiles/projectile/fragment.dm

Stinger are rebalance to not be as good by 7 pain to reduce spaming them to auto win any battle better then legitement frag nades
Also has less fragments to stack damage on everything around in an area.

makes stringer less lethal

---

code/__DEFINES/jobs.dm

Makes the foreman count as command

---

modular_sojourn/cardgame_2.dm

correts adders being goats
bull frog turn one win is removed

Card carp corrections

---

code/modules/mob/living/silicon/robot/gripper.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

Fixes dog borgs names not being accurate to how they are
Fixes some gripper issues

Fixes some borg issues

---

code/modules/clothing/head/jobs.dm
code/modules/clothing/suits/armor.dm

Fixes selecting the old alts of guns

Fixes some alt armors

---

nano/templates/clothing_stats.tmpl

This pr tots will not break anything
Makes both stiffness and obscuration viewable

Ruins everything again

---

code/modules/projectiles/guns/matter/launcher/books.dm

harmony_scepter icon fix

---

code/game/objects/items/weapons/storage/fancy.dm

candle boxes cant hold things other then candles as that brakes things

candle fix

---

code/modules/reagents/recipes/recipes.dm
code/modules/research/experiment.dm

Toxins scanners now has a limited poll of points it draws form before running out.
Also reduces nitro bomb mixes to be less crazy good, still can get max caps with effort and good gear tho

Toxin rebalance

---

code/modules/projectiles/projectile/beams.dm

Harmony staff and other book gun spells no longer blind people

Healing staff and books dont blind people anymore

---

code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/modules/nanogate/nanogate.dm
code/modules/projectiles/gun_hud_actions.dm
maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes misc random runtimes and errors by Sieg

misc fixes sieg came up with to fix

---

nano/templates/clothing_stats.tmpl

Fixes clothing

---

code/datums/outfits/jobs/science.dm

The CRO now spawns with the robotics tool belt as they are exspected to aid or do robotics

CRO now gets robotics tool belt

---

code/modules/clothing/glasses/misc.dm

ballistic goggles tweaks

---

code/game/mecha/mecha.dm

Allows you to over-ride the mech DNA lock with a very hard MEC skill that takes very long.
tested. it works.

Allows you to over-ride the mech DNA lock with a very hard MEC skill

---

code/game/objects/structures/low_wall.dm

Church low wall icon accully use the icon we want

---

code/game/objects/random/mob/misc.dm

Fixes the screacher remove cluster to not have screachers.

cluster spawner fix

---

code/modules/mob/living/recoil.dm

Removes some maths done in recoil

Small backend maths reduction

---

code/modules/research/experiment.dm

Bomb scanner no longer lies about its points

propper callout

---

code/modules/clothing/suits/storage.dm

Fixes storing accessory in suit storage slots

suit storage accessory bug remove

---

code/__DEFINES/research.dm
code/modules/integrated_electronics/core/debugger.dm
code/modules/integrated_electronics/passive/power.dm
code/modules/integrated_electronics/subtpes/manipulation.dm

integrated electronics no longer gives endless materals

removes metal doups

---

interface/skin.dmf

Corrected location of hotkeys

---

code/modules/mob/living/living.dm

Fixes more issues with dashing well cuffed, to hurt, lying down, and buckled

Sanity to wavedashing

---

modular_sojourn/cardgame_2.dm

Adds a cardcarp deck that draws randomly cards and pelts

endless cards

---

code/modules/reagents/machinery/chem_dispenser.dm
code/modules/reagents/machinery/chem_master.dm

Cleans up some hacking code in chem dispenders
Adds the same bio check as the chem master to chem dispenders

chemdispender cleaning and and stat requirements

---

code/modules/client/preference_setup/loadout/lists/xenowear.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Fix opifix mask not appearing on xenowear

---

code/datums/craft/recipes/robot.dm

Hand made drones when made by robotics or CRO costs less materals, as currently to make it takes well over 50 plasteel.

Lowers drone costs

---

code/modules/trade/datums/_trade_station.dm
code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm

By - Pink
Reduces proc calls for the unused overmap
Fixes a runtime

mico-optimation - Trade ships

---

code/datums/perks/nanogate.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes the nanite ammo perk
/:cl:

Fix nanite ammo

---

code/game/atoms.dm
dependencies.sh

Corrects being able to see chemicals in beakers without silly high stats

Fixes viewing chemicals + Dependency update

---

code/__DEFINES/lighting.dm
code/__HELPERS/game.dm
code/__HELPERS/unsorted.dm
code/datums/perks/oddity.dm
code/game/atoms.dm
code/modules/modular_computers/computers/modular_computer/core.dm
code/modules/modular_computers/computers/modular_computer/power.dm
code/modules/modular_computers/file_system/program_events.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes bug causing visible_message to break.
Also should fix Bluespace Alinement perk
/:cl:

Fix visible_message function

---

modular_sojourn/cardgame_2.dm

-Fixes the sprite and an issue with rat cards returning to their fodder deck.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Card carp fixes

---

code/game/jobs/job/assistant.dm
code/game/jobs/job/civilian.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/prospector.dm
code/game/jobs/job/science.dm
code/game/jobs/job/security.dm

Add new alt-titles to several jobs:
I only need feeback for blackshield and Marshal alt-titles:
Troopers: Blackshield Technician
Corpsmen: Trainee Corpsman, Blackshield Medical Specialist , Combat Surgeon
Ranger: Detective , Marshal Agent

New Alt-Titles[Need Feedback] 

---

code/game/machinery/vendor/misc_vendors.dm
code/game/objects/items/weapons/storage/hardcases.dm
modular_sojourn/cardgame_2.dm

Cardcarp now has a index card to show the card affects, so you dont need to clog your chat log with rules AND the effects
Cleans up and improves harcase actions

harcase fix and index card

---

code/game/objects/items/weapons/implant/implants/tracking.dm
code/modules/client/preference_setup/loadout/lists/general.dm

-Added an implanter and tracking implant as a general item for 1 point to load out.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Tracking implants

---

maps/submaps/dungeon_rooms/rooms/corner_energy_SE.dmm
maps/submaps/dungeon_rooms/rooms/droppod.dmm
maps/submaps/dungeon_rooms/rooms/room_templates.dm
maps/submaps/dungeon_rooms/rooms/shootingrange.dmm
maps/submaps/dungeon_rooms/rooms/surgery.dmm

Grayson gaultnet tweaks to have slightly better generation to be less same-y again
fixes some rooms bad spawns in rooms

more grayson tweaks

---

code/modules/maps/tg/reader.dm

Shadow-Quill SpaceManiac
Fixes a reader for maps so CI flows dosnt flip out randomly on none issues

Attempt to fix reader.dm CI fails

---

code/game/world.dm
code/modules/admin/admin.dm
code/modules/nanogate/nanogate_powers.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes Genetics recipes so they work again
Fixes Admin tickets so they work again
Fixes Nanogate Antenna so it can send an email to anyone.
/:cl:

List of Fixes

---

code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
sojourn-station.dme

New Grayson shuttle that only sells their cloathing, its not that good and wants their disks back
Medical ship caduceus can now when second inventory will want advanced surgery tools
Rebalances some bounties

New cargo trade beacon, and better balace

---

code/game/turfs/simulated/wall_types.dm

Church walls now properly have plasteel and steel rather then just steel and steel.

church wall correct

---

code/datums/craft/recipes/misc.dm
code/game/supplyshuttle.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm

By Alliostra
add: plastic flaps are now craftable and disassemblabe
By Trilby
Plastic flaps will now be destoryable so using them as a shield isnt viable

Plastic flaps crafting and destuction

---

code/controllers/subsystems/atoms.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
SHOULD (Potentially) (Probably) Fix the scrap beacon and all other LateInitialize-dependant processes from snapping like a twig.
/:cl:

Should fix the scrap beacon

---

code/game/objects/items/oddities_faction.dm
code/game/objects/items/weapons/storage/hardcases.dm
code/modules/projectiles/guns/matter/launcher/books.dm

-Fixed some typos and added better wording to the joyeuse sheath and harmony sceptor
-Fixed an issue with the game hard case. An incorrect var made it not carry as much but it should hold x3 the items it formerly could. (Still can only hold card game items.)
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Hardcase fix and typos

---

code/__DEFINES/chemistry.dm
code/__DEFINES/perks.dm
code/datums/perks/oddity.dm
code/datums/perks/racial.dm
code/datums/setup_option/backgrounds/origin_homeworld.dm
code/game/machinery/vendor/food_vendors.dm
code/modules/mob/living/carbon/human/species/station/station.dm
code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm
code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
code/modules/reagents/reagent_containers/food/snacks.dm
code/modules/reagents/reagents/food-Drinks.dm
code/modules/reagents/reagents/toxins.dm

-Carnivores are no longer a reagent tag and now use a perk system so players know they are carnivores.
-Herbivore added as a reagent perk.
-New oddity perk called snackivore added.
-Fixed an issue with nanobots and handmade bots being capable of processing reagents and taking toxins, they should now have immunity.
-All snack foods (chips, bread tubes, etc. etc.) now contain a new chemical reagent called preservatives and have severely reduced nutrition value. Preservatives provide a minuscule amount of nutrition (value 1 compared to nutriment value 5).
-Sablekyne now have the carnivore perk.
-The neapolis background now gives you the herbivore perk. Sablekyne can no longer take the neapolis background.
-All foods are now slightly less filling to encourage more interaction with the …

Modular reagent feedback and robot fixes

---

code/datums/setup_option/backgrounds/origin_homeworld.dm

-Neapolis now gives +5 Cog and Bio and -5 Rob.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Neapolis Change

---

code/modules/mob/living/living_defense.dm

Fixes math for bullets overpen and laser overpen so they are no longer inversed

maths fix by Minion Of The Void

---

code/datums/perks/job.dm
code/datums/setup_option/backgrounds/origin_upbringing.dm
code/modules/mob/living/damage_procs.dm
code/modules/multiz/turf.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Raider's Leap and Cyberpunk origin changes

---

code/game/objects/items/weapons/tools/mods/armor_mods.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm
code/modules/projectiles/guns/mods/mods.dm
sojourn-station.dme

Fixes bad tool mods having bad names
Moves armor mods to their own file
moves wax tool mod to the proper location as well

name fixes and armor to its own mods

---

maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Blackshield armory no longer has their medical gear

remoal of blackshield medical gear

---

code/datums/outfits/jobs/medical.dm
code/game/objects/items/weapons/storage/firstaid.dm
code/game/objects/items/weapons/storage/hardcases.dm

Church kit now has the proper amount of kits inside(woops)
Blackshield massive trama kit no longer has 2 spare kits
Medical now gets a shift start hardcase with their normal medical gear inside + large advanced kits to help with loadout storage

Medical hcases for medcal and hotfix for church kit

---

maps/DeepForest/map/_Deep_Forest.dmm

Adds a small hut in the woods for card games and small admeme events to connect to

Small house in the woods

---

code/datums/objective/individual_objective/common.dm
code/game/machinery/tesla_turret.dm
code/game/objects/items/weapons/circuitboards/machinery/tesla_turret.dm
code/game/objects/items/weapons/storage/hardcases.dm

Removes the commonly wrongly targetting obsessived objective
Makes  a hardcases that spawn with items not exspand its storage hopefully
Fixes master

masterfix remoes obsessive and hardcase fix

---

code/controllers/subsystems/chat.dm
code/datums/perks/job.dm
code/game/dna/genes/powers.dm
code/game/machinery/telecomms/broadcaster.dm
code/modules/maps/swapmaps.dm
sojourn-station.dme

Just cleans up some bad code, no game affects

fixes some easy linter errors

---

code/datums/outfits/jobs/civilian.dm
code/datums/outfits/jobs/command.dm
code/datums/outfits/jobs/engineering.dm
code/datums/outfits/jobs/medical.dm
code/datums/outfits/jobs/security.dm
code/game/objects/items/weapons/storage/hardcases.dm
code/game/objects/items/weapons/storage/storage.dm

Marshals Blackshield Medical Artest and Command roles that commonly get overfilled with starting items + loadout all now get hardcases with their gear inside to help prevent bugs form happening
Guild now starts with a hazard vest and their breaker gun equiped on it

Condences!

---

code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm
code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm

-Fixed a wide variety of Renglish in the trade beacons.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Trade beacon Renglish fixes

---

code/modules/hydroponics/seed.dm
code/modules/hydroponics/seed_datums.dm
code/modules/hydroponics/trays/tray.dm

Enables killer tomatoes, and causes self harvesting plants to properly self harvest.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Killer Tomatoes

---

code/game/machinery/deployable.dm
code/game/objects/structures/girders.dm
code/game/objects/structures/grille.dm
code/game/objects/structures/low_wall.dm
modular_sojourn/shields.dm

Low walls maybe now accully blocks bullets
Grills, Bastions and deployable barriers can now brace guns

some more bracing

---

code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm
code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
code/modules/mob/living/carbon/superior_animal/robots/robot.dm

Make robots superior mobs immune to heat & cold. This mean Greyson Robots, Handmade Robots & Nanobots.

Make robots superior mobs immune to heat & cold

---

code/modules/nanogate/powers/user.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Slight nanogate nerf

---

code/controllers/subsystems/migration.dm
code/game/objects/effects/spawners/maintshroom.dm
code/game/objects/random/flora.dm
code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
code/modules/core_implant/cruciform/machinery/obelisk.dm
code/modules/core_implant/cruciform/machinery/wall_obelisk.dm
code/modules/core_implant/cruciform/upgrades.dm
code/modules/hydroponics/grown.dm
code/modules/hydroponics/seed_datums.dm
code/modules/hydroponics/seed_packets.dm
code/modules/hydroponics/spreading/spacevines.dm
code/modules/hydroponics/spreading/spreading.dm
code/modules/hydroponics/spreading/spreading_growth.dm
code/modules/hydroponics/spreading/spreading_response.dm
code/modules/hydroponics/trays/tray.dm

Reverts sojourn-13/sojourn-station#2798
Pretty sure this caused the server to hit defcon 3 and crashed the mc. Gonna revert it and have it looked over more carefully.

Revert "Plant Tweaking"

---

code/game/machinery/autodoc.dm
code/game/objects/items/weapons/circuitboards/machinery/medical.dm
code/modules/reagents/reagent_containers/food/cans.dm
code/modules/research/designs/circuits.dm
code/modules/research/nodes/biotech.dm

Fixes church canned wine to have wine in it
Adds in the missing autodoc board to rnd.

docs and wine

---

code/game/objects/items/stacks/medical.dm
code/modules/surgery/robotic.dm
code/modules/surgery/surgery.dm

Fixes robotics surgery being counted as had if not harder then normal surgery
Fixes ATK kits

More ATK/Surgery fixes

---

code/modules/reagents/reagents/medicine.dm

Title.
I don't know why in the everloving _**fuck**_ the Ossisine healing fracture effect was put in the _regular_ processing proc when there is a _**perfectly usable**_ OD processing proc **right below it** !

Move the Ossisine OD effect to its OD proc.

---

code/game/objects/items/weapons/storage/firstaid.dm
maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Removes scavs golden cup
Gives blackshield their winnings

Colony game rewards

---

code/game/jobs/job/security.dm
code/game/machinery/vendor/weapon_kit_vendors.dm
code/game/objects/items/weapons/storage/hardcases.dm
code/game/objects/items/weapons/storage/marshal_kits.dm
code/game/objects/items/weapons/storage/pouches.dm
code/game/objects/items/weapons/vouchers.dm
code/modules/client/preference_setup/loadout/lists/utility.dm
code/modules/clothing/accessories/accessory.dm
code/modules/projectiles/projectile/bullettypes.dm

<details>
<summary>
<br>Gives sergeant account access
Fixes an incorrect path in the kneepads accessory. whoops!
made folders, clipboards and CorpRegs free in the loadout.
Marshal loadout changes. "Main" weapons now come with 2/1 lethal to LTL ammo, sidearms come 1/2 lethal to LTL.
Whirbelwind placed into the sidearm category where it belongs, in its place is the Thompson SMG.
Specialist+Ranger get main-arm vouchers now. Similarly to how Sergeant, Specs voucher includes special options not available to regular officers, Rangers get a standard.(They both retain their 'standard' sidearm in the locker.)
Pistol holster buffed, now fits; Aedes, Galaxy, Sky, Straylight, and ladon pistols. DM me if i'm missing any obvious pistols that need to be added.
Adjusts some of the ammo damage/pen values …

Marshal loadout changes, some fixes - Its a omni pr

---

code/game/objects/items/stacks/medical.dm
code/game/objects/items/stacks/rods.dm
code/game/objects/items/stacks/stack.dm
code/modules/reagents/reagent_containers/hypospray.dm

Fixes some rods not stacking
Fixes large advanced kits not stacking with one a other
Fixes a bug were transferring 5 kits between advanced kits deletes it
Fixes some bad wording on hypo injecting
Lowers resisting time form harm intent of hypo's
Fixes some messages with injecting a hypo

medical misc fixes

---

maps/DeepForest/map/_Deep_Forest.dmm
maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Garden windows are now correctly R-windows
Adds a prybar to garden
Adds impassable rock to an admin area
Adds a photocopyer and shreader to CRO office

Small tweaks

---

code/__DEFINES/perks.dm
code/modules/reagents/reagent_containers/syringes.dm

Chem Addicts now can use syringes regardless of Bio stat.

Crack Addicts and their Crack

---

code/modules/genetics/machinery/genetics_analyzer.dm
code/modules/genetics/machinery/genetics_cloner.dm
code/modules/genetics/machinery/genetics_extractor.dm

Genetics failer messages are now Hex proper messages
Genetics now has advanced medical perk bypass so doctors can play around inside as well - READ SOP
Genetics have more checks to prevent some crafty peoples bypasses of checks 🖌️

Makes genetics accully locked and give correct messages

---

code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/_defines.dm
code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/vendor.dm
sojourn-station.dme

Add a vendor that sells kits that are used to make the build-a-drone drones.
The vendor isn't mapped in yet.
Could probably use a better description by @Kazkin

Build-a-Drone part 3

---

code/modules/core_implant/cruciform/rituals/path.dm

-Food for the masses should now work properly.
-Lowered the nutri cost of some litanies.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Food for the Masses

---

code/modules/core_implant/cruciform/rituals/path.dm

-Reduced the time to 10 minutes.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Bulwark buff

---

code/modules/core_implant/cruciform/rituals/path.dm

-Further increases the slow down to 500%, up from 300%
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Bulwark nerf

---

code/modules/mob/living/silicon/robot/gripper.dm

Allow Chemistry and Scientific Grippers to take blood bags

Allow Chemistry and Scientific Grippers to take blood bags

---

code/__DEFINES/misc.dm
code/modules/client/client_procs.dm
code/modules/client/preference_setup/global/01_ui.dm

Emergency PR. Possum will be pinged when I need it merged.
>Be Trilby
>Remove feature that got approved by Possum because "I believe its a balance issue"
>Do so silently, and in a "1:1" port with Eris
>Do it badly
>Get caught
>Say this in OOC
Please remove Trilby's ability to merge content.

I HATE TRILBY

---

code/game/objects/items/devices/defib.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
Defibs should no longer runtime.

Fixing Defibs

---

code/modules/reagents/recipes/recipes.dm

<details>
<summary>
I typoed and broke-ed it ):
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Reaction now works for steralizer-stuff.
/:cl:

Fixed New Chem Reaction

---

code/modules/modular_computers/file_system/programs/research/passive_pointes.dm

RnD's Point Miner Program Change : 
- Add ping sound when finished.
- Also correctly fetch the cog level of the operator upon the start of the mining..
- Add a framework to allow for future support of more points per run.

Smol Update to RnD's point miner

---

code/__DEFINES/is_helpers.dm
code/game/objects/effects/chem/water.dm
code/modules/genetics/genetics.dm
code/modules/genetics/machinery/genetics_items.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Spray effects now leave residue on containers that can hold them
Improved performance on spray effects
Changed genetics so they cannot be applied to synthetic simplemobs
Added the 'issynthetic()' helper to better identify synthetic mobs of all shapes and sizes.
/:cl:

Spray bottles and Robot genes

---

code/datums/perks/job.dm
code/modules/reagents/reagents/medicine.dm
code/modules/reagents/recipes/recipes.dm

<details>
<summary>
Latin wasn't apperantly fixed in the last PR, guess my changes didn't save. Sterilizer was fixed buuuut apparently we just don't have Cronexidone's ID as Cronexidone. So, fixed now.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Final needed fix to Linguist. All work on testing now.
fixes: Sterilizer now mixes properly. Fuck you Cronexidone being called 'Clonexidone' in ID.
/:cl:

Latin Linguist Fix - Sterilizer Fix

---

code/datums/outfits/jobs/ghostroles.dm
code/game/objects/effects/spawners/ghostroles.dm

Fixes medical ERT
Coras requested doggo sleeper spawn

Ghost doggo

---

code/modules/mob/living/carbon/human/human.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes titles from announcing to everyone when they are toggled.
/:cl:

title Toggle fix

---

code/modules/mob/living/simple_animal/friendly/corgi.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm

Fix a runtime with the chicken.

Fix a runtime

---

code/modules/mining/drilling/wurm_wave.dm

<details>
<summary>
Makes it so the numbers are actually x5 original and 2x spawn interval 
</summary>
<hr>
<hr>
</details>
tweak: numbers are now accurate to the description of the previous change
:cl:
/:cl:

quick fix for my wurm spawn increas

---

code/modules/mob/living/carbon/superior_animal/defense.dm

<details>
<summary>
Master Butcher perk now allows full leather, meat, and bone amounts when butchering. Butchering now gives anyone half the defined amount of leather and bone in addition to the normal half amount of meat.
</summary>
<hr>
<hr>
</details>
:cl:
balance: Players with Master Butcher will now get the full meat, leather, and bone values defined in the animal's vars when butchering an animal, in addition to special parts
add: Players without Master Butcher will now get half of the leather and bone amounts for the animal when butchering, but still get no special parts
/:cl:

Master butcher butchers better

---

code/game/machinery/biogenerator.dm
code/modules/mob/living/carbon/superior_animal/lodge/types/clucker.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm

<details>
<summary>
Makes poultry much more accessible to both Garden and Lodge, gives them one more means of acquiring Diethylamine (more expensive than Robust Harvest), tweaks the biogen cost of salt and pepper to be in line with sugar, and slashes the kind of ridiculous egg box biogen cost from 6400 to a more reasonable but still steep 3200.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Reduces biogen price of salt and pepper to match sugar
add: adds diethylamine to the biogen for cost of 150 (twice the cost of Robust Harvest)
tweak: Increases hatchable egg chance for normal chickens to 1 in 4, to make poultry more accessible to the kitchen
tweak: Increases the max number of eggs per feeding a clucker may lay to match the chicken, and how many eggs it can accumulate before not being …

Livestock and Biogen QoL changes

---

code/game/objects/items/devices/radio/radio.dm
code/modules/genetics/genetics.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Should remove the headset frequency runtime report more about how the core error is occurring in the process.
/:cl:

Radio Frequency patch fix with error logging

---

code/modules/modular_computers/computers/subtypes/preset_tablet.dm
code/modules/modular_computers/file_system/catalog.dm
code/modules/modular_computers/file_system/programs/medical/debug_catalog.dm
code/modules/reagents/recipes.dm
code/modules/reagents/recipes/recipes.dm
nano/templates/catalog_entry_reagent.tmpl
nano/templates/catalog_list_general.tmpl
sojourn-station.dme

You can now in the SIRC see what chemicals block a reaction
Unused but still added, you can now see byproducts
Fixes the debug chatalog

The longest qol projects that failed

---

code/modules/mob/living/carbon/superior_animal/lodge/types/clucker.dm

Reverts sojourn-13/sojourn-station#2895

Revert "Bugfix for clucker eggs"

---

code/modules/mob/living/carbon/superior_animal/lodge/types/clucker.dm

Limits the heavily intents cluckers to 10, sorry hunters

better cluck sanity

---

maps/DeepForest/map/_Prepper_Bunker.dmm
maps/HunterLodge/map/_Hunting_Lodge.dmm
maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Hunters as per the event now get an industeral grinder
Fixes a button in medical lobby

hunters quest + fix

---

code/game/jobs/job/science.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Added Soteria to Geneticist title

---

maps/_DeepForest/map/_River_Forest.dmm

Fixes some REALLY unfun and unfair landmines in the river forest to be less impossable to see
Adds metal and wood to the pit fall trap to help people to be able to get out and less of a soft lock

Landminebad

---

code/game/objects/items/devices/radio/encryptionkey.dm
code/modules/clothing/chameleon.dm
code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm

Artest revolver no longer can be shunted of all its stats
Chameleon outfit 4 no longer bricks half your gear

Artest fix and chameleon

---

code/modules/core_implant/cruciform/rituals/construction.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/bishop.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/knight.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/pawn.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/rook.dm

-Updated descriptions.
-Added build recipe for knight golems.
-Did some rebalancing.

Golem Stuff

---

code/controllers/communications.dm
code/game/objects/items/devices/radio/headset.dm
code/game/objects/items/devices/radio/radio.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Changed the default engineering frequency so integrated circuits did not interfere with them.
Further tweaks the headset so the channels are recalculated more frequently when changes occur.
/:cl:

Headsets fixed forever (Potentially)

---

code/modules/power/antimatter/control.dm

Allow the antimatter console to have custom explosion strength

Allow the antimatter console to have custom explosion strength

---

code/modules/sanity/inspiration_component.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes some oddity desc being broken a small bit
Fixes the deep maints entry point never being borrowed

fixes oddity desc and deepmaints point

---

maps/SpaceFortress/spacefortress.dm
maps/__Nadezhda/data/shuttles-nadezhda.dm

No reason to let it process when it isn't being used.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Remove map

---

code/modules/genetics/mutations/cat_eyes.dm
code/modules/mob/living/carbon/human/life.dm

Cat eyes now is checked for in the appropriate file to give actual perfect night vision. (And of course horrible flash weakness)
Good luck getting it without infuriating our blue cat overlord.

Cat eyes fixed~

---

code/modules/power/antimatter/control.dm

Fix the rate at which the Antimatter Engine lose stability.

Fix the rate at which the Antimatter Engine lose stability

---

code/game/machinery/autolathe/artist_bench.dm
code/game/objects/items/oddities_faction.dm

Nukes Guilds prefction cube cutting it form 5 items to 3
Lowers artiest oddity spawns to not be able to give 30+ stats but still a good amount max 24 min 12

A clip in 2 saves 4

---

code/__HELPERS/global_lists.dm
code/modules/mining/drilling/drill.dm
code/modules/mining/drilling/wurm_controller.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm

Fixes wurms being able to be stuck behind mining rocks
Fixes some wurm aggroing
Wurms after destorying or turn off the drill leave in 60 seconds rather then 180

This was accully really hard to even think to fix

---

code/modules/mob/living/carbon/human/species/station/station.dm
code/modules/organs/external/subtypes/robotic.dm
code/modules/organs/external/subtypes/robotic_types.dm

Makes fpbs have 50 less health
Makes fpbs now be killable via shooting the chest/head/groin
All these changes do not affect church fpbs.

FPB fixes and rebalancing

---

code/datums/perks/oddity.dm

Adds 2 new oddity perks
One gives you more nsa and makes additions 80% less likely (still 100% going to happen)
One gives 20 more max hp

2 new perks for oddites

---

code/datums/perks/racial.dm

-Reduced the bonus folken give to oddities from +5 to +3
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Folken balance

---

maps/__Nadezhda/data/_Nadezhda_factions.dm

The kriosins have finnally learned how to turn their stolen sol fed fax machine to be able to reserve faxes

adds the missing kriosin fax

---

code/modules/clothing/under/jobs/medsci.dm

<details>
<summary>
Fixed Typo for Soteria Doctor's Uniform
</summary>
<hr>
<hr>
</details>
:cl: Fixed Typo for Soteria Doctor's uniform
/:cl:

Typo Fix: Soteria Doctor's Uniform

---

code/game/objects/random/mob/misc.dm
code/modules/genetics/creatures/ambusher.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Comment out the Ambusher on Sieg's recommendation due to it causing massive amount of runtimes.

Comment out the Ambusher

---

code/game/machinery/shower.dm
code/game/objects/items/weapons/mop.dm
code/game/objects/items/weapons/vacuum.dm
code/game/objects/structures/watercloset.dm
code/game/turfs/simulated/cleaning.dm
code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm
code/modules/mob/living/carbon/superior_animal/robots/robot.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/reagents/reagents/other.dm

Stops pool water overlays from being cleaned away by a verity of things.
If the hot tub keeps being cleaned away regardless Ill add a way to refill it mid round.

Water Overlays can't be cleaned away.

---

code/datums/autolathe/cells.dm
code/modules/reagents/reagent_containers/food/snacks/bread_loafs.dm
code/modules/reagents/reagent_containers/food/snacks/sandwich.dm

Fixes cell names being doble what they are when in a disk
Fixes butter toaste being unmakable
closes #2951

fixes cell names and toast

---

code/modules/recycling/disposal.dm

<details>
<summary>
Resolves Runtimes from Items being thrown at disposal units due to an integer trying to be assigned to an argument when it needs to be a string, should also help with message display issues.
</summary>
<hr>
<hr>
</details>
:cl: Fixes Runtimes for Disposal units and makes their related messages display correctly when items are thrown and it either lands inside or bounces.
/:cl:

Fixes Runtimes from Items being thrown into/at disposal units.

---

code/game/objects/structures/flora/flora_tree.dm

<details>
<summary>
Adds a 5% chance for trees to spawn spiders when chopped down, displaying a message to warn them when it happens.
</summary>
</summary>
<hr>
<hr>
</details>
:cl: Add: Trees will have a small chance (5%) to spawn spiders when chopped down, with an associated message to warn when it happens. :cl:
/:cl:

Tree Nests Spider Edition

---

code/game/objects/items/devices/lighting/flare.dm

Fixes torches to properly ignite and burn.

Torch Ignition Bug Fix

---

code/__HELPERS/global_lists.dm
code/game/area/Space Station 13 areas.dm
code/modules/ameridian/ameridian_crystal.dm
code/modules/mining/drilling/drill.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
code/modules/projectiles/guns/projectile/automatic/nordwind.dm

By Sieg
Swaps the crystals to SSObj rather then SSTurn
Fixes wurm armor being wrong snowflake own type eris did
Fixes a runtime in the nordwind spawning

Few fixes and wurm correction

---

code/game/area/Space Station 13 areas.dm
code/modules/ameridian/ameridian_crystal.dm
code/modules/ameridian/ameridian_spire.dm

Slight optimization to the crystal field area, and allow admins to toggle the processing of every crystal from the Spire.

Slight update to the crystals

---

code/modules/projectiles/guns/projectile/automatic/nordwind.dm

Nordwind ammo fix

---

code/modules/mob/living/carbon/human/say.dm

Did you know we overrid the emotes for humans?

---

code/game/objects/items/weapons/tools/pickaxe.dm
code/modules/clothing/accessories/accessory.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/projectile/automatic/buckler.dm
code/modules/projectiles/guns/projectile/automatic/vector.dm
code/modules/projectiles/guns/projectile/shotgun/swat.dm

Swapping fire modes with a stock now should not null the stocks boons
Fixes pickaxes not having a worksound
fixes buckler sound
fixes corpsman cape being invisable for real
fixes buckler missing flag

more misc fixes

---

code/game/objects/items/weapons/storage/backpack.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Should make linters happy when it works again
/:cl:

the dark testu

---

code/game/mecha/mecha_wreckage.dm

Fix a dumb error that prevented everyone from getting stuff from wrecked mechs.

Fix a dumb error

---

code/__HELPERS/time.dm
code/controllers/subsystems/ticker.dm
code/modules/mob/mob.dm

Adds a timer in minutes when round end gets called that counts down.
Tested and all that jaz.

Round End Timer

---

code/modules/mob/hear_say.dm

<details>
<summary>
Missed the fix PR for Eris' 'masks muffle voice' PR. This should fix at least one of the issues regarding it.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Should fix part of the issues regarding ghosts unable to hear people speak.
/:cl:

Fixes hear-say issue

---

code/__DEFINES/qdel.dm
code/__HELPERS/logging.dm
code/controllers/subsystems/garbage.dm
code/modules/admin/view_variables/reference_tracking.dm
sojourn-station.dme

Ports over code form LemonInTheDark GC opimation and sorting a bit.

GC update to even more TG like

---

code/modules/mob/living/carbon/human/say.dm

this will fix the issue of people appearing as 'unknown' despite wearing a mask. now they will be "Unknown as" since their id says who they are.
tested it and it works.

Fix Unknown speech

---

code/datums/mind.dm
code/modules/clothing/spacesuits/rig/modules/utility.dm
code/modules/core_implant/cruciform/machinery/armaments.dm
code/modules/core_implant/cruciform/rituals/priest.dm
code/modules/mob/living/silicon/robot/drone/_drone.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/mob/living/silicon/silicon.dm
code/modules/projectiles/guns/projectile.dm

Fixes robot modulas having endless power, they now have auto-charging cells
Fixes drones/robots hotkeys being defaulty set to hoomans, also in case for the rare odds this somehow messes up a "recalibrate hotkeys"
Fixes Will of the Protector name
Fixes Modular injectors not spawning correcting with beakers lists
Fixes speed loaders not updating icons

Misc issue fixes

---

code/modules/genetics/creatures/wasonce.dm
code/modules/genetics/genetics.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Nanogate users now actually take cloneloss damage when mutations are injected in them- and a good bit more of it.
/:cl:

Nanogate nerds take more cloneloss

---

code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/modules/clothing/spacesuits/rig/rig.dm
code/modules/clothing/spacesuits/rig/rig_pieces.dm
code/modules/clothing/spacesuits/rig/suits/combat.dm
code/modules/clothing/spacesuits/rig/suits/hydrogen_knight.dm
code/modules/clothing/spacesuits/rig/suits/station.dm
code/modules/clothing/spacesuits/void/void.dm

oh god how did i get here i am not good at atomization
:cl:
fix: rig armor plating
fix: rig armor in GENERAL
/:cl:

armor plating/rig armor plating changes/tweaks/fixes

---

code/modules/integrated_electronics/core/debugger.dm

<details>
<summary>
debugger now costs 10 steel, 5 glass, 5 plastic.
</summary>
<hr>
<hr>
</details>
:cl:
fix: debugger now costs 10 steel, 5 glass, 5 plastic in the protolathe instead of 1000, 500, 500
/:cl:

Fixes a bug with integrated circuits' debugger tool costing 1000 steel, 500 plastic, 500 glass

---

maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm

unloader removal

---

code/game/objects/effects/decals/crayon.dm
code/game/objects/items/weapons/candle.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/sanity/breakdowns.dm

Makes candles be able to be endless via magic
Adds Occult things
- Note this was legit 1:1 with a dream I had last night and then expanded a bit to be balanced

Dream Logic - Merge Me!

---

code/__DEFINES/cyborg_traits.dm

Fix the bitflags that were wrongly set in https://github.com/sojourn-13/sojourn-station/pull/3035

Fix the bitflags

---

code/game/objects/items/weapons/melee/energy.dm

Well, that should fix the coin bug.
https://github.com/sojourn-13/sojourn-station/pull/3037#issuecomment-1092314155
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Energy sword implant icon fix

---

code/datums/autolathe/clothing.dm
code/datums/craft/recipes/clothing.dm
code/modules/clothing/suits/miscellaneous.dm

Scavenger armor now has 10% more laser
Scavenger armor no longer has any slowdown
Scavenger armor now needs 2 plat the make

10% more laser and no slowdown

---

code/datums/setup_option/core_implants.dm

They are now unable to take body augmentations, as intended.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Cultured psionic organ implant fix

---

code/modules/core_implant/cruciform/rituals/path.dm

Cooldowns for church spells that were broken now are fixed

Fixes many church spells not having a cooldown

---

code/game/objects/items/weapons/space_harpoon.dm

Harpoon MODE_RECEIVE now accully is able to be used
Harpoon stat check no longer makes a runtime and now works

Harpoon Corrections

---

code/modules/bs_snare/machinery.dm

English corrected when pulled to the bluespace hub.
Made the console correctly connect with the hub so you didn't have to build the hub second.

Fixes for bluespace snare.

---

code/modules/materials/material_sheets.dm
code/modules/reagents/machinery/grinder.dm
code/modules/reagents/reagents/other.dm

Make the ameridian shards stack to 360 instead of 120
Add liquid ameridian as a reagent.

Make the ameridian shards stack to 360

---

code/modules/reagents/reagent_containers/glass/bottle.dm
code/modules/reagents/reagents/toxins.dm
code/modules/reagents/recipes/recipes_slime.dm

More reactions for the plorts
A new chemical that makes a friend?
Adds bottles to the game panel for testing. (The material chems, honey, pure slime jelly and plasma)

Upgrades xenobio

---

code/datums/objective/merc_mission.dm
code/modules/reagents/reagent_containers/food/snacks/soup.dm
maps/__Nadezhda/data/shuttles-eris.dm
maps/__Nadezhda/data/shuttles-nadezhda.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fuckening hell - Concerned K5
Fixes a runtime with wish soup 
Fixes the runtimes with shuttles

Shuttle fix and wish soup

---

maps/submaps/deepmaint_rooms/core/xenostudy.dmm

Fixes a linter error with a no chemical splashed thingy

Small linter fix

---

code/modules/projectiles/guns/energy/railgun.dm

-On closer inspection, the gauss rifle delt 86 damage with 100 armor pen, making it superior to the AMR in all possible ways. This change gives it 54 damage and 50 armor pen, an already super high and incredibly effective sniper caliber, despite its draw backs.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Gauss Nerf

---

code/game/objects/structures/crates_lockers/closets/secure/militia.dm

Adds in the vouchers that he forgot to add to the corpsman lockers. Already finding it questionable that he's giving the Marshals Counselors in their vouchers.

CDB is dumb femboy *GASP*

---

code/__DEFINES/qdel.dm

Reverts sojourn-13/sojourn-station#3067
Misstakes were made

Finer Toons GC exerpimental changes

---

code/game/objects/items/weapons/storage/blackshield_kits.dm
code/modules/reagents/machinery/grinder.dm

Fixes bottles given by the advanced grinder being wrong fill states
Fixes  STS Para box not being named

Fixes some bottles and para kit

---

code/modules/projectiles/guns/energy/railgun.dm

Reverts sojourn-13/sojourn-station#3085
This at basic look was an incorrect assumtion, the ARM does 90 damage 180 pen, this cant even take good upgrades
Also fixes the cells dusting by misstake
Fixes inconstants with materal

Fixes some Gauss rifle issues

---

code/game/jobs/job/civilian.dm
code/game/machinery/vendor/weapon_kit_vendors.dm

Artest has lost 10 TGH and gained 10 Mec at the request of RoquetheRogue#3951
Corrects corpsmen vouchers getting access to rushing bull and watchmen

Tweaks artest and fixes corpsmen vourchers

---

code/modules/cargo/packs_clothing.dm
code/modules/clothing/spacesuits/void/station.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Removed slowdown from Goldilocks armor, made crates ACTUALLY supply the whole suit. (It's still probably not worth the cost.)
/:cl:

Buff Goldilocks

---

code/game/mecha/mecha_wreckage.dm

Fix a duplication glitch with mech wreckages

Fix duplication glitch

---

code/modules/core_implant/cruciform/machinery/obelisk.dm

Fixes the church oblistic form always being active without churchies around

Fixes ablistics always being on

---

code/game/objects/items/weapons/power_cells.dm

fixes crank chargers for real

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Church garden somewhat reworked:
- Adds bee to the Church garden. Bzzzz!
- Puts some fencing around the garden in general to help travel flow, and make things look nice.
- The pathing from Altar to the Factory has been changed a little
- Small walkway to the Cherry tree
- Couple extra possible tree spawns to _spruce_ up the area
- Removed the stimky old barricades
Yes I am stupid.  Trilby showed me the error of my ways.  Also no more cows.

Adds Bees to the Church garden, slight rework!

---

code/modules/mob/living/carbon/human/species/species.dm
code/modules/mob/living/carbon/human/species/station/station.dm
code/modules/reagents/reagents/food-Drinks.dm

Important note; These values are all in kelvin. the base values are inherited directly from Eris and thus is likely why they are so "peculiar" and wide in range(and they were the base for our alien races and subsequently influenced said races values.)
Large changes to temperature tolerance ranges for all races. Initial values saw most races essentially immune to the affects of temperature outside of very specific scenarios.  To give some more context, tolerable temp is any value lower(or higher) than the 'cold/hot level 1-2-3'. This means that, say - for humans, whos heat-level-1=360, they did not suffer ANY ill effects of temperature until 360k(this is about 188f or 86c) and this is why we had weirdness with say...people getting infections and not even noticing till they were already …

temperature tolerance changes

---

code/__HELPERS/icons.dm

GetFlatIcon() optimizations from 2018 that we dont have yet

---

code/__HELPERS/logging.dm
code/_compile_options.dm
code/controllers/subsystems/garbage.dm
code/game/atoms_movable.dm

Adds logging to the reference tracker because someone decided to just copy and paste tg code without checking to see if it worked. It now logs into data>logs>year>Month/Day>day-weekday.log
:cl:
code: adds logging to the reference tracker
/:cl:

Really really dirty reference tracker fix

---

code/modules/mob/living/simple_animal/friendly/corgi.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm

E-M now no longer gets hungery and can be repaired
E-M dies properly now
Nerfs to robo hen -
takes 10 more units to make eggs
eggs are much less likely to be layed
coco now inside the hen makes coco bars

The long work

---

code/game/objects/items/devices/radio/encryptionkey.dm

Gives Cargo access to service coms for a little more inter-faction collaboration, same as with Marshals, Shield, and Si, Med

Gives Cargo access to service coms

---

code/datums/autolathe/biomatter.dm
code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
code/modules/core_implant/cruciform/rituals/path.dm

<details>
<summary>
</summary>
<hr>
Nerfs factorial "healing" to be more in line with the rest of the church litanies, because 5 minute cooldown aheal with 0 downsides really isn't something that should exist.
Also allows church to print individual brute and burn kits like ATK/ABK for same cost.
<hr>
</details>
:cl:
add: Individual printing for church brute/burn kits
balance: Factorial healing
/:cl:

Totally a church nerf

---

maps/submaps/deepmaint_rooms/core/Lab2.dmm

Fixes deepmaints lab2 map having the wrong area code

Area code fix

---

maps/_DeepForest/map/_River_Forest.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Reverts sojourn-13/sojourn-station#3140
To test if this legitmently is an issue or not

Revert "Elf mapping gone wrong"

---

code/game/machinery/doors/firedoor.dm

When forcing a fire door open when its not wanting to be opend now properly logs you once again

Readds fire door open list

---

maps/_DeepForest/map/_River_Forest.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

lower level

---

code/modules/mob/living/carbon/superior_animal/robots/subtype/church/church.dm

Prevent Church Golem from cleaning the floor.

Prevent Church Golem from cleaning the floor

---

code/modules/projectiles/guns/projectile/automatic/armsmg.dm
code/modules/projectiles/guns/projectile/automatic/buckler.dm

Buckler adjusted with the same changes as the others.
Triage ALREADY done but now it's in the changelog :)
arm SMG properly has its firereates defined now - also given the same treatement,
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

SMG hotbalance

---

code/controllers/subsystems/garbage.dm

FUCK.
</details>
:cl:
fix: FUCK.
/:cl:

FORGOT TO PUSH THIS COMMIT FUCK

---

code/game/objects/structures/firepits.dm

Due to a code issue, it was impossible to insert wood into a bonfire, this fixes the issue.

Fix the bonfire

---

code/modules/genetics/machinery/genetics_cloner.dm

Doctors can now use the genes cloner like intended

Fixes cloner bypass

---

code/modules/projectiles/guns/mods/mods.dm

:cl:
balance: silencer AP -10% >> 0%, silencer recoil -10% >> 0%
/:cl:

silencer rebalance

---

code/game/objects/items/stacks/throwing.dm

Prevent an exploit with the throwing knives due to the damage being stacked on one another.

Fix an exploit with the throwing knives

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes a couple of things, makes a couple of changes
- Removes cat walks from Church and Prospectors, because f%$k cat walks and their biomass hiding, and hard to click selves.
- Unnerfs the free clinic by giving it back a door
- Adds frames, and  a honey extractor to the garden, woops!!!
- Puts windows around the chicken put, they are no longer free range.  Sad!

Couple surface changes

---

code/modules/cargo/packs_engineering.dm

Adds counter crates for engi tab so people can get the geiger counters

geiger counters crate

---

code/datums/topic/admin.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Add Lonestar to job ban panel

---

code/modules/mob/living/carbon/superior_animal/superior_animal.dm

I recently realized that weakrefs might be confusing. So, I updated the documentation.
If you question the form, that's multiline autodoc. If you have vscode, hovering over that var will show the documentation in a box.
:cl:
code: Updated target_mob documentation
/:cl:

Updates target_mob documentation to hopefully avoid future AI failures

---

code/modules/clothing/spacesuits/rig/modules/utility.dm

"""""""""""""Correct"""""""""""""""""""' aka rebalances medical injectors to let you inject people once more

let me inject my people

---

code/modules/genetics/machinery/genetics_cloner.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes edge case where the cloner runtimes from the reader being disconnected during the cloning process.
/:cl:

Fix genetics cloner logs

---

code/game/objects/effects/decals/Cleanable/humans.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Anti Stain and Wax coatings now prevent shoes from getting bloody when crossing blood/oil stained tiles.
/:cl:

Anti Stain fix

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes wires

---

code/game/objects/items/weapons/manuals.dm

just types in a slime core recipe book. Nothing fancy its hand written for every recipe so eventually it will outdate. But for now can help people figure out the reactions. As normal I don't try to map things in so its admin spawn only.

slime core recipe manual

---

code/modules/mob/living/carbon/viruses.dm

Fixes antibodies to actually cure people now.
Radium injections should produce antibodies just fine. Those antibodies can be transferred around however needed.
The cure research machine however produces antibodies that don't work. The machine will need to be fixed at a later date.

Antibodies Fix

---

code/__HELPERS/_lists.dm
code/game/objects/items.dm
code/game/objects/items/weapons/tools/mods/_upgrades.dm
code/modules/projectiles/guns/energy/railgun.dm

literally a 5 minute fix why has this been broken for a year

fixes item mod blacklists

---

code/modules/trade/machinery/trade_beacon.dm

wow this is problematic due to bulk exports

50% reduction in beacon entropy

---

code/game/objects/items/weapons/power_cells.dm

Around nerfs the hand changer by like 50~%

Cell charger rebalance

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes low walls of glass to walls
Fixes some wires

mapping is bad

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Corrects a notice board location

fixes a notice board

---

code/game/mecha/equipment/weapons/ranged/laser_weapons.dm
code/modules/ameridian/ameridian_analyzer.dm
code/modules/ameridian/ameridian_crystal_red.dm
code/modules/ameridian/liquid_ameridian_processor.dm
code/modules/projectiles/projectile/special.dm
code/modules/research/designs/mecha_equipment.dm
code/modules/research/nodes/combat.dm

\- Add Sonic Mech Gun, a mech-mounted variant of the Handheld Sonic Emitter that pack a stronger punch, even against non-crystal enemies.
\- Change the sprite of the Liquid Ameridian Analyzer.
\- Allow the Liquid Ameridian Processor & Analyzer to be upgraded.
\- \- Upgrading the LAP's manipulator reduce the material price of printing objects.
\- \- Upgrading the LAA's manipulator allow the machine to extract more points from a given sample of Liquid Ameridian, while upgrading the matter bin allow the machine to process more ameridian at a time, increasing the speed.

More Ameridian stuff

---

code/game/objects/items/oddities_faction.dm

bandaid fix for now, I'll properly implement DROPDEL later

psionic omnitools can no longer be artifier perfection cubed

---

code/datums/mind.dm

<details>
<summary>
Potential fix for a runtime created by mind.dm, thanks Sieg!
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Updates mind.dm

---

code/datums/mind.dm
code/game/machinery/computer/prisoner.dm
code/modules/modular_computers/file_system/programs/command/card.dm

Fixes two warrenings
Edits access for access editing, heads of staff can termiate and print reports

access tweaks

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes more bad wires and lights
Fixes new storage room door wall

all the hotfixes

---

maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes chem lab issues
Improvings mining base area and windows adding in their new vendor

area code vender and chemaster

---

code/modules/library/lib_items.dm
code/modules/library/lib_machines.dm

Allows many more items to be stored in bookcases
Improves bookcase and general libary code

Better bookcase code

---

code/modules/client/preference_setup/background/03_records.dm
code/modules/mob/new_player/new_player.dm

Missing records now warns people that they are required
Fixes a few warnings

warrening players

---

code/modules/nanogate/powers/user.dm

Make the nanite chem power display the name of the nanites

Make the nanite chem power display the name of the nanites

---

code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm

Remove the drill drop from the mining drone that lonestar has.

Remove the drill drop from the mining drone

---

code/__HELPERS/time.dm
code/controllers/subsystems/ticker.dm

Reverts sojourn-13/sojourn-station#3304

Revert "Real time O:"

---

code/controllers/subsystems/ticker.dm

prob ruins everything

---

nano/templates/chem_dispenser.tmpl

adds the option to dispense 60 units to the chem dispenser

adds 60 units as an option to chem dispensers 

---

code/game/machinery/vendor/misc_vendors.dm

<details>
<summary>
Adds the maid headdress to the main kinkmaster inventory, and then adds such degenerate, sexual outfits as a wedding dress and plain glasses to its contraband inventory. Also a bible, for when you need to pray the horny away and/or light religious play. 
I will not stop buffing maids.
</summary>
<hr>
<hr>
</details>
:cl:
add: New contraband to the kinkmaster.
/:cl:

Kinkmaster Contraband

---

code/game/objects/structures/crates_lockers/closets/secure/security.dm

<details>
<summary>
Rangers no longer get 2 primary vouchers and instead get a proper armor voucher, seeing as they need to frequently go out and deal with real criminals who are actually armed. 
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Fixes Ranger vouchers

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Does what the title says. Literally just a one tile change. Asked for by a player in the map dev channel.
Before: https://i.imgur.com/zDH0HOR.png
After: https://i.imgur.com/witJW0q.png

Adds an ATM to the Blackshield department at player request.

---

code/modules/mob/living/simple_animal/friendly/farm_animals.dm
maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Replaces some outside and inside spider/roach spawns with termites (they cant make more of themselfs so this is a net loss of other factions)
Moves the ratking again
Replaces the gladstone in the armory with a SWAT
fixes cow name being wrong
cleans up some areas to look a bit nicer with added decore

cow and mapping tweaks

---

code/modules/detectivework/tools/bullet_scanner.dm

<details>
<summary>
Fixed typo in bullet scanner description
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Fixed typo in bullet scanner description

---

code/game/objects/items/weapons/storage/marshal_kits.dm

Fixes some bad box spawning
close #3341

fixes some marshal boxes

---

code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm

tin, heatwaves are like explosions but do burn damage and don't hurt walls

adds heatwave grenades to kaida high end grenade stock

---

code/modules/projectiles/projectile/special.dm

Reduces sonic bolt ap form 90 to 30

Sonic weapon fix

---

code/modules/projectiles/guns/energy/tetra.dm
code/modules/projectiles/projectile/beams.dm

does the same thing as the other pr only better
fixes tetra from being stuck on silenced mode

tetra re-rebalance (and fixes)

---

code/__DEFINES/maths.dm
code/modules/ameridian/ameridian_crystal.dm

<details>
<summary>
Improves linear interpolation math.
</summary>
<hr>
<hr>
</details>
:cl:
fix: LERP no longer branches or tolerates NULL as an input value.
code: Added UNLERP, which is the opposite of LERP.
code: Renamed r4d6's MAP into REMAP, which is a combination of both UNLERP and LERP.
/:cl:

Minor math improvements.

---

code/__DEFINES/machinery.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Propis shuttle now has its corrected cam network
Propis shuttle now has better air controle
The checkpoint area for the propis shuttle now counts as halways
The checkpoint area and halls have better cam covering them

of cams and pipes

---

code/game/objects/random/food.dm
code/modules/food/recipes_microwave.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
code/modules/mob/living/carbon/superior_animal/termite/termite.dm
code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
code/modules/reagents/reagent_containers/food/cubes.dm
code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm

Spider and roach blood has been fixed form their sickly greens to proper grays and blues
Exsanding cube code has been vastly improved fixing a bad runtime with kaiser roaches

cube improvements and better blood

---

code/game/atoms_movable.dm
code/modules/mob/mob.dm

!!!UNTESTED BECAUSE WE HAVE SO MANY USAGES OF WALK() I LITERALLY CANT TEST IT DUE TO THE FALSE POSITIVES!!!
Remember to remove your references people
:cl:
fix: Fixes a GC failure due to movement handlers not being removed on destroy of movable and mob
/:cl:

Fixes yet another harddel, this time on atom/movable and /mob.

---

code/modules/clothing/spacesuits/rig/modules/ninja.dm

Makes the ninja suit's modules usable, I made this because I'm making a PR that fixes the errors in vscode and I thought this one should be atomized.
:cl:
add: The ninja's suit cloak is now usable as is its teleporter.
/:cl:

Makes the ninja suit usable, part of a PR I'm making.

---

code/ATMOSPHERICS/datum_pipeline.dm
code/ATMOSPHERICS/pipes.dm
code/game/objects/items/weapons/storage/hardcases.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/ventcrawl/ventcrawl_atmospherics.dm

Fixes a huge harddel issue we had with hardcases, gets a step closer to fixing human harddels, and safeguards pipes from harddels at least on the code side.
NEVERMIND I GIVE UP ON PIIIPESSSS
:cl:
fix: Fixes more harddels
/:cl:

Fixes even MORE hard-dels. 

---

code/game/machinery/atmoalter/meter.dm

hotfixes a runtime
:cl:
fix: fixes potential runtime
/:cl:

Quick hotfix for a possible runtime

---

code/game/machinery/atmoalter/meter.dm

I dont know why this was needed, but it was.
:cl:
fix: fixes another runtime
/:cl:

Fixes ANOTHER runtime.

---

code/ATMOSPHERICS/pipes.dm
code/game/machinery/atmoalter/meter.dm

200k runtimes because of fucking deleted pipes huhhhhhhh
possible fix i hope it works
:cl:
fix: PLEASE. WORK.
/:cl:

Thank you eris for your wonderful code that includes calling procs on deleted pipes. Thank you. Hotfix.

---

code/modules/integrated_electronics/subtpes/input.dm
code/modules/integrated_electronics/subtpes/manipulation.dm
code/modules/integrated_electronics/subtpes/mining.dm
code/modules/integrated_electronics/subtpes/output.dm
code/modules/integrated_electronics/subtpes/reagents.dm

- Adds a new circuit component that allows you to purge chemicals without having to use the smoke generator which would flood admin logs.
- Reduce the cooldown of the locomotion circuit to its previous value 1 (current is 3). This change is very much needed as even walk speed was enough to out run the circuit. Making any buddy drone or useful remote drone just a painful snail speed experience.
- The Health Scanner circuit component has been rebalanced for both the simple and complex version. The simple version now outputs a total health value that allows you to create very simple if logic gates in case something happens. The complex version allows for much more precise information and allows you to determine which type of medication to give. An example would be that the simple version …

Integrated circuits tweaks and fixes

---

maps/_DeepForest/map/_Prepper_Bunker.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Like the title says. Removes a bunch of pipes that had duplicates on the same turf, in hopes of helping improve issues with pipe harddels. Lich knows about this.

Removes duplicate pipes in the colony and Preppers

---

code/datums/craft/recipes/tools.dm
code/game/objects/items/weapons/power_cells.dm

handmade crank charger. 4 cell charge restored per cycle, costs 30 steel, requires a welding tool better than junk tier to make.

handmade crank charger

---

code/datums/components/fabric.dm
code/modules/dungeons/crawler/dungeon_gen.dm
code/modules/dungeons/procedural/deepmaint.dm

Makes a breakdown no longer see ghosts
Tweaks generation of deepmaints and grayson

gen tweaks and ghost fix

---

maps/_DeepForest/map/_Prepper_Bunker.dmm

TRILLBY USE THIS FOR THE CHANGELOG: Deletes a duplicated pipe that was missed.
it does what the title says

Fixes a duplicated pipe that was missed.

---

maps/_DeepForest/map/_Prepper_Bunker.dmm

Fixes another duplicated pipe that was missed.

more fucking pipes

---

code/modules/ameridian/ameridian_crystal.dm
code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm

Fix some ameridian-related harddels.

Fix some ameridian-related harddels

---

code/game/objects/structures/burrows.dm

<details>
<summary>
</summary>
<hr>
Makes welders work on cracks again I screech
<hr>
</details>
:cl:
fix: me somehow breaking welders on cracks
/:cl:

burrow welding

---

code/modules/projectiles/guns/projectile/automatic/mamba.dm
code/modules/projectiles/guns/projectile/shotgun/riot.dm

<details>
<summary>
Fixes the Mamba and all paths of it from being dual-wielded. Suffering......
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Small possible exploit with dual-wielding Mambas or the like. Funny, but not intended.
/:cl:

GOD PLEASE GOD NO MORE

---

code/_onclick/hud/parallax.dm
code/_onclick/hud/screen_objects/base_screen_objects.dm
code/datums/mind.dm
code/datums/outfits/jobs/job.dm
code/datums/perks/perk.dm
code/game/machinery/camera/camera.dm
code/game/machinery/camera/motion.dm
code/game/objects/effects/portals.dm
code/game/objects/effects/spiders.dm
code/game/objects/items/devices/scanners/price.dm
code/game/objects/structures/burrows.dm
code/modules/ameridian/ameridian_crystal.dm
code/modules/dungeons/junk_tractor_beam.dm
code/modules/materials/material_sheets.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/friendly.dm
code/modules/mob/living/living.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/mob/mob.dm
code/modules/mob/mob_defines.dm
code/modules/projectiles/projectile.dm

Does what it says on the tin.
Note that not every change made here WILL fix problems. These are mainly educated guesses, like burrows, golems.
:cl:
fix: More fixed harddels and runtimes.
/:cl:

Fixes even more harddels and runtimes. 

---

code/modules/modular_computers/file_system/news_article.dm
code/modules/modular_computers/file_system/programs/generic/news_browser.dm
news_articles/Agent_Captured.html
news_articles/Call_to_Action.html
news_articles/CardCarp.html
news_articles/Catastrophic_Outbreak.html
news_articles/Deep_Maint_Psychosis.html
news_articles/Didnt_think_to_ask_if_they_should.html
news_articles/Gatehouse_Clusterfuck.html
news_articles/Listening_Post_Destroyed.html
news_articles/Morning_Star.html
news_articles/Official_Marshal_communique.html
news_articles/Progress.html
news_articles/Psionic_Ascension.html
news_articles/Psionic_Medicine.html
news_articles/Scrap_Haven.html
news_articles/Sniper_Assault.html
news_articles/Whoever_fights_monsters.html

Adds every minor news in minor news to the game

Better logged news

---

code/game/objects/structures/crates_lockers/closets/secure/security.dm
code/modules/clothing/head/helmet.dm

<details>
<summary>
Fixes WO helmet sprite reverting.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: WO helmet
/:cl:

Fixes WO helmet

---

code/modules/projectiles/guns/projectile/shotgun/handmade.dm
code/modules/projectiles/guns/projectile/shotgun/riot.dm

<details>
<summary>
</summary>
<hr>
What it says in the title, oversight on my part
<hr>
</details>
:cl:
fix: certain internal magazine shotguns not being able to use tubes
/:cl:

Allows more shotguns to use tubes

---

code/modules/mining/drilling/drill.dm
code/modules/mining/drilling/termite_wave.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/termite/termite.dm
code/modules/mob/living/simple_animal/soul.dm
sojourn-station.dme

Vastly lowers the danger of mining drills termites
Makes mining drill termites properly walk up and attack the drill

Makes termites accully attack the drill

---

code/game/jobs/job/engineering.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/medical.dm
code/game/jobs/job/science.dm
code/game/jobs/job/security.dm

Redoes many alt tiles adding in more better descripting what that person does 
Removes all cases of lower ranking Alt titles as people thought a lower pick was a lower rank, should clear up that confusion

Better names

---

code/modules/telesci/teleporter_blocker.dm

<details>
<summary>
Fixes typos and also grammar in the description and examine text of the bluespace inhibitor.
</summary>
<hr>
<hr>
</details>
:cl:
spellcheck: Fixed typos and grammar in the bluespace inhibitor
/:cl:

fixes typos in the bluespace inhibitor

---

code/datums/outfits/jobs/job.dm

Fixes a bug. Introduces a runtime but better than broken functionality.
Ask dongels if youre confused.
:cl:
code: Reverts a change made to job.dm
/:cl:

Reverts a change in job.dm

---

code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/attack.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/living_defines.dm

Adds delays for attacking and firing for mobs to do
Adds sanity checks for mobs to not shoot well dead

mob fire delays, they just work

---

code/modules/mob/living/carbon/superior_animal/superior_animal.dm

Title. Now checks to see if its needed to find a new target, reducing the calls of a VERY expensive proc.
:cl:
code: Optimizes mob target code.
/:cl:

Optimizes my last PR a bit.

---

code/__DEFINES/is_helpers.dm
code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/attack.dm
code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/termite/termite.dm

Title.
Some misc optimizations here and there too and a few QOL things.
TESTED. A GOOD BIT. Ranged attacks work, melee works, targetting works, untargetting works, no runtimes, doesnt feel laggy, and feels somewhat fairer.
Mobs are just as deadly as before-you just have a chance to react.
:cl:
balance: Mobs will now warn you before attacking or targetting you.
/:cl:

Makes ranged mobs have a delay on both attack and targetting, to make it a bit more fair to players.

---

code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/bishop.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/custodian.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/turrets.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/termite/termite.dm
code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
code/modules/mob/living/carbon/superior_animal/vox/vox.dm
code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm

Gives many different mob range verbs to be more fitting
"""Improves""" via removes some code

Tweaks mob messages to be more modular

---

code/modules/mob/living/carbon/superior_animal/superior_animal.dm

Does what the title says.
I love defines. They SURE DO ACTUALLY TELL ME HOW LONG THEY ARE
:cl:
tweak: Increased the mob shot delay
/:cl:

Increases timer on mob shot delay to give even more time to react.

---

code/modules/mob/living/carbon/superior_animal/vox/vox.dm

tin. they drop bone now
they're pretty common on the lodge plain so hopefully this makes them more worthwhile to actually kill

tribal vox now have a bone drop

---

code/_onclick/telekinesis.dm

Lowers tk range form 14 tiles to 10 tiles

Lowers tk range

---

code/modules/mob/living/carbon/superior_animal/superior_animal.dm

I found, in combat, you can miss some of the messages. This makes that much harder.
:cl:
tweak: Telegraph text is now colored.
/:cl:

Colors telegraph text to make it more clear to the reader.

---

code/game/jobs/job/guild.dm

Simple new alt title for miners called Ameridian Gatherer

Ameridian Gatherer

---

code/modules/projectiles/guns/projectile/automatic/blackguard.dm

Makes the blackguards scope as intented 3 tiles

Fixes blackguards scope

---

code/datums/datum_click_handlers.dm

<details>
<summary>
Makes it so full auto no longer fires on middle click and no longer targets adjacent things unless you're on harm intent, allowing you to brace with the safety off.
</summary>
<hr>
Full auto was overriding default behavior and making full auto mode guns unwieldy. This fixes that issue.
<hr>
</details>
:cl:
fix: Full auto no longer fires on middle click or next to you.
/:cl:

Full auto fix

---

code/modules/mob/living/carbon/superior_animal/superior_animal.dm

FUCKING HOTFIX FOR A STUPID FUCKING BUG

---

code/__HELPERS/unsorted.dm

Title. Only checks objects as thats the only thing that is opaque right now, besides turfs which we dont need to check. I hope.
:cl:
fix: Fixes a bug with can_see()
/:cl:

Patches a bug in the updated can_see proc. Will now respect the opacity of any object in it.

---

code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
code/modules/research/designs/cell.dm
code/modules/research/nodes/power.dm

Fixes the spider posin injecting
Adds in at request of R4 their ameridian cell, costs ameridian to make use or something

quick fix and ameridian cell

---

code/datums/perks/racial.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/nanobot/ai.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm

Title. Tested, mob targeting and following seems to work normally, no runtimes, and profiler seems to report a increased cost of getPotentialTargets(). All this means is that MC has more room to be able to process mobs, so the proc is being run more often as the SS is no longer freezing as much.
:cl:
code: Optimizes mobcode more.
/:cl:

Optimizes mobcode by removing two calls of findtarget() on every life tick.

---

code/__DEFINES/mobs.dm
code/_macros.dm
code/datums/perks/racial.dm
code/modules/genetics/creatures/wasonce.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
code/modules/mob/living/carbon/superior_animal/nanobot/ai.dm
code/modules/mob/living/carbon/superior_animal/roach/life.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm

IT WORKS HAHAHAHAHA
Replaces getPotentialTargets() by putting it straight into find_targets(). I was going to make isValidAttackTarget a macro but holy shit that wouldve been a headache.
fucked up and made this a branch off of https://github.com/sojourn-13/sojourn-station/pull/3465, please only merge when that is merged
:cl:
code: Centralizes mob targetting into findTargets() to further optimize mobcode
/:cl:

AHAHHAAH IT WORKS IT FUCKING WORKS (Optimizes mobcode even more by removing proccalls and setting for loop in findTargets() to as anything)

---

code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/attack.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm

Fixes mobs no longer respecting being weakend

mobs now respect being weakend

---

code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
code/modules/reagents/reagents/toxins.dm

Spiders move faster across the board(in order of speed, hunter types->nurse types->guardian types/other(includes plasma and recluse, no speedy 1 shots!)
Pararein has been adjusted to be significantly more toxic, no more forgetting you got bitten because it takes 30 minutes to metabolize to dangerous levels.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Spider difficulty tweak.

---

code/modules/mob/living/carbon/superior_animal/superior_animal.dm

fixes the dumb bug where spiders or whatever emote after death
:cl:
fix: fix bug...
/:cl:

Im stupid! I fix bug!

---

code/modules/mob/living/carbon/superior_animal/defense.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm

i love it when i miss a obvious problem with a pr
fixes dead emotes and following because my other fix didnt fix it
:cl:
fix: fixes dead emotes and following
/:cl:

AAAAAAAAAAAAA

---

code/modules/core_implant/cruciform/rituals/group.dm
code/modules/core_implant/cruciform/rituals/priest.dm

Fixes close #3471 
Group Sanctify now will work

Fixes Sanctify group

---

code/__DEFINES/admin.dm

Title. Loc is there, so why not locs.
:cl:
code: Locs is now in the var copy blacklist.
/:cl:

Adds locs to the var blacklist

---

code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
code/modules/reagents/reagents/toxins.dm

Slightly better numbers
Makes spider toxins more in line with a building up toxin issue rather then crippling mid-combat
Slows down many spiders form being a bit to fast for anyone not running on speed drugs or speed buffs in a line

More spider tweaks

---

code/modules/clothing/gloves/miscellaneous.dm

Just fixing a small icon thing

Fix an Icon of an glove

---

code/modules/mob/living/simple_animal/hostile/big.dm

<details>
<summary>
Title
</summary>
<hr>
<hr>
</details>
:cl:
fix: Nightmare stalkers now drop their chitin
/:cl:

Nightmare stalkers now drop chitin

---

code/modules/mob/living/carbon/superior_animal/superior_animal.dm

Title. Basically makes things work as intended
:cl:
fix: mobs now properly use comfy_distance
/:cl:

Adds a use of comfy_distance where I should've put it before, damn it.

---

code/modules/client/preference_setup/loadout/lists/clothing.dm
code/modules/client/preference_setup/loadout/lists/xenowear.dm

<details>
<summary>
</summary>
<hr>
Add Mime Mask costume piece to loadout selection!
There's a million other masks, and even the clown mask, so why not the mime mask?
<hr>
</details>
:cl:
add: added the mime mask to the loadout selection
/:cl:

Adding the Mime mask to the loadout. That's it.

---

code/modules/clothing/suits/armor.dm

When the forman armor was made it was balanced around a bug that was fixed.
This now makes it simular to the normal scav armor in that it can be invested in to greater affects

Fixes forman armor

---

code/modules/projectiles/gun.dm

Recoil tested hard-numbers fix

---

code/__HELPERS/turfs.dm
code/game/objects/items/weapons/mop.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/walllocker.dm

Wall lockers no longer block thrown items, mops or other random things
Mops sweeping motion has been properly fixed
All tested

Fixes mops for real

---

code/game/machinery/vendor/weapon_vendors.dm

<details>
<summary>
Guncases 25c instead of 50c.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Guncases half off! What a steal!

---

code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
code/modules/reagents/reagents/toxins.dm

Hunters .5 slower
Pararein, to compensate for being three times deadlier than before - now processes out 4 times faster, doing a bit less damage over its lifespan now.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Adjusts spiders further

---

code/game/mecha/equipment/tools/ai_holder.dm
code/game/mecha/mecha.dm
code/game/objects/random/mecha.dm
code/modules/research/designs/mecha_equipment.dm
code/modules/research/nodes/robotics.dm
sojourn-station.dme

Removes the broken, and useless Mech AI holders that bricks any AI that uses it

Remove not improve

---

code/game/mecha/equipment/tools/ai_holder.dm
code/game/mecha/mecha.dm
code/game/objects/random/mecha.dm
code/modules/research/designs/mecha_equipment.dm
code/modules/research/nodes/robotics.dm
sojourn-station.dme

Reverts sojourn-13/sojourn-station#3516
Wait

Revert "Remove not improve"

---

code/modules/client/preference_setup/loadout/lists/armament.dm
code/modules/client/preference_setup/loadout/lists/utility.dm
code/modules/projectiles/guns/projectile/pistol/clarissa.dm
sojourn-station.dme

Adds in the .35 op havelock to the loadout, starts unloaded so you need 3 points to even get it loaded on spawn
Adds in a few rubber and mags for .35 to loadout
Adds in a pre-loaded Clarissa  with rubbers
Adds in for 1 costs gun case to loadout

Loadout guns! pew pew

---

code/game/mecha/combat/combat.dm
code/game/mecha/equipment/tools/tools.dm
code/game/mecha/equipment/weapons/melee.dm
code/game/mecha/mecha.dm
code/game/mecha/working/working.dm
code/modules/research/designs/mecha_equipment.dm

\- Allow mechs to deselect the selected equipment.
\- Allow mechs to punch stuff when no equipment is selected and on harm intent.
\- Convert the Fist Plating from a melee weapon into a passive equipment that reduce damage taken by 10% and allow worker mechs to punch stuff. Combat Mechs don't need it to punch stuff, but still benefit from the damage reduction.
\- Allow mechs to interface with machinery while no equipment is selected. You can finally push buttons to open doors without having to leave the mech.
\- The odysseus still can't punch because of its vow of non-violence.

Allow mechs to punch & interact with shit.

---

code/modules/clothing/clothing.dm
code/modules/clothing/suits/armor.dm

guncases moved from clothing/suit/armor allowed to clothing/suit allowed - can be worn on any suit now. 
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Guncase twealks

---

code/modules/client/preference_setup/loadout/lists/xenowear.dm
code/modules/sprite_accessories/_accessory_hair.dm

fixes the Mar'qua gil mask and 'pointed frills' hairstyle. whoops!
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Few Mar'Qua fixes

---

code/controllers/subsystems/economy.dm
code/game/jobs/department.dm

The endless magic money of the department payouts have been disabled.

Printers run dry

---

code/datums/autolathe/guns.dm
code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm

<details>
<summary>
Fixes some misc lore errors with Blackshield guns being branded as "Blackshield" instead of NM. NM makes all colony issued guns to Security forces unless imported i.e the Holland and Sullivan firearms.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Lore inconsistencies.
/:cl:

Blackshield Lore Errors

---

code/modules/projectiles/guns/projectile/pistol/judiciary.dm

<details>
<summary>
Due to conflict with my previous PR it seems the Judiciary lacked a sprite. It's been amended and fixed now.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Judiciary no longer having missing sprite icon.
/:cl:

Fixes Missing Icon

---

code/modules/core_implant/cruciform/rituals/path.dm

Factorio holy item summoning no longer can be cheated to stack more then one request at a time

basic anti-cheat

---

code/modules/projectiles/guns/projectile/automatic/mamba.dm

<details>
<summary>
Oversight when fixing its caliber I forgot to change the mag path back away from stan-mag.
</summary>
<hr>
<hr>
</details>
fixes: Python now takes proper mag type.
/:cl:

Python Fix

---

code/game/gamemodes/events/carp_migration.dm
code/game/gamemodes/events/hidden_events/bluespace_rift.dm
code/game/gamemodes/events/ion_storm.dm
code/game/gamemodes/events/meteors.dm
code/game/gamemodes/events/radiation_storm.dm
code/game/gamemodes/events/rogue_drones.dm
code/game/gamemodes/events/supply_pod.dm
code/game/gamemodes/events/wormholes.dm
code/game/gamemodes/storyteller.dm

Blacklists several non-funicational and or bad events form even being selectable via the story teller
Enables the story teller to gain points and be able to do its magic to spice up the round over time
PREVENTS antag rng story teller issues
**this will need tweaking and balancing**

Story Teller enabled

---

code/controllers/subsystems/voting/poll_types.dm
code/game/gamemodes/events/electrical_storm.dm
code/game/gamemodes/storyteller.dm

Eltroc storm now much rare and only happens twice
You can now vote better for story tellers and more then one vote per round
Makes events more evenly spaced hopefully

Storyteller tweaks

---

code/modules/mob/living/carbon/superior_animal/ai.dm

Honestly I just hate new here. It sucks.
I dont really know if it'll make it run better. It just looks better.
:cl:
code: Makes findTarget's list use list() and not new
/:cl:

Tiny baby optimization for mob AI maybe???

---

code/game/gamemodes/events/hivemind_controller.dm
code/modules/admin/admin_verbs.dm
code/modules/hivemind/core.dm
code/modules/hivemind/machines.dm
code/modules/hivemind/mobs.dm
code/modules/hivemind/self_defense.dm
code/modules/hivemind/wires.dm
code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
sojourn-station.dme

admin: tools for extra fancy adminbus of hivemind and better tracking it.

Hivemind additons

---

code/modules/clothing/suits/miscellaneous.dm

Fixes numerical garb no longer is an error

Fixes numerical garb

---

code/controllers/subsystems/jobs.dm
code/game/gamemodes/events/hivemind_controller.dm
code/modules/core_implant/core_implant.dm
code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm

Fixes a small error in hivemind pannel
Allows admins to mass-trigger crusaders for when hivemind happens that require it

church buff

---

code/game/gamemodes/events/viral_infection.dm

Removes rather then improves rng viro infection that the story teller does

Its no longer 2020

---

code/modules/mob/living/carbon/superior_animal/termite/termite.dm
code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm

Gives termites their proper names

Proper Termite names

---

code/modules/mob/living/carbon/human/human_damage.dm

Renames Variable to hopefully correct runtime.

Hopefully Fixes Runtime

---

code/modules/mob/death.dm
code/modules/mob/living/carbon/superior_animal/defense.dm

I have no idea of what causes the bug, so I can't test this. This is my best guess onto what's happening.
:cl:
fix: Potentially fixed the bug where dead mobs follow you around
/:cl:

Potentially fixes the bug where dead mobs follow you

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes a space tile in maints
Fixes some bad wires, pipes and tiles in maints

wires, apcs, and air

---

code/modules/projectiles/guns/projectile/automatic/vintorez.dm

Val and Vintorez now say they are rifle rather then carbine

Fixes name of the val and vin

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes several mismatched tiles
Adds random batteries and tool mods back to Soteria
Adds Soda and Coffee machine to R&D Break room
Fixes a lot of bad wires.
/:cl:

Tweaks map

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Patches holes in space beneath windows in the new R&D map
/:cl:

patches holes

---

code/game/objects/items/weapons/implant/implants/death_alarm.dm

Death alarms now will accounce on common if no medical personal are in the game

death alarm medical check

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

less-wall obelisks

---

code/_global_vars/misc.dm
code/game/gamemodes/storytellers/mime.dm
code/modules/admin/admin_verbs.dm

admin: added "manage custom kits" verb and associated functionality
By Trilby
Tweaks mime to better statis its point gains and events when swapped form

Admin and Mimery

---

code/modules/mob/living/silicon/robot/gripper.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/mob/living/silicon/robot/robot_hud.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/power/cell.dm
code/modules/surgery/internal.dm

Medical borg can now do surgery affectively, i.e set the tanks and do organ replacements
Cyborg gear now recharges as intented
Cyborg emag gear is no longer doupable - again

Major fixes and qol

---

code/modules/hydroponics/beekeeping/beehive.dm

Bees now max out yield mod of 15 rather then endless

Bee Sanity

---

code/game/machinery/doors/airlock.dm
code/game/machinery/doors/blast_door.dm
code/game/machinery/doors/door.dm
code/game/machinery/portable_turret.dm
code/game/objects/structures/burrows.dm
code/game/objects/structures/satellite.dm
code/modules/client/edge_sliding/move_loop.dm
code/modules/mob/living/carbon/superior_animal/defense.dm
code/modules/scrap/scrap_beacon.dm

Back end code clean up to use call back timers over sleep in some commonly used things.
Makes code look better!

death to sleep procs MK I

---

code/modules/mob/living/silicon/robot/robot_dogborgs.dm

Fixes wideborgs being invisable

dogborg icon hotfix

---

code/modules/modular_computers/file_system/programs/generic/trade.dm

Hydros trade beacon program as intented now no longer can be copyed.
I hecked up on a false then a true

Worst trade deal

---

code/game/machinery/kitchen/gibber.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Rebalances the meat the gibber produces (50 slabs per large creature what)
Allows meat made from gibber to inherit genetics information.
/:cl:

Reintegrates the gibber with genetics

---

code/modules/organs/blood.dm
code/modules/reagents/reagents/drugs.dm
code/modules/reagents/reagents/other.dm

-Fixes Nosfernium OD to effect it instead of Sanguinium
-Alters effect to allow any type or race of blood to be used on the holder.
-Thanks to Lilly and Sieg for looking at the code to figure out what I was having issiues with.

Nosfernium effect change

---

code/game/objects/effects/decals/Cleanable/humans.dm
code/game/objects/effects/decals/cleanable.dm
code/game/objects/effects/decals/contraband.dm
code/game/objects/effects/decals/crayon.dm
code/modules/lighting/lighting_overlay.dm
code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
code/modules/mob/living/carbon/superior_animal/defense.dm
code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm
code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
code/modules/mob/living/carbon/superior_animal/robots/robot.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/custodian.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/superior_defines.dm
code/modules/mob/living/simple_animal/simple_animal.dm

Makes fire proof mobs fully fire proof
Techinnally fixes an armor stacking on fire bots (No wounder lasers were worthless on them)
Improves optimizations in mob code
Ruins blood as now it drys via a timer
Better codeing standerds in random files

Small optimizations

---

code/__HELPERS/game.dm
code/modules/mob/death.dm
code/modules/mob/living/carbon/superior_animal/attack.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
code/modules/mob/living/carbon/superior_animal/nanobot/life.dm
code/modules/mob/living/carbon/superior_animal/roach/life.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/living_powers.dm
code/modules/mob/mob_helpers.dm

title. this fucking sucks. im at the limit of my sanity because i just discovered this entire issue is because of the fact that mobs are INCONSISTANTLY getting ai_inactive set to false from superior mob death to base death
its so goddamn cursed
no energy to test it, but it doesnt runtime at least
:cl:
fix: hopefully fixes mobs sliding while dead
/:cl:

a godawful dirty fix for mobs following you while dead

---

code/game/jobs/job/job.dm

:cl:
Makes changes to unused back end as requested by Trilby.
/:cl:

Tweaks For Cat
