code/modules/sanity/sanity_mob.dm
Sanity currently adds almost nothing to the game except for arbitrary, permanent OOC annoyance mechanics, for almost no reason than to punish the crime of existing and to mechanically justify murder, violence, and murderviolence. Until such a time as it can be reworked into a mechanic that isn't incredibly un-fun for all but like, three people, ya-YEET!
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Disables sanity system (does not remove)

code/datums/autolathe/biomatter.dm, code/datums/autolathe/parts.dm, code/datums/autolathe/tools.dm, code/game/objects/items/weapons/autolathe_disks.dm
Adds salt, pepper NT belts to the NT disk
Adds Advs welders to the Adv tool disk
Adds Oxyjet to tool mod pack
:cl:
add: Salt, pepper NT belts to the NT disk
add: Advs welders to the Adv tool disk, Oxyjets to tool mods
/:cl:
=> adds salt, pepper, adv welder, oxy jets and nt belt to disks

code/datums/autolathe/biomatter.dm, code/datums/autolathe/parts.dm, code/datums/autolathe/tools.dm, code/game/objects/items/weapons/autolathe_disks.dm
Reverts sojourn-13/sojourn-station#3
Whoops. It looked fine but it seems like it needs a fix.
=> Revert "adds salt, pepper, adv welder, oxy jets and nt belt to disks"

config/example/config.txt
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Adds an example line for HUB_VISIBLE into the example config.

code/datums/objective/merc_mission.dm, code/modules/admin/player_notes.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fixes player notes not writing.

html/changelog.html
=> New Changelog

code/game/jobs/job/church.dm, code/game/machinery/vending.dm, code/game/objects/structures/crates_lockers/closets/job_closets.dm, code/modules/core_implant/cruciform/modules.dm, code/modules/hydroponics/trays/tray_soil.dm, code/modules/mining/machine_processing.dm, code/modules/mining/machine_stacking.dm, code/modules/mob/living/simple_animal/friendly/cat.dm, code/modules/modular_computers/file_system/programs/engineering/shield_control.dm, code/modules/modular_computers/file_system/programs/medical/chem_catalog.dm, code/modules/reagents/machinery/grinder.dm, code/modules/research/designs/cell.dm, code/modules/stashes/stash_items.dm, maps/CEVEris/_Nadezhda_areas.dm
=> Mild code fixes.

code/ATMOSPHERICS/he_pipes.dm, code/modules/xgm/xgm_gas_mixture.dm
Removes some offensive words.
Just being careful and covering our asses.
=> Think Of The Children

code/game/objects/items/weapons/cigs_lighters.dm, code/modules/reagents/reagents/food-Drinks.dm, code/modules/reagents/reagents/stims.dm
=> Some cig improvements.

code/game/objects/structures/signs-neon.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Quick Neon Sign Fix

code/game/objects/structures/crates_lockers/closets/secure/militia.dm, code/modules/clothing/under/jobs/security.dm
<details>
<summary>
Adds a cavalry hat variant to the Militia Commander's locker.
</summary>
<hr>
<hr>
</details>
:cl:
add: hat to locker
/:cl:
=> Militia Commander Cavalry Hat Variant

code/modules/mob/mob.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fixes the issue where you can examine your hud.

code/controllers/subsystems/vote.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Admin only vote fix

code/datums/autolathe/biomatter.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Biomatter cardboard - now gets 5-50 sheets instead of 1

code/__HELPERS/manifest.dm, code/controllers/subsystems/economy.dm, code/game/machinery/cryopod.dm, code/modules/modular_computers/file_system/programs/generic/records.dm, code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm, code/modules/modular_computers/file_system/reports/crew_record.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Makes crew records vanish when someone cryos

code/_onclick/hud/hud.dm, code/_onclick/hud/screen_objects/base_screen_objects.dm, code/modules/clothing/glasses/glasses.dm, code/modules/clothing/glasses/powered.dm, code/modules/clothing/glasses/thermal.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fixes issue where nightvision overlay could be weird

code/controllers/subsystems/ticker.dm, code/modules/modular_computers/file_system/reports/crew_record.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Adds some debug logging for record creation.

code/__HELPERS/manifest.dm, code/controllers/subsystems/economy.dm, code/game/machinery/cryopod.dm, code/modules/modular_computers/file_system/programs/generic/records.dm, code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm, code/modules/modular_computers/file_system/reports/crew_record.dm
Reverts sojourn-13/sojourn-station#68
=> Revert "Makes crew records vanish when someone cryos"

code/game/mecha/mecha.dm
Fixes mechs being unable to be recalibrated.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Actual mech fix (hopefully)

code/world.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Updates the hub text

code/world.dm
Reverts sojourn-13/sojourn-station#97
=> Revert "Updates the hub text"

code/game/machinery/autolathe/fabricators.dm, code/game/objects/items/weapons/circuitboards/machinery/research.dm, code/modules/client/preference_setup/loadout/lists/uniforms.dm, code/modules/mob/living/simple_animal/hostile/big.dm, odessa-outpost.dme
=> Dumb shit fixes

code/game/machinery/autolathe/fabricators.dm, code/game/machinery/excelsior/implantmaker.dm, code/game/objects/items/weapons/circuitboards/machinery/research.dm, code/modules/core_implant/core_implant.dm, code/modules/core_implant/cruciform/cruciform.dm, code/modules/projectiles/guns/energy/toxgun.dm, code/modules/projectiles/projectile/energy.dm, code/modules/projectiles/projectile/plasma.dm
Because the existing version sucked.
=> Plasma Pistol Changes

code/modules/projectiles/guns/energy/toxgun.dm, code/modules/projectiles/projectile/plasma.dm
Little longer cooldown on the impact shot but now it sends people flying.
=> Slight tweak to plasma pistols

code/datums/outfits/jobs/medical.dm, code/game/jobs/job/captain.dm, code/game/jobs/job/church.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/prospector.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/game/jobs/jobs.dm, code/game/objects/items/weapons/storage/belt.dm, code/modules/multiz/map_data.dm, code/modules/projectiles/guns/energy/stun.dm, code/modules/tips_and_tricks/jobs.dm
Replaces chemist with orderly and removes bonus languages based on jobs.
=> Orderly Update

code/modules/client/preference_setup/loadout/lists/factionsoteria.dm, code/modules/projectiles/guns/energy/toxgun.dm
Plasma pistol now properly fits a holster, orderlies can now select soteria equipment in the load out screen.
=> Minor Fixes

code/datums/autolathe/biomatter.dm, code/datums/perks/perk.dm, code/game/objects/items/weapons/autolathe_disks.dm, code/game/objects/items/weapons/storage/pouches.dm, code/modules/reagents/reagents/medicine.dm
Fixed the Naramad perk which was broken due to a typo and removes the deactivation chat code to prevet an improper display.
=> Perk Bugfixes

code/game/objects/items/devices/defib.dm, code/world.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Hub text again, defib overlay

code/game/objects/items/devices/defib.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Slight fix for me being retarded.

code/modules/hydroponics/seed_controller.dm, code/modules/hydroponics/trays/tray.dm, code/modules/hydroponics/trays/tray_process.dm
<details>
I made a PR to hydro before on eris and decided to bring it back here, it might need some more tweaking to better fit coding standard here
<summary>
Diehltymine will now boost the potency of the plant until its level 100
Water consumption of plants is halfed
PLant genes are no longer random stuff everytime. They say outright what they are
</summary>
<hr>
seed controler tweaked to unobfuscate (kinda hacky)
tray tweaked to boost potency of plants and half water consumption. Also health var is fixed now
<hr>
</details>
:cl:
add: Added new things
add: diehtlymine will now boost plant potency, needs better tweaking
tweak: plant genes are no longer obfuscated
tweak: plants consume nearly not as much water as before
code: plant health var fixed
/:cl:
=> Porting my hydro PR from eris

code/modules/projectiles/guns/energy/plasma.dm
The brigador had too much ammo, reduced it by 50% and changed one of the firing noises.
=> Slight Balance Tweak

code/game/objects/items/weapons/storage/pouches.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/energy/plasma.dm, code/modules/projectiles/guns/energy/toxgun.dm, code/modules/research/designs/weapon.dm, code/modules/research/nodes/combat.dm
=> Minor display fixes.

code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
<details>
<summary>
Corrects a minor oversight by adding the already coded/sprited security gorka pants to loadout. Also opens up the loadout to the sergeant.
</summary>
<hr>
<hr>
</details>
Add: Security gorka pants are now in security loadout
Tweak: Sergeant can access loadout options.
=> Adds security gorka pants to loadout options

code/modules/projectiles/guns/projectile/automatic/ak47.dm
=> ak47 sawn off fix.

code/modules/cargo/packs_security.dm, code/modules/clothing/spacesuits/syndi.dm, code/modules/clothing/spacesuits/void/merc.dm
=> Voidsuit hotfix.

code/datums/craft/recipes/guild.dm, code/game/machinery/adv_med.dm, code/game/objects/items/devices/scanners/health.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/mob.dm, code/modules/organs/external/_external.dm, code/modules/organs/external/subtypes/robotic.dm, code/modules/organs/wound.dm, code/modules/reagents/reagents/drugs.dm, code/modules/surgery/autodoc.dm, code/modules/surgery/wound_repair.dm
Some balance changes. Removed IB and
=> Removed IB and made synthetic limbs stronger.

code/game/machinery/vending.dm
Simply adds in the rifle cases into the vendor for 150 cr so that people that fine the Sike or Roe dont brake the law
:cl:
add: The Marshal Portable Armory vendor now stocks rifle cases for the low price of 150cr! Safely store you gun today!
/:cl:
=> Adds rifle cases to Marshal Portable Armory vendor

code/game/objects/structures/flora.dm, code/modules/reagents/reagents/stims.dm, code/modules/reagents/reagents/toxins.dm
=> Some label fixes

code/datums/autolathe/ammo.dm, code/modules/projectiles/ammunition/magazines.dm
Fixes them so they can be printed
:cl:
fix: Code side bug that prevents making the SBAW HEFI mag
/:cl:
=> Corrects 20mm SBAW HEFI mag

code/game/objects/structures/burrows.dm
=> Slight adjustment to the values of maint ladders.

code/modules/research/designs/weapon.dm, code/modules/research/nodes/biotech.dm
<details>
<summary>
</summary>
<hr>
Allows for syringe gun ammo to be printed once the research is complete.
<hr>
</details>
:cl:
=> allows for syringe ammo to be printed

code/modules/mob/living/simple_animal/hostile/syndicate.dm
=> Fix for syndies.

code/game/objects/items/devices/scanners/plant.dm
=> Hotfix for Plant Analyzer

code/game/machinery/autolathe/autolathe.dm
=> Autolathe Hotfix

code/modules/research/nodes/biotech.dm
fix: Corrects RnD ID name so that it dosnt eat others
=> Rnd Hot Fix

code/datums/perks/job.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/guild.dm, code/game/objects/items/oddities.dm, code/game/objects/items/toys.dm, code/modules/economy/cash.dm
It may be causing a crash, also fixes some typo's in the toys for lonestar.
=> Disables time is money

code/modules/economy/cash.dm
=> Commented out the defines.

code/datums/setup_option/backgrounds/origin.dm, code/game/objects/items/stacks/tiles/tile_types.dm
=> Origin Rebalance

code/modules/mob/living/simple_animal/hostile/big.dm, code/modules/mob/living/simple_animal/hostile/creature.dm, code/modules/mob/living/simple_animal/hostile/misc.dm, code/modules/mob/living/simple_animal/hostile/pirate.dm, code/modules/mob/living/simple_animal/hostile/syndicate.dm, code/modules/mob/living/simple_animal/simple_animal.dm
All mobs now drop meat, yay
Void wolfs now drop human meat, and will drop their weapons like they are meant to
:cl:
add: All mobs now drop meat, yay
fix: Void wolfs now drop human meat, and will drop their weapons like they are meant to
/:cl:
=> Fixes and now we dont have to deal with 3000 undealable bodys Also Void wolfs now drop things they are meant to drop

code/game/machinery/vending.dm, code/modules/mob/living/bot/cleanbot.dm
Cleanbots now like painting... Yay?
Venders that would within reason sell you welding fuel cans/packs now do
:cl:
add: Venders that would within reason sell you welding fuel cans/packs now do
tweak: Cleanbots now like painting... Yay?
/:cl:
=> Clean bot correction &  Vender buffs

code/modules/mob/living/carbon/human/emote.dm
There is an existing medic speechbubble in the code, so this simply makes use of it.
<hr>
</details>
:cl:
add: medic emote
/:cl:
=> Adds a Medic emote

code/modules/mob/living/simple_animal/hostile/pirate.dm
All ranged fokes are now ranged
Proper ammo and guns are used
They also relied that weapons are good
:cl:
fix: The Void Wolf Training has been paying off sadly and they know how to use their guns in things other then melee!
fix: Void Wolf Relied that their guns are not light falls but cogs, martins and Spider roses for each person.
fix: Void Techies now do to their new training relies they are using lesser gear in melee same with rang only Voiders
/:cl:
=> Void Volfs fixes

code/game/machinery/Sleeper.dm, code/modules/research/nodes/biotech.dm
Sleepers now have the chems they are meant to have
RnD Node now has the correct designs
=> Sleeper And Rnd Fixes

code/game/turfs/simulated/floor_static.dm
Water in the hydro-dam thing, is now 0c and wet
:cl:
tweak: Water in the hydro-dam thing, is now 0c and wet
/:cl:
=> Colder cold

code/game/objects/items/weapons/storage/boxes.dm
N/A
Just makes some quotes into to '' so master complies ''
=> Fixes master

code/game/machinery/portable_turret.dm
Makes grayson turrets have cogs rather then lightfalls
:cl:
tweak: Makes grayson turrets have cogs rather then lightfalls
/:cl:
=> Makes grayson turrets have cogs rather then lightfalls

code/modules/mob/living/carbon/human/human_damage.dm
It now requires you to have a total burn greater than 400.
=> Fixing Husking

code/modules/mob/living/bot/drillbot.dm
God damn you Eris
:cl:
fix: Drill bots now look like any normal engi greyson bot
/:cl:
=> Drill bots get sprites now

code/game/objects/items/weapons/secdocs.dm
Removes two unlogical/not friendly with lore tags 
Adds in 5 new names that can be pulled
=> Secdoc fluff

code/datums/perks/job.dm, code/modules/mob/living/carbon/human/life.dm
The obelisk now gives you a message when it adds the perk, also made LP 50%.
=> Perk Hotfix.

code/game/objects/items/weapons/tools/simple_weapons.dm
Some not all knifes + matches can now cut down trees
:cl:
fix: Some not all knifes + matches can now cut down trees
/:cl:
=> Makes knifes and matches be able to saw down trees

code/__DEFINES/perks.dm, code/datums/perks/racial.dm, code/datums/setup_option/backgrounds/origin.dm, code/game/objects/effects/spiders.dm, code/modules/research/xenoarchaeology/tools/tools_anoscanner.dm
What it says on the tin. Added a chtmant background and improved the nt_sword.
=> Joyeuse and Chtmant Spider Perk

code/game/machinery/lightswitch.dm
Sanity has been added
Flicker the worst thing ever now is a 1%
Auto turn on now lasts 30 mins
Manual turn on lasts 90 mins
=> Less Annoying Lights

code/game/objects/structures/salvageable.dm
Maybe its not a good idea to get 30~ disks with one ruin
:cl:
Lowers Grayson RnD disks odds for the consoles 
/:cl:
=> Lowers RnD disks from lonestar consoles

code/datums/autolathe/guns.dm, code/datums/autolathe/parts.dm, code/datums/autolathe/tools.dm, code/game/objects/items/weapons/autolathe_disks.dm, code/game/objects/items/weapons/stock_parts.dm, code/game/objects/random/lathe_disks.dm, code/game/objects/structures/salvageable.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/research/designs/cell.dm, code/modules/research/designs/circuits.dm, nano/css/shared.css
You can now get grayon disks from the onestar things
Fixes lack of tools in grayon tool disk + Grayson mod
Adds grayson stock part disk
Adds cog gun disk
Corrects Roe and Sike being swapped
Ups grayson tech to be ya know, good
Adds platium into each grayson stock part to prevent easy mass making
Misc Rnd grammar/naming fixes as well
:cl:
/:cl:
=> Grayson Disks

code/game/objects/items/weapons/tools/misc.dm
=> Clean the grammer

code/game/objects/items/weapons/paint.dm
Adds subtypes of each paint colour for later/admin spawning when they want to do some miner Event stuff or pixel art
:cl:
/:cl:
=> SM Paint for admins

code/game/machinery/Sleeper.dm, code/modules/reagents/machinery/chem_dispenser.dm, code/modules/reagents/machinery/grinder.dm
Upgrading Dispensers with better parts now does stuff other then faster/more charge!
All Dispensers can be hacked
Sleepers now relies on their scanners for filtering out blood!
Maybe fixes that one bug with the sleepers being able to upgrade loop themselfs
:cl:
/:cl:
=> Usefull Dispensers upgrades!

code/__DEFINES/perks.dm, code/datums/perks/oddity.dm, code/modules/mob/living/carbon/human/human_damage.dm, code/modules/mob/living/carbon/human/human_movement.dm
Off the bad, toxic ghost is now Fungal Host, 100% just less magic/curses
10 new untested perks that likely dont work
These new perks without spoiling to much can range from - 
Just basic stat buffs/debuffs of 5 or -5!
Movement speed slowers
More easy to get addicted to Chems
More Toughness other then your stats!
More Toxic resistant 
Those that walk the line on being able to use /some items/ may now fear even more so the perks that the oddity give~
Main goal is to not have the 3/4 be all good and such and to lower the odds of that fucken toxic perk god damn it Kaz its shit and should be reworked to not be less intrusive in RP.
:cl:
/:cl:
=> 10 more perks! - + Toxic ghost rebranding

code/__DEFINES/perks.dm, code/datums/perks/oddity.dm, code/modules/mob/living/carbon/human/human_movement.dm
Fixes and adjustments to weight it better for positive outcomes.
=> Perk Adjustments

code/datums/perks/job.dm, code/modules/scrap/scrap.dm
Also adds a loss text for true faith.
=> Scrap Hotfix

code/__DEFINES/perks.dm, code/datums/autolathe/guns.dm, code/datums/perks/oddity.dm, code/game/objects/items/weapons/autolathe_disks.dm
Code side fixes - better_toxins being used rather then it being its old retired lable
.40 church pack remaned to Thorn and Rose mk58 pack
Added .35 ammo to the now renamed pack
Corrects .35 Thorn from being named .40 Thorn
:cl:
/:cl:
=> Misc fixes

code/modules/reagents/recipes.dm
Included recipes for Gold Solidification and Uranium Solidification at the exchange rates commonly found on other servers. This is after several IC conversations among Soteria talking about Frost Oil but it was never coded in.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Gold and Uranium Solidification

code/game/objects/structures/watercloset.dm
Let me hide my spare ID god damn it - Joking
Maybe fixes toilets
=> fixes toilets

code/game/machinery/biogenerator.dm
Should now let us upgrade and decon the biogen
:cl:
/:cl:
=> Bio gen fix

code/game/objects/structures/medical_stand.dm
I was going to do this anyway I just didnt know what numbers to use
Saw Eris had a pr and might as well use the same ones
`https://github.com/discordia-space/CEV-Eris/pull/5197`
I found the long ass timer while placing the medical stand's gas mask on people during surgery a little annoying.
It's basically a small QoL tweak for medbay staff and the people that get surgery.
tweak: Placing gasmask and IV needles on people should be faster now.
=> Ports Eris's #5197 - Medical stands should be faster now

code/modules/mob/living/simple_animal/hostile/big.dm, code/modules/mob/living/simple_animal/hostile/misc.dm
=> Mob adjustments.

code/game/machinery/biogenerator.dm
Better matteral bins lets us hold more in the bio gene
Fixes bad else if statments, like really silly ones
Adds more notes so people can understand the code better
:cl:
/:cl:
=> Updates Bio-generator to be better

code/game/jobs/department.dm, code/modules/mob/living/silicon/ai/ai.dm, code/modules/mob/living/simple_animal/hostile/big.dm
=> Fixed a incorrect sound file and added languages to AI

code/game/verbs/ooc.dm
Im so sick of having to restart the game and wait 40 seconds every time to refresh my chat to maybe fix it.
Adds a new Ooc botton that fixes chat or at lests forces a reload! Stolen shamefully from TG
:cl:
/:cl:
=> Steals TG's fix chat ooc botton 

code/game/machinery/biogenerator.dm
Reverts sojourn-13/sojourn-station#279
=> Revert "Updates Bio-generator to be better"

code/game/machinery/biogenerator.dm
Reverts sojourn-13/sojourn-station#273
=> Revert "Bio gen fix"

code/modules/biomatter_manipulation/solidifier.dm
Reverts sojourn-13/sojourn-station#284
=> Revert "Update solidifier"

code/game/objects/effects/spiders.dm, code/game/objects/random/mob/spider.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
Hopefully these submits just the spider rebalances and not the whole carrion update since that is still being bug tested.
Just a minor balance fix.
=> Submitting just the spider changes.

code/game/objects/items/toys.dm
Toys now have a use and that is to be made into plastic
:cl:
add: Toys are now made of plastic
/:cl:
=> All toys can now be turned into plastic

code/modules/games/spaceball_cards.dm
Come on, its the current year. Ok?
=> Its the current year

code/modules/projectiles/guns/energy/laser.dm
=> Cog Hotfix

code/modules/research/designs/weapon.dm, code/modules/research/nodes/combat.dm
Star striker has been readded
firebreath ammo now prints ammo not projectil
:cl:
/:cl:
=> Re-adds star striker

code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
Cloaker spiders when death comes apond them will be normal 255 aphla to stop post-death eye strain
:cl:
/:cl:
=> Cloaker spiders no longer deal eye damage well dead

code/modules/cargo/packs_engineering.dm, code/modules/cargo/packs_security.dm, code/modules/projectiles/guns/mods/mods.dm
=> Mods and gun mods for cargo.

code/modules/cargo/packs_engineering.dm, code/modules/cargo/packs_security.dm
=> Some adjustments.

code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
Now spawns with 0 ammo - No more abusing that
Now is a normal size item - Ahaha better then normal carbine do not!
Now hold 3-1 shots as its meant to
NT spray fixed from refunding 30 of its 60 biomatter, wait it cant even hold 60! What the...
:cl:
/:cl:
=> Nerds on the Spot

code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
Moves the guns/mod from the bioprinter pack to bottom
Adds the laser pistol to the New Testament disk
Corrects church laser pistol  to not be broken
:cl:
/:cl:
=> Fixes Church pistol disk + qol

code/modules/reagents/reagents/medicine.dm
Clears more spider toxins,
Clears the chemical "toxin" from blood
:cl:
/:cl:
=> buffs Dylovene

code/modules/clothing/glasses/hud.dm
Someone just forgot to add in the flag to make them flash proof
:cl:
/:cl:
=> Sec flash proof huds are now flash proof

code/game/objects/items/devices/lighting/toggleable/flashlight.dm
Making a full pr for 1, **one** letter change that fixes checking eyes
:cl:
/:cl:
=> one syble change that fixes eye checking

code/game/objects/items/weapons/tools/simple_weapons.dm
Just an oversight that the normal one has it but not the nano one
:cl:
/:cl:s. -->
=> Nano Katana now has sawing when on

code/game/objects/structures/flora.dm, code/modules/hydroponics/grown.dm
Have you ever wanted to relive the potato famine? Ever want to go through the hardships of eating grass and random flowers you find well hunting down plants for biofuel? No? What about crushing rocks into sand dusts and other hard work for little gain? Still no... Then dont do any of these actions.
You can now cut down grass to get plant clipings
Crushing rocks now gives some sand - Yay!
You can harvest many of the once useless fluff around the jungle.
:cl:
/:cl:
=> Gardening and harvesting - Living off the land!

code/game/jobs/department.dm
=> Funding Fix

code/game/objects/structures/crates_lockers/closets/secure/militia.dm
=> Blackshield Locker Adjustment

code/datums/datacore.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/projectiles/projectile.dm, code/modules/projectiles/projectile/bullets.dm
=> Runtime Fixes

code/modules/research/designs/weapon.dm
You know if this is my only coding error thats really good
:cl:
/:cl:
=> Hot RnD laser omni shot fix

code/game/objects/structures/flora.dm
Should now drop its meant to be items
:cl:
/:cl:
=> flora hox fixes

code/modules/power/port_gen.dm
You can now take part packmans and upgrade them maybe. Yay.
:cl:
/:cl:
=> maybe makes pacmans better

code/modules/hydroponics/grown.dm
Plants now should have a icon that you cut from the ground
Plant cuttings and wild flowers now should have correct names as well
:cl:
/:cl:
=> plants are hard

code/modules/clothing/suits/storage.dm
Removes lots of misc runtimes
:cl:
/:cl:
=> Runtime-Code-Killer

code/game/objects/effects/decals/Cleanable/misc.dm
I got Kat5 to give me a bug fix
:cl:
/:cl:
=> Kfive coded this

code/modules/admin/bluespacetech.dm, code/modules/clothing/cloak/hooded.dm, code/modules/clothing/head/helmet.dm, code/modules/clothing/head/hood.dm, code/modules/clothing/shoes/miscellaneous.dm, code/modules/clothing/under/jobs/security.dm, code/modules/clothing/under/miscellaneous.dm
=> Runtime removal

code/modules/modular_computers/computers/modular_computer/core.dm
=> Kitten5 more like Fixing5 errors!

code/modules/admin/verbs/debug.dm
How did I forgot this? - No more naked Don
:cl:
/:cl:
=> the don now has a suit

code/modules/research/rdconsole.dm
Just rnd console consistency 
:cl:
/:cl:
=> Covert tech is covert

code/modules/projectiles/guns/projectile/pistol/mk58.dm, code/modules/projectiles/guns/projectile/revolver/detective.dm, code/modules/projectiles/guns/projectile/sniper.dm
It almost worked... Almost
:cl:
/:cl:
=> Forgots half the code in what makes a suppesser work

code/modules/reagents/reagents/medicine.dm
Makes clone/cryo chems heal much better.
=> Chem Hotfix

code/modules/power/solar.dm
Kaz this isnt even ported : <
Solors no longer get 10% but now 1% per upgrade tree
Corrects solar naming in code
:cl:
/:cl:
=> Nerds upgrading solars + afix

code/modules/mob/living/carbon/human/inventory.dm
<details>
<summary>
Allows you to pull a gun from suit storage with E.
</summary>
<hr>
<hr>
</details>
:cl: Lessie Evans
add: Quickdraw with E.
/:cl:
=> You can quickdraw a gun from suit storage with E.

code/modules/mob/say.dm
<details>
<summary>
You can press escape or cancel to exit a say box.
</summary>
<hr>
<hr>
</details>
:cl:
add: You can now escape out of a say box.
/:cl:
=> You can now escape out of a Say. Or press cancel.

code/game/objects/items/weapons/circuitboards/machinery/research.dm, code/modules/research/nodes/power.dm
2 manipulators in exosuit fabricator
:cl:
/:cl:
=> 2 manipulator Exosuit Fabricator

code/modules/mob/say.dm
Added automatic punctuation at the end of Say and Emotes.
=> Added automatic punctuation.

code/game/objects/items/weapons/autopsy.dm
Skill check is way to hard at 40
25 should be better
:cl:
/:cl:
=> Lowers autopsy scanner skill check

code/modules/mob/say.dm
=> Added cancel button to emote and subtle

code/modules/mob/say.dm
Reverts sojourn-13/sojourn-station#389
=> Revert "Added automatic punctuation."

code/modules/mob/say.dm
Reverts sojourn-13/sojourn-station#391
=> Revert "Added cancel button to emote and subtle"

code/modules/clothing/spacesuits/rig/rig_pieces.dm
=> Fixed the light rigsuit and its child's suitstorage

code/game/machinery/Sleeper.dm, nano/templates/sleeper.tmpl
Adds Stomach Pump functionality for sleepers, since there was no way for them, or actually in game (that didn't include a very specific vomit inducing chemical) to purge reagents out of someone's stomach.
<hr>
:cl: DimmaDunk
Adds Stomach Pump functionality for Sleepers.
/:cl:
=> Adds Stomach Pump functionality to Sleepers

code/modules/mob/say.dm
=> Added cancel to say and subtle. Added automatic .

code/datums/autolathe/circuits.dm, code/game/machinery/excelsior/ex_turret.dm, code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm, nano/templates/turret_control_artificer.tmpl
Title. Doing this because githubs a fucking cunt shit fuck and won't let me update without merging this.
=> Locking in my existing turret work and pushing it.

code/game/objects/items/bodybag.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/modules/research/designs/medical.dm, code/modules/research/nodes/biotech.dm, code/modules/tips_and_tricks/gameplay.dm, code/modules/tips_and_tricks/jobs.dm
Autosy scanners can now be made at sec disk, med disk and rnd
More helpfull tips to for medical
Rnd and med disks can make roller beds
New roller beds that are even more compact
:cl:
/:cl:
=> Medical qol 2 bagless aloo

code/game/machinery/excelsior/autolathe.dm
It can now be upgraded and destroyed without needing admins
=> excelsior boombox fix

code/modules/mob/emote.dm, code/modules/mob/living/say.dm, code/modules/mob/say.dm
<details>
<summary>
Fixed issues with pre defined emotes. Made it robust code.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Automatic punctuation, good code version.

code/datums/craft/recipes/guild.dm, code/game/jobs/job/engineering.dm, code/game/machinery/excelsior/ex_turret.dm, code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm, code/game/objects/random/mob/roach.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm, code/modules/mob/living/simple_animal/hostile/misc.dm, code/modules/mob/living/simple_animal/simple_animal.dm
=> Finished turrets and some bugfixes.

code/modules/tips_and_tricks/gameplay.dm, code/modules/tips_and_tricks/mobs.dm
Helpfull tips for chtmants and some other misc ones
:cl:
/:cl:
=> More tips n tricks

code/game/machinery/telecomms/broadcaster.dm, code/game/objects/items/devices/radio/radio.dm
Props channle is now cataloged to look back on radio messages from 30 years ago.
LoneStar radio got the new and hottest channles on the block
:cl:
/:cl:
=> Copy, radio fixes

code/modules/reagents/reagents/toxins.dm
Chtmants no longer will loose their spider friends if they eat the fuhrerole chemical, but will also not gain roach friendship
:cl:
/:cl:
=> fuhrerole fix maybe

maps/CEVEris/_Nadezhda_Colony_Underground.dmm
Moves some rather bad placed holo pads, adds loads more
adds some more cams to telecoms so AI can see inside
fixes medical pipe for cryo
gives CRO their locker back
evens out the medical sleepers to aline with the glass
adds telecoms access papers to CRO room GM Room Telecom Room and Captains Room
:cl:
/:cl:
=> More holo pads, telecom cams and fixes

code/modules/projectiles/guns/energy/laser.dm
Shell shock is in line with normal rail guns - yay its now viable! (I guess)
Some laser guns that didnt have the tag laser now have it,
:cl:
/:cl:
=> Gun tag fixes

code/modules/surgery/autodoc.dm
Hey Kids(!) are you sick and tired? Well now the AUTODOC is here to save YOU! Auto linking to the medcal funds but hey at a discount! Yay!
:cl:
/:cl:
Were all really poor
and these prices were never balanced for it
=> Affordable Privet Health Care

code/controllers/configuration.dm
=> Adminwho now shows moderators.

code/game/objects/structures/stool_bed_chair_nest/bed.dm
To exspensive for a non-refoldable bed
ups its plastic costs but removes the needed silver and gold
:cl:
/:cl:
=> Compact bed rebalance

code/game/gamemodes/events/money_lotto.dm
randomly getting 15k when everyone is meant to be poor is kinda odd...
=> Lottery is now also poor

code/modules/power/solar.dm
Makes upgrading soloars not legit useless now that they are again 50% less affective making them really not worth it
:cl:
/:cl:
=> Rebuffs solors upgrades

code/game/objects/items/weapons/power_cells.dm, code/modules/clothing/spacesuits/rig/modules/vision.dm, code/modules/clothing/spacesuits/rig/suits/light.dm, code/modules/research/designs/cell.dm, code/modules/research/designs/circuits.dm, code/modules/research/designs/illegal.dm, code/modules/research/designs/prosthesis_implants.dm, code/modules/research/designs/rigmodules.dm, code/modules/research/nodes/biotech.dm, code/modules/research/nodes/combat.dm, code/modules/research/nodes/engineering.dm, code/modules/research/nodes/illegal.dm, code/modules/research/nodes/power.dm
buffs hyper sci cells do to being the same as supper
new ultra light rig rnd makes weaker then their armor but hey it can add mods!
Fixes some bad names on cell
thermals and measons rig stuff added
fixes rnd fusion designs -again
For balance makes Vision Augmentation now costs 5k from 3k
Advanced Augmentations Biotech now has been also added to hold the more op bio stuff for latter game stuff.
:cl:
/:cl:
=> mostly fixes + some more blance with RnD

code/game/machinery/telecomms/broadcaster.dm
Telecoms board should now be seeable
:cl:
/:cl:
=> icon correction

code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/mob.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
fix: clothes now update wings, tail, and ears as necessary based on those flags
fix: The OOC Notes button now shows in the edge case when the flavor text existed but was very short.
/:cl:
=> Spawn bugs fix

code/game/objects/items/weapons/cigs_lighters.dm
no longer as big as a gas mask
:cl:
/:cl:
=> Pipes are smaller

code/game/objects/items/weapons/storage/deferred.dm, code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/projectile/bullettypes.dm
corrects buckshot doup hitting people for 300 damage if point blanked
fixes a few names on some mags/crates
:cl:
/:cl:
=> Bullet fixes and corretions

code/game/machinery/kitchen/microwave.dm
1-550-Come the heck on man, let use soap, any spray and rags to clean off some gunk : /
:cl:
/:cl:
=> Lets microwaves be cleaned with more then just a cleaner spray bottle

nano/templates/uplink.tmpl
Ports a fix pr from
``https://github.com/SyzygyStation/Syzygy-Eris/pull/94``
Helps pr such
:cl:
/:cl:
=> Ports uplink info fix

code/datums/craft/recipes/storage.dm, code/game/objects/items/weapons/storage/boxes.dm
Engi box now has MRE in it - They have to eat too you know...
Syringes box now can rapitly pick up things to help re-fill the box
:cl:
/:cl:
=> QoL Box buffing

code/modules/cargo/packs_clothing.dm, code/modules/cargo/packs_engineering.dm, code/modules/cargo/packs_hospitality.dm, code/modules/cargo/packs_hydroponics.dm, code/modules/cargo/packs_medsci.dm, code/modules/cargo/packs_mining.dm, code/modules/cargo/packs_operations.dm, code/modules/cargo/packs_randomised.dm, code/modules/cargo/packs_supply.dm
Re-balances mat imports to not be to much for non-heads to buy ,
Adds loads more crates
Buffs mining crates
Moves a lot of things into clothing, from ops
Moves a bit to other lesser filled sections
Adds in enzyme and sugar to cooking crate
:cl:
/:cl:
=> Cargo buffs

code/modules/stashes/stash_datum.dm
Fixes a runtime caused by faulty logic in the stash spawner code. Thanks to @Timberpoes for helping me.
A bunch less runtimes during initialisation.
=> Fixes a runtime due to a null value during a stash creation.

code/game/machinery/autolathe/autolathe.dm, code/game/objects/items/weapons/circuitboards/machinery/research.dm, code/modules/research/designs/circuits.dm, code/modules/research/nodes/engineering.dm
Industrial printer now has 2 manips 2 lasers added in
upgrading matter bins in an autolathe will give it more max queue
Changed the name from industrial printer to industrial autolathe
:cl:
/:cl:
=> More queueing and parts

code/game/machinery/Sleeper.dm, code/modules/reagents/machinery/chem_dispenser.dm
Makes when hacking the chem dispensers not double tell
Makes upgrading the sleeper, more easy as now it will upgrade its scanning level as well as properly upgrade its reagents.
replaces second level 1 chem with cryptobiolin from a doup chem
:cl:
/:cl:
=> Cleans up dispener code

code/game/objects/random/tools.dm
GM only gets ***1*** Flex tape role in their locker, thats IT
Its an admin tool that has been showed to be abused in some artifacts to get 20+ sat buffs.
:cl:
/:cl:
=> Removes flex tape form in game RnG spwans

code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm, code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Church disks now are consistant with other disk
Fixes the .257LMG having wrong ammo and not many prints
Gives some pluse gun disk more prints
Many gun disks have upgraded amount of prints to help them get some ammo
:cl:
/:cl:
=> Disk tooning

code/game/objects/items/weapons/circuitboards/machinery/chemestry.dm
Ya can now tell what dispender type it is by the board rather then making it and hoping its the right type
:cl:
/:cl:
=> Clears up dispender names

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Caliber was wrong, I blame sci-blue cat
:cl:
/:cl:
=> changes 7.5 gun disk to use 7.5

code/modules/mob/emote.dm, code/modules/mob/living/carbon/human/emote.dm, code/modules/mob/say.dm
<details>
<summary>
Conceals the content of the subtle verb from ghosts - for when players really only want those close by to see.
Logs are still created as appropriate.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Makes the subtle verb hidden to ghosts

code/game/objects/items/weapons/tools/mods/mod_types.dm
Woops forgot to add in the gun tag for the two other ones, spikes on all guns is intented tho.
:cl:
/:cl:
=> Fixes sharpender and diamond blade working on non-knifed guns

code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm, code/modules/mob/living/carbon/superior_animal/roach/life.dm, code/modules/mob/living/carbon/superior_animal/roach/roach.dm, code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm, code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm, code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm, code/modules/mob/living/carbon/superior_animal/roach/types/support.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Roaches will now eat bodies of non-humans MUCH faster will still taking the normal 15 mins to eat a normal human body
Roaches get more food out of eating making them lay more eggs
Roaches can now get revived more then once, Not Furhrer's tho, they get one life still (tanky guys ya know?)
Many roach health and damage is upgraded, making them just a little bit stronger
:cl:
/:cl:
=> Roach buffs

code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, code/modules/reagents/reagent_containers/food/snacks/meat.dm
<details>
<summary>
Created new meat types for emperor, queen and recluse spiders containing their signature venom. Numbers can be changed to balance and adjust this. It should make it more worth it to bring the meat back. 
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Spidermeat

code/game/machinery/Sleeper.dm
Corrects sleepers getting Alky at level 3 - A Exl unlock
Adds in level 5(For alien stock parts)
More commits to help people read the code
:cl:
/:cl:
=> Sleeper Upgrade fixes

code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/living/silicon/robot/robot_upgrades.dm, code/modules/reagents/reagent_containers/borghydro.dm, code/modules/research/designs/robot_parts.dm, code/modules/research/nodes/biotech.dm, code/modules/research/nodes/robotics.dm
Makes medical borg have their space cleaner for surgery and cleaning up their tools
adds 2 more medical borge upgrades
Adds more chems to their hypo, needs robotics
:cl:
/:cl:
=> More Medical borg stuff

code/game/objects/effects/spiders.dm
Corrects meleeing webs so you can again remove them with melee
:cl:
/:cl:
=> Correct web melee

code/game/objects/effects/spiders.dm
Spider weavers no longer drop 30 silk cods
this idea was a misstake
:cl:
/:cl:
=> Corrects what I thought was stacksize

code/modules/projectiles/ammunition/bullets.dm
new laser bullets now cost gold and silver like the others
:cl:
/:cl:
=> RnD corrections

code/datums/autolathe/guns.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
.35 SMG lethal mags are no longer free - my bad
The bore disk now longer is broken + has the red dot design on it now
:cl:
/:cl:
=> more gun disk corrections

code/modules/recycling/sortingmachinery.dm
QoL you can turn off chute sounds
:cl:
/:cl:
=> You can now turn off the chute sounds

code/datums/autolathe/guns.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/game/objects/items/weapons/autopsy.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/modules/projectiles/guns/mods/mods.dm
Clear up uses for cop blocks
adds cop blocks to sec-disk
fixes wound scanners being free
makes cop block insta add to a gun to give it tactical use for combat
:cl:
/:cl:
=> Cop block buffs

code/game/objects/effects/decals/Cleanable/humans.dm, code/modules/reagents/reagents/other.dm
ports  - https://github.com/SyzygyStation/Syzygy-Eris/pull/216
:cl:
/:cl:
=> Ports cleaning fixes

code/game/mecha/equipment/tools/tools.dm
Mechs really should be able to load up a bunch of junk and move it around with a mech
:cl:
/:cl:
=> Allows mechs to pick up trash piles and salvageable

code/modules/projectiles/guns/energy/stun.dm
Was pointed out to me that the taster modes were rather confusing and un-helpfull in telling what they are
:cl:
/:cl:
=> Better taser mode names

code/game/objects/items/devices/organ_module/active/armblades.dm, code/modules/clothing/glasses/shades.dm
TECH _COVERT isnt a thing  TECH_ILLEGAL is
/:cl:
=> corrects "covert tech" being wrong

code/game/objects/items/weapons/melee/energy.dm
- Adds tool qualities to the energy armblade, allowing it to be used in the same ways as the energy cutlass, in particular allowing butchering of corpses.
- Increases the force of the weapon to match the associated comment (wielded fire axes use WEAPON_FORCE_BRUTAL, not ROBUST).
:cl:
fix: added missing tool qualities to energy armblade.
balance: increased damage of energy armblade.
/:cl:
=> Fix and improve energy armblade.

code/modules/dungeons/procedural/deepmaint.dm
Adds in 2 more big rooms
Adds in 10 more smoller room
Should make deep maints a bit more longer and fun for people that like to slowly push through clearing things + more mazy maybe
:cl:
/:cl:
=> Makes deep maints a bit bigger

code/modules/client/preference_setup/loadout/lists/uniforms.dm
Adds after a request the black suit skirt to loadout
:cl:
/:cl:
=> Adds black suit skirt to loadout

code/modules/mob/living/carbon/superior_animal/roach/life.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Fixes the once broken loop timer thing of roaches eating bodies
:cl:
/:cl:
=> Roach eating fix

code/modules/mob/living/carbon/superior_animal/roach/life.dm
=> lowers roach body from eating one a other

code/game/objects/items/weapons/swords_axes_etc.dm
On help intent they deal halloss bit more
On disarm intent deals less  halloss but more AP
On Grab deals base damage
On harm deals quite a bit damage
:cl:
/:cl:
=> Wooden Batons and telebatons are good now

code/modules/cargo/packs_medsci.dm, code/modules/cargo/packs_security.dm, code/modules/projectiles/guns/energy/plasma.dm
Fixes the Cassad spawn
Fixes an explote with a crate
Added in 3 crates with each type of STS
:cl:
/:cl:
=> cargo gun tweaks

code/game/mecha/equipment/tools/tools.dm
Speeds it up to 200% drilling speed
Makes the drill force in melee not be out classed by a wrench
:cl:
/:cl:
=> Makes mech diamond drills more better

code/datums/craft/recipes/misc.dm, code/datums/craft/recipes/storage.dm
You can now craft each type of basic bag from ore, to chem
Moved the plastic bag to storage tab
:cl:
/:cl:
=> Bag crafting!

code/game/objects/items/devices/organ_module/passive/muscle.dm
With code thats been broke for years, the numbers and such are also rather brokenly high. Nerfs each leg slot to be a max of .30
buff rather then .70 tally
:cl:
/:cl:
=> Nerfs musle implants by 20%

code/game/gamemodes/storyteller.dm
11 people sitting in lobby with 4 people ready but no command or engi should run anyways when legit still low pop.
:cl:
/:cl:
=> 15 is low pop

code/global.dm, code/modules/admin/verbs/custom_event.dm, code/world.dm
<details>
<summary>
Adds verbs that let the server ad be altered in config and at runtime.
</summary>
<hr>
<hr>
</details>
:cl:
add: The server's ad can now be set in config.
admin: Can now change the server's ad on the pager.
/:cl:
=> The pager can now be set in config or updated by admins.

code/modules/modular_computers/NTNet/NTNet_relay.dm
NTNet Relays can now be deconed and upgraded
:cl:
/:cl:
=> NTNet relay decon fix

code/modules/mining/ore.dm
Slag and rocks are now only things that can be crushed into smaller ore
:cl:
/:cl:
=> Stops ore doups

code/game/objects/items/weapons/mine.dm
Mines no longer check mobs that cant have antag defins
:cl:
/:cl:
=> Mines no longer runtime on mobs

code/modules/clothing/spacesuits/void/station.dm
Most void suits that should have a small light now have one, mining type has a bigger light
:cl:
/:cl:
=> Void suits lights

code/modules/mob/living/bot/secbot.dm
Buffs sec bot to not get 1 shot by basic bullets
Makes secbot attack roaches/spiders and deal more
:cl:
/:cl:
=> Best bot is sec bot

code/modules/projectiles/guns/projectile/automatic/luger.dm
Sieg pointed out this small Error
:cl:
/:cl:
=> metal to steel

code/modules/projectiles/guns/projectile/revolver/revolver.dm
Removes funny endless spinning that was not intented
:cl:
/:cl:
=> spin to fix

code/modules/mining/mine_turfs.dm
Mineral walls should now be layered properly
:cl:
/:cl:
=> Layer listing fixes

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
I hate rifle and lrifle and hrifle are the autolathen code
:cl:
/:cl:
=> makes zatvor disk have correct ammo

code/game/objects/structures/burrows.dm, code/modules/mining/mine_turfs.dm, code/modules/projectiles/guns/energy/decloner.dm, code/modules/research/designs/devices.dm, code/modules/research/designs/illegal.dm, code/modules/research/designs/medical.dm, code/modules/research/designs/prosthesis_implants.dm, code/modules/research/designs/stock_parts.dm, code/modules/research/designs/structures.dm, code/modules/research/designs/weapon.dm
- Shortens the descriptions of "<items> of Holding" so that they fit better on the interface
- Adds proper (short) names for items on the RND console so that they fit and are able to be read instead of including the cathegory and the item's internal name
-Renames the "Biological demolecularisor" to the proper "Demolecularizer" since it made no sense
- Fixes a double "the" on a message when failing to collapse burrows
- Adds proper capitalization
- Fixes typo on "braking" geodes out of minerals
<hr>
:cl:DimmaDunk
tweak: Biological demolecularisor renamed to "Biological Demolecularizer"
spellcheck: fixed a few typos
/:cl:
=> Smallfixes

code/modules/projectiles/guns/projectile/automatic/ppsh.dm
One day will add in a gun correctly
:cl:
/:cl:
=> ppv icon fix

code/game/objects/items/weapons/tools/simple_weapons.dm
Fix a typo I saw in the Makeshift Kata's description.
=> Fix a typo

code/game/mecha/mecha_wreckage.dm
All mech wrecks can be sawn down into steel/plasteel/plastic/glass as thats what makes them
:cl:
/:cl:
=> Mech wrecks can now be sawn down into bits

code/game/objects/effects/decals/weldable.dm
Makes welding the cracks small bit faster
Makes it so hammers have a new use, hammering out cracks, takes longer then weldering and can mess up more, but hey now at lest you got a reason to smack the ground!
:cl:
/:cl:
=> You can now hammer out cracks

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Im so bad at names it amazes me how i keep my own
:cl:
/:cl:
=> makes exl gun not be in blackshield disk

code/modules/modular_computers/NTNet/NTNet_relay.dm
Propperly adds in wire and board now
:cl:
/:cl:
=> Fix with NTNet relay

code/modules/modular_computers/computers/modular_computer/core.dm, code/modules/modular_computers/computers/modular_computer/variables.dm, code/modules/modular_computers/computers/subtypes/dev_laptop.dm, code/modules/modular_computers/computers/subtypes/dev_telescreen.dm, code/modules/modular_computers/file_system/programs/antagonist/uplink.dm, code/modules/modular_computers/terminal/terminal.dm, code/modules/modular_computers/terminal/terminal_commands.dm
Emaging labtops and telescreens will now upgrade their bitflag to console for even more programs to download and terminal access...
Added firewall check to see if something is emaged or just disk/P2P downloaded
:cl:
/:cl:
=> Firewall check and better uplinking

code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/closets/maint_loot.dm, code/game/objects/structures/crates_lockers/closets/syndicate.dm, code/game/objects/structures/crates_lockers/closets/utility_closets.dm
Old lockers can now also be locked! This should give more reason to have a multy tool on you.
Synda lockers now need synda access
Fire Fighting lockers now have a inflatable door and a kit for burns
:cl:
/:cl:
=> Access locked loot

code/modules/organs/internal/blood_vessels.dm, code/modules/organs/internal/nerves.dm
blood veins from blood vessel 
nervous linking from nerve
+ nerve having size of 0.5
:cl:
/:cl:
=> Better organ names

code/game/objects/structures/salvageable.dm
Imagine WANTING to power the station with scap man but stats said no.
:cl:
/:cl:
=> Makes having high mech and cog stat ruin guild techs

code/game/objects/structures/crates_lockers/closets/utility_closets.dm, code/game/objects/structures/crates_lockers/closets/walllocker.dm
replaces the non-real hat that is in fire fighting lockes
:cl:
/:cl:
=> Firefighter hat fixes

code/modules/organs/organ_description.dm
Stops round start overloading and adds a bit more in flexable surgery cases
:cl:
/:cl:
=> Ups size of all lims for surgerys item

maps/CEVEris/_Nadezhda_Colony_Transition.dmm
Behold. WORKING!
Behold NOT WORKING!
:cl:
/:cl:
=> Fixes substations

code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/closets/syndicate.dm
I thought it auto added
locked = TRUE
secure = TRUE
when given access...
:cl:
/:cl:
=> Makes synda and locked old lockers locked

code/modules/mob/living/carbon/superior_animal/roach/attack.dm
With the new weighted system of KO this should be now balace for roach vs spider knockdown
:cl:
/:cl:
=> Roaches can knock down spiders again

code/game/objects/structures/crates_lockers/closets.dm
Makes hacking a more mec and cog state based skill check then flat mec skill to let some people with less engi/sci builds have a better time hacking well nerds and engis can do it better.
Also lowers the odds of the locker by locked by around 15% 
:cl:
/:cl:
=> Closet hacking tweak

code/modules/projectiles/projectile/energy.dm
Flash shells lasted like 2 seconds, now they last for 10 mins like a flare would. These things take silver... they should have /some worth/ for it other then "ahah shell go flash" 
:cl:
/:cl:
=> Makes flash shells last longer

code/modules/scrap/scrap_beacon.dm
=> Scrap becon now has 60 min limit

code/game/machinery/bioprinter.dm
Looking at a bioprinter now shows you its matter levels
:cl:
/:cl:
=> bioprinte matter levels

code/game/objects/items/oddities.dm
Makes the 1/4 odds to just 1/10
Their is /way/ to many perk ones and for some people that can pick and chose what perks to get it makes it e-z to nab basiclly in the first out all the perks you want.
:cl:
/:cl:
=> lowest perk annomlies a lot

code/game/objects/items/oddities_faction.dm, code/game/objects/items/weapons/storage.dm
Joyuese better defined in the back end code and the sheathes for the church now only fit church weaponry. Use a greatsword or cutless sheath for other weapons.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Weapon Fixes

code/modules/clothing/spacesuits/void/merc.dm
Lowers cursader armor to be 65 rather then 75 for the main 3 and bomb armor of 70
Lowers Ronin armor melee by 10% as well
Also lowers the lighting
:cl:
/:cl:
=> Rebalacnes Crusader power armor

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
we dont use drums in this, also wrong ammo typea
:cl:
/:cl:
=> corrects 20mm revolver shotgun ammo

code/game/objects/effects/spiders.dm
Could do nothing could make everything easer...
:cl:
/:cl:
=> Maybe lets any item regardless of intent remove webs

code/datums/autolathe/clothing.dm, code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm, code/game/objects/items/weapons/storage/deferred.dm, code/game/objects/random/lathe_disks.dm, code/modules/clothing/head/soft_caps.dm, code/modules/clothing/suits/armor.dm, code/modules/clothing/under/miscellaneous.dm
Makes NorthTech into Iron Lock Security
Makes their armor into a disk to refect lore
:cl:
/:cl:
=> Loretweaks

code/modules/mob/living/silicon/robot/robot_dogborgs.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
All borgs now have a cutting tool for roach bodies or spiders.
Tweaks some power_efficiency to be less harsh as are bigger map with few chargers around...
:cl:
/:cl:
=> Robot buffs

code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
Should help make spider nests not be as big and scary
:cl:
/:cl:
=> Makes nurses need 2 feds before laying eggs

code/modules/mob/living/carbon/human/species/station/station.dm
=> Cindarite organ hotfix

code/ATMOSPHERICS/components/omni_devices/filter.dm, code/ATMOSPHERICS/components/omni_devices/mixer.dm
Makes substations on surface, mines and stairs not cost like 90kws 
:cl:
/:cl:
=> Less exstream costs of basic air

code/modules/mob/living/carbon/human/life.dm
Makes it as if it god mode to system shock (pain)
:cl:
/:cl:
=> Maybe fixes nopain taking pain

code/game/objects/items/weapons/clown_items.dm
=> soap icon fix

html/changelog.html
=> Updates changlog people

code/modules/mob/living/simple_animal/hostile/pirate.dm
Maybe fixes how VWs can doup drops 4~ times
:cl:
/:cl:
=> Possable fix to void wolfs death drops

code/modules/mob/living/carbon/human/species/forms/station.dm
Kaz said they should have done this, thus I am to save them the time
:cl:
/:cl:
=> FBP death/halloss messages being better

code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
1 as im told is grater then 0
Spiders as it turns out were getting 1 free body before haivng to eat 2 making it 1-3-5-7 for egg laying numbers
:cl:
/:cl:
Might make it also not count mice
=> Spiders no longer get a free feed

html/changelog.html
Keeping it upto date
:cl:
/:cl:
=> updated changelogs again

code/game/objects/random/credits.dm
Drasticly lowes the minium credits each spawn past 50 credits get.
Should help make getting some "lucky" things much more random and less likely to set you for the round.
:cl:
/:cl:
=> Lowers credits min random spawns

code/game/objects/effects/spiders.dm
Makes farming chtmant webs unable to give webs
Makes web maybe take into account the silk weaver before attacking
:cl:
/:cl:
=> chtmant spider web fix

code/modules/detectivework/tools/rag.dm
Fixes a runtime I hope in rag update name
:cl:
/:cl:
=> fixes rag runtime maybe

code/modules/mob/living/simple_animal/hostile/big.dm
White carps no longer solo clear all of the lake forest of carp and mobs
:cl:
/:cl:
=> White carp no longer attack other carps

code/game/objects/items/weapons/nt_melee.dm
Longsword is now longer then short sward
:cl:
/:cl:
=> corrects longsword being small

code/datums/craft/recipes/guild.dm
Makes it so its not checking for materal gold 12 quility on a gold bars
:cl:
/:cl:
=> guild crafting hot fix

code/__HELPERS/bluespace_entropy.dm
Its now much MUCH easyer to trigger bluespace entrop showing to people that, hey maybe be careful with teleportering and bags of holding ok?
:cl:
/:cl:
=> Drasticly lows the bluespace entrop numbers so they can actually happen 

code/game/objects/items/weapons/circuitboards/machinery/research.dm
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhh
:cl:
/:cl:
=> Nanoforage building hotfix

code/game/machinery/turret_control.dm
Laser core is a much beter fit as its less wealth to sell and have better mats then 1 uranium making it better for the player market
:cl:
/:cl:
=> Swaps out RnD laser cannon in turrets for the lasercore

code/game/objects/items/oddities.dm
Trinkets now again have 10% drops rather then 100%
:cl:
/:cl:
=> trinket perks only at 10% again

code/game/mecha/equipment/tools/tools.dm
>places a check for a item below the check for it being bolt
Ah yes coding 100%
:cl:
/:cl:
=> Makes the cube fuction of scrap work

code/game/jobs/job/church.dm, code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
Hydro isnt church here
:cl:
/:cl:
=> Church no longer gets hydro bay

code/game/objects/items/weapons/tools/misc.dm
The greyson meditool now has been found to be infact also a laser scaple that takes a medium cell.
Truely amazing.
:cl:
/:cl:
=> Greyson meditool cell use

code/game/turfs/simulated/cleaning.dm
Why is this coded like this? - Fixes holywater and sterilizine not able to be used in cleaning
:cl:
/:cl:
=> Allows holywater and sterilizine to clean tiles

code/modules/projectiles/guns/energy/stun.dm
RIG tasers have been heavy nerfed to not be amazing and spammy to down someone in 3 shots
Borg tasers also slightly have been nerfed as well to take 5-6 shots to down someone
:cl:
/:cl:
=> taser nerfs

code/modules/reagents/reagents/medicine.dm
Dex+ to give it use now heals musles 
ossisineor what ever now also heals bones rather then just mending them
peridaxon now heals nerves
purger now heals kidneys 
Quickclot now heals blood vessels praise the sun as now its worth making. 
:cl:
/:cl:
=> all the heals

code/game/objects/items/oddities.dm
Fixes small runtime error when a ghost would attempt to view an oddity.
=> Fixes Oddity Run Time

code/modules/reagents/recipes/recipes_slime.dm
Fixes typos to help slimes react properly.
Also removes a couple of error flags.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fixes typos to help slimes react properly

code/modules/projectiles/guns/energy/stun.dm
im bad with numbers
:cl:
/:cl:
=> Lowers taser rig costs to not be 5k

code/modules/projectiles/guns/mods/mods.dm
Odd this that it prevents things that dont have this var if they are not a tool mod ngl
:cl:
/:cl:
=> fixes everything with gun mods and removal

code/modules/reagents/reagents/medicine.dm
turns out all the chems were broken and I used broken code yay. 
:cl:
/:cl:
=> fixes chemical issue maybe

html/changelog.html
=> dongles and stutters to adminship

code/modules/research/nodes/engineering.dm
Also removes the fact that the implant is listed twice there.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
add: Circuit printer is now in the tech node that unlocks them.
fix: Implants are no longer listed twice in the same node.
/:cl:
=> Re-Adds Custom Circuit Printer

code/modules/reagents/reagent_containers/spray.dm
Defence spray now has 50u rather then 40
and is now made by Seinemetall Defense, known for their high class poilice weapons
:cl:
/:cl:
=> spray lore and buff changes

code/modules/scrap/oldificator.dm
Laser guns now when old can cost more to fire, have less in their charge mode and charge less fast in charge mode!
Tools and guns now will not be as horrable if old, so no longer will we have 10% -20% tools
:cl:
/:cl:
=> Less horrible old things

code/modules/scrap/oldificator.dm
Speed merge, please
:cl:
/:cl:
=> Critical issue fixed

code/game/objects/effects/mines.dm
no longer are you able to pick up shadows
:cl:
/:cl:
=> Shadows now cant be picked up

code/game/machinery/bioprinter.dm
My bad broke it forever ago and dont know why
Also adds in the new organs that we have that for some reason are missing
:cl:
/:cl:
=> Maybe fixes organ printer desc issue

code/modules/mob/living/silicon/robot/robot_dogborgs.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
All borgs now get a GPS in them and drones
Sec borg "kitchen knife" is now a tactical knife
:cl:
/:cl:
=> All borgs now get GPS + sec borg buff

code/datums/autolathe/tools.dm, code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm, code/game/objects/random/lathe_disks.dm, code/game/objects/structures/crates_lockers/closets/secure/medical.dm
New medical disk that holds all the advanced tools and some other odds and ends for people to fine.
Places a CMO verson for the CBO in their locker as normal.
:cl:
/:cl:
=> advanced medical disk

code/game/machinery/vending.dm, code/modules/projectiles/projectile/force.dm
MadmanMartian as always has made a rather amazing pr making venders rather then just throw its items, it now shoots coins rather then free items!
Amazing and I love this so much im porting it and such.
#5874 on https://github.com/discordia-space/CEV-Eris/pulls
:cl:
/:cl:
=> Vendor coin shooting port

code/game/machinery/rechargestation.dm
=> Fixes icon issue with repair stations

code/game/machinery/doors/airlock.dm
Dosnt quite fit how long we hear the jingles
:cl:
/:cl:
=> lowers key time to find key

code/modules/mob/living/silicon/robot/drone/drone_items.dm, code/modules/reagents/reagent_containers/food/drinks.dm, code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Broken bottles and curcits for matter decompiler now works
Remains such as mice, and others will now work as well being cleaned up by the matter decompiler
Fixes broken icons, with - small milk carts, booze bottles
:cl:
/:cl:
=> few misc fixes

code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_dogborgs.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/living/silicon/robot/robot_upgrades.dm, code/modules/research/designs/robot_parts.dm, code/modules/research/nodes/power.dm
Corrects ark welder for borgs to you know... work... -
This was bugged, to not work do to a naming error in its path
Corrects scrub borgo to clean tiles
This was an unintended side affect of when we ported scrubborgs to be their own type thus not told to clean tiles as they walk over. Undersight correction
Makes a new Power Saver upgrade for borgs to have better power saving, for when they dont have an atomic cell.
This one has been long over-do but never added do to atomic cells being a thing nulling this type of upgrade. This makes it so that any borg will be 50% more power saving,
Replaces a few 1s and 0s with Trues and Falses.
Just your normal replacing of the same thing for easyer reading of the code, told to this by most coders for "consistency" 
:cl:
/:cl:
=> borg corrections and new upgrade

code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm
Gives the grayson bot a lot bigger view area as they are infact a massive mech and could see people shotting at them from only 33 tiles away
Speeds up their attacks to not be 2 mins
:cl:
/:cl:
=> Grayson Megafuan buff

code/game/objects/items/weapons/storage/bags.dm
Removes the stachle of holding lie in its desc making people think its safe to put in other bluespace bags
:cl:
/:cl:
=> lies be gone

code/game/jobs/job/security.dm
Better tells the players that your not a full Soteria Medical person rather then someone that works more independently 
:cl:
/:cl:
=> Better corpsman job duties

code/game/objects/items/weapons/power_cells.dm
As fun as is it to fine rare prototypes of stuff in who knows how old bunker, in lore its not all that logical. The new cell desc reflect that they are on the market and are nothing to fancy other then its power rating class.
:cl:
/:cl:
=> cell lore changes

code/modules/core_implant/cruciform/rituals/construction.dm
corrects console for biogenertaor being for the biomatter generetaor
makes platforms buildable
better names the platform
makes large canistors work, they had a rouge comma 
:cl:
/:cl:
=> fixes some contruction faith issues

code/game/objects/items/weapons/tools/simple_weapons.dm, code/game/objects/structures/crates_lockers/closets/secure/militia.dm, code/modules/mob/living/silicon/robot/robot_dogborgs.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/living/silicon/robot/robot_upgrades.dm, code/modules/research/designs/robot_parts.dm, code/modules/research/nodes/combat.dm
2 more borg upgrade!
Stachle of holding for many borgs that want to hord more!
New knife adding thingy that gives sec borgs a bigger knife!
New fluff weapon for CO, a chain for RP and the like - Suggested by Red
Tries to fix hypo upgrade...
:cl:
/:cl:
=> misc good things

code/game/objects/items/weapons/extinguisher.dm
QoL that makes water coolers work as mapped as more fitting extinguisher refills then random water tanks
:cl:
/:cl:
=> extinguisher can be filled from water coolers

code/game/objects/effects/step_triggers.dm, maps/encounters/deepforest/_Prepper_Bunker.dmm, maps/encounters/deepforest/deepforest.dm
SoJ2077 fixes - 
Fixes an issue with how the broke stairs are
Fixes an issue with map layering
These are 100% my fault and should not have happen, many sorries to anyone affected by these issues.
:cl:
/:cl:
=> the hotest of fixes

code/modules/organs/organ.dm, code/modules/reagents/holder.dm
* Fixes Tahcacillin and other Spaceacillin derivatives not treating infections at all.
:cl:
fix: Fixed tahcacillin and other spaceacillin derivatives not treating infections.
/:cl:
=> Bugfix/Fix spaceacillin derivatives not treating infections.

code/game/jobs/job/medical.dm
For when they need to get basic medical chems or sit in frount desk
:cl:
/:cl:
=> Gives Paramedics access to chems/frount desk

code/game/objects/items/devices/radio/encryptionkey.dm
Removes the headset radio thing for actors as its not read replacing it with supplie
Fixes plasmatag headset keys
:cl:
/:cl:
=> keyheadset fixes

code/modules/hivemind/wires.dm, code/modules/projectiles/guns/energy/plasma.dm, code/modules/reagents/reagents/core.dm
Martyen holdout pew pew now fits in hostlers
Holy tiles now do things against hivemind, having 30% odds to just kill the node slowing it down a bit maybe!
:cl:
/:cl:
=> small church tweaks

html/changelog.html
=> Medizan to moderator

code/modules/sanity/sanity_mob.dm
=> Balance Hotfix

code/__DEFINES/perks.dm, code/datums/perks/oddity.dm, code/game/objects/items/oddities.dm
You basically need 2 to make a full new one 3 if you want to power the guilds.
:cl:
/:cl:
=> Makes blackbox accully power the nanoforage

code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/living/silicon/robot/robot_upgrades.dm
Speed upgrades now stay active untill restarted rather then reset
Ups the miner borg rob stat to mine faster
Lowers miner borg tgh stat to take more damage
:cl:
/:cl:
=> better borg qol

code/game/jobs/access_datum.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/prospector.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm
Spec officer now gets medbay access again(woops)
New access, suits sensors
How gets it?
all of Soteria
Foreman
WO and CO
Preimer (duh)
:cl:
/:cl:
=> access changes

code/modules/projectiles/ammunition/bullets.dm, code/modules/projectiles/gun.dm, code/modules/surgery/surgery_ui.dm
7.5 now uses .257 icons for the time bieng
fixes surgery UI hopefully
fixes issues with scopes huds
:cl:
/:cl:
=> small fixes

code/datums/craft/recipes/weapon.dm
We now use 3 more steel
We now uses carboard rather then a tool of carboard 
:cl:
/:cl:
=> fixes ammo kits crafting

code/datums/autolathe/guns.dm, code/datums/corporations.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/game/objects/items/weapons/grenades/flashbang.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/guns/projectile/pistol/clarissa.dm, code/modules/projectiles/guns/projectile/pistol/colt.dm, code/modules/projectiles/guns/projectile/pistol/firefly.dm, code/modules/projectiles/guns/projectile/pistol/ladon.dm, code/modules/projectiles/guns/projectile/pistol/lamia.dm
Fixes some bad branding
Fixes all hanguns not taking highcap
Maybe fixes scopes
:cl:
/:cl:
=> branding and gun fixes

code/modules/projectiles/gun.dm
K5 will help me later to make a fix to the runtimes
:cl:
/:cl:
=> fixes gun scopes

code/game/objects/items/devices/scanners/plant.dm, code/modules/core_implant/core_implant.dm
-Green thumb and plant analyzers no longer require 25 cog, so no more annoying messages and proper feedback is now a thing.
-Cruciform materials altered, as was tech levels, to make attempting to steal a cruciform a more worthwhile reward.
=> Fixes an issue with green thumb

code/modules/core_implant/cruciform/rituals/priest.dm
-Reconsecration is now fixed, it was broken because of a fucking period missing at the end of the sentence.
=> Fixed Reconsecration

code/modules/reagents/reagents/medicine.dm
I only added line 462, I have no idea why the rest of the Ryetalyn code had spaces instead of tabulations since it was all literally untouched, sorry.
=> Fixes master, for real

html/changelog.html
Makes T306206 a moderator to are changelogs
:cl:
/:cl:
=> Cora to moderatiors

code/modules/scrap/scrap_beacon.dm
Doubles the scrap becone cool down to 2 hours
:cl:
/:cl:
=> doubles cooldown

code/modules/mob/living/silicon/robot/robot_dogborgs.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/research/nodes/bluespace.dm
Medihound and normal medical borgs now get roller beds
Makes their bags printable
:cl:
/:cl:
=> Roller Beds for borgs + bag fix

code/game/machinery/turret_control.dm
Titiania laser cannon is a better lore fit for the preppers and void wolf base
:cl:
/:cl:
=> Swaps out "advanced laser turrets" Lasercore to a lasercannon

code/modules/projectiles/guns/projectile/boltgun.dm
In real life when you bolt a gun, it makes the gun ready to fire as soon as it bolts. Lets do that so its more viable with quick players or trainning perk
:cl:
/:cl:
=> bolt buffs

code/modules/reagents/reagents/drugs.dm
Sorry Kaz, I never knew that one cig was 100% **GUARANTEED** addiction chance.
:cl:DimmaDunk
tweak: Reverts Nicotine back to a no-addiction chance. No more cravings spam!
/:cl:
=> Reverts Nicotine addiction

code/modules/projectiles/guns/projectile/revolver/rev10.dm
=> rev10 sprite fix

code/datums/autolathe/biomatter.dm, code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm, code/modules/clothing/shoes/jobs.dm
Adds hermes boots, slightly faster shoes but at a cost of mats and of armor!
:cl:
/:cl:
=> Hermes boots - Faithaloo

code/modules/reagents/recipes/recipes_food_drinks.dm
Turns out these reactions dont care about it being a no react for some reason
=> fixes maybe the microwave reaction

code/datums/outfits/jobs/engineering.dm
Tired of having to fight over the one pair of gloves on the guild? Every guild member (Master as well) gets insuls at roundstart now.
:cl:DimmaDunk
tweak: Guild Master and Adepts now spawn with insulated gloves by default
/:cl:
=> You get gloves, you get gloves, every(guildie) gets gloves!

code/datums/security_state.dm
<details>
<summary>
About The Pull Request: Changes all mentions of "Station" in alert level announcements to say "Colony" instead
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Changes all mentions of "Station" in alert level announcements to say "Colony" instead
:cl:
=> Updates alert messages to say "Colony"

code/game/objects/items/weapons/tools/mods/_upgrades.dm
Removes now unneeded vars that were runtiming
:cl:
/:cl:
=> runtime fix

code/game/objects/structures/crates_lockers/closets/utility_closets.dm
EOD sec lockers no longer have Jug armor
:cl:
/:cl:
=> fixes a balance issue

code/modules/reagents/reagents/drugs.dm
smoking op plz nerf
Smoking now will have an affect such as painkillers and if you have a perk heal you a small bit
:cl:
/:cl:
=> fixes smoking buffs

code/game/machinery/rechargestation.dm
You can now deconstruct repair station and upgrade them.
:cl:
/:cl:
=> Fixes unremovable repair stations

code/game/machinery/rechargestation.dm
I forgot a single (
:cl:
/:cl:
=> fixes master for real

code/datums/ai/ai_law_sets.dm
Both Kaz and Dongels, as well as drone mains have discussed this to being a bad law for are setting and RP
:cl:
/:cl:
=> Fixes drones law

code/modules/mob/living/silicon/robot/robot_items.dm
Turns out they are not in storage.icons
:cl:
/:cl:
=> fixes invisible borg satchel

code/game/objects/structures/crates_lockers/closets.dm, code/modules/reagents/machinery/centrifuge.dm, code/modules/reagents/machinery/grinder.dm
Fixes maybe the centrifuged chem doup
Fixes grinding up borg items and spay bottles
Fixes lockers not checking stats for hacking 
:cl:
/:cl:
=> fixes misc things

code/modules/tips_and_tricks/jobs.dm, code/modules/tips_and_tricks/mobs.dm
Ever feel like your getting the same 4 tips back to back?
Ever want to have chtmant tips?
well want no more untill a week when you see all the new tips added!
:cl:
/:cl:
=> more better tips

code/game/objects/items/bodybag.dm, code/modules/organs/internal/appendix.dm, code/modules/organs/internal/blood_vessels.dm, code/modules/organs/internal/eyes.dm, code/modules/organs/internal/heart.dm, code/modules/organs/internal/kidneys.dm, code/modules/organs/internal/liver.dm, code/modules/organs/internal/lungs.dm, code/modules/organs/internal/machine.dm, code/modules/organs/internal/muscles.dm, code/modules/organs/internal/nerves.dm, code/modules/organs/internal/stomach.dm
Makes most organs no longer all the same size.
Makes body bags way bigger.
:cl:
/:cl:
=> Body bag QoL and implant buffs

code/game/objects/structures/crates_lockers/closets/l3closet.dm
Viros and now normal medical viro lockers will now spawn with clearner
Normal non-gernal lockers will spawn with gear.
:cl:
/:cl:
=> Medical viro gear

maps/CEVEris/shuttles-nadezhda.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Hotfix timer

code/modules/reagents/machinery/centrifuge.dm
Likely fixes and issue with centrifuges
:cl:
/:cl:
=> Maybe fixes centrifuges again

maps/CEVEris/centcomm.dmm
https://cdn.discordapp.com/attachments/525548018951258112/819010429392650270/unknown.png
:cl:
/:cl:
=> tables and stuff for hacker chip

code/modules/projectiles/gun.dm, code/modules/projectiles/guns/matter/launcher/books.dm, code/modules/projectiles/guns/projectile/boltgun.dm, code/modules/projectiles/projectile/beams.dm
Magic books are STILL broken but less now!
Fixes a runtime with fireing without a user
:cl:
/:cl:
=> gun fix + book tweaks

code/modules/clothing/spacesuits/void/void.dm
Void suit helmets can now be removed and added
:cl:
/:cl:
=> void suit helmet removal

code/game/machinery/atmoalter/pump.dm, code/game/machinery/atmoalter/scrubber.dm
Fixes medium cells being spawned in pumps and scrubbers rather the large
:cl:
/:cl:
=> Corrects srubbers and air pumps cell

code/game/objects/items/devices/propaganda_chip.dm, code/game/objects/items/devices/spy_sensor.dm
Spy bug and exl chip no longer 0/3 as they now have a real tech level
:cl:
/:cl:
=> fixes bad levels

code/game/objects/random/food.dm, code/game/objects/structures/crates_lockers/closets/secure/militia.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/modules/reagents/reagents/other.dm
Adds random crayon ration to the game!
Adds rng for a crayon box to spawn in ration spawns
Adds rng crayons to blackshield lockers
Makes crayon powder act like paint
Removes crayon powder form being toxic
:cl:
/:cl:
=> founded in 1885

code/modules/telesci/bcrystal.dm
Lowers the insain amout of mats you get form bluespace roaches to not be 300 diamonds per cluster
:cl:
/:cl:
=> Bluespace roach nerf

code/game/objects/random/guns.dm, code/game/objects/random/lathe_disks.dm, code/game/objects/structures/crates_lockers/largecrate.dm, code/modules/cargo/packs_hospitality.dm, code/modules/cargo/packs_security.dm, code/modules/projectiles/guns/projectile/automatic/survivalrifle.dm
Adds 3 new crates - Music crates (piano and then a band crate
Adds new crate for the survival rifle Bond! Comes with 60 shots of the 10x24
Adds clarissa & makarov to trash/gun spawns
Tweaks spawn values of the Pug to spawn more then the SBWA or Pluse rifle as its not nearly as powerful 
Corrects 12x24 to 10x24
:cl:
/:cl:
=> More gun loot and cargo packets

code/modules/tips_and_tricks/gameplay.dm, code/modules/tips_and_tricks/jobs.dm, code/modules/tips_and_tricks/mobs.dm, code/modules/tips_and_tricks/roles.dm
Fixes some typos on tips, adds other useful tidbits for some jobs.
:cl:
add: Added more job tips! Changes some missinformation too!
del: Commented out the Supermatter tip
spellcheck: Fixed some typos on certain tips
/:cl:
=> New tips and typo fixes

code/game/objects/structures/window.dm
RPlasma glass now takes 100,000 kittens of temp
Takes more force to dent it
:cl:
/:cl:
=> Buffs chu- Er R-plasma glass

code/modules/projectiles/guns/projectile/automatic/basstet.dm
=> fixes some bad/missing vaules

code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm
Slot-o-Matic now has a safty to prevent bugs
Slot-o-Matic now has proper gun tags so it can be upgraded a bit - why you would do this is byond me
:cl:
/:cl:
=> Problem child

code/modules/mob/living/carbon/human/whisper.dm
<details>
<summary>
</summary>
<hr>
Noticed that whispers are not logged in the log file. Added a line to fix that.
<hr>
</details>
:cl:
fix: Whispering is now properly logged in the server log file.
/:cl:
=> Whispers are now logged correctly.

code/__DEFINES/research.dm, code/datums/autolathe/tools.dm, code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm, code/modules/research/designs.dm, code/modules/research/designs/devices.dm, code/modules/research/designs/greyson.dm, code/modules/research/designs/medical.dm, code/modules/research/designs/rigmodules.dm, code/modules/research/designs/stock_parts.dm, code/modules/research/designs/weapon.dm, code/modules/research/nodes/biotech.dm, code/modules/research/nodes/combat.dm, code/modules/research/nodes/engineering.dm, code/modules/research/nodes/greyson.dm, nano/css/shared.css
Beind the beta testing - Hopefully fixes all the icons being wrong
Hopefully fixes none of the things ever being in the menus to print
What rnd can see!
Armor and glasses are now in their own clothing tab
"Unsorted" tab should now be fixed into "Tools" or into "Clothing"
:cl:
/:cl:
=> Maybe Rnd fixes and stuff for the arc rewards

code/game/machinery/doors/airlock.dm
*sigh*
Fixes keys perma making doors stuck in use...
:cl:
/:cl:
=> Fixes inuse bug

code/game/jobs/job/medical.dm, code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Orderly now gets a stunbaton, and a holser for it
Orderly now has access to just about anywhere in their department as they are a Dr. Brown, what the hell these departments needs sec and are one token rent a cop doesn't have access?
Corrects Medical Difficulty text to be more reflective of how the difficulty legitimately is.
:cl:
/:cl:
=> orderly buffs

code/modules/research/designs/weapon.dm, code/modules/research/nodes/greyson.dm, code/modules/research/nodes/power.dm, nano/css/shared.css
Makes small atomic cells needed for large and small
Makes gun mods now in the gun mods tab
Fixes some more stuff for the greyson rewards
:cl:
/:cl:
=> last things for the rnd stuff I hope!

code/game/jobs/job/offcolony.dm
You know that thing I coded so long ago. That I forgot to give hunters... Amazing work me...
:cl:
/:cl:
=> Adds in the crafting for hunter soap

code/modules/research/nodes/greyson.dm
Fixes the best node ever that no one should be able to get without disks
:cl:
/:cl:
=> Fixes grayson tech - kaz broke it :P

code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/simple_animal/friendly/roomba.dm
It now cleans as a roomba should
:cl:
/:cl:
=> Roomba cleaning

code/modules/reagents/machinery/grinder.dm
Grinders now use their manipulators to grind up faster AND hold more things inside them
:cl:
/:cl:
=> upgradeable grinders

code/modules/reagents/machinery/chem_dispenser.dm
Chem dispensers should now use its capacitor to charge better
:cl:
/:cl:
=> better cell charge for chem dispenders

code/game/mecha/equipment/weapons/weapons.dm, code/modules/mob/living/simple_animal/hostile/doomba.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/hostile/onestar_drone.dm, code/modules/mob/living/simple_animal/hostile/pirate.dm, code/modules/mob/living/simple_animal/hostile/stranger.dm, code/modules/mob/living/simple_animal/hostile/syndicate.dm, code/modules/mob/living/simple_animal/simple_animal.dm
Mobs now have a fire delay that admins can tweak
Mech guns have a delay per firing to help space out shooting for balance against client crashing, again modular for admins to tweak (mechs are a bit brokenly good)
:cl:
/:cl:
=> Client side balance

code/game/objects/random/melee.dm
Material swords are now weighted to be steel/iron/plasteel
Material swords are more likely to also be made out of silver or gold if not above
Material swords now rarely spawn as gem swords
:cl:
/:cl:
=> rebalances material swords spawns

code/modules/research/xenoarchaeology/finds/finds.dm
Xenoarchy should now always be worth doing for funding if not for the items
New finds can be found
Removes coins form spawn table as they are useless. Like REALLY useless. So Useless they are removed kinda useless
:cl:
/:cl:
=> Its almost like these are rare items

code/game/machinery/excelsior/ex_turret.dm, code/game/machinery/portable_turret.dm, code/game/objects/items/weapons/grenades/spawnergrenade.dm, code/modules/core_implant/cruciform/machinery/obelisk.dm, code/modules/mob/living/bot/bot.dm, code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/carbon/slime/items.dm, code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/silicon/silicon.dm, code/modules/mob/living/simple_animal/friendly/cat.dm, code/modules/mob/living/simple_animal/friendly/corgi.dm, code/modules/mob/living/simple_animal/friendly/crab.dm, code/modules/mob/living/simple_animal/friendly/exotic_animals.dm, code/modules/mob/living/simple_animal/friendly/farm_animals.dm, code/modules/mob/living/simple_animal/friendly/lodge_pets.dm, code/modules/mob/living/simple_animal/friendly/mouse.dm, code/modules/mob/living/simple_animal/friendly/roomba.dm, code/modules/mob/living/simple_animal/friendly/spiderbot.dm, code/modules/mob/living/simple_animal/hostile/doomba.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/hostile/onestar_drone.dm, code/modules/mob/living/simple_animal/hostile/syndicate.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/mob/mob_defines.dm
The Roombas that are colony allied should no longer attack station pets, peaceful things and chtmants
Turrets no longer shoot allied mobs
Slimes that are made into pets should not be shot by colony base turrets
All roombas and cleaning bots that should clean now clean tiles
:cl:
/:cl:
=> This should work! Better Roomba AI!

code/modules/research/designs/prosthesis_implants.dm, code/modules/research/designs/weapon.dm, code/modules/research/nodes/biotech.dm
Robotics can now print off robotic chests and heads form their fabs to get out internal parts or replace people's FPBs with stronger cases or what not
Makes weapon upgrades go into gun mods tab
:cl:
/:cl:
=> SI can now make chest and head upgrades

code/game/objects/items/weapons/stock_parts.dm
Stockparts now have stock prices for stock selling
closes #1003 
:cl:
/:cl:
=> Legit just 1003

code/game/machinery/telecomms/presets.dm, code/modules/mob/living/say.dm, code/modules/modular_computers/terminal/terminal_commands.dm
Termianls when located will not give an XYZ + area 
Plasma tag headsets should now work
:cl:
/:cl:
=> termnal and plasmtag sets

code/game/machinery/turret_control.dm
Preppers turrets and void wolfs no longer attack their own. 
Yay
:cl:
/:cl:
=> Prepper turrets fix

code/game/objects/items/devices/radio/encryptionkey.dm
Binary keys now use silver plastic and metal
:cl:
/:cl:
=> Binary keys now use silver plastic and metal

code/__HELPERS/artwork_names.dm
Quick and easy fix to make all statues that are made not say Who?. but Nadezhda. Should be a bit more logcal
:cl:
/:cl:
=> Bandaid fix to Who?.

code/modules/economy/price_list.dm
Changes the prices of most kitchen made goods to better match the ingredients that go into them. Raises most, lowers others.
=> The end of the raw pasta market, the birth of everything else market

code/game/machinery/portable_turret.dm, code/modules/mob/living/simple_animal/hostile/doomba.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm
Fixes everything with mob power struggle. Should have also fixed anti-chtmant sentiment inside SI bots that are colony allied
Also maybe fixed anti Sillicon sentiment in turrets
:cl:
/:cl:
=> Hot fix of the ages

code/modules/mob/living/simple_animal/hostile/hostile.dm
Perhaps maybe im just the worst coder ever
=> maybe fixes chtmant racism 

code/modules/mob/living/simple_animal/friendly/lodge_pets.dm, code/modules/mob/living/simple_animal/hostile/doomba.dm
Loge pets divers and SI/Propis bots no longer attack everything colony related ever
:cl:
/:cl:
=> Rawr at myself for never checking the vars

code/modules/mob/living/silicon/robot/robot_modules.dm
Drones can now use rnd consoles to print themselfs better parts if needed.
:cl:
/:cl:
=> drones are infact smarts

code/modules/mob/living/simple_animal/hostile/hostile.dm
Mobs can now shoot again when player controled
:cl:
/:cl:
=> Fixes mob shooting

code/game/objects/items/weapons/tools/mods/mod_types.dm
Makes those 0.2 cost spikes not sell for 200 credits
Cant have shit in rnd
:cl:
/:cl:
=> nerfs spikes they are legit 2 metal

code/modules/research/xenoarchaeology/manuals.dm
Adds the manual: Suspension Setup for Xenoarch. Does not add it to the game world just codes it in. Book is "Suspension Setup"
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Suspension Field Manual

code/modules/hydroponics/trays/tray_reagents.dm
LSS water now has a sprite
:cl:
/:cl:
=> Fixings a null icon

code/modules/hydroponics/grown.dm
May fix issue where plants clipped or chopped in the wild would not appear
=> Maybe Fix plant clipping issue

code/game/objects/items/weapons/storage/bags.dm
<Nerfs chem bags to hold 10 items instead of 50. To prevent mobile medbay tactics with a single bag at least. You can still easily move things around chemistry with a hold of 10 bottles.>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Nerfs Chem Bag Capacity.

code/modules/hydroponics/seed_datums.dm, code/modules/reagents/reagents/dispenser.dm, code/modules/reagents/recipes/recipes.dm
Adds liquid silver as a chemical, adds in process to solidify, and changes Silver-Bells to take advantage of this.
=> Silver Solidification

code/modules/clothing/spacesuits/rig/modules/combat.dm, code/modules/projectiles/guns/energy/stun.dm
Fixed the mounted taser to:
1. allow you to change the shot type
2. Actually shoot it
Tested on my own server.
=> Mounted Taser Fix

code/game/machinery/vendor/food_vendors.dm
This has always annoyed me cuz ICly they are saying `Tea, Sirslashmadame` 
:cl:
/:cl:
=> Tea vender is now better at selling

code/modules/modular_computers/file_system/programs/research/cyborg_remote.dm
No longer soft-locks consoles
:cl:
/:cl:
=> Fixes a small issue with modular_console

code/modules/core_implant/cruciform/machinery/wall_obelisk.dm
=> the only dense one here is me

code/modules/mob/living/simple_animal/borer/borer.dm
Wall oblistics no longer should shoot these
Oblistics in gernal should no longer target them
:cl:
/:cl:
=> Boarders no longer gets nuked

code/game/objects/items/weapons/grenades/spawnergrenade.dm
Most drones SI makes now costs plasteel
Mannist drones is not Mannist drone
Sword bots are now sword couple
Ups cost in silver and gold for more explsive bots
:cl:
/:cl:
=> more drone balance

code/game/objects/items/weapons/storage/backpack.dm, code/game/objects/items/weapons/storage/belt.dm, code/game/objects/items/weapons/storage/wallets.dm, code/modules/clothing/suits/storage.dm, code/modules/hydroponics/trays/tray_reagents.dm
Namely makes the pest-killers/weed-killers/related printable things from the biogen have a price, 5-20, cheap but existent. Could probably use a bit of a raise sometime in the future, but we'll see.
Including the leather satchel and jacket being given a half-decent price. Oh, and the wallet, it's a nice 20 to match the bio-matter cost.
Along with adding a flat 15 cred price to most/if not all belts, save for the championship at a bit more, and the handmade belt at 5 creds. Again, could probably use some more specific fine-tuning for different belts.
=> Biogenerator related price additions, the aftershock of the ending of the pasta era

code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm
Exl .35 "Drozd" disk is now named properly
:cl:
/:cl:
=> Fixes a disk name

code/modules/projectiles/guns/projectile/automatic/lmg.dm
TK now can be loaded, has sprites and uses the correct caliber
:cl:
/:cl:
=> fixes TK sprites and caliber stuff

code/game/jobs/job/science.dm
Scientists and Roboticists gain access to departmental funds to be able to buy / sell stuff now. 
Tested it on my server. Works just fine.
=> Giving Soteria department account access.

code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/crates.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, code/modules/projectiles/guns/projectile/automatic/lmg.dm, maps/CEVEris/_Nadezhda_Colony_Underground.dmm
Closets and crates now get damaged  bombs rather then flat destory, Carts now also drop items rather then null space them (same as a locker)
LMG TK should be fixed
Recluse spiders no longer stun someone for around 20 mins per bit - still a 1 hit ko!
Fixes a bad stair at cargo
Spiders no longer doup egg laying
=> 5 misc fixes

code/game/objects/items/devices/scanners/plant.dm, code/modules/research/experiment.dm
Now plant research reports (printed on the plant analyzer) can be scanned with the science tool for research points based upon how varied the plants being scanned are.
Each individual fruit "base" is worth ~1/10 of an average research disk.
Each individual fruit "chem" is worth ~1/4 of an average research disk.
Each individual fruit "trait" is worth ~1/3 of an average research disk.
Is it 100% random numbers? Yes.
Is this balanced? Not in the slightest. 
So expect some tweaking as we see live numbers and how we can correct oversights.
=> Xenofloral Research Points

code/modules/reagents/reagent_dispenser.dm
You burn though it so fast for so little gain its not worth making more and if rng screws you (it will) it gives barely any points cuz you need t5 to get even any good points and most stop at t3-t4 so its worthless
=> Raises viro food form 1k to 50k

code/game/mecha/mecha_construction/durand.dm, code/game/mecha/mecha_construction/firefighter.dm, code/game/mecha/mecha_construction/gygax.dm, code/game/mecha/mecha_construction/odysseus.dm, code/game/mecha/mecha_construction/phazon.dm, code/game/mecha/mecha_construction/ripley.dm, code/game/mecha/mecha_construction_paths.dm, code/modules/projectiles/guns/projectile/automatic/lmg.dm
maybe fixes LMG icon...
maybe fixes mech messages for feedback
Corrects missing hints
Lowers step timer to long rather then REALLY LONG were it takes like 30 seconds with a debug tool PER STEP
:cl:
/:cl:
=> hot fixes to mechs and lmg

code/game/objects/items/weapons/storage/uplink_kits.dm
Syndicate Cigs no longer cause run time at server restart.
Syndicate Cigs now correctly fill with the correct reagents.
Syndicate Cigs Kits come with a new flavor: Dylovene
=> Fix Syndie Smokes

code/game/machinery/Sleeper.dm, code/game/machinery/cryo.dm, code/game/mecha/mecha_construction/durand.dm, code/game/mecha/mecha_construction/firefighter.dm, code/game/mecha/mecha_construction/gygax.dm, code/game/mecha/mecha_construction/odysseus.dm, code/game/mecha/mecha_construction/phazon.dm, code/game/mecha/mecha_construction/ripley.dm, code/game/mecha/mecha_construction_paths.dm, code/game/mecha/mecha_parts.dm, code/modules/reagents/machinery/centrifuge.dm, code/modules/reagents/machinery/chem_heater.dm, code/modules/reagents/machinery/chem_master.dm, code/modules/reagents/machinery/electrolyzer.dm
Fixes mat doups with mechs, this was always a thing but now made worst by needing some parts that cost more things - goddamn it people why
Fixes perks && states for medical - for reals
Fixes descs maybe for mech building
Fixes more misc things with mechs like descs/items
:cl:
/:cl:
=> fixes mat doups and more mech corrections

code/modules/mob/mob.dm
Just what the title says, we now display perks in 2 columns instead of 1 and make the window slightly bigger when opened.
Tested on my server, showed no issue even when going into high perk numbers or no perk numbers.
=> Perks now appear in 2 columns.

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Find out.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fuck around

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
=> Slight Adjustment

code/game/machinery/cryo.dm
Imagine relising all that healing was hard coded by the cryo pod
Cryo is at lest 20x more affective
:cl:
/:cl:
=> Cryo now is usefull

code/game/machinery/autolathe/mechfab.dm
Exo suits can now properly take the mats needed for making rigs
:cl:
:cl:
=> Exo suit fix

code/game/machinery/Sleeper.dm, code/game/machinery/adv_med.dm, code/game/machinery/cryo.dm, code/game/objects/items/devices/scanners/health.dm, code/modules/reagents/machinery/centrifuge.dm, code/modules/reagents/machinery/chem_heater.dm, code/modules/reagents/machinery/chem_master.dm, code/modules/reagents/machinery/electrolyzer.dm
Cog at a 2:1 can bypass bio checks in medical giving you a use to stack up cog but not give the other boons of bio
Body scanner now uses its perk properly to bypass skill checks
:cl:
/:cl:
=> stats and perks, cog become usefull

code/modules/reagents/reagent_containers/glass.dm
<details>
<summary>
This allows players while on Disarm intent to pour beakers into another beaker/chem bottle/vial without splashing or down into a sink.  This is a quicker way if you want to just use the entire bottle instead of having to right-click context menu and select the max amount every time.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Disarm Intent Beaker Pour [glass.dm update]

code/modules/projectiles/gun.dm
Cop block will now stops gun from firing
:cl:
/:cl:
=> Fixes cop block

code/game/mecha/equipment/tools/shields.dm
Sanity check to prevent runtime at restart initialization.
=> Fixes Exosuit Shields

html/changelog.html
=> Update changelog admins

code/modules/mob/living/living.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Untested Hotfix

code/modules/mob/living/living.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Another hotfix

code/game/objects/items/weapons/power_cells.dm, code/modules/modular_computers/computers/subtypes/dev_pda.dm, code/modules/power/cell.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Atomcells have a reduced cooldown.
tweak: The 50S atomcell has a better charge rate.
add: PDAs now spawn with a tesla link.
/:cl:
=> PDA Tweaks

code/game/objects/items/weapons/shields.dm, code/modules/admin/bluespacetech.dm, code/modules/mob/living/living.dm, code/modules/mob/living/simple_animal/hostile/excelsior.dm, code/modules/mob/living/simple_animal/hostile/pirate.dm, code/modules/mob/living/simple_animal/hostile/syndicate.dm
BSTs can raise and lower stats by 5
Aheals now heal halloss
Fixes some mobs blocking
fixes some stuff that cant be named
fixes icons on stuff that cant be named
:cl:
/:cl:
=> imporanted fixes

code/game/objects/items/weapons/nt_melee.dm, code/game/objects/items/weapons/tools/hammer.dm, code/game/objects/items/weapons/tools/simple_weapons.dm
Fixes loads of tools and weapons magiclly lossing their upgrades do to how defines work
Unironically a church buff without looking like it
:cl:
/:cl:
=> Eris cucks the church, cat corrects it

code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
Still admin only but the disk will now print the correct ammo
=> corrects ammo type for plasma shells disk

code/modules/projectiles/ammunition/bullets.dm, code/modules/projectiles/projectile/plasma.dm
Corrects Plasma shells icon state and buffs their damage
:cl:
/:cl:
=> shell corrections

code/datums/wires/autolathe.dm, code/game/machinery/autolathe/autolathe.dm, code/game/machinery/bioprinter_nt.dm, code/game/machinery/excelsior/autolathe.dm
Hacking autolathens is now modular and MUCH better/usefull rather then nulling upgrades
Autolathens no longer can eat any random thing only takng in trash and sheets
Industrial and bioprinters are unaffected by this
:cl:
/:cl:
=> autolathen rebalance, the second coming, remasted, uncut, deluxe edition, preorder edition, golden.

code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/life.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
<details>
<summary>
</summary>
<hr>
Mobs used to need to wait between targeting, chasing, and attacking. Now they can do it all at once. This means that they will attack even if you're moving, the same way you can.
<hr>
</details>
:cl:
tweak: Mobs now go through the steps of targeting, chasing, and attacking within a tick, rather than waiting ticks between them.
/:cl:
=> Mobs are a little snippier with their attacks now.

code/modules/projectiles/ammunition/bullets.dm, code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/boltgun/scout.dm, code/modules/projectiles/guns/projectile/boltgun/star_striker.dm, code/modules/research/designs/weapon.dm, maps/CEVEris/_Hunting_Lodge.dmm, sojourn-station.dme
buffs Star striker to deal damage thats now balanced with outers
buffs .223 laser ak to deal slightly more damage then normal, as it holds less ammo
.223 now is labled on shells
:cl:
/:cl:
=> better laser sci stuff

code/datums/uplink/ammunition.dm, code/datums/uplink/announcements.dm, code/datums/uplink/badassery.dm, code/datums/uplink/devices and tools.dm, code/datums/uplink/grenades.dm, code/datums/uplink/hardsuit_modules.dm, code/datums/uplink/highly visible and dangerous weapons.dm, code/datums/uplink/implants.dm, code/datums/uplink/medical.dm, code/datums/uplink/neotheology.dm, code/datums/uplink/stealth and camouflage items.dm, code/datums/uplink/stealthy and inconspicuous weapons.dm, code/datums/uplink/telecrystals.dm, code/datums/uplink/uplink_categories.dm, code/datums/uplink/void_wolf.dm, sojourn-station.dme
Corrects some names and items in the uplink that were miss-abled or wrong
Makes most uplink items able to be gotton by anyone that finds such things
Adds a new tab for void wolfs gear and items
Removes some horrible affects and corrects some "station" to colony
lowers cost of nanites
:cl:
/:cl:
=> Uplink fixes and balance

code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/automatic/basstet.dm, code/modules/projectiles/guns/projectile/automatic/bren.dm, code/modules/projectiles/guns/projectile/automatic/bulldog.dm, code/modules/projectiles/guns/projectile/automatic/dp.dm, code/modules/projectiles/guns/projectile/automatic/luger.dm, code/modules/projectiles/guns/projectile/automatic/mac.dm, code/modules/projectiles/guns/projectile/automatic/nordwind.dm, code/modules/projectiles/guns/projectile/automatic/ppsh.dm, code/modules/projectiles/guns/projectile/automatic/sts.dm
Reverts sojourn-13/sojourn-station#1195
=> Revert "Gun Price Fixes & Minor Recoil Rebalance"

code/modules/client/preference_setup/augmentation/01_modifications.dm, code/modules/client/preference_setup/general/01_basic.dm, code/modules/client/preference_setup/general/02_body.dm, code/modules/client/preference_setup/general/04_equipment.dm, code/modules/client/preference_setup/general/06_furry.dm, code/modules/client/preferences.dm
Reverts sojourn-13/sojourn-station#1196
=> Revert "Categorizes Graphic Updates in Char Creation"

code/modules/mob/living/silicon/robot/robot_dogborgs.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
Borgs can once more use sci console
:cl:
/:cl:
=> biggest circuit

code/modules/mob/living/simple_animal/hostile/excelsior.dm
The gun this exc uses cant phycially rapid fire
:cl:
/:cl:
=> Fixes exl sniper rapid fire

code/modules/projectiles/ammunition/boxes.dm
7.5 scrap kit - now is small size and holds 30 shells rather then 180
:cl:
/:cl:
=> Fixes ammo kit boxes

code/modules/projectiles/guns/launcher/crossbow.dm
Turns out they are bugged and cant ever be fired do to safty that they dont get
:cl:
/:cl:
=> fixes crossbows

code/game/objects/items/weapons/swords_axes_etc.dm
Corrects baton damage types and numbers to reflect better on what intent your on
:cl:
/:cl:
=> corrects batons

code/modules/research/experiment.dm
People cant play the game correctly
:cl:
/:cl:
=> removes rnd cheese

code/modules/mob/living/carbon/superior_animal/roach/types/emp.dm
Wrong icons for them
:cl:
/:cl:
=> Makes elektromagnetisch have the sprite

code/modules/research/experiment.dm
Maybe it works this time
:cl:
/:cl:
=> RnD Cheese fix mk II

code/game/objects/structures/displaycase.dm
Looking at a case will now tell you more about it
You can now unlock and relock the cases
You can now take items out of cases when they are unlocked and has something inside it
:cl:
/:cl:
=> massively improves display cases

code/modules/clothing/shoes/jobs.dm
Hermes boots now need 20 more biomatter to print to stop people spamming them
Hermes boots speed buff its 5% rather then 10%
This is why can cant have nice things, - Everyone ever spamming them.
:cl:
/:cl:
=> Hermes Boots the speedening

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/game/objects/items/weapons/power_cells.dm, code/modules/clothing/suits/armor.dm, code/modules/projectiles/ammunition/bullets.dm, code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/guns/projectile/automatic/survivalrifle.dm, code/modules/projectiles/guns/projectile/boltgun/star_striker.dm, code/modules/research/designs/greyson.dm, code/modules/research/designs/medical.dm
Star Striker now has it scope once more
Linked 7.5 ammo boxes for each type of ammo for admin spawns
fixes commander suit icon so we close #1256 
adds the 10mm bond mag to exodic disk
fixes up some rnd miss-naming
:cl:
/:cl:
=> omni fixes

code/game/objects/items/weapons/tools/simple_weapons.dm
This PR adds the tool qualities of cutting 20 and sawing 20. 
The main purpose of adding tool qualities is because that will allow the gauntlet to take appropriate tool mods. Up to a max of 3. This makes it more useful with being actually able to do a few things plus not overshined by tools which can take their own upgrades.
I'm not very familiar with github so let me know if there is any problem with the PR.
=> Render Gauntlet Modding

code/modules/research/experiment.dm
Reverts sojourn-13/sojourn-station#1248
=> Revert "RnD Cheese fix mk II"

code/game/objects/items/weapons/grenades/explosive.dm, code/modules/mob/living/simple_animal/hostile/huntersprey.dm
Popor Avtomat Excelsior Player Mob.
Abilities:
Middle-Click fires the currently loaded ammunition.
Ammunition types:
Default is a .35 SMG.
LoadAP loads a high penetration AMR round, medium cooldown.
LoadFlamethrower loads a small flamethrower burst, medium cooldown.
LoadMaxim loads a machinegun that takes a while to charge but fires a strong burst, telegraphed and long cooldown.
LoadArtileria loads artillery flares that land and, afte 15 minutes explode (as if artillery landed there)
Smoke will deploy smoke grenades at your location.
Bumping into people will kick them away from you.
Tested on my own server.
=> ExcelsiorMob

code/controllers/subsystems/ticker.dm, code/game/machinery/excelsior/ex_teleporter.dm, code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm, nano/templates/excelsior_teleporter.tmpl
Some optizimation and blackshield tp fix
also fixes a board name
:cl:
/:cl:
=> misc fixes to teleporters and exl gear

code/modules/projectiles/guns/energy/heavypulserifle.dm
Ever notice that the heavy pluse rifle is a cheaper better titanic? Thats one main downside is that it burns lower cap cells if your a dumb and shoot all shots to 0 charge?
Well I relised that and so did others. Balance the heavy pluse rifle to more reflect it being cheap and cut down verson of a real mech gun
:cl:
/:cl:
=> Heavy pluse rifle tweaks

code/datums/autolathe/cells.dm, code/modules/projectiles/ammunition/magazines.dm, code/modules/reagents/reagent_containers/bidon.dm
Timer statis bin maybe now works
Corrects some ammo descs to be correct
Corrects the autolathen LSS/Exl cells to have right charge
:cl:
/:cl:
=> Random corrections

code/modules/reagents/reagent_containers/food.dm, code/modules/reagents/reagent_containers/food/snacks.dm, code/modules/reagents/reagent_containers/food/snacks/meat.dm
Different food items now have different amout of biomatter inside them
Lowers based food item form 10biomatter to 1 as before hand the covertion rate wash 10u - > 1sheet
:cl:
/:cl:
=> biomatter tweaks

code/datums/autolathe/basic_stuff.dm, code/game/objects/items/weapons/autolathe_disk/guild_disks.dm, code/modules/power/lighting.dm
New lights that guild can make to save power
Lights that are tampred with now costs more power
Brighter bulbs can be made, but they drain loads of power
=> power lights

code/modules/research/designs/medical.dm
Corrects medical tools being in the toolmods tab
:cl:
/:cl:
=> RnD toolmods fix

code/modules/research/designs/prosthesis_implants.dm
This make the exosuit fabricator able to print bone braces for reinforcing bones.
Bone reinforcement is an augment, the exosuit fabricator print augments, so it should be able to print bone braces.
=> Making the exofab able to make bone brace

code/game/mecha/mecha_construction_paths.dm
So apparently I changed the wrong values for https://github.com/sojourn-13/sojourn-station/pull/1283 . So this is the correct change this time !
=> Make constructing mechs take 5 cables.

code/modules/organs/internal/kidneys.dm
Apparently I missed a " in another PR.
=> Add a missing "

code/game/mecha/equipment/weapons/bullet_weapons.dm
Rookie mistake...
Fixes a bug with mech ammo boxes to over-load guns and unload guns
:cl:
/:cl:
=> Better operations

code/modules/projectiles/guns/oddity_items.dm
=> fix master

code/modules/core_implant/cruciform/rituals/path.dm
Nerfs (fixes a bug) with monomial's pain relief/heal litany where it did not have its cooldown used. This makes it work properly.
=> Monomial Heal Nerf (Bug fix)

code/modules/power/lighting.dm
Clamps power use on lights and fixes some maths of it
:cl:
/:cl:
=> cleaner maths for lights

code/modules/clothing/under/miscellaneous.dm
-Fixes a simple spelling error
=> Spelling fix in loadout

code/modules/projectiles/guns/energy/railgun.dm, code/modules/projectiles/projectile/bullettypes.dm
Turns out it deals 16 damage cuz its damage was never defined like it was meant to be
:cl:
/:cl:
=> fixes scraprifle damage

code/game/objects/items/stacks/medical.dm, code/modules/mob/living/carbon/human/stripping.dm
splits can be placed on any part of the body now
:cl:
/:cl:
=> splint buff

code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
Corrects bad names used on the omni rifle
Corrects the Longarm to have a 2 round burst as its meant to have that
:cl:
/:cl:
=> gives longarm the correction to shooting and gun lore

code/modules/projectiles/gun.dm
Fixes the null screen runtime
Code-shaming can finnaly be full of actual runtimes that are detrimental of gameplay , and not filled with this.
Changelog
🆑
fix: gun scope runtime.
/🆑
=> Eris fix by MLGTASTICa to gun scopes

code/game/objects/items/weapons/circuitboards/machinery/research.dm, code/modules/research/nodes/engineering.dm, maps/CEVEris/_Nadezhda_Colony_Underground.dmm
The industeral board for autolathens now cost silver and gold
The spare industeral autolathen in GM room is removed
Tweaks some nodes to be less well pooring their points into the industeral autolathen node
:cl:\
/:cl:
=> People are just the worst

code/game/machinery/deployable.dm, code/game/objects/items/devices/taperecorder.dm, code/game/objects/items/weapons/explosives.dm, code/game/objects/items/weapons/implant/implants/explosive.dm, code/game/objects/items/weapons/weldbackpack.dm, code/modules/assembly/bomb.dm, code/modules/mob/living/simple_animal/friendly/spiderbot.dm, code/modules/mob/living/simple_animal/hostile/doomba.dm, code/modules/power/cell.dm, code/modules/power/port_gen.dm, code/modules/power/smes.dm, code/modules/projectiles/projectile/bullettypes.dm, code/modules/projectiles/projectile/special.dm, code/modules/reagents/reagent_dispenser.dm, code/modules/scrap/scrap_burner.dm
Removes all the -1 dev stuff as that messess with the math
Makes it on implact rather then on_hit as it implies that its *hitting something* that can be hit rather then being impacted
:cl:
/:cl:
=> maybe fixes bomb guns

code/game/machinery/bioprinter.dm, code/game/machinery/rechargestation.dm
Cyborg repair station can now be upgraded and deconne..
Bio and prostic printers can now also be upgrade-able
:cl:
/:cl:
=> Fixes repair stations decon/upgrade stuff

code/modules/power/lighting.dm
Keeps the bolb changes but tweaks their vaules to be less or more light making them basiclly do the same
:cl:\\
/:cl:
\
=> Reverts lighting issues

code/modules/research/designs/medical.dm, code/modules/research/nodes/biotech.dm, code/modules/research/nodes/bluespace.dm
Rnd can now make small and large beakers
:cl:
/:cl:
=> rnd beakers

code/game/objects/items/weapons/tools/mods/mod_types.dm, code/modules/reagents/reagent_containers/glass/beaker.dm
Bluespace beakers on making now makes a bit of entropy
Bluespace tar now also makes a small bit of entropy on creation but still isnt bluespace flagged
:cl:
/:cl:
=> Bluespace beaker entropy

code/game/machinery/bioprinter.dm
Its W for weapon here rather then O for obj like almost every other thing
:cl:
/:cl:
=> fixes master, again

code/game/machinery/bioprinter.dm, code/game/objects/items/weapons/circuitboards/machinery/cloning.dm
Makes organ and propstics pritners upgradeable with matter bins
:cl:
/:cl:
=> Makes organ and propstics pritners upgradeable

code/modules/reagents/recipes/recipes.dm
Turns out the changes to nitro bomb were a bit to much making them far far far to weak for what you do
:cl:
/:cl:
=> Lets not criple chem bombs

code/modules/core_implant/cruciform/rituals/base.dm
A requested QoL change.
-Adds in the sender's name to the message someone gets instead of forcing people to manually tack it on.
=> Sending Litany Adjustment

nano/templates/excelsior_teleporter.tmpl
HTML code is a nightmare
:cl:
/:cl:
=> Maybe fixes exl teleporter ui

code/modules/reagents/reagents/food-Drinks.dm
Should now work to give sanity for those disers to level up without needing booze  if you dont want to drink booze
:cl:
/:cl:
=> Makes non-booze drinks count to level up

code/game/objects/items/devices/scanners/mass_scpectrometer.dm
The unused, legitmently worse health scanner now dosnt need as much cog and has a perk bypass
:cl:
/:cl:
=> Update mass scpectrometers 

code/game/mecha/equipment/weapons/bullet_weapons.dm
Reverts sojourn-13/sojourn-station#1289
Fixes mechs ammo
=> Maths is hard

code/game/objects/items/weapons/stock_parts.dm
<details>
<summary>
Changes the rating tiers of stock parts to give guild parts a use, and slow down the power jump of going from 100% extra efficiency from super parts to 400% efficiency of Greyson parts. Makes guild parts far more useful, and moves excelsior up the chain to entice people with the communist efficiency.
</summary>
<hr>
<hr>
</details>
:cl: Tweak: changes the ratings of stock parts guild to t6, excel to t5, greyson to t4
/:cl:
=> Make guild stock parts useful

code/modules/core_implant/cruciform/rituals/priest.dm
Something I wanted to suggest for https://github.com/sojourn-13/sojourn-station/pull/1366, but that I couldn't do.
=> Fix and nip a bug in the mud

code/modules/hydroponics/grown.dm
Reverts 6 of the biomatter buffed in sojourn-13/sojourn-station#1298
=> Lowers plant biomatter

code/game/jobs/job/civilian.dm
requested feature
:cl:
tweak: janitors get full lonestar service access
/:cl:
=> gives janitors full lonestar service access

code/game/machinery/rechargestation.dm
Makes repair stations have a board on map spawn.
close #1349
:cl:
/:cl:
=> Recharger station board

code/game/objects/items/weapons/storage/deferred.dm
AK crate now has the propper ammo maxs
:cl:
/:cl:
=> fixes ammo crate for aks

code/datums/outfits/jobs/off_colony.dm
Should fix hunters and outsiders spawning with embeded pda's
:cl:
/:cl:
=> 	pda_type = null

code/modules/projectiles/guns/projectile/shotgun/hunter_crossbow.dm
stops all guns form giving this bolt caster message
:cl:
/:cl:
=> Bad at paths

code/modules/projectiles/ammunition.dm
Makes caseless ammo be caseless hopefully
:cl:
=> fixes caseless ammo

code/modules/organs/external/_external.dm, code/modules/organs/organ.dm
Its insainly easy to fix emp damage with some wire, or self surgery with a screwdriver alone. Let them have *some* drawbacks
:cl:
/:cl:
=> Emps screw over robotic internal and external organs

code/modules/projectiles/guns/projectile.dm
Missed a spot were it was still spawning new cases rather then use stored for some reason, corrected
:cl:
/:cl:
=> second caseless fix

code/modules/reagents/reagents/food-Drinks.dm, code/modules/sanity/sanity_mob.dm
Drinks now will give small amouts of sanity propperly now
:cl:\
/:cl:
\
=> Fixes a small runtime

code/game/machinery/cryo.dm
Cryo now will slowly heal o2. Toxins. Cloneloss
This now makes it viable to heal dead bodies without surgery and get lower medical bills or try and heal up people that re 200 cloneloss
:cl:
/:cl:
=> Cryo buffs mk III

code/modules/hydroponics/seed.dm
This just prevent the `NO_PLANT_ICON` error message from being shown to everyone on the server.
=> No longer yell to the world when there is no icon.

html/changelog.html
=> Updates changelogs

code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
Allows admins to pick and chose when tyrants end hiveminds
:cl:
/:cl:
=> Hive-mind tweak, tyrant no longer by default ends hiveminds whole career 

code/game/objects/items/devices/uplink.dm
headset uplinks can now be accessed by the player if they know the code, code is 1445 shh
:cl:
/:cl:
=> Fixes headset uplinks

code/modules/mob/living/simple_animal/friendly/cat.dm, code/modules/mob/living/simple_animal/hostile/commanded/nanomachines.dm, code/modules/mob/living/simple_animal/hostile/doomba.dm, code/modules/mob/living/simple_animal/hostile/hivebot.dm, code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm, code/modules/mob/living/simple_animal/hostile/onestar_drone.dm, code/modules/mob/living/simple_animal/hostile/pirate.dm, code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
Makes emps more useful by disabling ranged laser attacks with mobs, as well as deal damage to some types of other mobs
Fixes a cat type form being able to be picked up
:cl:
/:cl:
=> emp usefulness

code/__DEFINES/mobs.dm, code/game/objects/items/bodybag.dm, code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm, code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
Large mobs can no longer be body bagged
Corrects mega funa form being smaller then small mobs
:cl:
/:cl:
=> cryobag and mob fixes

code/game/objects/items/devices/defib.dm
30 mins to need nano-jell for dead
15 mins of death starts degrading brain
=> Defib timer tweaks

code/game/objects/items/weapons/clown_items.dm
Peels now only slip once
:cl:
/:cl:
=> Peels now only slip once

code/datums/movement/mob.dm, interface/skin.dmf, modular_sojourn/pixelshift.dm, sojourn-station.dme
This PR adds in Pixel Shifting. Usable via Ctrl+Shift+Arrow Key
Resets upon movement. Can't pixelshift while buckled.
Note: Lot of copy pasting occured here. But tested and works properly. (Not sure if it will merge easily or not though)
=> Ports in Pixel Shifting

code/modules/mob/living/simple_animal/hostile/huntersprey.dm
Now fires 75HV instead of Antimaterial when using AP.
Now walks a lot slower
Flares now take 38 seconds to explode instead of 15
=> Popor Avtomat Balancing

code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/construction.dm, code/modules/core_implant/cruciform/rituals/crusader.dm, code/modules/core_implant/cruciform/rituals/group.dm, code/modules/core_implant/cruciform/rituals/inquisitor.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/core_implant/cruciform/rituals/priest.dm
removes dead space
adds admin log for message
:cl:
/:cl:
=> removes some code dead spac

code/modules/tips_and_tricks/jobs.dm
=> Fixes a bad tip

code/datums/autolathe/guns.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
woops wrong names for guns
:cl:
/:cl:
=>  Ion Pistol

code/game/objects/items/weapons/implant/implants/explosive.dm
Using or getting emps is quick and easy for antags why punish them for using it?
:cl:
/:cl:
=> explosive implants are emp proof

code/game/machinery/portable_turret.dm
Turrets should now shoot people that they dislike and not shoot people people they do like
:cl:
/:cl:
=> turret AI fix

code/modules/projectiles/guns/energy/plasma.dm
Fix an issue where the plasma gun would keep consuming Coolant despite being unable to shoot due to lack of power.
=> Fix coolant issue with the experimental plasma gun

code/modules/projectiles/guns/energy/plasma.dm
1. Actually fix the coolant problem.
2. Set its damage multiplier to 1
3. Set its explosion to be the same as the Explosive Shotgun Shell.
4. Made the gun's explosion scale with the damage multiplier, if you mod it for max damage, you better be careful with it.
5. Made it use a wrench to remove the beaker instead of a screwdriver, to prevent removing the coolant when trying to remove a tool mod.
=> Changes a few things about the experimental plasma gun

code/game/machinery/portable_turret.dm
Turrets shouldnt be shooting the dead.
:cl:
/:cl:
=> Makes it so turrets stop killing the dead

code/modules/projectiles/guns/energy/plasma.dm
A line that became obsolete that I forgot to remove
=> Remove useless line

code/modules/mob/living/simple_animal/hostile/doomba.dm
Makes it so trip roombas and chem roombs work
=> Fixes some roomba attacks

code/game/objects/items/weapons/tools/simple_weapons.dm
Knifes being throw is now viable
:cl:
/:cl:
=> ups throwing knifes

code/controllers/subsystems/voting/poll_types.dm
End shift vote now propperly unlocks at 4 hours
You can vote more then once (duel votes do nothing)
You cant see the votes
You can unvote if you mess up your voting
Vote timer on fail can be called in 30 mins
Vote timer to vote in is now 90 seconds rather then 60
:cl:
/:cl:
=> Fixes votes

code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm
Girders are no longer safe for mob bashing, attacking a mob now makes it attack its confindments
super mob can now have range attacks
:cl:
/:cl:
=> range simples and more danger

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/modules/projectiles/guns/energy/stun.dm, code/modules/research/designs/weapon.dm
Renames the Hesta to Hera
:cl:
/:cl:
=> Hesta to Hera

code/game/jobs/job/medical.dm
Orderly and Psychiatrist now get the medical perk needed to bypass bio checks so they can do their jobs
:cl:
/:cl:
=> Orderly and Psychiatrist now get the medical perk

code/game/objects/structures/flora.dm
Makes trees only have 10 planks rather then 30...
:cl:
/:cl:
=> Trees no longer are op

code/modules/projectiles/guns/energy/ionrifle.dm
Ion pistol no longer requires doble hands
:cl:
=> Ion pistoldosnt need 2 hands

code/game/objects/items/weapons/power_cells.dm
this one is infact Soteria
:cl:
/:cl:
=> cell name fix

html/changelog.html
Zulu stepped down lets reflect that
:cl:
/:cl:
=> Admin update

code/modules/core_implant/cruciform/rituals/group.dm, code/modules/mob/language/ancient_latin.dm
All works of cum that are not for jokes into com
:cl:
/:cl:
=> People cant handle words

code/modules/projectiles/guns/energy/sst.dm
Ups the size of SST's to reflect how big their sprites
:cl:
/:cl:
=> SST size balance

code/modules/projectiles/guns/projectile/automatic/blackguard.dm
Fixes blackguard not able to take drums
Fixes desc for blackguard
=> fixes blackguard

code/modules/reagents/recipes/recipes_food_drinks.dm
No longer makes milkshakes
:cl:
/:cl:
=> Fixes icecream

code/game/objects/structures/stool_bed_chair_nest/bed.dm
Removes the lies and slander of compact roler beds
:cl:
/:cl:
=> no longer cheap and one use

code/game/mecha/mecha_construction/firefighter.dm
Turns out im a goof
:cl:
/:cl:
=> Fixes a bad tip for mechs

code/modules/client/preference_setup/loadout/lists/clothing.dm
=> KAZKIN PLEASE AT LEAST CHECK THE PRS BEFORE YOU MERGE THEM (actually adds balaclavas to loadout for real)

code/datums/craft/recipes/repairs.dm, code/modules/projectiles/guns/projectile/automatic/nordwind.dm
Solarian can now be fixed if sawn, rifle was fine
:cl:
/:cl:
=> doble var bad, and Solarian repair

code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/mob/mob_defines.dm
All mobs now can take "friendly to colony" useful for super mobs to not have consume drones attack chtmants
:cl:
/:cl:
=> fixes drones AI attacking chtmants

code/__DEFINES/perks.dm, code/datums/perks/racial.dm, code/modules/mob/living/carbon/human/species/forms/station.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm, code/modules/mob/living/carbon/superior_animal/fungi/fungi.dm, code/modules/mob/living/simple_animal/friendly/crab.dm
- Fix Tea's faction.
- Shroomlings and Drones can now go over table and railing
- Shroomlings will no longer try to eat Cht-mant.
- Remove Thermal perk
=> Misc changes

code/modules/mob/living/carbon/carbon_defines.dm
The other half of the code needed to stop drones/super mobs form attacking allied non-same faction
:cl:
/:cl:
=> Makes all carbons colony friend

maps/submaps/junk_field/j25_25/serbian/serbian1.dmm, maps/submaps/junk_field/j25_25/serbian/serbian2.dmm, maps/submaps/junk_field/j25_25/serbian/serbian3.dmm
-Added void wolf mobs to void wolf dungeons, making it more thematic.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Added void wolf mobs to void wolf dungeon

code/modules/mob/living/carbon/human/species/station/station.dm
Bit of a silly misstake, easy to make.
:cl:
/:cl:
=> Fixes hair

code/modules/mob/living/carbon/superior_animal/ai.dm
mobs no longer have xray
:cl:
/:cl:
=> sight lines

code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm, code/modules/mob/living/carbon/superior_animal/human/human.dm, code/modules/mob/living/carbon/superior_animal/roach/roach.dm, code/modules/mob/living/carbon/superior_animal/robots/robot.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
fixes super mobs attack sounds
Fixes some AI flags for combat targeting
:cl:
/:cl:
=> makes the AI fixes

code/modules/mob/living/carbon/superior_animal/life.dm
Allows Superior mobs to actually shoot at you.
The title says it all.
Tested and works on my server. No runtime.
=> Fixing Superior Mob Firing

code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm, code/modules/mob/living/carbon/superior_animal/robots/robot.dm
Title. the Junk Fields shall no longer be filled with corpses.
=> Make the space mobs space-proof

code/modules/clothing/spacesuits/void/station.dm
void suits even make shift are infact space proof
:cl:
/:cl:
=> makeshifts are now space proof

code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm, code/modules/mob/living/carbon/superior_animal/robots/robot.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm, code/modules/reagents/reagent_containers/food/cans.dm
makes gibbing modular for super mobs and fixes roombas gibbing into blood and guts
:cl:
/:cl:
=> likely fixes drones gibbing into roach blood

code/controllers/subsystems/machines.dm
Fixes a runtime and makes optimiation somehow
:cl:
/:cl:
=> ports a runtime fix

code/modules/reagents/reagent_containers/bidon.dm
Basically just force the bidon to check the possible reactions after removing its NO_REACT flag.
=> Fix the trigger stasis bidon's explosion

code/game/objects/items/weapons/power_cells.dm, code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm
All void wolfs and exl mobs now have a limited amount of ammo!
Mobs that run out of ammo will now if able to reload and drop old mags/cells
Running out of both mags and ammo, will force the mob into melee only.
:cl:
/:cl:
=> pew pew- click click click?!? Mobs now got to reload

code/modules/projectiles/guns/plasma/hydrogen.dm
Removes a doble var
:cl:
/:cl:
=> Does nothing

code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm, code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/friendly.dm
Make repairing the drones actually heal them.
=> Fix drone healing

code/modules/mob/living/carbon/superior_animal/roach/riding.dm, code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm, code/modules/mob/living/simple_animal/friendly/cat.dm, code/modules/mob/living/simple_animal/friendly/corgi.dm, code/modules/mob/living/simple_animal/friendly/crab.dm, code/modules/mob/living/simple_animal/friendly/farm_animals.dm, code/modules/mob/living/simple_animal/friendly/light_geist.dm, code/modules/mob/living/simple_animal/friendly/mouse.dm, code/modules/mob/living/simple_animal/friendly/roomba.dm
That way Vigil can parade his newly-tamed roach without it trying to eat anyone else.
=> Make tamed roach friendly to the rest of the colony

code/modules/mob/mob_movement.dm
Removes the prob 1 of slipping in space, mag bots dont prevent this or anything.
Its completely unfair, and not fun to deal with.
:cl:
/:cl:
=> Removes space slipping **again**

code/game/objects/structures/lattice.dm
Makes catwalks be made form lattices be 10x faster
:cl:
/:cl:
=> Faster catwalks

code/game/objects/items/weapons/power_cells.dm
-Fixes a pathing error with the self-recharging proc for manual battery chargers
Note: Did not test if manual chargers _actually work_. All this does is fix an issue someone pointed out.
=> Fixes broken manual chargers

code/modules/projectiles/projectile/bullettypes.dm, code/modules/projectiles/projectile/projectilegrenades.dm
Buffs its ion shot to be worth the cost
Makes the emp proc work on anything it hits rather then just people
:cl:
/:cl:
=> ARM ion fix

code/game/objects/items/oddities.dm, code/modules/client/preference_setup/loadout/lists/utility.dm
Adds each musically item to load out 
Fixes sci scanner in hand icon maybe
:cl:
/:cl:
=> music in loadout + sci scanner icon fix

code/modules/mob/living/carbon/superior_animal/life.dm
Fixes ranged mobs double shooting at the same time
:cl:
/:cl:
=> stops double range shooting

code/game/objects/structures/salvageable.dm
Lowers glass window spawns form scaving
Lowers RNG randomizers form scaving
:cl:
/:cl:
=> Tweaks rng of grayson gear scaving

code/game/objects/items/weapons/dna_injector.dm, code/modules/hivemind/mobs.dm, code/modules/mob/living/carbon/superior_animal/fungi/types/mushroom.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm, code/modules/mob/living/carbon/superior_animal/life.dm, code/modules/mob/living/carbon/superior_animal/lodge/lodge.dm, code/modules/mob/living/carbon/superior_animal/lodge/types/cerberus.dm, code/modules/mob/living/carbon/superior_animal/lodge/types/clucker.dm, code/modules/mob/living/carbon/superior_animal/lodge/types/tatonka.dm, code/modules/mob/living/carbon/superior_animal/roach/roach.dm, code/modules/mob/living/carbon/superior_animal/robots/robot.dm, code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/custodian.dm, code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/roomba.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/simple_animal/hostile/hivebot.dm, code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm, code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm, code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm, code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
Most if not all mobs now have correct blood type
Loge pets no longer drop roach meat
Roomba's with guns no longer have endless ammo
Injectors now should work on spawn
EMPs now properly deal damage to mobs that take EMP damage
Grayson mech no longer is EMP-able
Misc other meat fixes
Grayson flame bot no longer will be to far away form you to hit you with its fire
Emp on EMPable mobs are even more affective now deal more damage
:cl:
/:cl:
=> Loads of mob fixes

code/modules/projectiles/projectile/special.dm
Make the anti-slime gun actually kill slimes.
=> Fix the slimegun

code/datums/autolathe/clothing.dm
I forgot to do like half of the code for it
:cl:
/:cl:
=> fixes SI made hood and suit disk

code/modules/client/preference_setup/loadout/lists/utility.dm
Fixes loadout for guitars
:cl:
/:cl:
=> corrects names of loadout gear

code/game/machinery/biogenerator.dm, code/game/machinery/doors/blast_door.dm, code/game/machinery/vendor/misc_vendors.dm, code/game/objects/structures/burrows.dm, code/modules/power/solar.dm
Adds the new clothing to the clothing vender by Seb aka @Gundam Tanaka#9565
Fixes biogenes leather to be leather and ups the cost
Looking at soloars now gives you an idea what glass is inside them based on power level
Blast doors that are round start open should not longer be bugged
Making soloars now shouldnt brake them at 20%
Borrows now should when open be layered above filth, catwalks and other misc things to not hide as much
:cl:
/:cl:
=> few things that are long over dew

code/datums/helper_datums/construction_datum.dm, code/game/mecha/mecha_construction/durand.dm, code/game/mecha/mecha_construction/firefighter.dm, code/game/mecha/mecha_construction/gygax.dm, code/game/mecha/mecha_construction/odysseus.dm, code/game/mecha/mecha_construction/phazon.dm, code/game/mecha/mecha_construction/ripley.dm
Make the exosuits give points when building them.
Ripley give 10k.
Firefighter give 15k.
Oddysseus give 17.5k.
Durand give 20k.
Gygax give 25k.
Phazon give 50k.
=> Make exosuit give points

code/game/objects/items/devices/scanners/mass_scpectrometer.dm
Now it has a cog bypass + correct flags
:cl:
/:cl:
=> fixes mass spectrometers

code/modules/mob/living/carbon/superior_animal/defense.dm
Mobs now will wake up if attacked if they were inactive
Mobs now when dead will go inactive, likely a good opination trick 
:cl:
/:cl:
=> Better reactions and optimation 

code/modules/research/nodes/greyson.dm
fixes greyson prosthesis node, form 14 bio of 13 to 13 of 13
=> fixes greyson prosthesis node

code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/living_powers.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/simple_animal.dm
Better optimize mob AI turn off and on
Super mobs when ranged can now be controled and shoot
simple/super AI mobs when controled can have their AI turned on and off
simple/super AI mobs when controled can forceully attack area
:cl:
/:cl:
=> shooting and more meelee

code/game/objects/structures/burrows.dm
Borrows now will properly be layered ABOVE catwalks
:cl:
=> borrow layering fix

code/modules/clothing/suits/costume.dm
Bunny outfit now is not invisable
:cl:
/:cl:
=> fixes costume icon

code/game/objects/structures/crates_lockers/closets/secure/militia.dm
Blackshield corpsmancan now claim the corpsman locker
:cl:
/:cl:
=> fixes corpsman locker

code/game/objects/effects/spawners/ghostroles.dm, code/game/objects/effects/spawners/ghostspawner.dm, sojourn-station.dme
ports the tools and needed coded for ghost role spawners, From Eris that was ported form TG.
:cl:
/:cl:
=> ghost role spawners

code/modules/reagents/machinery/chem_dispenser.dm, code/modules/reagents/reagent_containers/borghydro.dm, code/modules/reagents/reagent_dispenser.dm
Admin only mead keg for hunter events or the like
adds fernet to the borg and beer dispeners
moves pineapple juice form booze dispender to soda
:cl:
/:cl:
=> More fernet and mead keg

code/modules/projectiles/guns/projectile/pistol/colt.dm
Colts that have all their icons set can now legitmently have the silencer
:cl:
/:cl:
=> fixes missing tag for colts

code/game/objects/items/weapons/hydrogen_fuel_cell.dm, code/game/objects/random/science.dm
Add the hydrogen fuel cell and the hydrogen fuel table to one random loot spawner.
Also allow the fuel cell to be recycled for 5 plasteel, 1 Metallic Hydrogen, 1 Osmium and 1 Tritium.
=> Give hydrogen fuel cell a chance to spawn

code/game/atoms.dm, code/modules/lighting/lighting_atom.dm
=> Update lighting_atom to remove light code

code/modules/core_implant/cruciform/rituals/path.dm, code/modules/core_implant/cruciform/rituals/priest.dm
-Renamed some of the factorial litanies
-Fixed a factorial bug.
-Adjusted the charge rate so it doesn't take years.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Factorial adjustment

code/modules/power/cell.dm
-In the event a rigged cell doesn't implode, we should now be able to directly open the variables of them and modify them as needed to prevent log spam.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Power Cell Hotfix

code/game/objects/items/devices/t_scanner.dm
Conistanty with other sprites that get swapped to be eris then SoJ
:cl:
/:cl:
=> Swaps default icon to Eris's for t-ray scanner

code/modules/core_implant/cruciform/rituals/priest.dm
Primes can now spawn factorial magic cups as they are meant to
:cl:
/:cl:
=> You can now summan factorial magic cups

code/modules/mob/living/carbon/superior_animal/superior_animal.dm
reload messages are now for reals fixed
:cl:
/:cl:
=> fixes reload messages for reals

html/changelog.html
Adds in HeadAdmin section
corrects and cleans up admin/moderator list
:cl:
/:cl:
=> fixes mod/admin listing

code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm, code/modules/mob/living/carbon/superior_animal/human/human.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/carbon/superior_animal/vox/vox.dm
Reverts sojourn-13/sojourn-station#1661
=> Revert "Fix the waring faction thing."

code/controllers/subsystems/jobs.dm, code/defines/procs/announce.dm, code/modules/clothing/suits/greatcoat.dm
Gives the Premier, BS Commander and Warrant Officer cloaks coverage more befitting their size, no longer making them straight downgrades from other armor these particular roles already have access to. 
Also adds a fix for alt-titles not announcing over the radio properly. 
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Council greatcoat changes + alt-title announcements

code/modules/projectiles/guns/energy/laser.dm
This buff the laser gun, at @Trilbyspaceclone's request, that security borgs get with the illegal module, due to it being weaker than a 'weak' energy beam.
=> Buff the borg's laser gun.

code/game/objects/items/weapons/grenades/spawnergrenade.dm
We can't have nice things.
Reduce the number of roombas in the roomba-nade from 3 to 1.
=> We can't have nice things.

code/modules/mob/living/silicon/robot/robot_items.dm
Standered and miner borg omni tools now have their screwdrivers built into the omni tool
:cl:
/:cl:
=> regives screwdrivers

code/ATMOSPHERICS/components/binary_devices/pipeturbine.dm
Try to fix the turbine's power connection problem at Trilby's request.
=> Try to fix the turbine's power connection problem.

code/game/objects/structures/flora.dm, code/modules/hydroponics/grown.dm
Fixes cutting plants like grass and flowers
:cl:
/:cl:
=> fixes harvesting

code/datums/craft/recipes/furniture.dm, code/game/objects/structures/firepits.dm
At @Kazkin's request, redo the whole bonfire, hopefully in a way that doesn't OOM.
=> Redo the bonfire

code/game/objects/items/devices/scanners/reagents.dm
Advanced reagent scanners now have a cog bypass of 30 and a bio of 15
Advanced reagent scanners now properly also check for perk AND stat requirements
:cl:
/:cl:
=> fixes advanced scanners again

code/modules/reagents/recipes/recipes_slime.dm
Well the reactions still work somehow the backend code was a bit wrong
:cl:
/:cl:
=> Fixes some bad paths

code/modules/mob/living/silicon/robot/robot_upgrades.dm, code/modules/research/nodes/illegal.dm
illegal borg upgrades are now called Overclocked Borg upgrade to reflect that its not illegal
:cl:
/:cl:
=> its not illegal

code/modules/stashes/stash_types/weapons.dm
=> fixes stashes

code/modules/mob/living/carbon/human/human.dm
Sets feet blood DNA to null upon cleaning
Meaning that washing feet form oil/blood will actually wash feet
:cl:
/:cl:
=>   Contributor fludd12

code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
adds the blackshield cap and blackshield beret to loadout options. This time without breaking something!
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Blackshield loadout

code/game/objects/items/weapons/tools/hammer.dm, code/game/objects/items/weapons/tools/shovel.dm, code/game/objects/items/weapons/tools/simple_weapons.dm
Nailed stick
Hammers
Shovels
all deal 2x damage to spider allied things. As spiders are infact weak to crushing damage
=> spiders are weak to crushing

code/modules/telesci/telepads.dm
Telepads are now longer able to be dragged
=> fixes mapped telepads form being dragabale

code/game/area/areas.dm, code/modules/client/preference_setup/global/preferences.dm, modular_sojourn/area_blurbs.dm, sojourn-station.dme
Adds blurps for when you enter an area form bearrrrrrrr
=> area blurps

code/modules/projectiles/projectile/bullettypes.dm
The 30mm ball round no longer deals 0 damage
:cl:
/:cl:
=> Fixes ball rounds

code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/projectiles/ammunition/bullets.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/guns/projectile.dm
Fixes a runtime when ghosts/mobs look at guns without stats
Fixes .70 jet rounds being 20mm
Fixes firing spent bullets
:cl:
/:cl:
=> fixes bullets and runtime

code/modules/projectiles/projectile/bullettypes.dm
=> derfs ball changes

maps/CEVEris/_Nadezhda_Colony_Underground.dmm
Revamps the medical area to look nice
=> H's changes

code/modules/projectiles/guns/projectile/automatic/blackguard.dm
Was missing GUN_PROJECTILE,
:cl:
/:cl:
=> Fixes blackguad tags

code/modules/reagents/reagents/drugs.dm, code/modules/reagents/reagents/other.dm
-Added a better player display of adminodrazine to be used more realistically IC
-Cerebrix is now liquid when formed.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Slight fix

code/datums/craft/recipes/tools.dm, code/datums/craft/recipes/weapon.dm
You once more can craft shields form trash carts
Better organization of crafting tools
:cl:
/:cl:
=> readds shield trash cart things

code/game/objects/items/oddities.dm, code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm, code/modules/mob/living/carbon/superior_animal/lodge/types/cerberus.dm, code/modules/mob/living/carbon/superior_animal/lodge/types/tatonka.dm, code/modules/projectiles/gun.dm
Fixes runtimes in hunter mobs
Fixes runtimes when ghosts look at some objects/mobs
Fixes needing the SI perk AND 90 cog to look at the sci scanner
:cl:
/:cl:
=> more runtime fixes

code/modules/projectiles/guns/plasma/hydrogen.dm, code/modules/projectiles/guns/plasma/welder.dm
Allow hydrogen-plasma stuff to take tool upgrades
I can't guarantee that some upgrades will work fine though.
=> Allow hydrogen-plasma stuff to take tool upgrades

code/game/machinery/tesla_turret.dm
=> Replace the tesla turret defines with something that doesn't conflict

maps/CEVEris/_Nadezhda_Colony_Transition.dmm, maps/CEVEris/_Nadezhda_Colony_Underground.dmm
Makes lower colony and transet so much more detailed like all the details
=> so much detail

code/modules/organs/internal/psionic.dm, code/modules/psionics/psion.dm, code/modules/psionics/psionic_items.dm, code/modules/psionics/standardpowers.dm
-Added a check to see if your psi points is higher than your max pool,  correcting it to the max amount with each process check.
-Added/cleaned some of the notes in the psion menus to be more clear.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Minor Psion adjustments

maps/CEVEris/_Hunting_Lodge.dmm, maps/CEVEris/_Nadezhda_Colony_Underground.dmm
Fixes bad flooring parring
Fixes few bad decal options
New cyborg charger inside hunters cabin
Removes Queen
=> Floor fixes

code/game/mecha/mecha_construction/durand.dm, code/game/mecha/mecha_construction_paths.dm
<details>
<summary>
Rewrites the construction text and descriptions for the Durand exosuit
</summary>
<hr>
The basic installation actions were out of order- they've been reordered to make sense to someone operating on them.
The the unused 'remove' actions were reordered and remade so they shouldn't create items at wierd times if they are ever implemented.
<hr>
</details>
:cl:
Fixed descriptions on the Durand.
/:cl:
=> Durand Rewrite

code/game/mecha/combat/gygax.dm, code/game/objects/items/weapons/autolathe_disks.dm, code/game/objects/structures/crates_lockers/closets.dm, code/modules/economy/price_list.dm, code/modules/multiz/structures.dm, code/modules/trade/datums/_trade_station.dm, code/modules/trade/datums/trade_stations_presets/KriosanConfederacy.dm, code/modules/trade/datums/trade_stations_presets/McRonalds.dm, code/modules/trade/datums/trade_stations_presets/asterstradecapital.dm, code/modules/trade/datums/trade_stations_presets/bluespace_tech.dm, code/modules/trade/datums/trade_stations_presets/boozefood.dm, code/modules/trade/datums/trade_stations_presets/cybernetics.dm, code/modules/trade/datums/trade_stations_presets/fs_weapon_factory.dm, code/modules/trade/datums/trade_stations_presets/mecha.dm, code/modules/trade/datums/trade_stations_presets/nt_cruisers.dm, code/modules/trade/datums/trade_stations_presets/trash_refine.dm, maps/CEVEris/_Nadezhda_Colony_Underground.dmm
Trade ships will no longer be insain with their requests
Dark Gygax no longer has a teleporter
Ammo no longer sells for insain prices
Crates should be fixed now when deconing them will hopefully now detete properly
All disks no longer have blank in the name
Fixes some more bad tiles
Lonestar now has their own disk for CEO 
Lonestar vault now has some materals to start with for shift start deal trading. Or robberies
stairs and ladders can no longer be nuked
:cl:
/:cl:
=> ecomandstuff

code/game/objects/items/stacks/tiles/tile_types.dm
=> Tweak copy tile with cyborg 

code/game/objects/items/weapons/tools/_tools.dm, nano/templates/tool_stats.tmpl
Ports form Eris that tools show AP as they should let you know
Contributor
vode-code
=> Tools show AP vaules

code/game/gamemodes/events/blob.dm
Contributor
SirRichardFrancis
Commits out blob exspand verb as its broken
=> People can no longer force blob to exspand

code/game/objects/structures/kitchen_spike.dm
Contributor
SirRichardFrancis
Makes spiked people no longer delete all items they had
=> Spikes no longer null everything on a person

code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
Contributor
vode-code
Turns out the radiation bile bite thing didnt check armor
=> Kaiser now checks armors

code/game/machinery/doors/airlock.dm
=> Fixes airlocks

code/game/machinery/jukebox.dm, code/game/objects/items/musictapes.dm, code/modules/media/media_tracks.dm
From Contributor
drexample
Coverts all music list lists into GLOBs
=> music GLOB

code/game/mecha/combat/durand.dm
Why would the Durand's Scattershot start loaded but not its AC-2 ?
=> Make the durand's AC2 start loaded

code/modules/reagents/reagents/drugs.dm
Mana potion now requests properly 5u or more rather then less then 5u
=> Mana Potion nerf

maps/CEVEris/_Nadezhda_Colony_Surface.dmm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
add: Colony shield generator room.
del: Surface emergency tool storage.
/:cl:
=> Colony shield generator

code/game/objects/random/mecha.dm
gygaxes are now more rare then duhands
death riply is no longer rarer then a real combat mech
=> Tweaks mech spawning

code/modules/paperwork/photocopier.dm
Borgs and AI no longer use 5 toner per printing their papers and photos
=> toner reduction

code/game/objects/items/oddities.dm
New level of Oddity for examine
=> Reality Bending level

maps/CEVEris/_Nadezhda_Solar_Area.dmm, maps/encounters/deeptunnels/_Nadezhda_Deep_Tunnels.dmm
<details>
<summary>
1. 	There was way too many advanced tools spawners in the guild dorms.
2. 	Added the toxins lab test range for Soteria.
</summary>
<hr>
<hr>
</details>
:cl:
balance: Removed a lot of random spawners in the guild dorms.
fix: There were two windows on top of each other, it's fixed.
tweak: Moved two cable coils, since they were inaccessible.
tweak: Silenced the intercom microphones.
add: Soteria toxins lab test range.
/:cl:
=> Minor fixes and tweaks to the guild residential complex

code/__DEFINES/qdel.dm, code/game/machinery/autolathe/artist_bench.dm, code/game/objects/items/weapons/clown_items.dm, code/game/objects/items/weapons/dna_injector.dm, code/modules/food/recipes_microwave.dm, code/modules/gambling/slot_machine.dm, code/modules/reagents/reagent_containers/food/snacks.dm, code/modules/reagents/reagents/food-Drinks.dm, code/modules/reagents/recipes/recipes_food_drinks.dm, code/modules/research/xenoarchaeology/finds/finds.dm
Eliminates some unnecessary and repetitive bits of code for improvement
**NOTE:** Certain macros are conflicting with pre-defined ones (Artist Bench and Tesla Turret), but I'd rather ask for confirmation before touching those two as I have no idea if the artist bench will properly call for the adequate caliber macros when crafting. Tesla turret is just merely a matter of renaming macros to something that does not conflict, but as those get undefined by the end of file they shouldn't pose a real conflict.
Please comment below if you're better informed than I am on these two macro defines so I don't accidentally go deleting stuff that actually works. Specially the Artist's bench.
- Kvass can now be crafted by combining Flour and Ethanol in equal parts in presence of 5u of Universal Enzyme
- …
=> Code cleanup + fixes

maps/CEVEris/_Nadezhda_Colony_Underground.dmm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
add: New bar main room, with side rooms, a fireplace (locked and secured), books, dining tables and more.
/:cl:
=> New bar main room

code/game/objects/items/weapons/shields.dm, code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm
Allows shields to now block mob attacks.
You will block 100% of the incoming damage and effects that come with that damage so long as you can block. Knockdown effects like the roach trip will still go through.
You can block so long as you are at 50 or less HALLOSS damage.
You receive HALLOSS damage and shield durability damage based on your toughness. If you're tougher, you can block for longer and use the shield better.
Examining the shield gives you an idea of its condition.
HALLOSS damage is healed automatically over time, three times quicker if resting or sleeping. 
In the future we may improve blocking and calculations / durability are subject to change: I need to see it in action on live before I know how to balance it.
Tested on my server, should work as expected.
=> Shields are able to block mob attacks now.

code/game/jobs/job/church.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Custom Vector job names

code/modules/core_implant/cruciform/cruciform.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_species.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/mob_defines.dm, code/modules/psionics/psion.dm, code/modules/psionics/standardpowers.dm, maps/encounters/deeptunnels/_Nadezhda_Deep_Tunnels.dmm
Prevents church records form seeing manniquins
prevents people form messaging manniquins
=> needs testing

code/game/objects/items/devices/organ_module/active/custom.dm, sojourn-station.dme
Add an implant that you can insert any item to extend/retract into your arm, just like an armblade.
Can fit anything from hydrogen-plasma cannons to the Absolute Bible.
=> Add custom object implants

code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/organs/organ.dm
Ports over eris's correction to looping deaths
=> stops death loops

code/modules/projectiles/guns/projectile/shotgun/bull.dm
Corrects the missing doble sprite missing on the bison and bull
=> bull icon correction

code/modules/psionics/psionic_items.dm
-Was a little weak due to purple coloration.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Upped hood light
