sojourn-13/sojourn-station

code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/life.dm
code/modules/mob/living/carbon/superior_animal/roach/types/emp.dm
code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
code/modules/mob/living/carbon/superior_animal/roach/types/plasmaroach.dm
code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm
code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
code/modules/mob/living/carbon/superior_animal/robots/robot.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/church/church.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/roomba.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/termite/termite.dm
code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
code/modules/mob/living/carbon/superior_animal/vox/ai.dm
code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
code/modules/mob/living/carbon/superior_animal/xenomorph/ai.dm
code/modules/mob/living/carbon/superior_animal/xenomorph/attack.dm
code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoMega.dm
code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoRobust.dm
code/modules/mob/living/simple_animal/simple_animal.dm
sojourn-station.dme

Cleans much more mob files to be standerd code
Xenos are also now fire proof as they are space and heat proof already
Optimizes some more mob checks to have fast returns or to make sure that they are not wasting as much processing power on things they really shouldnt

Cleaner code and more optiomation

---

code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/simple_animal.dm

Fixes simple mobs keeping their target on death

Simple mobs now also clear their target on death

---

code/__DEFINES/admin.dm

Title. Not a good var to copy between entities.
:cl:
code: Added computer_id to the banned var list for var copies
/:cl:

Adds another var to the banned var list

---

code/modules/clothing/head/misc.dm
code/modules/clothing/suits/storage.dm

fixes numerical and cardigan icons

---

code/game/gamemodes/events/hivemind_invasion.dm

Fixes natural spawning of hivemind being bugged and only false alarming
Even tested

hivemind event spawning fixes

---

code/modules/mob/living/carbon/human/human_damage.dm

Probably fixes a runtime issue when someone is missing their liver.

Fix for the Liverless

---

code/game/machinery/deployable.dm
code/game/objects/structures/grille.dm
code/game/objects/structures/low_wall.dm

Reworks how bullet cover works for grills, low walls and baracades
bullets now when moving over low walls like with grills and baracades will now dry check to be blocked
Well next to a low wall this check is re-ran so cover is more viable
Redid grill math so that its constant with are numbers for damage
That stated a lot of cover now has less health to compensate for the added odds

duck and cover

---

code/game/objects/effects/chem/water.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/pepper.dm

Buffs pepper spiders by making their spray's speed var go from ten to var, a significant improvement in its speed. Before, the spray was painfully slow. Now it's about as fast as the spider itself.
This is good, because you could easily just outrun the spray. Again, you no longer can.
:cl:
balance: Pepper spiders now have a faster spray.
/:cl:

Small pepper spider buff, increases the speed of their spray

---

code/game/objects/random/entity_spawners/entity_spawner.dm

I could only make this PR now.
:cl:
none needed DONT PUT THIS IN CHANGELOGS THIS TRILLBY
/:cl:

Makes entity spawners test projectile compatible.

---

code/game/objects/items/weapons/emp_mine.dm
code/modules/tables/interactions.dm
modular_sojourn/shields.dm

hmgnhgh
needed for functionality
<hr>
</details>
:cl:
fix: fixed trace projectiles more
/:cl:

a few more !testing checks

---

code/modules/admin/verbs/buildmode.dm

i fucking hate this code
blah blah blah it does what it says in the title
:cl:
fix: buildmode no longer deletes its own icons if you right click it
/:cl:

Fixes buildmode deleting its own icons

---

code/modules/mob/living/carbon/human/human_damage.dm

Probably fixed the missing organ runtime now.

Fixing GoatMed Again

---

code/modules/mob/living/carbon/human/human_damage.dm

I told goat the problem would need this check, they didnt add the check, Im doing it for them
:cl:
fix: Fixes a runtime that almost definitely wouldve happened
/:cl:

actually fixes this fucking runtime

---

code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/attack.dm
code/modules/mob/living/carbon/superior_animal/roach/roach.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/superior_defines.dm
code/modules/projectiles/projectile.dm

Adds a var and some logic that makes it so mobs have a percent chance to fire if they would hit a friendly. Testing shows it works with no runtimes.
Also makes ranged mobs actually use burrows.
:cl:
add: Mobs now only have a small chance to fire if they would hit a friendly.
fix: Ranged mobs can now use burrows.
/:cl:

Mobs now avoid friendly fire, and also work better with burrows

---

code/modules/mob/living/simple_animal/hostile/bear.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm

And a small number tweak on speed buff for bears

Fixes some mob AI stuff I broke

---

code/__DEFINES/perks.dm
code/game/objects/items/oddities.dm
code/game/objects/random/psi_loot.dm
code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm
code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiImpressive.dm
code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiMega.dm
code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiTrash.dm
code/modules/psionics/psionic_items/psi_weptools.dm
sojourn-station.dme

Deepmaints now when ever oddites spawn inside it will role higher numbers 
Deepmtains oddites now never have bad perks 
Deepmaints monsters drop deepmaints tools and weappns
Deepmaints tools and weapons are simular to psion ones but are slightly better and rounded numbers making going down into deepmaints more worth it to fight the monsters and gain loot

Oddites and Deepmtains

---

code/__DEFINES/admin.dm
code/__DEFINES/topic.dm
code/modules/admin/admin.dm
code/modules/admin/verbs/massmodvar.dm
code/modules/admin/verbs/modifyvariables.dm

Just protects two very important global lists.
:cl:
no changelog
/:cl:

Implements global var protection, GLOBAL_PROTECT(), and fixes a admin elevation exploit

---

code/modules/modular_computers/file_system/news_article.dm
news_articles/kros_news_ii.html

Event precuser 2 for the krosin arc

newsardical

---

code/datums/stat_modifiers/modifiers/mob/superior/ranged/ranged_modifiers.dm

im dumb.
:cl:
fix: Make slowdraw actually slow the mob's reaction
/:cl:

Fixes a prefix

---

code/modules/clothing/head/helmet.dm
code/modules/clothing/spacesuits/rig/rig_pieces.dm
code/modules/clothing/spacesuits/rig/suits/light.dm
code/modules/materials/material_sheets.dm
code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm

<details>
<summary>
Light RIGs(such as steward RIG, hacker RIG, etc) can now store a backpack on their suit slot, same as others.
Additionally, they can deploy over gloves+boots, same as other RIGs.
WO helmet has had its seams stitched in and will hide ears, hair, etc same as the other Marshal full helms.
Recoll now sells a full stack of plasma-glass as advertised, rather than ripping you off and giving only a single sheet.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Various fixes.

---

code/modules/mob/living/carbon/superior_animal/ai.dm

GUESS WHO PUT A BASE RETURN TRUE ON A CRUCIAL PROC FOR NO REASON
ME
:cl:
fix: Superior mobs should hopefully no longer attack mechs randomly.
/:cl:

Fixes mobs attacking mechs.

---

code/game/objects/items/weapons/storage/hardcases.dm
code/game/objects/items/weapons/storage/marshal_kits.dm

Trauma Team now start with a little box that lets them pick between the OP rig and the probably equally OP paramedic armor.
Also moves some stuff around for sanity sake.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

More TT adjustments

---

code/game/machinery/tesla_turret.dm

Tesla Turret no longer prints a message to admins EVERY SINGLE TIME it fires. It still logs attacks.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Tesla turret.

---

code/controllers/subsystems/trade.dm

Fixes check_offer_contents() so reagents are checked properly.
<hr>
</details>
:cl:
add: adds reagent check to check_offer_contents()
/:cl:

Fixes reagent check in trade program

---

code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm

Recoll trade station learned how much flares are worth on a open market

Fixes a bad flare inbalance

---

code/controllers/subsystems/trade.dm
code/game/objects/items/weapons/stock_parts.dm

Stockpart selling has been rebalance after small issues of the people before hand not understanding rating is a flat times - Woops
Trade stations now more sus of traded and items and now check for surplus tag

Reduces stockparts and stuff

---

code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm

USE . = ..() PLEASE GOD
<hr>
</details>
:cl:
fix: fixed kaiser roach targetting
/:cl:

fixes kaiser roach targetting

---

code/game/gamemodes/events/carp_migration.dm
code/game/gamemodes/events/rogue_drones.dm
code/modules/clothing/head/helmet.dm
sojourn-station.dme

Carp no longer mass-spawn at windows, ditto with the drone event. They'll simply look for 'grass' turfs in the forest area of the upper level, they shouldn't spawn inside the walls.
Ups the amount of carp per wave given how much more spread out they are.
Gives the WO helmet the same stats as the vest, it bugged me that it had different stats. - also restores the bio that i accidentally nicked off of it <:)
re-enables appendicitis, idk if it actually will spawn naturally 
\
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Random Event changes

---

code/modules/mob/living/living_defense.dm

Projectiles no longer need 200% ap to deal full damage

Bullet balance

---

code/game/objects/items/weapons/tools/mods/_upgrades.dm

Gun mods now show you if it deals pve damage
gun mods that increase pve damage now do that

Fixes pve multyplier and gun mod descs

---

code/__DEFINES/damage_organs.dm
code/modules/mob/living/carbon/human/human_damage.dm

Used in a forthcoming PR. Adds psy damage to apply_damage().
:cl:
add: Added psy damage handling
/:cl:

Adds psy damage handling to human mobs

---

code/game/objects/effects/effect_system.dm
code/modules/projectiles/guns/projectile/dartgun.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
- Artemis Chem darts that can't inject, splash the target
- Made the UI "Better"
- Failed to make the UI Better but it's just as bad as it was previously
- Tweaked chem explosion code a bit
/:cl:

Splashing Darts

---

code/game/machinery/atmoalter/scrubber.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

replaces stealpots helms in blackshield prep with blackshield maska
adds in siegs atmos regulator for n2

maska and tree of dog

---

code/modules/reagents/reagents/medicine.dm
code/modules/reagents/reagents/stims.dm
code/modules/reagents/recipes/recipes.dm

New chem thats insainly hard to make, but when made can revive a dead person without any drawback if adminstered within 1 min

The best chem

---

code/modules/mining/drilling/drill.dm

Drills now when dieing stop termites controlers like intented
Drills now when dieing remove its soul

termite sanity

---

code/modules/reagents/reagents/nanites.dm

By [Jamini](https://github.com/Jamini)
Adjusts nanite chems to be a bit cleaner/simpler and above all...functional
By CDB
Increases nanite stats so they are viable

Occult port

---

code/game/objects/items/weapons/implant/implant.dm
code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm
code/modules/psionics/psion.dm

Psions now accully reject implants as intented
Psions will not eject carrion spiders as they are not metal/whatever

makes it so psions as intented cant be implanted

---

code/modules/mob/living/carbon/superior_animal/lodge/lodge.dm

Reverts sojourn-13/sojourn-station#3754

Revert "pat"

---

code/datums/autolathe/ammo.dm
code/game/machinery/autolathe/fabricators.dm
code/game/objects/items/weapons/autolathe_disk/marshal.dm
code/modules/projectiles/ammunition/bullets.dm
code/modules/projectiles/guns/projectile/other/lenar.dm
code/modules/projectiles/projectile/projectilegrenades.dm

New 40mm grenades, Stingers! Available from the Marshals disk or Artificers guild.
Lenar now properly has two hand code to go with the sprites it has.
Also fixes the bulletfab not taking refined scrap as previously advertised, whoops <:3c
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

More nonsense

---

code/game/gamemodes/events/infestation.dm

Termites now properly spawn infestations
Removes 4 fake infestation picks to non-hostile mobs
Increases some mobs spawns in infestation

Better infestions

---

code/modules/projectiles/guns/projectile/automatic/freedom.dm
code/modules/projectiles/guns/projectile/automatic/nail_gun.dm

Freedom autopistol now has proper gun tags

fixes freedom tags

---

code/__DEFINES/perks.dm
code/datums/outfits/jobs/ghostroles.dm
code/datums/perks/job.dm
code/datums/perks/racial.dm
code/game/objects/effects/spawners/ghostroles.dm
code/game/objects/items/weapons/cards_ids.dm
code/game/objects/items/weapons/storage/belt.dm

Adds in the genetic Auditor spawner for command people to be
Adds in a perk to change the name of said Auditors (you should still change your spawned person)
Adds in a guild ERT person as well

Guild and genetic spawners

---

code/game/machinery/excelsior/blackshield_teleporter.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm
code/modules/projectiles/guns/projectile/automatic/ak47.dm
code/modules/projectiles/guns/projectile/automatic/duty.dm
code/modules/projectiles/guns/projectile/automatic/lmg.dm
code/modules/projectiles/guns/projectile/automatic/vintorez.dm

Since I am rather annoyed that anything unqiue given to Marshals or any-other department, from sprites to guns, gets near copied by Blackshield - I've balanced Blackshield out. Bullet points are as follows.
- Blackshield armor had higher armor values than Marshals, Rangers, or base loot armors. Blackshield are a Militia - they should be using cheap-stuff, as in nothing better than normal armor values. **I have balanced them by either making them identical to base armors, or having trade offs to base armors and equaling the same overall points.** (Ex - normal armor has 30, 25, 30 - BS get more bullet protection, so 25, 40, 25 instead. Same amount of point allocation.)
- Altyn helmets, across the board, have received a _slight_ buff. Ballistic bullet proof helmets aren't as good as BS ones. …

Blackshield Balancing

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
Restores the fax machine to brig. Used to contest charges properly just incase.
</summary>
<hr>
<hr>
</details>
:cl:
add: Adds fax machine to brig.
/:cl:

Brig Fax Machine

---

code/game/objects/structures/inflatable.dm

Fixes inflatable walls and doors not blocking air
closes #3780

fixes inflatable walls + cleaner code

---

code/modules/client/preference_setup/loadout/lists/factionsoteria.dm

closes #3779 
Fixes Soteria Client Recovery Specialist faction items not being selectable in loadout

fixes the faction medical items

---

code/modules/client/preference_setup/loadout/lists/utility.dm

<details>
<summary>
Adds a multicolored pen to the loadout under Utility
</summary>
<hr>
The multicolored pen costs 1 point, could also make it 0, not 100% sure on the guidelines for loadout costs.
<hr>
</details>
:cl: A Concerned Citizen
add: Adds a multicolored pen to the loadout under Utility
/:cl:

Adds multicolored pen to the loadout menu

---

code/modules/mob/living/carbon/superior_animal/roach/life.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Emergency turns off all roach breeding while we figure out why they broke the server by making 10k of themselves
/:cl:

no more roach splosion

---

code/modules/mob/living/carbon/superior_animal/roach/life.dm

Reverts sojourn-13/sojourn-station#3787

Revert "no more roach splosion"

---

code/game/objects/effects/spiders.dm
code/modules/mob/living/carbon/superior_animal/roach/life.dm

Maybe makes spiderlings die when eaten

untested roach fic

---

code/game/objects/items/weapons/grenades/grenade.dm

What the actual fuck even was this. They work fine without it.
:cl:
fix: Removed some eldritch code that was breaking grenades.
/:cl:

Removes some cursed code that was breaking grenades.

---

code/__HELPERS/game.dm
code/controllers/subsystems/processing/mobs.dm
code/game/atoms.dm
code/game/turfs/turf.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/say.dm
code/modules/mob/observer/ghost/ghost.dm

Optimizes saycode by reducing the amount of mobs iterated through every time the proc runs by ~80%.
Optimizes other code by adding as anything to procs that can survive it.
:cl:
code: Micro-optimizes many parts of the code, majorly optimizes saycode
/:cl:

A bunch of micro-optimizations (and maybe one significant one)

---

code/modules/admin/verbs/buildmode.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm

god i hope this works why is this even needed how is a mob bypassing the death checks and the ai inactive checks what the fuck is happening
:cl:
fix: FUCK
/:cl:

A desperate fix for fucking runtimes

---

code/modules/mob/living/say.dm

Why do your damn coordinates get set to 0 when you enter a container.
<hr>
</details>
:cl:
fix: Talking now works in containers
/:cl:

Potentially fixes a bug with saycode

---

code/datums/observation/moved.dm
code/game/atoms_movable.dm

Reverts sojourn-13/sojourn-station#3806
it runtimes too much

Revert "THIS IS THE WORST FUCKING CODE I HAVE SEEN. FIXES. A GODDAMN. SAYCODE ISSUE. AMONG OTHERS."

---

code/modules/mob/living/say.dm

WHY DO YOU DO THIS TO ME ERISCODE
WHY LITANIES
:cl:
fix: litanies are fixed. i h ope. god.
/:cl:

holy SHIT i hate saycode (hotfix)

---

code/modules/aberrants/organs/design_disks/disks.dm
code/modules/aberrants/organs/internal/dependent.dm
code/modules/aberrants/organs/machinery/medi-sarcophagus.dm
code/modules/aberrants/organs/machinery/organfridge.dm

Miscellaneous bug fixes for organ gaming.
:cl:
fix: Fixed organ freezer and organ vendor sprite issues
fix: Fixed medi-sarcophagus chems
fix: Fixed incorrect names in deep maint vendors
balance: Lowered deep maint organ vendor prices
/:cl:

Aberrant organ bug fixes

---

code/game/atoms_movable.dm
code/modules/multiz/shadow.dm

Turns out my change broke adjust_z(null). sad
:cl:
fix: Fixed a mob harddel derived from adjust_z changes
/:cl:

Fixes a harddel associated with z movement

---

code/datums/objective/individual_objective/common.dm

Maybe fixes bills to pay

---

code/game/objects/objs.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
A small performance improvement on examining any and all objects.
/:cl:

Remove corporation checking from examining objects

---

code/modules/aberrants/organs/machinery/medical_bioprinter.dm

:cl:
balance: removed recycling from organ fab
/:cl:

No more organ fab recycling

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Restructures and rebalances the Genetics lab- adds a new cloning vat / test chamber and streamlines the  area for easy movement.
/:cl:

Restructure Genetics Lab

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes misc lighting issues with the changing of rooms
Fixes some area issues
Redoes a bit of surgery and medical cryo
*Note the surgery bay one is slightly out of date, swapped the wrench and tank for pre-tanked stands*

lighting and better surgery

---

code/datums/objective/individual_objective/common.dm

Makes it so you know what account to pay for the personal goals
untested

Makes it so you know what account to pay

---

maps/__Nadezhda/area/_Nadezhda_areas.dm

<details>
<summary>
Prevents blob from spawning in the main R&D lab and Robotics, which are both critical areas. 
</summary>
<hr>
<hr>
</details>
:cl:

Blob Spawning Rework #1

---

code/game/objects/effects/decals/crayon.dm
code/game/objects/items/oddities.dm
code/modules/psionics/psion.dm

cannonically these dont work outside the planet

disables some things for event

---

code/game/objects/effects/decals/crayon.dm
code/game/objects/items/oddities.dm
code/modules/psionics/psion.dm

Reverts sojourn-13/sojourn-station#3851

Revert "disables some things for event"

---

code/modules/economy/Accounts.dm

small explote fix

---

code/modules/economy/Accounts.dm
code/modules/economy/Accounts_DB.dm
code/modules/economy/cash_register.dm
code/modules/ghosttrap/trap.dm
code/modules/mob/living/living.dm
code/modules/modular_computers/file_system/programs/generic/taxes.dm

Ports https://github.com/discordia-space/CEV-Eris/pull/7379

more MLGTASTIC fixes for sanitization

---

code/game/jobs/job/captain.dm
code/game/jobs/job/church.dm
code/game/jobs/job/civilian.dm
code/game/jobs/job/engineering.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/medical.dm
code/game/jobs/job/prospector.dm
code/game/jobs/job/science.dm
code/game/jobs/job/security.dm

departmental FPBs are much more limited now to their department
streward is also limited to combat FPBs.
Preimer has no limit on FPBs
Heads of Staff also can only be their department fpb
Scavs have a mix of FPBs they can use depending on the job
Propis can be BS FPB and normal type
Scavs can be church/SI/Guild and normal FPB types

fpb-phobic

---

maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Mining dorms have been replaced with an extra exit
Pod dorms in science had their beds replaced with sinks
Condences cargo a small bit
Removes cargo's bugged trolly
Condences science upper hallway a small bit as well as CBO/CRO rooms
Removes loads of spare food form dorm room lockers
Removes some spare food form church dorm area
All approved by lich

removal of more dorms and condecing

---

code/game/machinery/vendor/tool_vendors.dm
code/game/objects/items/devices/defib.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/organs/external/_external.dm
code/modules/surgery/autodoc.dm
code/modules/surgery/robotic_damage.dm
code/modules/surgery/surgery.dm

Adds in jumper cables for people that have a organic heart in a robotic chest pice 
Performance: techinnlly less

Medfixes andports

---

code/modules/ameridian/liquid_ameridian_processor.dm
code/modules/mob/new_player/new_player.dm
code/modules/modular_computers/file_system/programs/generic/taxes.dm

fixes exploits
<hr>
</details>
:cl:
fix: fixes exploits
/:cl:

fixes exploits

---

code/modules/mob/living/carbon/superior_animal/termite/termite.dm
code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm

Termites no longer doup ore on death/gib
Perforamance, more checks on a termites death

fixe ore drop doups

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Massively reduces unused and unwanted space in SI from the long hallway to maints
Fixes a space tile in genetics
Places the teleporter room now by the locker room on second floor, and makes it much easyer to use.
Testing: Hit saved a bunch of times
Perforamance: likely better???? less tiles of dirt I guess???

more dence xenoflora and teleporter room

---

code/modules/surgery/surgery.dm

Fixes the surgery requirement check for biology to call correctly now. Now with greater than 50 bio you can properly do sugery.
:cl:
fixes: Surgery bio stat fix.
/:cl:

Fixes bio check

---

code/controllers/subsystems/trade.dm
code/modules/modular_computers/file_system/programs/generic/trade.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
fix: trade bugs
/:cl:

Trade bug fix

---

code/controllers/subsystems/trade.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
fix: trade hotfix
/:cl:

Trade hotfix

---

code/modules/genetics/machinery/genetics_analyzer.dm
code/modules/projectiles/gun.dm
code/modules/research/xenoarchaeology/finds/finds.dm
code/modules/research/xenoarchaeology/finds/finds_eguns.dm

Better codes slightly genetics analyzer
Fixes pvp damage ui stuff to say its things
Fixes xenoarch guns
Tested: Spawned a laser gun and check its stats after upgrading, did some genetics
preformance: Improved

mis rnd and gun fixes

---

code/controllers/subsystems/trade.dm

:cl:
fix: properly tested fix
/:cl:

Yet another hotfix

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes a cargo camera being in sec
Fixes missing/bad labled faxes
Fixes some stuff on windows rather then the wall its next to

fixes faxes

---

code/modules/organs/external/_external.dm
code/modules/organs/organ.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Increases internal damage from EMPs on robotic prosthetics
Severely reduces external damage from EMPs on Robotic Prosthetics
Reduces internal damage from EMPs on prosthetics contained within biological organs
/:cl:

Emp tweaks

---

code/modules/aberrants/organs/mods/3_output.dm

It wasn't working. Now, it will.
:cl:
fix: Fixed endocrinal adjustment not working
/:cl:

Fixes endocrinal organoid adjustment

---

code/game/verbs/ooc.dm
code/modules/admin/verbs/adminhelp.dm
code/modules/mob/observer/ghost/say.dm

Prevents people that are not whitelisted from talk in ooc, looc, dsay or ahelps.

makes it so whitelists are a bit more needed

---

code/modules/clothing/under/suits.dm

fixes suits from recent PR, take three

---

code/modules/projectiles/guns/energy/antebellum.dm
code/modules/projectiles/guns/energy/carpediem.dm
code/modules/projectiles/guns/energy/concilium.dm
code/modules/projectiles/guns/energy/crossbow.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/plasma.dm
code/modules/projectiles/guns/energy/sniperrifle.dm
code/modules/projectiles/guns/energy/stun.dm
code/modules/projectiles/guns/matter/launcher/books.dm
code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
code/modules/projectiles/guns/projectile/other/protector.dm
code/modules/projectiles/guns/projectile/pistol/mk58.dm

<details>
<summary>
Updates descriptions for church guns.
</summary>
<hr>
A lot of fiddly bullshit tweaking to make sure that the timelines on all of the church guns match up with the new lore, plus a bunch of grammar fixes. Can you believe I haven't played this faction in months.	
<hr>
</details>
:cl:
tweak: Updates descriptions for church guns.
/:cl:

Church Gun Lore :tm:

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Prospectors won the last Colony Games. Their reward still hasn't even been decided so I'm moving the trophy pre-emptively instead of waiting longer.
:cl:
balances: NERFS BALACKSHIELD!!!! (prospectors beat you in the event, it's theirs now)
/:cl:

Blackshield HARD Nerf!!!! (Prospector gang rise up kill em' all 1984)

---

code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm

Adds biosuits to the medical trade shuttle
Adds missing items like Assault armor, hatton tubes and gems to a few of the ships rounding out all missing items for when we remove the shuttle
Testing: made sure it complied
Performance: less good as it adds stuff

adds last of the missing packs to trade beacons

---

code/datums/craft/recipes/furniture.dm

Adds craftable soil: Costs 5 rocks and 5 sands as well as 3 rods to craft
Requested by OorthianEmissary#3201
Performance: Likely less

craftable soil

---

code/game/machinery/mindswapper.dm
code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
code/modules/research/designs/circuits.dm
code/modules/research/nodes/illegal.dm
maps/_DeepForest/map/_Prepper_Bunker.dmm
sojourn-station.dme

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Removed the Mindswapper- it no longer fits our lore for how Brains work.
[Link to approved lore](https://docs.google.com/document/d/1V6TanVyAlzBs0-5r15HzLt8G6wzPKZu7CZ6iPDYti54/edit?usp=sharing)
/:cl:

Mindswapping out

---

code/game/gamemodes/events/grid_check.dm

Makes grid checks only happend once

i hate grid checks

---

code/modules/genetics/genetics.dm
code/modules/genetics/machinery/genetics_items.dm

Makes it so synths no longer can get genetic mutations from the genetics system we have.
Testing: Trust me bro
Performance:techinnally lessssss

fixes synths doing genetics

---

code/modules/aberrants/organs/design_disks/designs.dm
code/modules/aberrants/organs/design_disks/disks.dm
code/modules/aberrants/organs/internal/teratoma.dm
code/modules/organs/internal/bones.dm
code/modules/organs/surgery_helpers.dm
code/modules/surgery/mods.dm
nano/templates/surgery_organ.tmpl
sojourn-station.dme

:cl:
add: Added mod attach/remove buttons to organs in the surgery window
add: Added examine button to aberrant organs in the surgery window
tweak: Reagent-based teratomas are separated by their reagent pool
/:cl:

Aberrant Organs - surgery buttons and RNG reduction

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Woops
Readds the trade request console to carog
Testing: None
Performance: Less

Readds a trade request console to cargo

---

code/modules/genetics/genetics.dm
code/modules/genetics/machinery/genetics_items.dm

Reverts sojourn-13/sojourn-station#3936
Fix makes it so all genes cannot be injected. Very bad!

Revert "fixes synths doing genetics"

---

code/modules/genetics/genetics.dm
code/modules/genetics/machinery/genetics_items.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
properly prevents FBPs from using a mutagenic injector
testing: i didn't
/:cl:

FBPs cannot use genetics injector

---

code/modules/aberrants/organs/internal/teratoma.dm

teratoma no longer can give ana stat
performance: no change
testing: none

Fixes gaining of ana stat

---

code/ATMOSPHERICS/pipes.dm
code/game/objects/effects/chem/chemsmoke.dm
code/modules/mob/living/carbon/breathe.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/living.dm
code/modules/mob/mob.dm

Fixes pipes being a bit bad code end when deleted
Fixes something in chemicals being unable to be GC'ed
Fixes smoke beung unable to be GC'ed (This is ran a lot so hopefully bigger improvements on this)
Performance: this helps it
Testing: Legitmently blew up the colony to see if it would be able to delete pipes- it did
as well as a GC about some metalball things

fixes smoke and metaball

---

code/game/objects/structures/omnius.dm

Fixes #3922 
Closes #3922 
Testing: None
Performance: techinnally better

fixes being able to see smallivisable lights

---

code/modules/reagents/machinery/centrifuge.dm
code/modules/reagents/machinery/chem_dispenser.dm
code/modules/reagents/machinery/chem_heater.dm
code/modules/reagents/machinery/chem_master.dm
code/modules/reagents/machinery/electrolyzer.dm
code/modules/recycling/disposal.dm

Fixes Bags/Beakers getting stuck-in-hand from click dragging into some things
Fixes Phatom beakers with chem heaters
closes #3932
Performance: Likely no change
Testing: Tested everything rather exstensively with spam drag clicking spam clicking low stats high stats. - Other then chem heater

beaker and bag fixes

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes a obelisk in a book case
Corrects some bad piping and wires
Fixes bar shutters in the upstairs
Replaced 2 active pump/scrubbers with inactive ones
fixed some bad placed lights to be less ugly
Testing: none
Performance: likely better or less

removes a bad obelisk and misc

---

code/game/machinery/vending.dm

Now when a vender is moved it re-checks its power and such
Testing: Fully tested moving a maints vender to non-maints
Performance: Less as it checks more

fixes venders power changing

---

code/modules/projectiles/guns/energy/centurio_auretian.dm

<details>
<summary>
</summary>
<hr>
What it says on the tin
<hr>
</details>
:cl:
spellcheck: fixed centurion typos
/:cl:

fix typos in the centurion

---

code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/mob_grab_specials.dm

By [ErisMeleeEnjoyer](https://github.com/ErisMeleeEnjoyer)
tweak: throatslit timer
fix: swing grab special
fix: fireman grab special
Perfomance: better?
Testing: Basic test against a wall

Fixes fireman carry

---

code/game/objects/items/devices/lighting/glowstick.dm

Wow they are worthless
Buffs undarks range, power and brightness so they can light up an area better then a pda light
Testing: none
performance: less

Massively buffs undark glowsticks

---

code/modules/clothing/accessories/accessory.dm
code/modules/mob/living/simple_animal/borer/borer_powers.dm

<details>
<summary>
Fixes shit that's kind of broken and bugs me
</summary>
<hr>
<hr>
</details>
:cl:
Copy-pasta'd updated eris code-fix for borer
Removed "return" that fucked up forcemove(host) proc
Dabbed on haters
made red church cloaks actually red
shifted around scarf code to work properly
/:cl:

misc bug fixes. AKA, minor bug fixes

---

code/game/machinery/os_portable_turret.dm
code/modules/power/os_port_gen.dm
nano/templates/os_generator.tmpl

Fixes a few interactions with new turret and GP generator
Adds in the tmpl file for the GP generator so it can be used 
Testing: Made sure the GP genetator worked and powered stuff
Performance: no change really

genetor fix and turret fix

---

code/datums/autolathe/guns.dm
code/game/objects/items/weapons/autolathe_disk/marshal.dm
code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm
code/modules/research/designs/weapon.dm
code/modules/research/nodes/combat.dm

SI can now make the SI DNA lock via RnD
Performance: no real change

SI can make SI gunmods

---

code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm

Ploge should no longer be able to stun itself
Ploge no longer should be able to stun allies
Ploge now can regen ammo in cases were admins it can no reach its target to melee
Testing: test server showed no errors and seemed to work fine
Performance less

some ploge tweaks

---

sojourn-station.dme

Allows the new mobs to be spawnable

turns on solgov mobs

---

code/datums/perks/nanogate.dm
code/modules/clothing/accessories/accessory.dm
code/modules/mob/living/simple_animal/borer/borer_powers.dm
code/modules/nanogate/powers/user.dm

<details>
<summary>
Opi-fixee the codee!
</summary>
<hr>
<hr>
</details>
:cl:
del: crappy code
tweak: on meth
balance: lost it a few times
spellcheck: never
refactor: probably!
/:cl:

Opifexee the fucking code

---

code/game/jobs/job/security.dm

Re-adds,"Marshal Civil Servant"
:cl:
/:cl:
Performance: none
Testing: made sure they were spelled correctly

"Marshal Civil Servant"

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes SI solars right side not having wire nodes
Fixes unkillable nanite swarms in maints with normal roach types
Testing none
performance: better techinnally

wire and flyers

---

maps/_HunterLodge/map/_Hunting_Lodge.dmm

Fixes the spawn points and some windows.

Lodge Spawn Fixes

---

maps/_HunterLodge/map/_Hunting_Lodge.dmm

Major fixes areas and additional things and stuff

i hate maps

---

maps/_HunterLodge/map/_Hunting_Lodge.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

More fixes with lighting at the lodage and some walls being plasteel solid rather then rock walls

more lighting tweaks

---

code/modules/multiz/shadow.dm

Shadows now should be different sizes based on the person below and stop runtiming
Performance: little better or less

shadow runtime fix

---

code/game/machinery/cryopod.dm
code/modules/mob/mob_helpers.dm

Cryo no longer always fails to get the correct timer with call damages
Cryo-lifts no longer takes borgs and silicons as they bug out a bit
Testing: spawned in made sure damaging made the funny red text undamage made blue cool text
Performance: better

cryo fixes

---

code/game/machinery/cryopod.dm
code/modules/mob/mob_helpers.dm

A less rushed version of cryo tweaks

Cryotweaks

---

code/modules/mob/say.dm

Removes subtle
Testing: Made sure it was removed in a test server
Performance: no real change

death to subtle

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes a few space tiles
Replaces some areas and walls
Adds an apc to the new maints area bit
Corrects some loot spawns and piping
fixes a few odd ends and bits
Adds some lighting to the new area
Unironically reworks the bioreactor room and storages to be worse in every ware
Testing none
performance: more map items 😔

small map tweaks

---

code/modules/mob/living/carbon/human/species/station/station.dm

Fixes marquas darksight being set to 1
Testing: none
performance: no change

doble var trouble

---

code/game/jobs/job/offcolony.dm

says on the tin.
<details>
<summary>
</summary>
Huntmaster now has the training of both a Hunter and Herbalist as they should be expected to teach either parts of the lodge life to their underlings.
<hr>
<hr>
</details>
:cl:
/:cl:

Makes Huntmaster have the perks of hunter and herbalist.

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
It's literraly just a few fixes to the one named specific room, nothing more.
</summary>
<hr>
...I was also asked to place welding helmet and toolbox, as well as bunch of cables for maintained and since those aren't really valuable I don't think it's a bit deal.
Btw, now pumps going in right directions and NOT it opposites which I copy-spasted from my previous remapped version
<hr>
</details>
:cl:
add: Toolbox, coils of cables, welding helmet and a soap to the Church's biogen
fix: fixes pumps going opposite directions
/:cl:

Fixing new church biogen

---

maps/_HunterLodge/map/_Hunting_Lodge.dmm

<details>
<summary>
In short, this is changing the solar array of the lodge from the Guidesu version to one that looks more cohesive and has additional solar panels (about 10 more). It removes the mass amount of generators and replaces it with a single generator, as that is all that is required to power the entire lodge. This PR also adds a recycler in a new 'maintenance' room that has the solar setup, SMES, and recycler. Lastly, this PR has the additions of trash bins about the lodge to allow lodgers to throw things away instead of dropping items on the ground like a discarded Woody doll.
Lodge members will now have to insert wood into the generator found in the 'maintenance' room and toggle SMES and solars at the start of every shift to ensure power for the entire shift.
</summary>
<hr> …

Lodge Solar Array Revamp

---

code/controllers/subsystems/tickets/tickets.dm
code/game/verbs/who.dm
code/modules/paperwork/faxmachine.dm

Mods now should be able to see and maybe even replie to faxes
Mods now should see ahelps rather then only hearing them (???)
"Event Staff" is now seeable in who for when these roles are given in game to better denote that staff is infact having people in a role of eventing

Ticket changes and fax stuff

---

code/controllers/subsystems/tickets/tickets.dm
code/game/verbs/who.dm
code/modules/paperwork/faxmachine.dm

Reverts sojourn-13/sojourn-station#4048
Dosnt fully work yet

Revert "Ticket changes and fax stuff"

---

code/controllers/subsystems/tickets/tickets.dm
code/modules/admin/admin.dm
code/modules/paperwork/faxmachine.dm

Retrys to give mods more power and seeing ahelps :~:

faxes and maybe messages

---

code/ATMOSPHERICS/components/valve.dm
code/ATMOSPHERICS/mainspipe.dm
code/ATMOSPHERICS/pipes.dm
code/__DEFINES/misc.dm
code/__HELPERS/type2type.dm
code/game/machinery/autolathe/fabricators.dm
code/game/machinery/telecomms/broadcaster.dm
code/game/objects/effects/decals/contraband.dm
code/modules/flufftext/Dreaming.dm
code/modules/flufftext/TextFilters.dm
code/modules/mob/holder.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/say.dm
code/modules/mob/mob_helpers.dm
code/modules/organs/body_modifications.dm
code/modules/power/singularity/singularity.dm
code/modules/shuttles/shuttle.dm
sojourn-station.dme

<details>
<summary>
Tired of seeing errors while working. Fixed them
</summary>
<hr>
<hr>
</details>
:cl:
Slapped away some bugs so they don't bug me or anyone else again.
/:cl:

misc. bugfixes to get them off the error list

---

code/modules/mob/living/living.dm
nano/templates/tasks.tmpl

Adds UI window and a verb under the IC tab to show tasks
:cl:
add: Added "show task" IC verb and UI window
/:cl:

Adds UI and verb for tasks

---

nano/templates/tasks.tmpl

Tasks stack vertically
:cl:
fix: Fixed task UI
/:cl:

Task UI fix

---

code/modules/clothing/head/misc.dm

<details>
<summary>
</summary>
Adds bio armour to the Laurel Wreath and Numerical Hat. Wreath has _only_ 100 bio armour, Hat has equal armour to Numerical Garb. Church overwear should be suitable for church work.
<hr>
<hr>
</details>
:cl:
balance: slightly buffed laurel wreaths/numerical hats
/:cl:

egregious Church buffs

---

code/modules/projectiles/ammunition.dm
code/modules/projectiles/guns/_projectile.dm

With help of Pink-Chink
Selling ammo no longer leaves flying bullets

Fixes flying deleted bullets

---

code/modules/clothing/spacesuits/rig/rig_verbs.dm

Requested by a player adds a button to undeploy every rig bit you have on you
Testing: pressed button saw it work
performance, none

deploynt suits verb

---

code/game/objects/structures/crates_lockers/closets/secure/scientist.dm

Swaps the body bags in the sci lockers to be the folded version (requested by @shirumic)

sci locker - folded bodybags

---

code/game/gamemodes/events/blob.dm
code/game/gamemodes/events/hivemind_controller.dm
code/game/objects/items/oddities_faction.dm
code/game/objects/items/weapons/grenades/flashbang.dm
code/game/objects/items/weapons/grenades/smokebomb.dm
code/modules/mob/living/carbon/superior_animal/defense.dm
code/modules/projectiles/projectile/projectilegrenades.dm
code/modules/projectiles/projectile/special.dm
code/modules/tips_and_tricks/gameplay.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
maps/submaps/deepmaint_rooms/core/overrun.dmm
modular_sojourn/stalker_annomlies.dm

Blobs now propery die when taking damage from some obsercure sources
blobs have a pop lock of active combats of 7
adds new tips and tricks for slime and blob fighting
fixes a few annomlie things
misc map tweaks to fix some errors
Testing: a bit
Performance: unknown

Blob changes, fixes and tips and tricks

---

code/modules/projectiles/gun.dm
code/modules/projectiles/guns/energy/cog.dm

Cog now only has 1 shot fire mode
Cog has 1 less modding slot
Fixes fire delay for all guns
Cog now has 2ms more fire delay
Gear has 3 ms less fire delay
Pinion has only 1 shot fire mode
Testing: Shot a cog a bunch
Performance: better

gear tweaks and firedelay fix

---

code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/sonic_emitter.dm
code/modules/projectiles/guns/energy/stun.dm
code/modules/projectiles/guns/projectile/automatic/dp.dm
code/modules/projectiles/guns/projectile/automatic/mac.dm

Fixes a lot of really high fire delays on guns now that the system works
Testing:none
Performance:none

changes fire_delays down

---

code/modules/research/xenoarchaeology/manuals.dm
code/modules/research/xenoarchaeology/misc.dm

Xenoarch manuals updated to be easier to understand. (Anomaly research manuals might be done at a later date)
"Out on the Dig" book placed into excavation lockers to help newer players sense the suspension field guide was literally just for the suspension field.
Tested so I could do a proof read. I'm vary tired and my grammer isn't perfect so still might have some spelling errors.

Archeology Manuals Update

---

code/game/objects/items/weapons/tools/knifes_daggers.dm
code/modules/client/preference_setup/loadout/lists/armament.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

fix heirloom dagger icon

---

code/modules/client/preference_setup/loadout/lists/armament.dm
code/modules/client/preference_setup/loadout/lists/belt.dm
code/modules/client/preference_setup/loadout/lists/utility.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
tweak: tweaked a few prices of items and make cosmetic (items that do not altere too much the round) or other items for free and let things that affect gameplay the same price.
fix: fixed a few objects
:cl:
/:cl:

Readjust some prices and essentially fixed all the belts issues

---

code/modules/mob/living/simple_animal/friendly/cat.dm

Fixes cats spamming dead chat with hissing.

Cat dead chat fix

---

code/game/objects/items/weapons/storage/firstaid.dm
code/modules/aberrants/organs/holders.dm
code/modules/aberrants/organs/internal/simple.dm
code/modules/aberrants/organs/internal/teratoma.dm
code/modules/aberrants/organs/mods/0_mods.dm
code/modules/aberrants/organs/mods/1_input.dm
code/modules/aberrants/organs/mods/component/_component.dm
code/modules/aberrants/organs/mods/component/input.dm
code/modules/aberrants/organs/mods/component/output.dm
code/modules/organs/internal/_internal.dm
code/modules/organs/internal/bones.dm

:cl:
tweak: Organ freezers can hold organ mods
balance: Nociceptive organoids have a minimum damage threshold of 45, 30, or 15
fix: Fixed bones destroying themselves when modded
fix: Fixed reagent input adjustment bug
fix: Fixed some GC issues with scaffolds and mods
fix: Fixed issue with initial organ efficiencies not being stored correctly
fix: Fixed issue with multiple inputs and outputs not functioning
code: Cleaned up miscellaneous code
/:cl:

Aberrant organ updates

---

code/_onclick/item_attack.dm
code/datums/autolathe/tools.dm
code/game/machinery/autolathe/autolathe.dm
code/game/objects/items/oddities_faction.dm
code/game/objects/items/weapons/nt_melee.dm
code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/items/weapons/tools/crowbars.dm
code/game/objects/items/weapons/tools/hammer.dm
code/game/objects/items/weapons/tools/misc.dm
code/game/objects/items/weapons/tools/multitool.dm
code/game/objects/items/weapons/tools/pickaxe.dm
code/game/objects/items/weapons/tools/saws.dm
code/game/objects/items/weapons/tools/screwdrivers.dm
code/game/objects/items/weapons/tools/shovel.dm
code/game/objects/items/weapons/tools/weldingtools.dm
code/game/objects/items/weapons/tools/wirecutters.dm

GP tools now longer have perfected printing
GP tools break faster now
Braking tools now destorys them completely
Autolathens max materal saving is now 50% rather then 80%

GP and autolathen balance

---

code/game/objects/structures/crates_lockers/closets/job_closets.dm
code/modules/client/preference_setup/loadout/lists/armament.dm
code/modules/core_implant/cruciform/rituals/path.dm
code/modules/projectiles/guns/oddity_items.dm

<details>
<summary>
</summary>
<hr>
Divisor now spawns with singlular single use church cell for his pistol and you can take scabbards as church for your sword
<hr>
</details>
:cl:
add: Church scabbard for churchies in loadout
fix: Bluecross serenity having wrong stats
fix: Divisors not spawning with cell for their weapon
/:cl:

Uhh yeah uhhhhhhhhhhh

---

nano/templates/trade.tmpl

:cl:
fix: Fixed missing trade logs button on trade program
/:cl:

Adds missing button for the trade logs

---

code/game/objects/items.dm
code/game/objects/items/stacks/throwing.dm
code/game/objects/items/weapons/material/thrown.dm
code/game/objects/items/weapons/nt_melee.dm
code/game/objects/items/weapons/tools/knifes_daggers.dm
code/game/objects/items/weapons/tools/simple_weapons.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/power/lighting.dm

<details>
<summary>
</summary>
<hr>
Title, obviously didn't make either of these the authors did
https://github.com/discordia-space/CEV-Eris/pull/7800
https://github.com/discordia-space/CEV-Eris/pull/7806
<hr>
</details>
:cl:
add: Ports #7800 #7806 from Eris
/:cl:

Ports #7800 #7806 from Eris

---

code/datums/autolathe/security.dm
code/game/machinery/vendor/weapon_vendors.dm
code/game/objects/items/weapons/storage/backpack.dm
code/modules/client/preference_setup/loadout/lists/armament.dm
code/modules/clothing/clothing.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Gun cases can now be opend in hand

gunbox buff

---

code/game/objects/items/devices/hardware_imprinter.dm
code/modules/mob/living/carbon/human/human_recoil.dm
code/modules/mob/living/living_recoil.dm

Perk implanters now have downsides
Smartlink values have been changed to be less insainly good

Smartlink balance

---

code/modules/client/preference_setup/loadout/lists/armament.dm

<details>
<summary>
</summary>
<hr>
You can take a machete scabbard in your loadout for the same cost as a saya or cutlass sheath. If you can take a sheath for the cutlass, you should be able to take one for the machete, which is also already in the loadout.
<hr>
</details>
:cl:
balance: machete scabbards are available in the loadout menu
/:cl:

adds machete scabbards to the loadout

---

code/modules/modular_computers/file_system/programs/generic/trade.dm

Fixes an exploit, fixes an issue where the first item added to an inventory is not actually added, and did some misc. code cleanup.
:cl:
fix: Fixed infinite money exploit from buying negative amounts of items
fix: Fixed an issue where the first item added to an inventory is not actually added
code: Changed usage of some list procs and vars to macros
/:cl:

Trade tweaks

---

code/modules/food/recipes_microwave.dm

<details>
<summary>
Add missing pizza recipe to microwave.
</summary>
<hr>
Added missing pizza microwave recipe, enabling the chef to cook all the pizzas that are also in an ordered pizza crate. The pizza itself was already there, it was just not possible to create it.
<hr>
</details>
:cl:dutop
add: Added missing pizza recipe to microwave
/:cl:

Add microwave recipe for hawaiian pizza

---

code/modules/genetics/machinery/genetics_items.dm

Fixes genetics reject icon to actually be somthing instead of nothing.

fixes reject icon

---

code/game/objects/items/weapons/tools/_tools.dm

<details>
<summary>
</summary>
<hr>
fixes a mistaken use of "switched_on_forcemult" rather than "switched_on_penmult" which caused a runtime/visual bug
<hr>
</details>
:cl:
fix: fixes a runtime/visual bug with tools
/:cl:

fixes a silly error in the tool refactor

---

code/modules/psionics/psion_powers/deepmaints_themed_powers.dm
code/modules/psionics/psion_powers/mob_affecting_powers.dm
code/modules/psionics/psion_powers/pyschiatrist_powers.dm
code/modules/psionics/psion_powers/telekinetsis_powers.dm
code/modules/psionics/psion_powers/teleporation_powers.dm

Fixes a few cases were points for psions were being costed twice

fixes doble point costs

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Fixes a bad flower
Fixes a pipe in the TEG output
Fixes a bad tablet spawn
Fixes some bad mapping in the spider den inside the colony

some map error fixes

---

code/modules/scrap/scrap_refine.dm

unrefined scrap now can only have silicon as its reagent

scrap refine exploit fix

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Adds a upper layer to the prison cells that is just open air
Removes some maintance animals in an old garden to help with livestock numbers
Removes some over-stacked dust

Better Marshal mapping

---

code/game/objects/items/weapons/nt_melee.dm
code/game/objects/items/weapons/shields.dm
code/modules/projectiles/projectile/bullets.dm
code/modules/psionics/psionic_items/psi_temp_items.dm

Shields now when taking bullets reduce its health
Sheilds now properly block bullets/projectils
Sheilds armor has been increased
Shields health has been decreased

shield properly block and break

---

code/__DEFINES/species_languages.dm

Title
:cl:
fixes: Illyrian mis-match name.
/:cl:

Fixes Illyrian

---

maps/submaps/map_clearers/coras_map.dmm

space be gone

---

code/game/objects/structures/firepits.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm

Fixes when bond fires are completely depleeded being unable to be refused
Fixes missing AI langs 
Fixes a cargo trade having wrong item

fixes a edge case in bondfires and AI langs

---

code/game/objects/items/weapons/manuals.dm
code/modules/library/lib_items.dm

Remove Eris_ prefix from links to Wiki
Update links to wiki articles that really exist, where possible Remove books that have no wiki article
Remove references to removed books
<details>
<summary>
Fix the links in the books that refer to Wiki
</summary>
<hr>
Some books have no content, but when you read them, they open a iframe containing (the print version of) a wiki page. That didn't work, because every page they linked to was expected to contain "Eris_". This is not Eris. Boo. So I removed that.
Then I noticed that the title of some of the Wiki article was incorrect. We have no "Guide to Food and Drinks", we have "Guide to Food" and "Guide to Drinks". So I checked which books referred to invalid Wiki articles and changed it to a fitting article I found.
Where I didn't find an article …

fix: Fix links to Wiki-books

---

code/modules/core_implant/cruciform/rituals/construction.dm

By [Mycah142](https://github.com/Mycah142)
add: Uproot: Deconstruction Litany

ports deconning church stuff

---

code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
sojourn-station.dme

Readds casio ship

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Removes an item given away in an event

Event Givings

---

maps/submaps/map_clearers/map_clearers.dm
maps/submaps/map_clearers/os_reclaimed_spider_post.dmm

A small map made for admins to spawn in for mini events

something mini-eventy

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
maps/submaps/map_clearers/burnt_post_voidwolf_reclaimed.dmm
maps/submaps/map_clearers/map_clearers.dm
maps/submaps/map_clearers/os_reclaimed_spider_post.dmm

Secondary template for events

---

code/modules/mob/angel/login.dm
code/modules/mob/living/login.dm
code/modules/mob/living/silicon/ai/login.dm
code/modules/mob/living/silicon/robot/login.dm
code/modules/mob/login.dm
code/modules/mob/new_player/login.dm
code/modules/mob/observer/ghost/login.dm
code/modules/multiz/shadow.dm
interface/skin.dmf

Fixes borg/ai spawning
Fixes some issues with shadow calls
Fixes pixel shifting

Fixes stuff

---

code/modules/gambling/slot_machine.dm

jackpotfix

---

maps/__Nadezhda/area/_Nadezhda_areas.dm

Partially fixes the issues with infestations spawning in maints. They still spawn in the woods/outdoor colony areas for reasons that im not HORRIBLY clear on but hey- little victories.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Infestation fixes

---

code/game/machinery/vending.dm
code/modules/sanity/sanity_mob.dm
modular_sojourn/task_master/task_helpers.dm
modular_sojourn/task_master/tasks.dm

Replaces eris level up sound with ares again
Fixes venders not giving tasks when properly used
Cleans up a small bit of vender code

fixes venders not giving tasks and level up sound

---

code/datums/outfits/jobs/off_colony.dm

<details>
<summary>
This PR basically gives hunters there boots, this includes hunters and hunt masters. Changes bone armor that hunter master got into regular hunter armor. Hunter gloves into hunt master. 
</summary>
<hr>
<hr>
</details>
:cl:
tweak: gives hunter boots to hunters and hunters master. 
replace: bone armor to regular hunter armor for head master
add: hunter gloves roundstart on hunt master.
/:cl:

QoL - Lodge roles

---

code/game/gamemodes/scores.dm
code/game/jobs/department.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Echomic deasters

---

maps/__Nadezhda/area/_Nadezhda_areas.dm

Reverts sojourn-13/sojourn-station#4313

Revert "Infestation fixes"

---

code/modules/sanity/sanity_mob.dm

Makes it so desirers once again no longer endlessly stack
Ports an infi loop done by Pink
https://github.com/discordia-space/CEV-Eris/commit/28890afd5928d36119ca3cab5a2b68692830ef8a

Ports a infi loop fix

---

maps/__Nadezhda/area/_Nadezhda_areas.dm

Infestation fixes re-add

---

code/game/objects/items/toys.dm
code/modules/client/preference_setup/loadout/lists/general.dm

<details>
<summary>
Adds a photo frame to loadout for RP purposes. Will be updated to a proper sprite when I get my hands on one.
</summary>
<hr>
<hr>
</details>
:cl:
Adds a photo frame to loadout.
/:cl:

Adds a Photo Frame to loadout

---

code/datums/perks/oddity.dm

<details>
<summary>
Changes the Absolute's pronouns
</summary>
<hr>
It uses it/its now.
<hr>
</details>
:cl:
tweak: The Absolute now uses it/its
/:cl:

Changes the absolute's pronouns

---

code/game/machinery/smelter.dm

<details>
<summary>
Changes efficiency math to the following:
- Tier 6 is 100% efficient
- tier 5 is 90% efficient
- tier 4 is 80% efficient
- tier 3 is 70% efficient
- tier 2 is 60% efficient
- tier 1 is 50% efficient
</summary>
<hr>
<hr>
</details>
:cl:
tweak: changes micro laser tier gain from 5% to 10%, as well as scanners now also increase processing speed
/:cl:

Makes smelters possible to be 100% efficient

---

code/modules/reagents/reagents.dm

Chemicals after 5 processes of not gaining a dose above 0 now get + 0.1 metaball, this should help the forever stuck chems get out of peoples systems such as spaceascillion, base level toxins and battlian

adds a safty check to chems

---

code/game/objects/items/weapons/storage/wallets.dm
code/game/objects/random/cigarettes.dm
code/game/objects/random/packs.dm
code/game/objects/random/purerandom.dm
code/game/objects/random/scrap.dm
code/modules/clothing/accessories/accessory.dm
code/modules/clothing/accessories/world_building.dm
code/modules/gambling/slot_machine.dm
code/modules/reagents/reagent_containers/pill.dm
code/modules/scrap/scrap.dm
code/modules/scrap/scrap_beacon.dm
sojourn-station.dme

Slots are now way less talky
Jesters are more calm on adding wealth
Allows random wallets to spawn around
Allows more random wallet based items to spawn in wallets
Rebalances a lot of trash numbers to be less desne and less locker spawns
Rebalance the trash beacon to be less good at getting every type in the game

Trash beacon + fluff + small slots balance

---

code/game/gamemodes/scores.dm
code/game/jobs/department.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

Reverts sojourn-13/sojourn-station#4321
WE GOT IT BACK!

Revert "Echomic deasters"

---

code/game/jobs/job/assistant.dm

It explains by itself!
Guidesa
:tm: add: Colonist can choose the title of "Freelancers"

Freelancer as alt-title for colonist

---

code/modules/sanity/sanity_mob.dm

Correctly changes inspiration gain to 50% from 25% like it is labelled in the tool tip for the nanogate perk.

Rebalances nanogate inspiration

---

code/game/objects/items/toys.dm
code/modules/client/preference_setup/loadout/lists/general.dm
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

<details>
<summary>
Adds a pen and paperbin to the GM office as it was lacking one.
</summary>
<hr>
<hr>
</details>
:cl:
Adds a pen and paperbin to the GM office as it was lacking one.
/:cl:

Adds a pen and paperbin to the GM office as it was lacking one

---

code/game/machinery/excelsior/blackshield_teleporter.dm
code/modules/projectiles/ammunition/boxes.dm

Adds shotgun speed loaders and shotgun mags to blackshield teleporter
[removed ammo box buff, Pug meta 4 lyfe.]

Ammo box and quality of life.

---

code/modules/modular_computers/file_system/news_article.dm
news_articles/Emily_chu.html

miner news once again

---

maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm

<details>
<summary>
Fixes some lack of floor under windows, gets the TEG room pipes colored and maps in a pipe painter to the TEG room
</summary>
<hr>
<hr>
</details>
:cl:
add: pipe painter to a table in the TEG room in solars
fix: windows in the supermatter room now have a proper floor
tweak: pipes in the TEG room are now colored, based on input/output and loop they belong
/:cl:

Fixes mapping issues in solars + colored pipes + pipe painter

---

code/game/objects/effects/decals/crayon.dm

Adds two more rituals to crayon magic

Time To Duel!

---

code/__DEFINES/machinery.dm
code/game/machinery/alarm.dm

<details>
<summary>
- Air alarms now start off, from filtering
- filtering now actually filters! Guild and smokers rejoices!
- air alarms now HATE plasma and will make alerts about it! (Guild better keep an eye on atmos alerts)
- syphon mode now turns off all vents in the area, from not changing them
- scrubbers and relatives can now fully clean a room of unwanted gases, syphon unchanged
- tested locally five times, twice per server reset(one CO2, one plasma), no noticeable increment to lag (had one time lagspike while filtering, but I was doing other stuff while testing it, so I discarded that test entirelly)
</summary>
<hr>
<hr>
</details>
:cl:
tweak: air alarms now start on off mode, from filtering
tweak: increased filtering sensitivity, now on par with the minimum threshold to start a …

air alarm + scrubbers fixes (this one does not causes lag)

---

code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipe_donuts.dm
code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
sojourn-station.dme

Exstends a few mostly cooking from microwave to the hex cooking system

Hex cooking convering

---

code/modules/modular_computers/file_system/programs/engineering/shield_control.dm

<details>
<summary>
it was dead set to only hull gens, now it searches for any shield generator that is wrenched and the AI wire is not cut (ai and remote control in the code are the same, so I kept as is)
</summary>
<hr>
<hr>
</details>
:cl:
fix: shield control program now works as intended (for real)
/:cl:

Shield control program fix

---

code/modules/mob/mob.dm

Adds 'Colony Date' to the status tab.
<details>
<summary>
What does it do?!?!??!?!?!?
</summary>
Adds a 'Colony Date' entry in the 'Status' in-game tab.
<hr>
<hr>
</details>
:cl:
add: Colony Time is now displayed in the 'Status' tab.
/:cl:

Date in Status

---

code/ZAS/Zone.dm

<details>
<summary>
- ports this Aurorastation/Aurora.3/pull/14577
- tested locally, improves ZAS marginally, but in extreme cases the difference is measurable, like setting the whole colony on plasma fire
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

ports #14577 from Aurora

---

code/datums/craft/gun_parts.dm

Fixes heavy barrel printing

---

code/game/objects/effects/decals/crayon.dm
maps/Centcom/map/centcom.dmm

Adds in a ritual to equalize blood between all humans and monkeys in a small area.
Finally a way to kill yourself while trying to fix the 0 blood colonist.

Equalize ritual

---

code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipe_donuts.dm
code/modules/cooking_with_jane/recipes/recipes_to_covert.dm

Coverts more cooking repice to hex cooking
Balances sandwitches a small bit

more cooking repices

---

code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipe_donuts.dm
code/modules/cooking_with_jane/recipes/recipes_to_covert.dm

Fixes bread making repices
Adds 17 more repices mostly salad and cakes

more repices again and fixes

---

code/game/objects/effects/decals/crayon.dm
code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm

Adds bees wax as a dropped item to "Wasps"
Adds Bees! as a ritual.

Bees wax to bees

---

maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm

<details>
<summary>
one of the pipes in the SM engine was facing the wrong way this change corrects it
</summary>
<hr>
<hr>
</details>
:cl:
fix: pipe on the SM engine facing the wrong way
/:cl:

SM Pipe fix

---

code/__DEFINES/_planes+layers.dm
code/_onclick/hud/plane_master.dm
code/_onclick/hud/radial.dm
code/_onclick/hud/screen_objects/base_screen_objects.dm
code/datums/progressbar.dm
code/game/atoms.dm
code/game/objects/items/devices/t_scanner.dm
code/game/objects/items/weapons/material/swords.dm
code/game/objects/items/weapons/policetape.dm
code/game/objects/structures/firepits.dm
code/modules/mob/animations.dm
code/modules/mob/living/carbon/human/species/forms/station.dm
code/modules/mob/living/carbon/human/species/forms/station_unusual.dm
code/modules/mob/observer/ghost/login.dm
code/modules/mob/observer/observer.dm
code/modules/organs/external/organ_icon.dm
code/modules/scrap/scrap.dm
code/modules/xgm/xgm_gas_data.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
Add: Makes things less blurry

Uses pixel scaling in general to combat blurness in general

---

code/modules/mob/death.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Optimizes death code slightly so messages aren't sent to NPC mobs 
Adds logging for character death
/:cl:

Death optimization

---

nano/templates/cooking_catalog.tmpl

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Fixes the name on one of the VIKA pages
/:cl:

VIKA name fix

---

code/game/mecha/combat/combat.dm
code/game/mecha/medical/medical.dm
code/game/mecha/working/working.dm
code/modules/holodeck/HolodeckObjects.dm

closes #2635
Fixes mechs dropping items and them being invisable
Fixes holo floors maybe again

fixes mechs dropping invisable stuff

---

code/modules/mob/living/living_defense.dm

<details>
<summary>
fire wasn't checking if you were actually on fire, just firestacks and if you were too hot for the purposes of hot food. Now hot food will still be scary (and you should RP it dammit), but not deadly or actually harmful
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

fixes spicy food gibbing you

---

code/modules/projectiles/guns/projectile/automatic/ak47.dm
code/modules/projectiles/guns/projectile/automatic/solmarine.dm

Maybe this time it'll work. Also made the breacher AK craftable via rubber grip on the AK body.
:cl:
fixes: Solarian frame issue.
add: Breacher AK crafting.
/:cl:

Solmarine Fix Again

---

code/game/machinery/crafting_station.dm

Adds 8.6 Cheap to Guild crafting

---

code/modules/client/preference_setup/loadout/lists/accessories.dm

<details>
<summary>
</summary>
<hr>
Hoods in the loadout are mistakenly pathed as poncho. This fixes that.
<hr>
</details>
:cl:
fix: colorable hoods spawn properly
/:cl:

Drip Infusion hotfix

---

maps/_DeepForest/map/_Beast_Cave.dmm
maps/_DeepForest/map/_Deep_Forest.dmm
maps/_DeepForest/map/_Prepper_Bunker.dmm
maps/_DeepForest/map/_River_Forest.dmm
maps/_DeepForest/map/_River_Forest_old.dmm
maps/_DeepForest/map/_River_To_Swamp.dmm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Outsider now spawns in a single location

---

code/datums/craft/recipes/misc.dm
code/modules/clothing/head/misc.dm

Makes base hair pins craftable.
Allows attaching certain flowers to pins.
https://user-images.githubusercontent.com/13492089/218567226-6fe039ae-3153-4d8f-983e-9637890e15af.mp4

V-day hair pins

---

code/__DEFINES/cooking_with_jane.dm
code/modules/cooking_with_jane/recipes/_read_me.dm
nano/templates/cooking_catalog.tmpl

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Adds use grill to the cooking recipe documentation
/:cl:

Cooking minor edit

---

maps/_DeepForest/map/_Beast_Cave.dmm
maps/_DeepForest/map/_Deep_Forest.dmm
maps/_DeepForest/map/_Prepper_Bunker.dmm
maps/_DeepForest/map/_River_Forest.dmm
maps/_DeepForest/map/_River_Forest_old.dmm
maps/_DeepForest/map/_River_To_Swamp.dmm

Reverts sojourn-13/sojourn-station#4437
Requested by a few known outsiders

Revert "Outsider now spawns in a single location"

---

code/game/objects/effects/decals/crayon.dm

scroll spell updoot

---

code/game/machinery/computer/atmos_alert.dm

refactor: atmos_alert.dm now usestgui, from nanoui
<details>
<summary>
literally what is in the title, originally I wanted to do this on station_alert.dm, but it's too tied to the modular program and I would have to make a ton of changes in the whole modular computers folder to make one program use tgui
</summary>
<hr>
<hr>
</details>
:cl:
refactor: atmos_alert.dm now uses tgui, from nanoui
/:cl:

TGUI atmos_alert.dm

---

code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/items/weapons/tools/mods/mod_types.dm
code/modules/mob/living/silicon/robot/robot_items.dm

reduces tool health by 20%
Tools now all are able to break unless you have nanorepair
Makes auro damper now increase degeration rather then decresses tool break tool threashold

tools nerf

---

code/ATMOSPHERICS/components/binary_devices/circulator.dm
code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
code/ATMOSPHERICS/components/binary_devices/pipeturbine.dm
code/ATMOSPHERICS/components/binary_devices/pump.dm
code/ATMOSPHERICS/components/binary_devices/volume_pump.dm
code/ATMOSPHERICS/components/omni_devices/filter.dm
code/ATMOSPHERICS/components/omni_devices/mixer.dm
code/ATMOSPHERICS/components/omni_devices/omni_base.dm
code/ATMOSPHERICS/components/portables_connector.dm
code/ATMOSPHERICS/components/trinary_devices/filter.dm
code/ATMOSPHERICS/components/trinary_devices/mixer.dm
code/ATMOSPHERICS/components/tvalve.dm
code/ATMOSPHERICS/components/unary/cold_sink.dm
code/ATMOSPHERICS/components/unary/generator_input.dm
code/ATMOSPHERICS/components/unary/heat_exchanger.dm
code/ATMOSPHERICS/components/unary/heat_source.dm
code/ATMOSPHERICS/components/unary/outlet_injector.dm
code/ATMOSPHERICS/components/unary/oxygen_generator.dm
code/ATMOSPHERICS/components/unary/vent_pump.dm
code/ATMOSPHERICS/components/unary/vent_scrubber.dm
code/ATMOSPHERICS/components/valve.dm

<details>
<summary>
#4406 , but toned down since the issue was either in datums or how was interacting with ZAS. local server restarted 15 times, no issues and little to no performance enhancement noticed in server start
</summary>
<hr>
code obtained from Eris and adapted to this server by me
<hr>
</details>
:cl:
refactor: all pipes codes (minus meters), TEG circulators
refactor: heater/cooler code
Guild alert: supermatter is again fickle, test the waters before diving or you will have a bad time.
/:cl:

Piping changes 2: electric bogaloo (Guild buff and nerf)

---

code/ATMOSPHERICS/_atmospherics_helpers.dm

<details>
<summary>
Due to the revert of the whole ATMOSPHERICS folder, this issue has returned, and it is now gone
</summary>
<hr>
<hr>
</details>
:cl:
fix: scrubbers/vents no longer generate one watt when their work gets cancelled
/:cl:

Fixes negative power draw on scrubbers/vents (again)

---

code/modules/power/apc.dm

<details>
<summary>
- Reroutes code from nanoui to tgui, some useless buttons kept, they do nothing since their action is commented out
- I just slapped TGUI template and adjusted the data, button functionality and silicon ifs
- silicons can use the APC just fine, overload lights button still there
- hacking is a separate thing and uses nanoui, but the two talk just fine since they are ui, not the under the hood stuff
</summary>
<hr>
<hr>
</details>
:cl:
code: Area Power Controller (APC) are now using TGUI, extra functionalities from TG remain, but do nothing
/:cl:

APC -> TGUI (another Guild buff...really)

---

code/game/objects/structures/burrows.dm
code/modules/reagents/reagent_containers/pill.dm
modular_sojourn/task_master/_task_master_defines.dm
modular_sojourn/task_master/tasks.dm

Eating floor pills now give you a fancy task
Floor pills have more types of rng toxins in them
sealing borrow code is now much more cleaner and easyer to read
sealing borrows with a shovel and then welding/hammering cracks now gives you a fancy task

two new tasks and borrow sealing refractor-ish

---

code/_onclick/ghost.dm
code/_onclick/other_mobs.dm
code/modules/power/apc.dm
code/modules/tgui/states/admin.dm

<details>
<summary>
- 	ghosts can now interact with tgui, but not press buttons (even aghosts)
- this is a VERY jury rigged fix, ideally the whole _onclick folder and mobcode would have to be rebased/refactored for it to work as it should
- don't blame me TGUI is not working as intended, it was a halfassed port that barely works with our code
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Ghosts can now visualize TGUI, not interact (Admin ghosts intract with it like a normal person)
/:cl:

Re-allows admins to use APCs

---

code/modules/power/power.dm
code/modules/power/smes.dm

<details>
<summary>
- all SMES now use TGUI
- ghosts can't interact since it's an issue in our TGUI or mob code or onclick...making ghosts have UI_update on interact with TGUI is harder than you'd think
- now all numbers update and show their numbers properly
</summary>
<hr>
<hr>
</details>
:cl:
code: SMES now use TGUI, missing parameters to the UI are now fixed
/:cl:

SMES -> TGUI (yet another guild buff, trust me)

---

code/game/objects/structures/watercloset.dm
code/modules/mob/living/carbon/superior_animal/robots/robot.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Fixes the grammar skill issue of catto

---

code/modules/cooking_with_jane/recipes/recipe.dm

Corrects a lot of the oven and stove requirements for hex cooking repices

fixes a bunch of repices

---

code/__DEFINES/species_languages.dm
code/modules/mob/language/language.dm
code/modules/mob/language/outsider.dm
code/modules/mob/language/synthetic.dm
code/modules/mob/living/carbon/human/species/species.dm
code/modules/mob/living/silicon/silicon.dm

<details>
<summary>
New language, Technical Cant. Possessed by all synths, as well as borgs and AIs.
ADDITIONALLY.
adds the remaining languages to borg/AI speak from the list of racial languages- if the holopad can translate them, why can't the AI?
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Synthetic racial language + AI language adjustments.

---

code/game/jobs/job/captain.dm

Streward no longer enforces itself on people thinking its a head of staff

Streward is no longer head position

---

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm

fixes an apc being the wrong way in the trade room
reverts at the request of cora the tea party above the trade room

tea party removed and apc fix

---

code/__DEFINES/perks.dm
code/datums/perks/nanogate.dm
code/modules/nanogate/powers/user.dm
code/modules/organs/internal/nanogate.dm
code/modules/reagents/reagents/dispenser.dm
code/modules/reagents/reagents/other.dm

Fixes allowing some nanogate perks that dont work to be allowed on synthics (chem based ones)
Adds 3 new nanogate perks

three new nanogate perks

---

code/game/objects/items/robot/robot_items.dm
code/game/objects/items/weapons/tools/scalpels.dm
code/modules/mob/living/silicon/robot/drone/blitzshell.dm
code/modules/mob/living/silicon/robot/gripper.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

Blitz shell has gotton health, stats and equipment massively buffed to better help fight
Medical bots now have laser scaples and can use the fancy organs with their medical gripper

Massively buffs bltizshell

---

code/__DEFINES/chemistry.dm
code/__DEFINES/species_languages.dm
code/modules/mob/language/outsider.dm
code/modules/mob/living/carbon/human/species/species.dm
code/modules/mob/living/carbon/human/species/station/station.dm
code/modules/mob/living/silicon/silicon.dm

New language, Narad Pidgin.
"A crude pidgin tongue, not created by it's supposedly native speakers, but by their foreign overlords. Enforced as the only legal native language of the Naramadi people by the Federation as a means to unify the planet and make administrative work easier, while allowing them to keep a semblance of native culture."
All credit goes to Yanniert for lore + language details. Tested and working as far as i can tell.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Naramad Language

---

code/modules/mob/new_player/new_player.dm

Informs players who do not have records that they are required to have records by our current rules.
:cl:
tweak: Adjusts message when attempting to join without records.
/:cl:

Records Requirement

---

code/datums/autolathe/parts.dm
code/datums/craft/recipes/guild.dm
code/modules/research/designs/weapon.dm

<details>
<summary>
Corrects some gunmod names
</summary>
<hr>
Corrects instances of recipe, disk, and research gunmod names not matching what their player-facing name is to make it easier for players to find.
<hr>
</details>

Fixes gunmod names

---

code/modules/mob/living/carbon/human/human_movement.dm

painkillers no longer give speed buffs

painkiller changes

---

code/game/objects/effects/decals/crayon.dm

Adds a weapon to crayon mages due to popular request. THROWING CRAYONS requires scrolls to get. Does more damage less hp you have.
Buffs Floor Seal scroll to remove deep maint holes.
Fixes Warren card carp cards to actually create deep maint entry points now.
Adds Mightier scroll spell to summon a single throwing crayon per scroll.

sharpened crayons

---

code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm

<details>
<summary>
</summary>
<hr>
Long overdue, this was meant to be a thing when I first made them but never got around to doing it.
<hr>
</details>
:cl:
add: Imprinters to beacon
/:cl:

Imprinters

---

code/modules/power/supermatter/supermatter.dm

<details>
<summary>
Rad collectors now work with supermatters! It even has decay with range!
</summary>
<hr>
still not working with "real" radiation, that requires a refactor of collector code and probably of the radiation subsystem too
<hr>
</details>
:cl:
fix: rad collectors now output power when near an active supermatter (max range still 15)
/:cl:

rad collectors are now viable

---

code/modules/client/preference_setup/loadout/lists/general.dm

<details>
<summary>
Zoe pointed out we didn't had it, easy fix, therefore I fix
</summary>
<hr>
tested locally, data disk included
<hr>
</details>
:cl:
add: universal recorder on loadout (general tab, one point cost)
/:cl:

add tape recorder to loadout

---

code/game/objects/items/weapons/tools/_tools.dm

Tools now longer shadow stick around well being deleted

tool break fix

---

code/controllers/subsystems/migration.dm
code/game/antagonist/antagonist_create.dm
code/modules/aberrants/organs/_defines.dm
code/modules/hydroponics/spreading/spreading_growth.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/projectiles/projectile.dm
code/modules/reagents/reagents/medicine.dm

https://github.com/discordia-space/CEV-Eris/pull/7807
https://github.com/discordia-space/CEV-Eris/pull/8014
https://github.com/discordia-space/CEV-Eris/pull/8013
https://github.com/discordia-space/CEV-Eris/pull/8012
[By Firefox13](https://github.com/sojourn-13/sojourn-station/commit/10e7dffa6c8595ef5551015ee60629a84ccd72a5) 
Makes antag creation now properly log whoms become the antag
[By SingingSpock](https://github.com/sojourn-13/sojourn-station/commit/37094e8b89ad4332945759544c37cad144c82262) 
Fixes maintshroops and plants illegaly moving around
Fixes maintshroops not properly caring about lumcount
[By MLGTASTICa](https://github.com/sojourn-13/sojourn-station/commit/461e213e87be8c8714f19ac7109a9bf371ce48d3) 
Removes a sleep(0) from bullet shooting code
[By …

Erisportsss

---

code/modules/power/solar.dm

<details>
<summary>
that's it, no mystery, just changed the solars computer from the god-awful ui code that it had to TGUI
</summary>
<hr>
- we are almost out of stuff to port to TGUI without changing the layouts in js
- several things have very different mechanics than here, making the change either tiresome or possibly requiring to change the item in question to a tg version of it (air alarms is a big offender in that front)
<hr>
</details>
:cl:
code: solars computers now use TGUI
/:cl:

TGUI solars computer

---

code/modules/organs/external/_external.dm

<details>
<summary>
i hate u psions
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Exalt Psions stop gibbing

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
CEO disposal fix, wire fix, etc. 
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Fixes Map Issues

---

code/game/machinery/sorter.dm
code/game/objects/items/weapons/storage/firstaid.dm
code/modules/organs/internal/bones.dm
code/modules/organs/internal/internal_organ_processes.dm
code/modules/reagents/reagent_containers/food/snacks.dm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Fixes many missing wires
Fixes a missing pipe for the trash line
Fixes missing items in kitchen
Adds a more ladders and stairs in maints
Adds more reacharger and paper tables to halls
Fixes biostorter rejecting bodies
Fixes surgery kits not able to hold everything that it spawns witn

fixes many things

---

code/game/objects/effects/decals/crayon.dm
code/game/objects/effects/decals/remains.dm
code/game/objects/structures/flora/flora.dm
code/game/turfs/simulated/footsteps.dm
code/modules/clothing/clothing.dm
code/modules/reagents/reagent_containers/food/snacks.dm
code/modules/sanity/sanity_mob.dm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Walking now restores tiny amounts of sanity
Fixes eating food not giving desier
Fixes more map issues with stairs and atms

more sanity and map fixes

---

code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm

Fixes some npcs not having proper ammo

fixes up some npcs

---

code/game/objects/effects/decals/crayon.dm

adds crayon pouch and related ritual.

Crayon Pouch

---

code/modules/mob/living/carbon/superior_animal/termite/termite.dm
code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
code/modules/mob/living/simple_animal/friendly/crab.dm
code/modules/mob/living/simple_animal/friendly/exotic_animals.dm
code/modules/mob/living/simple_animal/friendly/light_geist.dm
code/modules/mob/living/simple_animal/friendly/possum.dm
code/modules/mob/living/simple_animal/friendly/roomba.dm
code/modules/mob/living/simple_animal/friendly/slime.dm
code/modules/mob/living/simple_animal/friendly/spiderbot.dm
code/modules/mob/living/simple_animal/hostile/alien.dm
code/modules/mob/living/simple_animal/hostile/big.dm
code/modules/mob/living/simple_animal/hostile/creature.dm
code/modules/mob/living/simple_animal/hostile/dino.dm
code/modules/mob/living/simple_animal/hostile/hivebot.dm
code/modules/mob/living/simple_animal/hostile/huntersprey.dm
code/modules/mob/living/simple_animal/hostile/jelly.dm
code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
code/modules/mob/living/simple_animal/hostile/mimic.dm
code/modules/mob/living/simple_animal/hostile/misc.dm
code/modules/mob/living/simple_animal/hostile/tomato.dm
code/modules/mob/living/simple_animal/hostile/tree.dm
code/modules/mob/living/simple_animal/parrot.dm

adds sanity effects to more mobs

helpful mobs

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Fixes up the last few known to me errors
Buffs scavs a lot by adding a second buy window, as well as readds their venders well giving them more space

last fixes, that i know about

---

code/datums/outfits/jobs/security.dm
code/modules/clothing/masks/balaclava.dm

<details>
<summary>
</summary>
<hr>
Gives marshals their loadout hat on spawn like blackshield has and makes balaclava no longer show hair when you unroll it from your face
<hr>
</details>
:cl:
add: Rounstart hat to marshal officers
fix: Balaclava showing hair
/:cl:

Marshal hat and balaclava

---

code/datums/perks/racial.dm

<details>
<summary>
</summary>
<hr>
Title
<hr>
</details>
:cl:
fix: Mar'qua addiction immunity
/:cl:

Makes the marqua perk not lie

---

code/__DEFINES/economy.dm
code/game/jobs/department.dm

<details>
<summary>
</summary>
<hr>
Increases wages to account for the fact we no longer get 8 to 16 hours rounds but 4 to 5 at best
<hr>
</details>
:cl:
balance: Wages
/:cl:

9 to 5 experience

---

code/modules/sanity/sanity_lists.dm
code/modules/sanity/sanity_mob.dm

Removes whispering from sanity. Adds quotes instead that will span messages into your head, hopefully alerting players better their stanity is low.
:cl:
removes: Sanity whispering shit
tweak: Replaces the force creepy emotes
/:cl:

No More Sanity Whispering

---

code/modules/organs/internal/internal_organ_processes.dm

Should fix runtimes with liver and kidneys getting NULL damage values.
:cl:
fixes: runtime issue. Unsure of effects.
/:cl:

Fixes internal organs nulling damages

---

code/modules/sanity/sanity_mob.dm
modular_sojourn/task_master/tasks.dm

Oddities now work again on first resting rather then nulling
Fixes an issue with a task

fixes some insighter

---

code/modules/sanity/sanity_mob.dm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
modular_sojourn/task_master/_task_master_defines.dm
modular_sojourn/task_master/tasks.dm

Smoking around no smoking signs no longer restores sanity or rest - Unless you have the chainsmoker perk, in that case you dont care
Smoking around smoking area sings give you an additional sanity, as well as a task

smoking nerfs?

---

code/modules/projectiles/guns/energy/laser/antebellum.dm
code/modules/projectiles/guns/energy/laser/carpediem.dm
code/modules/projectiles/projectile/beams.dm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
100% tested both fixes
</summary>
<hr>
- disposal line from the beacon now 100% arrives at the intended location
- the wires under the SMES that power the shield now work as intended
- LS substation APC is now properly wired
- carpediem lost it's charge mode, but fire delay got adjusted accordingly
- gave 5ap to antebellum, hopefully it's not too much
<hr>
</details>
:cl:
map: colony's shield now properly charges
map: garbage beacon chute now reaches the smelter room 100% of the time
map: LS substation APC is now wired to the grid
balance: carpediem is now viable, gun mechanics heavily changed, but the niche of the gun was found
balance: antebellum main mode now has 5 ap
/:cl:

small mapfix + church rebalance round 3

---

code/modules/sanity/sanity_mob.dm

Tweaks the wording on the message to better get across the lessened sanity gain
Adds a 51 puffs cooldown on the message

adds a message cooldown to nonsmoking areas

---

code/game/machinery/autolathe/matterforge.dm

<details>
<summary>
changes the values of compressed matter obtained from materials on the forge and adds ameridian as an option for it
</summary>
<hr>
https://www.youtube.com/watch?v=-fC2oke5MFg this video explains the thought process of the rates before this pr was made
<hr>
</details>
:cl:
add: matter forge now accepts ameridian, almost as good as compressed matter itself
balance: matter forge had it's material conversion rate changed in a way that takes into account both material density and availability
/:cl:

forge rebalance

---

code/game/jobs/department.dm
code/game/jobs/job/prospector.dm

-Reduce Prospector and Salvager income to none. Foreman remains unchanged. 
-Reduces departmental funds from 10600 to 6500.
-Now with 3/3 Headadmin approval, k5
-#possumsvision
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Stop Making Me Hurt You

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
Marshal Armory QoL. Changes around how the Blast Doors work, separating the interior blast door to the exteriors like it was on the old map. Moves the lathe around to the interior as well as the disks and repositions the locker.
Compiled and Tested.
</summary>
<hr>
<hr>
</details>
Marshal Armory QoL. Changes around how the Blast Doors work, separating the interior blast door to the exteriors like it was on the old map. Moves the lathe around to the interior as well as the disks and repositions the locker.
/:cl:

Marshal Armory QoL

---

code/game/objects/items/weapons/shields.dm

<details>
<summary>
This reduces 'durability' damage to shields from roaches(/6), spiders(/2), and termites(/2).
Requested by Dissent and to help balance shields from breaking so often against weaker type enemies
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Shield Balances

---

maps/SpaceFortress/map/space_dungeons.dmm

Fixes up some area stuff and removes cams for an unused atm map

area and some map fixes

---

code/modules/clothing/under/jobs/civilian.dm
code/modules/clothing/under/jobs/engineering.dm
code/modules/clothing/under/jobs/security.dm

Fixes missing spelling i in visibality 
Fixes some sec cloathing not adjusting their icon properly

fixes some spelling and bad slot_w_uniforms

---

code/modules/clothing/under/jobs/civilian.dm
code/modules/clothing/under/jobs/engineering.dm
code/modules/clothing/under/jobs/security.dm

Trys again to fix thins

---

code/controllers/subsystems/voting/poll.dm
code/modules/sprite_accessories/_accessory_hair.dm

<details>
<summary>
</summary>
<hr>
Removes a slur from code, think it's obvious as to why
<hr>
</details>
:cl:
del: Slur
/:cl:

Github TOS

---

code/modules/clothing/clothing.dm

<details>
<summary>
</summary>
<hr>
Fixes a broken feature so that accessories can be made spawnable on clothing.
<hr>
</details>
:cl:
fix: Accessory spawning
/:cl:

Fixes accessories on spawn

---

code/game/objects/items.dm

Fixes a typo in alt-modes

---

code/game/objects/items/weapons/storage/church_kits.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm

Compresses some church path armor into 1 type with alts
Compresses down some descs of church path armor

fixes armor doups and compresses

---

maps/SpaceFortress/spacefortress.dm
maps/__Nadezhda/data/shuttles-nadezhda.dm

event over

---

maps/Centcom/map/centcom.dmm

fixes a douped navpoint

---

code/modules/research/xenoarchaeology/machinery/psionic_harvester.dm

Ports the psionic harvester fix
is a 1:1 port so shouldn't mess anything up.

psionic harvester port

---

code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipes_to_covert.dm

<details>
<summary>
Add 7 new cooking recipes.
</summary>
<hr>
Add recipes for 
- Burger
- Beef Curry
- Chicken Curry
- Mashed Potatoes
- Loaded Baked Potato
- Banana Bread
- Patty
Based on the microwave recipes. Removed from recipes_to_convert.md.
<hr>
</details>
:cl: dutop
add: Add 7 cooking recipes
/:cl:

Add recipes

---

maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
</summary>
<hr>
Pls save me from my ineptitude. 
Area tag fix, plus air vent/scrubber fix. (I learned how they work now, at least)
<hr>
</details>
:cl:
Added in 3 more dorms, pool, sauna, hot-tub, and a fireplace common area with furnishings and vendors.
Swapped chemistry windoor to the interior side
connected the janitor APC, there was no wire there originally
Reduced the number of slot machines and moved them, replacing them with more booths.
Fixed power cable in lower soteria science.
Souped up the guildmasters quarters.
Moved maintenance gardern to where maintenance pool was(this was to make room for dormatory common area).
Renamed Dorm cat to "Mr Snuggles" because why not.
Added Lizard called "Slippy" to fireplace common area.
Adjusted number of smoking signs in …

Redo....redo...Of Skinks First Map Edit (last one, I promise)

---

code/game/objects/structures/crates_lockers/closets/fitness.dm

<details>
<summary>
The athletic wardrobe, especially when near the pool, could take a few towels
</summary>
<hr>
Added three towels to the athletic wardrobe
<hr>
</details>
:cl: dutop
add: Three towels added to athletic wardrobe
/:cl:

Add three towels to the athletic wardrobe

---

code/game/objects/random/mob/misc.dm

<details>
<summary>
remove the Pitch Horror from spawning because its literally only a reskinned Crimson Jelly with more HP and armor pen, its functionally the exact same besides those two points and is a menace to deepmaint i hate it so much and it adds absolutely nothing to deepmaint (its also ugly as fuck)
fank you twilby for explaining how work
local tested and works
</summary>
<hr>
<hr>
</details>
:cl:
code: removed pitch horror from spawning
/:cl:

baby's first salt PR

---

code/modules/client/preference_setup/loadout/lists/xenowear.dm

<details>
<summary>
Just a typo synthetizer -> synthesizer.
</summary>
<hr>
<hr>
</details>
:cl: dutop
spellcheck: Typo in Opifex gas synthesizer 
/:cl:

typo in opifex mask

---

code/game/objects/items/oddities.dm

<details>
<summary>
Makes the bluespace scanner device actually work. Removes the check, because I couldn't make it work and frankly i dunno if it really is necessary.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

fixes the bluespace scanner oddity

---

code/modules/clothing/head/helmet.dm

<details>
<summary>
Title
</summary>
<hr>
<hr>
</details>
:cl:
fix: Fixed lemni hat turning into tesselate veil visually
/:cl:

Fixed lemni hat turning into tesselate veil visually

---

code/game/objects/items/oddities_faction.dm

Direct line no longer has a exploit were you can spam click and endlessly unlock stations

Direct line exploits fix

---

code/modules/projectiles/guns/energy/laser/carpediem.dm
code/modules/projectiles/projectile/beams.dm

<details>
<summary>
Buffed damage and reduced fire delay
</summary>
<hr>
<hr>
</details>
:cl:
balance: buffed carpediem
/:cl:

Carpediem buff, recommended by Rain Chule

---

code/modules/sanity/sanity_lists.dm

<details>
<summary>
Fixes typo in sanity messages
</summary>
<hr>
Conjugation of verbs in third person singular.
<hr>
</details>
:cl: dutop
spellcheck: Fixes typo in sanity messages
/:cl:

Typos in sanity messages

---

code/game/objects/structures/janicart.dm

<details>
<summary>
Make janitorial cart destructible
</summary>
<hr>
There was no way to destroy the janitor cart. This seems unreasonable.
Dismantling via wrench didn't work, because the variable `dismantle` was already set to `TRUE`. Now it is set only after dismantling. Remember to remove the trash bag first or wrench is in bag. A bit of metal and plastic is yielded. The items in the cart tumble around a bit.
Gunfire didn't work, because `health` was not set to a reasonable value and there were no methods to minimize the value of the `health` variable. Methods added, taken from /obj/structure/closet. If health is 0, the cart ceases to exists, its item tumble around. 
Park the cart next to a fuel tank. Blow up the fuel tank. The contents of the cart fly around, the cart itself is …

Make janitorial cart destructible

---

code/modules/projectiles/guns/energy/projectile/sst.dm
code/modules/projectiles/projectile/bullettypes.dm
code/modules/research/designs/greyson.dm
code/modules/research/nodes/combat.dm

<details>
<summary>
brings back the SST format bound and system cost as well as readds the soporific 7.65 bullet to the code. compiled but didn't host to test it (my PC is too shit today for some reason)
</summary>
<hr>
i miss my sopo guns
<hr>
</details>
:cl:
add: readded the 7.65 sopo round to code (who gutted it? dunno but its back now)
code: reenabled the format bound and system cost 
/:cl:

TALLY HO EEPY TIME TO GO

---

maps/_HunterLodge/map/_Hunting_Lodge.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
Going through and updating the closets at the Lodge, changing the entire power grid for the Lodge and went over on the colony to remove the stray light in the Premier's office. Should be all gone now! 
</summary>
<hr>
See above in summary, however, I'll show images of the direct changes I've made. Also-- Adding a patio that overlooks the solar array with a little tea pot and little flowers. Yet another RP spot at the Lodge that we'll sadly never see used.
<hr>
</details>
:cl:
add: Lodge Patio
del: Premier Office Light
fix: Fixed closets and bins across Lodge
tweak: Changed Lodge's solar array
/:cl:

Revamping Lodge Power + Colony Map Fix

---

code/game/objects/items/devices/radio/headset.dm

Fixes BS regular headsets lacking fallback comms.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

fixes BS headsets

---

code/modules/admin/verbs/diagnostics.dm

These commands crashed the server/were irrelevant respectively and have been disabled.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Disables reload admin/mentor

---

code/datums/autolathe/gun_frames.dm
code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
code/modules/mob/living/say.dm
code/modules/projectiles/guns/energy/projectile/railgun.dm
code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
code/modules/projectiles/guns/projectile/automatic/nordwind.dm
code/modules/projectiles/guns/projectile/automatic/ostwind.dm
code/modules/reagents/metabolism.dm

Adds the wind(ostwind + Nordwind) frame to the Marshal disk.
Raises the price of the wind frame to include diamond owing to the high quality of the weapons it produces- ditto for the omni frame. In the future I may want to find an alternative resource for these higher quality weapon frames
fixes [#4767](https://github.com/sojourn-13/sojourn-station/issues/4767) probably. Adds a check to prevent bleeding once blood has reached a certain volume.
fixes [#4763](https://github.com/sojourn-13/sojourn-station/issues/4763) , im not sure how this ever worked but should be fine now.
Probably fixes [#4740](https://github.com/sojourn-13/sojourn-station/issues/4740), there was a pathing issue.
First two were all trilby :)
oops forgot to make a new fork so i guess this is also a bugfi x pr now …

Buffs marshals for Pneumo. Nerfs marshals for Meeeeeee also some bugfixes i guess

---

code/modules/projectiles/guns/energy/laser/abdicator.dm

removes a mistakenly doubled-up proc for turning safeties off, should work now.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

should've tested the last bugfix, oh well.

---

maps/Centcom/map/centcom.dmm

<details>
This creates and adds an ERT Ready Room.
<summary>
This creates and adds an ERT Ready Room that will allow admins and mods to access and prepare ERT characters quicker and without needing the ADMIN+ or SPAWN+ perms. This is exclusively for the times that we do need and use ERT when applicable. 
</summary>
<hr>
The room, seen below comes with the capacity of five units. Three Marshal Units and two Corpsman Units. Images of the loadout are provided with this. For ammo, they are given an ammo printer with six stacks of refined scrap which should be more than enough scrap for any of the loadouts. They come with WO headsets, Marshal IDs, and ammo pouches for each type of weapon. 
There's four boxes of gun parts for all the attachments for any of the guns, ten medium super cells, ten …

Creating ERT Ready Room

---

code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/maint_loot.dm
sojourn-station.dme

<details>
<summary>
```Mobs inside of lockers now have a tell, this tell can be inaccurate as its spawners can spawn nothing so you can be tricked!
This in theory shouldnt do much to reduce lag but according to SoJ it helps a lot.
Code wise mobs inside lockers wait to spawn untill opened, destorying the locker directly will not cause the mobs to spawn
this is intented as your expending ammo to bypass fighting mobs inside```
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Trilby asked me to port this - Reladds mobs into lockers

---

code/game/objects/items/weapons/manuals.dm
code/game/objects/structures/noticeboard.dm
code/modules/client/preference_setup/loadout/lists/utility.dm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Adds a new manual for the roboticist(and players) that includes pictures of and a bit of lore for all the various borg frames. - You can either grab it in the loadout or ask the roboticist to see it, incase you were thinking of buying a bot of your own
Adjusts an old noticeboard paper that was incorrect.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Just a small PR this time, i promise.

---

code/datums/setup_option/core_implants.dm

Allows outsiders to use nanogates/psionic organs. Also fixes a small issue I noticed basic gates and organs both lacked a blacklist for AI/cyborg. So fixed that to! First PR so make sure I'm not gonna make anything explode. Tested locally and works fine.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

yet another outsider buff

---

maps/_DeepForest/map/_Deep_Forest.dmm

<details>
<summary>
This changes the excelsior base slightly to remove some tiles of pure space and prevent the room from being completely void of air.
</summary>
<hr>
This change removes the chance to vent the room directly to space. 
The change includes adding tiles underneath these halfwalls in particular.	
<hr>
</details>

Excelsior Space Program

---

maps/_DeepForest/map/_Deep_Forest.dmm

You know, when I took up mapping I did know it would be miserable. However, the word 'miserable' has it's limits. Also I am sorry Cdb but making an entirely new PR is the easiest way for me to get around the multi-file problem quickly
] Replaced Excel mines with normal mines due to runtime issues (please get back to me on that one)
] Added more loot
I may add more bears and excel slaves in the future, depending on if this is enough to satisfy the masses. Clearly you are all too cowardly to break into somewhere without enough reward.
Enjoy.

Update - Loot & Mines

---

code/modules/reagents/reagent_containers/food/drinks/bottle.dm

<details>
<summary>
Bottles that are smashed against a wall or mob won't show a message "contents of [bottle] splash all over [target]" if they are empty.
</summary>
<hr>
<hr>
</details>
:cl: dutop
fix: No message regarding contents on empty bottles
/:cl:

No message regarding contents on empty bottles

---

code/modules/projectiles/ammunition/boxes.dm
code/modules/projectiles/guns/energy/projectile/railgun.dm

Pretty simple PR no changes to balance. All this does is add some descriptions and change the names of rail gun fire modes to be a little more clear that these are not non-lethal weapons. More less lethal and in some cases totally lethal! Should give a better understanding to the player of just what calibers won't break every bone in someone body if they wanna avoid it.
<hr>
</details>
:cl:
/:cl:

Better descriptions for ''non-lethal'' ballistics

---

code/datums/craft/recipes/furniture.dm

Quality of life change. Makes the entire process of making soil plots less mind numbingly slow.
It just tweaks one number. It compiles.

Soil crafting crafting time reduction

---

code/modules/mob/living/silicon/robot/gripper.dm
code/modules/mob/living/silicon/robot/robot_items.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/modular_computers/file_system/programs/generic/camera.dm

Buffs their omnitool to allow the bare minimums needed to produce all Guild crafts. Yes. they can print tools and toss them on a table and have humans help put cells in but really? Tedious and anti-fun! 
Allows their magnetic gripper to hold the black box cube to start the nanoforge.
Gives them a mini RPED. seriously! Maint drones have this so silly! This is most importantly so they can upgrade the nanoforge without needing to destroy the cube prying it apart.
They only had 40 mechanical....very underwhelming bumped it to 60. Should be good at what they do they can't do much else.
Also a small touch on the medical module gave their crowbar rather weak digging so they can painstakingly deal with burrows on their own like every other module.
Tested locally compiles and runs. Gripper works …

Guild borg buffs mostly (so they can do their job)

---

code/modules/modular_computers/file_system/programs/generic/taxes.dm

<details>
<summary>
Makes the TaxQuickly 2561 program available to download on all devices
</summary>
<hr>
Pretty much what it says on the tin. This change is primarily intended for Heads and others who have more than one account they manage, allowing them to have a laptop/tablet/console dedicated to managing the department account. There's nothing about the program that makes it need to be on a PDA, I tested and this works just fine.
<hr>
</details>
:cl: SingingSpock
tweak: The non-antag TaxQuickly program can now be downloaded on all devices, not just PDAs.
/:cl:

Makes non-antag TaxQuickly available on all devices

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

] Adds a Xeno Storage room in lower maints for all those non-prospies to have a go at.
Requested earlier by the many legends that don't play Prospector.

Adds new mini-room at the lowest maints

---

code/modules/aberrants/organs/design_disks/disks.dm
code/modules/aberrants/organs/spawners.dm

After many a long days spent as medical in deep maints looking for OMG venders I've become TIRED. 
Significantly improves the spawn rates of all the useful organ venders. About 2 times more common
Reduces the spawn rates of the classics one since it just exists to sadden me every time I see it. (same stuff medical can produce round start) Reduced by a LOT! Hate you classics vender.
Reduces the spawn rates of medi sarcophagus sleepers. Still very common! Lots of deep maint maps contain these hardspawned. Reduced by about a quarter
Mostly the logic behind this is these numbers no doubt come from Eris where deep maints is a walk in the park compared to here. This should be much more inline with the level of difficulty to reward down there. Plus hopefully! Gives are bored doctors more to do. …

Organ vender spawn rate buff.

---

code/game/mecha/equipment/weapons/ranged/laser_weapons.dm
code/game/objects/structures/noticeboard.dm
code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/modular_computers/file_system/news_article.dm
code/modules/research/designs/mecha_equipment.dm
news_articles/wanted_issue_terran.html

A new wanted issue has been added to the shield/marshal bulletin boards and the news app.
Also fixes the mech mounted sonic gun.
Fixes the code for french toast that would've prevented the server from compiling. oops, lol!
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Bugfix + wanted issue.

---

code/game/objects/items/weapons/storage/firstaid.dm

Quick PR adding ossi tape to the combat surgery kits I assume this was unintended to be left out. Essential for doing bone repairs the most COMMON type of organ repair. 
I don't personally think this needs a test merging but it doesn't lock up a particularly important file either way.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Adds ossi tape to the 3 advanced surgery kits

---

code/modules/psionics/psionic_items/psi_armor.dm

<details>
<summary>
I love people writing a comment about how the gloves they coded are insulated after a line that makes them entirely uninsulated
</summary>
<hr>
<hr>
</details>
:cl: SingingSpock
fix: Psionic gloves are now insulated as intended
/:cl:

Makes psionic gloves actually insulated as intended

---

code/game/objects/effects/decals/crayon.dm
code/game/objects/items/crayons.dm
code/game/objects/items/oddities.dm

Better details crayon magic being crayon magic

crayon fluff

---

code/modules/organs/external/subtypes/robotic_types.dm

Fixes Greyson, excelsior and the unused Nashef limbs missing bioprotection causing synths who install them to take damage from biomatter and god knows what else.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

robot limbs bio protection bugfix

---

code/modules/clothing/spacesuits/void/station.dm
code/modules/psionics/psionic_items/psi_Harmor.dm
code/modules/psionics/psionic_items/psi_Larmor.dm

Fixes 2 armors not being space proof. As well as some minor balance changes 
The medical void armor printed at R&D is now space proof duh its a space suit. Helmet also given higher energy protection to make it closer to the armor its attached to. 
Suit given reduced slowdown given it's meant for medical use. Still rather slow but on the slightly higher end as far as voidsuits go for slowdown.
Psion heavy and light armors given insulated gloves given they are intended to be a upgrade from standard psion armor. Heavy armor had its pressure resistance fixed as well and is now space proof.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

armor fixes!

---

code/modules/genetics/mutations/disability.dm

Smol fix for a rarely used gene. Simply switches it over to using race flags rather then cursed old genetics stuff. Tested fully and works. fixes #4869 
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

fixes Anomalous Air Supply gene

---

code/game/machinery/kitchen/smartfridge.dm

Did a minor fuckup. Fixes disk storage fridge icon disappearing. Hopefully.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

disk storage fix

---

code/game/objects/items/devices/lighting/flare.dm

<details>
<summary>
@Gidgit
This adds damtype = BURN to "torch" allowing them to burn webs.  It also ensures torch cannot burn webs when not lit.  Tested and working.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Torch web burn

---

code/modules/biomatter_manipulation/bioreactor/bioreactor.dm

<details>
<summary>
As per Trilby's suggestion. Buffs big biomatter can to 1000 and medium to 750
</summary>
<hr>
<hr>
</details>
:cl:
balance: Buffs large biomatter can to 1000 and medium to 750
/:cl:

Buffs biojuice tanks

---

code/game/objects/items/devices/organ_module/active/armblades.dm

Gives the armblade augment a hit sound effect as it was missing one super duper simple.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

fixes armblade sound

---

code/game/objects/effects/decals/crayon.dm
code/game/objects/random/cloth.dm
modular_sojourn/cardgame_2/cardgame_2.dm
modular_sojourn/cardgame_2/cardpacks_and_spawner.dm

Reorganizes crayon decal dm
rebalances rat deck for card carp - again
adds pelt lice card
Adds 2 more spells to crayon magic
Tea party and Escape
Nerds daus 
Adds some better code to crayon decal dm

Of Cards and Crayonsolot

---

code/game/machinery/vendor/recycle_vendor.dm

<details>
<summary>
fix own bug that prevented the recycling vendor from accepting items
</summary>
<hr>
<hr>
</details>
:cl: dutop
fix: fix own bug that prevented the recycling vendor from accepting items
/:cl:

fix own bug that prevented the recycling vendor from accepting items

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

notes: I'd consider everything in this PR a bugfix _however_ this is my first major mapping PR and I've mostly learned from trial and error so I'd suggest a test merge regardless encase I somehow broke everything but I tested pretty thoroughly
Changelog: 
Fixes the engineering turbine burn chamber. Adds a gas sensor, high volume vent, and correctly links the vent to the computer.
Adds to atmos a hard storage of sorts. Has most kinds of gas canisters, spare pumps and scrubbers as well as 3 emitters. Back are the days of engi using these on blobs I hope.
Adds 2 boxes of the unique disks needed for old genetics to the old genetics lab. 
Adds normal plating to all low walls I could find missing it. This was not funny! It was inconsistent what ones had underplating and what ones had normal …

misc map fixes

---

maps/_DeepForest/map/_Deep_Forest.dmm

Should be fixed now if the PR is put in place.
> Added actual flooring under the glass.

Had some trouble with the glass

---

code/game/mecha/mech_bay.dm

Significantly increase the charge rate of mech rechargers. Very simple! Tested. It's bothered me for the longest time these large rechargers being pretty damn useless taking absolutely ages to recharge a mech and usually being outclassed by a T4 cell recharger. It now sits somewhere between the charge rate of a normal charger and a industrial charger. Peaking with upgrades at about 3-5% per cycle depending on the cell size, 
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

useful mech chargers

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
New storage closet for medical in the lower area, includes a lathe with some basic materials,(plus a lethals disk so SLT stop dying when they wrongly choose the bullpip primary.) basic medical disks, recharger, smartfridge(in case you want to put hyperzine away from the main floor.), and wall storage locker.
Relocates many of the most commonly pilfered medical stuff to this single closet. The medkits, defib(which now has a spare cell that actually matches it.)
Also gives medical a couple jars of bare-minimum meds in said closet.
Medical blood-freezer is still in the main area for obvious reasons however it now has access requirements.
Adds a few missing total lockdown shutters for medical.
Moves the medbay-lower break room(the lil tiiny one), adds a new hallway between …

med map changes

---

maps/_DeepForest/map/_Deep_Forest.dmm

<details>
<summary>
Just stops an annoying error that happens every startup complaining about a duplicate APC.
</summary>
<hr>
<hr>
</details>
:cl:
fix: Removed duplicate APC in forest excel bunker
/:cl:

Removes duplicate APC from forest excel bunker

---

code/modules/projectiles/guns/projectile/automatic/c20r.dm
code/modules/projectiles/projectile/bullettypes.dm

Tweaks the values for HP damage/postpen mult. They've generally received slightly more mutiplier on their damage and less damage overall. The last buff i made to HP bullets made an incorrect assumption of how these rounds worked with armors of varying types, resulting in SEVERELY overtuned rounds that outperformed their alternatives by sometimes double(We're talking 45 damage .408s which could only be reduced by full on bulletproof armor and even then only to about base damage).
Sorry HP stans, they still work quite well just maybe less insanely so.
Fixes an exploit with the bullpip where you could disassemble it and reassemble it iinto a bullpup.
Buffs the bullpip a bit, it's still inferior to the bullpup but not insanely so(old dam 1, pen 1. New dam 1.1, pen 1.3)
Bullpup and Bullpip can …

guns and bullets 

---

code/game/machinery/vendor/misc_vendors.dm

<details>
<summary>
Fix: Game vendor sold invalid deck of cards
</summary>
<hr>
The game vendor Game Emporium sells /obj/item/deck. This deck of card looks great until you try to deal a card of the deck - it is empty. (cards is an empty list). Get a deck of cards from the old library and it works. The difference: it's an object of /obj/item/deck/cards. 
So I told the Vendor to sell /obj/item/deck/cards instead.
<hr>
</details>
:cl:
fix: Fix card game in vendor
/:cl:

Fix game vendor: Sell real deck of cards

---

code/modules/organs/internal/psionic.dm
code/modules/psionics/psion_powers/pyschiatrist_powers.dm

<details>
<summary>
considering the upcoming possible removal of crayon time for psions i wanted to readd a funky power to the cultured organ
</summary>
<hr>
readds peace of mind
changes cost to 4 from 2
<hr>
</details>
:cl:
add: readded peace of mind
balance: doubled psion point cost of peace of mind 2 > 4
:cl:

psion sleepy time powers return

---

code/modules/mob/living/simple_animal/hostile/syndicate.dm

>Adds armor to the simple mob "Elite Mercenary".
> Also adds some health to it's 'Heavy' variation.

Elite Armor

---

code/game/machinery/shower.dm
code/game/objects/items/weapons/clown_items.dm
code/game/objects/structures/watercloset.dm

Small fix to soap/showers allowing them to clean blood off bare feet. Tested and works. Also admit looked at Polaris on how they fixed this. Yes its tested.
For context it used to be impossible to clean blood off feet causing you to just become cursed for the entire round if you dare step on blood without shoes on.

fixes showers/soap

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
Fixes gatehouse door with no access requirements, adds button for Blackshield shutters
</summary>
<hr>
The door from the gatehouse proper to the between-gates area had its access list improperly written, causing it to runtime. Fixed that, and added a button for these shutters
<hr>
</details>
:cl:
map: Fixed a couple map issues for Blackshield
/:cl:

Fixes a couple security map issues

---

code/modules/projectiles/guns/projectile/revolver/capgun.dm
code/modules/projectiles/projectile/bullettypes.dm

Prevents cap guns from being taken apart for a fully functioning revolver as well as making their ammo boxes correctly populate with ammo. Fixes cap guns firing a projectile in spite of being a cap gun.
~~Side note: 
these still have one major issue left they fire a harmless projectile that triggers screen shake. Makes no sense and is liable to cause confusion tried and tried and I could not come up with  a fix so if anyone has any ideas.~~
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

fixes cap guns

---

code/controllers/subsystems/jobs.dm
code/datums/perks/backgrounds.dm
code/modules/sanity/sanity_mob.dm

Fixes players not gaining NSA after gaining it/having it round start. Trilby helped. Thanks cat.
Fixes the desc on nihilist saying its 10% positive breakdown and 20% neg breakdown. In reality its 30 and 20
Tested and works.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Vivification fixes plus smaller stuff.

---

code/modules/projectiles/projectile.dm
maps/_DeepForest/map/_Deep_Forest.dmm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Admin messages

---

code/modules/clothing/spacesuits/rig/suits/combat.dm

<details>
<summary>
accidentally gave the baseline combat suit negative stiffness as a test and forgot to set back. fixes.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

fix a small oversight, oops.

---

code/game/objects/effects/decals/Cleanable/humans.dm
code/game/objects/effects/decals/Cleanable/misc.dm
code/game/objects/effects/decals/remains.dm
code/modules/sanity/sanity_mob.dm

Reduces blood sanity damage from 0.5 to 0.25
Reduces remains sanity damage from 1 to 0.5
reduced human remains sanity damage from 5 to 2.5
Reduces passive insight gain from 0.05 to 0.025
Full Sanity raised from 150-300(This is what you start with.) Insight passive gain reduced from 0.5 to 0.25
insight gain multiplier lowered from 1.0 to 0.5
Low-threshold of environment damage raised from 20-100. suggestions were to raise this from 20-50 before sanity cap was doubled, that would be 33% of your max. To keep that percentage it was also doubled to maintain a nice level. This is only the 'lowest' that environmental sanity features can take you.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Sanity tweaks.

---

code/game/objects/items/weapons/storage/firstaid.dm

<details>
<summary>
Removes the bicaridine pill from IFAKs and adds a stack of splints
</summary>
<hr>
Splints are emergency medicine that can save your life in a fight, a single bicar pill is nearly worthless.
<hr>
</details>
:cl: Removes the bicaridine pill from IFAKs and adds a stack of splints
tweak:
/:cl:

Exchanges bicar pill in IFAKs for splints

---

code/modules/core_implant/cruciform/rituals/path.dm

<details>
<summary>
Changes Hymn of the Engineer's description to indicate requesting it rather than making it. This makes it clear that you can't recycle them for materials.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Changes the description of the Hymn of the Engineer factorial litany to make it clear recycling the mods is a sin.
/:cl:

Changes the Hymn of the Engineer description

---

code/game/machinery/requests_console.dm
code/modules/modular_computers/computers/subtypes/preset_console.dm
code/modules/modular_computers/computers/subtypes/preset_tablet.dm
maps/__Nadezhda/area/_Nadezhda_areas.dm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
Updates the Heads Offices, and a few smaller supporting changes
</summary>
<hr>
Updates each Head office to have 1) A command console and a console for their department if their department has one, 2) A command tablet, 3)Buttons to open and bolt their door on their desk (except Prime because holy doors work on prayers), 4) A Filing Cabinet, 5) A request console, and 6) some kind of bedroom or private space.
Warrant Officer office got a full remap, removing the old unused elevator and moving the WO office down, adding a small bedroom. The newly freed space got converted to a smaller briefing space for Marshals.
Redid a few areas: the main Bridge room is now one area (whose idea was it for it to be two?), the bridge hallway is its own area, and the security firing range …

Head Office upgrades and other things

---

code/__DEFINES/misc.dm

The data wants to be free
<details>
<summary>
Increases low, high, and ethernet speeds from .05, .15, and .4 to .25, .5, and 1 respectively
</summary>
<hr>
Downloading is just waiting to do what you actually want to do with your console. It's important to have in general, but it doesn't have to be an eternity	
<hr>
</details>
:cl:
tweak: Buffs download speeds across the board to be less of a pain.
/:cl:

Buffs download speeds

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
Exactly what it says on the tin
</summary>
<hr>
<hr>
</details>
:cl:
fix: The Warrant Officer can now tint their windows
/:cl:

Makes the WO's window tinter work

---

code/game/objects/items/weapons/tools/_tools.dm
code/game/objects/random/mob/roach.dm
code/game/objects/structures/crates_lockers/largecrate.dm
code/modules/mob/living/carbon/superior_animal/roach/types/benzin.dm
code/modules/projectiles/projectile.dm
code/modules/projectiles/projectile/bullettypes.dm
code/modules/projectiles/projectile/fragment.dm
code/modules/projectiles/projectile/plasma.dm
code/modules/projectiles/projectile/special.dm
code/modules/reagents/reagent_containers/food/cubes.dm
code/modules/reagents/reagent_containers/food/snacks/meat.dm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

A near direct port of benzins from https://github.com/Eclipse-Station/NEV-Northern-Light. Most of the changes are under the hood but some big mechanical things to note:
Most importantly very likely fixes a few major runtimes related to these annoying fellows tho time will tell.
Benzins will now explode based on projectile. Rubbers, arrows, etc _should_ not blow them up. Cant say I got every example for sure but I SHOULD have. Common sense should apply here for the most part. But most projectiles will explody.
Doing ANY form of burn damage to a benzin will make it explode. Laser scalpels, deep maint weapons, etc, If it burns it blows.
Benzins now only explode in a small 3x3 area. Smol. Less pain.
Likely other things I'm forgetting. Pretty much if something seems like it will blow one up it …

Sensible Benzin roaches

---

code/modules/admin/bluespacetech.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Gives Mods BST perms.

---

code/controllers/subsystems/vote.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
admin: +mod and +fun can now make votes.
/:cl:

Allows event ops and mods to make votes.

---

code/datums/craft/recipes/guild.dm
code/game/objects/items/weapons/tools/shovel.dm

Reverts sojourn-13/sojourn-station#4996

Revert "Crovel rebalance"

---

code/datums/craft/recipes/guild.dm
code/game/objects/items/weapons/tools/shovel.dm

[github.com/sojourn-13/sojourn-station/pull/4996)](https://github.com/sojourn-13/sojourn-station/pull/4996)
This pr but also adds the materal to the item!

Fix to crovl tweaks

---

code/modules/admin/verbs/adminsay.dm

Mods now get access to Asay (Admin say)
Requested by K5

Mod supremisy

---

code/modules/mob/living/carbon/human/human_movement.dm
code/modules/organs/internal/internal_organ_processes.dm
code/modules/reagents/recipes/recipes.dm

Eyes are now greatly (2x lmao) boosted by eye fixing chemicals 
Max hunger no longer constantly resets itself to 400 making genetic/tasks/ect changes permitate as intented
Anti-toxin no longer negitively impacts kidneys
Anti-toxin when mixed now has a byproduct of salt!

Antitoxin + hunger fix

---

code/datums/craft/recipes/guild.dm
code/game/objects/items/weapons/tools/shovel.dm

Also edited the flavor text a bit and fixed a spelling error in a comment
<details>
<summary>
</summary>
<hr>
Real men test on prod
<hr>
</details>
:cl:
fix: Fixed the crafting recipe not working
tweak: Cleaned up flavor text
/:cl:

fixed crovel recipe

---

code/game/objects/items/weapons/storage/pouches.dm

tubular pouches can now hold 40mm grenades, flashes and bread tubes.
<details>
<summary>
tubular pouches can now hold 40mm grenades, flashes and bread tubes.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

tubulkar pouch buff

---

code/__HELPERS/unsorted.dm

<details>
<summary>
What it says on the tin
</summary>
<hr>
Creates a new top-level proc, /proc/ennumeratemobs, that outputs the number of mobs on each Z-level, primarily for testing/lagfinding purposes
<hr>
</details>
:cl:
add: Adds a helper proc no non-staff player will ever interact with
/:cl:

Adds a new helper proc that returns the number of mobs in each z-level

---

code/game/gamemodes/storyteller.dm

Round now requires *one* person to be ready

no more ghost-crew

---

code/game/gamemodes/storyteller.dm

Replaces black text in lobby round start with angel say

Colour difference

---

code/game/objects/items/devices/defib.dm

Fixes defibs stealing stats and wrong messages

Fixes some bad layering code issues with defibs

---

code/modules/client/preference_setup/options_popup.dm

<details>
<summary>
Just what it says on the tin. Indentation is important, it's how the compiler detects flow.
</summary>
<hr>
<hr>
</details>
:cl:
fix: Fixes the "this should never be shown" message being shown
/:cl:

Fixes an indentation error that causes an error message

---

code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
code/modules/mob/living/carbon/superior_animal/human/stranger.dm
code/modules/mob/living/carbon/superior_animal/roach/roach.dm
code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm
code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm
code/modules/mob/living/carbon/superior_animal/termite/termite.dm
code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm

Generally reduces common mobs armor by up to half. Particularly energy/bullet armor with the sole exception of strangers who've been given a bit more energy/bullet armor and less melee armor.
Deepmaints mobs not touched. Megafauna not touched(for now). This is mostly roaches/spiders/termites and jungle birds(some of them had ablative armor equivilents).
This will likely need a lotta tweak before it's ready to go to market.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

mob armor nukiing.

---

code/game/jobs/job/assistant.dm

Exactly what it says on the tin. A person suggested it to me and seeing as how I am planning to re-do the lower council halls, I thought it would not be a bad idea.
This is an alt title for colonist.

Adds Journalist alt title

---

code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm

Datastar cant be betrayed by allied bullets
Datastar now has added layers of shielding
Datastar has learnt how to not be deleted
Datastar has collected data on how to use stairs

more data star buffs

---

maps/__Nadezhda/data/shuttles-nadezhda.dm

Lowers the amount of time that shuttles would spend in flight. As of right now, it's egregiously long to the point nobody ever uses them.
<hr>
</details>
:cl:
balance: reduced shuttle flight timers
/:cl:

Lowers the Shuttle Flight time

---

code/modules/mob/living/carbon/human/update_icons.dm

Fixes the recent problem of helmets not hiding ears cased by pr #4930 . Thank you to K5 for pointing out the problem

Fixes helmets not hiding ears

---

code/modules/research/xenoarchaeology/finds/finds.dm
code/modules/research/xenoarchaeology/geosample.dm
code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
code/modules/research/xenoarchaeology/tools/tools_coresampler.dm

Fixes maybe improper spawning of relics
Expands the methods of strange rock sampling and extracting

Xenoarch fix(es) and intractions

---

code/modules/hydroponics/seed_datums.dm

Yeah uh.. if you get your hands on omni its a free evo to panacea right now with no effort. Used to require trinity grass, another evo.
This fixes it by making that a requirement again. Looks more of an error than anything else.
Its fixed on my other PR, just in case somebody has a better fix for greater mutation.
Edit: Somebody did have a better fix.

Fixed Ambrosia Panacea being a freeby

---

code/datums/perks/backgrounds.dm
code/modules/sanity/sanity_mob.dm

<details>
<summary>
Removes anatomy from list of possible heirloom stats. This was allowing people to get hundreds of health every levelup.
Limits maximum reduction in environmental sanity damage from vigilance, preventing it from going into the negatives at values higher than 72 and allowing people to instantly refill their sanity bar by staring at runes and gibs.
</summary>
<hr>
<hr>
</details>
:cl:
balance: Removed anatomy from potential heirloom stats.
balance: Introduced cap to insight's reduction on environmental sanity damage.
/:cl:

Tames Some Exploits

---

code/game/objects/effects/decals/crayon.dm

Changes cost of crayon blood basin to be insight instead of sanity. 
Fixes up a few wrong statements in crayon code comments.

crayon basin anti spam

---

code/modules/flufftext/Dreaming.dm

This is basically just some additions to dream snippets. Dreams can get extremely bizarre if people are put into stressful environments. This PR aims to add more dream snippets, some regular some less regular. Few about intricate machines and others about machines of impossible complexity. Might add more later when creatively more inspired. Also finally adds cindarites to the list of possible species to dream about. Now you too can dream on how your cindarite is eating cheese in dorms.

Stranger dreams part 0.1

---

code/game/machinery/tesla_turret.dm

Massively nerf tesla turret 
Fixes tesla turret allowing you to have negitive power

tesla turret fix(?)

---

code/game/objects/effects/decals/crayon.dm
code/modules/paperwork/paper.dm

Tweaks some desc/intent and feedback in crayon magic
Tweaks the fountain in crayon magic to not have a flipped checked
Crayon magic more so uses crayons now

Paper Encurgement

---

code/modules/mob/say.dm

Change the me verb to be a message box rather than a small text input.
We are a HRP server afterall and write more than five 5 words. Being able to see what you write for pacing, grammar correction and structering is pretty huge.

Change the me verb to be a message box rather than a small text input

---

code/game/jobs/job/prospector.dm

<details>
<summary>
slightly buffs foreman stats to be more of a allrounder instead of just prospector+ salvager-
</summary>
<hr>
buffs foreman stats
<hr>
</details>
:cl:

Buffs foreman

---

code/game/objects/random/mob/greyson.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm

Data star now will spawn turrets around it rather then on it
Additional mobs will spawn when data star is being attacked
Added more punishment mechanics
Fixed Data star say lines not being in quotes

data_star buff and fixes

---

code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm

Data star no longer infi gathers armor
Data star buffed a little more on armor base

armor and message fixes

---

code/game/verbs/toggle_verbs.dm
sojourn-station.dme

Title.
If you struggle with client side performance, try using this. Verbs suck ass. T hey lag your game.
:cl:
add: Toggle-Verbs, a new verb that lets you toggle verb visibility. Should drastically improve clientside performance.
/:cl:

Adds a verb that lets you toggle verb visibility

---

code/__DEFINES/genetics.dm
code/modules/genetics/genetics.dm
code/modules/genetics/machinery/genetics_items.dm
code/modules/genetics/mutations/vampire.dm
code/modules/genetics/recipes/blood_based.dm
code/modules/mob/living/simple_animal/hostile/bat.dm
code/modules/mob/living/simple_animal/hostile/creature.dm
code/modules/organs/blood.dm
code/modules/reagents/reagents/core.dm
code/modules/reagents/reagents/food-Drinks.dm
sojourn-station.dme

New gene that is Genoferous Hematocryptosis Sickness
Better hint to get blood temple
Genoferous Hematocryptosis Sickness makes it so you can drink blood as food, makes food no longer count for hunger, regen blood faster and stablizes genes as it increases hunger draw.

regal sickness

---

code/game/objects/explosion.dm
code/game/objects/explosion_recursive.dm
code/modules/research/experiment.dm

The toxins beacon now checks for z level and reports the next power level target on radio.

z level check and QoL for toxins

---

code/game/objects/structures/flora/flora.dm

<details>
<summary>
</summary>
<hr>
A while back, I brought up to ben that the code for big bushes to be cut was kinda borked, but definitely intended. they said they would fix it, but it never happened, so I am doing it. A refactor is still probably needed in the near future to simplify the code down for rocks/bushes.<hr>
</details>
:cl:
fix: You can now cut down large bushes, as intended by god and nature.
/:cl:

spaghettifix big bushes to be cuttable.

---

code/modules/cooking_with_jane/cooking_items/cooking_containers.dm
code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
code/modules/mob/living/silicon/robot/gripper.dm
code/modules/mob/living/silicon/subsystems.dm

Converts fried chicken repice for jane cooking
Makes borgs be able to jane cooking
fixes hacked defender borgs not being able to use the china lake they get access to

fixes borg intractions and misc

---

code/modules/client/preference_setup/global/preferences.dm
code/modules/core_implant/cruciform/rituals/base.dm
code/modules/psionics/psion_powers/psion_starter_powers.dm

Ghosts now can toggle off psionic messages and the churchies sending message
Psionic messages is more vage i.e not only voice

psionic messages

---

code/__HELPERS/text.dm
code/__HELPERS/unsorted.dm

<details>
<summary>
</summary>
<hr>
Ports this I made https://github.com/Liberty-Landing/Liberty-Station-13/pull/54 to allow everyone to use actual numbers in names so vatties / synths and opifex can have a field day
<hr>
</details>
:cl:
code: Naming code to allow numbers
/:cl:

Name numbers

---

code/game/jobs/job/captain.dm
code/game/jobs/job/engineering.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/security.dm

Unlocks race restrictions on all LC roles for Aulvae at the request of CDB.

Squishy heads of staff

---

code/modules/cooking_with_jane/cooking_items/cooking_containers.dm
code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
code/modules/mob/living/silicon/robot/gripper.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/mob/living/silicon/subsystems.dm
code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm

Fixes borgs being unable to use their china lack gun

China Lake fix for borgs

---

code/modules/cooking_with_jane/cooking_appliances/grill.dm
code/modules/cooking_with_jane/cooking_appliances/oven.dm
code/modules/cooking_with_jane/cooking_appliances/stove.dm
code/modules/mob/living/silicon/robot/gripper.dm

cyborgs can now pick up spatulas
well janky and bad cyborgs serves gripper can now take item out/off cook machinery

More cyborg cooking fixes

---

code/datums/autolathe/gun_frames.dm
code/datums/autolathe/guns.dm
code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
code/modules/projectiles/guns/projectile/automatic/bulldog.dm
code/modules/projectiles/guns/projectile/automatic/duty.dm
code/modules/projectiles/guns/projectile/automatic/nordwind.dm
code/modules/projectiles/guns/projectile/automatic/pitbull.dm
code/modules/projectiles/guns/projectile/automatic/ppsh.dm
code/modules/projectiles/guns/projectile/pistol/ladon.dm
code/modules/projectiles/guns/projectile/revolver/breakaction.dm

<details>
<summary>
</summary>
<hr>
Adds frames and parts to - Bulldog/Pitbull, Duty/Watchtower got their own frame, Both Cowboy revolvers, Ladon can actually be deconned.
Gave the blackshield disk some of their weapon designs alongside frames which don't really match marshals (Like come on there is a singular Omni ((osprey)) that marshals get and even that's a unique)
Removed the lie of "Can only take drums" on PPSH weapons since infact they can all take sticks and drums
Fix Ladon being called Lamia for no real reason on design disks
<hr>
</details>
:cl:
add: Gunframes and parts to certain weapons
tweak: BS "Shall-not-be-infringed" disk
spellcheck: PPSH description lying to the player
fix: Ladon design being called Lamia for whatever reason on the disk
/:cl:

Le gun in my le colony

---

code/modules/hydroponics/grown.dm
code/modules/reagents/reagents/medicine.dm

Fruits now adpativly change their maximum volume depending on how much they produce.
Fix a flossisine pathing.

Fruit volume fix

---

code/modules/shield_generators/shield.dm

Fix shield geni not blocking air

---

code/game/objects/items/weapons/tools/mods/_upgrades.dm

Borgs now can with the help of a fleshy be upgraded
Borgs can not have their upgrades removed

Fixes humans being unable to upgrade borgs

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Removes prefab cameras that had wrong locations in them. Replaces down cameras thruout the fenceline that link up with colony proper. Tested with a bluespace tech on private.

Fixes the fence cameras

---

code/game/objects/random/mob/greyson.dm
code/game/objects/random/random.dm
code/modules/dungeons/crawler/areas.dm
maps/_DeepForest/map/_Greyson_Field_Office.dmm
maps/submaps/dungeon_rooms/rooms/commanderoffice.dmm
maps/submaps/dungeon_rooms/rooms/corner_energy_NE.dmm
maps/submaps/dungeon_rooms/rooms/corner_energy_NW.dmm
maps/submaps/dungeon_rooms/rooms/corner_energy_SE.dmm

reduces the amount of mobs at round start via having GP moon base only late spawn mobs when a *human mob* entures its 
Replace some bad spawns with proper spawners to not mess with spawning of spawns spawning spawns spawn
area Tested with teleporter teleport with an ERT to ensure it works

GP optimization

---

maps/__Nadezhda/data/shuttles-nadezhda.dm

Gives soteria access to the surface transport shuttle.

Sci shuttle Access

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Fixes the fenceline cameras again... someone saved over my map changes ;-;

Fixes fence prefabs

---

code/modules/core_implant/core_implant.dm

Church spells will now be able to send you into the negitive power values
Church spells will be able to cast when at max power of the cruciform type, I.e max power of 30 but a spell costs 50? -20 power after successfully casting.

K5 request

---

code/modules/client/preference_setup/general/02_body.dm
code/modules/client/preference_setup/preference_setup.dm
code/modules/client/preference_setup/preview.dm
code/modules/mob/living/carbon/human/update_icons.dm

This will definitely make char creation slower, but will definitely make the server faster. IT might also break things horribly.
<hr>
</details>
:cl:
code: Human rendering is now heavily CHECK_TICKed
/:cl:

Adds risky CHECK_TICKs to human rendering code

---

code/game/objects/items/devices/hardware_imprinter.dm

<details>
<summary>
</summary>
<hr>
Mechanically not an implant lore wise it is so no more psions with these.
<hr>
</details>
:cl:
balance: Psions can no longer use hardware imprinters
/:cl:

Imprinter psion check

---

code/game/machinery/kitchen/smartfridge.dm

"Catalouging" to cataloging
Fixes a typo on the disk storage. Thats it.
:cl:
spellcheck: Fixes a typo on disk storage
/:cl:

[Spellcheck] Spellchecks disk storage

---

code/modules/projectiles/gun.dm
code/modules/projectiles/guns/_projectile.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/energy/plasma/plasma.dm
code/modules/projectiles/guns/energy/projectile/railgun.dm
code/modules/projectiles/guns/energy/projectile/shrapnel.dm
code/modules/projectiles/guns/energy/projectile/slab.dm
code/modules/projectiles/guns/launcher/crossbow.dm
sojourn-station.dme

Gun intractions have been greatly streamlined
Borgs can now properly intract with many guns
Omni tools can now properly intract with guns
Adds framework for E-guns to be sawnable (byproduct of streamlining)
Moves shrapnel to its own file
Also fixes slab

Standardizes gun interactions

---

code/game/objects/items/weapons/tools/stunbatons.dm

Fixes a minor typo.
:cl:
fix: Fixes a typo.
/:cl:

[Spellcheck] Mini Stunbaton --> Defence to defense.

---

code/modules/clothing/spacesuits/rig/modules/utility.dm
code/modules/clothing/spacesuits/rig/rig_verbs.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/reagents/reagent_containers/glass/beaker.dm

Medical rigs "max" injections for speed-selection is raised to 5
Injector units for rigs can now be set to *any* value you wish when using a wrench on it itself
Added new button for verbs to quick select different injection levels
Beakers in rigs now have lables for easyer pop outs/menus
Allow beakers to be code-labled

Lables and tweaks

---

code/modules/clothing/spacesuits/void/excelsior.dm

Gives Excelsior armor psi blocking so they can't be spammed with naughty things.

Excelsior psi_block

---

code/game/machinery/vending.dm

Ewallets now properly gives the task and discounts

Fixes Ewallets tasks

---

code/modules/projectiles/gun.dm

<details>
<summary>
</summary>
<hr>
Gives proper feedback on unfolding/folding instead of having the messages reversed
<hr>
</details>
:cl:
fix: Unfolding/Folding stocks having swapped message
/:cl:

Folding typo fix

---

code/modules/reagents/reagents/food-Drinks.dm

1/10th of the efficiency of Hyronalin while still able to OD yourself on.
I cannot wait to see doctors injecting salt + hyronalin into people if this goes through.
:cl:
balance: Table salt is now a very mild radioprotectant.
/:cl:

[Balance] Table salt radiation intraction

---

code/modules/genetics/machinery/genetics_cloner.dm

Does what it says on the tin. Destroyed or deconstructed genetics vat control consoles will no longer create infinite duplicates.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

fix genetics console deconstruction

---

code/game/objects/items/weapons/tools/_tools.dm

Codes in a requested % change on tool repair by Trilby

tool repair change

---

code/game/jobs/job/silicon.dm
code/game/machinery/computer/ai_core.dm
code/modules/mob/living/silicon/ai/ai.dm
code/modules/mob/transform_procs.dm

Gives borgs an alt title called "Cyborg"
Having cyborg as a title will give your shell a MMI
Normal Robot titled players will have a posibrain
Ai cores can only take posibrains now
Ai players should now be a posi brain.
Tested with Trilby (Thanks to her for saving me days worth of learning job code)

Borg posibrains

---

code/game/objects/items/weapons/shields.dm

Fixes some pathing issue on excel shields.
Adds in the ability for shields to force a enemy to target them by SHIELD BASHING them.
Oh no this helpless bluespace tech!
I HAVE SAVED HIM!

Shield SMASHING targets

---

code/datums/setup_option/core_implants.dm

Allows all low councilors other than VBO and CRO to be faithful and select the cruciform. Hallelujah.
This PR may be fucked up as.im testing if I can make PRs.on mobile.

[lore] Cruciforms for Councilors

---

code/modules/clothing/head/jobs.dm

<details>
<summary>
Gives the preacher hat 100 bio protection.
</summary>
<hr>
<hr>
</details>
:cl:dutop
tweak: Give preacher hat bio protection
/:cl:

Give preacher hat bioprotection

---

code/modules/biomatter_manipulation/bioreactor/bioreactor.dm

<details>
<summary>
Make bioreactor goo anchored to the ground or something
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Make bioreactor goo anchored to the ground

---

code/datums/perks/job.dm

Related to https://discord.com/channels/859887473940889640/1237535140129931385/1237535140129931385

Perk pathing fix for prospector and blackshield conditioning

---

code/modules/clothing/spacesuits/rig/modules/utility.dm
code/modules/clothing/spacesuits/rig/suits/combat.dm
code/modules/clothing/spacesuits/rig/suits/light.dm
code/modules/clothing/spacesuits/rig/suits/merc.dm
code/modules/clothing/spacesuits/rig/suits/station.dm
code/modules/stashes/stash_types/ninja.dm

Printing and buying rig modular chemical units no longer will have them come pre-filled
Random rng lose rig modular chemical units will no longer come pre-filled eather

less chemicals around (rigs)

---

code/game/objects/items/devices/organ_module/passive/armor.dm
code/game/objects/items/devices/scanners/health.dm
code/modules/mob/living/carbon/human/species/species.dm
code/modules/organs/blood.dm
sojourn-station.dme

Blood now properly generates above 560 units, making blood genes and GYM buffs work as intended.
Health scanners now display if someone has a buff to their blood volume
Subdermal armor now properly applies its damage modifier.
Subdermal armor now affects the whole body and only works when implanted inside the chest.
Changed subdermals armor modifier to be multpilicative, second PR follows shortly reworking every other modifier.

Fix blood volume adjustments and subdermal armor

---

code/modules/reagents/reagents/toxins.dm

Turns out that the pathing of Polyacid is broken too. I had it fixed on local a month back but for some alien reason I didn't push it.
Fixes pathing on polyacid making it work now.
:cl:
fix: Fixes polyacid pathing
/:cl:

[Hotfix] Polyacid Pathing issue

---

code/controllers/subsystems/trade.dm
code/modules/modular_computers/file_system/programs/generic/trade.dm

Cargo's Export mass sell now properly now should care about anchored if it wasnt before
Cargo's Export now if someone personally accualt uses it will give the normal cut to LSS
Cargo Export now should allow **wrapped** items and crates with nested items inside

cargo export tweaks

---

code/_onclick/hud/screen_objects/base_screen_objects.dm

NSA UI now respects modified thresholds like buffs and debuffs to it

NSA icon is now percentage based

---

code/datums/wires/wires.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

When seeing wires you needed 41 mech skill, rather then 40. That is a misstake
Gives drones more mech as well
closes #5333

fixes wire exsam for drones (and everyone)

---

code/modules/reagents/reagent_containers/hypospray.dm

closes #4716
Corrects the placement of the hyposprays delay timer as to no longer have it endlessly stack if it dosnt complete its injection or injects people in suits

Fixes hypospray delay stacking

---

code/modules/mob/living/carbon/superior_animal/drone/types/roomba.dm

<details>
<summary>
Make roomba un-buckle-able. 
the buckle feature dosnt work at all
and leads to issues
closes #5284
Requested by Trilby.        
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Make roomba un-buckle-able

---

code/modules/cooking_with_jane/step_types/add_produce.dm

- fixed bug preventing gmo plants from being used in CWJ recipes
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

gmo plants are good for you

---

code/game/objects/structures/crates_lockers/closets/secure/engineering.dm

<details>
<summary>
So, only the GM starts with tape to secure an area for repairs, this PR fixes that
</summary>
<hr>
<hr>
</details>
:cl:
add: /obj/item/taperoll/engineering to Adept's lockers
/:cl:

Oversight on Guild Adept's locker

---

code/modules/hivemind/mobs.dm

Mechivers no longer eat mechs and Qdel the user inside

mechivers no longer eat mechs

---

code/modules/mob/living/carbon/human/life.dm

Contaminated items now respect bio armor and only ignore it when a clothing item is worn.

[balance] Contaminiated items respect bio_armor now

---

code/modules/projectiles/guns/energy/misc/slimegun.dm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

changes that where done to xenobio and the rancher gun from #5345
Rancher went from 100 per shot to 20
slime compresser is now roundstart aviable

TEFs changes to xenobio/slimegun

---

code/modules/modular_computers/computers/subtypes/dev_tablet.dm
code/modules/modular_computers/computers/subtypes/preset_laptop.dm
code/modules/modular_computers/computers/subtypes/preset_pda.dm
code/modules/nanogate/nanogate_vm.dm

forgot to update these to work
:cl:
fix: Fixed some tablets and laptops having the wrong icons
/:cl:

Fix Computer Subtype Sprites being wrong

---

code/game/objects/items/devices/defib.dm
code/game/objects/items/weapons/handcuffs.dm
code/modules/mob/living/silicon/ai/ai.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

More QOL nothing massive. Don't think there should be much debate as to why.
Changelog: 
Adds 2 more beakers to the medical borg for a total of 4.
Makes the medical borg defib a SI advanced defib.
Adds a large syringe to the medical borg replacing their old one.
Adds a mini welder to the janitor borg as all other modules get one.
Adds the sec borgs holowarrent projector back now that it has print functionality it can be used correctly.
Tweaks the desc on sec borg handcuffs to convey that they can collect used handcuffs with it.
Disables speaking Jive for AI for obvious reasons.

More QOL for borgs and minor AI bugfix

---

code/modules/biomatter_manipulation/bioreactor/platform.dm

Forces the materal shoot to round materals, if its rounded down to 0, it hardsets to 0

Church biomatter rounding

---

code/modules/mob/new_player/new_player.dm

I can't replicate this locally and I'm out of ideas, so this just smears log_debug all over this area of code in the hopes that it'll catch something going wrong?
:cl:
code: Added debug logs to new spawning code to try and nail down a problem
/:cl:

Add a bunch of log_debugs to the new spawning code to try and nail down a problem

---

code/modules/mob/new_player/new_player.dm

Reverts sojourn-13/sojourn-station#5408
Got a clean snapshot of the problem and these logs revealed... that everything here is working as intended, the problem is somewhere in equipping code.

Revert "Add a bunch of log_debugs to the new spawning code to try and nail down a problem"

---

code/modules/projectiles/guns/projectile/shotgun/hunter_crossbow.dm

People with the MASTER_BUTCHER Perk (The Lodge) now automatically pump the bolt lance when shooting.

Bolt Lance Quickpump

---

code/game/mecha/mecha.dm

as described
:cl:
fix: mechs can compact and load scrap again
/:cl:

Let mechs compact scrap again

---

code/modules/surgery/surgery.dm

Requested by Chef_Doggo
Reduces difficulty_adjust to be 1/3rd of what they are. The numbers used before hand where set a little (lot) to high.
------------------
Fixes masks always being allowed

Armor surgery difficulty tweaks

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Copy and pastes a couple other of my pull requests totalling it together, since i am a big dumb and cant use github properly

fixing map troubles (copypasting)

---

code/modules/goonchat/browserassets/css/browserOutput.css
code/modules/goonchat/browserassets/css/browserOutput_override.css
code/modules/goonchat/browserassets/css/browserOutput_white.css

Changes Deadsay hexcode values to make the coloration less difficult to read for dark mode users. Has a theme as per coder cat's suggestion. Shout out to Shadow and Randall for the help finding the right file and letting me know about the browserOutput-override.css thing.
<hr>
Changed browserOutput.css deadsay from #e2c1ff to #e79e00
Changed browserOutput-override.css from #530FAD to no value, disabling the override for deadsay.
Changed browserOutput-white.css from #5c00e6 to #3f4041
Tested on local, works, doesn't break anything.
<hr>
</details>
:cl:
code: Changed hex values for deadsay, making dark mode users not destroy their eyesight further.
/:cl:

Deadsay chat color fixes

---

code/modules/mob/living/living.dm

Your to hurt too dive.
This fixes a couple typos for the diving mechanic. They are not as memy as the "supper majority" we have which is great and not at weird as the "Your [REDACTED] finally feel full, again." from cit
:cl:
spellcheck: Fixes a bunch of typos on diving
/:cl:

[Spellcheck] Fixes various typos and grammar on diving messages

---

code/modules/aberrants/organs/machinery/organ_fabricator.dm
code/modules/power/hydrogen_generator.dm
code/modules/projectiles/gun.dm
code/modules/reagents/machinery/chem_dispenser.dm

Fixes being able to accidently decon guns if you were trying to remove mods from them
Fixes chem dispender being only hackable via a multy tool directly
Fixes organ fabricator omni tool bricking intraction
Fixes hydrogen generator not being able to be omni tooled

fixes some omni tool intractions

---

code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm

Data star now is to big to be crate stuffed (Sorry cheaters)
Data star now gets finally debug logs on fallen robotic enemies around
After around 13 debug logs data star will summen new bots around them
Data star now self repairs a small bit based on debug logs
Data star has no longer been made with painrespectors making it closer to perfection

Data star collectors addition

---

code/modules/aberrants/_modification.dm

When using aberrant system on robotic lims it now uses your cog stat rather then bio stat

robotic aberrants

---

code/game/objects/structures/flora/flora_tree.dm
code/modules/hydroponics/beekeeping/beehive.dm

Tree spider infection now is rather wasps
Infected trees now have 2-3 wasps with 1-2 honeycomb
New honeycomb frame type that is frameless

swaps tree spiders with wasps

---

maps/_DeepForest/map/_Deep_Forest.dmm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

(The first change as of now, will continue posting in comments)
Giving Soteria more content and some redesigning to areas to make them feel more comfortable.

Soteria+ Cosmetic Upgrade (Not limited)

---

code/modules/clothing/head/misc.dm
code/modules/clothing/suits/miscellaneous.dm

Gives the HEV suit cold protection and unacidable (for good measure). Should cover every environmental hazard other then space now.

missed a few HEV things. Woops!

---

code/game/objects/effects/mines.dm
code/game/objects/items/weapons/storage/hardcases.dm
code/game/objects/items/weapons/traps.dm
code/modules/hydroponics/beekeeping/beehive.dm
code/modules/scrap/scrap_pileripper.dm

Fixes:
Beehives spam clicking
old mines have been touched up and now allows any mob to trigger them
hardcases scuffness has been reduced hopefully
Pile Ripper exploits and bad intractions
Fixes bear traps trapping large mobs + feedback not being hidden properly
Also fixes beartraps posting chat with fail logs twice

untested fixes to misc things

---

code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm

Shout out to blue zippo for funding the ego resources for this
Limbus jokes side
The emperor and thus reaper spider now have a "dash though attack" that hits the player 3 times at 20% damage (so every 3rd attack is inaffect 300% toxins, 160% damage)
Choas level 2 means this attack is every other
If the target is not accually vailded (i.e standing gainst a wall) the attack will not happen, but it will still use the resources to do so

Wingbat HE Ego

---

code/game/objects/structures/crates_lockers/closets/secure/medical.dm
code/modules/clothing/spacesuits/rig/suits/station.dm

<details>
<summary>
Fixes the rigsuit to be airtight, hide hair, and protect in hazardous pressures and temps
</summary>
<hr>
<hr>
</details>
:cl:
CHANGE: Makes CBO rigsuit airtight, hide hair, and protect in hazard/temperatures
:cl:

CBO rigsuit fix

---

code/datums/autolathe/clothing.dm
code/modules/clothing/head/helmet.dm

fixes ballistic mask item requirements.

fixes ballistic mask

---

code/controllers/subsystems/trade.dm

Fixes sending crates not properly deleteing the crate

package issue

---

code/modules/projectiles/projectile.dm

Maybe tasers now will log things

more robust logging

---

code/datums/perks/racial.dm
code/datums/setup_option/backgrounds/origin_opifex.dm
code/game/machinery/adv_med.dm
code/game/objects/items/devices/organ_module/_module.dm
code/game/objects/items/devices/organ_module/active/pouch.dm
code/game/objects/items/devices/organ_module/passive/muscle.dm
code/game/objects/items/weapons/storage/belt.dm
code/game/objects/items/weapons/storage/firstaid.dm

Oppifex smuggler pouch is now even more hidden
Adds framework to completely hide implants
Makes the organic musles for legs no longer count as robotic
Condences down and gives more pills to opifex medical backround
Opifex medical backround now gets SI bandaids, oitment, a surgery kit, some sleeping toxins and some splints
Buffs the medical opifex backround to have 5 more bio

opfiex buffs

---

code/datums/outfits/jobs/medical.dm

<details>
Fixes #5532. I think, lol. If you wanted the armor just get shot or something.
<summary>
Fixes #5532 by replacing armor vest with labcoat .
</summary>
<hr>
<hr>
</details>
1 line of code is changed to allow this goal to happen
:cl:
/:cl:

med students now spawn with labcoats & not armored vests

---

code/game/turfs/flooring/flooring.dm

<details>
<summary>
Fixes some error in tripping on flooring, I guess. Dictated by Trilby
</summary>
<hr>
<hr>
</details>
:cl:
fix: Error with tripping in flooring.
/:cl:

Something about tripping

---

modular_sojourn/task_master/human_helper.dm

removes some debug things

---

code/game/turfs/simulated/wall_icon.dm

This is just kinda suss and maybe it's causing our server problems?
:cl:
fix: Maybe fix server shutdown?
/:cl:

Switch all_wall_states to be less sus and initialize lazily

---

interface/skin.dmf

Somehow this didn't make it into #5544 
:cl:
fix: status bar overlapping
/:cl:

Emergency Fix: Actually apply the skin.dmf changes

---

code/game/machinery/autolathe/autolathe.dm
code/modules/mining/mine_point_vendor.dm
code/modules/mining/mine_turfs.dm

Readds Aether drones for 1200 mining points
Makes it so autolathens cant smell raw ore

mining less affect + less cheesy ore smelting

---

code/game/jobs/job/science.dm

<details>
<summary>
</summary>
<hr>
"Learnie" isn't a word. "Learner" is, but isn't the verbiage that gets used in the workplace. "Student", a word meaning the same thing, is in much more common usage. 
It's not immediately clear just from the title that "Lab Assistants" work in the robotics lab, so I clarified that.
<hr>
</details>
:cl:
/:cl:

fixes weird verbiage in new soteria alt titles

---

code/modules/mob/living/carbon/superior_animal/defense.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/scrap/scrap_pileripper.dm

Pile ripper no longer endlessly harvests from simple mobs
Pile ripper now properly gibs simple mobs
Pile ripper now when gibbing non-humans gives proper resources
It is now techinally possible to automate harvesting of simple mobs

Gibber fixs

---

code/modules/mob/living/carbon/human/life.dm

Closes #5548
Fixes plasma contamination giving 300+ plasma

Fixes endless plasma

---

code/game/machinery/autolathe/matterforge.dm
code/game/objects/items/weapons/tools/mods/_upgrades.dm

Nanoforge now should no longer allow intractions with untrainned plebs
Nanoforge should now be a bit better at getting its design list when showing the UI to people
Fixes AP mult not properly displaying its affects
closes #5483
closes #5525

Nanoforgestuff + toolmod fix

---

code/game/turfs/simulated/wall_types.dm
maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Was messing around and HOH figured out you can make cloth walls. perfect for are psych ward! I was crazy once.....
Changelog:
Adds cloth walls to the psych ward rooms

Cloth psych ward walls

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Adds BRAIN GYM equipment to Soteria's lower break room Adds Disposal bin to Soteria's lower break room
Moves a camera and a decal
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Soteria Gets A Game Room

---

code/modules/clothing/head/helmet.dm
code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm

Altyn no longer has crazy armor
Excelsior shield guy no longer has nearly infinite armor
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

more fixes

---

code/modules/clothing/head/helmet.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Fixes armor values for the ballistic mask

---

code/modules/clothing/spacesuits/rig/rig.dm
code/modules/clothing/spacesuits/rig/rig_pieces.dm

Rigs armor now should no longer imporperly lose all its armor stats

Fixes rig armor maybe

---

code/modules/reagents/machinery/alchemy.dm
code/modules/reagents/recipes/alchemy.dm

Trillby told me to when debugging something to do with the alchemy code
<details>
Trillby found something when debugging the code for alembic phials and as such told me to flip the two lines
<summary>
trillby found it
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
From trilby
Fixes Alchemy thing no longer being wrong layered (huzza)
Fixes (maybe) work tonic repice
Fixes alchemy reaction being a bad order

Fixes for Alchemy

---

code/modules/scrap/scrap_pileripper.dm

Make a fixes pile ripper to to allow it to harvest more then one body

Returns to pile ripper

---

code/modules/projectiles/guns/mods/mods.dm
code/modules/projectiles/guns/projectile/revolver/hornet.dm
code/modules/projectiles/projectile.dm

Proj pain mult now properly increase halloss damage bullets do
Painmaker and hornet now flat add 20 halloss damage to bullets they shoot
Painmaker and hornet have been rebalanced to adjust for this change

Painmaker fixers

---

code/modules/mob/say.dm

based?
Subtle (not antighost) is like a small emote thats kinda like a whisper that works in a small area. Useful for hostages and sneaky cases of antagery!

Return of Sudtle (Not antighost)

---

code/modules/mob/living/simple_animal/hostile/big.dm
code/modules/mob/living/simple_animal/hostile/creature.dm
maps/_DeepForest/map/_Deep_Forest.dmm
maps/__Nadezhda/area/_Nadezhda_areas.dm

New ruin west of Greyson, essentially an abandoned warehouse/transport hub + some additional areas. Pretty difficult with some decent rewards this time! Also added a bit better rewards and a rolling pin to the Lima-09 (Coldlabs) ruin

New forest ruin!

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

Puts #5597 into this pr
Replaces like 99% of maints and some ruins tiles to the new ruin-y looking ones to better have them flow in
fixes a wall news caster

Defib + better floors

---

code/modules/clothing/suits/armor.dm

Lowers the chemical breacher vests by a few points

lowers some armor values

---

code/game/objects/structures/flora/flora_tree.dm

Fixes tree stumps not spawning anchored

Fixes tree stumps not spawning anchored

---

code/game/machinery/vendor/tool_vendors.dm
code/modules/materials/material_sheets.dm

Fixes pathing of the vender materials

fixes some pathing

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
</summary>
<hr>
Adds an abandoned wrestling ring in the west maintenance, right in front of the library and over the maintenance bar.
Replacing the little place with trash piled that was grilled away, I've thought that we could shove a place there for appeasing the folks that may want to do some grabbing PvP.
This being my first PR, if you have tips what I can change or how to make changes properly I'll take ALL of these.
<hr>
</details>
:cl:
add: Added the wrestling ring
del: Removed the trash pocket place (?)
/:cl:

Wrestling ring in the west maintenance

---

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm

<details>
<summary>
</summary>
<hr>
Moved some stuff around the kitchen for ease of access, added two shelves, put an extra mop and bucket for cleaning floors under furniture.
<hr>
</details>
:cl:
add: Added a bucket, a mop and two shelves to the kitchen.
tweak: Pushed some things around to make the kitchen more accessible.
/:cl:

Small kitchen changes

---

code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/slime/life.dm
code/modules/mob/living/carbon/superior_animal/defense.dm
code/modules/mob/living/carbon/superior_animal/life.dm

Removes some unused code checks for mobs that dont need them
Adjusts some code to return early or ask less questions that dont need to
Sleeping now heals 5 sanity per sleep tick
Ups sleeping verb timer from 20 sleep to 60 sleep

sleeping buff + some small optimizations

---

code/modules/projectiles/projectile.dm

Drop off rather then 1 AD is now 0.01 AD per step (Or just about that)

Drop off maths tweaks

---

code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/mob/living/carbon/human/human_defense.dm

Fixes a small bug with regal suit after a rework

fixes to regal suit

---

code/controllers/subsystems/jobs.dm
code/datums/mob_stats.dm
code/modules/client/preference_setup/general/07_stats.dm

Requested by Chef-Doggo
Allows you to set your stat cap to a value between -30 to 150
Lowering stat cap does not give you any benefit other then the stat being at a lower value

Opt in lower stat caps

---

code/datums/perks/special.dm
code/game/machinery/autolathe/matterforge.dm

Fixes both perks that increases stat caps
Maybe fixies a matter forge issue, but also reduces its prices by 50%

Fixes skill perks cap things

---

code/modules/reagents/reagents/medicine.dm
code/modules/reagents/recipes/recipes.dm

Adds two need relatively easy to craft chemicals for medical 
Somnadine - heals brute damage at: 1.5 x effect_multiplier - to every race *only well the person is asleep* and only on touch
dermahypnodol -  heals brun damage at: 1.5 x effect_multiplier - to every race *only well the person is asleep* and only on touch
Names helped by Tenno

chemicals for sleeping folks

---

code/game/objects/effects/overlays.dm
code/modules/mob/living/carbon/superior_animal/ai.dm
code/modules/mob/living/carbon/superior_animal/attack.dm
code/modules/mob/living/carbon/superior_animal/roach/roach_spits.dm
code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/superior_defines.dm

Adds framework for move n attacking
Fixes kaiser spit tracker line making goop
Allows kaiser to move and attack its target
Removes kaisers spare reloads for its spit attack, it was not meant to have spare ammo just 2 shots per target

Kaiser fixes and betterment

---

code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm

fixes kaizer well dead attacking when dragged

kaiser dead attack fix

---

code/modules/projectiles/projectile/bullettypes.dm
code/modules/projectiles/projectile/energy.dm
code/modules/projectiles/projectile/plasma.dm
code/modules/projectiles/projectile/special.dm

<details>
<summary>
Fixes Electrode and a few lesser modes not actually doing any damage due to a spelling error
</summary>
<hr>
Halloss is pain damage and hallos doesn't exist. Guess which one these were using?	
<hr>
</details>
:cl:
fix: Certain nonfunctional tasers will now actually tase
/:cl:

Fixes certain tasers not tasing

---

code/game/objects/items/weapons/implant/implants/chemical.dm
code/modules/research/designs/prosthesis_implants.dm
code/modules/research/nodes/biotech.dm

Fixes an exploit with chemical implants using default death gasp emote
Gives rnd tracking and implant pad
Chemical implant now properly on death triggers

exploit fix + rnd additions

---

code/modules/projectiles/projectile/beams.dm
code/modules/projectiles/projectile/bullets.dm
code/modules/projectiles/projectile/bullettypes.dm
code/modules/projectiles/projectile/fragment.dm
code/modules/projectiles/projectile/projectilegrenades.dm
code/modules/projectiles/projectile/special.dm

Fixes many cases of trajectory line warning shots activating the affects of the shot

bullet fixes

---

code/modules/clothing/head/helmet.dm
code/modules/clothing/spacesuits/rig/rig.dm

Nerfs riot helmet from being the best all around face shield
Fixes alytst helmet stats
Fixes (maybe) rig suits randomly losing their presser proofing

rig and helmt stuff

---

maps/_DeepForest/map/_Deep_Forest.dmm

removes the tesla gun and replaces it with a tesla shotgun in a ruin
tesla gun has never been balanced nor corrected for new armor/gun systems

removes a bad debug gun

---

code/modules/sanity/sanity_mob.dm
modular_sojourn/spaceleak.dm

Bluespace leaks now reduces a bit of inspiration rather then forcefully gives breakdowns

leaks no longer break down

---

code/modules/mob/living/carbon/superior_animal/attack.dm
code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/reaver.dm
code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
code/modules/projectiles/ammunition/bullets.dm
code/modules/projectiles/projectile/beams.dm
sojourn-station.dme

Voidwolf captains now will never friendly fire. 
Voidwolf captains now will move and melee making them much harder kite them
Reavers now have their own file
c20r reavers on reload will change ammo type to match the targets bullet armor i.e bullet proof armor will get HV loaded, unarmored will get HP
Reavers with shields now will block a single melee hit after moving always
Reavers other then c20r will now never friendly fire, c20r still can

reavers will no longer be as mocked

---

code/modules/mob/living/carbon/superior_animal/defense.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/projectile.dm

Armor for mobs now matters and is used
Hitting stuff that has little to no armor no longer tells you that their armor that is not existent is doing anything
Fixes guns giving every bullet a phatom +1 AD
Fixes gun mult not properly working

armor fixes + gun penetration fix

---

code/datums/perks/job.dm
code/modules/sanity/sanity_mob.dm

Insight gaining from sanity tanking now has a cap
Insight gaining now has a pitty net of 0.5
Artists have a cap of insight gaining that is 5x better then normal folks
Artists also gain more insight mult then before by 0.5

Insight womp

---

code/modules/psionics/ear.dm

fixes a issue with EAR pillar checks

fixes ear slotting in pillar 3

---

code/game/objects/items/devices/organ_module/passive/food.dm
code/game/objects/items/devices/organ_module/passive/nsa.dm
code/game/objects/items/devices/organ_module/passive/sanity.dm
code/modules/mob/living/silicon/robot/robot_items.dm

Fixes typos on most silicon omnitool and new cybernetics.
<details>
<summary>
Fixes the typos on the majority of silicon omnitools (Medical, Security/Defense, Engineering, Custodial, Basic, and Science). Also adds a little more flavor to the recently added implants (SMH, NSA Banker, SNACK System, Cortex Support Cyberware) by changing the description, making their function and purpose a little easier to understand upon examination.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: S.N.A.C.K System description better laying out what it does.
tweak: NSA Banker renamed to NSA Banker implant with a new description to give it some more flavour.
tweak: S.M.H Enhancer renamed to S.M.H Module with a new description.
tweak: Cortex Support Cyberware renamed to Cortex Support Implant with a new …

minor Robotics Typo fixes

---

code/controllers/subsystems/trade.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
code/modules/modular_computers/file_system/programs/generic/trade.dm
code/modules/trade/datums/_trade_station.dm
nano/templates/trade.tmpl

Regives SOM their cargo disk
Removes SOMs firesuit
Gives SOM locker a munchkin so that they have tools like cargo techs
Deconstructing a locker now needs to be on any other intent but help
Adds a blanket "Dont mass complete" option to stations that folks can toggle

SOM and cargo "qol"

---

code/modules/reagents/reagents/drugs.dm
code/modules/reagents/reagents/medicine.dm
code/modules/reagents/reagents/toxins.dm

<details>
<summary>
Update descriptions of meds. Taking information from wiki.
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Update descriptions of meds

---

modular_sojourn/brewing.dm
modular_sojourn/brewing_datums.dm

Allows the brewing of fernet
Church exclusive brewing of holywater and then church wine

more brewing

---

code/game/jobs/job/avisitor.dm
code/game/jobs/job/blackshield.dm
code/game/jobs/job/captain.dm
code/game/jobs/job/church.dm
code/game/jobs/job/civilian.dm
code/game/jobs/job/engineering.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/medical.dm
code/game/jobs/job/offcolony.dm
code/game/jobs/job/prospector.dm
code/game/jobs/job/security.dm

Adds new Job titles for:
Corpsman - Field Medic
Marshal officer - Marshal Patrolman, Marshal Enforcer
MD - Chemist added and line about there being a different chemist for the department removed
ELT - Soteria Biolab Enforcer and Emergency Recovery Specialist

New job titles, fixing spelling errors and rephrasing some descriptions

---

code/_onclick/hud/plane_master.dm
modular_sojourn/client_colour.dm
sojourn-station.dme

Ports over many TG colour filters for client side view
Allows players to select pre-defined colour filters to their likings

Opt in colour filters

---

maps/__Nadezhda/map/_Nadezhda_Colony.dmm

Reverts #5514 ' Guild proity and smelter givens
Reverts cargo having a refiner
Gives back the refiner to the guild

dispolies cargo

---

code/game/objects/items/oddities_faction.dm
code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipe_burger.dm
code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
code/modules/cooking_with_jane/step_types/add_produce.dm
code/modules/hydroponics/seed_datums.dm
code/modules/hydroponics/seed_packets.dm
code/modules/hydroponics/trays/tray.dm
code/modules/mob/living/carbon/superior_animal/lodge/types/cerberus.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/reagents/reagent_containers/food/drinks.dm
code/modules/reagents/reagent_containers/food/drinks/bottle.dm
code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
code/modules/reagents/reagent_containers/food/snacks.dm
code/modules/reagents/reagent_containers/food/snacks/bread_loafs.dm
code/modules/reagents/reagent_containers/food/snacks/burger.dm
code/modules/reagents/reagent_containers/food/snacks/cakes_pies.dm
code/modules/reagents/reagent_containers/food/snacks/donut.dm
code/modules/reagents/reagent_containers/food/snacks/meat.dm
code/modules/reagents/reagent_containers/food/snacks/pizza.dm
code/modules/reagents/reagent_containers/food/snacks/sandwich.dm
code/modules/reagents/reagent_containers/food/snacks/soup.dm
code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
sojourn-station.dme

Goes through every food item, every drink bottle and fixes the desc to not be bay/tg/agressive or tell you what you think/feel/how to act
Fixes beet soup CWJ code error
Fixes mushrooms for CWJ 
Converts a few more dishes to CWJ

Recipe coverts + fixes + makeover of food and drink

---

code/modules/genetics/machinery/advanced_grinder.dm
code/modules/genetics/machinery/genetics_analyzer.dm
code/modules/genetics/machinery/genetics_cloner.dm
code/modules/genetics/machinery/genetics_designs.dm
code/modules/genetics/machinery/genetics_items.dm
maps/Centcom/map/centcom.dmm
nano/templates/clone_console.tmpl
nano/templates/genetic_analyzer.tmpl

Removes a direct refence to a player that is a bit overbearing.

Removes character direct refences

---

code/game/objects/items/weapons/shields.dm

<details>
<summary>
</summary>
<hr>
Changes the rigsuit shield module so it isn't as flimsy. It's way heavier than other shields and requires you to stand still as it slowly deploys, so it's health would be increased.
<hr>
</details>
:cl:
balance: doubled the health of the hardsuit shield
/:cl:

Rigsuit shield module health buff

---

code/game/machinery/vendor/food_vendors.dm

<details>
<summary>
Per request. `/carafe` pitchers should be able to hold liquid as they're `reagent_container` subtype
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Add glass pitchers to dinnerware vendors.
tweak: Vendors have 10 forks and knives
/:cl:

Add glass pitchers to dinnerware vendors

---

code/game/gamemodes/storyteller.dm

<details>
<summary>
Removes the requirement for guild members for certain gamemodes. Unlike Eris, we don't run out of oxygen that easily.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Removes roundstart guild requirement.
/:cl:

Removes guild requirement

---

code/game/jobs/job/guild.dm
code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm
code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm

Adds a new Title to Lonestar Miner - Lonestar Excavation Specialist
Fixes a plethora of grammar and spelling errors across Trade Stations and rephrases some headers and offers for better understanding and proper english.

Lonestar grammar fixes and additions

---

maps/__Nadezhda/map/_Nadezhda_Colony.dmm

Blackshield now has 7 beds and lockers as well as small bathroom/shower area
Also gives blakshield area a console

exspands blackshield dorms and gives back the shower area

---

code/__DEFINES/genetics.dm
code/_onclick/hud/screen_objects/base_screen_objects.dm
code/game/machinery/doors/airlock.dm
code/game/machinery/suit_storage_unit.dm
code/game/objects/items/weapons/material/shards.dm
code/game/objects/structures/morgue.dm
code/modules/genetics/mutations/painless.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/human_damage.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/human_organs.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/human/unarmed_attack.dm
code/modules/mob/living/carbon/shock.dm
code/modules/mob/living/carbon/slime/powers.dm
code/modules/mob/mob.dm
code/modules/organs/external/damage.dm
code/modules/organs/internal/_internal.dm
code/modules/organs/organ.dm
code/modules/organs/pain.dm
code/modules/reagents/reagents/food-Drinks.dm
code/modules/reagents/reagents/toxins.dm
code/modules/scrap/scrap.dm

No pain gene from genetics now properly gives its affects to the character rather then to the race
No pain gene no longer randomly resets when a new player joins the round

No pain gene fix

---

code/__HELPERS/global_lists.dm
code/modules/cooking_with_jane/recipes/cubes.dm
code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipe_donuts.dm
code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
code/modules/cooking_with_jane/step_types/add_produce.dm
code/modules/hydroponics/grown_predefined.dm
code/modules/hydroponics/seed_datums.dm
code/modules/hydroponics/seed_packets.dm
modular_sojourn/brewing_datums.dm
sojourn-station.dme

Moves over all roach cubes into CWJ
Fixes poppy tea and beet soup maybe
Converts a few more recipies to CWJ

more CWJ recipes and fixes

---

code/modules/projectiles/guns/projectile/pistol/ladon.dm
code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm

Fixes ladon deconstructing
Fixes artwork revolvers being able to be taken apart
closes #5694

art + ladon fixes

---

code/modules/genetics/machinery/advanced_grinder.dm
code/modules/genetics/machinery/genetics_analyzer.dm
code/modules/genetics/machinery/genetics_cloner.dm
code/modules/genetics/machinery/genetics_items.dm
maps/Centcom/map/centcom.dmm

-Does The removal of Belvoix's name from things properly.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Correctly removing Belvoix from things

---

code/game/jobs/job/church.dm
code/modules/clothing/head/helmet.dm

Fixes Rosaria helmet since it was never updated, stats now in line with body armor. Adds two more church slots putting them in line with other faction slots.

Church changes

---

code/datums/topic/admin.dm

<details>
<summary>
Would be good to clean up adminfaxes in earnest and make them prettier. Maybe allow for pre-set formats, too. Can do later if asked to do. Till then, adminfaxes now allow for BBcode.
</summary>
<hr>
<hr>
</details>
:cl:
admin: adminfaxes now support bbcode formatting
/:cl:

Parse bbcode for admin fax

---

maps/__Nadezhda/map/_Nadezhda_Colony.dmm

What this PR does is adds crosses / turrest to chiken nest by the church
:cl:
add: absolutist crosses to chicken nest
/:cl:

Micro Map Addition: Chikens Crosses

---

code/game/machinery/autolathe/artist_bench.dm
code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm

Arts bench now cares about TGH stat once more
Artsts can make powerful low ammo 12mm revolvers, weighted by tgh stat to produce

allows artist to make 12mm revolvers

---

code/modules/client/preference_setup/loadout/lists/fluff.dm

Prehaps maybe fixes chefs ckey in fluff items to allow them to take it

Fixes fluff item ckey check

---

code/modules/reagents/reagent_containers/food/drinks.dm
maps/__Nadezhda/map/_Nadezhda_Colony.dmm

<details>
<summary>
</summary>
<hr>
Provides wine and whiskey instead of random booze, and adds filled cerebrix/tea mix in psych office.
<hr>
</details>
:cl:
add: Added new teapot, containing cerebrix and tea, to psych office
del: removed random booze spawn
tweak: rep;aced random booze with wine and whiskey
/:cl:

MINOR Psych QOL Map Changes

---

code/modules/clothing/head/helmet.dm

<details>
<summary>
Helmet that is meant to be paired with the bulletproof armour and can only be acquired via special issue for Marshals or in maintenance spawns. Should probably be marginally good enough in the bulletproof department. Nerfed the bomb resistance as a change.
</summary>
<hr>
<hr>
</details>
:cl:
balance: Altyn rebalanced. More melee/bullet armour, less bomb armour
/:cl:

Altyn Rebalance

---

code/modules/mob/language/outsider.dm

<details>
<summary>
Change Crinos from ,s to ,5. Conflicted with Jive
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Crinos is now ,5 instead of ,s
/:cl:

Change Crinos to ,5

---

code/datums/setup_option/backgrounds/origin_marqua.dm

Corrects marqua backgrounds descriptions and tweaks some values to be more inpactful

marqua backround tweaks

---

code/game/machinery/excelsior/blackshield_teleporter.dm

<details>
<summary>
750 power for a 0.1 decrease in recoil, and a 0.1 increase in damage multiplier + slick looks and a downgrade to only 2 modslots is a bit ludicrous when you can mod up a regular STS from the teleporter to be way better for only 400 power
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Decrease PARA conversion kit power req from 750 to 150
/:cl:

Decrease PARA conversion kit price

---

code/game/machinery/autolathe/artist_bench.dm

<details>
<summary>
Title. Description will still append a small descriptor of "It inspires x", but otherwise, people can re-desc their art as they please.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Artists can now name and describe their art.
/:cl:

Let artists name/desc their creation

---

code/modules/hydroponics/seed_gene_presets.dm

Fixes a name of a disk that is automatically generated

fixes disk auto naming incorrectly

---

code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipe_burger.dm

<details>
<summary>
</summary>
<hr>
Adds a couple of burgers to VIKA to give the two chefs some more recipes to goof around with. Also fixes dumplings. That's that!
<hr>
</details>
:cl:
add: Added more burger recipes
fix: Fixed the dumpling recipe from being a meat pie
/:cl:

Burgers for VIKA + dumplings fix

---

code/datums/craft/recipes/furniture.dm

This PR allows you to craft sofa
:cl:
add: sofas into crafting menu
/:cl:

Crafting Addition: Sofa

---

code/modules/projectiles/guns/energy/laser/firestorm.dm
code/modules/projectiles/guns/energy/laser/sunrise.dm

<details>
<summary>
</summary>
<hr>
Gives sunrise 1 (one) singular slot for modifications.
Fixes firestorm using wrong projectile leading to it being a full auto cog instead of pew pew with firestacks.
<hr>
</details>
:cl:
balance: Add 1 modification slot to sunrise
fix: Firestorm using the wrong projectile
/:cl:

Sunrise + Firestorm

---

code/modules/reagents/reagents/medicine.dm
code/modules/reagents/recipes/recipes.dm

Update description of sleep meds
:cl:
/:cl:

Update description of sleep meds

---

code/modules/clothing/head/helmet.dm

<details>
<summary>
As promised in previous PR, since the thermal helmet has a mandible now, and the NV helmet doesn't. Refer to #5765 changelog
Couldn't do it in the last PR because merge errors somehow messed things up. Fixed that, now.
</summary>
<hr>
<hr>
</details>
:cl:
balance: NV helmets don't cover the face anymore. Thermal helmets do.
/:cl:

Actually swap helmet coverage values

---

code/game/machinery/doors/blast_door.dm

Blast doors now can be meleed using melee weapons, wahoo

Fixes no melee blast doors

---

code/modules/client/preference_setup/loadout/lists/footwear.dm

These shoes fuck, so they gotta be in loadout.
Sadly, they are old black and gold church colors.

Add blacksilk boots to loadout

---

code/modules/mob/language/euro.dm
code/modules/mob/language/outsider.dm

Fixed the words to not use special letters

Euro hotfix

---

code/modules/client/preference_setup/loadout/lists/factionsecurity.dm

Requested change
Adds a spare marshal uniform to loadout for marshals access.

adds spare marshal uniform to loadout

---

code/modules/projectiles/guns/projectile/automatic/sts.dm

<details>
<summary>
</summary>
<hr>
Makes STS carbine be able to be assembled from it's frame, it exists fully functioning in code simply no way to acquire it currently.
<hr>
</details>
:cl:
add: STS carbine craft
/:cl:

STS Carbine

---

code/modules/clothing/head/helmet.dm

adds a normal golden laurel to the prime helmet alt styles like before.

Alt prime helmet laurel

---

code/game/objects/structures/crates_lockers/closets/onestar.dm

Fixes 90% of GP lockers spawning much less then intented

Fixes GP lockers not properly stacking spawns

---

code/datums/stat_modifiers/modifiers/mob/superior/ranged/ranged_modifiers.dm
code/datums/stat_modifiers/stat_modifier.dm
code/modules/mob/living/carbon/superior_animal/attack.dm
code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/turrets.dm
code/modules/mob/living/carbon/superior_animal/superior_defines.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/projectiles/projectile.dm

NPCs now will accually randomly shoot lims, this is accually not evenly random as mobs now have a pick-with-weights to target body parts
Range modifiers also now have affects on where a mob is aiming.

better shooting for mobs

---

code/game/gamemodes/events/rogue_drones.dm
code/game/gamemodes/events/spacevine.dm
code/game/gamemodes/events/spontaneous_appendicitis.dm
code/game/machinery/adv_med.dm

Space vines via admin pannels can once again be triggered!
Appendicitis rng is back wahoo! Only can trigger once and now shows up on Advanced scanners

return of appendicitis and spacevines

---

code/modules/cooking_with_jane/recipes/recipe.dm

since the stove doesn't work in intervals of 5, changes all timers with intervals of 5 to be lower or higher dependant entirely upon my whims
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Recipe Timer updates

---

code/datums/setup_option/backgrounds/origin_upbringing.dm
code/game/mecha/mecha_construction_paths.dm
code/game/objects/effects/spawners/ghostroles.dm
code/modules/mob/living/carbon/human/human_organs.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/oddity_items.dm
code/modules/research/designs/prosthesis_implants.dm
code/modules/research/nodes/greyson.dm
code/modules/sprite_accessories/_accessory_hair.dm

fixes "always targetted" to "always targeted" and a lot of other errors

fix more spelling errors

---

code/__DEFINES/jobs.dm
code/game/antagonist/station/inquisitor.dm
code/game/jobs/department.dm
code/game/objects/items/oddities.dm
code/game/objects/items/oddities_faction.dm
code/game/objects/items/paintkit.dm
code/game/objects/items/toys.dm
code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
code/game/objects/items/weapons/cards_ids_syndicate.dm
code/game/objects/items/weapons/nt_melee.dm
code/modules/biomatter_manipulation/solidifier.dm
code/modules/clothing/accessories/accessory.dm
code/modules/clothing/masks/gasmask.dm
code/modules/clothing/spacesuits/void/neotheology.dm
code/modules/mob/living/simple_animal/friendly/crab.dm
code/modules/reagents/reagent_containers/spray.dm
code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
maps/_HunterLodge/map/_Hunting_Lodge_old.dmm
maps/__Nadezhda/data/_Nadezhda_factions.dm

Mainly puts a "church of the absolute" where it was forgotten and had a "church of absolute" instead.

Minor spelling fixes

---

code/modules/projectiles/guns/energy/laser/abdicator.dm
code/modules/projectiles/guns/energy/laser/antebellum.dm
code/modules/projectiles/guns/energy/laser/carpediem.dm
code/modules/projectiles/guns/energy/laser/centauri.dm
code/modules/projectiles/guns/energy/laser/cog.dm
code/modules/projectiles/guns/energy/laser/concilium.dm
code/modules/projectiles/guns/energy/laser/disco_vazer.dm
code/modules/projectiles/guns/energy/laser/egun.dm
code/modules/projectiles/guns/energy/laser/firestorm.dm
code/modules/projectiles/guns/energy/laser/laser.dm
code/modules/projectiles/guns/energy/laser/laser_cannon.dm
code/modules/projectiles/guns/energy/laser/lasercore.dm
code/modules/projectiles/guns/energy/laser/makeshift_carbine.dm
code/modules/projectiles/guns/energy/laser/nuclear.dm
code/modules/projectiles/guns/energy/laser/peacekeeper.dm
code/modules/projectiles/guns/energy/laser/sunrise.dm
code/modules/projectiles/guns/energy/laser/xray.dm
code/modules/projectiles/guns/energy/misc/floragun.dm
code/modules/projectiles/guns/energy/misc/lasertag.dm
code/modules/projectiles/guns/energy/misc/mindflayer.dm
code/modules/projectiles/guns/energy/misc/robotguns.dm
code/modules/projectiles/guns/energy/plasma/cassad.dm
code/modules/projectiles/guns/energy/plasma/centurio_auretian.dm
code/modules/projectiles/guns/energy/plasma/excubitor.dm
code/modules/projectiles/guns/energy/plasma/hydrogen.dm
code/modules/projectiles/guns/energy/plasma/variant.dm
code/modules/projectiles/guns/energy/pulse/glock.dm
code/modules/projectiles/guns/energy/tesla/tesla_gun.dm

Fixes spelling and rephrases some things across almost every energy weapon.

Grammar and spelling fixes - Gunslinger's Edition Part 2 -Energy Weapons

---

code/modules/mob/living/carbon/resist.dm

Cuffs now have a minium break out timer of 10% of its normal timer
Robustness math tweak for cuffs

cuff math tweaks

---

code/modules/clothing/spacesuits/rig/suits/combat.dm
code/modules/research/designs/mecha_equipment.dm
code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm

Ok so now this only fixes some spelling

sheild - shield spelling fix

---

code/modules/reagents/machinery/chem_dispenser.dm

What this PR does adding the strawberry juice in the soda dispenser. So that way if people want strawberry juice they can.
<hr>
</details>
:cl:
add: strawberry juice to the soda dispenser
/:cl:

Soda Dispenser: Strawberry Juice

---

code/modules/admin/admin.dm

<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:

Lets mods dragdrop ghosts into control of a mob.

---

code/modules/reagents/reagents/medicine.dm

Carth now is a grow type anti-toxin and has proper scaling attached rather then being a stagnet 0.6 affect

carth now is a proper anti-toxin

---

code/game/objects/structures/watercloset.dm
code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/food/recipes_microwave.dm

Cooking With Jane stuff no longer will allow you to fill them by a sink, this breaks them
Fixes mushrooms recipes in microwaves
Plump Helmet biscuit no longer needs a full flat bread but a single slice to make now.

Cooking tweaks + fixes

---

code/modules/clothing/spacesuits/rig/rig.dm
code/modules/clothing/spacesuits/rig/rig_ui.dm
code/modules/clothing/spacesuits/rig/rig_verbs.dm

Fix rigs loosing their armor stats and name.
Fairly shitty fix because I have no idea what the root cause of it is but hey, it works.

duct tape rig fix

---

maps/__DeepTunnels/deeptunnels.dm
maps/__Nadezhda/map/_Nadezhda_Colony.dmm

Fixes a rouge tile being missing
Removes a rock flora from a tile it shouldnt be on
Fixes a code commit
Fixes bunker command maints access doors and uses maints doors
Removes a lockdown door from telecoms
Adds 2 more layers of lockdown doors to panic bunker
Adds a toilet and cutrains to perma brig cell.

Map fixes misc

---

code/modules/modular_computers/file_system/programs/generic/records.dm

Records now are recorded
:cl:
/:cl:

records record

---

code/modules/clothing/spacesuits/rig/rig.dm

Fix labcoats not fitting under rigsuits and improved the code behind it

Cosmetic check fix

---

code/modules/mob/living/simple_animal/hostile/hostile.dm

Junkbots and other targets that have target_dummy, will now be properly targeted by hostile simple mobs rather then ingored

dummy targets no longer are ignored by simples

---

code/modules/mob/living/carbon/superior_animal/sa_breath.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/carbon/superior_animal/superior_defines.dm
sojourn-station.dme

Fixes many vars simple not being correctly used for superior animal, making half the air mechanics they are were checking useless
superior animal no longer eat air at all
superior animal now take bad air damage, being to cold and being to hot!
superior animal now take toxic damage for being in plasma air, as well as normal "oh no my lungs cant handle plasma"  
In theory this should make less lag.

Simplified and fixed atmos for bugs [Exclusive for Superior Animal]

---

code/game/objects/items/devices/organ_module/active/armblades.dm
code/game/objects/items/weapons/nt_melee.dm
code/game/objects/items/weapons/tools/knifes_daggers.dm
code/modules/core_implant/cruciform/rituals/path.dm

Adds a new factorio magnetism spell that when holding church shields, healing items, and weapons (not implanted) become no drop.
Does not work for armor/cells/guns as that would be either useless or op

factorio magnetism

---

code/modules/research/destructive_analyzer.dm

Adds a limit of mater return for DA to be 100% rather giving more mater then item has
Fixes DA not properly giving updates when filled with better stockparts

Removes DA mater doup

---

code/game/objects/items/weapons/tools/mods/_upgrades.dm

Melee addition for weapons (guns) now is shown
Melee AD addition is now shown for weapons(guns)

Fixes missing upgrade stats

---

code/game/objects/effects/effect_system.dm
code/game/objects/objs.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/projectile/automatic/duty.dm
code/modules/projectiles/guns/projectile/automatic/solmarine.dm
code/modules/projectiles/projectile.dm

WP smoke properly respect max fire stacks code
Duty has been retooled to be anti-low armor rifle for clearing out swarms of weak mobs rather.
Adds framework for guns to give extra post-armor damage mult
Fixes solmarine line for wielding

Duty retool and WP fix

---

code/modules/mob/living/carbon/human/say.dm
code/modules/mob/living/carbon/human/whisper.dm

adds a little bit more flavour to ? and ! endings.
Also fixes whisper verbs just saying "Lilian softy" instead of "lilian whispers softly" so the speech verb doesnt look out of place in the chat.
? additions: "inquires", "enquires", "queries"
! additions: "proclaims", "hollers"
whisper additions: "whispers quietly", "whispers softly"

Speech flavour

---

code/game/objects/items/weapons/tools/misc.dm
code/modules/core_implant/cruciform/rituals/path.dm

Adds a new litany for Tessellates that gives a medical omnitool
Handled codewise the same as the psionic omnitool/factorial omnitool
<hr>
Adds the omnitool to the misc tools file
Adds a litany to the paths ritual file
<hr>
</details>
:cl:
add: Adds a litany for Tesselates to summon a medical omnitool
/:cl:

Tessellate Omnitool Litany (For real this time)

---

code/game/objects/items/weapons/storage/hardcases.dm
code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
code/modules/projectiles/ammunition/bullets.dm
code/modules/projectiles/guns/projectile/revolver/capgun.dm
code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm

What started out as me looking to add an upgraded Rigsuit module for SOMs (And immediately giving up on the notion)  expanded to me combing through and doing some quality of life additions of equipment to Cargo and a few station tabs.
This PR adds: (And why)
A base price for Hardcases (For the purposes of importing them through a new storage utilities tab)
A new storage utilities tab in Solnishko, along with the variety of hardcases, also contains a few pouches (So there's an option other than spending a bunch of steel/disk points to craft them) [Later, this can probably be expanded to included satchels, backpacks, and duffels, just so we have a 'renewable' inround source for the basics]
Adds the capgun and capgun ammo to the Solnishko Toy's tab (With Trillby's tutelage, capgun ammo now …

Lonestar-ering

---

code/datums/craft/gun_parts.dm
code/datums/perks/job.dm
code/datums/perks/oddity.dm
code/game/objects/items/weapons/storage/hardcases.dm
code/game/objects/random/mob/termite.dm
code/modules/hydroponics/seed.dm
code/modules/mob/living/living.dm
code/modules/organs/internal/lungs.dm
modular_sojourn/churn.dm
modular_sojourn/task_master/_task_master_defines.dm
modular_sojourn/task_master/tasks.dm

Good evening ladies and gentlemen to this year's Spelling TrilBee contest part 5(?)!
Today we have: 
Fixes every visible "dosnt" to "doesn't"
Fixes every visible "do to" to "due to"
Fixes spelling and phrasing in "tasks"  to hopefully make it easier to understand while not omitting flavour.
Fixes spelling and phrasing behind the code to have diving and bad luck still be applicable and functional across skills and oddities.

5th Absolutist Spelling TrilBee Contest

---

code/datums/repositories/crew/vital.dm
code/modules/genetics/machinery/advanced_grinder.dm
code/modules/reagents/machinery/grinder.dm

Grinder's bottles no longer have glass in them.
crew vital monitor now properly shows toxins levels

fixes grinders matter doup and vital monitor

---

code/game/objects/items/weapons/tools/stunbatons.dm

<details>
<summary>
</summary>
<hr>
Fixes a spelling misstake
<hr>
</details>
:cl:
fix: Typo in xenobio stun baton description
/:cl:

Xenobio batong

---

code/game/objects/items/weapons/tools/hyrogen_melee.dm

Fixes hydrogen sword size when detactive

size fix for hydrogen sword

---

code/modules/reagents/recipes/recipes.dm

<details>
<summary>
</summary>
<hr>
Replaces four spaces with one tab. No change in-game.
<hr>
</details>
:cl:
refactor:Change spaces for tab
/:cl:

Replace spaces with tab

---

code/datums/perks/special.dm

<details>
<summary>
</summary>
<hr>
typo Forecful -> Forceful
<hr>
</details>
:cl:
spellcheck:Forecful -> Forceful
/:cl:

typo Forecful -> Forceful

---

code/modules/psionics/psion_powers/healing_powers.dm

<details>
<summary>
</summary>
<hr>
Typo; requested by Trilby
<hr>
</details>
:cl:
spellcheck: Typo
/:cl:

Typo; requested by Trilby

---

code/modules/psionics/ear.dm
code/modules/psionics/psion_powers/armour_powers.dm
code/modules/psionics/psion_powers/deepmaints_themed_powers.dm
code/modules/psionics/psion_powers/faction_powers.dm
code/modules/psionics/psion_powers/gear_summoning_powers.dm
code/modules/psionics/psion_powers/healing_powers.dm
code/modules/psionics/psion_powers/locator_powers.dm
code/modules/psionics/psion_powers/mob_affecting_powers.dm
code/modules/psionics/psion_powers/oddity_powers.dm
code/modules/psionics/psion_powers/oldification_powers.dm
code/modules/psionics/psion_powers/psion_starter_powers.dm
code/modules/psionics/psion_powers/telekinetsis_powers.dm
code/modules/psionics/psion_powers/teleporation_powers.dm
code/modules/psionics/psion_powers/trash_powers.dm
code/modules/psionics/psionic_items/psi_catalysts.dm

<details>
<summary>
</summary>
<hr>
Changes a lot of descriptions, names and interactions of mostly psion-focused things. Tried to stick to the original ideas as much as I could, though I DID have to change the "Scrap Together" description a bit, since it was a blatant lie and I didn't like it >:(
Anyways it took a bit of effort and hopefully it's gonna be worth it
<hr>
</details>
:cl:
tweak: Changed descriptions of a couple of catalysts and "Scrap Together" psi power.
spellcheck: SO many psi powers. And the EGO machine, too.
/:cl:

Grammar n' stuff

---

code/modules/surgery/surgery.dm

<details>
<summary>
Does not slowdown when performing surgery on patients that selected barefoot as "shoes" on loadout, for example characters with talons, hooves and so on.
</summary>
<hr>
fixes #5931
The check for shoes also considered the "fake" shoes (talons, hooves, ...) as ... well, shoes. Therefore a punishing slowdown was applied. Even though the shoes can't be removed by the surgeon. An added check now prevents the penalty being added.
Change dicktated by Trilby.
<hr>
</details>
:cl:
fix: No slowdown on hooves/talons
/:cl:

No slowdown on surgery on hooved/taloned/callused patients

---

maps/__Nadezhda/map/_Nadezhda_Colony.dmm

Fixes a light switch not being on a wall. and a spare air alarm in maints stuck in a wall
fixes medical pysc door controles not properly bolting doors closes #5923

fixes a light switch and extra air alarm

---

code/datums/observation/~cleanup.dm
code/datums/sound_player.dm

By phoenix_404 fixes a issue that lead to debug log spams

Log Spam Fix - instrument issues

---

.github/workflows/ci_suite.yml
.github/workflows/generate_documentation.yml

Update workflows to v4.
Updates workflows from 3.7.1 -> v4.7.2

Workflow Update

---

code/modules/psionics/psionic_items/psi_catalysts.dm

<details>
<summary>
</summary>
<hr>
Just a typo, "our mind" instead of "are mind". Phonetically similar, written differently.
<hr>
</details>
:cl:
spellcheck
/:cl:

typo: are mind -> our mind

---

code/modules/economy/os_cash.dm

corrects that you can take out more GP coins then in a stack of GP coins

Fixes GP coins being doup'ed

---

code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm

Does what it says on the tin, prices felt a little low so I bumped up the costs of the importable mechs at the mecha station.

Imported mech Price Bump

---

code/modules/client/preference_setup/loadout/lists/armament.dm

Adds the quickdraw scabbard to loadout. Nothing more, nothing less.
<details>
<summary>
</summary>
<hr>
Adds quickdraw scabbard to loadout, since currently you can ONLY get it from trash piles.
<hr>
</details>
:cl:
add: added qd scabbard to loadout :^)
/:cl:

Addition of the quickdraw scabbard to loadout

---

code/datums/craft/recipes/medical.dm
code/game/machinery/autolathe/matterforge.dm
code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
code/game/objects/items/stacks/medical_stacks/splint_stacks.dm
code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm
code/modules/mob/living/carbon/superior_animal/vox/vox.dm

By lolman
NanoForge will now drop the power source (oddity you add in) when deconstructed
By Draganfrukts
Lowers crafting of handmade gauss to 4 from 5
By Trilby
Lowers biomatter per stack of handmade gauss
Wooden splints contain, wood rather then biomatter
Renames bird mobs from the Hausa language to Romany and better sights name translations for birds
Renames wasp to be Amethyn wasp rather then jungle to stop confusion

Ports + Tweaks 

---

code/game/objects/effects/decals/crayon.dm

The drain spell now informs you when you reached max HP.

Feedback for crayon drain

---

code/game/objects/items/weapons/power_cells.dm

QoL Handcrank charger now automatically continues to charge
Fixes in use var when taking the cell out mid charging or when it is full

QoL Handcrank charger now automatically continues to charge

---

code/controllers/subsystems/ticker.dm

Adds a cooldown for lobby ending notification sound as requested by people that play with sound.
By Wilson
Fixes some trilbish

Adds a cooldown for lobby ending notification sound

---

code/datums/craft/recipes/clothing.dm

<details>
<summary>
</summary>
<hr>
More clothes crafting, yay.
I based the material requirements off of the already existing 'tribal hides' recipe for the loincloth and chestwrap, and the 'ragged cloak' recipe for the suit items, adjusted for their respective materials.
<hr>
</details>

Adds crafting recipes for tribal clothing

---

code/__DEFINES/perks.dm
code/datums/perks/backgrounds.dm
code/datums/setup_option/backgrounds/origin_upbringing.dm
code/modules/sanity/sanity_mob.dm

<details>
<summary>
</summary>
<hr>
Just an idea I've had floating around for a while, and finally decided to put into code.
This basically just adds an upbringing choice for non-synths that gives them a decently big stat boost in exchange for not being able to gain inspiration without admin intervention.
<hr>
</details>

Close-minded upbringing (No inspiration)

---

code/modules/mob/living/silicon/robot/robot.dm

Someone sent a link to a PR from the Equinox-Sojourn offshoot, and asked for it to be mirrored here.
Literally can't see a reason as not to do this, as it's just a quality of life feature already afforded to all other players.

Gives Robots OOC notes

---

code/__DEFINES/jobs.dm

<details>
<summary>
removes AI, premier and robo from hivemind list
</summary>
<hr>
removes AI, premier and robo from hivemind list
(can you tell?)
<hr>
</details>
:cl:
tweak: removes AI, premier and robo from hivemind list
/:cl:

remove AI, premier and robo from hivemind list

---

code/datums/craft/recipes/furniture.dm

<details>
<summary>
</summary>
<hr>
Finally, the best option for outdoors seating (Excluding the determination chair) can be made for custom builds.
<hr>
</details>

Corrects a heresy (Makes benches buildable)

---

maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
maps/__Nadezhda/map/_Nadezhda_Colony.dmm

Toxins main mixing area now has a working scrubber 
A backup pipe that leads into main distro has been corrected

Fixes two missing/wrong pipes

---

code/modules/cooking_with_jane/recipes/recipe.dm
code/modules/cooking_with_jane/recipes/recipe_burger_roach.dm
code/modules/cooking_with_jane/recipes/recipe_donuts.dm
code/modules/food/recipes_microwave.dm
code/modules/hydroponics/grown_predefined.dm
code/modules/hydroponics/seed_datums.dm
code/modules/mining/satchel_ore_boxdm.dm
code/modules/mob/living/carbon/human/human_species.dm
code/modules/mob/living/silicon/silicon.dm

By CWJ
standerized soybean naming in code, should fix any recipies that where no functional do to this
fixes a runtime in silicons with a verb
By ryuu-dragon
Fixes some recipies having qmod when not needing to and bad recipies
By Mycah142
Mannequins no longer process
By VmpOS2NHSkhkejA9
Makes ore boxes climeable

Ports downstream fixes and some upstream fixes as well

---

code/game/objects/structures/crates_lockers/closets.dm
code/modules/tips_and_tricks/gameplay.dm

When looking at crates/lockers/closets you now get a sense of how damage it is
You can now repair crates/lockers/closets with tape
Adds two new tips explaining these features and and mechanics
Welding closets/lockers/crates now need to be in any intent other then help, should help accidental welding/sealing be less common

closet repair and seeable health

---

code/__HELPERS/unsorted.dm
code/controllers/subsystems/statpanel.dm
code/game/machinery/camera/presets.dm
code/game/machinery/doors/airlock.dm
code/game/objects/effects/portals.dm
code/game/objects/items/weapons/tools/_tools.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/new_player/new_player.dm
code/modules/organs/internal/_internal.dm
code/modules/paperwork/folders.dm
code/modules/power/cable.dm
code/modules/projectiles/projectile/bullettypes.dm
code/modules/research/xenoarchaeology/finds/finds.dm
code/modules/tgui/tgui.dm
code/modules/trade/datums/_trade_station.dm

By ryuu-dragon
fixes many missing sanity checks that throw runtimes/errors Fixes divide by 0 issues
By Trilby
Fixes missing/incorrect xenoarch fines

Runtime squashing

---

code/modules/surgery/autodoc.dm
nano/templates/autodoc.tmpl
nano/templates/autodoc_capitalism.tmpl

Updates how autodoc sees toxin build up and handles it
autodoc healing of toxins is now a chemical injection and carbon pill to counter toxins
Autodoc toxins healing is now cheaper as it no longer directly heals toxins

autodoc toxin fix

---

code/controllers/subsystems/ticker.dm

Adds a 10 second delay for messages and sounds in lobby when restarting

increases cooldown + less spammy

---

code/modules/reagents/reagent_containers/glass.dm

<details>
<summary>
</summary>
<hr>
There is an awkward sound of pen scribbling on paper whenever a bottle is created in the chem_master. That's because the Initialize method of a newly created bottle calls a proc that labels a bottle with its name, even if the name is not set.
<hr>
</details>
:cl:
/:cl:

Remove scribble sound when creating glass bottle

---

code/game/mecha/equipment/weapons/ranged/bullet_weapons.dm
code/game/mecha/equipment/weapons/ranged/explosive_weapons.dm
code/game/mecha/equipment/weapons/ranged/mech_ammunition.dm
code/game/mecha/mecha.dm
code/game/verbs/ooc.dm

Fixes mecha ammo not being reloaded properly
Fixes the UI action for reloading not working on rocket racks
Fixes LOOC not working for mecha persons/poilets/occupants
Fixes lack of feedback to the occupant about gun reloading

Mecha fixa

---

code/modules/projectiles/guns/projectile/automatic/bond.dm

Removes the part of the bond's desc saying its bolt action

fixes bond

---

code/modules/lighting/lighting_overlay.dm
code/modules/lighting/lighting_source.dm
code/modules/mob/living/carbon/human/species/station/station.dm
maps/__Nadezhda/map/_Nadezhda_Colony.dmm

By Ryuu-Dragon
Fixes runtimes for lighting
By Trilby 
Fixes some broken sofa's
Removes beds from some locations replacing them with tables
Rebalances some race hunger to not be as extreme

Lighting fixes by  ryuu-dragon and misc tweaked

---

code/__DEFINES/maths.dm
code/game/atoms_movable.dm
code/game/objects/effects/temporary_visual.dm
code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm

Adds framework for mobs, items and misc other things that when they made leave a shadow after image to show faster speeds or be really cool
Kiaser when getting faster now uses said framework as a tell that they are speeding up

After Image Movement

---

code/modules/clothing/clothing.dm
code/modules/clothing/spacesuits/rig/rig.dm
code/modules/clothing/spacesuits/rig/rig_modules.dm
code/modules/mob/living/living.dm

Allows oddity knifes to go into boots, this is a qol thing
Oddities held inside of a vest or shoe now are counted properly for resting, how many people i wounder accidently left out a super oddity in the vest pocket?
Oddities in rig storage also are now checked for

Fixes oddies hiding away

---

code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
code/modules/mob/living/carbon/superior_animal/psi_monsters/attack.dm
code/modules/mob/living/carbon/superior_animal/superior_animal.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm

Makes some mobs no longer doble inject chemicals
Makes the math for chemical injections of mobs way more forgiving as not to assume everyone has 40+ melee armor

Makes poison bites from mobs injection scaling better

---

code/__DEFINES/perks.dm
code/datums/perks/cooldown.dm
code/game/objects/effects/temporary_text.dm
code/modules/core_implant/cruciform/rituals/priest.dm
code/modules/mob/living/carbon/human/human_movement.dm
code/modules/sanity/breakdowns/common.dm

Adds a new spell for the prime to use on a 1 hour cooldown with 70 power requirement
Adds a perk that is used for the new church power
Fixes a small bug with breakdowns 
New church power is quite powerful, scaling its damage and some affects by how many holy folks are around including fractles
Psionics on the otherhand get punished and reduce the affect of the primes damage with the spell
The new power also has a uniquic affect based on crusiform users around.

Jugement of the prime

---

code/game/objects/items/weapons/tools/_tools.dm

Remove an unneeded warning about welding levels when below 3 or more making people think

Removes unneeded feedback about welding

---

code/modules/projectiles/projectile/bullettypes.dm

Relay bullets now work again as intented

Fixes relay

---

code/modules/mob/language/outsider.dm

<details>
<summary>
</summary>
<hr>
Minor grammar edits to species language lore blurbs in Outsider.dm for readability. 
<hr>
</details>
:cl:
Edit: Minor grammar fix to Cindarite Voc, Sablekyne, Naramadi and Marqua language selection lore blurbs.
Edit: Kriosan and Akula language lore blurbs now properly note there is no written equivalent as indicated by the "has_written_form = FALSE", with a lore explanation cited on the same line
:cl:

Minor Grammar edit to species language lore blurbs.

---

code/modules/psionics/psion_powers/armour_powers.dm
code/modules/psionics/psion_powers/deepmaints_themed_powers.dm
code/modules/psionics/psion_powers/enhance_items.dm
code/modules/psionics/psion_powers/faction_powers.dm
code/modules/psionics/psion_powers/gear_summoning_powers.dm
code/modules/psionics/psion_powers/healing_powers.dm
code/modules/psionics/psion_powers/locator_powers.dm
code/modules/psionics/psion_powers/mob_affecting_powers.dm
code/modules/psionics/psion_powers/oddity_powers.dm
code/modules/psionics/psion_powers/oldification_powers.dm
code/modules/psionics/psion_powers/psion_starter_powers.dm
code/modules/psionics/psion_powers/pyschiatrist_powers.dm
code/modules/psionics/psion_powers/telekinetsis_powers.dm
code/modules/psionics/psion_powers/teleporation_powers.dm
code/modules/psionics/psion_powers/trash_powers.dm

Makes psionic powers a bit easyer to fine and better sorted 
Good looking verson

Gives every psionic power (that i know of) its own section

---

code/game/objects/items/weapons/power_cells.dm

manual_charger now will tell you more indept about why a cell or item cant be added to it
manual_charger no longer will eat cells if already having one present inside

feedback + bug fix for manual charger
