code/_onclick/telekinesis.dm
Does what #3815 does but separates the Nanogate nerf and Psionic nerf instead. People apparently have still been abusing this and not it's not being merged because of complaints over nanogates not going to FBPs.
:cl:
fixes: Psionic exploit.
/:cl:
=> Psionic Range Nerf

code/modules/mob/living/carbon/human/examine.dm, code/modules/organs/external/_external.dm, code/modules/surgery/autodoc.dm, code/modules/surgery/robotic_damage.dm, code/modules/surgery/surgery.dm
[By Jamini](https://github.com/sojourn-13/sojourn-station/commit/2beaebd2e6575a063137d74375cf359f1d6a81cc) 
tweak: Wounds now process every third tick
tweak: Wounds that are fully healed, bandaged, and salved will no longer show on examine
tweak: examine text now shows infections on external organs, as well as severity
tweak: adjusted examine text for broken limbs
tweak: blood vessel damage now only shows IB text if you have above 5 blood vessel damage
tweak: infections now show on examine if they are above infection level 1
[By MLGTASTICa](https://github.com/sojourn-13/sojourn-station/commit/a92b05a9573977459b7d7034ac332d36a3311316) 
fix: Fixed autodoc shrapnel removal not working properly.
fix: FIxed hardsuits not being removeable from FBP's backs. …
=> Medfixes and ports

code/game/jobs/job/captain.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm
Simply put - changes the jobs Synths can do somewhat.
- Most synthetics can be a cargo tech since I doubt LS lore-wise would care and there's not much they can abuse. (BS due to possibly replacing prospectors.)
- BS synths can now play Trauma Team. Makes sense since it's a combat-oriented role, usually, and BS synths can be corpsmen anyway.
- All synthetics can be a bartender, chef or janitor.
- Steward is no longer locked to only combat synths since it is a role that just handles finance _and_ body-guarding. (Personally - I'd argue Premier should be only unlocked to unbranded but I lost the argument of biased premiers ages ago.)
- Unbrandeds can now be heads of all departments (Except Prime, you need a cruciform - dumby) since regular FBPs can be heads anyway. 
:cl:
balance: (?) Allows …
=> Allows More Jobs for FBPs

code/modules/mob/living/carbon/human/examine.dm, code/modules/organs/external/_external.dm, code/modules/organs/wound.dm
By [zackerycodestoo](https://github.com/zackerycodestoo)
tweak: Injuries are displayed with more clarity
spellcheck: 'fresh skins' have been renamed to be more grammatically correct
=> more medical stuff

code/modules/clothing/glasses/powered.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/living_defines.dm
Fixes darksight always being 8 for humans do to bad number calles
Fixes darksight form equiment
Rebalances some races darksight
Buffs NV goggles to have 50% more power effectiveness 
Testing: Made sure it complies, that if you ware bigsunglasses your not completely blind, that lighint properly lets you see areas around you, that difference races have different darksight, that measons still work 
More testing: Tested with thermals, NV and everthing else I can think of, all working rather well and having its intented view ranges and quirks.
Performance: Likely a bit more intensive now with more checks and math stuff
=> massively lowers darksight and fixes it

maps/_DeepForest/map/_River_Forest.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Massively reworks the church map to be better trade mark
Moves the church/guild """recycler""" (aka the thing that eats every item ever and gives nothing but refined scrap) into the guilds atmos storage
Removes 1 doble stacked trash cart in scavs
turns the old recycler room that into a table/shelf/trashcart storge room
Fixes the missing landing zone in the river forest
Added more sofa's
Testing: Tested every wire line that I remember to, ever pipe I remember to and the new stairs to make sure it all works
Performance: less wall oblistics but not sure if its good or bad in net
=> New church maping

code/modules/mob/living/carbon/human/emote.dm
<details>
<summary>
</summary>
Alters all * emotes (i.e. *shake, *dap) to use pronouns based on the character's gender, rather than biological sex. 
<hr>
<hr>
</details>
:cl:
fix: emotes are consistent with a character's pronouns
/:cl:
=> Emotes now use gender, not sex

code/datums/craft/recipes/guild.dm, code/modules/clothing/glasses/powered.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm, code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
Guild can now covert mesons into NV goggles, these NV goggles to incentivize them being made and used have 10% better charge whatever
Also added 2 new cargo deals to want said goggles so guild has a product to trade thats also worth any amount of credits that doesnt cost an arm and a leg
Testing: Made sure it complied, spawned a normal measons checked its cell that it spawned with
spawned crafted, made sure no cell, made sure adding a cell worked
Performance, technically less
=> Nv coverted guild goggles

code/modules/clothing/glasses/powered.dm
Measons now get +1 darkview so you can see around you 1 more tile with them
Testing: Actually none, legit 0
Performance: No real change
Why is this made?
Requested by Jack Torrs
=> Measons +1 view

code/datums/craft/recipes/guild.dm, code/game/mecha/equipment/tools/tools.dm, code/game/mecha/working/ripley.dm, code/game/objects/structures/burrows.dm
The Ripley mech has been quite a disappointment for both mining and guild. While this PR is not addressing the issues for mining it does address those in the interest of guild. A common issues that mechs in maints is poor energy, overall slower progression and more tedium that especially shows when fighting armies of roaches. With the extra storage the ripley has much more of an incentive to be used over the rig suits cargo clamp and the decreased energy draw giving it more range. The tesla link would both reward the guild of turning on power in maints and help with tedious walking back and forth. Drills being able to seal burrows makes it also the ultimate maints clean up tool and the kill clamp recipe just to give the mech much needed offense that isn't relying too much on rng.
Tested: …
=> Ripley buff

code/modules/genetics/creatures/wasonce.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Teleporting (like using the psionic teleport) while within a crimson jelly no longer pushes more mutations into you once freed.
/:cl:
=> You can teleport out of the wasonce

code/modules/projectiles/projectile.dm, code/modules/projectiles/projectile/bullets.dm, code/modules/projectiles/projectile/bullettypes.dm
Requested by CDB
Drastically increases most bullet damage against players and structures alike
Well still not **any different against pve**  in hopes of better balance in faster combat in pvp stulations and increased 
Makes everything that checks structure_damage_factor actually use it
The increase against structures ontop with added damage should make it way easyer to face against locked doors, turrets and walls in cases were it matters do to such. This also makes reavers much more deadely with their projectile based weapons.
Note: Most values are close if not increased compared to the pre-bullet balance of pve damage.
Other note: Bolts/Arrows from hunters base gear have not been changed at all as those values are simply already extremely high and balanced with the pve damage in mind. …
=> bullet balance 2.0

code/modules/core_implant/cruciform/rituals/priest.dm
Simple change. Makes it so FBPs can no longer be healed by church litanies nor heal themselves via church litanies.
Note: The new way the Heathen healing prayer works is that it gives healing chems, doing roughly the same healing as prior. Only risk is OD but brute-healing chem used is uncommon. Thus hard to OD on ever really.
Done in accordance as asked by lore-head.
Reasons given:
- Church healing is strong since it's full-on brute/burn damage removal.
- Self healing is very cheap power-wise and strong for the previous reason.
- Lore wise it doesn't seem to make sense cruciform can heal synthetic beings.
:cl:
balance: FBPs no longer get free hard-heals or self heals as requested.
/:cl:
=> Synthetic Church Healing - No More Self-Synth Healing

code/modules/mob/living/carbon/slime/items.dm
REALLY small edit of preventing -0.2 speed ups via red slimes capping at -0.1
Performance: none
Testing: none
=> Stops slime speed up being stackable to -0.2

code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Makes cows have a 10% chance to play the moo sound when they make a verbal emote (Mooing, moo's hauntingly)
Though this has brought my attention to the fact that cows, and maybe other simple animals don't do their noise emotes anymore. Will test if it's something in this PR specifically or if it's something that was broken at some point previously.
The cows will still moo, but won't show the emote of them mooing (Which already exists, but doesn't have a sound associated with it)
(PS, after saving the logs from a round and CTRL-Fing it, it seems chickens and cows, at the least, don't show their audible emotes. While this PR doesn't break it, I'll try looking into it to see if I can source out what's preventing them from showing.
They might even just be disabled for one reason or another, …
=> Moo Moo revolution

code/datums/setup_option/core_implants.dm
Does what #3815 does but separates out the Nanogate nerf from the psionic nerf. Only change now is that Nanogates are limited to Guild FBPs to actually give a reason for these FBP types to be used and prevent oversights in how Nanogates work from being abused.
If the retort argument is: "But this limits FBPs" - we limit Church cultie implants that have upsides and basically no downsides to Church FBPs, so I don't see why we limit the implant that has effectively no downside for FBPs to the relevant faction that these implants are used by. 
:cl:
balance: Removes regular FBPs from taking Nanogates. Only Guild ones can now.
/:cl:
=> Nanogate Removed from FBPS (EXCEPT Guild FBP Models)

code/datums/perks/job.dm
When people want you filling 10 item lunchboxes with cooked food its alot of alog spam. This removes that by commenting it out.
=> chef perk no alog

code/modules/reagents/reagents/other.dm, code/modules/reagents/recipes/recipes.dm
Will be used in a future PR.
Allows coolant to cool reagent containers when sprayed. Adds a refrigerant subtype that is better at cooling. Also, this makes them both somewhat toxic. Coolant will cool a container by about 5.5 K per 5 unit squirt and refrigerant will cool it by about 38 K. Disables admin logs for coolant since it doesn't cool the air anymore.
:cl:
tweak: Allows coolant to cool reagent containers
add: Added refrigerant as a coolant subtype
code: Commented out unused coolant proc
/:cl:
=> Makes coolant cool

code/__DEFINES/weapons.dm, code/datums/uplink/stealth and camouflage items.dm, code/datums/uplink/stealthy and inconspicuous weapons.dm, code/game/objects/items/weapons/tools/mods/_defines.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/game/objects/random/guns.dm, code/modules/organs/internal/kidneys.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/gun_hud_actions.dm, code/modules/projectiles/guns/mods/mods.dm, code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm, nano/templates/weapon_stats.tmpl
Recoil maxium has been raised to 50 from 30 meaning it can build up more
Red is current:
Yellow is the inbettewn:
Green is now:
New gunmod - Pain-maker massively reduces a guns damage, AP and increase recoil offset and paindamage for when you dont want to snipe from 5000 years away and still take down someone
Fixes some bad numbers with kidneys
Fixes some bad trade names from organs
Makes the gun ui slightly bigger by default to prevent a UI scaling issue
Testing: shoot a gun a lot with the mod and without the mod to see recoil changes to make sure they were not storm trooper levels
Performance: no real change
=> recoil and new gunmod

code/modules/modular_computers/file_system/binary/research.dm, code/modules/modular_computers/file_system/programs/research/passive_pointes.dm, code/modules/research/rdconsole.dm, code/modules/research/research.dm
Adds in 2 robust anti-cheat messers and fixes a rare but real issue regarding same numbered data
When data is uploaded into rnd now it sets its size to 0 
Data now cant be copyed or exported
Data from the dataminer now only gets placed onto a disk
When a rnd console is made it now auto-syncs 
:cl:
fix: Data for RnD is much more robust in anticheats, as well as more fair if same numbers are rng roled. Also Data disks when uploaded to a console now sets their size to 0.
balance: RnD console now auto-sync when made as an anti-cheat
/:cl:
Testing: Robust testing of the bare minium to make sure it all works, made sure the console still works as well as the point miner
Performance: Not much changed
=> RnD Anti-cheating

code/modules/mob/hear_say.dm, code/modules/mob/language/codespeak.dm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Detaining now properly states that you are detaining the suspect rather then asking about it
Attack Lethal and Attack Non-Lethal now propose their questions rather then ask for premission
Added more numbers and code-say to help bolster unquic verbs 
When a church member hears codespeak they hear different words then what people accully say (this is accully normal as everyone hears something different)
:cl:
tweak: Code speak is slightly less useless
fix: Fixes some bad tiles on the transport shuttle
/:cl:
Testing: Well tested using mulitable mobs with and without code speak on mulitable channels making sure everything worked
Performance: less
=> slightly improves code-speak

code/modules/mob/death.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm, code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm, code/modules/mob/living/carbon/superior_animal/robots/robot.dm, code/modules/mob/living/carbon/superior_animal/termite/termite.dm, code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm, code/modules/mob/living/simple_animal/hostile/hivebot.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/mob/mob_defines.dm, code/modules/projectiles/ammunition/bullets.dm
Way less GC harddeletes
Fixes 12mm revolver speed loaders icons
Fixes some overlays staying after gibbing
Fixes some runtimes when overkilling some mobs
:cl:
/:cl:
Performance: improved
Testing: gibbed a few monkeys, saw they didnt runtime, dealt 50000000 damage to some mobs and watch them not runtime ect et
=> death fix+ gc fixes + icon fix

code/game/jobs/job/civilian.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/prospector.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm
A simple PR that's entire purpose is to fix alternative job names basically being nicknames and inconsistencies that just cause confusion. Prospector having a job called "enforcer" for example is a good example of it. Also changing corpsman to field medic, seeing as the blackshield are not a navy so them using a navy term for their medic has always been confusing, might require some other name changes to match, I'll see how it goes.
=> Job Alternative Names Updates

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
<details>
<summary>
My biggest nitpick about aberrant organs was its map location. Right now the lab was stashed away deep into soteria which gave it more of a hint that it is a science department thing more than a medical one. Additinaly grafting organs can sometimes consume a good chunk of time similar to chemistry so one of its biggest issue was that it forced people to be away from each other. By moving it where the exam room is and giving it plenty of windows you can now say hello to any pass by walkers, chit chat with the reception folks and even look over to the entrance in case someone needs help.
</summary>
<details>
<summary>
The exam room was then recycled and given a face lift that mimics the psych office a bit. Also moved the morgue a bit.
</summary>
</details>
<details> …
=> Organlab improvement

code/modules/projectiles/guns/_projectile.dm
Fixes a ammo shell doup with some reloading ways
Testing: Made sure the way it was douping no longer doups and still works as normal
Performance: no difference
=> miner ammo fix

maps/_HunterLodge/map/_Hunting_Lodge.dmm
Adds two wires to the Lodge's solar array, one under a panel that was missing a connection, the other underneath the SMES' terminal since currently it can only output, not input, so this lets it act as a proper battery.
Adds a bar of soap in the Barn for blood since it used to have one already inside the old farm shack.
Testing:
Compiled and ran it on a local server, panel now moved along with all the others and the SMES when given a surplus of energy, charged instead of staying at 20% or depleting.
The solar array has a fair amount of vestigial wiring leading to nowhere still, but unless that's deemed problematic by the dev team I'm not messing with it, since it's doing nothing.
First time using StrongDMM so let me know if there's been any sort of change that's not the above two, or any …
=> Lodge wiring and soap

code/datums/outfits/jobs/off_colony.dm, code/datums/setup_option/core_implants.dm, code/game/objects/items/weapons/storage/hardcases.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/game/objects/random/guns.dm, code/modules/mob/living/silicon/robot/robot_items.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/projectiles/guns/mods/mods.dm, code/modules/projectiles/guns/projectile/pistol/clarissa.dm, code/modules/research/designs/weapon.dm, code/modules/research/nodes/combat.dm
New gun mod for SI the Faller - like the dropper but once added cant be removed dosnt skrink the gun nor slow its fire rate, mostly for borg guns
All borg models (other then drones) now have a gun, a 9mm minium malpractice
Outsiders now will always have a medium and small cell as well as a random makeshift weapon with an ammo kit for crafting ammo aid them in the harder spawns or worst rng cases / soft locks
Outsiders now always get a flashlight as well
Fixes a few bugs with some intractions with installing mods
Fixes cyborg trashbag not able to store items
CBO gun now spawns with its silencer attached (not the DNA lock as that could lead to issues)
You can no longer by core-implanted and selete AI or Robot as they auto-drop and such the implants making it an admin saddo issue
:cl:
/:cl: …
=> guns and robo fixes

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
The kitchen freezer area was using /area/eris/crew_quarters/kitchen_storage and led to space tiles when something destroyed the baseplate.
Replaced the area with /area/nadezhda/crew_quarters/kitchen and removed the double APC inside the freezer room.
=> Kitchen Freezer Area Fix

code/game/objects/items/weapons/autolathe_disk/marshal.dm, code/game/objects/items/weapons/storage/marshal_kits.dm
<details>
<summary>
Replaces the Armstrong rifle in the Ranger's loadout with the 8.6mm Custer lever action. The reason being that the Spec-Op and the E-shotgun vastly surpassed the 10mms damage. This should balance it as the 8.6mm Custer is strong but sports a high recoil and is bolt-action, being slower firing than either other option but hard-hitting. Also fixes two issues; one being the Freedom SMG disk printed the wrong gun and the fact there was no ability to print 10x24 caseless for Rangers who used the spec-op.
</summary>
<hr>
<hr>
</details>
:cl:
add: Custer rifle has replaced the Armstrong for Rangers.
add: Adds the ability for the Marshal 'Shoot Out' disk to print 10x24 mags and ammo for the Spec-Op
fix: Fixed the issue with the Freedom SMG disk printing Thompsons.
/:cl:
=> Ranger Loadout & Fixes

code/__HELPERS/unsorted.dm, code/modules/mob/living/carbon/resist.dm, code/modules/mob/mob_grab.dm
Changes pow operations used to perform roots to preserve the sign of the first parameter.
This introduces `/proc/spow(x,y)` as a helper to solve this issue.
It should be used instead of `(x ** y)`.
Fixes the following runtime exceptions;
```
[23:40:51] Runtime in mob_grab.dm,283: illegal: pow(-3.000000,0.600000)
proc name: s click (/obj/item/grab/proc/s_click)
[23:45:01] Runtime in resist.dm,72: illegal: pow(-3.000000,0.800000)
proc name: resist grab (/mob/living/proc/resist_grab)
```
=> stat runtime fix: negative robust stat should not make you a god in grabs

code/game/machinery/autodoc.dm, code/modules/surgery/autodoc.dm
Fix behavior of ejecting autodoc not stopping and not clearing patient account.
Fix runtime in autodoc process when card does not have associated bank account.
```
[04:18:13] Runtime in autodoc.dm,189: list index out of bounds
```
=> Autodoc runtime and behavior fix

code/datums/perks/nanogate.dm
Fixes these runtimes; `..()` should be called _after_ messing with holder in both cases.
See other perk overloads of `remove()` for reference.
```
[22:56:03] Runtime in nanogate.dm,29: Cannot read null.brute_mod_perk
proc name: remove (/datum/perk/nanite_muscle/remove)
src: Nanofiber Muscle Therapy (/datum/perk/nanite_muscle)
call stack:
Nanofiber Muscle Therapy (/datum/perk/nanite_muscle): remove()
/datum/stat_holder (/datum/stat_holder): removePerk(/datum/perk/nanite_muscle (/datum/perk/nanite_muscle))
...
[22:56:03] Runtime in nanogate.dm,44: Cannot read null.maxHealth
proc name: remove (/datum/perk/nanite_armor/remove)
src: Nanite Skin-Weave (/datum/perk/nanite_armor)
call stack:
Nanite Skin-Weave (/datum/perk/nanite_armor): remove()
/datum/stat_holder (/datum/stat_holder): …
```
=> fix runtimes in nanogate prk removal

code/modules/research/xenoarchaeology/finds/finds.dm, code/modules/research/xenoarchaeology/finds/finds_eguns.dm
Removes chance for weapon to explode and not be reloadable. Changes out two of the weaker weapons for 3 modified weapons using different gimmiks. Adds more rounds to the revolver styled weapon. Basically making the xenoarch guns partially worth the effort of finding.
Testing on this is barely done due to how finds are spawned in game. Its exceptionally hard to test. I can't just spawn the guns in to work with them. But overall shouldn't actually break anything. And no runtimes were firing on my server.
=> Xenoarch weapons pass

code/controllers/subsystems/xenoarch.dm, code/modules/research/xenoarchaeology/finds/finds_defines.dm
Alters digsite spawning to be based on z level. This means mines and any map not specifically set will use the current normal way of spawning.
Maps like colony will use the HOUSE set of finds. While hunter fields will use GARDEN and ANIMAL. There are others of course but I don't want to spoil it.
Tested and code has comments for those who like to browse thru it.
=> Xenoarch Expiditions

code/datums/outfits/jobs/security.dm, code/game/objects/items/devices/radio/headset.dm, code/game/objects/items/weapons/grenades/flashbang.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/modules/clothing/glasses/misc.dm
<details>
<summary>
Adds in ear protection akin to that of ear muffs for the Marshal bowman headsets. Reason for this being that otherwise Marshals can flashbang themselves. This should now add +2 protection, and another +1 can be stacked with it if a helmet is worn along with the headset. Also - PR makes it so large shades are no longer welding-goggles despite being sunglasses.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Makes Marshal bowman headsets flashbang proof. (Mostly)
tweak: Makes large sunglasses no longer equal to better welding goggles. Why did they do this in the first place?
balance: Swapped out regular spawn Sec headset with a Bowman so Marshals start with flashbang protection. Backup headset in locker changed from bowmans to regular headsets, providing no flashbang …
=> Marshal Bowman Headsets Unique

code/modules/mob/living/simple_animal/friendly/slime.dm
Initial bug fixes on pet slimes carrying things.
Fixes pet slimes not updating sprites right on death.
Fixes pet slimes able to take items besides backpacks.
Fixes pet slimes able to take bags even after they have died.
Fixes a chat message that appeared wrong.
TESTED.
=> Pet slime bug fix pass

code/datums/perks/job.dm, code/game/jobs/job/offcolony.dm, code/game/objects/items/weapons/storage/hardcases.dm, code/modules/clothing/glasses/misc.dm, code/modules/genetics/mutations/cat_eyes.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/power/port_gen.dm, code/modules/projectiles/guns/projectile/automatic/solmarine.dm, code/modules/tips_and_tricks/jobs.dm, maps/_HunterLodge/map/_Hunting_Lodge.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
- Nightcrawler perk does no longer give perfect nightvision, now works **closer** to its intended luminosity. TODO: Apply a nightvision-like white overlay to make things easier to see without being literally free NVG
- Fixed medium cell not spawning for lifeline techs
- Typo fixes on the Saturnian
- Fixes Sec patch hud giving more flash protection than intended
- Blindfolds and tape blindfolds now offer maximum welding protection (as they should) since you're literally blind wearing them
- Replaces "items" in Blackshield mines with proper flashlights, adds a hidden easter egg somewhere else
<details> <summary> Adds a bottle of oil and universal enzyme, and a rolling pin to the kitchen</summary>
</details>
<details> <summary> Adds a ladder for ease of travel between medical and …
=> Hotfixes and Lodge improvement

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
<details>
<summary>
</summary>
Fixes misspellings of cache, melee, duffel* and industrial in PR #4085. While I don't want to be a grammar nazi, consistent spellings make it a hell of a lot easier to maintain and build off of code.
*"Duffle" is a valid spelling, but we use "duffel" everywhere else.
<hr>
</details>
:cl:
spellcheck: fixed backend typos introduced in #4085
/:cl:
=> Fixes spelling errors in #4085

code/game/objects/effects/decals/Cleanable/humans.dm, code/modules/mob/death.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/living.dm, code/modules/mob/mob.dm, code/modules/reagents/holder.dm, code/modules/reagents/metabolism.dm, code/modules/sanity/sanity_mob.dm
fix: Added Destroy() logic to metabolism and metabolism effects
fix: Cleaned up logic for qdels in reagent holders
fix: Cleaned up logic for metabolism qdels in carbon mobs
fix: Living mobs remove themselves from mob_living_by_zlevel in SSmob
=> By Pink-Chink

code/modules/research/xenoarchaeology/finds/finds.dm, code/modules/research/xenoarchaeology/finds/finds_eguns.dm
removes the xenoarch guns ammo problems.
Makes them overall better considering you can't just buy or make them and have to instead rely on RNG
=> xenoarch guns fix

code/modules/projectiles/guns/projectile/automatic/ak47.dm
<details>
<summary>
Makeshift AK was pulling from the Excelsior one and caused people to blow the fuck up when using it sometimes. It's been fixed.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Oversight on my end making makeshift AKs explode 40% of the time if the user was not Excelsior. Or - 99% shoot self.
/:cl:
=> Fixes Explosive Makeshift AK

code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
Makes Lancer station offer 300 credits for up to 4 sheet snatchers at a time, considering Solnishko buys many more knives at a time, for 150 each, this seems more than fair considering the effort  and materials involved. Also ain't no one cooking food for trade offers chief.
Also makes Boris station offer 400 credits for up to 2  guild made advanced sheet snatchers at a time.  Having literally only one, extremely niche and rare to obtain offer as the only offer for a station is a really bad idea. Might not make the most sense for this station, but I'll consider replacing it with something more fitting. Eventually. But it works for now.
...Also it's been awhile since I've made a PR so yell at me if I fucked it up somehow.
And, tested to make sure it works and compiles
=> Sheet Snatchers Offers!! Wow!!

code/modules/organs/internal/bones.dm
Modding bones caused their HP to vanish and potentially "bricked" people. Bone mods are disabled for now.
=> Removes bone modding (bug fix)

code/modules/reagents/reagent_containers/food/snacks/meat.dm, code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm, code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm, code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm
Woops! Guess I gotta found out how to make it so the old commits go away before starting a new PR, but for now, it looks like nothing outside of the latest commit will be changed via doing this. So for now, hehehaw.
Makes the religion stations buy meat, not as much per slab as Dionis does (given it's a tier one, roundstart station), but they can buy more at a time based on RNG.
Gives meat and all of it's sub-types a base price of 20 credits (hopefully)
Ghost-kitchen, AKA the VERY under utilized chef station now buys dinner trays. Slightly cheaper than knives. But I may change this to be more profitable than knives, albeit very restricted in number sold at a time, given it's one steel PLUS a tool-step. (Though honestly, I think I'm gonna tone back kitchen knife sales to 100, at LEAST, here …
=> More beacon fiddling, part TWO!! WOW! !EGHGHG!!! 

code/modules/projectiles/projectile/bullettypes.dm
Simply - this PR does these few things:
- Ups the effective range of 9mm to not instantly lose its drop off after traveling a single tile from the user firing it.
- Ups the recoil on 12mm / .50 Kurz. The reason being - the rounds are more powerful than even a 7.62 rifle. As such, they deserve a higher recoil. AP is good to have, but with the changes of AP damage to mobs, it is not as powerful as it once was.
- Ups the damage but also the recoil of 8.6mm / .408. The reason the same as above - its AP is strong, but its damage is 'meh'. This should make .408s act as proper hard-hitting battle rifles but hard to fire in large bursts of full-auto.
- Increased some agony damages on HPs to make them more viable. Also upped some of their recoils  - no idea why they were lower.
- 6.5mm has …
=> Caliber Damages & Recoil

code/game/objects/items/weapons/tools/screwdrivers.dm, code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm, code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
Sets non-default prices for meat, tofu, eggs, flour, and milk for Vermouth station.
Cad station has gotten a set of basic medicine bottles as offers, to give something chemists to do quickly and easily. Or the church/garden that knows how to work with plants.
Gives Dylovene a non-default price for the SI station.
Decreases the value of both normal and Greyson combination drills, and ups the required materials to print both.
=> Basic Chemist Offers, Combination Driver Slash. Famine.

code/game/objects/structures/watercloset.dm, code/modules/mob/living/silicon/Cyborg_AI/remote_control.dm, code/modules/mob/living/silicon/ai/ai.dm, code/modules/mob/living/silicon/robot/life.dm, code/modules/mob/living/silicon/silicon.dm, maps/_HunterLodge/map/_Hunting_Lodge.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Makes AI cyborgs limited to 1 print pr AI core
Makes hunter water basions no longer run out of water
Vastly improves churchs water fountains to be less likely to run dry
Fixes borgs being perma stunned/weakened/paralized
=> water and bots

code/modules/projectiles/guns/projectile/automatic/ak47.dm, code/modules/projectiles/guns/projectile/automatic/luty.dm
<details>
<summary>
</summary>
<hr>
Currently, the 9mm "Luty" and scrap Kalashnikov have a penetration_multiplier of 0. No matter what ammo you use, it'll always have 0 AP. I'm _fairly sure_ this is an oversight - they're the _only guns_ with _no AP_, and giving them this wouldn't disrupt their place as "acceptable but mediocre".
This PR gives the Kalash 0.8 and the Luty 0.6, compared to their damage_multipliers of 1.1 and 0.8 respectively.
<hr>
</details>
:cl:
add: Added new things
balance: Luty/homemade AK now have low armour pen rather than none at all
/:cl:
=> Fixes AP on the Luty/homemade Kalash

code/modules/sanity/sanity_mob.dm
<details>
<summary>
This PR does one simple thing - effectively reverting the code that made oddities keep their perk after usage. This was a change Eris did last year as well that I still feel is not exactly well balanced and makes oddity perks a 'pass-around' thing instead of encouraging the buying and/or selling of oddity perks. Similarly, some oddity perks are rather strong perks (i.e - Gunslinger, Springheel, etc) and therefor should be limited and treated as rare commodities rather than something to be freely passed around as: "I got my use out of it, here, on the house." _How will the Oddity economy ever recover from this mean rebel-man???_
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Tweaks oddities to be a 1-time use in terms of perks. After the use, the perk disappears but the …
=> No More Infinite Perks from Oddities

code/modules/mob/living/carbon/human/life.dm
halfs the hallos damage fire stacks do.
Testing information:
Keep in mind fire stacks only deal hallos damage every 50 seconds. So people saying they go down in a single hit of hallos are far weaker then my testing server spawned in puppet. Even having 4 stacks put on the puppet instantly, took more then then two procs (the initial, a second and the 3rd finally crit him)
=> firestack hallos buff

code/game/objects/random/scrap.dm, code/modules/scrap/scrap.dm
<details>
<summary>
</summary>
<hr>
Rescales trash pile so that food is not second most common pile in the colony (seriously why ?).
Adds plasteel to actually spawn for some reason it wasn't ever in pool.
Removes rods from spawning in food trash piles.
Removes medical and food piles from being called down by scrap beacon as it's name implies it's for scrap.
<hr>
</details>
:cl:
balance: Trash
/:cl:
=> This will affect the trout population

code/modules/organs/internal/nanogate.dm, code/modules/organs/organ.dm
<details>
<summary>
Balanced out nanogates finally. Nanogates now actually have IMPACTS from being EMPed and damaged. When the Nanogate takes and EMP, depending on its severity, it does temporary agony damage to the user. If the Nanogate goes below 10 health, it will break, causing the user intense looping pain and organ damage to either their heart, eyes, or brain, until the implant is removed or fixed. This will **FINALLY** provide a proper downside to Nanogate; as genetics is rarely used with a nanogate anyhow and the inspiration is honestly negligible due to perks you can get from 1 inspiration usage.
</summary>
<hr>
<hr>
</details>
:cl:
balance: Finally adds an effect for Nanogates when they get damaged rather than being funni meme: "YOU HATH NO EFFECT ON ME!!!" when they are damaged …
=> Nanogate Balancing

code/modules/client/preference_setup/loadout/lists/armament.dm, code/modules/client/preference_setup/loadout/lists/factionabsolute.dm, code/modules/client/preference_setup/loadout/lists/factionsecurity.dm, code/modules/client/preference_setup/loadout/lists/factionsoteria.dm, code/modules/client/preference_setup/loadout/lists/general.dm, code/modules/client/preference_setup/loadout/lists/utility.dm
Removes Katana, boot knife steel spear, pitcure from loadout
Ups Matchie in loadout
Makes huds spawn in bag rather then on face (this is a code optimization)
Costume kit now costs 1
anti-psion hat now costs one
ritual book is now in the church tab rather then general
=> loadout clearing and balance

code/game/machinery/crafting_station.dm, code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm, code/modules/nanogate/nanogate_items.dm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
This PR does a few things. Simply put in a an easy manner:
- **I bootleg fixed Nanobots not being able to be repaired** by a simple change of their code. It is jank as fuck, but it works in testing. Even though they can gain more health over their max health it refereshes upon hit and puts them back below their max. So - 'working as intended', clearly. (:
- **Increased scrap ammo cost in crafting & decreased cost in the Guild printer.** Scrap ammo, for some reason, was cheaper to craft rather than print. As such I increased the crafting cost and decreased the Guild cost to be roughly the same; a bit more steel required for hand-crafting.
- **Added a firefighter ripley & claw to Guild.** Don't see why not, can be useful in that roundstart grind RNG.
- **Fixed the RNG gun spawns in Guild.** …
=> Guild Fixes & Minor Additions

code/game/objects/items/weapons/storage/belt.dm, code/modules/client/preference_setup/loadout/lists/suits.dm, code/modules/materials/materials.dm, code/modules/mob/living/carbon/human/emote.dm, code/modules/mob/living/carbon/taste.dm, code/modules/power/solar.dm, maps/_DeepForest/map/_Deep_Forest.dmm
A recollection of fixes I noticed from my last PR, and player feedback.
<hr>
</details>
:cl:
add: Properly adds SoyFed jacket to loadout
tweak: Security belt can now take mini stunbatons.
balance: Removed random chance for a mob right outside Void Wolf outsider spawn as it was sometimes an instant game ending Nightmare Stalker.
fix: Certain materials now assigned their proper sheets. This solves the bug of not gaining back material (like cloth) used to pad a bed with, when you use a tool of wire cutting property to take off the padding of a bed.
soundfix: Lowered the volume on certain emotes that were too loud, through player feedback.
lore: Rewrites the paper in the Ironhammer Compound to symbolize the end of the hivemind arc and the disappearance of a teleporter that's no longer there, …
=> Minor hotfixes

code/game/gamemodes/scores.dm
<details>
<summary>
Move penalties for dirty floors from Church to Lonestar
</summary>
<hr>
Points were taken from Church for dirty floors. Unlike on Eris, it's not Church's responsibility (Janitor is a Church job on Eris). It's Lonestar's responsibility. So they get the points taken from them. 
I'm sure a lot of Church players were despaired because of their low points. Pain and suffering. Lifes ruined forever. Maybe one or two ritual suicides. Don't look at me that way, I _know_ that no one cares about the points.
<hr>
</details>
:cl: dutop
tweak: Move point deductions for dirty areas from Church to Lonestar
/:cl:
=> Fix point deductions for Church for dirty areas

code/modules/projectiles/guns/projectile/boltgun.dm
Bolt guns now properly use caseless ammo (the lever is the only gun that can)
In doing so you no longer have to cycle the bolt for caseless ammo, making the bolt reaction perk a conflicting perk with caseless ammo so do be warned
=> buffs the heck out of the lever guns

code/datums/perks/oddity.dm, code/modules/goonchat/browserassets/css/browserOutput_override.css, code/modules/mob/language/euro.dm, code/modules/mob/language/illyrian.dm, code/modules/mob/language/jana.dm, code/modules/mob/language/station.dm, code/modules/mob/language/yassari.dm
- Eurolang now has a proper color when spoken
- Jana now has its intended override color from the CSS rather than "brass" (makes it different from church latin)
- Languages got more snowflakey by changing how one speaks, asks and exclaims in them
- Fixes an exploit with the Springheel perk allowing a player to take multiple stackable instances of it
- Minor typo fixes
<hr>
</details>
:cl:
fix: Fixes an exploit with anomalies causing a player to have multiple instances of the Springheel perk that stacked for movement speed
fix: Fixed german not having a color when spoken
tweak: Jana no longer "brass" in color, now uses its intended one as per the CSS doc, to differentiate from Latin
tweak: Changed how certain languages talk, ask and exclaim from base english language, to make them …
=> Language and anomaly exploit fixes

code/datums/craft/recipes/floor.dm, code/datums/craft/recipes/wall.dm
Moves the catwalk and underplating craft recipe from the wall category to the floor category in the crafting menu.
:cl:
tweak: tweaked wall.dm & floor.dm
/:cl:
=> Catwalk and underplating categorization fix

maps/_DeepForest/map/_River_Forest.dmm
Removes a duplicate table for an outsider spawn on river forest.  Noticed by a friend a while ago, thought I'd fix.
:cl:
tweak: tweaked _River_Forest.dmm
/:cl:
=> Duplicate Table fix

code/game/objects/items.dm, code/game/objects/items/weapons/tools/_tools.dm, code/game/objects/items/weapons/tools/crowbars.dm, code/game/objects/items/weapons/tools/hammer.dm, code/game/objects/items/weapons/tools/misc.dm, code/game/objects/items/weapons/tools/mods/_defines.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/game/objects/items/weapons/tools/mods/mod_types.dm, code/game/objects/items/weapons/tools/multitool.dm, code/game/objects/items/weapons/tools/pickaxe.dm, code/game/objects/items/weapons/tools/saws.dm, code/game/objects/items/weapons/tools/screwdrivers.dm, code/game/objects/items/weapons/tools/shovel.dm, code/game/objects/items/weapons/tools/weldingtools.dm, code/game/objects/items/weapons/tools/wirecutters.dm, code/modules/projectiles/guns/ameridian.dm, code/modules/projectiles/guns/energy/laser/cog.dm, code/modules/projectiles/guns/energy/laser/laser.dm, code/modules/projectiles/guns/energy/plasma/plasma.dm, code/modules/projectiles/guns/energy/projectile/railgun.dm, code/modules/projectiles/guns/mods/mods.dm, code/modules/projectiles/guns/oddity_items.dm, code/modules/projectiles/guns/projectile/automatic/nail_gun.dm, code/modules/projectiles/guns/projectile/automatic/scaffold.dm, code/modules/projectiles/guns/projectile/automatic/trouble_shooter.dm, code/modules/projectiles/guns/projectile/pistol/rebar.dm, code/modules/projectiles/guns/projectile/pistol/rivet.dm, code/modules/projectiles/guns/projectile/pistol/spring.dm, code/modules/research/xenoarchaeology/finds/finds_eguns.dm
GP Nano-AI now requires the tool/gun to have either power or be GP compatible
GP Nano-AI once added cant be removed from a tool/gun
GP Nano-Repair now requires the tool to have either power or be GP compatible
GP Master Unmaker now requires the gun to have either power or be GP compatible
GP Nano-AI when added to any tool/gun makes that item GP compatible
All GP guns and tools are by default GP compatible
=> Banana Republic

code/game/machinery/crafting_station.dm, code/modules/projectiles/ammunition/ammo_kits.dm, code/modules/projectiles/ammunition/bullets.dm
Finner toons balance of crafting station to allow it to be able to mass produce ammo
Allows crafting station and ammo kits to make at a higher cost normal ammo
Tweaks incendiary prices to make them more rare in ammo crafting
=> Ammo crafting changes

code/game/objects/items/weapons/manuals.dm
<details>
<summary>
One slash too many made the URL invalid
</summary>
<hr>
I made a mistake in my fix for PR 4253. I had a slash too much in the path to the wiki. So I removed the trailing slash in my wikiurl config entry. I should have fixed the place where the URL is put together instead. So my local server worked, the server server didn't.
<hr>
</details>
:cl:dutop
Fix my previous fix for wiki connections in books
/:cl:
=> bug Additional slash makes URL invalid

code/modules/reagents/reagent_containers/food/drinks/bottle.dm
The correct sprite name was set to icon_state_empty, but later overwritten in Initialize.
<details>
<summary>
An incorrect sprite name was set
</summary>
<hr>
Some drink bottles have a sprite for a full bottle and one for an empty one (NAME_empty). Some other drink bottles, like "Emeraldine Melon Liquor", "Miss Blue Curacao", "Mister Red Candy Liquor", ... follow another pattern where they get the "icon_state_empty" property set in their definition (multiple drinks use the "alco-empty" sprite, for example). But this value was overwritten in the Initialize method.
I've added an if-clause checking if the said variable was already set. Only if it's still null, it's set to the full-bottle-sprite with suffix "_empty".
While writing this, I noticed that one icon_state_empty was set to …
=> fix some drink bottles having invalid empty sprites

code/controllers/subsystems/trade.dm, code/modules/modular_computers/file_system/programs/generic/trade.dm, code/modules/projectiles/ammunition/ammo_kits.dm, code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
Cargo no longer gets full ammo boxes to prevent direct selling of them making lag
Cargo direct selling now has a 1 second cooldown (the horror)
Cargo now can with an export beacon only do 50 items at a time, items that cant be sold are wasted in this count to help prevent cargo lag
Ammo boxes hand crafted in ammo kits is cheaper and more mathically forgiving with spare points
=> cargo nerfs and ammo crafting buff

code/game/objects/items/bodybag.dm, code/game/objects/items/devices/radio/beacon.dm, code/game/objects/items/devices/radio/encryptionkey.dm, code/game/objects/items/devices/radio/headset.dm, code/game/objects/items/devices/scanners/gas.dm, code/game/objects/items/devices/scanners/health.dm, code/game/objects/items/devices/scanners/plant.dm, code/game/objects/items/toys.dm, code/game/objects/items/trash.dm, code/game/objects/items/weapons/phone.dm, code/game/objects/items/weapons/power_cells.dm, code/game/objects/items/weapons/tools/mods/mod_types.dm, code/modules/paperwork/paper.dm, code/modules/paperwork/pen.dm, code/modules/psionics/psion.dm, code/modules/reagents/reagent_containers/food/snacks/meat.dm
- Adds preloaded reagents to a bunch of items, specifically focused on making some chemicals easier to access without a dispenser.
- Makes termite meat contain phosphorus, hydrochloric acid and sulphuric acid.
- Adds preloaded reagents to most tool mods.
- Adds plasticide (among other things) to phones, body bags, radio headsets, encryption keys, toys and trash.
- Adds ammonia to spider meat.
- Tweaks roach chemical values to make slightly more sense.
- Adds wood pulp to paper when ground, letting anyone make their own cardboard. (Guild buff)
- Adds lithium to batteries, radium and phosphorus to higher tier batteries.
- Adds mercury to scanners.
- Adds acetone to pens and paint.
- Fixes a typo in psion.dm
- Adds material quantities to phones.
=> Ghetto Chem Revamp (And minor typo fix)

code/game/objects/items/weapons/circuitboards/machinery/ameridian.dm, code/game/objects/structures/noticeboard.dm, code/modules/ameridian/ameridian_core.dm, code/modules/ameridian/ameridian_refinery.dm, code/modules/ameridian/liquid_ameridian_processor.dm
Massively reduces the price to use ameridian in the refiner
Improves the guide on the bulletin board 
Makes ameridian cores worth 5k rather then 1k
Makes the ameridian processor upgradeable with manips
=> ameridian buffs

code/controllers/subsystems/xenoarch.dm, code/modules/multiz/map_data.dm, code/modules/research/xenoarchaeology/finds/finds.dm, code/modules/research/xenoarchaeology/finds/finds_defines.dm, code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm, maps/_DeepForest/deepforest.dm, maps/__DeepTunnels/deeptunnels.dm, maps/__Nadezhda/nadezhda.dm
Gives mappers more control over xenoarch spawning
Causes finds in digsites to appear at lower depths
Makes geosampling less of a hassle
=> Xenoarch Types and QOL

code/datums/autolathe/guns.dm, code/datums/craft/recipes/guns.dm, code/game/machinery/excelsior/blackshield_teleporter.dm, code/game/machinery/vendor/weapon_kit_vendors.dm, code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm, code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm, code/game/objects/items/weapons/storage/blackshield_kits.dm, code/game/objects/items/weapons/storage/marshal_kits.dm, code/game/objects/random/guns.dm, code/game/objects/random/lathe_disks/guns.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/modules/projectiles/guns/projectile/automatic/lmg.dm, code/modules/projectiles/guns/projectile/pistol/colt.dm, code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm, sojourn-station.dme
Simple removals of some more guns. They are as follows:
- **Zatvor**. Reason: No one used it, my original idea of replacing BS' Mosins with actual more modern though jank equipment was accepted but then denied suddenly after. Gun has been in limbo.
- **Pegasus**. Reason: Shitty LMG everyone complains about. Replaced it in loot rotation with the objectively better Takeshi. Why did we port an Eris LMG and only give it to the Marshals, who never use LMGs anyway?
- **Delta Elite Colt - Dark Varient**. Reason: Why would Sol-Gov use a Colt M1911 and just make no changes besides an auto-dropper feature? Conflicts with want for 'sci-fi' guns for Sol-Gov rather than old WWII era guns. (FUDDs go away.) Replaced it on BS disk with its brother, the Delta Elite - identical besides the auto drop …
=> Gun Bloat Finals (For Now)

code/modules/mob/living/carbon/human/examine.dm
<details>
<summary>
</summary>
<hr>
Original PR: https://github.com/PolarisSS13/Polaris/pull/8775
Long story short, when you examine a carbon mob, you'll now be able to click on the name of anything they're wearing to see a description of it! Nifty stuff. Adds a reason to give flavour text to loadout items. Lets you judge the fashion sense of others. 
<hr>
</details>
:cl:
add: "mob examine", allowing you to examine items worn or held by other characters
/:cl:
=> Ports onmob examine from Polaris

code/modules/clothing/accessories/holster.dm, code/modules/mob/living/carbon/human/examine.dm
<details>
<summary>
</summary>
<hr>
Fixes an incorrect ref that allowed you to make people examine their own accessories. Also, the contents of holsters can only be seen while on the same tile.
I'm aware of issues where non-carbon mobs can't click the text, but this is a higher priority to me.
<hr>
</details>
:cl:
fix: fixed improper ref in examine code
tweak: holsters only show their contents if you're on the same tile
/:cl:
=> Onmob-examine fixes

code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
Allows Lonestar to buy the Exotic Ammunition disk they used to have on their console through the Factio seller.
:cl:
adds: Exotic Ammo disk to Factor trader on beacon.
/:cl:
=> Adds Exotic Ammo Disk to Factio

code/__DEFINES/reagents.dm, code/modules/reagents/reagents/stims.dm
Party drops once again cause brain damage on overdose, and now overdose at 10 units(3 bites completely unarmored, or 4 bites with a standard plate carrier. Better melee armor increases the number of bites it'll take to hit the OD.)
Menace now overdoses at 12 units, causing oxyloss in addition to its previous effects.
Additionally, slightly buffs both of the above chems to compensate for their increased lethality, their positive effects lasting longer
Tested extensively on a test-server, however worth noting that due to the very slow tickrate on my test server i could only test that it was basically working, not the exact balance of its working.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Ruins everything, Again.

code/modules/hivemind/mobs.dm
We increased explosive damage to cause death so easily due to something as simple as bleed damage - which even rough life cannot prevent.
Mob should not be density of 0 when it can nearly instant-kill the target and, if they somehow survive, will bleed out 70% of the time.
:cl:
balance: fixes the Enclave-eyebot rip to be less broken.
/:cl:
=> Enclave Bot Salt

code/game/machinery/smelter.dm, code/modules/aberrants/organs/_defines.dm, code/modules/reagents/metabolism.dm, code/modules/reagents/reagents/medicine.dm, code/modules/reagents/reagents/toxins.dm, code/modules/sanity/sanity_mob.dm
Long time no see from dah cat, back at with todays deal with Satin themself.
Lets start with the good news
Smelters now properly respect stack items once again and no longer reduces its materals so its 1:1 wooh
Thats about it for good news
Now for the greate changes ya been waiting for
Ana no longer is randomly and for free given out, it was a nice test to see how it would work and sadly its a bit to powerful.
Second NSA now has a much bigger selection of malus affects from making you see things, to giving you a heart attack so its actually lethal. But wait theirs more, most toxins now give **way** more nsa, most medical aid as well. 
On the flip side many more useless chems or sleeping agents now also help lower nsa build up to help treat overstimulation without needing to fully purge …
=> Smelter fix, ana not with levels and nsa changes

code/game/jobs/department.dm
Hello,
Bad rebelman back with a new PR that deflates our economy, allowing us to finally advanced past the need for the Zimbabwe hyper inflated currency.
Basically does what should have been done ages ago as agreed upon to reduce department accounts to cover wages with a tiny bit of discretion funding to encourage a want to participate in sales to earn money. Similarly, the command department has kept its emergency funding to allow them some level of negotiating authority in an emergency situation.
This can be adjusted or tweaked as we go, this should serve fine as we rarely max out departments let alone max them out with every player having nepotism. Even if everyone _did_ have nepotism - their wages would still be covered.
:cl:
balance: Balances budgets of departments.
/:cl:
=> Department Account Tweaks

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm, maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm, maps/__Nadezhda/nadezhda.dm
<details>
<summary>
moves the TEG room to solars, adapts it to be more supermatter friendly, for the event of a delamination, the server will suffer little due to the size of solars and lack of direct interaction with the main colony/atmos tanks.
</summary>
<br />Tests done: <br />
Ran a supermatter for 2+hours with it, cold loop went from 20c to 100c, basic setup deemed safe enough to run a whole shift with emitter on without delamination.  <br />
Caused a delamination, solars and most of the path to the elevator were unaffected, air still got deadly hot without a suit and internals.  <br />
There is "radiation" in the nearby area, but radiation closets were provided and to reach them negligible radiation MAY occur (who said Guild was OSHA compliant anyways?).  <br /><br />
Things …
=> Guild TEG changes + small bar mapfix

code/modules/organs/organ.dm, code/modules/surgery/surgery.dm
Simply makes a change that I believe may have been an oversight when we adjusted our system some time back of max.health and health changes; both by anatomy and changing how buffs/nerfs worked (replacing brute modifiers with health modifiers, etc)
Changes robotic limbs to effectively not get 20% extra 'armor' on top of whatever the limb gave previously. This makes it so robotic limbs actually do feel like they have less health than human limbs. Previously you had to hit a robot's limb more times with a high-damage weapon to gib/knock it off than a human counterpart. This changes that to allow limbs of robots to be more flimsy but allow self repair.
As such - self repair has been made slightly easier as well to compensate for the the fact synthetic limbs will take 20% more damage now (not …
=> Adjusted Robotic Limbs

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm, maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
<details>
<summary>
- Moves the Guild Adept's lockers from solars to the workshop
- Creates a "locker room" in the south of the workshop
- Moves what was there before to other areas or just nearby
- Deletes all dirt from areas a cleanbot is unable to reach normally in the entire Guild (solars not included)
- Makes the Church's conveyors in the reactor room start on
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Adept's lockers are now located in the southern part of the workshop, from solars.
tweak: The computers in the south part of the workshop got changed to wall computers and placed in broad visibility areas (pillar in the workshop and front desk room respectively).
tweak: One cyborg recharger from the south part got moved to near the dam controller computer, the other got moved to the …
=> Guild's redecoration of the workshop + church conveyor starts on

code/game/objects/effects/decals/crayon.dm, code/modules/reagents/machinery/alchemy.dm
Alchemy perk is now required to use the Alchemy equipment.
Adds in Alchemy Recipe papers.
=> Alchemy Addition

code/game/jobs/job/offcolony.dm, code/modules/library/lib_items.dm, code/modules/organs/internal/psionic.dm, code/modules/paperwork/filingcabinet.dm, code/modules/paperwork/folders.dm, code/modules/reagents/machinery/alchemy.dm, maps/_HunterLodge/map/_Hunting_Lodge.dmm
<details>
<summary>
</summary>
<hr>
Alchemy was recently updated to be usable in-game via blood magic, but the faction it was originally for - the Lodge - can't use it without going to the colony to maint-dive. This grants all three lodge roles PERK_ALCHEMY.
<hr>
</details>
:cl:
balance: Hunter, Herbalist and Huntmaster spawn with PERK_ALCHEMY
/:cl:
=> gives lodge roles access to alchemy

maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Adds in Blackshield RPG. I'm personally still iffy on the EMP rocket but - Trilby suggested to let it be tried. So, added one to it. 
Blackshield get a total of 2 regular RPG rockets and 1 EMP, plus a tubular pouch. I did remove their single box of teargas grenades though (this violates the Geneva Convention to use them on uniformed combatants........) - but I gave them a nice bobble head in their place (: 
:cl:
adds: RPG and rockets to Blackshield armory.
removes: Tear gas grenades from Blackshield armory. (Why have these?)
adds: small figurine to BS armory (: 
/:cl:
=> Adds RPG to BS Armory

code/datums/autolathe/parts.dm, code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm, code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
Bad pathing caused the 8.6mm barrel to be not printable. Fixed the pathing. Also reduced its license cost by 1 since the barrels are in high demand.
Similarly added the ability to buy 8.6mm barrels, 14.5 AMR barrels, machine gun mechanisms, and rubber grips from Syndicate trade beacon if enough rep is had now.
:cl:
fixes: Marshal disk now has proper 8.6 barrel on it. Also reduces license cost by 1.
adds: LSS now able to buy in-demand rare parts for guns from Syndicate beacon. Hopefully takes some stress away from rare loot spawns.
/:cl:
=> Fixes Marshal 'Do It Yourself' Disk & More LSS Beacon Parts

code/game/machinery/autolathe/autolathe.dm, code/game/machinery/autolathe/mechfab.dm, code/game/machinery/bioprinter_nt.dm, code/modules/research/rdmachines.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
- Returns balance to this world
- Industrial Autolathe maximum material Efficiency is now 30% (was 50%)
- Circuit printer maximum material Efficiency is now 20% (was 50%)
- Protolathe maximum material Efficiency is now 20% (was 50%)
- Exosuit Fabricator maximum material Efficiency is still 50% (Troublesome cat)
- Asserts Soterian gigachad dominance over the Absolutist sheep (and goats)
- Church Biovomiter material Efficiency is now 50% (Was 60%) (It cannot change it has no components don't @ me)
- Regular Autolathe maximum material Efficiency is still 50%
- Order a printer from Soteria today!
/:cl:
=> Autolathe Rebalancing

code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm, code/modules/projectiles/guns/projectile/automatic/specop.dm, code/modules/projectiles/guns/projectile/pistol/clarissa.dm
Small misc PR.
- Makarov no longer takes or gives Excel grips. 
- Spec Op now has slightly higher recoil modifier (it's literally a 10x24 caliber)
- Rubber grips now use 1 license instead of 2 on Marshal disk after feedback was given.
:cl:
balance: Makarov grip fix, Spec-op balance to have higher recoil, grip on Marshal disk no longer costs 2 licenses.
/:cl:
=> Spec Op & Misc

code/modules/cooking_with_jane/cooking.dm, code/modules/cooking_with_jane/cooking_catalog.dm, code/modules/cooking_with_jane/food_overrides.dm, code/modules/cooking_with_jane/porting_readme.txt, code/modules/cooking_with_jane/recipes/_read_me.dm, code/modules/cooking_with_jane/recipes/example_recipes.dm, code/modules/cooking_with_jane/recipes/recipe.dm, code/modules/modular_computers/computers/subtypes/preset_pda.dm, code/modules/reagents/reagent_containers/food/snacks.dm, nano/templates/catalog_entry_cooking.tmpl
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
- Implements cooking food in certain ways having the potential to change how the resulting food is described. (IE: If you add mushrooms to a steak recipe, its description can mention being sauteed with mushrooms.)
- Removes typos and vagueness from some recipes.
- Clarifies what cooking utensil to use when cooking in the VIKA
- Updates the eris port readme
- The cooking catalog now appears on Bar staff's PDA by default.
/:cl:
=> Add Food Qualifiers

code/datums/craft/recipes/alchemy.dm
Alters crafting order for the oil burner so it dosn't get stuck on tincture.
=> oil burner fix

code/modules/tips_and_tricks/jobs.dm
This PR fixes a singular typo of 
"Scrap Beacon has an one hour delay before it can be used again, meaning in a productive shift you can use it 8 times before its end."
to thirty minutes, as the scrap beacon currently stands at 30 minutes instead of a hour if this changes eventually down the line, then go ahead and add it back to one hour.
<hr>
</details>
:cl:
tweak: tips and tricks with updated info
/:cl:
=> Fixes typo in Tips and Tricks.

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/superior_defines.dm, code/modules/mob/living/life.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/simple_animal/simple_animal.dm
<details>
<summary>
- being set on fire is as harmful as most mobs as it is for players now (other sources of burning like being in a too hot room, accidentally stepping into a burn chamber and others unaffected, so no setting deep maints on fire to kill the king, you need to set him on fire directly and maybe survive the encounter)
- tested on several mobs from different folders, results are very similar across the board, processing impact was pitiful, apparently 50 roaches on fire are more of a strain to their AI while trying to murder you than anything
-  to tweak the burn damage go to code\modules\mob\living\living_defense.dm line 396 and adjust the math to your will
- pr made with the purpose to make mobs a bit easier to buff/nerf all in one move
</summary>
<hr>
<hr>
</details>
:cl: …
=> Being on fire is now bad for everyone's health (buff or nerf?)

maps/_HunterLodge/map/_Hunting_Lodge.dmm
<details>
<summary>
Adds the three hexcooking machines and extends the tablespace one tile west
</summary>
<hr>
<hr>
</details>
:cl:
add: Added hexcooking equipment to the Lodge
/:cl:
=> Adds hexcooking equipment to the Lodge

code/modules/cooking_with_jane/cooking_appliances/grill.dm, code/modules/cooking_with_jane/cooking_appliances/oven.dm, code/modules/cooking_with_jane/cooking_appliances/stove.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Relegates all object verbs for the cooking machines to the object tab. (The 'cooking' tab caused lag with its creation and deletion)
Prevents the dead from rising bread
/:cl:
=> Object verbs for cooking

code/game/jobs/job/offcolony.dm
Adds 7 more Outsider slots. Reason being that Outsiders commonly die early on and clog up the ability for more to join. The comment of 'well staff can open more slots' is moot considering the lack of response from staff when slots are requested to be opened. **Preferably** at some point this can be code-changed to open a slot every 30 minutes instead of all at once. But oh-well.
Especially stupid since they start in dungeons, many of which have mobs with over-screens length range, where they are meant to effectively die.
:cl:
add: More outside slots. (Total of 10)
/:cl:
=> Adds Outsider Slots

code/game/jobs/job/offcolony.dm, code/game/objects/landmarks/join.dm, code/modules/client/preferences_spawnpoints.dm, maps/_DeepForest/map/_Beast_Cave.dmm, maps/_DeepForest/map/_Deep_Forest.dmm, maps/_DeepForest/map/_Prepper_Bunker.dmm, maps/_DeepForest/map/_River_Forest.dmm, maps/_DeepForest/map/_River_Forest_old.dmm, maps/_DeepForest/map/_River_To_Swamp.dmm, maps/__Nadezhda/area/_Nadezhda_areas.dm
Tl;dr - removes all old Outsider spawns and adds new ones in a focused place. Including a new spawn location set that should work for outsiders as well.
Crashed ship with cyro pods, plus long-beds and a shit shack - for both sorts of player backgrounds who play outsiders really.
:cl:
adds: Outsider job slot increase from 3 to 10
removes: Outsider dungeon spawns
adds: Outsider standardized spawning area in swamps
/:cl:
=> Outsider Slots - Take 2

code/modules/psionics/psionic_items/psi_temp_items.dm
<details>
<summary>
Sets the Psychokinetic Balls to an empty tech tree, so that way it can't be infinitely produced to generate a free and quick 50 tech points in the deconstructive analyzer. You will do fabrication and you will Suffer.
</summary>
<hr>
<hr>
</details>
:cl:
Sets the Psychokinetic Balls to an empty tech tree
/:cl:
=> Fixes the Psions' balls

code/modules/mob/living/carbon/human/human_movement.dm, code/modules/mob/living/carbon/shock.dm
Contains this PR fix I missed on Eris during the Erismed 3 port.
https://github.com/discordia-space/CEV-Eris/pull/6684
Also updates our shock.dm to reflect Eris' shock.dm pain-states.
:cl:
balance: Pain slowdown changes slightly.
balance: Less overall pain taken. Similar for oxyloss damage.
tweak: Redoes shock.dm stages of pain to make paincrit hit less commonly.
/:cl:
=> Decreases Overall Pain by 10%, Decreases Oxy Pain by 40%, & Some other changes

code/modules/organs/internal/nerves.dm
This was originally left open for vote but - funny story - TURNS OUT that you can't even use oxycodone as an Exalt because ALL the nerves in your body fire when hit, making even oxycodone in surgery ineffective.
So sedatives didn't even fully work properly on Exalts. I tried. RIP.
:cl:
fixes: Exalts no longer are basically immune to painkillers due to being such special snowflakes. Intended to follow the vote, after testing with a player - proved surgery using sedatives can't even be done on them. RIP.
/:cl:
=> Exalt Nerve Fix

code/datums/setup_option/backgrounds/origin_synthetic.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/organs/internal/eyes.dm
Complaint was levied how useless toughness is on FBPs besides countering grabs; so I've taken most of the toughness-additions away and replaced it into other more useful stats.
Added FBPs to have welder-proof eyes now. This should prevent issues regarding welding. FBPs can no longer be flash-stunned but - who the hell cares, the instant go-to anyway for dealing with them is ions or lethals half the time anyway.
:cl:
tweak: Removes most toughness additions to FBP perks.
add: Addes new welder-proof eyes.
/:cl:
=> Less Dump-Stat FBP Backgrounds & Welderproof Eyes

code/game/objects/items/devices/radio/headset.dm, code/game/objects/items/devices/radio/radio.dm
<details>
<summary>
Adds multi-z transmission and reception to hand-helds
</summary>
<hr>
This lets Ham Radios (handhelds) transmit and listen to radio messages through multi-z environments like Scrap Haven without needing a telecomms setup, Robots are able to do the same, and headsets of all kinds are unchanged as they can only hear and transmit in their own z-level like before. Fallback-capable headsets like those belonging to the prospectors or marshals can hear multi-z, but not transmit. 
<hr>
</details>
:cl:
add: Ham radios are now able to transmit in multi-z areas
/:cl:
=> Adds multi-z transmission to radios

code/game/objects/items/weapons/tools/_tools.dm, modular_sojourn/task_master/_task_master_defines.dm, modular_sojourn/task_master/tasks.dm
Massively reduces the penitiles for having damaged tools
Adds a new task that helps with tools
Repairing a tool now lowers its health by 0.02 (aka 2%) of the healed value of the tool
=> tool breaking buffs

code/ATMOSPHERICS/components/binary_devices/passive_gate.dm, code/ATMOSPHERICS/components/binary_devices/pump.dm, code/game/machinery/cryo.dm, tgui/packages/tgui/interfaces/Cryo.js
<details>
<summary>
pumps, passive pumps and cryo cells now use TGUI, cryo also got autoeject functionality that is rudimentary, but works
</summary>
<hr>
the door button on the cryo menu will eject people, I can't edit the Cryo.js to change that button to Eject 😔 , also the autoeject only cares about the occupants health in relation to it's max health, if the occupant can't reach max health for any reason, it will not autoeject
<hr>
</details>
:cl:
add: cryo now has an autoeject function, it starts off, will eject and turn off the cryo **if the occupant is at full health**
tweak: gas pumps now use TGUI
tweak: passive gas pumps now use TGUI
tweak: cryo cells now use TGUI, door button will eject occupant (because I can't edit the associated .js properly, sorry)
/:cl:
=> more stuff into TGUI and a small cryo buff? (somewhat of a Guild nerf)

maps/_DeepForest/map/_Deep_Forest.dmm, maps/__Nadezhda/area/_Nadezhda_areas.dm
<details>
<summary>
Converts the admin safehouse thing location for actual use.
</summary>
<hr>
Mostly just gets rid of the impassable terrain that was blocking it, add some loot, some void wolfs spawns, and boom.
<hr>
</details>
:cl:
tweak:Makes the deepforest safehouse a actual location. Can be used for RPs or what not, if cleared out.
/:cl:
=> Abandoned Safehouse

code/modules/organs/internal/internal_wounds/_internal_wound.dm, code/modules/reagents/reagents/medicine.dm
<summary>
As the title says, converts organ wound signals to LEGACY_SEND_SIGNAL() in _internal_wounds.dm and medicine.dm. This should take care of the bug where peridaxon was deleting organs instead of wounds.
</summary>
:cl:
code: Converts legacy-formatted signals to legacy
/:cl:
=> Converts legacy-formatted signals to legacy

code/modules/organs/internal/psionic.dm, code/modules/psionics/psion_powers/healing_powers.dm, code/modules/psionics/psion_powers/pyschiatrist_powers.dm
<details>
<summary>
Adds two new psionic abilities
For all psionics:
Meditative Focus - Expend two psi points of your psi essence to focus your mind and increase your sanity, scales off your Cog stat and Psi focused Background perks ( Scholar / Bedlam )
For psychiatrist/enhanced psion:
Psionic Tranquility - Expend two psi points of your psi essence to calm the mind of another person you are grappling and restore their sanity, scales off your Cog stat and Psi focused Background perks ( Scholar / Bedlam )
Dev note: This has been tested and balanced with LongSleeves/Landen to not cause issues with inspiration system and is capped to (max sanity level - 10) and costing 2 psi points to curb Power gaming abuse.  If issues arrise, a timer will be coded in to prevent inspiration abuse
</summary> …
=> Frontier Psychiatrist - Two new psionic abilities to help with sanity

code/game/objects/effects/decals/crayon.dm, code/game/objects/items/weapons/candle.dm, code/game/objects/structures/bluespace_crystal_structure.dm, code/game/objects/structures/diamond_gem.dm, code/game/objects/structures/displaycase.dm, code/game/objects/structures/extinguisher.dm, code/game/objects/structures/fireaxe_cabinet.dm, code/game/objects/structures/flora/flora.dm, code/game/objects/structures/flora/flora_potted.dm, code/modules/reagents/reagent_dispenser.dm, code/modules/sanity/sanity_mob.dm
Adds more instigations of sanity
Potted plants now regen small amount of sanity, everything it needs to be maintained lowers its sanity regen
Broken fire axe cases and display cases lower sanity
Water coolers increase sanity
extinguisher cases now increase sanity based on being stocked (Mini gives smaller then full stock), having a empty  on open deals sanity damage
Bluespace cystal stuckers now give sanity
Both the golden shovel and LSS big gem now give sanity
Increases max sanity storage by 20 to give a bit more of breathing room
=> more sanity interactions

code/controllers/subsystems/xenoarch.dm
Makes anomalies spawn at a 5% - 10% of total non fossil digsites rate.
Might be tweaked down the line if to many are spawning.
=> dynamic xenoarch anomalies

maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
Adds a diesel board for expeditions
Changes one of the anomaly scan rooms to have a psionic harvester instead.
=> anomaly research additions

code/game/machinery/adv_med.dm, code/game/objects/items/devices/scanners/health.dm, code/modules/clothing/accessories/accessory.dm, code/modules/mob/living/carbon/brain/brain_item.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_damage.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/shock.dm, code/modules/mob/living/carbon/superior_animal/roach/roach_spits.dm, code/modules/mob/living/living.dm, code/modules/organs/external/damage.dm, code/modules/organs/internal/_internal.dm, code/modules/organs/internal/carrion.dm, code/modules/organs/internal/internal_organ_processes.dm, code/modules/organs/internal/internal_wounds/_internal_wound.dm, code/modules/organs/internal/internal_wounds/organic.dm, code/modules/organs/organ.dm, code/modules/reagents/reagents/medicine.dm, code/modules/reagents/reagents/toxins.dm, modular_sojourn/Borers/borer_powers.dm
- Mob health checks vital limb brute and burn damage again.
- Burn damage will always transfer at least 25% damage to internal organs.
- Damage to limbs will only be deducted when the transferred damage creates/progresses a wound.
- Oxy damage doesn't contribute to pain. Organ wounds cause pain as a side effect and organ damage to certain organs can causes oxy damage. It doesn't make sense to make organ wounds apply pain from two sources.
- Unbreakable type bones don't break. Slime people are the only ones that use these bones and this change is needed to allow them to die.
- Blood loss organ wounds progression time increased to 1 minute per level instead of 18 seconds.
- Oxy damage from damaged organs reduced by 50% to 75% depending on the case.
- Oxygenation effect from Dexalin and …
=> Erismed ports

code/datums/craft/recipes/lodge.dm
<details>
<summary>
Reduces the bolt lance's bolt crafting cost
</summary>
<hr>
Makes the regular bolt's recipe a bulk one, and halves all three bolt types' metal rod cost, where previously it was 1 sheet = 1 bolt, now it's 1 sheet = 2 bolts
I feel like 1 sheet = 1 shot with the bolt lance is a bit steep and could be lowered so less time has to be spent gathering scrap metal objects to smelt.
This PR does not touch the makeshift crossbow at all.
<hr>
</details>
:cl:
balance: Reduces crossbow bolt crafting costs
/:cl:
=> Reduces crossbow bolt crafting cost

code/game/jobs/job/prospector.dm
Their wage was set to 0 but, unlike colonists, did not receive starting money.
The starting money is 300 less than colonists, but to be fair, they start with bonus stats, bonus health, gear, and some baseline stuff like death alarms provided to them. So - seems fair to give them 500 credits vs the 800 colonists get.
:cl:
adds: Prospector starting money.
/:cl:
=> Adds Initial Starting Funds to Prospectors

maps/SpaceFortress/map/space_dungeons.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Removes the teleporter in the Excelsior dungeon as it was only added to make the turrets work; which are still not preforming right. As such, it's been removed and replaced with hostiles. Also - some later event map changes.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: No more excel tele and not-working turrets in lower-colony dungeon.
tweak: Event-map stuff.
/:cl:
=> Excelsior Map Fix

code/datums/uplink/void_wolf.dm, code/game/machinery/vendor/weapon_kit_vendors.dm, code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm, code/game/objects/items/weapons/disc.dm, code/game/objects/items/weapons/storage/hardcases.dm, code/game/objects/items/weapons/storage/marshal_kits.dm, code/game/objects/random/medicine.dm, code/modules/clothing/accessories/accessory.dm, code/modules/clothing/suits/armor.dm, code/modules/clothing/suits/greatcoat.dm, code/modules/core_implant/cruciform/rituals/construction.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm, code/modules/projectiles/guns/energy/laser/antebellum.dm, code/modules/projectiles/guns/energy/laser/carpediem.dm, code/modules/projectiles/guns/energy/laser/cog.dm, code/modules/projectiles/guns/energy/laser/laser.dm, code/modules/projectiles/guns/projectile/pistol/gyropistol.dm, code/modules/reagents/reagent_containers/food/snacks.dm, code/modules/reagents/reagent_containers/food/snacks/sandwich.dm, code/modules/reagents/reagent_containers/syringes.dm, code/modules/reagents/reagents/stims.dm, code/modules/reagents/recipes/recipes.dm, code/modules/research/designs/greyson.dm, code/modules/research/nodes/greyson.dm, maps/__Nadezhda/map/Underground_Old.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_Underground.dmm, modular_sojourn/Borers/borer.dm
<details>
<summary>
</summary>
<hr>
Removes several on the nose references from code - Lasguns (yes it is a generic term used by more than that one universe but for sake of consistency) now all of them are either laser carbines or in case of church weapons laser musket / blunderbuss
Machine Binding Ritual and Machine spirit renamed to Greaser and Greasy Lard to not be 1 to 1 reference.
"God Emperor of Mankind" is now "Demolition Man", yes still a reference but one less people will get and it can be considered generic.
"Emperor" Gyrojet pistol is now "Novichok" (hopefully that actually does mean manopener in russian) to be more in line with serbian guns.
Clothing referencing nonexistant jungle according to lore now refer to it as Amethyn or Amethyn forest
<hr> …
=> Reference moment

code/game/objects/items/weapons/shields.dm, code/game/objects/items/weapons/tools/hammer.dm, code/game/objects/items/weapons/tools/knifes_daggers.dm, code/game/objects/items/weapons/tools/shovel.dm, code/game/objects/items/weapons/tools/simple_weapons.dm
<details>
<summary>
</summary>
<hr>
Fixes alt-mode message typos and adjusts them to be more accurate (made the cheap spear inherit the same alt-mode stats as other spears, and adds alt-mode to the power fist)
If the power fist needs different alt-mode HALLOSS damage let me know, wasn't sure what to set it to.
<hr>
</details>
:cl:
spellcheck: Fixes typos in alt-mode messages
tweak: Adjusts cheap weapon alt-modes to be more accurate
add: Adds alt-mode to the power fist
/:cl:
=> Altmode item adjustments

code/modules/hydroponics/trays/tray.dm, code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
The churchie stations get access to hydro-trays for purchase (150 base price, which means they're bought at 170 from the ship) They arrive bolted to the floor, mildly annoying, overall nonissue though Can only be sold when unwrenched, which makes sense
Tested it to make sure fruit can grow (grape) and be harvested (grape)
=> Adds trays to Beacon (Tray revolution)

code/game/machinery/vendor/one_star_vending.dm
<details>
<summary>
</summary>
<hr>
Changes the "One Star Vendor" name to "Greyson Positronic Vendor" to match with our lore. The name "One Star" is what is used by Eris. Also altered the description to match, and minorly altered the wording
<hr>
</details>
:cl:
fix: Changed One Star Vendor to Greyson Positronic Vendor to match with Sojourn's lore 
/:cl:
=> Changes One Star Vendor to Greyson Positronic Vendor

code/modules/projectiles/guns/projectile/boltgun/mares_leg.dm
The bounty is a lever action rifle, made to fire 20mm shotgun rounds. But, despite being a quite costly, and supposedly mid-tier blackshield weapon, it's actually pretty bad. And that's because its stats are derived from a makeshift weapon that is purposefully bad, and I can't quite get why. This fixes it, and makes it a decent, but still not very good lever action that trades AP for some damage.
=> rebalancing bounty

code/game/jobs/job/offcolony.dm
FBPs may now be allowed to be outsider, this rule has been set in a time where fear of them powergaming against the colony was common, but now that the rules of conflict between outsiders and colonists is more strict, this is not a problem anymore.
=> outsiders can now be FPBs

maps/_DeepForest/map/_Deep_Forest.dmm
For too long, outsiders have been kinda shafted when it comes to medical needs. This gives them access to a chemistry dispenser along with prospectors if they so wish at the void wolf medical facility. These were removed so everyone had to rely on soteria for their medicines, but that's not really an option for outsiders.
literally all it does is readd the chemistry dispensers to the void wolves that were removed like over a year ago.
=> Chemistry For the Outlander

code/modules/research/designs/weapon.dm, code/modules/research/nodes/combat.dm
<details>
<summary>
</summary>
<hr>
Adds 9mm pistol magazines compatible with the SI HG "Malpractice" low-power pistol to the Protolathe, allowing Soteria to use the weapon and experiment with ballistic designs in the same way as their C20r.
Specifically, this adds empty pistol magazines available by default, rubber magazines after researching basic non-lethal technology, and standard magazines after researching basic lethal weapons.
This makes the Malpractice consistent with the C20r in availability with empty, basic, and rubber smg ammo designs being available in the protolathe, and hopefully encourages early-game use of the often-forgotten Soteria knock-off pistol among Soteria personnel for defense and experimenting with the ballistic mod combinations available …
=> Fixes Protolathe Munitions

code/modules/reagents/reagent_containers/food/snacks.dm
<details>
<summary>
Fixes slices of food not having the quality of the sliced food
</summary>
<hr>
Slice-able food has a variable slice_path. For example "/obj/item/reagent_containers/food/snacks/plaincakeslice" for "/obj/item/reagent_containers/food/snacks/sliceable/plaincake". When slicing, a new object of that given type is created for each slice. As I understand it, right after slicing, it was attempted to alter the food_quality variable of *the path* of the newly created object instead of the object itself.
Fixes #4623, thanks for finding the troublesome code lines! 
<hr>
</details>
:cl: dutop
fix: Slices of slice-able food items get the same quality as the food item itself.
/:cl:
=> fix #4623 - Use created object instead of object type

code/modules/economy/cash_register.dm
<details>
<summary>
fix cash register custom orders
add ability to change prices
</summary>
<hr>
Today's episode of "Things no one will ever notice":
When adding custom orders in the cash register, each item is shown with 0 Credits, although the total transaction amount will be updated. The code used two lists with named items, but the part about custom orders used them as simple lists. So instead of an item (item 1, name Apple, value 1) we had (item 1, Apple). Later calculations were doomed to fail (An apple costs 3 credits, so Apple times three is ... bullshit, to be honest. 1 times three works better). Same thing with the prices list.
By fixing the way items are added to these lists, another feature is working (again?): In one line, the amount of items to be bought can be changed. This …
=> Cash register: fix custom orders, make price changeable

code/modules/clothing/spacesuits/void/excelsior.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
**-Changelog-**
Changed Excel void suit to reflect it's description and make it less of a juggernaut suit made by the gods.
(Requires additional material to craft /&/ Better energy protection, less melee and rad with average Ballistic; with added weight as it's a pretty beefy bomb suit for a full void suit)
Seems the experience i've seen is that even a lone Excel agent can 1v5 the colony with this armor, although it's expected that the excel agent is to be fighting an uphill battle. This will hopefully make them less reliant on going full "nuke-ops war mode" every time they play. Y'all got traps and other fun toys to play with before choosing a gun. After all a dead colonist is a terrible slave for implants of the glorious revolution!.
Reduced excel slave meat drop from 4 to 1 to reduce …
=> Excel armor stat change and mob tweaks

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
**Removed extra PunPun
Set CEO bedroom to same area as CEO office.
Fixed Dorm signs
fixed vent Issue in Guildmaster office and removed extra wall tile.
Fixed Sauna's wall issue
Added light switches to dorms missing them
Maint doors by dorms are now powered
Added in protection obelisks to other dorms and above fireplace**
(my previous map PR fixed #4615 and fixed #4611  )
=> Minor map fixes

code/__HELPERS/time.dm
<details>
<summary>
Fix the display of the expiration time in guest passes
</summary>
<hr>
The variable expiration_time is set to world.time + the duration the guest pass is supposed to be valid. That is correct and the guest pass is valid for the given time. But when examining the guest pass, an incorrect expiration time is shown. This leads to "The guest pass expired at XXX", where XXX is two minutes in the future.
The reason is in the display method worldtime2stationtime. It does not consider that there's a difference between the world start time and the round start time. Subtracting the round start time (in round_start_time) fixes this issue.
This change also affects the autopsy scanner and a display at round end showing when an event started.
fixes #4666 
<hr>
</details>
:cl: dutop …
=> Error in calculation of station time, fix #4666

code/modules/clothing/underwear/base.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/stripping.dm
<details>
<summary>
Enable removing other's underwear, comparable to other clothing items.
</summary>
<hr>
This is not an ERP mechanics change! Possible correlations to my own presumed fetishes are coincidental and not intended! That made it worse, didn't it? My intentions for this change were:
- you can add underwear to another (appropriate) naked mob by just clicking on it. But there is no way to get it back.
- Performing an autopsy (or a full-body-surgery) on a player who will continue wearing their underwear seems unrealistic to me (immershionnn!)
- All clothing can be removed, but not underwear. Seems inconsistent to me.
Yes, it can be used for ERP and non-con RP, but this mechanic won't change anything about IC or OOC laws/rules. An admin-attack-log entry is performed.
In the …
=> Enable removing other's underwear, comparable to other clothing items.

maps/Centcom/map/centcom.dmm
<details>
<summary>
</summary>
<hr>
Decided that the space base needed a few small changes to spice it up a bit for anyone that ever wanted to use the "Merc" antag slot. Made it more voidwolf like and added in a few small rooms with useful machines for event runners.
<hr>
</details>
:cl:
fixes up the merc compound at centcom map for antag use. Adds in some voiddwolf scaf suits along with RNG mech and a chem lab. Secret-ish uplink for funs add as well.
:cl:
=> Merc space base update

code/game/objects/items/weapons/tools/_tools.dm, code/modules/power/cable.dm
Fun fact; Prosthetics did NOT follow the usual code that would cause a limb to regenerate its damage_mask after being fixed(say, with a welder.).
This pr does *not* fix this underlying issue, it does however provide a band-aid to resolve the symptoms of said problem via a forced icon update whenever using a tool with the welding quality, or a cable length to repair a synth.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Small lil bandaid.

code/modules/psionics/psion.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Increases Psion Regen
Tweak: Changes Psion Regen based on COG from 0.2 to 0.5, and lowers base Regen from 10 minutes to 5 minutes.  Formula has been changed to reflect, and will only allow up to a maximum of 3 minutes removed at high COG. e.g.
Small COG(10): Regen is 5-4.5 minutes per point with about 1-2 psi points Large COG(100): Regen is 2 minutes per point with about 10-12 psi points
QoL
These values can easily be tweaked.  Tested for speed and still feels slow, but more balanced to let a psionic recharge faster if they're focusing Cog.  Allows non-Soteria focused psions to have an easier time regen without Cerebrix.
/:cl:
=> Psion Regen Increase

code/modules/projectiles/projectile/bullettypes.dm
Biomass bullets were still using toxins damage which. Not really a valid damage type anymore.  Adjusts it to be burn, because like....duh?
closes #4713
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fixes caustic bullets

code/game/objects/structures/janicart.dm
<details>
<summary>
Updates the icon of the mop bucket in a janitor cart when it goes empty
</summary>
<hr>
When water is removed from a mop bucket while it is attached to a janitorial cart, the icon will be updated. If the bucket is empty, it will show the empty bucket.
A similar fix was done for the mop bucket when it is _not_ attached to a cart.
<hr>
</details>
:cl: dutop
fix: Show empty bucket icon when taking the last water from bucket in janitorial cart
/:cl:
=> fixes #4690: update icon of mop bucket in cart when it goes empty

code/modules/client/preference_setup/loadout/lists/belt.dm, code/modules/clothing/suits/armor.dm, code/modules/psionics/psionic_items/psi_Larmor.dm, code/modules/reagents/reagents/drugs.dm
Cigarettes no longer(seem to) cause kidney damage to people with unclean living.
psion void armor has correct slowdown Additionally, no longer allows ears to flop outside of it. It's a fucking space suit, why would they be out?
Opifex medbelt no longer selectable, sorry powergamers.
Removes change_appearance from baseline armor vest. Why? It is the parent to MANY MANY MANY fucking items and thus caused MANY MANY MANY items to have erronious change_appearance procs that only had two options for the base parent item. This is why we don't put fucking procs on BASE PARENT items that affect DOZENS of other items. Fixes a few others, WO plate has no unique sprite and now has a proper working change appearance. CO does have a unique sprite, it is gone.
Fixes #4732
Fixes #4734
fixes #4724 …
=> Im so sick of bugs.

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
<details>
<summary>
</summary>
<hr>
For some reason, the combat role gets free shock-proof work gloves instead of the role that might actually need them for digging through trash piles. This fixes the problem.
<hr>
</details>
:cl:
fix: Salvagers now get combat gloves in their lockers, for safely digging through trash.
/:cl:
=> Gives salvagers combat gloves in their locker

code/datums/contract.dm, code/modules/clothing/suits/armor.dm
All the suit/storage/vest children lacked QUALITY_ARMOR making them unable to be upgraded even when they should be. Fixed.
faulty antag objective to get a 'CEO jumpsuit' now properly indicates that it wants the guildmasters jumpsuit.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> small bugfixes

code/game/objects/items/weapons/storage/deferred.dm
storage set their own inventory size/max itm size based on what's in them, cool right? Well, this means things like the tool-mods kit from lonestar is the most potent storage item ever because it comes with 12 normal size slots. They can now only hold the kinda items they come with, I'm very likely missing some stuff but oh well.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> PROBABLY fixes certain deferred boxes being an obnoxious meme.

code/game/objects/items/weapons/storage/lunchbox.dm
<details>
<summary>
Enable spoons, forks and knives in lunchboxes
</summary>
<hr>
Spoons, forks and knives should fit in a lunchbox, so you don't have to eat your steak like an animal. As we don't have dinner knives / menu knives and _every_ knife is based on the kitchen knife, this means that every knife works. Other kitchen tools are not allowed.
<hr>
</details>
:cl: dutop
add: Allow spoons, forks and knives in lunchboxes.
/:cl:
=> Enable spoons, forks and knives in lunchboxes

code/modules/mob/living/bot/farmbot.dm
<details>
<summary>
Add option to disable the farmbot speaker
</summary>
<hr>
The options menu that can be accessed by pulling your ID through the farmbot, gets a new option to disable the speaker. No sound is played, no text is spoken. The texts describing the actions (...starts to harvest, ... harvested) stay. But the text spam stops. This is comparable to the vendors who can get their speaker disabled.
<hr>
</details>
:cl: dutop
tweak: Add option to disable the farmbot speaker
/:cl:
=> Add option to disable the farmbot speaker

code/game/gamemodes/events/blob.dm, code/game/gamemodes/events/hivemind_invasion.dm
Reduces total 'combat related' players required to spawn either blob or Hivemind.
Hiveminds now require 7 players.
Blob now requires 4 players.
See below for the list of jobs that count for this requirement. Why does Premier count??
``#define JOBS_ANTI_HIVEMIND "Blackshield Commander","Warrant Officer","Supply Specialist","Ranger","Corpsman","Blackshield Trooper","Marshal Officer","Sergeant","Prime","Vector","Foreman","Salvager","Prospector","Premier","Steward","AI","Janitor","Soteria Lifeline Technician","Soteria Roboticist","Lonestar Miner" ``
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Hivemind - per emojiocracy vote.

code/game/objects/structures/crates_lockers/closets/maint_loot.dm
This isn't a balancing act, this is potentially something that's going to remove a lot of lag, given the amount of loot lockers on the map, this would likely remove hundreds if not thousands of mobs that usually would not be interacted with by the players at all.
=> removing roaches from maint lockers

code/__DEFINES/jobs.dm, code/datums/outfits/jobs/civilian.dm, code/game/jobs/department.dm, code/game/jobs/job/avisitor.dm, code/game/jobs/jobs.dm, code/game/objects/items/weapons/cards_ids.dm, code/modules/multiz/map_data.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm, sojourn-station.dme
Visitor role is back, however this time it is not simply an alt-title for colonists. They spawn with a 0 access , 'official' guest pass that shows they have the right to be there. Mind you, they are STILL visitors they are STILL subject to all the usual rules for visitors. any crimes they commit can result in ejection and they generally should stick to main areas - but this should help the longtime issue of new players choosing outsider to introduce their 'foreigner' character and promptly dying dead-ly.
Also rename the dept for colonists/visitors from 'contractors' to 'Independents'.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Visitor update.

code/modules/projectiles/projectile/bullettypes.dm
Peacekeeper/Abdicator buckshot has postpen damagemult. Essentially, against 'soft' targets(no armor/low armor) it'll do 50% extra damage, this will probably get nerfed but for now we'll see, these two items are expensive and relatively rare.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> postpen for abdicator/Peacekeeper

code/game/objects/structures/bedsheet_bin.dm, code/modules/clothing/underwear/base.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Adds a linen bin (bedsheetbin in code) to the Janitor closet. Enables the linen bin to contain double-sized bedsheets
</summary>
<hr>
I simply wanted to add a linen bin to the Janitor closet, to be able to change the bed sheets in Dorms. Collecting all sheets, washing them and returning them is just not great, as it leaves the beds uncovered! Having no spares sucks, as well, because maybe someone needed a bedsheet to cover up a shivering friend somewhere.
Problem: The linen bin does only provide single bed sheets, while the beds in the dorms are double-sized. So I simply added a var "double" that defines the bin as a bin for double-sized bedsheets. Default is FALSE. Var can be set in map. Description of linen bin shows if it's loaded with double sheets or not. Tested …
=> Add linen bin to Janitor closet

code/modules/projectiles/guns/energy/laser/abdicator.dm, code/modules/projectiles/guns/energy/laser/peacekeeper.dm
Blacklists unmaker from the abdicator and raises recoil from 0.3(handgun) to 1.0(carbine) to be more in line with the other energy shotgun
peacekeeper given 15 fire delay(from 20)
Also removes a deprecated and misleading part of the peacekeepers desc saying it burned out cells(it dont)
probably fixes the abdicators grenade mode
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> some energy shotgun changes.

code/modules/mob/living/silicon/robot/robot.dm
Suffer not the non-AA carbon rattling keys at a door. The AA tallborg will handle it all.
=> Fixes janitor borg icons

maps/_DeepForest/map/_Deep_Forest.dmm
Erases a sad attempt at a dungeon and replaces it with this Excelsior Fortress.
UPDATE: Found the issue, that's on me. #4791 
So earlier today I found this... thing in the Deep Forest underground.
This was going to be removed in a few hours because it was a disgusting carcass. Which is why I attempted to revamp it into a fully fledged dungeon for you all to enjoy.
The dungeon is consisting of Excelsior troops, one big OKB-01 boss and a load of goodies for players to enjoy. This is mainly for mid/late game prospies and outsiders to have a pry at due to it's inhabitant's ability to sweep ass.
There are some slight additions to some items/mobs which are basically the same one with different flavour text and health. For instance, the 'Communist Manifesto' can be found …
=> Addon - Excel Fortress (Fixed maybe)

code/datums/setup_option/backgrounds/origin_synthetic.dm
Removes restrictions on synthetic backgrounds for outsiders. We allow synths to be outsiders....but don't bother to let them actually have their background options? Weird.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Removes background restrictions for synthetic outsiders

code/game/objects/structures/bedsheet_bin.dm
<details>
<summary>
When putting a bedsheet on a bed, remove pixel shift
</summary>
<hr>
If you put a folded bedsheet on a table, the bedsheet will be put to the location on the table where the click was located (pixel shift). This shift will be stored in the bedsheet object. When that folded bedsheet is put on a bed, this shift is used again and the bedsheet lands at a ridiculous location. This is solved by re-setting the pixel_x, y, z and w variables to zero when unfolding the sheet.
<hr>
</details>
:cl: dutop
fix: Remove pixel shift when putting bedsheets
/:cl:
=> When putting a bedsheet on a bed, remove pixel shift

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
:cl:
Added a box of Spare ids in the premiers room. Seems the last premier forgot to put it back up on their table when it was knocked off during their last drink. Goofy thing was **under the table**. 
*SMH*
:cl:
=> Joseph atton found the ids!

code/modules/mob/living/bot/farmbot.dm, code/modules/surgery/surgery.dm
Self surgery is now 12.5% harder for organics and 50% harder for robots.
Self surgery is now 50% easier for Cht'Mants
Fixes; Farmbots putting ammonia into hydroponics trays along with water, thus creating space cleaner. Fertilizing now uses ez nutrient.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> balances self surgery + fixes farmbots

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Ided 
</summary>
<hr>
Modifies the garden and scrap beacon conveyors to disposals, removing the windoor and adding instead plastic flaps. This will prevent people accidentally going down it.
<hr>
</details>
:cl: SingingSpock
add: Plastic flaps added to conveyors to disposals
/:cl:
=> Puts plastic flaps in front of disposal conveyors

modular_sojourn/spaceleak.dm
Makes leaking bluespace no longer guarantee positive breakdowns. Still abuseable tbh but you'll be bruteforcing negative breakdowns to get positive ones.
Port of: https://github.com/Liberty-Landing/Liberty-Station-13/pull/375
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> bugfix for leaking bluespace

code/modules/clothing/suits/miscellaneous.dm, code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
Removes unique allowed items list for slings and Expedition suits. This making it default to what all overwear use (vests, jackets, etc). This was just....odd and unnecessary.
Also technically fixes a small bug allowing it to hold /obj/item/storage/box it being able to do so made some very odd sprite related things involving becoming a massive cardboard box. Switches the sling to use a extra_allowed list to retain it's niche use cases on the bases that it has no armor values.
Flat out buff to the Expedition suit but needs it....it's easily one of the worst bits of ''armor'' in the game.
Fixes #4728
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> more consistent overwear

code/datums/setup_option/backgrounds/origin_chtmant.dm, code/datums/setup_option/backgrounds/origin_synthetic.dm, code/datums/setup_option/core_implants.dm, code/game/jobs/job/church.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm
Lotta little changes so might miss something here but.
The Church has now FINALLY permitted unbranded and standard FBPs to join the fold and work directly for the Church. Department synthetics are still as they where due to security concerns.
SI is now willing to outsource robotics work to guild synthetics. Guild in return has also permitted SI engineering synths to work with them.
Lonestar is now willing to allow church synthetics to work in mining. Buffs the ''Depts-Class'' Guild synth background robustness by 5 points to not make them redundant in mining (same as the highest robustness church synth background their implant sucks anyways tbh). Fixes what I assume to be a spelling mistake. ''Depts-Class'' is now Depths-Class
Blackshield has now permitted SI synthetics to work as corpsman …
=> Tweaks to job restrictions (mostly for synths)

code/modules/projectiles/guns/projectile/automatic/mac.dm
This is an actual fix of the croon. To put it simply, this weapon from eye cybermancy meant to have a firerate similar to a minigun in a small package had been badly coded, the person who tried to make it fire fast actually only modified fire_delay, but that has little effect on the actual tested firerate of the gun, instead, now, I make it use burst_delay, which ironically full auto weapons use to regulate their firerate more precisely.  It used to have the firerate of any regular SMG, now, it's actually the gun it was meant to be. The little damage value of the gun means it's still a rare and not really viable SMG, but now the weapon is actually cool to use.
Not only this, but before, the firemodes of the weapon were also scuffed, you only had fuller auto and.. fuller auto. Now there's …
=> Fixing the croon's firerate (using burst delay instead of fire_delay).dm

code/modules/mining/drilling/drill.dm, code/modules/mining/drilling/termite_burrow.dm, code/modules/mining/drilling/termite_wave.dm
Ports : https://github.com/Liberty-Landing/Liberty-Station-13/pull/363
does not port the map changes because duh.
Drill heads now have a verb to configure their internal "Seismic Stimulator" in order to intentionally provoke or bait larger termite swarms, this does not let you lower their aggression, only increase it if desired.
Drill heads now fully excavate an entire tile before selecting another random tile in their range.
Drill head's base mining speed has doubled.
Termite burrows are not dense anymore, but have lost the ability to be destroyed by force, they only dissapear when the drill is stopped and the termite waves cease.
Termite waves' downtime between waves and new burrows spawned has been decreased.
<details>
<summary>
</summary>
<hr>
<hr>
</details> …
=> Liberty drill port.

code/datums/autolathe/circuits.dm, code/game/machinery/kitchen/smartfridge.dm, code/game/objects/items/weapons/autolathe_disk/guild_disks.dm, code/game/objects/items/weapons/circuitboards/machinery/smartfridge.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm, sojourn-station.dme
<details>
<summary>
Adds a disk storage machine
</summary>
<hr>
Adds a subtype of smartfridge that holds disks, and maps them in at the places where a table/rack that held a faction's disks used to be, as well as the public lathe. More can be made with a board found on the Guild Circuits disk. Also adds the ability to make regular smartfridges for good measure, since those couldn't be made previously.
<hr>
</details>
:cl:
add: New disk storage fridges
/:cl:
=> Adds the disk storage fridge

code/modules/mob/living/carbon/human/emote.dm
~~Switches emote sound effects to work off gender identity rather then true gender. Also fixes and cleans up the highly scuffed code used for *urah. Why why was it like this. Thanks to Trilby for helping me figure this madness out. Tested pretty thoroughly should be all set. _I hope._~~ 
Fixes *Urah not working for some cases of gender choices making it function the same as all other emotes code wise.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fixes/cleans up Urah emote code

code/modules/mob/new_player/new_player.dm
Slightly adjusts the warning message when attempting to join the round with no records to clarify that records are required for COLONIST roles, not hunters outsiders or visitors
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> updates non-records warning

code/modules/projectiles/guns/projectile/automatic/mamba.dm
Small PR. Makes the mamba a normal sized item when folded. Why was this gun the same size as the average baggable rifle? Defeats the point of a folding stock.
Makes the copperhead no longer fit in a backpack at CDBs request.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> marshi gun tweaks

code/game/machinery/vendor/recycle_vendor.dm
<details>
<summary>
When using the recycling vendor, consider stacks of materials.
</summary>
<hr>
When you are using the recycling vendor and add a stack of materials, for example a stack of five plasma cubes, you will get the price of _one_ cube and _one_ cube will be stored into the vendor's storage. To circumvent that, you have to pop one item from the stack, put it in the vendor, click recycle, pop the next one, ... That sucks.
Now the code checks for material stacks. If the object hat has been shoved into the vendor is a stack, the amount is considered. The value is multiplied, the amount added to the internal storage as well.
Here, have a before/after of adding a stack of five plasma crystals. Everyone loves before/afters.
<hr>
</details>
:cl: dutop
fix: Consider stacks in …
=> Recycling vendor: consider stacks of materials in payout and storage

code/game/objects/items/weapons/material/knives.dm, code/game/objects/items/weapons/tools/knifes_daggers.dm, code/modules/mob/living/damage_procs.dm
ports https://github.com/Liberty-Landing/Liberty-Station-13/pull/531
>Backstabbing in alt mode is now properly LTL
>Fixes backstabbing with closed knifes no longer works
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> cat tribute

code/modules/client/preference_setup/loadout/lists/accessories.dm, code/modules/client/preference_setup/loadout/lists/general.dm
<details>
<summary>
Just what it says on the tin. Only subtypes of /obj/item/clothing/accessory should be in the accessories loadout or they cause runtimes when they try to attach
</summary>
<hr>
<hr>
</details>
:cl:
Moves wallet from accessories to general loadout to stop runtimes
/:cl:
=> Moves wallet to general loadout to stop runtimes

code/datums/perks/backgrounds.dm, code/modules/sanity/inspiration_component.dm
<details>
<summary>
Stops the heirloom weapon from runtiming when it tries to add a perk. Also rebalances the system
</summary>
<hr>
Balance changes: shifts the pickweight list to favor useable-but-not-great weapons within a group and makes the oddity picker choose from the good oddity list so people don't wind up shooting themselves in the foot while meditating on their heirloom. Adjusts how the NT weapons are selected for disciples.
<hr>
</details>
:cl:
fix: Heirloom weapons will have a good perk and no longer runtime
change: Rebalanced heirloom pickweight list
/:cl:
=> Heirloom weapon fix and balance

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Adds an escape pathway for Command in the bunker, so it's not a deathtrap when attacked
</summary>
<hr>
Adds a simple ladder from the north part of the panic bunker to security's garden area. 
The red circled airlock has access for command or security, the green circled airlock only has access for command. This allows security to pour in to defend the bunker if necessary but doesn't give them access to the bridge.
<hr>
</details>
:cl:
map: added an emergency exit to Command's panic bunker so they don't get trapped in it.
/:cl:
=> Gives the Command panic bunker an exit to Security

code/game/objects/items/weapons/cigs_lighters.dm, code/game/objects/items/weapons/storage/fancy.dm
<details>
<summary>
This will be changing the Kitsuhana Singularity cigarette's to no longer be a direct attack towards Virgo's code and lore while giving it a more aesthetically pleasing look.
</summary>
<hr>
It had come to my attention that the Kitsuhana Singularity cigarettes were created **intentionally and exclusively** to attack Virgo's lore as Kitsuhana is a big name in the Virgo codebase and server. Given the context, I believe that this is not only a low blow, but outright childish of a coder to be doing with Sojourn's codebase. While I cannot change the sprite as I do not know how to sprite, I am requesting that we consider changing these to something else, my idea is that it should be something relating more in line with a hippie van that lives on the beaches. Like beach bums …
=> Removing Possum's Shit Code

code/__HELPERS/time.dm
<details>
<summary>
Makes the start time of each round be the server's time, rounded to the nearest hour. A couple other procs are added for testing or getting the time.
</summary>
<hr>
<hr>
</details>
:cl:
Rounds now start at the time on the server box, rounded to the nearest hour, so time actually progresses between shifts
/:cl:
=> Makes the IC start time the server time, rounded to the nearest hour

code/modules/mob/living/carbon/superior_animal/human/subtype/eventwolf/eventwolf, code/modules/mob/living/carbon/superior_animal/human/subtype/eventwolf/eventwolf.dm
The Eventwolves aren't meant to be in-game due to their general power and ability to fuck-shit-up. As such, these will be seen in events such as raids or similar.
> Marauders are high health high damage, used with other melee voidwolves to break into lines and do damage. 
> Suicide bombers are weak, but explode on impact. Great for breaching into places, _like colony defences_. (Basically the boomba with a different sprite.)
=> Creates the Eventwolf

code/modules/projectiles/gun.dm, maps/__Nadezhda/area/_Nadezhda_areas.dm
Finally figured this one out. Prevents cap guns and cham guns from letting you commit suicide. 
Minor map area bug fix: fixes #4901 lodge was getting incorrectly defined as a maint area via it's parent 
tested and works.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> prevents harmless guns from harming you. + lodge fix

code/datums/perks/backgrounds.dm, code/datums/perks/racial.dm, code/modules/mob/language/outsider.dm
Title. Makes several racial languages available for selection in theory. Namely, Kriosan, Akula, and Naramad. Mar'Qua, Cht'Mant and Opifexee were left out due to a variety of factors - being generally unspeakable by non-members, being integrated, or just being generally unspeakable.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Removes the restricted tag from several languages.

code/modules/projectiles/projectile/beams.dm, code/modules/projectiles/projectile/energy.dm
Taser beam has lost its AP, the combination of hitscan, commonality and pain damage makes me think it really...doesnt deserve AP.
Electrode bolt(such as those used by the counselor and zeus.) which DIDN't have AP have been given the AP that taser beams had, they are slower and a bit harder to use - and giiven that they fit the 'heavy big boy stuns, this seems fiine'.
Stunbolts(as used by the counselors big boy fire mode and shotgun stunslugs) have the above +20 ap, though I mused on giving them extra in light of how limited these shots tend to be, but for now just 20AP.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Taser changes.

code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm, code/modules/projectiles/guns/energy/laser/concilium.dm
Updated the concilium lasMG disk to have large cells instead of medium cells since they were reworked to use large.
Removed a warhammer 40k reference on the concilium lasMG fire modes.
=> Las mg fix

code/modules/psionics/psion_powers/healing_powers.dm
<details>
<summary>
Makes the psionic food power now give some burns rather than take your blood, changes the amount, and reflavors it
</summary>
<hr>
Psychosomatic Transference is renamed Psychosomatic Fullness, and is flavored as convincing your stomach it's not actually that hungry (which fits the actual meaning of the word psychosomatic). Changed it to give +100 nutrition rather than just setting your nutrition to 400. This is twice as strong as Soul Hunger, but given that 1 psi point is a bigger expenditure than 20 faith and this has a stronger downside I think it's fine. Gave it 10 burn damage (5 with Psi Attunement) rather than costing blood, because the blood cost would almost instantly negate the nutrition gain if you didn't have Attunement. Shouldn't run into the problem Church …
=> Psionic food power now burns rather than takes blood, also reflavored

code/game/machinery/vendor/one_star_vending.dm, code/modules/clothing/spacesuits/rig/suits/combat.dm, code/modules/clothing/spacesuits/rig/suits/light.dm, code/modules/clothing/spacesuits/rig/suits/station.dm, code/modules/nanogate/nanogate_items.dm, code/modules/power/apc.dm
starting with the small stuff: 
the greysons Star traders vender no longer gives out free **genuine** greyson coats. Now giving the star traders version at cost.
The guild APC disturbance objective now works. Trilby helped me with this one thanks. The one where you need to go power down a APC in a area (mostly). There is still a issue related to this objective selecting areas that don't exist on map. I will try and fix this later but the files I think are the problem are locked up currently. 
RIG stuff:
Goes through I believe every single RIG and standardizes their naming there should be no more weirdness of a ''hussar RIG hussar hardsuit boots'' across all RIGs. I did not test every single suit but it _should_ be fine I checked a fair few. 
The nanite RIG has been giving 100 rad …
=> RIG weirdness, star trader and objective bug fixs

code/datums/craft/recipes/airlocks.dm, code/modules/mob/living/silicon/robot/gripper.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
Finally allows both research and medical borgs to partake in genetics via the medical gripper. Can hold plates, injecters and purgers.
Fixes a small pathing issue I made with the paperwork gripper. Can now grip ALL types of data disks. 
Good news anyone can now craft airlocks and it is no longer (Weirdly) bound to the guild handyman perk. Bad news! Drones have lost the handyman perk and by extent AIs can no longer produce guild hand made products. This was not something I was intending to allow when buffing the engineering borgs omnitool.
I tested this pretty well. Nothing _should_ go weird and maint drones should still be able to pass every skillcheck they need 
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> more borg QOL tweaks and airlocks to the people

code/game/objects/effects/spawners/ghostroles.dm
<details>
<summary>
The admin Excel spawners now actually has an implant. Also, the armored one has stats and perks now
</summary>
<hr>
Adds code to make the Excel spawners actually give the individual the Excel implant. Also makes the armored one a child of the original so it gets the perks, and gives them a decently beefy stat set fit for an antag.	
<hr>
</details>
:cl:
Fix: Makes admin-spawned Excel actually have an implant
/:cl:
=> Makes Excel Spawners actually give you the implant, buffs armored Excel

code/modules/projectiles/guns/oddity_items.dm, code/modules/projectiles/guns/projectile/boltgun/flaregun.dm, code/modules/projectiles/guns/projectile/revolver/breakaction.dm, code/modules/projectiles/guns/projectile/revolver/lemant.dm
most likely fixes the last of the de-constructable frameless weapons. Being the Pilgrim, Frontier, Cowboy and the many blue cross weapons that needed it. Turns out flare guns could be turned into mosins as well. Funny but not anymore.
intentionally leaves the Maxim out of this since I could see someone taking the parts that make it safe out of it like a dumbass
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> fixes hopefully the last of frameless weapons.

code/modules/mob/living/living_defense.dm
No more splint memes. Splints now break off when the limb they're attached to gets damaged. A full port of : https://github.com/discordia-space/CEV-Eris/pull/6786, thanks fella.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Breakable splints, brought 2 u by kegdo ft. "CDB ruins the game". 

code/game/machinery/computer/guestpass.dm
comments out a few lines of code making guest pass computers default to deselected rather then all selected. 90% of the time this is used for letting outsiders in meaning no access! On the off time its not better to opt in to access then forget somewhere important opting out of access . Gone are the days of commanders giving a outsider access to the armory! (as funny as it was)
Tested and works
Super short changelog without long winded explanation and reasoning to appease CDB: 
comments out a few lines of code making guest pass computers default to all deselected rather then all selected. No real balance implications just QOL many have asked for/complained about.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> senseable guest passes

code/__HELPERS/bluespace_entropy.dm, code/game/objects/items/weapons/teleportation.dm, code/game/objects/items/weapons/tools/simple_weapons.dm
Makes the machete contain 15 steel rather then 15 plasteel fixing a exploit involving guild crafting.
Fixes the NT BSD "Jumper" aka handtele not working in most off-colony zlevels. To my surprise this is actually unintended as far as I'm aware.
Fixes items existing in nullspace being able to create entropy. Only real example of this being the bluespace trade vender. Should be less ooooppps 300 entropy. (trilby did all the work I just found the issue and tested her fix)
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> machete exploit/handtele fix

code/game/objects/items/weapons/nt_melee.dm, code/game/objects/items/weapons/storage/belt.dm
long needed look at of church melee weapons. I may do more I may call it good here. Input is welcome from anyone in terms of what needs changing.
So far changes are as follows:
Both church belts can now hold the church shortsword. Making it have a place as a effective backup melee.
The warhammer now has bonus structural damage idk why it never had such.
The NT spear has had its god damn 50! AP reduced to 30 making it no longer the best PVE church melee.
The Vexilar force blade has had its active time doubled. The most expensive church melee should likely not just be a gimmick. Around 12 seconds or so but mileage may vary with tickrate as usual.
=> church melee balance

code/game/objects/items/weapons/storage/hardcases.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm
<details>
<summary>
Adds the Ostwind to the Warrant Officer's primary weapon choices, and adds an ammo pouch to their locker
</summary>
<hr>
Currently WOs have two options, whereas the lower ranks get three. Those two options are a DMR and a pump-action shotgun, which fill two different niches, but they don't have a burst-fire option. The Ostwind's a pretty solid gun and its description denotes it as a high-end police carbine. 6.5mm isn't the strongest caliber, but with that comes a low propensity for overpenetration, which is useful for if you might need to fire into an area with others. They get 2 standard carbine mags and one pepperball mag with it. Also adds an ammo pouch to their locker, since unlike other roles they don't get a box that holds it when they spawn their weapon.
<hr> …
=> Adds Ostwind to WO primary selection and gives them an ammo pouch

code/game/machinery/adv_med.dm, code/game/objects/items/devices/organ_module/active/armblades.dm, code/game/objects/items/weapons/implant/implanter.dm, code/game/objects/items/weapons/implant/implants/generic.dm, code/game/objects/items/weapons/implant/implants/tracking.dm, code/modules/client/preference_setup/loadout/lists/general.dm, code/modules/psionics/psion.dm, sojourn-station.dme
<details>
<summary>
Adds generic implant to loadout you can give custom name to, it will show up on adv medical scanner for that extra RP, makes any implants one might have in their medical records A REALITY !!!
<br><br>
For easier implanting of those generic (and in the future others ???) implants the currently avabile tracking implanter in loadout has been split into a empty implanter and a loose tracking implant for the same combined price as before.
<br><br>
Additionally gives adv medical scanners ability to detect common cybernetics like razor boy/girl upbringing claws.
<br><br>
And yes /obj/item/implant/excelsior still properly shows up as death implant on adv medical scanners.
</summary>
</details>
:cl:
add: Added generic implant to loadout, you can rename it so that whatever you …
=> Adds generic implant and known_cybernetics to adv medscanner

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
After formal complaints related to recent advancements in teleporter technology miniaturized bluespace inhibitors have now been distributed across the relevant colony areas.  Courtesy of and at the cost of Soteria Research in the following areas:
Nearly all armories, command panic room, Premiers office, the Lonestar vault, AI core and upload.
The Church of the Absolute has refused to except installation of one in the Primes office regardless of the valuables contained in there. (talked to Spock. Says church would proly be to petty to take one.)
SI research once again reiterates these devices do not prevent use of teleporter technology only reduce its effectiveness significantly. So please do not complain about them failing to outright prevent it.
=> maps in my mini-inhibitors (AKA nerfing myself)

maps/__Nadezhda/area/_Nadezhda_areas.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Adjusts the areas for most maintenance sections so that they correctly name the floor.
</summary>
<hr>
For some reason, most of our maintenance areas on level 2 are labeled as being level 1. This fixes that, and adds new APCs to areas that need them. Additionally adds an APC to the maints area east of security since it had none at all before.	
<hr>
</details>
:cl:
tweak: Changes the areas of much of maintenance, especially Floor 2
/:cl:
=> Makes maintenance areas make sense

code/datums/autolathe/guns.dm, code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm, code/modules/core_implant/cruciform/rituals/construction.dm, code/modules/projectiles/guns/energy/laser/concilium.dm, code/modules/projectiles/guns/energy/laser/laser.dm, code/modules/projectiles/guns/energy/plasma/plasma.dm, code/modules/projectiles/guns/energy/projectile/railgun.dm, code/modules/psionics/psionic_items/psi_weptools.dm
Bug fixes first: Fixes the Bat'ko grabbing its serial number from the lightfall
Fixes many church weapons mislabeling themselves as NT (new testament) and vice versa for OT (old testament). inside autolathes. Removes the lightfall from the OT disk. It was on both idk why. Lives on NT disk only now.
Important balance stuff: Concillium has seen well needed nerfs/fixes from my last time touching it. Fixes it incorrectly having 1 fire delay if you never change the fire mode. 
Pretty substantially reduces it's fire rate. I never wanted this to be a DPS monster and somehow it ended up that way.
It's recoil is now a factor. By no means is it bad but if you want it to be recoilless you'll be modding it or bracing it. Should discourage running and gunning as well
Ups its gold cost even more. …
=> More church gun balance and small fixes.

code/modules/psionics/psion_powers/gear_summoning_powers.dm, code/modules/psionics/psionic_items/psi_catalysts.dm, code/modules/psionics/psionic_items/psi_temp_items.dm
Psionic shields by default no longer block proj
Psionic shields now when activated again with one in hand will gain blocking for proj at the cost of 10 durably, but gain 10 more block odds
If you have more then 60 TGH (STAT_LEVEL_PROF aka Master) you will for free condense the shield as if you used an additional psionic point for free
Psionic shields if able to already block proj will gain 80 durability back + 5% more blocking odds 
New psionic shield type Layered Psionic shield, costs 1 point found in deepmaints catalysts. Blocks proj by default as well as has more max durability and armor values
=> more_layered_shielding

code/modules/reagents/reagent_containers/food/snacks.dm
Fixes the description of mercys hand tisane to accurately reference itself instead of two separate wrong fruit.
Image to show the before and after results, and that it compiles/launches.
=> Tisane description fix

code/datums/craft/recipes/guild.dm, code/game/objects/items/weapons/tools/shovel.dm
Rebalanced the crafting recipe and stats a little
<details>
<summary>
</summary>
<hr>
Added a diamond to the crafting recipe to make it more expensive. Tweaked tool qualities a smidge, that digging quality wasn't supposed to be left that high.
<hr>
</details>
:cl:
balance: Rebalanced recipe and stats a little
/:cl:
=> Crovel rebalance

code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/construction.dm, code/modules/core_implant/cruciform/rituals/crusader.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/core_implant/cruciform/rituals/priest.dm
<details>
<summary>
Lowers the price of a couple litanies, ensures all litanies return TRUE when they succeed and thus actually spend their power, and fixes a couple other minor issues
</summary>
<hr>
Lowers the price of the Canticle of Defense (divisor weapon summon litany) and Litany of Armaments (crusader weapon summon litany) from 50 to 20 and from 100 to 75 respectively. Canticle of Defense has a four hour cooldown which means it can be used at most twice in a shift anyways, and Litany of Armaments has a 12 hour cooldown, it can never be used more than once in a shift. Canticle of Defense in particular is often used (at least by me) to get some Church looking clothes and a nonlethal weapon while not on duty as a Vector, and having a 50 cost just delays getting it for several more …
=> Lowers cost of armament summoning litanies, ensures litanies consume power, couple other minor Church fixes

code/datums/craft/recipes/guild.dm, code/modules/projectiles/guns/energy/plasma/hydrogen.dm, code/modules/projectiles/guns/energy/plasma/variant.dm
Fixes the hydrogen plasma weapons missing slot_flag vars. Is that a hydrogen plasma cannon in your pocket or are you just happy to see me?
Pretty much funny thing fix. Could holster all hydrogen plasma weapons. The cannon! Included! So silly. I figure this was a oversight and unintended. Now ONLY the welder gun and hydrogen pistol can be holstered. Hydrogen cannon no longer fits in a bag as well. Only the pistol/welder can be duel wielded.
Tiny exploit fix to the guild claymore crafting recipe as well. You can no longer use it to convert steel into plasteel.
=> hydrogen plasma fixes and stuff

code/modules/genetics/mutations/bottomless_belly.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/station.dm
Bottomless Belly directly raises max nutrition by 1600
Bottomless Belly no longer statis max nutrition
Exalts now get an additional 100 max nutrition
Slimes now get an additional 150 max nutrition
=> Fixes some hunger issues

maps/__Nadezhda/area/_Nadezhda_areas.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Spider Outpost collapses into the ground, exposing the spider cave that was beneath it!
</summary>
<hr>
Replaces the spider outpost with a spider cave, which had sometimes been said to be beneath it in the past. This cave is on the Underground 1 level, and has some mineable rock that leads to the colony's maintenances. This gives the colony a second entry point via mining into maints, which is good for allowing hostile outsiders to actually do something other than die in the meadow as they fail to get into the colony proper.
I tried to balance the loot and loot types against the amount of mobs, but it might be a bit off. I tried to err on the side of less rather than the side of more.
<hr>
</details>
:cl:
map: Replaces the Spider Outpost with an underground Spider Cave …
=> Replaces the Spider Outpost with an underground Spider Cave

code/game/objects/items/weapons/storage/hardcases.dm
Pretty much improves the storage the density of specialized hard cases across the board. Generic hard cases untouched cos their already pretty epic. All my own numbers but I did look at Eris's buff to these for vague idea where to start.  Overall much better choice then filling your bag with 10 medium pouches. 
Med hard case can now hold 50% more medical stuffs. Pretty much a combat medkit with some extra room for bandages. It can also now hold _most_ Surgical tools. Become a walking medbay today.
Ammo hard cases now use slot based storage having 14 slots. They can however only hold small items. Good for 12mm enjoyers! Or those stuck using a crafting station.  Higher ammo density then most big ammo boxes just much more annoying about it.
Parts hard cases now use slot based storage. 20 …
=> Hard case storage buffing

code/modules/biomatter_manipulation/bioreactor/platform.dm
<details>
<summary>
Comments out the code that ejects the organs from carbons and dissolves them separately so they don't get absurd amounts of biomass for their size
</summary>
<hr>
Exactly what it says on the tin. Humans no longer have more biomass than Empress spiders, they've got 100
<hr>
</details>
:cl:
tweak: Humans give a reasonable amount of biomass now rather than an absurd amount
/:cl:
=> Makes carbons no longer spill their organs during bioreactor procesing and give too much biomatter

code/game/objects/structures/crates_lockers/closets/secure/engineering.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Removes the bullet fab from the GM's vault and adds a board to their locker instead
</summary>
<hr>
This should lessen the problem of regular adepts casually breaking in to grab the fab. Eventually I do hope that it's removed, but until then we can at least limit it to when there's actually a GM to set it up.
<hr>
</details>
:cl:
tweak: Removes the Guild's prebuilt bullet fab but adds a board to the GM's locker to discourage Adepts stealing it
/:cl:
=> Foreshadowing the end of an era: removes the Guild bullet fab and adds a board to GM locker

code/modules/biomatter_manipulation/bioreactor/biotank.dm, code/modules/biomatter_manipulation/solidifier.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Fixes the old bug of connecting bioreactors to solidifiers, buffs the transfer rate to canisters
</summary>
<hr>
Folks couldn't stop abusing it, so this puts a stop to it through a simple means: the port on the biomatter solidifier is now on the south side like on Eris, so you can't directly connect it to a bioreactor. This forces Church to once more use the intended method of filling canisters and solidifying them. I buffed the transfer rate of the bioreactor to canisters by 5x, though, to avoid it being **too** much of a constant chore. This should have the additional benefit of not runtiming and having the bioreactor no longer break consistently, since you're now forced to do things the right way which seems to avoid most of the errors.
Map change is just adjusting …
=> No more connecting bioreactor to solidifier, but buffs transfer rate to canisters

code/modules/clothing/accessories/accessory.dm, code/modules/mob/living/say.dm
Adds the Wanderers Armada, Kurilskaya, Marqua Homeworlds and Norian passcards in. They where lazing around in are code not being utilized and I don't believe it was intended. The sprites themselfs belong to Guidesa I believe. Attempted to give them fitting descs. I encourage anyone to give me better descs.
Fixes the general passport having no icon.
Changes the channel keys of the plasma tag channels. The old ones being 1-4 was making problems for the AI stating laws in some cases.
=> Passcard adding and tiny AI fix

code/modules/mob/living/damage_procs.dm
Radiation mod now applies to the recieved value as well as the damage recieved.
Both the gene and cindarites were no longer immune to radiation because the majority of bad effects and damage procs were moved before the actual damage reduction, likewise not counting in the other nasty effects.
Fixes issue: #4866
=> radiation mod fix

code/modules/projectiles/guns/projectile/automatic/ak47.dm
AK frame changed to no longer accept the serb (bakelite) grip as the recipe for /obj/item/gun/projectile/automatic/ak47/sa has changed to wood grips.
=> Fixes AK frame grips

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Prospectors blast door. This bug was requested from K5 in the discord. Thank you for reporting it.
This discord links you to the bug report that was reported.
https://discord.com/channels/859887473940889640/1211030604523642992/1211030604523642992
<hr>
</details>
:cl:
bug: squash prospector blast door
/:cl:
=> Map Bugfix: Prospector Blast Doors

code/game/atoms_movable.dm, code/modules/biomatter_manipulation/biogenerator.dm, code/modules/biomatter_manipulation/bioreactor/biotank.dm, code/modules/biomatter_manipulation/bioreactor/loader.dm, code/modules/biomatter_manipulation/bioreactor/platform.dm, code/modules/biomatter_manipulation/bioreactor/unloader.dm, code/modules/biomatter_manipulation/solidifier.dm, code/modules/materials/material_sheets.dm
Ports over the near current state of the bioreactor from eris while keeping most of the tweaks/buffs we added to it over the years and some of my own minor fixes. Balance impact minimal. Tested everything pretty thoroughly
Change stuff:
Bioreactor should no longer have issues with its acid overlay not appearing (hopefully)
Bioreactor should no longer lock up and cease working (hopefully)
Bioreactor now does burn damage rather then brute preventing blood from being scattered under it. It's acid why was it like this? (my change)
Bioreactor port now allows non-human mobs to be automatically inserted via the disposals belt system
Biomatter solidifier now makes 5 sheets per cycle (5x faster) removing the tedious chore of spamming down several of them (trilby helped get this working thanks …
=> Bioreactor eris update.

code/modules/mob/living/carbon/human/human.dm
So now you can see who is at the gate instead of waiting for like a two hours playing league of legends plus its the lodge "leadership" and you know whos in charge for the shift. 
Yes Trilby you can call this a cope PR if you are doing tags.
:cl:
add: Title broadcast for lodge hunt master
/:cl:
=> Title Addition: Lodge Hunt Master

code/modules/psionics/psion.dm, code/modules/psionics/psion_powers/armour_powers.dm, code/modules/psionics/psion_powers/deepmaints_themed_powers.dm, code/modules/psionics/psion_powers/faction_powers.dm, code/modules/psionics/psion_powers/gear_summoning_powers.dm, code/modules/psionics/psion_powers/healing_powers.dm, code/modules/psionics/psion_powers/locator_powers.dm, code/modules/psionics/psion_powers/mob_affecting_powers.dm, code/modules/psionics/psion_powers/oddity_powers.dm, code/modules/psionics/psion_powers/oldification_powers.dm, code/modules/psionics/psion_powers/psion_starter_powers.dm, code/modules/psionics/psion_powers/pyschiatrist_powers.dm, code/modules/psionics/psion_powers/telekinetsis_powers.dm, code/modules/psionics/psion_powers/teleporation_powers.dm
<details>
<summary>
Creates a general proc to check if a psion can use their power and implements it instead of piecemeal copy/paste code. Also misc. improvements to psionics code.
</summary>
<hr>
Reworks the normal list of checks that was in so many psion powers and condenses it to a single proc that can be called on every one. Also tries to remove synthetics and dead people from the list of potential telepathy targets. **This PR needs to be testmerged on a lowpop round because it is impossible to test telepathy on a solo server. I do not know whether this works perfectly, has no change, or completely borks telepathy.**
<hr>
</details>
:cl:
tweak: Refactors psionics to have a generalize check_possibility proc
/:cl:
=> Refactors psionic powers, plus misc. improvements

code/modules/projectiles/guns/energy/plasma/centurio_auretian.dm
The auretian was nerfed in PR #4552 by a factor of 2.5 which put it down from 20 shots down to 8.
I believe that this was an accidential nerf because the auretian is using a small cell and not a medium cell which most other guns in that PR were balanced around.
The auretian is a Soteria exclusive, high cost and research heavy weapon that is ment to act as a side arm. At the current state the sidearm is just more than useless now, it was fine before. It wasn't the greatest side arm but still a very good one to have and very much worth its investment. Not it is sadly just pure trash and a classica is more usuable than it
Edit: Fixed recoil: Auretian no longer has rifle recoil and instead handgun while the centurio recieved a recoil nerf.
The blacklist restriction that was inherented from …
=> revert auretian nerf

code/modules/hydroponics/seed.dm
Restores some old code that got replaced accidentally in pr #4243 preventing greater mutations in xenoflora from working. Credit to AIrkallaEpsilon and Trilby for talking things through to figure out problem.
=> a better fix for greatermutant not working! :D

code/modules/mob/living/carbon/human/human.dm
Basically changes Hunt Master to Huntmaster to fit in with more of the wiki and fits in more in temrs with the rest of the titles.
:cl:
Tweak: Huntmaster title
/:cl:
=> Title Tweak: Huntmaster not Hunt Master

code/game/objects/effects/decals/crayon.dm
Adds a soft cap of 200 max hp to drain spell, to keep players from becoming demi gods.
Crayon magic was supposed to be non viable to actual gear like armor or leveling.
=> drain max hp softcap

code/modules/mob/mob.dm
Adds in a cap for gaining max health thru leveling. Cap is currently set to 300 and can be easily adjusted if needed in the future.
=> Maxhp via leveling cap

code/modules/goonchat/browserassets/css/browserOutput_override.css, code/modules/mob/language/outsider.dm, code/stylesheet.dm
What this PR does is:
Brings the Opifex in line with old "Opifex" by bringing back there old syllables, which is vox, as the language states before it is basically vox, but changes the color to soft red. That way it isnt too similar to Cultist and people dont get confused between the two.;
Color has changed to red on suggested by Trilby
Rcolor has been changed from Marqua
Color: 
https://www.colorhexa.com/e96443
https://www.colorhexa.com/5ec2e7
:cl:
add: Red Opifex, Blue Marqua and "new" syllables for opifex
/:cl:
=> Language Adjustment: Opifexee

code/__DEFINES/jobs.dm, code/__HELPERS/manifest.dm, code/datums/datacore.dm, code/datums/setup_option/core_implants.dm, code/datums/topic/admin.dm, code/datums/topic/world.dm, code/game/jobs/department.dm, code/game/jobs/job/offcolony.dm, code/game/jobs/jobs.dm
What this PR does is basically seperates the outsiders and makes lodge its own "department" rather then sit with the outsiders, ontop of that basically makes the lodge appear on the manifest which should hopefully fix the pop issues and show people they are playing the game. More interactions with the colony and among other people. They arent in the network themselves, but you know. It 'should' help. 
P.S. Colony gets your records, but you can remove them on your own. So thats a you issue babe.
Thanks Trilby and Llamas who helped with this PR. ❤️ 
:cl:
add: Lodge Manifest
/:cl:
=> Faction Addition: Lodge Manifest

code/modules/projectiles/guns/energy/pulse/heavypulserifle.dm
tweak making the heavy pulse rifle (the energy one guild makes via converting a rare exosuit pulse cannon) have the same damage output per cell as a Titanic. Essentially trades fire rate and shot capacity for per shot damage compared to the las-cannon finally making it a useful (if still not very practical) gun.
=> Buffs the heavy pulse rifle

code/game/gamemodes/events/hivemind_controller.dm, code/game/objects/items/blueprints.dm, code/modules/admin/admin_verbs.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/deepmaints_psionic_controler.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/life.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm, code/modules/psionics/psion.dm, sojourn-station.dme
Blueprints cant rename deepmaints
By default disables deepmaints mobs that are locked away in deepmaints from being free to wounder the upper levels
adds in deepmaints pannel - Like hivemind pannel but for deepmaints
It allows r_fun users to toggle:
Allowing all deepmaints mobs to be free on the surface wowie
Allows the toggleing off for *all deepmaints mobs* respawning
Disabling holy tiles delay
Disabling holy tiles preventing respawning
Disabling crown of the hound and dreaming king teleport
Disabling the dreaming king from even lowing global chaos
=> psi monsters pannel + blueprint exploit fixes

code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/pray.dm
Allows event staff to use set security level as well as see Pray messages.  For event things obviously.
Note: untested due to being a pain in the butt to test such things on a private server but no reason it shouldn't be fine.
=> Pray for eventmins

code/modules/mob/living/carbon/shock.dm, code/modules/mob/living/living_defense.dm, code/modules/organs/pain.dm
Pain damage multilier now cannot exceed over 1.
This is a straight forward and simple fix to the current problem that exalts are basically unplayable when it comes to combat.
Do I think that more sensitive nerves should make you feel more pain? Maybe. The concept of nerve efficency is quite abstract and you could also argue that these nerves are "smarter" and know how to "filter" information. Being able to feel pain to an intelligent point next to still being able to feel the gentle touch of a feather.
Gameplay wise it also means that having an upgraded nerve organ will no longer be a downside which was quite counter intuitive. The extra NSA never really played that much of a benefit that would outweight the negatives.
=> cap pain multiplier from nerves

code/modules/aberrants/organs/mods/component/output.dm
Aberrent organs now stop producing reagents at 7 units. Preventing organs to fill up someones body up to 1000 units.
Edit: Chem production now scales with OD. It will stop producing at 90% of OD at its current selected target, preventing OD. Note it is still possible to OD by having it to apply to both stomach and bloodstream for double benefits as well, a good trade off. Reagents with no OD cap at 50.
=> Fix aberrant infinit reagent

code/game/machinery/excelsior/ex_turret.dm, code/game/machinery/os_portable_turret.dm, code/game/machinery/portable_turret.dm, code/game/objects/items/weapons/implant/implants/excelsior.dm, code/modules/mob/living/carbon/superior_animal/attack.dm, code/modules/mob/living/carbon/superior_animal/drone/types/roomba.dm, code/modules/projectiles/projectile.dm
IFF (Identification Friend or Foe)
This PR allows projectiles to be given the abillity to bypass friendly_to_colony people.
This abillity was then given to the artificer turret and ranged friendly mobs.
Reasoning:
After playing with both the guild turret and the handmade roomba from soteria I noticed lack of practicallity quite quickly.
The guild turrets often or not will friendly fire people by either you standing infront, or behind the enemy and since the turrets shoots in bursts, it will always overkill and shoot you again. Both the roomba suffers from this to a lesser extend but due to its nature, it is always behind you following. Sure, you can move around and manouver it infront of you but it can happen that it will shoot you still even with that 10% chance.
In both cases, if either …
=> IFF for allied mobs and unique turrets

code/game/mecha/equipment/tools/shields.dm
removal: Comments out the code related to the primes fancy personal shield icon. Its well agreed it very ugly. No one likes it. It gets in the way of everything visually. Now defaults to what all other personal shields use. Color adjusted to a church goldish yellow. Icon itself left alone and the codes still there if anyone wants to make something better please do.
Balance tweak: Ups the range of the Primes shield by 1 tile radius. The church cares about protecting their own as a whole. Not just the Prime. 
While lowering the CROs personal shield by 1 radius on the same kind of logic. SI cares more about its valuable personnel asset then everyone else lets be real. Pretty much just flipping the two.
Screenie of what dis looks like:
=> LC personal shields tweak.

code/modules/hydroponics/seed_datums.dm, code/modules/reagents/reagents/medicine.dm
Fixes two spelling mistakes in ambrosia panacea for ossisine and respirodaxon.
Adds a new xenobotany exclusive version of ossisine to xenobotany for the panacea plant, replacing its old version.
Flossisine is painless and has only 25 NSA demand.
Reasoning: I always found panacea to be in a really strange spot of it seemingly powerful on paper but barely useful in practise. Usually by the time you are done making this plant with a time investment of like 40 or 30 minutes, medical already has everything mixed and more so. Most often or not they will look at your plant, say cool and forget about it. Mass production of chems never really was its main strenght of xenobotany since medical never needed a mass production to begin with. So elevate xenobotany slightly in its use, I decided to give …
=> panacea fixes and adjustment

code/modules/organs/internal/psionic.dm, code/modules/psionics/psion_powers/healing_powers.dm
After somehow loosing track last night and talking to Trilby about mind wizard stuff there was the idea floating in the room that psions could be able to do things with pain. So theres that. Ideas were: Pain Transference, Pain Mirror and Pain Infliction.
This PR solely handles "Pain Infliction" or "powerword_pain" in code.
What it does:
If a psion gets an aggressive grab on a person they can inflict pain upon them expending two psi points. Yup. Thats it.
"But Irkalla what the fuck." 
Well if people have deep psi pools and they didn't powerlevel robustness in round to shit they invested into having said psi pools either by picking cog, cog backgrounds, psi point boosting backgrounds locking them out of more interesting choices or by being a cog heavy role which lacks robustness for grabs. …
=> Adds Pain Infliction Psionic Power

code/ATMOSPHERICS/components/unary/map_sink.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm, maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm, sojourn-station.dme
Adds two new mapper pipes to cooldown/heat up gasses and another that replaces its contents with air, allowing it to be siphoned or waste gas to be pumped inside.
Additionally 3 major map changes and few minor map fixes.
Minor fixes: breaker box name fix for science substation, added a camera for the hydroelectric turbine, removed a duplicate pipe at mountain top, added a missing wire at mountain top, fixed a connection where the main grid connected to the science grid.
Major changes: Replace the old turbine with the classic TEG. Offering more options, varierty and atmosian shenagigans to be done. Utilized the two new mapper pipes as well so we are no longer pumping into an area and a tree. And no longer using giant nitrogen tank as a heatsink which made little to no IC sense. In both …
=> Guild burn engine and extra mapping

code/modules/organs/internal/internal_organ_processes.dm
Over the past few weeks I made a silent observation where medical people would be both confused and complain about things like Peridaxon being hyperlethal, causing peoples oxyloss to skyrocket instantly with no obvious signs.
Turns out that both quickclot and peridaxon WILL kill you if injected. In both cases, rendering the chems obsolete. Medical is more content to perform surgery over using peri or simply using a bandage instead of using quickclot. Taking away the purpose of both chems.
=> CE_BLOODCLOT no longer lethal

code/game/objects/random/oddities.dm, code/modules/projectiles/guns/oddity_items.dm
The lockpick o matic has been changed from a single 99 bullet 10x24 pistol to a holster containing an endless amount of its somewhat stronger version of slaught o matics now. Same caliber with slightly better stats and the gimick that it gains a ton of throw force when running out of bullets for a short amount of time.
=> lockpick o matic rework

maps/_HunterLodge/map/_Hunting_Lodge.dmm
Fixes the wire under the Hunting Lodge Smes to be functional at round start. (Thanks goes to catto for this cause she told me what was wrong)
=> Lodge SMES Fix

code/modules/modular_computers/file_system/programs/generic/camera.dm
Adds a line to security cameras that should hopefully fix cameras along the fence not appearing in the list.
Trilby code-
=> Fenceline camera fix

code/modules/projectiles/projectile/plasma.dm
Plasmaweapon Firestack per hit reduction
The number one reason why any PVP encounter with anyone using plasma just isnt fun. Its actually also ultra boring to use if you are the user in PVP. 
So.. (X times 5+3) per firestack. The dinky soteria plasma applies already 2 stacks. Thats 13 damage per tick DOT. You can roll off 2 stacks per stop drop and roll. Reducing this to 1 cuts down the damage to 8. Still notable but gives you some more time to get the fuck out of dodge.
Worse offenders are church plasma and unbidden plasma. Those apply 4 stacks per hit and are burst fire. This is insanely lethal, stuns you with pain super fast and completely fucks any chance of counterplay. 
The firestack damage equation may need another look so less stacks (you have a little bit of burning going on your …
=> Nerfs Plasma Firestacks

code/datums/perks/racial.dm
A simple PR of lowering the Aulvaes limb regen from the insane 30 minutes to 5. This ability is not spamable anyhow due to needing 300 nutrients per use and it also is not a full heal. Also CDB kindly asked for a buff on slime limb regen in terms of a cooldown reduction.
:cl:
balance: Aulvae Limb Regen from 30 minutes down to 5. 
/:cl:
=> [Balancing] Lowers cooldown of Aulvaes limb regen

code/game/machinery/os_portable_turret.dm, code/game/objects/items/weapons/circuitboards/machinery/tesla_turret.dm
GP turrets no longer out shoot players by default
GP turrets when deconned now properly donst target players
=> GP turret fixes

code/modules/paperwork/handlabeler.dm
I enjoy putting bizarre text, emoji's and other things onto my equipment on other servers, and I think this commit will let me do so.
<summary>
Lets the people put Emoji's onto their equipment.
</summary>
<hr>
Changes the usage Sanitize name Proc for a text input to a sanitize text input on the hand labeler.
<hr>
</details>
:cl:
add: Hand Labelers now can label more then A-Z, 0-9 & -.
/:cl:
=> Allow Hand Labelers to label a wide variety of things onto equipment.

code/modules/assembly/signaler.dm
QOL improvement for all kinds of singalers for all kinds of assemblies
This adds a method of transferring frequency and code from one remote to another. Click with the active remote on the other signaler. Useful for all kinds of assemblies, from infrared assemblies to proximity alarms to anything else you can think off.
Credit goes to: 
1.  ExcessiveUseOfCobblestone for the initial conception on TG.
2. DimasW99 for handling Eriscode/Sojcode related questions and some fixing relating to vars on how to transition this feature.
3. Me (IrkallaEpsilon) getting it moved over and initial work/fixes.
Tested and working
:cl:
add: Remote signal devices frequency and code can now be paired by clicking on eachother.
/:cl:
=> [QOL] Frequency Transfer for Signallers

code/modules/assembly/timer.dm
An addition that should allow the time settings of one timer to be transferred to another timer. Time matters after all and setting a dozent timers can get very tedious, especially with latency in mind.
Credits:
ExcessiveUseOfCobbleStone from TG for the initial idea and implementation for signalers
DimasW99 for helping with a question and explaining a few things on Eriscode/Sojcode
IrkallaEpsilon (Me) for transferring this from signalers to timers
:cl:
add: Timers can now transfer their timing data by clicking one time with another.
/:cl:
=> [QOL] Transferring timing parameters (timing and time) from one timer to another timer

code/game/objects/items/trash_material.dm
What it says on the title, can't sleep till this typo and the grammar has been fixed or at least PRed.
It just fixes grammar, typo and some flavor to the reappearing broken posibrain in the description.
<hr>
</details>
:cl:
<!--add: Added new things
spellcheck: Fixed a typo and some grammar and added a little bit more flavor to the roundstart broken posibrain
/:cl:
=> [Spellcheck] Fixes grammar on the scrapped positronic brain

code/modules/telesci/relay.dm, code/modules/telesci/telepads.dm, code/modules/telesci/teleporter_blocker.dm
Robust bay autolathe code saving the day again.
Telesci Icon States are currently broken and dont properly update. This fixes icons for the "new" (ca 2022) telesci equipment.
Again overlays+= only adds a layer ontop. It does not clear icons. While add overlay clears up the the icon and returns to initial state.
Tested locally. Working.
Credits:
@Dimasw99 for VV checking what happens with the telesci equipment. 
IrkallaEpsilon (me) for grabbing autolathe iconstate check that was applied to vendor and then applied to here to fix it.
:cl:
fix: Fixes telesci iconstate overlays on open panel, inserted crystal etc.
/:cl:
=> [FIX] Assorted TeleSci Icon Fixes

maps/_DeepForest/map/_Deep_Forest.dmm
Outsider crashed shuttle will no longer have a chem dispenser and high tier medical kits.
Outsiders now get ghetto surgery tools including: A kitchen knife, wire cutters, pliers and a zippo lighter.
Adds in 2 ham radios to encourage player to player interaction between outsiders and potentially others.
This is the bare minimum needed to remove shrapnel on another person.
Added a small rock near the entrance ladder to outsider shuttle spawn. (Keeps mob from wandering into a player spawn)
New picture of the opening blocked by a single rock for anti mob wandering. Dying when spawning in isn't fun.
New medical area layout. Plenty of table space for stuff to be dropped off at. And a few tools for ghetto surgery (Only what was required for removing shrapnel) A knife, A wirecutter, A pliers, A …
=> Outsider shuttle med nerf

code/modules/projectiles/guns/projectile/dartgun.dm
Dartrifle was not firing its chemdarts. Worse: It multiplied RECYCLEABLE chemdarts when standing on a spot and firing it allowing for infinite mats on some materials. This makes the darts caseless (they are pneumatically fired and thus dont have propellant) and thus restoring function to the dart rifle.
This also lowers the dart rifles chem payload per dart to 5. Why you ask? Well I am the sole reason why RSG (Rapid Syringe Gun) and analogues are nerfed on any and all codebases to either be single shot, don't apply certain reagents or simply have lower capacity.
Unrelated to this PR: Polytrinic acid is utterly harmless for whatever reason. Need to look into that next
:cl:
fix: Dartrifle now can fire its chemical darts again proper.
balance: Chemdarts now only hold 5u instead of 15
/:cl:
=> [FIX] [BALANCE] Dartrifle now functioning again + lower capacity fired with darts

code/modules/mob/living/silicon/robot/robot_modules.dm
Fixes borgs bugging if they are reset while in a resting state.
Potentially might have fixed the stats going wonky too but not sure why it would have?
Tested on private server. Trilby knew about the bug and watched. She says its fixed but ive never experienced the bug before due to never resetting as borg.
=> Robot resting on reset fix

code/modules/reagents/recipes/recipes.dm
Dylovene reaction no longer produces table salt as per the title.
I am not sure why this is a thing, I am not sure how this is a thing. Its kinda weird and insignificant but triggers OCD.
Like really. If there was a meaningful byproduct sure. But this is exclusive to dylovene. Not sure why. Its weird.
<hr>
</details>
:cl:
del: Dylovene no longer produces Tablesalt as byproduct in insignificant irrelevant amounts.
/:cl:
=> Removes Dylovenes table salt byproduct

code/modules/projectiles/guns/oddity_items.dm
The lockpick o matic holster now holds 10 charges that recharge every second to prevent spam
The lockpick o matics despawn after a minute, making it a limit of 70 guns at a time when drawing constantly
The bullet type has been changed to caseless, damage mult, AP and recoil has been adjusted to compensate
Using the out of ammo special now stuns non humans. Bonus style!
=> bluecross Lockpick o matic anti lag measures

code/modules/core_implant/cruciform/rituals/path.dm
The entire litany and its target acquisition was fundamentally broken and did not work at all. So I gave it a rewrite to make it work.
What this does: Takes some code from existing litanies (Succour), repurposes it quite a bit. Now the litany is two stage: First it checks if somebody is adjacent to you. If adjacent it begins a channel.
During the channel it checks:
If you are synthetic: It wont proceed
If your target is a synthetic: It won't proceed
If your target moved out of the way: It won't proceed
Else it will proceed.
Local testing conducted with 3 characters: Organic test subject, organic prime and synthetic vector.
Prime casting on vector: Failed
Vector Synthetic casting on either: Failed
Prime casting on organic test subject: Works. Sanity deducted from prime and added to test …
=> [Fix] Fixes Inner Peace Church Litany

code/modules/projectiles/projectile/special.dm
So. Some gamer set the corestopper to be hitscan.  While this is a very cool idea this has a few nasty implications. The gun deals no damage per say and calls a proc to kill a slime. The gun is supposed to pass through windows if fired. This is very interesting. Unfortunately it makes the gun very inconsistent due to it being hitscan and often functionally useless. Additionally the sprite of the projectile is completely invisible due to hitscan.
This PR:
Sets the corestopper to be a projectile and not a (s)hitscan. This fixes the invisible sprite on the beam, allows it to kill slimes more consistently and most importantly doesnt break half the time you try to shoot them through windows due to clipping somehow on the disposal chute.
Drawbacks to this: Well its no longer hitscan so you have …
=> [Balance, Fix, Spritefix] Corestopper inconsistency fix

code/modules/power/apc.dm
Icons of APCs were stuck on bluescreen power outage. Really annoying once you note it. Its also really inconsistent on servers, sometimes the iconstate update works, sometimes it doesn't. Assume that happens because they are changing to another icon state and thus get stuck. Forcing an update upon reboot should fix this.
Fixes APCs not updating icon state and overlays when bluescreened.
Additionally it turns out we do not have a panel overlay for bluescreened APCs. Thats however spritework I guess which is uhghghhghghgkldfgjkghjk
Tested locally:
Went in: Triggered the best event in all of SS13. Went to closest APC. Rebooted APC. Screen changed.
If TMed please report of any abnormalities since thats some really obscure POS code from malf AI back when that was a thing on bay during the …
=> [Fix] Icons now update again when an APC is rebooted during the best event in the game

code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/game/objects/items/weapons/tools/simple_weapons.dm, code/modules/clothing/spacesuits/breaches.dm, code/modules/clothing/spacesuits/void/void.dm
Injector Rapier no longer breaks when upgraded
Injector and Deconner Rapier break less often (tool health wise)
Rapiers do not embed anymore as they are rapiers. Not Sabers 
Void suits and armor now have proper returns when upgrades are given to them
**You can now fix voidsuits that are damaged if its upgraded**
close #5038
close #4769
=> Fixes some tool upgrade intractions

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
-Alters the door on the surface transport to have soteria general access. The medical access it had before didn't work as intended for half of the medical positions. (I.E. lifeline techs)
=> surface transport access patch

code/modules/hydroponics/seed.dm
Fixes a critical runaway reaction that can occur in fringe cases
So: Picture this: You make a cold box for whatever reason, about 70 K in temperature. You manage to put a plant in there that produces N2O. This plant outputs gas. Sure. Okay. The problem arises that it just creates the gas at the temperature and pressure it is exposed to. This is a massive problem. Not for the low temperature case but for the high temperature case.
Lets say you luck out on strange seed or are a savy scientist wanting to have a miniscule amount of plasma for other research. Now you have a plant producing plasma and oxygen as byproducts (which can roll on lootbox seeds). Sure. Fine. Now that plasma ignites. As it currently is the plant will keep extruding gas at that temperature. If you are really *really* …
=> [Fix] Fixes broken thermodynamics resulting in critical thermal runaway reactions with plants

code/game/objects/items/weapons/storage/hardcases.dm, code/modules/projectiles/guns/energy/laser/egun.dm, code/modules/projectiles/guns/energy/projectile/stun.dm
<details>
<summary>
</summary>
<hr>
Gives SLTs the option to choose between the Abnegate, soteria version of the Zeus and Spider Rose.
Spider Rose doesn't see much use neither does Zeus with Zeus being an orderly weapon at one point so it makes sense.
<hr>
</details>
:cl:
balance: Sidearm options for SLTs
/:cl:
=> SLT sidearm options

code/modules/maint_expeditions/adms.dm
<details>
<summary>
ADMS will no longer work if there is open space within 5 tiles
</summary>
<hr>
People have learned they can cheese the ADMS by just putting it on a bridge with lots of space and then the mobs will spawn and quickly fall down below. This stops that from happening by checking if there's any open space within 5 tiles and stopping the ADMS if there is.	
<hr>
</details>
:cl:
tweak: ADMS will no longer work if there's open space within 5 tiles
/:cl:
=> ADMS requires solid work space

code/modules/reagents/reagents/toxins.dm
Right now you can drink Polytrinic with little consequence.
During dicking around with the dart gun I figured that Polytrinic currently does nothing if its in your blood. Which makes zero sense considering this is the closest thing we got to a super acid. This PR aims to make it more lethal so it isn't a joke item that is currently an illegal substance for no reason.
So what it does: Burns you, causes organ damage, chokes you. It also tells you that your insides are melting because you *will know* when you somehow got a super acid inside of you. Or anything highly corrosive. Can go more into detail about some folks accidentally ramming a syringe loaded with Butyl-Lithium into themself. Thats not a a trivial injury or chemical burn. Neither is this shit.
:cl:
balance: Polytrinic now …
=> [Balance, Buff] Polytrinic Acid lethality  

code/datums/outfits/jobs/ghostroles.dm, code/game/objects/effects/spawners/ghostroles.dm
<details>
<summary>
Changes the Lonestar ERT to be an Internal Affairs Agent rather than an Auditor
</summary>
<hr>
It was kinda weird to have an Auditor as the one who handles when CEOs are acting out of line in things other than their numbers not matching up, so changing it over to IAA makes more sense. Also tweaks their uniform to not have weird guild things.	
<hr>
</details>
:cl:
tweak: Lonestar ERT is now an IAA rather than an Auditor
/:cl:
=> Changes LSS ERT to an IAA

code/modules/organs/external/_external.dm, code/modules/organs/internal/_internal.dm
<details>
<summary>
</summary>
<hr>
Ports the organ damage function code from this PR
https://github.com/Baystation12/Baystation12/pull/34346
This makes FBPs / Anyone with prosthetic organs take less direct damage from the EMP itself making it more into a disable due to all the wounds it still causes rather than being instant kill.
<hr>
</details>
:cl:
balance: ION/EMP damage
/:cl:
=> EMP scaling

code/__DEFINES/chemistry.dm, code/__DEFINES/species_languages.dm, code/modules/goonchat/browserassets/css/browserOutput_override.css, code/modules/mob/language/outsider.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/silicon/silicon.dm
Works on local very well, see screenshot below.
Every race currently has an own language, even minor races. Cindarites currently lack that. This PR attempts to fix that.
The idea or lore behind is can be described as follows (WIP):
Cindarites originate from Cindar, which basically boils down to a radioactive deathworld with violent sandstorms containing glass shards. This is definitely not a comfortable environment to be in. They are confined to bunkers for the most part. Communication both inside and outside of bunkers in such an environment is critical and requires a very clear linguistic pattern. The language itself is described as devoid of rhetorical devices such as metaphors, allegories and colorful comparisons. It is optimized for relaying of information here and now. To …
=> [Feature] Cindarite Voc, a Cindarite language PR

code/modules/client/client_procs.dm
This adds a warning to 515+ clients telling them that stuff is likely to break, because stuff is likely to break.
Remember to remove this when we fix 515 compatibility.
:cl:
tweak: 515 clients now get a warning that they're in for a bad time
/:cl:
=> Add a warning to 515+ clients that stuff is likely to break

code/game/jobs/job/prospector.dm
<details>
<summary>
gives salvager the medical expert perk, someone had already attempted this with making sawbones get it as an alt but never seemed to make it work
</summary>
<hr>
<hr>
</details>
:cl:
code: adds PERK_MEDICAL_EXPERT to the salvager perk list
code: comments out the nonfunctional attempt to make the alt title get the perk
/:cl:
=> powercreep round 2 (gives salvager med expert)

code/game/machinery/machinery.dm
Ghosts and anyone with PERK_HANDYMAN (Guild Adept/Guild Master) can now see what components are inside of a machine, provided (for humans):
A) the maintenance panel is open
B) they are within two tiles
This is basically just to make it easier to know what's going on inside a machine when you aren't in possession of the one CRPED the guild gets. For example, to plan ahead of time what you'll need to load the RPED with.
:cl:
balance: Guild Members can now see machine parts when they are within two tiles of the machine and the maintenance panel is open.
add: Ghosts can now see machine parts
/:cl:
=> Let Guildees and Ghosts see Machine Parts

code/game/objects/random/mob/greyson.dm, code/game/objects/random/mob/misc.dm, code/game/objects/random/mob/roach.dm, code/game/objects/random/mob/spider.dm, code/game/objects/random/mob/termite.dm, code/game/objects/random/random.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm, code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
Chaos level now affects spawning of most *common* mobs (I.e Xenos/Roaches/Spiders/GP)
Higher Chaos level makes "tougher" spawn pools lineally
GP "Sniper" lower range has been added to the GP ranged spawn pool when at higher chaos level
Crimson Jelly and ploge have been added to the Psionic Monster pool when at higher chaos level
EMP roaches and Welder Roaches and even Kaisers have been moved to require higher chaos level before spawning naturally
=> Chaos intrigration

code/__DEFINES/items_clothing.dm, code/modules/mob/living/living_defense.dm
So this needs some explanation I suppose.
Firestacks currently are hyperlethal due to the equation for the burn damage being 5*Firestacks+3 with Firestacks from now on referred to as X. So even at 4 firestacks which means being hit ONCE by an incendiary slug you wind up with a DOT of 23 burn per fire process. This is really nasty, rapidly causes infections and wounds and also feels very off. So instead of a really harsh linear scaling I decided to use a logistics function. Its a subtype of an exponential function with some very interesting attributes:
A/1+(e^(-b*(x-s)) 
A is the max value this function can reach (how much burn per processing tick for firestacks, no matter what you do the fire damage you will do at maximum per tick is A. There is no way around it, thats how the function is …
=> [Balance, Fix(?), Math, Sanity Check] Rebalances firestacks to use a logistic function

code/game/objects/items/weapons/tools/_tools.dm
Corrects and santizes tool health repairing to prevent removing 40% of tool hp per repair
Fixes how mechanical skill intracts with repairing tools so that it accually matters
=> fixes tools for reals

code/modules/mob/living/silicon/robot/robot_upgrades.dm
Borg inventories will now auto close on module reset.
This prevents a visual glitch that would cause previous module items to be permanently pasted across the screen.
=> Borg inventory patch

code/game/objects/effects/spawners/ghostroles.dm
<details>
<summary>
Makes the excel spawners set excel faction on the person spawned
</summary>
<hr>
<hr>
</details>
:cl:
tweak: People made by excel spawners will no longer be attacked by excel mobs
/:cl:
=> Makes the excel spawner set the person as excel faction

code/game/antagonist/station/inquisitor.dm, code/modules/core_implant/cruciform/cruciform.dm, code/modules/core_implant/cruciform/rituals/crusader.dm
<details>
<summary>
Gives two ways to end the Crusader protocol
</summary>
<hr>
There is now a litany to end the Crusader protocol once it is no longer needed. It will be mandatory in SOP for certain individuals to use this after the crisis is resolved. Additionally, admins can remove the antag status from a person and the Crusade will end for them. There is not currently a way to do this en masse, but it likely wouldn't be hard to code one.
<hr>
</details>
:cl:
add: Crusades can now be ended with a litany or by admins
/:cl:
=> Crusades can now end

code/controllers/subsystems/xenoarch.dm
Command lines stated xenoarch was being moved to background processing due to fear of looping. 
Set it to background manually so it dosn't complaign about a non existant loop.
Still spawns finds, tested with all maps enabled
And added a manual spat message to tell me when its finishing despite being a background process.
=> xenoarch loop fix

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
<details>
<summary>
Adds a few Church weapons to the Prospector spawn pools. Do not merge until lore is ready
</summary>
<hr>
Adds the Church Longsword to each of the Prosepector melee spawn pools, adds the Rose to the pistol spawn pools, adds the Pilgrim to  the revolver spawn pools, and adds the Lightfall and Concilium to the Egun spawn pools. Concilium has a super low spawn chance.
<hr>
</details>
:cl:
add: Church weapons to Prospector spawn pools as a result of an in-lore deal between the factions
/:cl:
=> Gives Prospectors some Church weapons

code/modules/core_implant/cruciform/rituals/path.dm
<details>
<summary>
</summary>
<hr>
Fixes a bug with the Monomial path litany Bulwark of Harmony whereby players become permanently immune to all damage after using the ability.
Also fixes a glitch whereby Bulwark of Harmony slowdown did not last its full intended duration.
<hr>
</details>
:cl:
balance: Reduces Bulwark of Harmony damage reduction to 50%, down from 100%.
balance: Reduces Bulwark of Harmony duration to 1 minute, down from 1 eternity.
balance: Increases Bulwark of Harmony slowdown duration by ~55 seconds, up from one life() tick.
tweak: Added feedback message to user when Bulwark of Harmony expires.
:cl:
=> Fixes Bulwark of Harmony

code/controllers/master.dm
This makes it so the init timer resets between each subsystem, so that when it outputs "initialized within" it'll report the amount of time it actually took to initialize that subsystem, rather than the time at which it finished relative to server start.
:cl:
server: Subsystem Init time output now reports the time the subsystem took to initialize, instead of when it completed relative to the start of init.
/:cl:
=> Make subsystems report self-init time

maps/_DeepForest/map/_Deep_Forest.dmm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Someone copy pasted a maints APC into the marshals break room, making it off by default.
Also remove a random spider spawner inside the walls.
=> marshal break room fix

code/game/machinery/os_portable_turret.dm
EMP'ing greyson turrets multiple times now properly resets the timer instead of making several that each trigger an EMP off individually.
Also killing the turret while it is in the middle of it firing will properly stop its burst.
=> Greyson turret emp and death fix

code/__HELPERS/global_lists.dm, code/game/objects/random/guns.dm, code/game/objects/random/oddities.dm, code/modules/projectiles/guns/oddity_items.dm
Removes pluse rifle from oddities weapon spawns, its frame was ALREADY in rare loot tables
Adds the pluse rifle to rare gun spawn
Weapon Oddity spawns now will *try* to reroll **once** if said gun has already been spawned by the spawners around the map
This is to help lower **consecutive** repeats
Devil eyes now properly has drum mags loadable
Devil eyes now spawn in pars
Maxin MG now spawns with a pan mag
That gun now has more firemodes, without gun damage loss and can hold any type of pistol mag atm
"\"Elite\" magnum revolver" thing that holds 60 rounds now spawns with a large 10mm box of ammo, so you can actually load it at lest once
=> buffs, tweaks and differences in spawning for oddities weapon 

code/game/machinery/vendor/weapon_vendors.dm, code/game/objects/items/devices/holowarrant.dm, code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm, nano/templates/digitalwarrant.tmpl
<details>
<summary>
Permits holowarrant projectors to print the warrants, refactors the code, some minor QoL improvements for making search warrants
</summary>
<hr>
Behind the scenes rework of when the warrant projector creates its output, and adds a verb that will print out the warrant (available from Object tab or by right clicking). Additionally makes the warrant program actually use different prompts for search and arrest warrants to improve the quality of life slightly (including not having to input a job for the search warrant).
<hr>
</details>
:cl:
tweak: Making a search warrant in the Warrant Assistant program no longer asks for a job
add: Warrant projectors can now print their warrants via a verb accessible by right-clicking or the Object tab
/:cl:
=> Refactors warrant projectors and makes them able to print

code/modules/projectiles/gun.dm
<details>
<summary>
Gun safety verb no longer makes you choose a gun from a list (and then doesn't work if you choose anything but a gun in your active hand)
</summary>
<hr>
Gun safety verb has long been annoying on every Baycode server except CM because if you have a gun in hand, and a gun on your vest, and you trigger the toggle safety verb, it brings up a list. I ported the proc CM uses to handle that and rewrote the verb so now when you use the verb it checks your active hand, toggles safety if there's a gun there, if there's no gun there it checks your inactive hand and toggles safety, and if there's no guns in your hands it tells you you need a gun in your hands to use it.
<hr>
</details>
:cl:
tweak: Using the toggle-gun-safety verb will no longer bring up a dialogue box and will …
=> Gun safety verb no longer brings up a dialogue box

code/game/gamemodes/storyteller.dm
<details>
<summary>
Removes the requirement for a Councilor to start the game
</summary>
<hr>
Requiring a Councilor doesn't actually provide much benefit... there isn't all that much that the colony regularly needs where a single Council member is key. Requiring a Councilor does, however, lead to folks feeling obligated to change their job to suit the needs of the storyteller, and as often as not cryoing out at the first opportunity. Requiring Guild is fine because setting up power is actually important, and someone joining in as Guild and cryoing out a bit later doesn't use any one-time equipment kits or similar that complicate future people joining in that role.	
<hr>
</details>
:cl:
tweak: Game start no longer requires a member of Command
/:cl:
=> Councilors are no longer required for game start

code/modules/client/client_procs.dm, code/modules/client/preference_setup/global/01_ui.dm, code/modules/client/preferences.dm
No matter when you join in the boot process, it'll now eventually set your client.fps to the value you've selected.
Previously, client FPS would only follow your preference if you set it during the round.
:cl:
fix: Client FPS preference is now applied correctly.
/:cl:
=> Make sure client FPS is always set to preference value

code/modules/mob/language/generic.dm, code/modules/mob/language/monkey.dm
Adds the no-translate flag to a few languages that shouldn't be a thing to begin with. I *hate* TG bullshit. Separate PR is going to either gut mice or having to implement a check so say verbs for simple mobs are *no longer translated*. Which if its the latter is a pain in the ass cause there are fringe cases where simple mobs have verbs and are clearly of higher sapience and would still be non-translatable. Actually thats a polaris port and just as I said on discord: Add rudimentary mice language under monkey language dm, then add all the necessities, add RESTRICTED and NO_TRANSLATE flags then use has_lang or equivalent on the mouse mob. 
:cl:
fix: Various non-sapients can no longer be translated by the omni translator.
/:cl:
=> [Fix] Makes some non-languages non-translatable.

code/game/objects/items/devices/taperecorder.dm, code/game/objects/items/devices/translators.dm, code/modules/mob/language/generic.dm
#5323 had some issues
Reverts the noise lang change, noise lang must be understandable to everyone, that's it's point
This makes the correct changes to prevent the underlying issue
:cl:
balance: Animals can no longer be tape-recorded or translated.
/:cl:
=> Fix the animals translate bug properly

code/modules/ameridian/liquid_ameridian_processor.dm
It was possible to edit the amount to be a negative amount of anything above 120.
Allowing you to either create infinit liquid ameridian or create stacks above 120 using this exploit.
=> Fix Href exploit for the ameridian processor

code/game/gamemodes/events/hivemind_controller.dm, code/game/objects/structures/burrows.dm, code/modules/hivemind/machines.dm, code/modules/hivemind/wires.dm
<details>
<summary>
Spreading through burrows now no longer refuses to spread if the burrow is in maintenance, and gibbing players now gives a warning and 90 seconds first
</summary>
<hr>
Firstly, the spreading check. When "Spread through burrows" is enabled, the wires will now spread even if the origin burrow is in maintenance. This means that it actually does spread, since most burrows are in maintenance. Testing has verified that the hivemind now does properly spread in hard-to-predict ways.
Secondly, the gibbing check. Previously, it would happen almost instantly if the option was enabled, which isn't very fun player-side. If something *is* going to RR them, there should be more ways to prevent it. Therefore it now gives a message about wires wreathing around them once the hivemind …
=> Rebalances Hivemind Special Options

code/modules/surgery/robotic_damage.dm, code/modules/surgery/surgery.dm
Surgery debuffs and buffs now stack rather then set (this likely was a bug and not actually indented) 
Doing surgery on someone (or yourself) now takes account to what clothing the person is waring, generally doing surgery through clothing is harder and takes slightly longer.
Robotic burn repair now can use wirecutters and costs 1 less coil
Using wire cutters to repair burn simply heals less then coil but is easier as its a proper tool 
Fixes doing self robotic surgery counting as a 100% more difficult, now doing 5 more difficulty and takes much longer
=> Surgery Tweaks + Cloathing balance

code/datums/datum_click_handlers.dm
I noticed that fullauto still loops when a gun is being deleted like it is for the case of the bluecross lockpick o matic.
This should hopefully stop it looped and delete itself proper since it stopped people from interacting with anything.
Forewarning, I wasn't able to replicate this issue so it may or may not fix it.
If anyone else wants to take a peek at it.
=> Fullauto runtime

code/game/turfs/flooring/flooring.dm, code/modules/mob/living/living.dm, modular_sojourn/task_master/_task_master_defines.dm, modular_sojourn/task_master/task_helpers.dm, modular_sojourn/task_master/tasks.dm
Synths when diving no longer have the hunger drain, rejoice FPB buff!
Tripping now gives you a task, that per level directly lowers the tripping odds per level, like a silent cog addition
Diving has a task for lowering hunger cost (upto making it no longer cost hunger) per level
closes #4718
=> New tasks + diving tweak

code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
Nanobot healing is fixed, rejoice nanobot users!
Having robotics expert now stacks its healing affect with normal repair rng, rather then flat 50 healing, aka the best role you can get with rng repairs.
closes #5234
=> fixes nanobot healing + buffs

code/game/objects/items/weapons/tools/simple_weapons.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
Allows the injector rapier that the CBO gets to be loaded with acid and not melt, this was actually unintended rather then init balance 
Robotic tools in cyborgs/borgs/drones/ect no longer degrade as they have no ways of replacing or fixing them
closes #5288
=> injector sword fix + robo tool fixes

maps/Centcom/map/centcom.dmm
Fixes space tiles/airless tiles on the skipjack and merc shuttle under thrusters and low walls. Given they can land on a planet.
Removes all underplating under low walls on the 2 shuttles since its bad practice.
=> skipjack and merc event shuttles fixes

code/modules/tgui/tgui.dm
Missed these two other places the preference is assumed to be TRUE/FALSE instead of "Yes"/"No"
:cl:
fix: Disabling TGUI fancy mode should no longer trap you in a window with no exit button.
/:cl:
=> Fix tgui fancy mode not initiating correctly

code/game/machinery/tesla_turret.dm
Changed "Filter out Friendly Fauna" to "Filter out Colony Members" for the tesla turret.
This caused endless amounts of confusion since fauna are not humans from a players side of perspective.
Causing them to flip it off when trying to zap rats and the likes but only ending up zapping themself.
=> Change missleading setting

code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, code/modules/reagents/reagents/toxins.dm
Certified salt PR moment. Why do we have an instant death spider with no way to proper counter play? Prob Kaz thought it was funny. Good thing he is no longer around!
Now you need at least two hits to be dead and zombie powder as well requires 1 unit to work, preventing players to cheese super thinned out zombie powder to sleep people indefinetly. So if you do end up lagging into them (Some of us play with a 1 second stutter like me :( ) you don't end up instant dead.
=> Rebalance recluse to be 2 hit instant death

code/modules/admin/admin.dm
<details>
<summary>
Removes the "Delay" Admin verb, replacing it with separate "Start/End Delay" and "Start/End Resume" verbs
</summary>
<hr>
The Delay verb isn't very clear in the fact that it both starts *or* ends a delay period, and if things aren't properly communicated two separate staff can accidentally toggle the delay on and off. This splits it into two distinct, better explained verbs.
<hr>
</details>
:cl:
admin: Turns the Delay admin verbs into separate start and resume verbs
/:cl:
=> Turns the Delay admin verbs into separate start and resume verbs

code/controllers/subsystems/trade.dm, code/modules/trade/datums/_trade_station.dm
Default markdown multiplier for stations is now 1 - Trilby edit, its 0.8 to avoid exploits still
Fixed the math behind the markdown when markup is below markdown. markdown is now multplied with the current price if markup is lower.
I figured to change the markdown value for all stations to be a proper one to one when you examine your wares or use an export scanner. Making everything a little bit more accessible and less obfuscated.
=> fix markdown calc and rebalance direct sales

code/modules/scrap/scrap_beacon.dm
Examining or activating the Scrap Beacon now gives the time left until it's ready.
=> Scrap Beacon cooldown timer visibility

code/game/machinery/vendor/food_vendors.dm, maps/_HunterLodge/map/_Hunting_Lodge.dmm
<details>
<summary>
Gives Lodge the same seeds they've had before Xenobotany tweaks by making an independent version of the MegaSeed Servitor with the same seeds they had prior
</summary>
<hr>
<hr>
</details>
:cl:
Add: MegaSeed Servitor independent for lodge
Change: Changes MegaSeed Servitor at lodge to independent Lodge version
=> MegaSeed Servitor for Lodge

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Removes the Church vendor from upstairs
</summary>
<hr>
It's just used for free disks and such rather than people using the EOTP which is the intent. I've also heard people are recycling things from it. It doesn't really serve a needed purpose, so it can go.
<hr>
</details>
:cl:
map: Removes the upstairs church vendor that Churchies only use for free disks and such
/:cl:
=> Removes the spare Church vendor

code/modules/recycling/disposal.dm
Projectiles now fly over disposal bins.
----------------
I'm not completely happy with just adding a flat projectile check, but it seems that we don't use the CanPass() "height" variable anywhere in the code for these sorts of purposes, and I don't want to do a code crawl and adjust every single copy-pasted "height=0" in the code.
=> Projectiles go over disposal bins

code/modules/mob/living/carbon/human/human_damage.dm
Previously, the nopain flag/mutations didn't actually stop you from accumulating halloss(which meant you still suffered all kinds of deleterious effects). This has been fixed. This will also introduce a new issue because some jackalope decided to make it so that shields cause halloss when struck even though halloss is used as pain(not STAMINA). this i will maybe fix later.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> [bugfix] NO_PAIN flag now actually properly confers pain immunity.

code/datums/perks/job.dm, code/datums/perks/oddity.dm, code/datums/perks/racial.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/genetics/mutations/cow_skin.dm, code/modules/genetics/mutations/dwarfism.dm, code/modules/genetics/mutations/gigantism.dm, code/modules/genetics/mutations/thick_fur.dm, code/modules/mob/living/living_defines.dm, code/modules/reagents/reagents/alchemy.dm
Reworked how damage modifiers are applied to people, making scaling linear instead of being a 1/x curve.
All damage modifiers are now multiplicative instead of additive.
Reasoning: For a while now I noticed that a lot of damage modifiers are tip toeing the line between incredibly small but if stacked enough will utterly break the balance. For example if you have a brute mod of 0.2 from prior stacking, adding another -0.1 from something like cow skin would double your effective HP. Otherwise, it only would be 10% if you had nothing else.
Now that they are multpilied, it is much easier to see how much damage you take less while also preventing the insane stacking. Another reason was that a lot of choices for damage absorbtion by itself were more than just meaningless, the game was …
=> rework of damage mods

code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
This has like, no gameplay impact whatsoever. Both ammo boxes are the same, lackluster price, but just had their names swapped around (A single number.)
The game is now playable.
=> Trivial Favor Title Correction

code/__DEFINES/chemistry.dm, code/modules/organs/internal/internal_wounds/organic.dm, code/modules/reagents/reagents/medicine.dm, code/modules/reagents/recipes/recipes.dm
Adds a new chem for use in treating internal burns/necrosis.  Created by mixing carbon, sulfuric acid and dermaline. Painful to use, but at least it doesn't require surgery. Trypsin can also be used to treat "permanent" scars but only via overdose- which will cause steady brute wounds similar to kyphotorin(and even more pain). This chem is partly an experiment in chem effect numbers that aren't flat values, but are determined by dose(a number that steadily goes up as you metabolize a reagent.)
Probably works. testing chems and wound shit is a PITA.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> [balance] New burn-wound medicine

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Remaps the engine area and small monitoring room to allow for larger engine configurations
</summary>
<hr>
Guild recently got a few more antimatter pieces which allows them to make larger engines... but their engine room is very firmly designed for a 3x3 engine. This PR remaps the area to support a 5x5, with it able to be made 5x6 relatively easily if the Guild acquires a lot of parts.
<hr>
</details>
:cl:
map: Guild Engine room remapped for larger engines.
/:cl:
=> Remaps the engine chamber to allow for larger engines

code/modules/mob/language/monkey.dm, code/modules/mob/language/station.dm
Both are old references to a gamemode that was merged in 2015 (?) on another codebase for about a month before it got removed. Somehow this reference still exists on many codebases for whatever reason. Theres no instance where a monkey is controlable here outside of certain fringe case events (looking at Carrions turning into one I suppose.). This is basically just a little cleanup.
- It removes an oversight/pseudofeature from long long ago back when Eriscode was Bay which has no place in our setting.
:cl:
del: Partial understanding on monkey language for common and partial understanding on common for monkey language. Code cleanup basically.
/:cl:
=> [Removal] Removes partial understanding on monkey for common and for common on monkey

code/game/machinery/vendor/weapon_kit_vendors.dm
See title. the lascore was a cool gun that i was happy to give to the shield but it seems like it outshines most other options.
Sgt/Corpsman may still select this option.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> [balance] Removes the Laser-Core from the Trooper starting options.

code/game/machinery/adv_med.dm, code/game/machinery/cryo.dm
This removes the requirement for people being thrown in the scanner or cryo cell to have nothing in their hands (the abiotic() proc).
Tested and made sure that any items that are dropped inside get vomited out with the occupant.
The reason behind this PR is primarily armblades and the like being impossible to remove from hands short of cutting off people's arms, which interferes with medical treatment.
:cl:
tweak: Body Scanner no longer requires empty hands to load
tweak: Cryo Cell no longer requires empty hands to load
/:cl:
=> Ditch abiotic checks in scanner/cryo cell, make cryo eject dropped items

code/game/objects/structures/noticeboard.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Fixes noticeboards not updating icons correctly on spawn
Requested by Pravel Marsk
Adds in a noteiceboard for scavs instructing them how to bulk sell
Adds in a notice to cargos notice boards as well as a few new ones instructing folks how to deal with scavs bulk selling
=> note boards for bulk selling

code/controllers/subsystems/ticker.dm, code/modules/client/preferences_spawnpoints.dm, code/modules/mob/new_player/new_player.dm, code/modules/mob/transform_procs.dm
This hopefully should make it so that any issues with people all spawning on top of each other at roundstart go away, since the system will now try really really hard to spawn people directly inside the station at the same time as `new`, and then wrassle them around afterwards for like, cryo tubes and the elevator and stuff.
:cl:
tweak: People now spawn directly where they should at roundstart.
/:cl:
=> Make people spawn directly at appropriate locations

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Redoes the layout of xenobio, this sadly does remove the animal pen area and look less good. But hey people might want it over current objectively better looking one we currently have
Closes #5345
=> Xenohydro relayed out!

code/controllers/subsystems/trade.dm, code/game/objects/items.dm
Fixes market exspert perk not really giving you the full idea of how much things would export
Fixes market exspert not telling you about trade deals (This is a fix as it was meant to be ported with cargo reworks)
Fixes imported items not being labled as "Surplus"
Fixes the math of imported items when surplus to be 1/10th the value rather then 9/10ths
NOTE: when filling spec officers, surplus tag isnt checked, this is do to me not being able to find a way to ingore surplus tag for spec officers without it also being unsellable (something i dont want to do)
=> Market Exspert fix + surplus tag fix

code/modules/clothing/clothing.dm, code/modules/clothing/head/helmet.dm
The special SLT alert helmets not also print the area the alert came from.
Suit sensors can now be changed with tools that have "SCREWDRIVING" but are also sharp, like knives.
Only clothing that spawns on Station Levels (The colony, the mines, the solars) start with sensors enabled, clothing that spawns outside starts with sensors disabled.
=> Adds area to SLT helmet alerts, suit sensor changes

code/game/objects/items/weapons/storage/pouches.dm, code/game/objects/items/weapons/tools/tape.dm, code/modules/mob/inventory/slots.dm
Hey hey catto here from back from hell and me and the fallen have been chitchatting before seeking otherworldly advice for tweaking the balance of storage!
Pouches are now "soft storage" for sake of mechanical refence, what that means is that more items put in the more it grows in size well in modular storage.
Pouches default size has been lowered by 1 weight class, some pouches have been given bulk to undo this lowering of class
Putting items of the higher weight class into the soft storage increases its size by the difference 
An exsample
Small pouch is tiny! code wise thats a weight class of 1
You put a medium cell in, thats small and thats a class of 2
so the pouch grows for having an item inside it and then an additional 1 extra bulk for the cell.
This system does NOT prevent you …
=> Pouch "rebalance" 

code/game/objects/structures/crates_lockers/closets/wardrobe.dm
<details>
<summary>
Adds militia and security armbands to the Blackshield and Marshal lockers respectively
</summary>
<hr>
Blackshield and Marshals are allowed to wear non-uniform jackets/armor only if they have an armband with their faction's colors on that armor, but none actually spawn on the map, they're only available in loadout. This adds some to the lockers in-game so that players aren't caught without access to them.
<hr>
</details>
:cl:
add: Blackshield and Marshal armbands to their wardrobe lockers
/:cl:
=> Adds armbands to Marshal and Blackshield wardrobes

code/controllers/subsystems/ticker.dm, code/modules/client/preferences_spawnpoints.dm, code/modules/mob/new_player/new_player.dm, code/modules/mob/transform_procs.dm
Reverts sojourn-13/sojourn-station#5402
This is triggering some underlying equipment bug that I can't reproduce locally and can't find the source of, and it's a severe issue that causes players inventories to get so fucked up they have to have an admin fix it.
=> Revert "Make people spawn directly at appropriate locations"

code/controllers/subsystems/garbage.dm, code/datums/transformation_types/transform_types.dm, code/game/objects/effects/decals/Cleanable/humans.dm, code/game/objects/effects/decals/cleanable.dm, code/game/objects/structures/lattice.dm, code/game/turfs/flooring/flooring_effects.dm
Fixes a bunch of random errors that happen on startup, see changelog.
:cl:
fix: Things deleted at roundstart during maploading won't initialize after deletion anymore
fix: Fix qdel failures from /datum/transform_type 
refactor: Cleanable decals handle merging together in a much better way
fix: Blood doesn't qdel anything other than itself at map start anymore (merging means qdeling src instead)
fix: Lattices no longer qdel() in Initialize, similar to decals
fix: Flooring effects use LateInitialize to do their thing and qdel(src) now.
/:cl:
=> Fix some miscellaneous startup errors

code/game/jobs/job/engineering.dm
I did a fucky wucky 7 months ago. Allowed SI synths to be GM by total mistake. All better now! Woops! (how did no one notice?) Mini PRs stink but its a important issue so.
Changelog:
Disallows SI synths to be GMs once again. Was permited by mistake.
=> disallows SI synth to be GM

code/game/objects/items/weapons/hydrogen_melee.dm
Trilby is right, it calls explosion 20 times.
So something was pasted from the Hydrogen grenade clearly. The H2 sword doesnt need to explode 20 times to get the message across. It also crashes the server kinda. This fixes the issue for real this time without commenting out the interaction.
DO NOTE: IF THE H2 GRENADE CAUSES SIMILAR ISSUES REMOVE THE SPAWN 20 COMPONENT.
:cl:
fix: Hydrogen Sword no longer crashes the server if EMPed by a roach
/:cl:
=> [Hotfix] Hydrogen Sword EMP effect wont crash the server

maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
Was curious just what exactly was sucking so much power at SI outpost. Turns out! toxins was not all to blame. It's atmos was setup in such a way that it attempted to compress via filtering several very very large air canisters into a single pipe. Making them run non-stop all round.
This PR fixes that! Some things shuffled around. Nothing removed/added unrelated to atmos. Did testing via dumping every kind of gas into the system and making sure it went to the right places.
Changelog:
Mildly shuffles around and fixes SI outpost atmos making it no longer consume a absurd amount of power and now actually functions.
Pretty picture:
=> Fixes SI outpost atmos setup

code/game/objects/items/weapons/hydrogen_melee.dm
It crashes the server (or nearly does so) so the part that makes it detonate is commented out. NOTE this is only when hitting certain fringe cases or if an EMP roach detonates while the sword is active. 
Fundamentally broken from the start in case something keeps pulsing EMPs like EMP roaches. An overglorified arc welder does not explode either when I remove its power supply.
Also: Its probably better long term to fix the EMP roach cause it cant be that good that it can perma trigger effects acting on emps.
:cl:
del: Hydrogen Swords no longer explode when EMPed due to it fucking the server.
/:cl:
=> [Removal, Hotfix] Hydrogen Sword EMP interaction removal

code/game/objects/structures/kitchen_spike.dm, code/modules/genetics/creatures/wasonce.dm, code/modules/mob/living/carbon/alien/alien.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm, code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm, code/modules/mob/living/simple_animal/friendly/crab.dm, code/modules/mob/living/simple_animal/hostile/big.dm, code/modules/mob/living/simple_animal/hostile/huntersprey.dm, code/modules/mob/living/simple_animal/hostile/misc.dm
Several copy-pasted mob size vars were adjusted to be more sensible and to use defines whenever possible.
Meatspikes can now only fit up to MOB_MEDIUM size creatures.
=> Small mob size audit, kitchen spike mob size limit

code/modules/client/preference_setup/loadout/lists/fluff.dm
whoops
:cl:
fix: TEF's fluff item should actually work now
/:cl:
=> Fixes TEF's fluff item, ckeys are always lower case

code/game/machinery/os_portable_turret.dm, code/game/machinery/portable_turret.dm, code/game/machinery/tesla_turret.dm, code/modules/mob/living/carbon/superior_animal/ai.dm
Turrets that target a mob now will be targeted by the mob its targeting
Only expiation is church ones as they dont break
Tweaks how mobs view living as anything rather then strick type
Should be an optimization, might break something
=> Mobs targeting turrets

code/game/objects/random/mob/misc.dm, code/modules/core_implant/cruciform/machinery/obelisk.dm, code/modules/hivemind/objects.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/attack.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm, code/modules/psionics/psionic_items/psi_armor.dm
At higher chaos level darksie cult mobs can respawn in deepmaints, WAR WAR WAR WARRRRRRRRRRRRRR
At higher chaos levels weaker mobs found in deepmaints will have *uniquic* intractions and attacks!
The following are locked behind chaos level 2
Memorys now teleport behind the person after attacking (even through walls!)
Memory Eater now when not waring a hat will do a 2x attack
thought melter will now rip of hats so that the memory eater can do its 2x attack
hovering nightmares will now rip off your mask (even through your hats) and try and sew on a new one for you! (Lowers stats and on removal deals sanity damage, but on removal gives back the stats it steals)
The Cerebral crusher gets by far the most complex and silly fancy attacks.
If we have a shield, then we deal direct damage to it, …
=> deepmaint mobs uniquic attacks

code/modules/genetics/machinery/genetics_extractor.dm, code/modules/genetics/machinery/genetics_items.dm
Pulper now labels its vials.
Flesh sacs now drop their contents on the floor. (If you held it in your hands while cutting it open it would dumb all its stored organs into your body instead of spilling it onto the floor)
=> Pulper auto lable and flesh sac fix

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Updates the Soteria Telesci room, giving it two more frames and making the structure a hexagonal shape, as well as making the room slightly trashed and require cleaning, also adds some decals and a sign. CAUTION FOR SPILLED BIOMASS!
=> Trashed Telesci Room™ (An all-you-can-repair-yourself toy)

code/modules/power/solar.dm, maps/_DeepForest/map/_Deep_Forest.dmm, maps/_HunterLodge/map/_Hunting_Lodge.dmm
Built solar panels can now be upgraded to only require 3 tiles of unobstructed space to function instead of 20, at the cost of 1 silver per panel.
The Zoo and the Lodge have their solar panel grid upgraded by default.
=> Adds solar panel upgrade

code/_compile_options.dm, code/controllers/subsystems/jobs.dm, code/game/objects/items/oddities.dm, code/game/objects/structures/bedsheet_bin.dm, code/modules/mob/living/carbon/human/life.dm
<details>
<summary>
- 	Makes the codebase able to be compiled on 515, no errors anymore
- Fixes bedsheet bins not updating the icon in case you remove or add sheets to it by hand
- Adds some stuff to code/_compile_options.dm to bridge the code that will need to be properly mass replaced later for a proper 515 update, with probably more to be done for the task to be considered done that I have no idea right now
</summary>
<hr>
The bedsheet bug got fixed because one of the compiling errors happens exactly at the update_icons() inside of it, not really a critical issue in case this PR gets scrapped
<hr>
</details>
:cl:
add: partial 515 compatibility, mainly switch() issues
fix: bedsheet bins now update their icon if you remove/add sheets by hand
:cl:
Credits to Eris codebase, with a bit of …
=> 515 compiling issues + bedsheet bin bug fix

code/game/objects/items/weapons/power_cells.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm, code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm, code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm, code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
Adds a price to cells that increments with their capacity, Soteria cells have prices set too, roughly incremented up by one, as one would assume they would have a higher quality all around.
Adds Greyson Positronic cells favors to some stations, as they would understandably be a very hot item for almost anywhere a cell can be used in the galaxy.
Adds a  favor for the unknown plasma gun to the bluespace station. Whoever they are, they'd probably want them 'back'. Or just want them in general.
Overall, the cell prices make it more sensical, looking at a page of cells to buy with all their prices being exactly the same regardless of capacity reeks of 'unpolished' to anyone who comes across it. Nerfs cargo in the fact they can't get robust-X cells/big cells in general for literally no downside …
=> The Great Cellening, prices for thee AND me

code/controllers/subsystems/movement/movement_types.dm, code/datums/components/clothing_sanity_protection.dm, code/datums/perks/backgrounds.dm, code/datums/perks/imprinter_perks.dm, code/datums/perks/job.dm, code/datums/perks/nanite_powers.dm, code/datums/perks/nanogate.dm, code/datums/perks/nepotism.dm, code/datums/perks/oddity.dm, code/datums/perks/perk.dm, code/datums/perks/psionic.dm, code/datums/perks/racial.dm, code/datums/perks/special.dm, code/game/machinery/bioprinter.dm, code/modules/cooking_with_jane/cooking_items/cooking_containers.dm, code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/carbon/superior_animal/defense.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/life.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/modular_computers/hardware/scanners/scanner_price.dm, code/modules/nano/nanoui.dm, code/modules/organs/blood.dm, code/modules/reagents/reagent_containers/glass/beaker.dm, code/modules/reagents/reagents.dm, code/modules/reagents/reagents/core.dm, code/modules/virus2/isolator.dm
See changelog
:cl:
fix: Runtime when superior mobs move towards qdeleted things
fix: Runtime when adding bad item to a Jane's cooking container
fix: Runtime when superior mobs try to attack after being qdeleted
fix: Runtime when brains in MMis tried to handle being on fire
fix: Runtime when beakers are initialized
fix: Runtime when putting on sanity-protecting gear (it still doesn't work tho)
fix: Runtime when trying to print a blood-matched organ in the bioprinter
fix: Runtime when a mob tries to hit a limb that no longer exists
fix: Runtime when scanning a turf with the export scanner (only movable atoms work)
fix: Runtime when overdosing on plasma
fix: Runtime when opening nanoUI without a client (how?)
fix: Runtime when selecting robot modules
fix: Runtime when robot module has been …
=> Fix a bunch of runtimes

code/modules/nano/nanoui.dm
I didn't notice the subtle behavior change in 411c917941d9deaa5d75f081e17d4baa81f12fb8 where data is no longer checked for isnull() - evidently, this causes nano to scream whenever a UI is out of range
:cl:
fix: NanoUI no longer screams and errors when you walk away from an object
/:cl:
=> Fix nanoui throwing errors when moving away

code/modules/projectiles/gun.dm, interface/skin.dmf
Gun scopes can now be toggled in Hotkey Mode using Shift+C
=> Gun scope toggle hotkey

code/game/objects/random/mob/misc.dm
Changes the incorrectly named "low chance nightmare" vox spawner to "low chance vox".
Only shows up in mapping tools.
=> Fix incorrect spawner name

code/modules/paperwork/faxmachine.dm
:cl:
admin: Faxes are now logged to `data/logs/faxes/[year]/[month]/[day]/fax_[numbers].html`
/:cl:
=> Make faxes log to a place we can actually see as admins

code/__DEFINES/is_helpers.dm
This removes our defines overriding the much more efficient builtins of `ismob`, `islist`, and `ismovable`
:cl:
code: ismob, islist, and ismovablewere using inferior defines instead of native procs
/:cl:
=> Remove a handful of native BYOND procs we redefine for no reason

code/controllers/subsystems/radiation.dm, code/modules/power/supermatter/supermatter.dm
<details>
<summary>
Makes the radiationSS now use the inverse square law for propagation of radiation, and makes the supermatter use it instead of doing it on it's own
</summary>
<hr>
Overall it's both a nerf to radiation from far and a buff if you're too close, but the effect on mobs seem to be currently bugged, I will probably have to return to those files and tweak the values in case they cause too much damage to players, or too little once it gets sorted, right now SM is in equal footing with early torch Bay, but walls block it, so avoid being in line of sight of the SM to never get irradiated/hallucinations
<hr>
</details>
:cl:
fix: radiation now follows the inverse square law
tweak: supermatter now operates normally under radiationSS instead of it's own, delams are still handled by …
=> Supermatter now tied to radiationSS

code/modules/clothing/head/misc.dm, code/modules/clothing/suits/miscellaneous.dm, maps/_DeepForest/map/_Deep_Forest.dmm
Makes the map edited armor from PR #5460 into a real item.
Combat stats copy pasted. Descs slightly adjusted and included general hazard protection. (heat and gas permeability etc). I've not made any significant balance changes intentionally with the hopes this can be full merged rather then lock up a map file. :3
Changelog: 
Tweaks the HEV suit in the LAMBDA dungeon to be a normal item.  
Fixes one of the coldrasil's (cold atoms tree) being visible.
=> fixes the HEV suit

code/modules/nano/nanoui.dm, nano/js/nano_utility.js
So, I had a hunch, and commented out `user << output(list2params(list(strip_improper(json_encode(send_data)))),"[window_id].browser:receiveUpdateData")` completely...
and what do you know? Never got a white screen error no matter how hard I pressed it.
So, the problem with Nano has been this entire time, that it ends up pushing data before everything has loaded, causing an alert that then stops the rest of the UI from loading.
To fix this, I just took a note from TGUI - Nano now will not push updates to a UI until the UI signals via /Topic that it's loaded and ready. 
With this change, I haven't experienced *a single white screen* from Nano. This might not fix it all, but holy shit it should improve reliability.
:cl:
fix: NanoUI now waits until it's loaded to send data, hopefully …
=> Make nano wait till the UI loads to send updates

code/modules/goonchat/browserassets/css/browserOutput_white.css
Revert the change to white mode dsay. #5452
While I think the change to darkmode dsay was reasonble since dark blue on black is not a great mix. Changing white modes dsay was not necessery. It actually introduced a new issue in making it look nearly identical to normal say. Example here:
=> Revert white mode dsay change

code/game/objects/items/weapons/cosmetics.dm
Adds attackverbs to the comb.
Previously, it was only an item that does an emote when you use it, now it's still that, but you can mechanically bush other people's hair too. (Or use it on yourself in a different way)
:cl:
Add: Added attackverbs to comb
/:cl:
=> Adds comb attackverbs

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Basically what it says on the title
</summary>
<hr>
- Lower Lonestars gets changed with the intent of making it easy to repair damaged piping
- Hallways get a few more firedoors and some atmos related machinery get moved around so in case of trouble the system can't easily create pockets of bad air
- NE main floor maints gets a tight corridor mini slum, good place for more sordid characters to mingle, but as dangerous as any maintenance, it has awful lighting on purpose
- Guild AM room got partially reverted, for ease of use/assembly
Mandatory checklist for when I consider this PR to get out of draft:
<hr>
</details>
:cl:
fix: atmos related changes on hallways and lower Lonestars
add: NE main floor maintenance slum
fix: hopoloster on xenoflora
/:cl:
=> Colony atmos pass + more maintenance

code/modules/clothing/spacesuits/rig/modules/storage.dm, code/modules/clothing/spacesuits/rig/suits/combat.dm, code/modules/clothing/spacesuits/rig/suits/station.dm, code/modules/research/designs/rigmodules.dm, code/modules/research/nodes/engineering.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
Rebalances hardsuit storage
<details>
<summary>
</summary>
<hr>
Adds a new 'large' distributed storage module for hardsuits. This has about the same storage as a satchel, but cannot hold bulky items.
The old storage module has had its overall size reduced, but can hold bulky items.
Both storage modules can now hold appropriately sized containers, similar to a satchel, such as boxes and pouches.
These now replace the old specialized storage modules on all hardsuits. Previous specialized storage modules can still be printed from RnD or ordered from the Suit Up station by Lonestar, if for some reason you prefer them.
Removed slowdown from hardsuit storage modules. It was a lot of slowdown, especially considering most hardsuits have a lot of slowdown anyway.
<hr> …
=> Hardsuit storage module tweaks

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Moved foreman armor disk and vector disk from foreman's office to prep room. On request.
=> Moved foreman disks to prep

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Removing Sweatshop and Vector disks from Foreman's locker. This was meant to be added to PR #5491 but the changes were not made on that PR. 
Both PR's are designed to improve QOL so people stop breaking into foreman's office for the disks during low-pop rounds same that was done with guild and church disks
=> Prospector disks movement PR.2

code/modules/paperwork/folders.dm
The "folder_white" sprite does not exist, this is an incomplete item that also should not exist.
=> removes broken folder

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
That's it, that is all this PR does, assuming I didn't misclick somewhere in the map
Just a simple bugfix
🆑 
bugfix: medical front desk and chemistry no longer lack firedoors
🆑
=> Fixes lack of firedoors in medical

code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Fixes the Neuland Himbeergest bottle turning invisible when emptied by making the empty sprite the same as the bottle sprite, since the empty sprite does not seem to exist.
=> Fixes Neuland Himbeergeist Empty Sprite

code/modules/clothing/spacesuits/rig/suits/light.dm
<details>
<summary>
Lets righud users eat
</summary>
<hr>
Adds updated flags so the hacker and spacer rig helmets, which aren't spaceproof, now no longer block the face when deployed. Despite being marked as not airtight, they still retained full face covering flags as being spacesuit helmet subtypes.
<hr>
</details>
:cl:
Fix: Updated hud-style rig helmets to no longer block mouths.
/:cl:
=> Gives hud-style rig helmets no face covering

code/modules/clothing/spacesuits/rig/rig.dm, code/modules/clothing/spacesuits/rig/rig_attackby.dm, code/modules/clothing/spacesuits/rig/rig_modules.dm, code/modules/clothing/spacesuits/rig/rig_pieces.dm, code/modules/clothing/spacesuits/rig/rig_verbs.dm, code/modules/clothing/spacesuits/rig/rig_wiring.dm
Rigs now only give verbs when equipped onto back
and of course get removed when removed off back
Behind the code as been miniumilly cleaned up (i.e removal of unneeded var/ and return 1 rather then return true)
=> rigs to be storged in the human verbs

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
<details>
<summary>
Reroutes the disposals ending to make it go to church, then guild, then to LS for export. Makes it so that you can also ship directly to export.
</summary>
<hr>
Rr-routes the pipes so that unsorted stuff goes to the church, then to the guild, and anything leftover is sent to LS.
Also replaces the previous disposal room to be used as a mailing room. And where mailing once was, is now a mech spot for cargo.
<hr>
</details>
:cl:
add: new routing for pipes.
add: A new mech for cargo.
del: the cargo trolly. It's a buggy mess, might get added back in if it's ever fixed.
tweak: moved the recycler, and the smelter, recycler is now in cargo at the EOL, and the smelter is now in the guild.
fix: removes that random termite spawn out in the rocks.
/:cl:
=> Disposal rework and mailing room

code/__DEFINES/cooking_with_jane.dm, code/modules/cooking_with_jane/cooking.dm, code/modules/cooking_with_jane/cooking_appliances/grill.dm, code/modules/cooking_with_jane/cooking_appliances/oven.dm, code/modules/cooking_with_jane/cooking_appliances/stove.dm, code/modules/cooking_with_jane/cooking_items/cooking_containers.dm, code/modules/cooking_with_jane/cooking_tracker.dm, code/modules/cooking_with_jane/recipes/recipe.dm, code/modules/cooking_with_jane/recipes/recipe_dough.dm, code/modules/cooking_with_jane/step_types/add_reagent.dm, code/modules/cooking_with_jane/step_types/use_tool.dm, code/modules/mob/living/simple_animal/friendly/farm_animals.dm, code/modules/reagents/recipes.dm, sojourn-station.dme
- Prevents containers placed in an oven from storing time infinitely, leading to a feedback loop where it caused later recipes to be low quality.
- Cleans up typos in the oven action texts
- Measuring Cooking time should be improved across the board
- Food is burned if left to cook in an oven for too long
- Ovens, Grills and Stoves catch fire if left on with food too long; will trigger nearby fire alarms and require an extinguisher to put out.
- This "fire" is smoke that deals oxy damage if nearby without a gas mask or airtight suit
- Improved oven open/close interactions
- Added CWJ recipes for making and kneading up high quality dough, and making dough batches
- Small bug removed from use_tool step type
- Laid chicken eggs have  more food quality
- Improved Reagent quality calculation …
=> CWJ Oven overhaul

code/game/machinery/vendor/weapon_vendors.dm
<details>
<summary>
Makes the Church vendor no longer a custom vendor that can be unlocked with an ID
</summary>
<hr>
It was made such back on Eris so that the Church could be cool and sell stuff with it, but they only use it to gain free things. They can and do just set up a new custom vendor for selling stuff to the public.	
Also removes a proc that was checked any time someone interacted with the Church vending machine but would only ever return one value because the Church wants to sell.
<hr>
</details>
:cl:
tweak: The Church vendor is no longer a custom vendor that can be used for free goodies by any Vector
/:cl:
=> Makes the Church vendor no longer custom

code/game/objects/structures.dm, maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Pretty much the title, plus the conveyor line is changed to start on as to not clog the line in case of no Guild
:cl:
fix: guild smelter has correct outputs
code: changes a line as per shadow's instructions
tweak: guild conveyor starts on
/:cl:
=> Fixes the Guild part of the disposal line

code/controllers/subsystems/overlays.dm
Maybe this is the problem on live?
:cl:
fix: SSoverlays no longer tries to write a big file on round end
/:cl:
=> Remove overlay stat logging at round end

code/modules/clothing/head/misc.dm, code/modules/clothing/suits/miscellaneous.dm
Guess HEV suit got missed in the merge conflicts. OH well! Fixed now
changelog:
Converts the HEV suit over to the new armor system numbers. (so it no longer makes you near immortal)
=> converts the HEV suit to new armor system

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Fixes some bad piping and wires 
Fixes some grass issues
Fixes some overlayed dirt piles
Removes hens in maints
Fixes some lights in maints
replaces mining drill in maints with a bunch of slavage
Gives cargo back book cases
Gives cargo more wrapping paper and labelers
Fixes CEO has vault door button access again 
Givesn gardeners hidden area a scarecrow and scythe
=> Cargo +  maints  + pipeing

maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
- The CRO's Office has replaced Virology, and has been merged with the Server room. The server room has been turned it into a mini-command center, and many of the CRO's computers are now down there to reduce clutter in the CRO's main office.
- Showers have been expanded slightly
- R&D Prep has been given it's own separate room, and some gloves/masks that were previously in Viro
- A new break room for Science/Medical has been added, moving many of the vending machines in the current break room up there.
- The Teleporter room is cleaned up and doesn't have trash everywhere anymore
- Organ Research got a monkey cube to offset the monkey pen removal
- Removes camera from SOM's "secret" base
- Front desk now has GOOD LAYERING, WOW
=> Research Face Lift

code/modules/projectiles/projectile/bullettypes.dm
wounding mult was accidentally defined twice(by me), giving it the same wounding mult as a slug. this has been corrected and it now has a mult of 1
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> tiny bugfix for beanbags

code/game/machinery/smelter.dm, code/modules/mob/living/simple_animal/hostile/bear.dm, code/modules/mob/living/simple_animal/hostile/big.dm, code/modules/projectiles/ammunition/boxes.dm, code/modules/projectiles/projectile/bullettypes.dm
requesting a TM since I'd like to play with these lodge numbers on live and tweak them more. Im still somewhat stuck. supereffectivness on projectile weapons is *still* not working and I don't know why. If anyone has ideas lemme know.
IMPORTANT NOTE: Merge #5561 before TMing this
Changelog:
Fixes the prebuilt guild smelter. It now has space OSHA compliant settings by default and hopefully should reduce the the number of adepts down disposals.
Fixes the desc if 9mm ball boxes. They  no longer declare to be non-lethal
Nerfs mukwah knocking them down to 300 health from 400. (way to chonky on new combat)
Nerfs slepnirs down to 350 from 550. (hypersonic speeds plus crazy health was making them pretty much guaranteed death)
Buffs lodge bolt lance projectiles. generally just higher damage.
=> Hopefully fixes lodge bolt lance and minor smelter fixes.

code/modules/mining/drilling/slab_mining.dm, code/modules/organs/internal/psionic.dm, code/modules/psionics/psion.dm
Reduces the spawns of ore nodes to about 30% for spawns for the slab
Makes it so psionic bounce gets reset to 0 rather then endlessly added
=> Tweaks spawn rates of ore in slab + psion fix

code/game/objects/random/rig.dm, code/modules/clothing/spacesuits/rig/rig.dm, code/modules/clothing/spacesuits/rig/suits/combat.dm, code/modules/clothing/spacesuits/rig/suits/light.dm, code/modules/clothing/spacesuits/rig/suits/merc.dm, code/modules/clothing/spacesuits/rig/suits/station.dm, code/modules/mob/living/living_defense.dm, code/modules/projectiles/guns/projectile/shotgun/buffalo.dm, code/modules/projectiles/guns/projectile/shotgun/swat.dm
Buffalo has 1.5 AP mod up from 0.8
specialized RIG modules are generally rarer and more expensive, the standard level of ablative armor has gone from 10 to 5(that is to say, they now provide an extra 5 destroyable armor instead of 10, as this was maybe a bit much. combat suits retain their high ablation value.)
Industrial RIG has retained high ablation and gained a bit of max ablative, given that it's slow and kinda rare. makes it good for miners, but maybe not ideal for combat.
SWAT may no longer be disassembled.
if your armor divisor somehow becomes negative, instead of returning a 1 it return a 0.001, meanuing it is no longer a good idea to accept a negative armor divisor as it will unironically be unable to penetrate even jackboot tier armor.
<details>
<summary> …
=> some combat PR balance tweaks

code/game/objects/random/rig.dm, code/game/objects/random/science.dm, code/modules/clothing/spacesuits/rig/rig.dm, code/modules/clothing/spacesuits/rig/suits/station.dm
AMI rig no longer has the same ablation value as the other insanely powerful suits.
ablative armor 'need fixing or not' readout now properly says when it's fully fixed.
AMI rig is no longer cheaper than the hazard suit while having comparable if not better performance. this suit will very likely get hit with the nerf stick in the future but for now this works.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fixes RIG ablative armor readout, nerfs AMI rig.

code/game/objects/items/stacks/medical_stacks/medical.dm, code/game/objects/items/stacks/medical_stacks/splint_stacks.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/organs/external/_external.dm
You may now always splint any robot, as splints are always useful - basically fixes a bug
FPBS chest for shrapnel or other imbedded items no longer can be damaged, basically always counted as walking and or splinted for mercy reasons - FPBs **often** in a single step would gain 4 damage on FPB heart and instantly die. This was not deemed fun or engaging content
=> splint fix and fpb mercy

code/game/jobs/job/church.dm, code/modules/surgery/autodoc.dm
<details>
<summary>
</summary>
<hr>
Vectors and Primes now have strength training (+10 ROB for Vectors, +15 for Primes, to match their VIG stat buff and help them be more well-rounded statwise).
Autodocs are now (almost) fully operational. They will now complete all operations that are selected. Mapped-in autodocs will (probably) still need to be rebuilt before they operate.
<hr>
</details>
:cl:
bugfix: Autodocs now properly finish all selected operations. Mapped autodocs will likely still need rebuilding before they work.
/:cl:
=> Autodoc Bugfix / Church Jobs Tweak

code/game/objects/effects/portals.dm
A quick one line change that should prevent Junk Field portal duds from happening. Tested locally on two occasions and it seems fine.
:cl: Toriate
fix: JTB portal should stop deleting itself when a mob crosses it before the stationside portal is generated.
/:cl:
=> Quick botch fix for JTB portals

code/modules/materials/material_sheets.dm
Wood planks now should have the icon back
=> Fixes an icon error

code/game/objects/items/weapons/tools/hammer.dm
both regular and greyson powered sledgehammers are now large instead of bulky. they thusly no longer fit in bags and get double tact. Foreman hammer remains untouched.
"CDB why" hearing that power sledges are seriously outpacing other forms of melee. 
"What about the chainsaw that shit is also OP as fuck" I have my eye on that too, but for now; this. 
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> nerfs power sledges

code/modules/projectiles/gun.dm, code/modules/projectiles/gun_firemode.dm, code/modules/projectiles/guns/energy/charge.dm, code/modules/projectiles/guns/projectile/automatic.dm
When dropping a gun it now will first thing unwield if wielded
When dropping a gun it now should forcefully delete the click checkers for firing said gun
This in theory should fix dropping guns and having them stick to you and fire from distance
=> Maybe fixes dropped phatom guns

code/datums/mob_stats.dm, code/modules/clothing/shoes/jobs.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm, code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
Herme shoes do to how slowdown works now no longer seemed to give you a speed boost even if you ran 10+ tiles 
It has been buffed accordingly to help off-set inhand item slowdown
Fixes negative stats not properly showing
Rez Sickness now slows you down rather then speeds you up
Fixes some cargo kegs spawning wrong
=> fixes tally issues + fixes some kegs + buffs herme shoes

code/modules/reagents/reagent_containers/food/snacks/meat.dm, maps/_HunterLodge/map/_Hunting_Lodge.dmm, maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Gives back runtime their food
Moves ians steak outside the fire locker
Removes debug CWJ debug plates from hunters
=> runtimes food and fix for ians

code/modules/mob/living/carbon/human/species/station/station.dm
Removes a very random 0.3 slowdown stat from SI synths. Not sure what this was..or why this was. But SI synths had a random unexplained debuff. Maybe a mixup meaning to give them a buff?? Regardless. its dumb. Mini PR fixing it. YEARS off my life crawling places....
Changelog: 
Tweak: Removes the very small slowdown debuff SI synths suffer for no reason.
=> Removes a *BRUH* unexpanded debuff from SI synths 

code/modules/cooking_with_jane/food_overrides.dm
Changed the numbers on the food descriptors to fill in the blanks that caused food to lack any descriptors at all. And changes a single letter in one of the descriptors, too.
<details>
<summary>
</summary>
<hr>
Did some tiny changes for the numbers to make sure there are no blanks. And removed a single letter and a space in one of the descriptors.
<hr>
</details>
:cl:
tweak: Changed the numbers that applied food descriptors to food.
del: " a"
/:cl:
=> Food descriptor fix

code/game/objects/items/weapons/storage/vendor_loot_boxes.dm, code/game/objects/random/oddities.dm
Bluecrosses now need to be mannaully spawned in via clicking a portal to drop the item
This is to stop ghosts and meta-gaming of what spawned where
=> antibluecross cheats

code/game/world.dm
This is to modify the HUB link from "https//\" to the link that we use to get to our discord from the wiki link. This is to hopefully avoid any confusion and allow players to easily locate our Discord. 
Kudos to plant from Discord finding this and bringing it to our attention! Thank you!
=> Generate Discord Link

code/game/turfs/flooring/flooring.dm, maps/__Nadezhda/area/_Nadezhda_areas.dm, maps/__Nadezhda/map/_Nadezhda_Colony.dmm
The court room is no more, it has been replaced with (for the time being) an arcade.
Moves the advanced arcade cabnet (vig gym) to new arcade
This also gives use to the rarely outside of now SI used gym equipment for BIO COG and MEC
But why?????
Are current laws and sop and everything does not support a courtroom, and its mere presence gaslights people into thinking that it would be used for legal issues or votes or really anything. 
dinner area has been generally relayed out to better look nice and fit within the space
halway jank curve has been flattened
church now has a small table section for prayer cards/candles as well as a mini flora area
Sadly the blue sofa area has been shrunk
New GP food vender by bar
Relayed out kitchen to be more spaceful + gives a custom vender board
=> replaces courtroom with arcade + general remapping of the bar/halway

.github/workflows/ci_suite.yml
Reverts sojourn-13/sojourn-station#5658
=> Revert "Bump actions/download-artifact from 3 to 4.1.7 in /.github/workflows"

code/game/objects/items/devices/organ_module/active/pouch.dm, code/modules/clothing/spacesuits/rig/rig.dm, code/modules/reagents/reagent_containers/food/cubes.dm
Fixes embedded ammo pouches being not in arms
Fixes Roach Cubes being unable expand do to lack of volume
Allows players to see the ablative armor of RIGs when examined
=> Cube+Pouch+Rig

code/game/objects/items/weapons/tools/pickaxe.dm, code/modules/mob/living/silicon/ai/ai.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
Mining cyborg can now do it's main function. Gives Janiborgs and Research borgs the ability to get the Arc welder.
<details>
<summary>
Gives the mining cyborgs a dedicated tool for mining which doesn't break and mines decently well. Also gives Janitor cyborgs and Research cyborgs the ability to get an Arc Welder Upgrade to do their jobs a little better. Reasoning for research borgs is that their nanopaste is finite and can't be used to repair borgs/FBP's en-masse. Additionally if they're repairing an exosuit their starting welding tool will quickly run out of fuel. As for janiborgs it's purely for sealing burrows, as the failrate of the omnitool is purposefully low and the need to refill the small welder coupled with the already low power efficiency make this a pure QOL upgrade. Not doing …
=> More love for borgs.

code/game/objects/items/weapons/storage/wallets.dm
Kinda goofy how a currency, albeit archaic, doesn't fit in a wallet. Remedies that.
=> G.P. Revolution (Lets wallets holds G.P. Yuan.)

code/__HELPERS/game.dm, code/game/machinery/doors/door.dm, code/game/objects/explosion.dm, code/modules/ameridian/ameridian_crystal.dm, code/modules/ameridian/ameridian_spire.dm, code/modules/mob/death.dm, code/modules/mob/living/carbon/superior_animal/ai.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/projectiles/projectile.dm, code/modules/sanity/sanity_mob.dm
Mob activation is now mostly based on line of sight rather then z-level
Mobs will now relise that as a matter of fact that synth walking around from the colony IS a likely a target, wow such progress.
Mobs will now do firing squads and still melee you if your dieing, as long as your awake and standing. 
Silly trace bullet stuff should no longer make blood affects and get logged endlessly
**maybe improves the mob target finding list a little??**
Some pre-approved commits to put on this pr are the following
`Wow Trilby your so cool and amazing`
`Woo I hate mob cheesing, this is fantastic!`
`I cant believe its not removed:tm` 
Some NOT approved commits are the following
`Rebase to virgo`
`This sucks`
`How does this impact game performance`
`Why`
Thank you.
=> The greatest NPC revolt as seen on TV

code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/core_implant/cruciform/rituals/priest.dm
<details>
<summary>
Improves the Divisor's enemy detection litany, fixes and buffs their divine smite, and gives them the speed boost litany that Lemniscates used to have. Gives Lemniscates a "holy boost" litany that only affects disciples, but boosts all stats rather than just half. Gives Primes/Crusaders a litany to send a Sending to all disciples.
</summary>
<hr>
Divisor enemy detection litany now tells the user the general "type" of enemy for each detection, as well as how many are within a "close" range of 7 tiles. It also now reveals cloaked deep-maint monsters within 7 tiles. The carrion detection will now actually trigger for a carrion that's outside a person.
Divisor's Divine Smite was fixed to not last a full 5 minutes, but the intended duration was buffed to 90 seconds from 30, …
=> Buffs Divisors, changes Lemniscates, gives utility litany to prime

code/game/objects/items/weapons/extinguisher.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
Gives borgs a new fire-b-gone that holds 3x the reagents, refills in a recharger and is faster at spraying. - This only applies to borgs that had fire-b-gone present in their kit rather then every borg type
=> fire fighting buff for borgs

code/game/jobs/job/blackshield.dm
<details>
<summary>
Aulvae have no discenrable reason to not be sergeants- lorewise. And they can be commanders anyways.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Aulvae can be Sergeants now
/:cl:
=> Allow slimes to be sergeants

code/game/jobs/job/civilian.dm
<details>
<summary>
</summary>
<hr>
Very simple change, makes it so there can be only one chef, and only one bartender. You might ask - why? It is because every chef sees the kitchen as their own. It's a ruthless world out there, and there can be only one who cooks. And- Two bartenders is just overkill, honestly.
<hr>
</details>
:cl:
tweak: changed the amount of job slots for cooks and bartenders from 2 to 1
/:cl:
=> Removal of a second chef and bartender slot

code/game/area/areas.dm, code/game/area/asteroid_areas.dm, maps/__Nadezhda/area/_Nadezhda_areas.dm
Fixes hivemind spawning in the mines, unknown areas and in the forest
Corrects many areas being wrongly counted as "ship area"
=> Area issues Corrections

maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm, maps/__Nadezhda/area/_Nadezhda_areas.dm, maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Essentially what it says on the tin, an almost complete bridge remodel. 
The Guild is proud to present: the new bridge!
**The bridge is now split into three primary areas: Council Halls, Offices & Emergency Sections.**
<hr>
_Event Hall - The Council meeting hall upstairs has been turned into a general-purpose area for Council day-to-day lives, and hosting events, featuring a small office to the south for paperworking needs!_ _**NOTE: YES, I KNOW THAT THE WALLS TO THE NORTH CAN BE SEEN FROM ABOVE, I FIXED THAT AFTER TAKING THE SCREENSHOT :3**_
_The Conference Room - the room downstairs, featuring a desk for a steward to sit at and a secure and out of the way location for holding those important votes._
<hr>
_Premier and Steward's Office - The offices have been merged, giving them a common …
=> Bridge Remodel!

code/modules/client/preference_setup/loadout/lists/accessories.dm
What this PR does is add a colorable drop straps using the drop straps in the code, without taking up a new /accessory/ just mainly a adding in COLORABLE to another drop straps instead of coding in colorable on the regular one as the regular one is a basis for the rest of the accessories. 
:cl:
add: colorable drop straps
/:cl:
=> Accessory Addition: colorable drop straps

code/modules/mob/living/carbon/human/human.dm
Allows humans (players) that are stack on other mobs or objects to be able to use a new verb "Move to top". Requested by chef doggo
=> Human layering button

code/game/gamemodes/events/hivemind_controller.dm, code/game/objects/structures/burrows.dm, code/modules/hivemind/mobs.dm
Hivemind admin pannel now lets you properly see mobs lists
Hivemind admin pannel now lets you teleport to each master node of an active hivemind
Hivemind admin pannel now lets you add (and thus subtract) evo points to active hiveminds
Hivemind borrowing has been tweaked: By default hivemind will borrow only with non-maints borrows unless otherwise set.
Fixes mechiver null issue leading to endless converting by misstake
=> Hivemind buffs(*)

code/modules/client/preference_setup/loadout/lists/factionblackshield.dm
<details>
<summary>
Blackshield can once again use the BDU.
Who put the gear datum path as the same as the marshal one 😭 
</summary>
<hr>
<hr>
</details>
:cl:
fix: allow the BS BDU to be loadout selectable again.
/:cl:
=> Make BS-BDU selectable in loadout

code/game/machinery/vending.dm, code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
Makes it so that psionic items cant be placed inside custom venders.
=> fixes vender exploit

code/modules/mob/living/simple_animal/friendly/farm_animals.dm
switches a mushrooms to a plump helmets. Seems like a skill issue to me but Trilby asked. ¯\_(ツ)_/¯
Changelog:
Slight adjustment to the Amerethi hog desc to be more specific on mushroom type.
=> More specific hog desc

code/modules/projectiles/guns/projectile/automatic/greasegun.dm, code/modules/projectiles/guns/projectile/automatic/sts.dm
Adds wooden grip to the list of accepted grips on the greasegun frame and texan to the resultvars so texan SMGs can be disassembled and reassembled properly.
Changes the bakelite grip on sawn down STS rifles to wood in order to match the current version of the full rifle.
=> Gun parts fixes

code/__HELPERS/mobs.dm
<details>
<summary>
Fixes the bug about head covers in storage slots stopping implanters. though i don't think this is the best solution, because headwear (and some other gear) may be able to be placed in empty belt slots as well, which can prove an issue. would be good to overhaul how body-part checks are done in the future
</summary>
<hr>
<hr>
</details>
:cl:
fix: Storage slots don't strike bodypart cover checks
/:cl:
=> Allow items in storage slots to not hassle body cover checks

code/modules/mob/living/carbon/human/human_organs.dm
For normal limbs: Holding any medical item regardless of pain will stay in hand I.e you will no longer drop gauze well trying to self gauze do to pain
For robotic limbs: Holding cable coil or nanopaste will stay in hand regardless of malfunction or lim damage
The above does not applied to stuns, nerve strikes or other interactions that forcedrop items
=> Medical items death grip

maps/__Nadezhda/map/_Nadezhda_Colony.dmm
This PR adds in two more lockers to the church and moves the chiken coop into a more viewable area instead of tucked away by the church
:cl:
add: new vector room and new chicken coop
/:cl:
=> Map Addition: New Vector Room and Chiken Coop Moved

code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm, code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm, code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm, code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
Alright, so first and foremost the Dayanji station (Secondary Greyson Station) has had it's tool/part stock replaced with the special Greyson Zhengdou voidsuit (priced at 25k) and the GP Greyson air tank (priced at 2k)
This is because I personally believe it allows LS to stomp on what should be the Guild's and Soteria's toes way too easily, given it's just a matter of nabbing some plat from the mines and using the SOM phone to immediately phone in the station. I'm planning on tossing in more misc. Greyson goodies in the near future, but this is a decent start.
The roach meat offers have been audited, generally a 1/3 to 1/2 reduction in value depending on the specific meat. Given Armitage allows players to buy roach cubes obscenely cheaply, this was long overdue. Also fixes jager meat …
=> Roach Meat Audit + GP station change (And Misc Station tweaks)

code/modules/clothing/shoes/magboots.dm, code/modules/clothing/spacesuits/void/merc.dm, code/modules/clothing/spacesuits/void/station.dm, code/modules/trade/datums/trade_stations_presets/1-common/botany.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm, code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
Throws a price onto most voidsuits to make them not have an unpolished "Unset price"  vibe to the suit-up tab.
Adds magboots to suit up, kinda goofy how you couldn't buy relatively vital EVA equipment from the station that specializes in EVA equipment.
Nerfs both modified tool offers on the botany station, makes it so you don't have to use an expansion slot on mini-hoes to actually get enough space to sell them. Payment for the tool adjusted accordingly.
Adds military magboots to Arau, as the station is currently lackluster in epic 'Operative gear', seems fitting to be sold here.
=> Suits and Boots

code/game/objects/items/weapons/tools/simple_weapons.dm
<details>
<summary>
Both the renderslayer and the foreman's sledge tend to be pretty equal in stats (~5 hits to kill a nightmare stalker, for one example). This gives the renderslayer the ability to break secure doors like the sledge, intending to make both options more of a visual/stylistic (or in technicalities, minor combat) choices rather than a choice between two good weapons with one having a clear utility bonus
</summary>
<hr>
<hr>
</details>
:cl:
balance: Lets renderslayer sword break secure doors.
/:cl:
=> Makes both foreman melee options more equivalent

code/game/objects/items/weapons/weaponry.dm, code/modules/clothing/spacesuits/rig/modules/ninja.dm, code/modules/mob/mob_defines.dm
<details>
<summary>
Rig-based teleporters now leave bluespace dust where they jump from, and where they jump to. Also takes a few seconds to spool up before jump. Can reduce it if its too large of a timer. Let me know if its a big nerf, because the intent is to make it to be an access tool rather than a `use annoyingly in combat` tool.
E-nets now actually buckle and lock-down mobs.
This is part 1 of 2. Part 2'll be out when the invisibility module stops kicking me in the nuts
</summary>
<hr>
<hr>
</details>
:cl:
balance: Rig-Tele leaves behind bluespace dust. Also takes a few seconds to spool up before phase.
fix: E-nets now buckle people.
/:cl:
=> Balance rigtele, fix energy nets

code/datums/setup_option/backgrounds/origin_synthetic.dm
Makes all synth backrounds more robust in giving stats to help minimize minmaxing 
Blacklists "\"Long-Haul\" Body Chassis" from outsider do to being one of O'Conners designs
=> big stat buffs for synths

code/modules/mob/mob_grab_specials.dm
closes #5739 
Firefighter slam now properly checks for dense objects before throwing someone backwards
=> Fixes firefighter slam interactions with dense objects

code/game/machinery/cryopod.dm
<details>
<summary>
Use role's alt title instead of assigned role when cryoing
</summary>
<hr>
This way the titles used in the announcement are the same in joining and leaving. So I won't join as nurse and leave as doctor.
<hr>
</details>
:cl:
fix: Use role's alt title instead of assigned role when cryoing
/:cl:
=> Use role's alt title instead of assigned role when cryoing

code/modules/cooking_with_jane/recipes/recipe.dm, code/modules/mob/inventory.dm, code/modules/psionics/psion_powers/gear_summoning_powers.dm, maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Gas masks no longer make sanity proof if you rapily take them off and on
fixes a bad pipe in bridge
fixes lack of a room having piping and atmos alarm
fixes psionic shields spawning inside players giving them free endless glowing 
fixes a cooking with jane step error with salt
closes #5732
closes #5692
closes #5672
=> fixes gas masks and bridge pipes

code/datums/setup_option/backgrounds/origin_synthetic.dm
Related to triliby PR that was uploaded earlier this week. Edits the church's combat model to not have a dump stat bringing it in line with other models because currently there is no way to even get COG high enough with other stats to get it to be a bypass stat correctly. Moves the twenty COG to ROB and VIG putting it in line with the unbranded veteran model and weaker then the Standard combat synth models.
=> Updates synth buffs.

code/game/objects/effects/decals/crayon.dm
Sanity damage from crayon drawings such as arrows, unpowered runes and letters has been reduced to 0.04 from 4
this is a 100 devide as 4 is on par with a megafuna like a kaizer roach.
Sadly this makes it harder for folks to inspiration room gene without needing about 16 more blood splatters to replace per rune
=> Lowers crayon sanity damage

code/modules/clothing/spacesuits/rig/modules/computer.dm, code/modules/clothing/spacesuits/rig/suits/station.dm
Small PR with some minor changes. addition of power sinks to the suits was at Chefs request and I don't particularly care about it. Buuut I think its fair that the people who make the power get it on tap.
The buffs to the sinks I hold strong on. They fucking suck for how rare of a module they are and now have to compete with cell hot-swapping.
Changes the name of guild RIGs for something more lore correct. We are not Technomancers. _sadly_
Buffs power sinks from 40KW per cycle to a entire 100kw per cycle. Approximately 3 minutes to fully charge a 14000L.
Buffs both the GMs RIG and adepts RIGs to have power sinks round start.
=> better power sink and guilg rig

code/game/objects/items/weapons/material/material_weapons.dm, code/modules/research/xenoarchaeology/finds/finds_eguns.dm
Materal weapons such as katana's claymores and swords now shouldnt randomly reset themselfs to 0 damage
Fixes being able to add gunmods uselessly to xenoarch weapons
=> fixes some materal weapons and xenoarch weapons

code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm, code/modules/research/designs/greyson.dm, code/modules/research/nodes/greyson.dm
It's been a long time coming, This PR was meant to be done months ago. It reduces the research points needed by 37500 because it removes the research tree for the unmaker. The Greyson portable shield was moved to the glass widow branch. Unmakers can still be purchased from cargo, Found at the end of the gauntlet and now are a rare drop from the Greyson Titan robots that can be found at the end of the gauntlet or the boss rooms in the Greyson's outpost.
The node was left untouched as things will be added too it later for a replacement, but spiriting needs to be done. Greyson oxygen tank will most likely added to this tree as well in the future.
=> Soteria Buff one out of one hundred.

code/modules/clothing/suits/armor.dm
<details>
<summary>
Gives the Marshal's default webbing vest lower body protection. This vest, when upgraded into a full-body vest, loses its webbing anyway.
Removing the webbed armor's slowdown was never going to make the full-body vest obsolete; the full-body vest still is more useful overall but webbed armor is able to hold a 4 extra small items for those willing to risk their limbs. Webbed Operator Armor can be upgraded into a full-body vest, but it **loses** the webbing if you do this. 
There was no need to remove half of its protective region; the point is for the player to choose between a bit of extra storage space, or limb protection when choosing between the webbed armor or tactical unit armor. Making the webbed vest even less usable as armor is overcorrecting for an issue no …
=> Marshal Vest has LOWER_TORSO tag

code/game/machinery/smelter.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/closets/fitness.dm, code/game/objects/structures/crates_lockers/closets/gimmick.dm, code/game/objects/structures/crates_lockers/closets/job_closets.dm, code/game/objects/structures/crates_lockers/closets/l3closet.dm, code/game/objects/structures/crates_lockers/closets/maint_loot.dm, code/game/objects/structures/crates_lockers/closets/malfunction.dm, code/game/objects/structures/crates_lockers/closets/onestar.dm, code/game/objects/structures/crates_lockers/closets/secure/bar.dm, code/game/objects/structures/crates_lockers/closets/secure/cargo.dm, code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm, code/game/objects/structures/crates_lockers/closets/secure/engineering.dm, code/game/objects/structures/crates_lockers/closets/secure/freezer.dm, code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm, code/game/objects/structures/crates_lockers/closets/secure/medical.dm, code/game/objects/structures/crates_lockers/closets/secure/militia.dm, code/game/objects/structures/crates_lockers/closets/secure/personal/subtypes.dm, code/game/objects/structures/crates_lockers/closets/secure/scientist.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/game/objects/structures/crates_lockers/closets/syndicate.dm, code/game/objects/structures/crates_lockers/closets/utility_closets.dm, code/game/objects/structures/crates_lockers/closets/walllocker.dm, code/game/objects/structures/crates_lockers/closets/wardrobe.dm, code/game/objects/structures/crates_lockers/crates.dm, code/modules/mining/mine_items.dm, maps/_DeepForest/map/_Beast_Cave.dmm, maps/_DeepForest/map/_Deep_Forest.dmm
Commie Bunker in the underground has been cut in half with size
Lima-09 Has been shrinked
Deletes **many** decals in ruins and replaces them with maints flooring
Lockers now on spawn dont populate contents, rather any interactions with them will do so now, this should reduce item amounts by a lot
Removes some walls from zoo and gives zoo more loot in the old viro lab
=> map reduction and locker post spawning

code/modules/mob/language/euro.dm, code/modules/mob/language/outsider.dm
Back when I made the german language for eris (my very first coding contribution to SS13 ever) I had no real idea about quality standards and how languages will be perceived ingame over a long time.
When I saw people speaking eurolang/kriosan a while back i physically cringed on how hard it was to read because I added way too many nouns. For a more fluent and coherent reading experience when someone speaks eurolang, i added a lot more german filler words to offset the capitalized and incoherent words and added and corrected the animal specific things from Kriosan and Eurolang and vice-versa.
The next person I see writing "Hundt", "Hunden" (fuck you "Teufelhunden" propagandists for making that word up and coining it for future generations to spell "Teufelshunde" or "Höllenhunde" wrong) or …
=> update Eurolang and Kriosan with more filler words for more a coherent reading experience

code/modules/reagents/reagents/food-Drinks.dm
adds the umami drink tag to Kvass, Bloody Mary, Bilk and Changeling Sting because who realizes an insight desire for "savoury drink" was only able to be sated with tomato juice or soy sauce, which you wont drink ingame. Now its in 2 proper drinks/cocktails.
Removes the mention of russia from Kvass because old terran countries arent generally a thing anymore and kvass is slavic overall.
=> Add Umami Tags to drinks

code/game/objects/items/weapons/nt_melee.dm, code/modules/clothing/head/helmet.dm, code/modules/clothing/head/jobs.dm, code/modules/clothing/head/misc.dm, code/modules/clothing/head/misc_special.dm, code/modules/clothing/masks/gasmask.dm, code/modules/clothing/shoes/jobs.dm, code/modules/clothing/suits/armor.dm, code/modules/clothing/suits/greatcoat.dm, code/modules/clothing/suits/jobs.dm
Rephrases some church item descriptions to declutter them and have proper phrasing/explanation.
Adds the damage modifier against psionic mobs and hivemind from the vexilar forceblade to the crusader sword as well.
Fixes the prime hood alternate style "saint" laurel from turning you bald (being bald in exchange for being a saint is a bad tradeoff).
=> Church fixes and flavour rephrasing

code/modules/client/preference_setup/loadout/lists/general.dm
this adds an empty glass case to the loadout so you have something to put your implants in. previously, you could spawn with 3 generic implants, an implanter and a tracking implant on top of that, but not the case. enjoy your gimmicks without having to hunt a vendor down
:cl:
add: empty implant case in loadout selection
/:cl:
=> adds empty implant case to loadout

code/game/machinery/vendor/cloathing.dm, code/game/objects/items/weapons/storage/costume.dm
This PR just basically adds the centurion gear into a box just incase if someone wants to larp as space centurion / roman for halloween.
:cl:
add: LARP roman box to vending and loadout
/:cl:
=> Costume Box Addition: Live Action Roleplay Roman Gear

code/modules/client/preference_setup/loadout/lists/footwear.dm
I thought the boots fucked but after seeing them ingame, I get why they were removed. This codersprite would need a due makeover.
Removing for aesthetic reasons.
=> removes blacksilk boots from loadout

code/modules/client/preference_setup/loadout/lists/accessories.dm, code/modules/client/preference_setup/loadout/lists/factionblackshield.dm
this adds shoulderboards to the blackshield loadout selection screen. they go:
- blank (cadet/volunteer)
- trooper
- corpsman
- sergeant
- commander
i have left out the larp ranks like sergeant major and major. During testing it came to my attention that the sprites are mid, but now that they're available regularly maybe they can be improved at some point. Have fun looking sharp the 1 time per year you need to use your dress uniform #Blackshield #Human #SpriteQueen #Diva #Tea
i have also added a selection of proper blackshield patches, each with their own sprite (mob sprites soonTM), to the general accessories setup. anyone can use them as they can with the normal blackshield patch, shouldn't be any different. 
:cl:
add: shoulderboards added to loadout selection
add: more patches in …
=> adds shoulderboards & patches to loadout

code/datums/craft/recipes/guild.dm, code/game/objects/random/oddities.dm, code/modules/projectiles/guns/energy/laser/abdicator.dm, code/modules/projectiles/guns/energy/laser/sunrise.dm, code/modules/projectiles/guns/energy/projectile/railgun.dm, code/modules/projectiles/guns/projectile/automatic/battlerifle.dm, code/modules/projectiles/guns/projectile/automatic/dp.dm, code/modules/projectiles/guns/projectile/automatic/lmg.dm, code/modules/projectiles/projectile/bullettypes.dm
Got too lazy fixing prior PR's chemistry sprite port, because it would require adding new sprites to get it to work with code and all. Plus didn't seem wanted.
Anyway, does basically the same thing as this PR minus the chemistry sprite change.
https://github.com/sojourn-13/sojourn-station/pull/5773
Only other changes done that are new:
- Made DP-27 able to be scoped.
- Made DP-27 on-par with the AK-47 damage wise, and raised it's pen by 0.1. Its recoil was also lowered by 0.1
- Lowered DP-27 cost by 15 plasteel, raised wood cost. It no longer costs more than a Takeshi or other LMG to print by over 10 plasteel.
- Heroic is now able to be scoped; it's an HMG benefiting from bracing so I see no reason it shouldn't be allowed to benefit from it.
DP-27 fixes were prompted by hearing feedback …
=> Gun Fixes & Misc Stuff (Second Attempt)

code/modules/reagents/metabolism.dm
NSA now properly accounts for negative numbers.
NSA math has been tweaked a bit to be a slower build up
=> Fixes a nsa bug

code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_upgrades.dm
Fixes tall borgs when reset from death to become invisable
Fixes the `Do you like this icon` pop up on default borgs
Fixes resetting a dead borg health hud icon staying blue and broken.
=> robot restart fixes

code/modules/mob/living/carbon/human/human_defense.dm
So, remember how the armor system and armor values got reworked?
Embed chance calculation was not reworked with that. So, this meant you were FAR more likely than before to have shrapnel embed. While I do actually kinda like that shrapnel is a bit deadly now, it was really silly that even 9mm had a decently high chance to shrapnel even though some of the best armor.
:cl:
fixes: Shrapnel calculation
/:cl:
=> Embed Chance Fix

code/modules/mob/living/simple_animal/hostile/big.dm, code/modules/projectiles/guns/projectile/automatic/greasegun.dm
Swaps the grip order in the code to make grease guns and texans construct properly when building them.
Changes giant snake to the pond faction like all the small snakes, preventing it from going on a rampage and eating all fellow snakes at round start.
=> Greasegun/Texan/Giant Snake Fix

code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm, code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm, code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm, maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Guild has regained its Recycler to help crush down unrefrined scrap into blah blah delete items
Guild belt has been adjusted to account for self-made smelters, with a belt section to be turned off to help reduce item movement lag
Reduces many cargo trade stations budget and spawn amounts for trash, roach cubes, and other animals including xenobio spawn crates.
=> Nerfs cargo and some anti-lag mapping

code/modules/clothing/suits/labcoat.dm
The armor stats of bio and bomb are instantly overwritten in the lab coat.
=> Labcoat overwrites own armor stats

code/modules/genetics/machinery/genetics_cloner.dm
Updates the wording surrounding embryos in the Xenofauna Cloning Vat to be pro-choice friendly. Being purposefully unsettling for the sake of humor is one thing, not using proper terminology over embryos is another.
=> Janetics Embryo PR

code/modules/dungeons/junk_tractor_beam.dm
Reverts sojourn-13/sojourn-station#5020
After a long think about this and how it affectively made a colonist dungeon end up being completed in 12-30
After the strides in optimization and decluttering of runtimes this should be less bad maybe
=> Revert "junk field nerf, sorry ya'll."

modular_sojourn/task_master/tasks.dm
Finding some idle time means I felt like touching up a few typos in the Tasks folder. There's still a few sentences overall that could stand to be rephrased, but for the meantime, this just polishes what's already there.
While we were still recovering from the book burning of Supper to Super Majority, someone lit the library on fire.
It's been blow after blow, how will we ever recover?
Maybe we won't.
=> Task typo corrections

code/game/machinery/vendor/weapon_kit_vendors.dm, code/game/objects/items/weapons/storage/hardcases.dm
Suggested by Wilson
Allows all vouchers and kits for blackshield and marshals to pick a Second Secondary. Why would you do this is for duel wielding or if you are objectively picking wrong options.
=> Allows marshals and blackshield TWO Secondaries

code/game/objects/items/toys.dm, code/modules/reagents/reagent_containers/food/snacks/burger.dm, code/modules/trade/datums/trade_stations_presets/1-common/factio.dm, code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm, code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm, code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
Adds a dipping bird sub-item. Just a changed name and description for fluff. Adds this new item to the Ghost Kitchen station.
Adds a variety of office supplies to a new tab in the Ghost Kitchen station.
Sets a price for all the food Dionis sells, reeling in the meta of ordering 100's of 2 credit burgers for Church biomass. Also adds some novelty burgers to the Dionis secret inventory to flesh out a chronically anemic listing.
Adds the 9mm Economy disk to the Factorio expanded inventory.
Adds a basic clothing tab to the Absolute ships.
Sets a high price for Supermatters from Zarya, hopefully resulting in no more, if not heavily reduced random instances of supermatters being sent unsolicited to unsuspecting Cargotechs.
Edit, Also fixes a typo in the burger .DM
=> Lonestar-ering 2

code/game/objects/random/booze.dm, code/game/objects/random/cloth.dm, code/game/objects/random/food.dm, code/game/objects/random/junk.dm, code/game/objects/random/packs.dm, code/game/objects/random/prosthesis.dm, code/game/objects/random/purerandom.dm, code/modules/scrap/scrap.dm, sojourn-station.dme
Allow canned drinks to spawn (not department drinks) Allows mugs/glasses/ect to spawn
Tweaks cloth/weapons pile spawns to be more in line with what they are Tweaks spawns of food stuffs
Allows robotic lims to more naturally spawn in piles
increases gun piles loot spawn amount (i.e how many items are inside them)
=> way more random and more items

code/game/objects/items/devices/text_to_speech.dm, code/game/objects/items/weapons/storage/wallets.dm
Makes the TTS device smaller so that it can fit in a wallet
Squeaky wheel gets the grease. Someone asked for TTS devices to fit in a wallet, so I made a PR for that
<hr>
Swaps the TTS Device size from 'small' to 'tiny'
<hr>
</details>
:cl:
tweak: Made TTS Devices tiny, instead of small.
/:cl:
=> Makes TTS device 'Tiny' instead of small

code/__DEFINES/weapons.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/projectiles/projectile/bullettypes.dm
Lowers sharpnal embed odds by 10%
shrapnel now deals way less organ damage
shrapnel now has a internal pity system that every other same action jostle that triggers it will nullify another trigger affectively halfling to 2/3s unlucky shrapnel movements
shrapnel now can be fully blocked by using good armor
projectiles wound mult now affect how likely you are to get shrapnel
Raises HP embed mult to be more able to embed
this heavily incentives waring real armor
=> shrapnel tweaks

code/modules/clothing/gloves/miscellaneous.dm, code/modules/clothing/shoes/magboots.dm, code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
Fixes a typo in the Artificers insulated gloves dec.
Gives the military magboots a set of protection values that differs from the standard magboots. More physical protection, less rad protection.
Adds swat gloves to the Hellcat armor tab.
=>  Boots and Gloves

code/modules/power/antimatter/control.dm
Players can now chose to disable the antimatter announcement without needing admin powers.
=> allows players to disable the antimatter annoucer

code/modules/projectiles/gun.dm, code/modules/projectiles/guns/projectile/automatic/mac.dm, code/modules/projectiles/guns/projectile/automatic/texan.dm, nano/templates/weapon_stats.tmpl
Texan has been giving 0.5 more armor mult to help it deal affective damage against soft-armor.
Mac has traded 0.2 armor mult for a (1).75 gain in post-armor damage mult making it affective against unarmored/low armored mobs that group up such as roaches
Basically makes the two have the use cases that they used to have before the gun rework:
Texan is meant to deal conistant but lower damage to the Mac that has more damage
Also adds the wound mult adder stat to gun UI's
=> Mac and Texan buffs

code/modules/psionics/ear.dm
Fixes an itty bitty mistake :)
<details>
<summary>
</summary>
<hr>
Literally adds a single letter "h" to fix the entire EAR machine thingy (thank Trilby for actually finding the issue and telling me how to fix it)
<hr>
</details>
:cl:
fix: fixed the third EAR machine pillar to accept resonances
/:cl:
=> EGO EAR machine thingy fix.dm

code/modules/clothing/spacesuits/rig/rig.dm
Rigs no longer should randomly no longer protect the user from heat
=> Fixes rig pieces randomly losing temp/shock protection

code/__DEFINES/_hydro_setup.dm, code/datums/craft/recipes/misc.dm, code/game/objects/items/devices/scanners/plant.dm, code/modules/hydroponics/seed.dm, code/modules/hydroponics/seed_datums.dm, code/modules/hydroponics/seed_gene_presets.dm, code/modules/hydroponics/trays/tray.dm, code/modules/hydroponics/trays/tray_process.dm, code/modules/mob/living/silicon/robot/gripper.dm, code/modules/research/experiment.dm, code/modules/trade/datums/trade_stations_presets/1-common/botany.dm, modular_sojourn/brewing_datums.dm
Borgs can now properly craft cement bags, and other consumer tab items
Making cement bags is easyer
Added grass and wheat as random "weeds" that can overgrown trays
Adds more reagent affects on plants
Removed age punishment for harvesting plants
Plant trays now if stacked ontop of one another will be harmed greatly
Same plants that are planted around one another will now give boosts
Adds a new trait that removes the need to be same type to give boosts to other plants
Almost if not all seeds now have a crop that it likes to be grown around.
Adds both chem producer and the new trait to science research for points (forgot to do this last time)
=> hydrotweaks: more regnant interactions + borg qol + balance tweaks

code/modules/projectiles/projectile/bullettypes.dm
Increases 6.5, 408, and 7.5 damages a small bit to make them feeeel more impactful.
gives 5 more damage to 10mm caseless
=> Requested balance changes

code/modules/psionics/psion_powers/healing_powers.dm
Fixes a wrongly named psi power
<details>
<summary>
</summary>
<hr>
Literally just changes a single name of a power that was most likely mistakingly left unedited after copypasting, lol
<hr>
</details>
:cl:
tweak: changed single psi power's name
/:cl:
=> Tiny name fix

code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm, code/modules/psionics/psionic_items/psi_catalysts.dm
<details>
<summary>
</summary>
<hr>
Makes small changes here and there to increase the odds of getting the fancy catalysts from ponderous and flesh behemoth. As someone who spent HOURS hunting for these silly-ass cubes, it's currently very infuriating with how rare these can be, ESPECIALLY the flesh behemoth ones. I tried to stay within reason while tweaking the values, and I'll be sure to see if they're fair next excursion.
<hr>
</details>
:cl:
tweak: drop rates of mob-exclusive catalysts
/:cl:
=> Mob-exclusive catalyst drop changes

code/modules/mob/living/carbon/slime/powers.dm, code/modules/mob/living/carbon/slime/slime.dm, code/modules/projectiles/guns/energy/misc/slimegun.dm, code/modules/projectiles/projectile/special.dm
Slimes when shot with slime gun, now die again
Slimes now cant feed on dead bodies at all
Slimes deal clone damage rather then toxins to make them a little less lethal but more lasting in harm
Increases Slime feeding burn and clone damage 
Updates the slime gun desc to say "simple" slime lifeforms to hint that it infact dosnt harm slime players.
=> fixes slime gun and makes feeding less exploitable

maps/__Nadezhda/map/_Nadezhda_Colony.dmm
closes https://github.com/sojourn-13/sojourn-station/issues/5934
Fixes psyc door only be accessible to psychiatrist rather then general medical
=> psyc door fix

code/modules/organs/internal/nerves.dm
Changes the nerve health to be SMALL instead of TINY, effectively bringing it up to par with Muscles.
The damage thresholds are untouched, so theoretically they're still more likely to accumulate a wound at lesser damages, but I don't exactly know how the wound code works.
Getting unlucky with a laser shot (Especially with how most lasers punch through ablative armor anyways, or the subpar quality of ablation on DEDICATED ablation gear) can lead to frankly an incredibly frustrating death spiral of a nerve accumulating a single organ wound, and just dying within minutes, leading to necrosis and everything that follows.
So in Summary:
What?
Nerves go from 4 to 6 HP, moving them past a very important damage threshold.
Why?
Given how a SINGLE burn or bruise on a limb's nerves can render a …
=> Nerve buff

code/modules/economy/Accounts_DB.dm, nano/templates/accounts_terminal.tmpl
Allows Premiers/BST/Centcom accessed cards to see account pins in the Account Database machine.
It also prints the account pin on the paper.
I figure if you're accessing accounts at that level you're trusted with the Pin to begin with, and the printed papers should be treated as highly confidential anyways.
I'm scared of NanoUI.
=> Account Database Tweak

code/__HELPERS/text.dm
<details>
<summary>
</summary>
<hr>
Makes linebreaks actually break the lines.
I'm too small-brained to work with TGUI, so it only works with NanoUI (Since you can actually shift-enter with it, while with TGUI shift-enter just posts the message)
Textwallers rejoice	
<hr>
</details>
=> Actually adds linebreaks to /me

nano/templates/autodoc_capitalism.tmpl, tgui/packages/tgui/interfaces/OreBox.tsx
By WeNeedMorePhoron
fix: Non-Excelsior Autodoc no longer try to fix non-existent internal damage on external organs and will fix internal damage on internal organs properly now.
tweak: Orebox can accept custom ejection amount up to 600 (5 stacks), has a eject 120 (full stack) short cut, has a wider window and now sorts the minerals alphabetically to minimize unnecessary UI shift when you eject any ores from it.
=> Auto Doc Fix and Ore Box UI

code/game/objects/items/oddities_faction.dm, code/modules/admin/admin.dm, code/modules/hydroponics/grown_predefined.dm, code/modules/hydroponics/seed.dm, code/modules/hydroponics/spreading/spreading_response.dm, code/modules/hydroponics/trays/tray.dm
<details>
<summary>
</summary>
<hr>
Another minor gripe PR (The best reason for PRs)
I was mildly annoyed at being unable to harvest from trays and soil plots at a distance, but understood the reasoning why it was disabled.
Therefore, I made harvesting from trays, even with telekinesis, put it on the same turf as the tray. Also works with farmbots, making automated farms infinitely neater.
I tested every scenario where harvesting occurs I could find, but if something pops up, throw a brick at me, I'll try to fix it
<hr>
</details>
=> Re-enables telekinetic hydroponics harvesting, removes the plant teleportation that it previously caused

maps/__Nadezhda/map/_Nadezhda_Colony.dmm
<details>
<summary>
</summary>
<hr>
For some unholy reason, the dorms lobby/hallway sofas were NW/NE/SW/SE directional sofa corners, which, in game, made them look very weird. Now they're better.
I looked through the colony map and didn't find any other broken sofas. If there are any, do tell
<hr>
</details>
=> Fixes some sofas in dorms

code/game/objects/effects/mines.dm, code/game/objects/items/weapons/traps.dm, code/modules/tips_and_tricks/gameplay.dm
You can now click a bear trap with rods or a gripper (for borgs) to disarm it, this is slightly faster
You can now disarm spider traps (colletion of webs, dark shadow) by clicking on it with meat, this prevents the stun
Fixes a tip being labled wrong and never properly being triggered
Adds two new tips and tricks explaining these mechanics
=> Ways to disable traps

code/modules/trade/datums/_trade_station.dm
Reverts a port of a single bug fix as the error it causes is greater then the runtime it solved
More or less fixes cargo being unable to order things
=> reverts changes to cargo goods list

code/game/gamemodes/events/hivemind_invasion.dm, code/game/machinery/jukebox.dm, code/game/objects/items/weapons/grenades/flashbang.dm, code/modules/hivemind/machines.dm, code/modules/hivemind/mobs.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoRobust.dm, code/modules/mob/living/living.dm, code/modules/mob/living/simple_animal/hostile/huntersprey.dm, code/modules/projectiles/projectile/projectilegrenades.dm
Standerises ear protection to be consistent and internally logical
Nerfs hivemind health for mobs 
Nerfs some hivemind stuctures
Minimum requirement of hivemind combative pop is raised to 3, to prevent low pop stuggles
Nerfs hivemind stun locking with weaken
=> Updates ear protection and hivemind nerfs

code/__DEFINES/items.dm, code/datums/movement/mob.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/human_recoil.dm, code/modules/projectiles/gun.dm
Requested by wilson
Increases recoil when moving
Picking up guns gives a massive amount of recoil, as does equipping them from bags/holster/pocket
Walking now gives recoil, but less then running
=> movement recoil

code/modules/organs/internal/internal_wounds/organic.dm, code/modules/organs/internal/internal_wounds/robotic.dm
Bumps down the max severity of individual internal wounds caused by external damage (brute/burn) to 2, instead of 5.
Doesn't touch poisoning, infections, radiation/tumors, etc.
Mostly meant to tune it from being a borderline death sentence for the smaller organs (Nerves, vessels, etc.) by an unlucky dice roll to something that feels like the player is accumulating deep wounds from overextending into combat.
Will have the secondary effect of making surgeries in the OR being less about constantly replacing dead tiny organs in people, and make chemical treatments more viable. 
Field surgeries will be less frequently in a  "Shit out of luck" situation due to this hopefully resulting in less dead organs.
Bone injuries aren't nerfed either, as demonstrated by the screenshots.
=> Organic and Robotic internal injuries nerf

code/game/objects/items.dm, code/game/objects/items/stacks/throwing.dm, code/modules/mob/living/living_defense.dm
Fixes when an item misses it was silent when it was meant to be playing a sound
Adds framework to allow every item to have uniquic pickup, dropped and thrown sounds
=> framework for sounds

code/modules/mob/living/carbon/human/life.dm
When humans are on fire and are alive, awake, and feel pain, will sometimes forcefully scream to give the user feedback that they are dieing from fire damage
=> fire screaming

code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
Glowing roaches no longer runtime when using its fancy glow attack against targets that cant ware glasses
=> fixes a roach runtime on equipment checks

code/__DEFINES/chemistry.dm, code/_onclick/click.dm, code/modules/reagents/reagents.dm, code/modules/reagents/reagents/drugs.dm, code/modules/reagents/reagents/other.dm, code/modules/reagents/reagents/race.dm, code/modules/reagents/reagents/stims.dm, code/modules/reagents/reagents/toxins.dm
Removes some race-chem withdraws that where non functional
Fixes withdraws for every chemical that has them
massively lowers sanity damage from chem addition stage 3 and 4 so that way you dont sanity spiral as hard for not constantly smoking 8 packs a day
Makes it so Boxer, Utra violence and mence slightly increase attack speed when used, on withdraw slightly reduce attack speed
Makes it so party drops slightly reduce attack speed
=> Attack cooldown chem and fixes withdraws

code/__DEFINES/chemistry.dm, code/modules/organs/blood.dm, code/modules/organs/external/_external.dm, code/modules/organs/internal/internal_wounds/_internal_wound.dm, code/modules/organs/internal/internal_wounds/eyes.dm, code/modules/organs/internal/internal_wounds/organic.dm, code/modules/organs/internal/internal_wounds/sanity.dm, code/modules/organs/internal/internal_wounds/slime.dm, code/modules/organs/organ_description.dm, code/modules/reagents/reagents/medicine.dm, code/modules/reagents/recipes/recipes.dm
Tweaks readability of wound damage progression
Wounds no longer progress if the limb they are in, if said limb is almost fully healed
Adds a new chemical for science to make that stops wound progression and stabilizes people (inaproval stabilize affect)
Having poor circulation lowers bleeding out
Having slower pulse lowers bleeding out
Resting, or being buckled to a bed lowers bleeding out
Having fast pulse increases bleeding out
Having more blood then normal increases bleed out
Many types of wounds such as infections, radiation, toxins ect progress even in a healthy limb, but still can be delayed by new stabilizer chemical
=> Organ damage delaying

code/game/objects/objs.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/guns/_projectile.dm, code/modules/projectiles/guns/launcher.dm, code/modules/projectiles/guns/matter/launcher.dm, code/modules/projectiles/projectile.dm, code/modules/projectiles/projectile/bullets.dm
Removes unneeded vars that didnt really work as intented for nerfing gun damage
Removes being able to handle_suicide with guns, if you want to self end you got to use more then one round or bleed out slowly!
Cleans up muzzle flashes and prevents a few exploits with them do to how they worked before
Muzzle flashes now leave a small gas decal on the ground, this is done for lighting reasons and looks nicer then having it attached onto the gun itself 
Cleans up dual wielding mechanics to be less wierd to use: Basically if the gun and off hand can both dual wield both will fire basically at the same time rather then delayed
Removes a *second* clumy trigger in gun checks, this was clearly a bug and not intented to be able to have clumy trigger twice
Allows bullets, lasers and ecta to have cone …
=> Cleans up gun code a little and removes feature

code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm, code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm, code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm, code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm, code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
Removes plain meat from being sold from most stations.
Spider and Many variants of roach meat are no longer offers on stations, their chems in bottles are now what are sought after.
Lowers the value of the Bicaridine and Kelotane offers, adds plenty of more advanced medicine offers to be sought out by competent chemists.
Buffs the offers of many Guild crafted components and weapons in Hellcat.
Assigns prices to the animal crates listings in Faith.
Faith no longer wants slabs of meat, they want cutlets instead.
Slightly nerfed Dionis meat offer, gave them roach chem offers (Flavoring for Cht'Mant clientele, or something.)
Armitage chems bumped up in price. They're still lower than the offers, so they could stand to be bumped up even more in the future if this proves problematic.
=> Yet Another Cargo Tweaking (I'm tweaking)

code/modules/ameridian/ameridian_crystal.dm, code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
By R4D6
Fixes a wrong proc call when harvesting ameridian crystal
By Trilby
Removes a un-needed timer and less proc calls for when a golem is shot.
=> Slightly better code for golems

modular_sojourn/brewing_datums.dm
For a few brewing recipies the name harebell was used over the real name of harebells, causing these to be unuseable
:cl:
/:cl:
=> Fixes bad crop data

code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm, code/modules/projectiles/projectile/bullettypes.dm
Data star no longer gets stuck using only teller if above 6000 data and not using k-amps
Data star now properly scales its armor based on what is attacking it rather then mile stones
Fixes a issue with data star if stunned early or weakened will be in a perma stunned mode
Fixes data star being bullied by tesla turrets
Fixes a small infi loop bug with relay shot if two targets are immortal
=> Data star fixes as well as buffs

code/datums/perks/job.dm, code/modules/projectiles/guns/projectile/boltgun.dm
Makes bolt gun perk toggle.
Adds some more logic to prevent runtimes if nonusers fire a bolt gun (such as procalls)
=> Bolt gun toggleable
